### ISSUE TITLE
Google Pixel with Android 10 and Bubble for Libre

### ISSUE THREAD

**Issue by westermarck** [NightscoutFoundation/xDrip#1001]
After upgrading the Google Pixel to Android 10 we use for xdrip+ we're unable to connect to the Bubble.

The Status screen shows **Connection Status** as _Not Connected_. We tried upgrading to `15a2977-2019.08.06` and `5c91be6-2019.08.20` but that did'nt help either.

I have gone through the different issues regarding configuration of the MiaoMiao (e.g. NightscoutFoundation/xDrip#486 and NightscoutFoundation/xDrip#609) since the configuration of the Bubble seems to be similar to MiaoMiao. Prior to upgrading to Android 10 the same configuration worked fine.

I'm also unable to find any suspicious connection errors in the log besides that the Collector seems to be restarting due to reception issues.

![download_20190906_224516_2](https://user-images.githubusercontent.com/592737/64471040-6f81ad80-d14c-11e9-9209-1365f851e2c0.png)

Any help or suggestions on how to proceed would be greatly appreciated.

**Comment by reedhuish** [comment]
Dittos on this.

I have Xdrip (latest version) and MiaoMiao and Freestyle Libre.

Was working perfectly on my Android 9 phone - Pixel 3 XL

UNTIL....I upgraded to the Android 10 version last night.

Now, the bluetooth can see the MiaoMiao bluetooth reader, but cannot get any readings from it.

The NFC capture still works, all the other settings still work.

But bluetooth communication in Android 10 doesn't work.

My full logs and posting for my MiaoMiao / Libre on Android 10 are here:
https://github.com/NightscoutFoundation/xDrip/issues/996

**Comment by elrufoelrufo** [comment]
I have the same problem with Pixel 3a. 

I found a workaround:   

> Forget Bluetooth device in xdrip. 
> Go to Settings - Apps - See all Apps - (3 dots on top right corner) - Show system apps - Bluetooth - Delete Data 
> 
> Then you can try to connect with your miao miao again. 


Hope it helps you. 


Thanks. Regards.

**Comment by westermarck** [comment]
Yes the workaround also fixed my issue. Thanks @elrufoelrufo!

**Comment by reedhuish** [comment]
this workaround also worked for me (on a Pixel 3 XL and Android 10)

It is GOOD TO BE BACK with CGM monitoring.

Thank you.

**Comment by loop2016** [comment]
Thanks for the workaround. Now I regret that I already downgraded back to Android 9. Thanks nonetheless.

**Comment by elrufoelrufo** [comment]
To avoid the workaround, please, check the following in Settings - Less common settings - Bluetooth settings and check if you have everything like in the screenshot attached. Then after reboot the device, bluetooth should connect automatically. 

![Bluetooth_Settings](https://user-images.githubusercontent.com/14137306/66328836-b4f0f080-e92d-11e9-94c0-a8e23ba1cace.jpeg)

I hope it helps.

**Comment by reedhuish** [comment]
Thumbs up to elrufoelrufo

Yesterday I put on a new Libre US 10-day 

I made the changes that elrufoelrufo suggested

And my Pixel 3 XL (running Android 10) worked detected the new Libre and worked perfectly

Thank you elrufoelrufo
