### ISSUE TITLE
Samsung Note10 Plus problems

### ISSUE THREAD

**Issue by marc-gaub** [NightscoutFoundation/xDrip#1004]
Samsung Note 10 Plus stops receiving data from G6 after a few readings. After restarting the collector, it works again for a few readings.
On the G6 status, the phone service stats is "Scanning xx:xx", and the Bluetooth Link stays in connecting.

**Comment by detellis** [comment]
Hi, I have Note 10 Plus too. I had an issue with it at first.
Currently have 100% capture by changing this setting:
Glose GATT on BLE disconnect - ON

I also opened the Dexcom app to clear a battery warning as G6 transmitter is now ~90 days old. I believe that may sometimes cause a loss of data, not sure as transmitters last a while, but towards transmitter end of life it I find it necessary to clear the battery warning in the Dexcom app before Xdrip can work flawlessly.

**Comment by marc-gaub** [comment]
> Hi, I have Note 10 Plus too. I had that exact same issue with it at first.
> Currently have 100% capture by changing this setting:
> Glose GATT on BLE disconnect - ON
> 
> I also opened the Dexcom app to clear a battery warning as G6 transmitter is now ~90 days old. I believe that may sometimes cause a loss of data, not sure as transmitters last a while, but towards transmitter end of life it I find it necessary to clear the battery warning in the Dexcom app before Xdrip can work flawlessly.

Hi, thank you for your suggestion. It's working for a few hours without problems.

**Comment by Chaimwax** [comment]
I tried with brand new sensor and transmitter. It took 4 attempts just to get to connect. It lasted about a before losing signal. About 2 hours later it did the same thing. After several hours of no readings, I deleted xdrip from my phone
