### ISSUE TITLE
Amazfit GTR 

### ISSUE THREAD

**Issue by josecarlosE** [NightscoutFoundation/xDrip#1007]
Hi
When is going to be avaliable syncing with Amazfit GTR?
Thanks!!!!!

**Comment by Klaus3d3** [comment]
right after you coded a plugin for it.

**Comment by Benwahhhh** [comment]
hello
i'm just a user, and need it too .. i have activated the Amazfit Service on Xdrip, but nothing s showing on the watch
would it be possible to replace the Step counter that appears on almost every watchface ? and put the BG Value instead ?

thanks !

**Comment by Klaus3d3** [comment]
No, but maybe it could be done with the weather widget, since theese data are coming from the watch.
But i don't have any of this incompatible watches to test it.
Thinking of getting a stratos 3 when its available. Maybe i can get it working with it in low power mode wich should be the same os as the GTR/GTS have. But this needs time

**Comment by leoussis** [comment]
Hi, just started using xdrip with libre and miao miao and wanted to get a amazfit gtr.
I know that only stratos and pace are compatible in order to have the graph to a watchface but i was wondering if the gtr/gts can at least get the notifications about the glucose readings just like i have them on the phone.
Stratos and pace are too bulky for my small wrist.

**Comment by agniabakush** [comment]
Hi! Have any progress with gtr?

**Comment by agniabakush** [comment]
Why no GTR support? I understand that no possibility to make grafic but just make watchface with BG vidget instead weather?

**Comment by agniabakush** [comment]
> No, but maybe it could be done with the weather widget, since theese data are coming from the watch.
> But i don't have any of this incompatible watches to test it.
> Thinking of getting a stratos 3 when its available. Maybe i can get it working with it in low power mode wich should be the same os as the GTR/GTS have. But this needs time

Did you buy stratos already? Is there any progress for GTR please?

**Comment by agniabakush** [comment]
Hello. What news about GTR and Xdrip ?

**Comment by agniabakush** [comment]
> > No, but maybe it could be done with the weather widget, since theese data are coming from the watch.
> > But i don't have any of this incompatible watches to test it.
> > Thinking of getting a stratos 3 when its available. Maybe i can get it working with it in low power mode wich should be the same os as the GTR/GTS have. But this needs time
> 
> Did you buy stratos already? Is there any progress for GTR please?

Any news available?

**Comment by balrog20pl** [comment]
Hi. are there any news with amazfit GTR? I hope it will work soon:)

**Comment by balrog20pl** [comment]
How is it possible that xdrip can send data to miband but not to amazfit GTR?

**Comment by agniabakush** [comment]
Hi, folks! Any news about GTR? MIband 4,5 already work with xdrip.

**Comment by agniabakush** [comment]
Hello. I got connection GTR and xdrip via miband menu. Put MAC of my GTR and restarted watch.
![Screenshot_20200923-222245](https://user-images.githubusercontent.com/33312884/94105012-93e91e80-fe62-11ea-8373-63a4b9933593.png)

**Comment by agniabakush** [comment]
Now I have notifications every 5 min. If someone could make watchscreen, be able pull data to show graphic?

**Comment by agniabakush** [comment]
![Uploading IMG_20200924_124415_228.jpg…]()

**Comment by agniabakush** [comment]
![Uploading IMG_20200924_124415_228.jpg…]()

**Comment by Klaus3d3** [comment]
I would guess that a similar way like for miband should be possible. as soon as the gtr2 is available, i will into it.

**Comment by agniabakush** [comment]
![Uploading Screenshot_20200924-130858~2.png…]()

**Comment by balrog20pl** [comment]
I hope the amazfit GTR will work :D

**Comment by agniabakush** [comment]
> I would guess that a similar way like for miband should be possible. as soon as the gtr2 is available, i will into it.

It means GTR also will be available to show bg?

**Comment by agniabakush** [comment]
![Screenshot_20200924-130858~2](https://user-images.githubusercontent.com/33312884/94108127-f34a2d00-fe68-11ea-8e2e-c943bd62b7a5.png)

**Comment by balrog20pl** [comment]
Hmm my gtr could not connect with xdrip

**Comment by Klaus3d3** [comment]
> 
> 
> > I would guess that a similar way like for miband should be possible. as soon as the gtr2 is available, i will into it.
> 
> It means GTR also will be available to show bg? But I never heard about gtr2

GTR2 and GTS2 were resently announced by huami.
I will not promise, that it will be working in the future. but i'm pretty sure. Mi band watchface is just a standard watchface with a picture inside. This picture is updated ever 5min and contains the graph and the value. So changing the background picture every 5min should also work with gtr/gtr2.

**Comment by agniabakush** [comment]
Great!!!

**Comment by balrog20pl** [comment]
![Screenshot_20200924-095653_xDrip+](https://user-images.githubusercontent.com/46726104/94117319-5bd6e100-fe4c-11ea-84bd-1c685deab83c.jpg)
Xdrip show me miband no gtr and cant send any notyfication

**Comment by balrog20pl** [comment]
Ok I put mac adres manualy. Now xdrip see my GTR but is not connected
![Uploading Screenshot_20200924-101223_xDrip+.jpg…]()

**Comment by agniabakush** [comment]
You should restart watches

**Comment by balrog20pl** [comment]
After restart xdrip show my that my gtr is not authorizated. But i install newest zepp app from freemyband

**Comment by balrog20pl** [comment]
![Uploading Screenshot_20200924-103322_xDrip+.jpg…]()

**Comment by balrog20pl** [comment]
My GTR show my this info:

Update failed, update the application to the latest version for data synchronization

**Comment by balrog20pl** [comment]
which version of zepp and xdrip are you using?

**Comment by agniabakush** [comment]
> which version of zepp and xdrip are you using?

I use now latest nightly xdrip (01.10.2020) and Notify. I have no Zepp

**Comment by ftp841** [comment]
balrog20pl 

> ¿Qué versión de zepp y xdrip estás usando?

I have the same problem like you, have you solved this?

**Comment by lkraleva** [comment]
Hope we will have a solution soon. I don't have programming skills. What is needed this to be processed future?

**Comment by tolot27** [comment]
If someone is willing to spend a device to the core developer, this would speed it up, significantly.

**Comment by lkraleva** [comment]
A gtr watch is 120euro. Do we have an option for donation?

**Comment by mcurly** [comment]
I'm interested as well. Can I help in testing for instance? Currently I have spare time ...

**Comment by tolot27** [comment]
No one posted a log so far. That would be really helpful. Please also enable extra logging `Amazfitservice:v,NewDataObserver:v'.

**Comment by Klaus3d3** [comment]
> 
> 
> No one posted a log so far. That would be really helpful. Please also enable extra logging `Amazfitservice:v,NewDataObserver:v'.

The AmazfitService ist not made for GTR and GTS. Ist only for Pace and Stratos. These watches also run an Android based OS.

A possible way to use the gtr could be the same way as the miband. Here a simple background picture is generated inside xDrip and sent to the band as part as a watchface.
I'm prety sure this could be possible with gtr, too. But it will need a different watchface as the one for the miband.
You should contact the developer of the miband "plugin" within xdrip.

**Comment by mhv75** [comment]
I think you need to install the Amazfit version of notify and fitness, and try if that works

**Comment by agniabakush** [comment]
Have any prorgess with GTR?

**Comment by agniabakush** [comment]
![Screenshot_2021-02-15-02-21-38-246_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/33312884/107886808-e53e9b00-6f34-11eb-80f5-6e6039774700.jpg)
As I understand now I need watchface.bin and watchface.png as on Miband, but just for GTR compatible

**Comment by agniabakush** [comment]
Could someone create these files for testing?

**Comment by dirceusemighini** [comment]
> ![Screenshot_2021-02-15-02-21-38-246_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/33312884/107886808-e53e9b00-6f34-11eb-80f5-6e6039774700.jpg)
> As I understand now I need watchface.bin and watchface.png as on Miband, but just for GTR compatible to put them to xdrip folder?

Where you able to post the graph to your watch? I just got my gtr2 mini.

**Comment by agniabakush** [comment]
What graph you mean?

**Comment by dirceusemighini** [comment]
By graph I mean if you were able to display the BG curve, and other infos like, arrow, how many it's going up/down, as a watchface.

**Comment by agniabakush** [comment]
No, I'm not

**Comment by twinko** [comment]
> 
> 
> I would guess that a similar way like for miband should be possible. as soon as the gtr2 is available, i will into it.

Hey @Klaus3d3 did you had the chance to have a look at the GTR2? 

bigdigtal already released some early work for GTR ( first GTR release https://www.patreon.com/posts/im-ready-to-gtr-47426327)and also GTR2 (https://github.com/bigdigital/py_amazfit_tools). Sadly the GTR is not the best watch to go along with xdrip. But according to bigdigtals comments the GTR2 looks more suitable:

> I've spend some time on  reverse-engineering GTR2(also GTS2 and GTS2e) watchface format and made a first watchface editor tool for this watch https://amazfitwatchfaces.com/forum/viewtopic.php?f=29&t=1798  
> It looks like second generation will suits better for xdrip needs. At least they allow disabling system vibration which happens after every watch face uploading .  
> I only need to reverse-engineer the Bluetooth communication protocol for this watch. So most possibly xdrip will support these watch models too.

**Comment by agniabakush** [comment]
![IMG_20210315_152036](https://user-images.githubusercontent.com/33312884/111123585-1ba61f00-85a2-11eb-8b80-483b70eab24f.jpg)
It's really cool!!!

**Comment by mcurly** [comment]
@agniabakush that's brilliant!

So you were able to somehow solve this issue.

Care to share your findings?

Thank you in advance!

**Comment by balrog20pl** [comment]
Is that work on gtr v1?

**Comment by mcurly** [comment]
@balrog20pl it looks like so  GTR (v. 1)

In my case I am delving with a GTR2...

But it looks very promising!

**Comment by agniabakush** [comment]
Guys, it works. I have used info from msg above mine. Just follow links

**Comment by mcurly** [comment]
> Guys, it works. I have used info from msg Twinko above mine. Just follow links

Ok. I'm "trying to trace back" your successful path, and need to check out these questions:

You just edited a custom gtr2 watch face correct?

I'm assuming you "cropped out" and "padded" that custom watch face to the needed scenario (displaying the xDrip main interface, correct)?

And finally putting that customized and repacked watch face onto the xDrip folder that is already available for that purpose... (Right?)

Thanks again for your help!

**Comment by twinko** [comment]
> 
> 
> > Guys, it works. I have used info from msg Twinko above mine. Just follow links
> 
> Ok. I'm "trying to trace back" your successful path, and need to check out these questions:
> 
> You just edited a custom gtr2 watch face correct?
> 
> I'm assuming you "cropped out" and "padded" that custom watch face to the needed scenario (displaying the xDrip main interface, correct)?
> 
> And finally putting that customized and repacked watch face onto the xDrip folder that is already available for that purpose... (Right?)
> 
> Thanks again for your help!

Please reade more than1 post above. agniabakush is only taking abouzt gtr (V1). 
If you want  a summary of the actual development for gtr2 see my post from 12th of march 2021

**Comment by balrog20pl** [comment]
It work perfectly :) thans so much
![20210315_183932](https://user-images.githubusercontent.com/46726104/111198702-28397000-85c0-11eb-8fd5-e2fd6caa8048.jpg)

**Comment by lkraleva** [comment]
Thank you very much guys! i'm very happy i will be able to see my daughter BG on my watch. Unfortunately i'm very newbie, i have downloaded python, pillow, and files from github. Where i can find the watchface files now? Even i can't find the xdrip folder on my phone.

**Comment by twinko** [comment]
@lkraleva 

see my post from 12th of march 2021. Follow the link i posted and read the description, artem linked instructions on how to install it.
https://www.patreon.com/posts/im-ready-to-gtr-47426327

**Comment by lkraleva** [comment]
Thanks, i was able to install it on my watch and works great. Followed same steps for my wife watch, which is GTR 42 glitter edition. And is failing to install the watchface (it's authenticated, but can't install it). Is this works only on 47 or?

**Comment by agniabakush** [comment]
> Thanks, i was able to install it on my watch and works great. Followed same steps for my wife watch, which is GTR 42 glitter edition. And is failing to install the watchface (it's authenticated, but can't install it). Is this works only on 47 or?

I believe that you should create watchface for 42mm. And put it in xdrip folder

**Comment by dirceusemighini** [comment]
Does this can be applied to gts2 mini, with some changes to generate a square face? Or in this watch it's a different system?
In freemyband website it does not cite the gts2 mini, just the gts2.

**Comment by twinko** [comment]
@lkraleva @dirceusemighini 
read the comments on the linked patreon page. Moreover notice the headline, does it say "also supported: gts2, gts2 mini and GTR 42"?

**Comment by lkraleva** [comment]
> > Thanks, i was able to install it on my watch and works great. Followed same steps for my wife watch, which is GTR 42 glitter edition. And is failing to install the watchface (it's authenticated, but can't install it). Is this works only on 47 or?
> 
> I believe that you should create watchface for 42mm. And put it in xdrip folder

I've tried that, i have used the below software to convert the 47 whatchface to 42. 
https://amazfitwatchfaces.com/forum/viewtopic.php?t=1076&start=10

But still is failing to install it. Not sure where i'm mistaken....

**Comment by agniabakush** [comment]
Hello folks! Who knows is it possible to switch off vibration after face uploaded?

**Comment by twinko** [comment]
hey guys looks like gtr2 and gtr2e development startet. perhaps more patreons would help artem:)
https://www.patreon.com/posts/51313261

**Comment by dirceusemighini** [comment]
> > > Thanks, i was able to install it on my watch and works great. Followed same steps for my wife watch, which is GTR 42 glitter edition. And is failing to install the watchface (it's authenticated, but can't install it). Is this works only on 47 or?
> > 
> > 
> > I believe that you should create watchface for 42mm. And put it in xdrip folder
> 
> I've tried that, i have used the below software to convert the 47 whatchface to 42.
> https://amazfitwatchfaces.com/forum/viewtopic.php?t=1076&start=10
> 
> But still is failing to install it. Not sure where i'm mistaken....



> @lkraleva @dirceusemighini
> read the comments on the linked patreon page. Moreover notice the headline, does it say "also supported: gts2, gts2 mini and GTR 42"?

I was able to integrate my gts2 mini, but it's missing the watchface. Any help on that would be appreciated, as far as I understood I should use the amazfitwatchfaces to design a new one.
I'm a bit confused to which source code should my changes be based on, this Nightscout, bigdigital Xdrip-miband, Xdrip+, can anyone help me to finding this?

**Comment by twinko** [comment]
> > @lkraleva @dirceusemighini
> > read the comments on the linked patreon page. Moreover notice the headline, does it say "also supported: gts2, gts2 mini and GTR 42"?
> 
> I was able to integrate my gts2 mini, but it's missing the watchface. Any help on that would be appreciated, as far as I understood I should use the amazfitwatchfaces to design a new one.
> I'm a bit confused to which source code should my changes be based on, this Nightscout, bigdigital Xdrip-miband, Xdrip+, can anyone help me to finding this?

what do you mean by integrate? did you coded support for the mini?
afaik thereis no support for the mini and no watchface generator
supported devices: https://www.patreon.com/posts/53034931

**Comment by dirceusemighini** [comment]
> > > @lkraleva @dirceusemighini
> > > read the comments on the linked patreon page. Moreover notice the headline, does it say "also supported: gts2, gts2 mini and GTR 42"?
> > 
> > 
> > I was able to integrate my gts2 mini, but it's missing the watchface. Any help on that would be appreciated, as far as I understood I should use the amazfitwatchfaces to design a new one.
> > I'm a bit confused to which source code should my changes be based on, this Nightscout, bigdigital Xdrip-miband, Xdrip+, can anyone help me to finding this?
> 
> what do you mean by integrate? did you coded support for the mini?
> afaik thereis no support for the mini and no watchface generator
> supported devices: https://www.patreon.com/posts/53034931

Yes I've coded a support for mini, I've used the  bigdigital / xDrip-miband repository.
I started to look for this this weekend and yesterday I was able to do it. I can now receive alarms and other things from xdrip, I can also see my heart rate at xdrip, but I'm not sure if that is the right place to get the code to do so. I saw at his blog that GTR is supported, also BIP, but I haven't seen this watches watchfaces there.
I was planning to try to use BIP watchface as mini and BIP resolution are close o each other.
The watchface isn't working due to the lack of it, I've seen that I can design an watchface for it, using huami tools, but I don't have a clue on how do I have to do it.

**Comment by twinko** [comment]
> 
> 
> > > > @lkraleva @dirceusemighini
> > > > read the comments on the linked patreon page. Moreover notice the headline, does it say "also supported: gts2, gts2 mini and GTR 42"?
> > > 
> > > 
> > > I was able to integrate my gts2 mini, but it's missing the watchface. Any help on that would be appreciated, as far as I understood I should use the amazfitwatchfaces to design a new one.
> > > I'm a bit confused to which source code should my changes be based on, this Nightscout, bigdigital Xdrip-miband, Xdrip+, can anyone help me to finding this?
> > 
> > 
> > what do you mean by integrate? did you coded support for the mini?
> > afaik thereis no support for the mini and no watchface generator
> > supported devices: https://www.patreon.com/posts/53034931
> 
> Yes I've coded a support for mini, I've used the bigdigital / xDrip-miband repository.
> I started to look for this this weekend and yesterday I was able to do it. I can now receive alarms and other things from xdrip, I can also see my heart rate at xdrip, but I'm not sure if that is the right place to get the code to do so. I saw at his blog that GTR is supported, also BIP, but I haven't seen this watches watchfaces there.
> I was planning to try to use BIP watchface as mini and BIP resolution are close o each other.
> The watchface isn't working due to the lack of it, I've seen that I can design an watchface for it, using huami tools, but I don't have a clue on how do I have to do it.

Read the answere from Artem to this the post of Jesus Perez Riuz in this patreon: https://www.patreon.com/posts/xdrip-update-v0-53034931?utm_medium=clipboard_copy&utm_source=copy_to_clipboard&utm_campaign=postshare

**Comment by dircsem** [comment]
@twinko It's now possible do design watchfaces for gts2-mini, although I'm not a professional on it, it's possible using huami dev tools here:
https://dev.huami.com/watchface/index.html
![photo_2021-07-30_15-09-44](https://user-images.githubusercontent.com/2041058/127694538-c2112913-982a-4636-ae0b-bc4abc964c0b.jpg)
By the beauty of it you can conclude that this is custom made, and it's not available at any store. ;)
Using this tool, it only export an .bin file, looking at it's header it seems that it's like miband5 header, but I'm not sure how can I define the header size.
I've tried to use it as a custom watchface but it's not working yet.
I've seen other people asking for this integration, and I can commit my code to the github, but I'm not sure if this need to be done here at this repository, or at @bigdigital xdrip repository. Is the Artem code merged here?

**Comment by twinko** [comment]
@dircsem You should definitly talk to Artem!

**Comment by dircsem** [comment]
@twinko I've seen that you are helping a lot with gtr whatfaces, and is close to him. Artem is @bigdigital  right? Is here a good place to talk to him, or do he have another preferred way?

**Comment by twinko** [comment]
@dircsem i would recommend opening an issue here: https://github.com/bigdigital/xDrip-miband/issues

**Comment by Navid200** [comment]
Consolidated all watch support requests: https://github.com/NightscoutFoundation/xDrip/issues/1872
