### ISSUE TITLE
Wearable widgets not updating screen

### ISSUE THREAD

**Issue by marshall10488** [NightscoutFoundation/xDrip#1011]
So I have miao miao linked to xdrip and that all seems to be working fine. Even getting alerts through. I have wearable widgets on phone (samsung s9) and galaxy watch but the widget doesnt seem to constantly update u less I open the wearable widgets app on my phone. Have I missed a setting somewhere?

**Comment by goochman55** [comment]
I had the same problem. Forst I went to battery maintenance and checked allow background activity under settings/apps/wearable widgets/battery. Also there is an option to turn off optomise battery usage. This keeps the app fromep going to sleep

**Comment by marshall10488** [comment]
That's exactly it. Funny thing is earlier that day I did have a thought that maybe the battery optimisation was causing it but disnt know how to change individual apps. Thank you very much.
