### ISSUE TITLE
Bluetooth not connecting to G6 transmitter

### ISSUE THREAD

**Issue by IsaacRoitman** [NightscoutFoundation/xDrip#1013]
Bluetooth is working on Pixel 3a XL for all BT devices, but xDrip+ is unable to connect to the transmitter.  

Logs show "No valid timestamp stored for transmitter: 8GEBY1" repeatedly.

**Comment by jamorham** [comment]
Which version are you using? Please update at least to the latest Alpha channel release.

**Comment by IsaacRoitman** [comment]
Hi JoH, thanks, I think it's related to a faulty transmitter.  Contacted Dexcom for a replacement (not connecting to G6 receiver also).
