### ISSUE TITLE
Xdrip only using one calibration for calibration line

### ISSUE THREAD

**Issue by BradleyPJ** [NightscoutFoundation/xDrip#1014]
https://media.discordapp.net/attachments/257580365529481217/622498520070488065/Screenshot_20190914-192634.jpg?width=380&height=676

had some issues with calibrations this morning where it wouldn't take any calibrations had to restart  calibration then the line of best fit seems to have broken

**Comment by BradleyPJ** [comment]
https://cdn.discordapp.com/attachments/257580365529481217/622862077429678100/Screenshot_20190915-193111.jpg

it appears to only be using the latest calibration for the line of best fit

**Comment by jamorham** [comment]
What type of sensor are you using?

**Comment by BradleyPJ** [comment]
Freestyle Libre 1 with MiaoMiao 1. Uninstalled the app last night and reinstalled and that worked

**Comment by Navid200** [comment]
@BradleyPJ Would you please close this as it seems you solved the problem?
Thanks
