### ISSUE TITLE
duplicate treatments

### ISSUE THREAD

**Issue by gempickfordwaugh** [NightscoutFoundation/xDrip#102]
xdrip+ is adding two entries to careportal, one listed as xdrip (what I chose to list xdrip+ app as) and one listed as blank.  One is of the type of entry it is (e.g. meal bolus) and one is just a note.
![double reporting](https://cloud.githubusercontent.com/assets/17012342/24993617/0e16acde-201f-11e7-9382-e8720e936ea1.jpg)

First time I've recorded an issue so please let me know what further info you need.

**Comment by jamorham** [comment]
Can you use the System Status menu item and tell me the version code of xDrip that you are using and reporting this bug with?

Thanks

**Comment by gempickfordwaugh** [comment]
It's 673462a-2017.01.20 code 1701201513

Although it happened occasionally with a previous version, but this is
consistently all the time now.

**Comment by jamorham** [comment]
Okay I think this may be a bug already fixed, can you switch the update channel to Alpha in the Update Settings section and apply the offered update and let me know if that resolves the issue? Thanks

**Comment by gempickfordwaugh** [comment]
Yes and no. For the test input i did, it only went in once. 😊 But for the
treatments previously entered by pebble they're showing up as duplicates in
xdrip+ but not in careportal! (And don't panic, the 55 units was a test
input and the 3.9 is a compression low, they just happen to coincide at the
same time!)

**Comment by jamorham** [comment]
Going forward do you think the issue is resolved now that you are running the new version?

**Comment by gempickfordwaugh** [comment]
Sorry, thought I'd replied earlier.  Yes, the issue I raised is resolved.
Thank you :-)

**Comment by jamorham** [comment]
Okay I will mark this issue closed. Thanks for testing.
