### ISSUE TITLE
Libre OOP algorithm no data / missed signal

### ISSUE THREAD

**Issue by ph1l-l** [NightscoutFoundation/xDrip#1020]
Hi, I'm new to using xDrip+ but have it working well with a Libre 14 day sensor, MiaoMiao 2 and Samsung Note 9 (also sending glucose data to watch), the problem starts when I switch to using the out of process Libre algorithm. When selected it will simply stop showing any new data and show a signal missed message. Once deselected it will begin working again.

I'm currently using xDrip-plus-20190907-66c8a5a.apk.

**Comment by tzachi-dar** [comment]
Is this US 14 days sensors?

After you install libreoop does it show algorithm worked correctly?

**Comment by ph1l-l** [comment]
No it's the UK version Libre 1 sensor.

I downloaded it and ran the create_apk.cmd but when I try to install the libreoopalgorithm.apk it says app not installed. I must have missed something out somehow.

**Comment by tzachi-dar** [comment]
Do you have Android studio installed?

בתאריך יום א׳, 22 בספט׳ 2019, 00:26, מאת ph1l-l ‏<notifications@github.com>:

**Comment by ph1l-l** [comment]
No, I tried to install the apk from my phone.

**Comment by tzachi-dar** [comment]
you should have android studio installed on the computer that is creating
the apk.

**Comment by ph1l-l** [comment]
Ok I see, I thought that was for a different apk altogether.

It's getting late now so I will try again tomorrow and let you know what happens, thank you.

**Comment by ph1l-l** [comment]
Thank you for your help, it's working as it should now. Readings are the same as libre and updates just as regularly.

**Comment by ph1l-l** [comment]
I started a new sensor yesterday and I've noticed the reading are now not the same as the libre reader. At the moment they are about 1.0 higher on the librelink app. 

I'm not sure what could have happened, I did the same thing as last time.

**Comment by tzachi-dar** [comment]
I think that the issue will be resolved in a day or so. Are you using the new OOP algorithm?

**Comment by ph1l-l** [comment]
I'm not sure if there is a newer one but the oop app says version 2bb4958-service-2018.08.26 and I'm using that on the xdrip version mentioned in the first message. It was working fine up until I changed sensor

**Comment by tzachi-dar** [comment]
If you have another phone, can you try installing xDrip and new oop from: https://github.com/tzachi-dar/LibreOOPAlgorithm#how-to-build-for-us-sensors-and-maybe-even-germany-and-other-countries and see if this changes anything. 
Just use manual scan.
I would not do changes with the primary phone as the chance of this working is small.

**Comment by ph1l-l** [comment]
This is the only android phone I have unfortunately. Is this able to work with the UK sensors as well?

**Comment by tzachi-dar** [comment]
It should, but I have never tried this.

בתאריך יום ו׳, 4 באוק׳ 2019, 16:52, מאת ph1l-l ‏<notifications@github.com>:

**Comment by ph1l-l** [comment]
I might try this if the problem persists, thank you

**Comment by ph1l-l** [comment]
Could this be because I didn't use the 'stop sensor' option on the menu? I just removed it and put a new one on. I've only been using xdrip for 2 weeks so this is the first time I've changed a sensor with it

**Comment by ph1l-l** [comment]
After reinstalling xdrip and the oop apk then setting it up as a new sensor it doesn't seem to have made a difference. I'll let you know if anything changes

**Comment by Navid200** [comment]
@ph1l-l Would you please close this issue if it has been resolved?
If not, would you please use the support channels?
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks
