### ISSUE TITLE
Feature Request: add xDrip+ Sync Follower to SourceWizard on first page

### ISSUE THREAD

**Issue by k2s** [NightscoutFoundation/xDrip#1027]
It is not possible to select `xDrip+ Sync Follower` in data source wizard. It is not on first page and it is not nested in other.

I suggest to add it to the fist wizard page, under `Others`.

Selecting this item should set xDrip hardware source to `xDrip+ Sync Follower` and start `ActivityDisplayQrcodeBinding`.

**Comment by Navid200** [comment]
@k2s Would you please update this?
Has it been resolved with more recent releases?

**Comment by Navid200** [comment]
We are asking people to use xDrip as is if they can.
We are asking people to use work-arounds instead of asking for nice-to-have features.
If you like to reopen this, you can.  But, I suggest you provide a good reason why this is necessary.

**Comment by Navid200** [comment]
xDrip Sync is now one of the options in Source Wizard as of the 2025.06.20 release.
