### ISSUE TITLE
BUG: G6 Calibration Issue

### ISSUE THREAD

**Issue by definitivequestion** [NightscoutFoundation/xDrip#1029]
I'm sorry I can't provide more specifics right now, but after ending up in the ER with severe hypoglycemic symptoms I have decided to switch back to the official Dexcom app for awhile. Here is what happened. My previous sensor had been used for 19 days but it was seriously out of calibration this morning so I stopped the sensor and immediately set about inserting and starting a new sensor. I had a previous calibration of say 120 mg/dL while the old sensor said 100 mg/dL (the numbers aren't exact but they give the gist). I did not wait an additional 15 minutes for the old sensor to finish calibrating before trying to start a new sensor session. The new sensor code was 5937 if that helps, but Xdrip started giving readings prior to the 2 hour warmup. I can't give exact version information, but I downloaded a new APK on September 23 and the name of the APK is: xDrip-plus-20190518-14a03a7.apk . Anyways, the Xdrip app kept insisting that my blood sugar was 40 mg/dL when the ER did a finger stick and had 124 mg/dL or 111 mg/dL later. I tried to calibrate the Xdrip app using the readings from the hospital and it simply refused.

**Comment by definitivequestion** [comment]
Looking at the official Dexcom app, my sensor is showing as having been started on 9/16, but in reality it was started 9/23. Thus it seems I must not have waited long enough for the sensor stop request to complete.

**Comment by joshhiram** [comment]
Same thing happened to us today, minus the ER (sorry mate). Son's xdrip said he was 39 all day. Finger pokes showed he was indeed low at 60, but not 39. I did note in the logs that xdrip marked his sensor as "failed 4" right before the 39s started. Once we got home and replaced his sensor and transmitter, the calibration prompt problem started for us to. Alpha release, 9.30 nightly release, no change. See issue 1008. Back to Dexcom app for us. Hopefully xdrip is fixed soon.

**Comment by definitivequestion** [comment]
Josh, I'm wondering if there is a commonality between us. Do you have automatic restarts, preemptive restarts, and extended time travel enabled? Also if you haven't disposed of your previous transmitter that worked with XDrip there are tutorials on YouTube for how to Dremel the old battery out and replace it. I went ahead and got a refurbished transmitter on Etsy so I have a spare. The official Dexcom app may be necessary to start the new sensors, but XDrip can seamlessly pick up the session once you get past the calibration.

**Comment by joshhiram** [comment]
Yes, I am wondering the same thing.  I do not have the automatic restarts
enabled.  This is the first time we have replaced the transmitter, so we're
still pretty new to this.  I have heard of the battery hack.  I'm glad to
hear that works.  We have had no problem with xdrip the past 3 months and
we have grown quite fond of it.  Thank you for the reply.

**Comment by Navid200** [comment]
@definitivequestion Please update if you believe that there is a bug.
Otherwise, I would like to close this issue.
If you need advice with respect to how to use xDrip, you can get that from the xDrip facebook group or Gitter.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

**Comment by definitivequestion** [comment]
You can close this as I am no longer able to test things.
