### ISSUE TITLE
Daydream feature in Nougat persists the status bar... can you turn that off?

### ISSUE THREAD

**Issue by gitanO0** [NightscoutFoundation/xDrip#103]
When the xdrip+ daydream feature kicks in, the screen turns black and the graph, current BG values show up on the screen.... all good there.  However, at the top of the screen the status bar remains, will all the status bar items... clock, notification icons, etc... and, the status bar is a bright blue color. 

I'm concerned about screen burn-in with this and would rather there be nothing on the screen except for the floating graph and bg value.

**Comment by jamorham** [comment]
Is this behavior new for Nougat or is this something which occurs on other android versiosn too do you think?

**Comment by gitanO0** [comment]
I seem to remember the status bar persisting in Marshmallow as well but it was black... so only the icons, clock, etc... stood out in white fonts and icons.  Now the actual status bar itself is bright blue.

**Comment by jamorham** [comment]
I believe this is an option we can control in the daydream code but at the time a decision was made to leave it on to display the time. Googling I can't really tell if burn-in is still a thing but my plan will be to add a preference option to display the status bar or not when in daydream mode so the user can choose either.

**Comment by gitanO0** [comment]
You could, as a start, and if possible, change that status bar color to the same background color as folks have their xdrip+ background set to... for me that's black.  It's that bright blue color that really doesn't work.  I have my phone plugged in at night and the blue status bar shines like a lighthouse in my room.

**Comment by jamorham** [comment]
Can you let me know if the June 10th Nightly resolves this issue? So far I have tried to set the status bar background colour to black.

**Comment by roycesimpson** [comment]
Works perfectly!

**Comment by jamorham** [comment]
Marking as resolved.
