### ISSUE TITLE
Dexcom G6 - No valid timestamp stored for transmitter

### ISSUE THREAD

**Issue by jofrep** [NightscoutFoundation/xDrip#1030]
xDrip version: 5c91bed6-2019.08.20
Phone: Googlel Pixel 3
OS: Android 10
Dexcom 6, 8Gxxxx

Tried to use for the first time a Dexcom 6 transmitter and sensor.
Used the wizard and set the settings as required
After 2h warmup no readings were recieved. Tried to stop and start the sensor without any luck
After severla tries I got the message that the sensor crashed and now it is always Stopped.
Rebooted phone and started the process again with same results-

If I look at the logs I see severla times the message "No valid timestamp stored for transmitter:8Gxxxx"

Not sure if this is a bug or normal message.

**Comment by anthonymarzi** [comment]
Was there any resolution to this? Experience same issue.

**Comment by fooelisa** [comment]
Same here on a Huawei Mate 10 Lite phone (RNE-L21) with LineageOS 15.1 (based on Android 8.1.0). Had this with two G6 transmitters now, both with a 8Gxxxx serial. Haven't found a solution yet.

**Comment by Elvin6669** [comment]
Any update on this error? I have this issue on old type G6 and on G5 transmitters too. It's seems something quite new, tried older versions of xdrip but I still can't connect to the transmitters, are there any new commands in newer xdrip versions that could "brick" the transmitter?

**Comment by tolot27** [comment]
This issue is duplicated by #1778 and will be discussed there.
