### ISSUE TITLE
Bluetooth Meter Connectivity - Contour Next One

### ISSUE THREAD

**Issue by Xenocide23** [NightscoutFoundation/xDrip#104]
I cannot enable the "use bluetooth meter" option in Xdrip+ - the off/on button seems to be stuck in the off position despite pairing my meter with the app using the scan for bluetooth meter option.  

How does this integration work or is it still in development?  

Love the app and appreciate the help.

**Comment by jamorham** [comment]
Can you tell me which version of xDrip you are using? See the System Status menu item and please let me know the version code.

The Contour Next One integration normally works really well.

**Comment by Xenocide23** [comment]
I'm on the alpha version of xdrip plus the 2017.04.03 update I believe. Let me know if I can provide any other info for you.

**Comment by Xenocide23** [comment]
So using the stable version I was able to connect my meter. I think I didn't realize after pairing that I needed to click on the meter in the scanning settings.
