### ISSUE TITLE
No glucose values in G6 after calibrating: Confused Calibration 1

### ISSUE THREAD

**Issue by Gonzmdv** [NightscoutFoundation/xDrip#1044]
Hello, I started a new sensor yesterday night and this morning I calibrated it because it was a little far from the blood glucose result (153 in G6, 124 blood test).
Since then I haven't got a single reading. It shows Confused Calibration 1. I don't know what to do.
Any idea?
Event Log crowded with "Encountered backfill data we don't recognize: 85 127"
Using the XDrip algorithm, it works perfectly, so I suppose the problem is related to the transmitter. However the XDrip algorithm doesn't work properly. It shows higher values than the real ones. 
After several hours not working I have tried to hard reset the transmitter, but it didn't work, the hard reset failed, was not executed.
Still showing Confused Calibration 1 when I activate the G6 native algorithm.

![Screenshot_20191004-121218](https://user-images.githubusercontent.com/45602955/66200844-392f4380-e6a2-11e9-84b2-03c720ff8256.png)

**Comment by definitivequestion** [comment]
Try recalibrating with the official Dexcom app. It will take multiple finger sticks and several hours, but that should reset the sensor. When you return to Xdrip disable all automatic restarts, especially preemptive restart with time travel. In essence the transmitter will not accept huge calibration variances.

**Comment by Gonzmdv** [comment]
Thank you very much. That's a good idea. What worries me is that the Dexcom App can detect the Hard Reset and block the transmitter.
What's the difference between using XDrip  with the option "Use the OB1 collector"

**Comment by Gonzmdv** [comment]
Installed the Dexcom App in a Iphone. The Dexcom App told me that I should wait for 11 hours to calibrate but after 11 hours I introduced a calibration value and the App told me that it was no possible to calibrate.

**Comment by Navid200** [comment]
@Gonzmdv Would you please close this issue if your questions have been answered.
If not, you can use the facebook group or the Gitter room.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks
