### ISSUE TITLE
Whole house network

### ISSUE THREAD

**Issue by yoxud** [NightscoutFoundation/xDrip#1046]
I have searched but cannot find the answer to my question. What does the Participate in a whole house network precisely do? Does it allow you to roam the house and BLE connect to multiple xdrip instances?

**Comment by belyash7777** [comment]
Hello 
I want to make bluetooth bridge for miao miao. In xdrip+ is libre + bluetooth and wifi. How it work?
Is there some proects for this?

**Comment by tzachi-dar** [comment]
See https://github.com/tzachi-dar/LibreAllHouse for a description of how to create a whole house network for libre.

Currently working on MM1 and bubble. Work on MM2 is in progress (or one can use another android phone for mm2).

[@yoxud sorry, but this does not answer the question of what the "participate in a whole house netwrok do"]

**Comment by yoxud** [comment]
@tzachi-dar , I subsequently found a comment on gitter from jamorham stating that it is for use with his yet to be released whole house rpi system so I think it is an unused setting for now. I am beginning to tire of the Libre1's lack of precision in the low BG zone and frequent RMAs after 4 days of wear. The lack of whole house for G6 is the only thing keeping me from switching as it would take too much toll on my mind to force DD to carry her cell with her in the house. Just out of curiosity, many of us have old androids lying around and I wonder why other android xdrip instances  can not be used instead of rpis? Is it a fundamental reason or simply someone hasn't yet devoted time to it?

**Comment by tzachi-dar** [comment]
I don't have a g6 so I do not know for sure.
In the days of the g5 I have asked this question, and the answer that I got was that if there are two g5 phones that are paired with a G5, once one goes out of range there will be a missed reading before the other one has joined in (If you ask me this is not too bad).

Because of this reason, whole house coverage was not developed for g5.
I don't know what the status is with g6, but I guess this can be done (with a limit of a missed reading from time to time).

**Comment by yoxud** [comment]
Thanks @tzachi-dar, but I am still a little confused...
> Because of this reason, whole house coverage was not developed for g5
This seems to indicate the missed reading is an inherent property of the g5 itself and not of xdrip or android, otherwise one could still have built the WHC on rpis for g5.

On the other hand, if this problem is solely a property of the cgm, then why take the trouble to develop it on a different platform for g4 and Libre instead of directly in xdrip?

If @jamorham has some time, an update and clarification on this would be greatly appreciated. I would accept the libre as it is (sniff....)  and move on instead of waiting/planning for the g6. (I'd rather have a libre with all readings and good connections than g6 with missed readings.)

**Comment by tzachi-dar** [comment]
g4 all house support was developed before xDrip, so the question had no
mining at that time.

Libre works right now:
  mm1 / bubble using pi or extra phones.
  mm2 using another phone only.

Hope this helps.

**Comment by tolot27** [comment]
It looks like the question is answered. Can I close this issue?

**Comment by belyash7777** [comment]
Yes, thanks

  
>Среда, 30 декабря 2020, 14:48 +03:00 от Mathias Walter <notifications@github.com>:
> 
> 
>It looks like the question is answered. Can I close this issue?
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Виктор Беляев
