### ISSUE TITLE
Latest TicWatch Pro does not work reliably, as a Standalone Collector

### ISSUE THREAD

**Issue by amycarter112** [NightscoutFoundation/xDrip#1048]
Latest TicWatch Pro does not work reliably, as a Standalone Collector

https://www.facebook.com/groups/xDripG5/permalink/3047785118628296/

Folks,

Despite much chatter in the forums, I have been unable to get TicWatch Pro working as a stand-alone collector.

I personally, had no success at all the with 31 January version of xDrip+. I’ve had more success with 18 May version of xDrip+. However, Ticwatch Pro only stays running in standalone mode for between 2 to 12 hours, at best. Then it simply stops collecting. It always loses connection overnight.  If I then stop collecting wait 10 minutes and restart collecting on the watch it will resume again.

Here is my configuration.
Samsung S9 (SM-G960F), running Android OS version 9
xDrip+ 2019/01/31 (c/o ParapenT1sta) and tried 2019/05/18 (c/o David Potter)
MM1
Libre sensor 14 day UK version
TicWatchPro (recently purchased)
WearOS 2.28

I’ve tried two versions of xDrip+ the people have suggested work for them xDrip+ 2019/01/31 (c/o ParapenT1sta) and 2019/05/18 (c/o David Potter). 

I have followed the ideas discussed in problem report 840.
https://github.com/NightscoutFoundation/xDrip/issues/840

I have tried, IDEA NO 1, these ideas from David (Thank you, David)
“ ……………….With the help of Kirsten Verity Firefly's post in the miaomiao facebook group, I may have solved my issue. Hopefully this will help others.
I think the whole problem is competing Bluetooth.
I don't need Bluetooth on my Android for anything.
Here's what I did and again, Thanks are to Kirsten
1.	Check Force Collector on the phone
2.	Turn Bluetooth off on the phone
3.	wait and see what happens
4.	if you lose signal tap the three vertical dots on the watch
5.	Restart the Collector from the watch
6.	I have both my phone and watch connected to my work and home wifi.
When I got to work the value on the phone had a line through it, as expected and the watch was working fine. Once the watch and phone reconnected to my work wifi everything was back to normal. Same readings on both and phone is uploading to Nightscout :-)
Tip: On the watch under accessibility there is a magnification option. When you tap the screen 3x it enlarges that area. It also brings the area to the centre of the watchface. Tap the 3 dots 3 times and they will enlarge in the centre of the watchface. Tap once more and the menu will open up where you can restart the collector.”

I have tried, IDEA NO 2, these ideas are also from David (Again, Thank you David)
“…………Okay so another update which hopefully will help some. Thank you to Andrew Cruikshank
My Ticwatch died and I was back to square one. After following the steps below I have both my Ticwatch Pro and my daughter’s Fossil Gen4 back up and running. The Fossil Gen4 had not worked since January.
1.	get Xdrip running on both the watch and phone with Force Collector unchecked
2.	check Force Collector only on the watch. The phone should vibrate or sound with a notification
3.	on the watch press the 3 vertical dots and select restart Collector
4.	I went into Bluetooth on the watch and miaomiao was showing as available. I tapped it and it came up with “pairing” but then showed as available again.
After this watch was working standalone
Steps 3/4 can be reversed. I'm not 100% certain they are both necessary, but I do know that both watches are working again standalone with Xdrip. Very happy   and thanks to Andrew….”

I have tried, IDEA NO 3, these ideas are from ParapenT1sta. Namely his Portugese tutorial. With no success. Appreciate your efforts producing this Parapen.

I appreciate all the help on the forums I’ve had and also for the sterling work carried out by the developers.

Any thoughts, or ideas, please?

Thank you
•	
Kwis Jones Mine's OK I use may xdrip as well. So far since may only 2 disconnections and restarted tic watch and reconnected automatically. I don't use it as a standalone, I can't see the point of that. It's the collector so when it's in range it sends all the data to my phone which sends it all to nightscout. But I'm not attached to my phone
o	Chris Carter Kwis Jones thank you for your input, Chris

•	Andrew Cruikshank Have you updated the wear OS to the most recent version, my watch is running wear OS 2.9. And except of the odd connection issues my TicPro runs standalone fine, using the methods you listed above.
o	Chris Carter Andrew Cruikshank Hi Andrew, thank you for your reply. Could I plse ask what version of xDrip plus you are using? Thank you Chris
o	Andrew Cruikshank Not sure I’ll check when I get home and let you know.
o	Andrew Cruikshank Chris Carter version 14fecb8-2019.01.10
o	Chris Carter Andrew Cruikshank Cheers Andrew, I will try this version

•	Mike Simmons I use a ticwatch E2. I have to turn bluetooth off on the phone, then go to xdrip settings on the watch and turn on enable wear collection and force wear collection, then I go to bluetooth settings on the watch and scan for the miaomiao. Tap connect and it will say pairing and then quickly back to available. As long as it says pairing even if it is a fraction of a second it then works standalone. When I want to go back to my phone I turn off enable wear collection and force wear collection on the watch, put the watch in airplane mode and then turn bluetooth back on on the phone and reconnect. A bit involved but it seems to work
o	Chris Carter Mike Simmons thank you Mike for the information. I will try it out.
•

**Comment by jamorham** [comment]
Please try the latest nightly version:

https://github.com/NightscoutFoundation/xDrip/wiki/How-to-get-the-Nightlies-on-Automatic-Update

**Comment by paaascal** [comment]
ive tried the lastest and it doesnt work for me... are there any other things that need to be set up?  watch is fine if my cell is the collector...

**Comment by greekostas** [comment]
@ammycarter , have you read Event Log when your watch stops collecting?

**Comment by paaascal** [comment]
ticwatch pro or pro 3... same result doesnt work as standalone with xdrip and freestyle libre on oneplus 5

anyone knows the fix?

**Comment by xannasavin** [comment]
Ticwatch Pro 2020 neither does work as standalone collector

**Comment by lwychan** [comment]
Same for me, I bought the Ticwatch pro 3 so that I could use it as standalone, and now it doesn't work at all as a standalone, can we please get some help?

**Comment by tolot27** [comment]
Without any logs it is hardly possible to help.

**Comment by lwychan** [comment]
> Without any logs it is hardly possible to help.

How do I get the logs? I'm happy to help in anyway.

**Comment by lwychan** [comment]
> Without any logs it is hardly possible to help.

@tolot27 I've submitted logs via the app now. 

![Screenshot_20210103_193308_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/69717137/103487092-ab895900-4dfa-11eb-82b9-794b038625c1.jpg)

As soon as I change to wear collection it stops collecting now.

**Comment by lwychan** [comment]
@tolot27 @jamorham please let me know if there is anything else I can do to assist you.

**Comment by tolot27** [comment]
@lwychan Sorry, I do not have access to the app-uploaded logs, only jamorham. Please can you: either paste a screenshot here or dump the table UserErrors (or part of it) from an exported database and attach the relevant entries here (preferred by me).

**Comment by lwychan** [comment]
> @lwychan Sorry, I do not have access to the app-uploaded logs, only jamorham. Please can you: either paste a screenshot here or dump the table UserErrors (or part of it) from an exported database and attach the relevant entries here (preferred by me).

![Screenshot_20210106_073306_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/69717137/103741885-cc67cf00-4ff1-11eb-98b7-81f4bf82f967.jpg)

https://drive.google.com/file/d/1IafSrjUgu77TGNlZ2k1cl97a1GCjiVZn/view?usp=drivesdk 

@tolot27 It wasn't letting me upload the file, so I've put it on Google drive, hopefully that's what you need.

**Comment by lwychan** [comment]
> > @lwychan Sorry, I do not have access to the app-uploaded logs, only jamorham. Please can you: either paste a screenshot here or dump the table UserErrors (or part of it) from an exported database and attach the relevant entries here (preferred by me).
> 
> ![Screenshot_20210106_073306_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/69717137/103741885-cc67cf00-4ff1-11eb-98b7-81f4bf82f967.jpg)
> 
> https://drive.google.com/file/d/1IafSrjUgu77TGNlZ2k1cl97a1GCjiVZn/view?usp=drivesdk
> 
> @tolot27 It wasn't letting me upload the file, so I've put it on Google drive, hopefully that's what you need.

@tolot27 is that the right file you needed? I searched through the app for everything that it could've been.

**Comment by tolot27** [comment]
@lwychan The link you've sent is not freely accessible. I've already ask for access but did not get it so far. Please attach the file here.

**Comment by lwychan** [comment]
> @lwychan The link you've sent is not freely accessible. I've already ask for access but did not get it so far. Please attach the file here.

Apologies, I didn't realize I had to change the file access options, should work on: https://drive.google.com/file/d/1IafSrjUgu77TGNlZ2k1cl97a1GCjiVZn/view?usp=drivesdk
 Now for you, I can't seem to add a file in the thread other than images 🤦🏻‍♂️

**Comment by tolot27** [comment]
The main problem seem to be that the TicWatch is handled/recognized as a Bluetooth headset. Are there some selectable BT profiles for/at this watch?

Please enable extra logging for `ScanMeister:v` and upload a new log screenshot of the connection process.

**Comment by tolot27** [comment]
@lwychan Did you enable the vehicle mode?

**Comment by lwychan** [comment]
> process

@tolot27 I'm not sure how to enable extra logging? Is there a guide? 

I haven't enabled vehicle mode on purpose, but I do use car notifier to get the notification on Android auto.

**Comment by lwychan** [comment]
> The main problem seem to be that the TicWatch is handled/recognized as a Bluetooth headset. Are there some selectable BT profiles for/at this watch?
> 
> Please enable extra logging for `ScanMeister:v` and upload a new log screenshot of the connection process.

When you say the connection process, I hope this helps: 
![Screenshot_20210113_235904_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/69717137/104527220-1bb68c80-55fc-11eb-9c36-05a87091499e.jpg)

https://drive.google.com/file/d/1JxMIIrtPtC0Gxl1a9Owwd43VVD_ux3wb/view?usp=drivesdk

**Comment by Diabeetuss** [comment]
> Same for me, I bought the Ticwatch pro 3 so that I could use it as standalone, and now it doesn't work at all as a standalone, @jamorham can we please get some help?

I second this. Out of all the watches available, this one can/should be the +xdrip goto for everybody based on its specs and battery life....if only it worked as a standalone collector for the Dexcom.

@jamorham - assuming you have the time/interest - would it be any easier for you if you had a watch to work with? I'd be happy to try and help round one up for you.

**Comment by Diabeetuss** [comment]
Oddly, for the first time my TicWatch Pro 3 GPS is working as a Dexcom collector - only every 10 minutes. Using the latest xdrip update. Went in to the watch's Bluetooth settings and told it to forget the Dexcom (which it was saying was unauthorized), then restarted the watch collector via my settings on the phone. It's been working now for about an hour.

Good news?

**Comment by Diabeetuss** [comment]
Worked for about 2 hours as a standalone collector for Dexcom G6 then became hit or miss. I'd call it unreliable at best. Bummer. So close.

**Comment by lwychan** [comment]
@jamorham @tolot27 anything we can do to help?

**Comment by lwychan** [comment]
> Oddly, for the first time my TicWatch Pro 3 GPS is working as a Dexcom collector - only every 10 minutes. Using the latest xdrip update. Went in to the watch's Bluetooth settings and told it to forget the Dexcom (which it was saying was unauthorized), then restarted the watch collector via my settings on the phone. It's been working now for about an hour.
> 
> Good news?

I'm using Miaomiao 2, tried the latest nightly build and the problem still exists.

**Comment by elrufoelrufo** [comment]
Same problem here with 

MM1 v39 + Libre 2 + OOPT 2 + Xdrip + Fossil Sport


Does anyone know if it possible with this combination to use a Wear Os watch as a collector? 

Thanks.

**Comment by Navid200** [comment]
Consolidated all watch support requests: https://github.com/NightscoutFoundation/xDrip/issues/1872
