### ISSUE TITLE
Nightscout data different to Xdrip

### ISSUE THREAD

**Issue by alexmoir1** [NightscoutFoundation/xDrip#1049]
Hi Guys
My son's Nightscout Reports data is different to Xdrip. For example at midday today, 6th October, Xdrip shows up to midday. Nightscout shows a full day! Live data on both shows the same (up to midday),
Any ideas how that can happen & how to fix it?
Thanks
Ali

**Comment by steve8x8** [comment]
@alexmoir1 This probably is a glitch in Nightscout - did you set your timezone properly? UTC (the default) seems to cause offsets by up to a full day

**Comment by alexmoir1** [comment]
Yes that was it. There seems to be several settings for GMT/UTC. Changing it sorted the issue.
