### ISSUE TITLE
ANdroid Auto

### ISSUE THREAD

**Issue by jo1st** [NightscoutFoundation/xDrip#1057]
Not really an issue but more a request. I'm not sure how many users of xdrip use Android Auto in their vehicles but it's becaming very popular and helpful. I thought to request the creators/programmers to maybe look in to it. Sorry if I posted here but I didn't know where I should.

**Comment by gregorybel** [comment]
android APS supports it, see wiki how to use it.

**Comment by jo1st** [comment]
please direct me a bit. I have no idea what you are talking about

**Comment by jo1st** [comment]
I did everything you suggested, even created thew androidaps but still no
xdrip on android auto display

**Comment by gregorybel** [comment]
do you loop with Android APS?

**Comment by jo1st** [comment]
loop?

**Comment by gregorybel** [comment]
ok then you come from far away. So maybe android APS is not a solution for you. 

Xdrip can read out your BG, would it not be enough for you?

Otherwise, even if you don't Loop you can use android aps, but you need to configure it. please look at wiki. android needs to get Data from xdrip, you could select a virtual pump and keep Loop opened.

**Comment by jo1st** [comment]
xdrip is fine for me. I just wanted to hear the readings on Android auto
while driving but this happens only when connected Bluetooth, not in
Android auto.

as you said I don't know how to configure androidaps to receive the
readings from xdrip.

**Comment by gregorybel** [comment]
did you try the wizard?
I described in previous message how to configure it. Otherwise the wiki is really good.

**Comment by playingbball20** [comment]
Well I have used Android APS and it can work, but have had issues with it including it beeping ever 5-10 minutes on my phone. I also don't want to use another app on my phone to waste my battery. I am looking into implementing it, but there are certain sections of the xdrip which I really don't want to mess with. It really shouldn't be a huge deal to add, but I'm not familiar with the code.

**Comment by playingbball20** [comment]
I found an app that will put the notification onto android auto, it is much better than AndroidAPS.  It is CarNotifier.

**Comment by Cindy65** [comment]
Bonjour, je suis actuellement sous xdrip et je souhaiterais voir mes glycémies sur Android auto... Est-ce faisable ?
Si oui pouvez vous me donner toutes les directives ? J'ai suivi qq informations plus hautes mais que faut-il cocher dans l'appli xdrip ? Merci beaucoup

**Comment by gregorybel** [comment]
avez-vous suivi ce lien ?

https://androidaps.readthedocs.io/en/latest/EN/Usage/Android-auto.html

**Comment by Cindy65** [comment]
Oui tout est installé..je vais tester dès que je récupère ma voiture...au
garage 🤪🤪🤪

Le ven. 7 févr. 2020 à 22:38, Grégory Beloncle <notifications@github.com> a
écrit :

**Comment by jo1st** [comment]
I'm sorry but if the topic is in English what gives you the idea that is ok to start posting in French? and the you guys wonder why many people think you are just simply rude.

**Comment by gregorybel** [comment]
ok. Normalement vous devriez voir votre taux de sucre même sans votre voiture directement dans Android Auto, est-ce le cas ? Si oui, tout est bon.

**Comment by Cindy65** [comment]
Merci Grégorybel. Non dans mon application Android auto sur le tél ma glycémie n'apparaît pas... Je suis désolée mais je ne parle pas du tout anglais...si mon message dérange je peux le supprimer.... bonne journée

**Comment by jo1st** [comment]
assholes, either stop posting in French or get off this thread. Start your own

**Comment by gregorybel** [comment]
Nice way to talk other peaple. 
Not everybody can speak English and there are other ways asking something.
I just started a report to ban you.

**Comment by jo1st** [comment]
I asked you guys to speak english and you continued in French. You should
be banned.

**Comment by Cindy65** [comment]
I am very sorry.
