### ISSUE TITLE
miaomiao2: could retrieve libre history from blukon be applied? Not working now

### ISSUE THREAD

**Issue by yosepito** [NightscoutFoundation/xDrip#1059]
Just a small issue related to MM2. Eventually, it may loose connection by any reason, but it quickly reconnects. The issue is that if the disconnection lasts more than 10 minutes, it will loose readings. I have activated "retrieving libre history" just in case it could work with MM2, but it is not the case.

Is there any possibility to integrate the same feature for MM2? Although MM2 is meant to be used permanently even for taking a shower, it is not fully protected against water, so when swimming it could be affected. There are many other situations that lead users to wear it out, so I was wondering whether that utility may be implemented within the same feature

thanks

My setting for MM2 (working on Xiaomi Redmi 3S, android 6.0.1, MIUI 8.5.4.0 Global Stable):
turned on: 
*Turn BT on
*Trust auto-connect (although may be useless for MM2 since it has no pin code, but need it for Blukon)
*allow blucon unbonding (simply the MM2 seems to reconnect faster with this on if you turn off the phone)
*Aggresive service restarting
* run collector in foreground
* smooth libre data
* retrieve libre history
*Samsung Workaround

I do not recommend to use any utility turning BT on/off simply because MM2 requires much time to reconnect when for instance rebooting the phone. You can short it by pressing MM2 reset but with the BT settings commented above there is no need to do so.

The issue of Samsung Workaround is because blukon works better in Xiaomi with that enabled. Needless to say I use blukon while charging MM2, but I'd rather MM2 because the battery an be recharged and it has lesser BT issues than blukon

thanks for your support

**Comment by tzachi-dar** [comment]
What sensor are you using?

בתאריך יום ה׳, 17 באוק׳ 2019, 14:52, מאת yosepito ‏<notifications@github.com

**Comment by yosepito** [comment]
Thanks for the reply tzachi-dar, and for your excelent developments 

I'm using Libre-1 European version. From time to time I shift from blukon to MM2. Blukon depicts the dots retrieved after losing connection. MM2 does not. Neither are those missing dots in data table.
In logs, I can see that MM2 sends 16 raw values each time (from 0 to 15), and I selected smooth libre data with last 5 points, which is fine in both cases. However, MM2 seems not to gather history on reconnections (logs say nothing on that) while Blukon does (logs say retrieving libre history....... and the like and the missing raw values appear in the logs)
thanks!

**Comment by tzachi-dar** [comment]
This seems very strange, to say the least.

MM2, should be using the same values as mm1, and mm1 was able to handle gap closing...

Can you please do the following:

go to settings->less common settings->extra logging settings->extra tags for logging, and put there:
jamorham librereceiver:v,BgReading:v

Make sure there is a 25 minutes gap, and then send me the logs.

To send the logs, please do the following: 
Import export features->export database 
and then share it with tzachi.dar@gmail.com

Thanks

**Comment by yosepito** [comment]
will do, thanks. I've been out for a while. I will do that today late after starting a new sensor. I'm afraid I'm using blukon simply because I replaced MM2 (to charge it) with it and got glued to sensor due to the old sticker of MM2. Amazing, but I was unable to unglued it so decided to use blukon until the old sensor finish. This is relevant for others using MM2: the glue of double-sided stickers will stay on top of sensor unless cleaned. Since blukon fit perfectly on top, one will be unable to remove it!!
