### ISSUE TITLE
Feature request: Make it possible to disable "toast" notifications from the notifications menu

### ISSUE THREAD

**Issue by corneliusroemer** [NightscoutFoundation/xDrip#1060]
First of all, I love the app! Thanks for your great help in putting something so much better than LibreLink out there.

**Motivation**
It happens occasionally that my Miaomiao detaches a little too much from the Libre sensor. As a result, xDrip+ continuously throws "xdrip+: sensor not found" toast messages at the bottom of my phone screen. While it's nice to be notified that there's a problem, I don't like the fact that the message appears as a quite intrusive toast.

Right now, I don't know of a way to disable the toast notifications other than some hacks suggested via Android Stackexchange (https://android.stackexchange.com/questions/217733/how-to-get-rid-of-grey-error-alert-message-popup-toast).

**Suggestion**
a. The quickest fix would be to add a menu item in the notifications part of the settings to disable all toast notifications.
b. A potentially better way would be to route the error message through normal notification channels instead of toast messages.

Toast messages seem like a very crude way of doing UI. They are not persistent and so only really get seen by people who are actively using their phones. And in that case they're quite annoying, say while watching YouTube. It seems much more suitable to me to use a normal notification in this case. I don't know why the toasts were chosen in the first place - maybe because it was easier. But there are unintended consequences.

![](https://i.stack.imgur.com/kW07Sl.jpg)

**Comment by Navid200** [comment]
@corneliusroemer Would you please close this issue if you don't need it any longer?
If you do, would you please update since it has been more then a year since you posted your message?
Thanks

**Comment by corneliusroemer** [comment]
Closed as I no longer use Miaomiao
