### ISSUE TITLE
Multiple error messages in logs using 8G sensor

### ISSUE THREAD

**Issue by joelm335** [NightscoutFoundation/xDrip#1065]
Recently switched to an 8Gxxxx transmitter.  Running 08-October nightly. Am getting BG readings but Error and Events list shows 2 or 3 errors with every reading.  
![xDripn 8G errors](https://user-images.githubusercontent.com/32453941/67199396-14a0ce80-f3f9-11e9-94b4-20e94231cf60.jpg)

**Comment by 17gubbar** [comment]
Same issue

**Comment by Gonzmdv** [comment]
Same here.

**Comment by Navid200** [comment]
Those logs are expected.  They will not show up any longer if you update to February 17, 2021.
