### ISSUE TITLE
Alarm sound not played, only vibration

### ISSUE THREAD

**Issue by DavidAG2000** [NightscoutFoundation/xDrip#1066]
Moto G5 Plus, latest nightly of xDrip+, Android 8.1:

No matter what System Sound/Alarm I choose, the phone only vibrates. It doesn't sound as well the xDrip default sound :(

**Comment by Navid200** [comment]
@DavidAG2000 Would you please close this issue if it has been resolved by now?
If not, could you please post in the xDrip facebook support group?
https://www.facebook.com/groups/xDripG5
Thanks

**Comment by DavidAG2000** [comment]
> @DavidAG2000 Would you please close this issue if it has been resolved by now?
> If not, could you please post in the xDrip facebook support group?
> https://www.facebook.com/groups/xDripG5
> Thanks

Closed, thanks 😉
