### ISSUE TITLE
alarm sound

### ISSUE THREAD

**Issue by jo1st** [NightscoutFoundation/xDrip#1068]
Can anyone tell me if there is a way to reduce the volume of alarms??? I looked everywhere and the only thing I can see is high or medium or ASCENDING. How about implement a low or selectable option?? during the night while sleeping next to a spouse or a child it's insanely loud, my neighbor can ear it. Any help please???

**Comment by tzachi-dar** [comment]
You can choose a custom file for your alerts.

Choose something with low volume, then the total volume will not be too strong.

**Comment by jo1st** [comment]
I appreciate your reply and suggestion but I really don't think it's a good
one. After so many people are asking for a low / be able to adjust volume
within the app I don't think we should be looking and testing sound files
too see if they fit the volume we need.

**Comment by corneliusroemer** [comment]
I second this, the app is great, but alarms make me hate it increasingly. There are also a number of bugs with the repeat frequency and vibration features. I will try to list them all at some point in the future.

**Comment by jo1st** [comment]
Just to let you know what I use to modify the volume of XDRIP alarms is
Samsung sound assistant. It can lower the volume of specific apps. I don't
know if that works for you but give it a try
https://play.google.com/store/apps/details?id=com.samsung.android.soundassistant&hl=en_US


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Navid200** [comment]
Duplicate: https://github.com/NightscoutFoundation/xDrip/issues/620
https://github.com/NightscoutFoundation/xDrip/issues/813

**Comment by Navid200** [comment]
Please post in the original existing issue.  https://github.com/NightscoutFoundation/xDrip/issues/813

Creating redundant issues could actually reduce the visibility of the real number of users affected.
