### ISSUE TITLE
No initial readings

### ISSUE THREAD

**Issue by qOlivia0809** [NightscoutFoundation/xDrip#1070]
We have been using Libre, miao miao and Xdrip + for months with great success.  Now Xrip is 'stuck' on collecting initial readings.  I have changed the Libre, changed to a new miao miao, uninstalled and reinstalled xdrip + and tried on a different phone.  The Xdrip connects to the miao miao but there are no initial readings. I have disabled Trust Auto connect.  The Glimp App is working but it's a very poor substitute to Xdrip.

**Comment by qOlivia0809** [comment]
I have deleted Glimp and tried the Xdrip again.  No success.  I can only get as far as the Collecting Initial Readings screen.

**Comment by qOlivia0809** [comment]
The new miao miao is the miao miao 2.  I found a similar issue with collecting initial readings here.  https://drive.google.com/uc?id=18GTYzBp0rDVspy1bopaagyN6UrZDZJpc&export=download was suggested as the version to use.  I cant access it.  It says invalid resource path specified.

**Comment by DavidAG2000** [comment]
That happens to me quite often, and I could solve the problem several times activing airplane mode. I hope that helps you.

**Comment by plmarcelo** [comment]
I have same issue. Using MM1 + Libre 2. It gets stuck reading initial data. I tried Tomato application and it reads the data correctly. But don't like the application and it stops working every 30 minutes or an hour. Have been using Xdrip + MM1 + Libre 1 for 2 years and was very happy with it. :-(

**Comment by Navid200** [comment]
@qOlivia0809 Would you please close this issue if the problem has been resolved?
Please note that you can consult with the user community using the support channels.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks

**Comment by qOlivia0809** [comment]
Issue was resolved
