### ISSUE TITLE
Omnipod Dash

### ISSUE THREAD

**Issue by Jimwedel** [NightscoutFoundation/xDrip#1072]
Is there any development planned to pull carb, bolus and basal rate data from the Omipod Dash into the XDrip system to more fully automate this system?  This would be incredibly exciting for potential management outcomes.

**Comment by edisiENt** [comment]
Bump.  I agree, this would be very helpful & eliminate the redundant data input to the pump controller & into Xdrip.

**Comment by teleriddler** [comment]
Issue with DASH right now is that the BT communication has not been decoded.  This would be useful for both reading values from the pump as well as issuing commands to control it.  Until that happens, there will not be much development in this area of your request.

**Comment by Navid200** [comment]
I am postponing this as it is outside the scope of the current development plans.
A better place for this would be the discussions: https://github.com/NightscoutFoundation/xDrip/discussions
