### ISSUE TITLE
No BG values in nightwatch 

### ISSUE THREAD

**Issue by Gosee1960** [NightscoutFoundation/xDrip#1074]
After update AAPS to v2.5 i need to fill in by Xdrip+, interapp setting, Identify Receiver, info.nightscout.androidaps.
After this change in xdrip  Nightwatch didn't receive no longer BG values. 
How can i solve the problem?

Thanx in advance

![20191031_161113](https://user-images.githubusercontent.com/50959947/67960000-e93c9180-fbf9-11e9-9f31-aade6ee62c8a.jpg)

**Comment by Navid200** [comment]
@Gosee1960 Would you please close this issue if it has been addressed by now?
If not, you can use the CGM in the Cloud support group on facebook.
https://www.facebook.com/groups/cgminthecloud
Thanks

**Comment by Gosee1960** [comment]
I closed it,
Thanx @Navid200
