### ISSUE TITLE
Bridge battery level confusion

### ISSUE THREAD

**Issue by drpmorris** [NightscoutFoundation/xDrip#108]
I am using version 1704032023 (which I believe is the latest one?) on a samsung galaxy S6, with a sony smartwatch 3, xbridge (v2), and a dexcom G4.

Since the update, the xbridge battery status appears to be getting confused with the watch battery level when using the wear based collection service (which I use the majority of the time as I seem to get more reliability in that). 

This is a particular pain for me at the moment as I am havaing issues with my xbridge battery not lasting as long as it used to, so it would be really helpful to be getting correct battery information.

What seems to happen is that when the watch is doing the collecting, it displays both the watch and xbridge battery as the same level even when I know they are not the same (for example if I've just charged the watch and not the bridge, it will show "W:100% Bridge:100%" on the watch screen and on the phone app xBridge Battery: 100%.

This was not seen in the previous version.

Thanks

Paul

**Comment by jamorham** [comment]
@kskandispersonal do you have any ideas about this? thanks

**Comment by drpmorris** [comment]
Sorry - I should also add, when I disable the wear collection service I get the correct bridge battery level displayed on both the phone and watch. Just for completeness.

Thanks

**Comment by jamorham** [comment]
@kskandispersonal has provided a patch for this issue and it should be resolved in the 25th April nightly. Can you try that out and let me know if it fixes it. Thanks

**Comment by drpmorris** [comment]
Gladly, how do i access the nightly and install it? Thanks.

On 25 Apr 2017 22:42, "Jamorham" <notifications@github.com> wrote:

@kskandispersonal <https://github.com/kskandispersonal> has provided a
patch for this issue and it should be resolved in the 25th April nightly.
Can you try that out and let me know if it fixes it. Thanks

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/NightscoutFoundation/xDrip/issues/108#issuecomment-297173814>,
or mute the thread

**Comment by doohdah** [comment]
@drpmorris you can find the nightlys here [https://github.com/NightscoutFoundation/xDrip/releases](url)

**Comment by jamorham** [comment]
@drpmorris To access the nightly update channel within the app, go to the Update Settings and select the Alpha update channel, then exit the settings and then go back in and select the Nightly channel which should have appeared. You should get an offer of an update which you can then install.

**Comment by drpmorris** [comment]
Thanks. I've got the update and it appears to be working properly now.

Thanks for the quick fix!

Cheers

Paul

**Comment by jamorham** [comment]
Marking as resolved.
