### ISSUE TITLE
Large Chart AOD watch face no colour

### ISSUE THREAD

**Issue by jamespaulley** [NightscoutFoundation/xDrip#1081]
Can we have the Large Chart watch face go to black and white on AOD on a watch?

**Comment by jamespaulley** [comment]
There is currently no difference between the Always On Display and Active Display versions of the Big Chart watch face. Basically it's very hard to tell if the watch face is active or not. Could we have a low/no colour version for the AOD, perhaps with thinner line weights and less detail?

**Comment by tolot27** [comment]
Is this resolved with #1625? If yes, please close this issue.

**Comment by Navid200** [comment]
@jamespaulley Would you please respond to the question posed by tolot27?

I am closing this issue now since we have not heard from you.
We can always reopen if needed.

Thanks
