### ISSUE TITLE
Broadcast to xDrip (step2)

### ISSUE THREAD

**Issue by WalkingMyRoad** [NightscoutFoundation/xDrip#1082]
thank you @tzachi-dar and @MasterPlexus 
I tried your suggestion , and XDrip can show the glucose values success,
![Screenshot_20191105-094043_xDrip+](https://user-images.githubusercontent.com/12733707/68171962-cbcc4680-ffb0-11e9-8409-d1918fa826ce.jpg)
But I have some other questions that I hope you can help me：
1.Every 3 minutes i will send one glucose value to XDrip, can XDrip show every glucose values?
2. i don't quite konw  the meaning of each parameter , can you explain them for me ?https://github.com/NightscoutFoundation/xDrip/blob/606e53c0f6a601627e78588441aa77660aa22f25/app/src/main/java/com/eveningoutpost/dexdrip/Models/OOPResultsContainer.java
3.Do you have any better suggestions for me or closer cooperation?
4.Need to send unit to you(mmol/L or mg/dL)
Thank you for your help anyway.

**Comment by tzachi-dar** [comment]
1) xDrip can only show a new message every 5 minutes (or more). The reason is that there are many places in the code (for example, raise, or drop alerts) that will need to be changed.

    double currentBg; - current BG value
    int currentTime; - number of minutes from sensor start.
    int currentTrend; - a number saying the direction of the bg (not really used)
    HistoricBg [] historicBg; -> a vector of historical data (if you can create it)
    long timestamp; - epoch in ms 
    String serialNumber; - an identifier of the sensor.
3) I think that if you can have in xDrip your type of the sensor, this could make installation for users much better.

4) Thanks. Here we use mg/dl

**Comment by Navid200** [comment]
@WalkingMyRoad Would you please close this issue if your questions have been answered?
If not, you can use the xDrip support group on facebook.
https://www.facebook.com/groups/xDripG5
Thanks

**Comment by Navid200** [comment]
Duplicate: https://github.com/NightscoutFoundation/xDrip/issues/1058
