### ISSUE TITLE
Retrieve Voltage History

### ISSUE THREAD

**Issue by LongboatAline** [NightscoutFoundation/xDrip#1085]
Looking for a way to retrieve a backlog of the Voltage A/B and resistance data. 
Would it be possible to have that logged to a file or uploaded?

It'd already be helpful if the logs/older logs could be dumped to file for analysis/filtering. It only seems possible to upload them, and the older logs are too large for that even.

Or is there another way to retrieve them? Maybe I'm just clueless, any hint welcome.

**Comment by LongboatAline** [comment]
![Screenshot_20191111-215045_VoltageA](https://user-images.githubusercontent.com/35570803/68624781-e97d3c80-04d7-11ea-9726-092548f8f8b9.jpg)

**Comment by emp-00** [comment]
Since this issue is still open w/o feedback I'd like to add these lines and renew this as a "feature request": It would be great if xDrip had a battery trend of the values so that you can see how fast the voltage is dropping... this feature is missing. Punchline: "Single values are meaningless => the trend is your friend".

**Comment by mk886714** [comment]
but what is this trend supposed to predict for you? It would make more sense to evaluate the voltage drop from the start of the transmitter and to calculate the remaining time until the transmitter dies on the basis of the data In my opinion, displaying this in days and hours is more useful than a trend.

**Comment by emp-00** [comment]
OK, %battery would be nice, but many users are running rebatteried transmitters and depending on the used system the voltages for 100/50/0% battery are not known reliably. They're not documented by the supplier. Therefore it would be the most simple and straightforward solution to provide a **battery voltage trend graph in xDrip+**: 

Day 1 is start of transmitter and VA+VB+R could simply be plotted in a graph over time. This will help a lot in estimating how long the battery will still last. Sharp drops are visible enabling projecting an early transmitter failure (this is a common problem reported by many users). Currently we can only see single datapoints in the event log and it's impossible to plot it in the app. Such a battery plot could be added to the System Status in an (optional) additional page.

Here's how it could look like (values for Dexcom G6, 80x transmitter - 8G+ transmitters and other systems looking different!)
![image](https://user-images.githubusercontent.com/60714349/89712833-b5b24300-d993-11ea-83f9-ae112b86a094.png)

**Comment by machiyag** [comment]
I find no way to view the voltage states shown above. Is that not available for G6?

**Comment by tolot27** [comment]
> I find no way to view the voltage states shown above. Is that not available for G6?

Do you mean with "shown above" the screenshots uploaded to #629? They are available in &#8801; > System Status

**Comment by machiyag** [comment]
Now I can't remember what mine was a comment to, but it was not to that. I
get to the basic status screen without problems.

mh

**Comment by Navid200** [comment]
Duplicate:  https://github.com/NightscoutFoundation/xDrip/issues/530

Would you please add your comments to the existing open issue?
We are closing duplicate, as well as partially duplicate, issues.

Please let me know if you think this is not mainly the same concept.
