### ISSUE TITLE
Snoozing alarms on full Android watch

### ISSUE THREAD

**Issue by alexmoir1** [NightscoutFoundation/xDrip#1089]
Hi Guys, is there a way of using the buttons on the side of the full Android smart watch (KOSPET Prime) to snooze alarms?
It very fiddly to get to the side menu to choose the snooze option (especially in the middle of the night when half asleep!)
If not possible now, would someone be able to code it?
Thanks for your help.
Ali

**Comment by greekostas** [comment]
Hi @alexmoir1 , i had the same issue with my Kospet watch. Didn't managed to fix it.
I wanted to ask you something,  how many hours lasts the battery of your watch? Since that its the largest battery of all smartwatches.

**Comment by dinizmauricio** [comment]
Eu também gostaria saber alguma maneira rápida de adiar ou cancelar alarmes.

**Comment by Navid200** [comment]
@alexmoir1 Would you please update?
Is this something that can be fixed from the xDrip side?
