### ISSUE TITLE
Miao Miao 2 FSL2  and xdrip+

### ISSUE THREAD

**Issue by PeterKirp** [NightscoutFoundation/xDrip#1093]
Hi tried may things - couldn't make it work
FSL1 works fine!

Should this configuration work?

**Comment by keencave** [comment]
FSL2 ist encrypted. This is NO supported by MM2 and xdrip yet. Please follow the xdrip gitter channel for updates.

**Comment by Navid200** [comment]
@PeterKirp Would you please close the issue if it has already been resolved?
Otherwise, would you please post in the xDrip support group on facebook?
https://www.facebook.com/groups/xDripG5
Thanks
