### ISSUE TITLE
Hour markers off (for finger pricks only?) by ~ 10 minutes

### ISSUE THREAD

**Issue by steve8x8** [NightscoutFoundation/xDrip#1094]
I'm currently running xDrip without a CGM, only syncing a Contour BG meter via BT.
Today I took a blood sample at 14:46, but the red dot-square representing it is shown rather close to the 15:00 marker - off by about 10 minutes.
Looking closer, the yellow line above (my upper range limit) reaches beyond the 15:00 marker (~ 15:10) although I'm writing this at 15:00 straight.
Also the value itself is represented properly, AFAICT.
So the offset must be in the hour markers? (This happens both in portrait and landscape modes; they appear shifted to the left by ~10 minutes.)

**Comment by nsghub** [comment]
I stumbled upon this too when I started using xdrip. This behaviour is a bit irritating, but intendet. The marker is placed 15 (?) minutes in advance to take the delay between blood and tissue glucose into account. In your case this is not needed but AFAIK there is no switch to change the behaviour.

**Comment by steve8x8** [comment]
@nsghub So you want to say that a BG measurement is transposed to the point where the corresponding SG value is supposed to end up? While this sounds reasonable, what about other markers? (Meals, etc.) - Got to test that... Is there an explanation for the range limit lines?

**Comment by nsghub** [comment]
@steve8x8 Yes, that's what I meant. Markers for meals and treatments are placed at the same time you enter them.

Maybe you should post a screen shot ;)

**Comment by steve8x8** [comment]
OK, after adding meal records directly I can confirm that this offset seems to be intentional. I'm still puzzled by the use of a magic number - the blood-ISF delay time (which, I admit, is close to 15 minutes, but is it constant for all times and everyone?)
