### ISSUE TITLE
Feature request: Adjustable timestamp for notes (in treatments)

### ISSUE THREAD

**Issue by steve8x8** [NightscoutFoundation/xDrip#1098]
This feature requests asks for the addition of a "notes" field to the treatment input, right next to finger glucose, meal carbs and bolus injections.
I think this field would be rather useful - i.e. to jot down what the meal consisted of, whether there was blood or another anomaly after the injection, and other observations directly related to the treatment or combination of treatments.
These notes could be uploaded to Nightscout's DB with the three treatment values, within the same record.
Any thoughts?

**Comment by steve8x8** [comment]
(This seems to be an extra addition to #112 and #833.)

**Comment by steve8x8** [comment]
It turns out that there is an option to comment an existing "treatment" entry (that has been assigned a time), but I haven't found a way to add a timestamped note without that, and carbs are rounded up to the next full gram :/ (i.e., apparently there's no way to keep the treatment empty otherwise)

**Comment by Navid200** [comment]
@steve8x8 Would you please add your suggestions to https://github.com/NightscoutFoundation/xDrip/issues/833
