### ISSUE TITLE
Feature Request: Extended/Dual Wave Bolus

### ISSUE THREAD

**Issue by mistermintsgh** [NightscoutFoundation/xDrip#1099]
Can an option be added to the bolus recorder to add an extended/dual wave/square wave/whatever other manufacturers call it bolus?

When I was on MDI it was fine just entering my bolus as is. If I needed to take a split dose I would just record another bolus an hour later (or whenever it was I injected again).

Moving on to a pump, I can't see anyway to record an extended bolus, either on the bolus/carbs/time input screen, or hidden inside any of the menus. It would be really useful to be able to see IOB like this, rather than it just ending after 4 hours (or whatever you put as the insulin duration in the settings)

It may well be that this is displayed, or works already when using a loop system, but with a standalone pump I can't currently see if/how this is possible.

**Comment by wouterlemcke** [comment]
I am missing this feature to. Would love to have this

**Comment by Navid200** [comment]
This looks like a duplicate:
https://github.com/NightscoutFoundation/xDrip/issues/429
Please let me know if you think it is not.
If it is, please add your comments there.
