### ISSUE TITLE
G6 Sensor - Transmiter ID DB location

### ISSUE THREAD

**Issue by jofrep** [NightscoutFoundation/xDrip#1102]
Hi,
Sensor died at day 8 with "Sensor errors"
Replaced the Sensor with a new one but after the warm up did not work either. Nothing was captured.

I wanted to try the official application in case it was a transmitter problem and had to convince the help desk. I did a backup of the xDrip DB and Settings but forgot to write down the Transmitter ID before I uninstalled it.

Now I want to use the official application but I need the Transmitter ID. I looked into the sqlite DB but could not find it. 

- Is the Transmitter ID stored in the sqlite DDBB?
- If yes, where it is?

Thanks

**Comment by xannasavin** [comment]
best just reinstall xdrip, restore backup and lookup the ID in the settings.

**Comment by jofrep** [comment]
Simple and easy. Thanks for pointing this.
