### ISSUE TITLE
SAGE information not uploaded to Nightscout (miaomiao2)

### ISSUE THREAD

**Issue by Philoul** [NightscoutFoundation/xDrip#1109]
Hello,

After asking help on facebook CGM (https://www.facebook.com/groups/cgminthecloud/permalink/2541512405970000/) I saw that I'm not alone having problems to upload SAGE information from xdrip to NS (don't know if it's limited to miaomiao2 + FSL...)

![SAGE KO](https://user-images.githubusercontent.com/52934600/69906031-5b50f380-13bd-11ea-8a37-f71733f0a96c.jpg)

My NS website is up to date and my xdrip version is Pre-release d7689af-2019.11.02

**Comment by steve8x8** [comment]
Apparently there's no "Sensor Start" or "Sensor Change" treatment recoed - I think you're supposed to "Start Sensor" once from xDrip (select "not today" for whichever reason), then "Change" the sensors. (xDrip will set the time to somewhere in the past though, off by one day.)

If you know how to work with the NS API, you may add a "Sensor Start" treatment record to the database (entryType, date, created_at, and possibly notes with the sensor code should be sufficient), NS will show a valid SAGE afterwards.

**Comment by tolot27** [comment]
@Philoul Did you close this issue because it is fixed with your recent PR?

**Comment by Philoul** [comment]
No
My recent PR only improve User Interface in AAPS with sensor battery level.
I'm still thinking it could be a good idea to share a Start Sensor event, I closed this xdrip issue because I don't know today what is the best transverse solution between xdrip, AAPS, NS and other existing apps (glimp, Dexcom patched app, ...) to manage properly this information.
