### ISSUE TITLE
XDrip not backfilling data to nightscout

### ISSUE THREAD

**Issue by StormeHawke** [NightscoutFoundation/xDrip#111]
I have been using xdrip+ for several months, but due to an upcoming endo appointment I started looking at the best way to generate reports and Nightscout seemed to be the seamless way.  I'm a software dev, so the complicated setup didn't bother me.

I went through all the setup to get nightscout up and running, and my xdrip app is uploading current blood sugar readings as expected.  However, it's been about 18ish hours since I got it running and as of yet it hasn't uploaded any of my several months worth of back data.

![image](https://cloud.githubusercontent.com/assets/540587/25579645/a217a63c-2e47-11e7-8264-bc59e92718c3.png)

I've been told in the xdrip+ facebook group that it should be uploading the back data, so since it's not I'm filing this issue.  Thanks!

**Comment by tzachi-dar** [comment]
Hi, 
xDrip+ will not load data that was not set to be uploaded when it was created.

There is probably a simple way around it, (Simple here is relative, if you are a dev that is familiar with java, and sqllite, this will be easy...).

There is an uploader queue (file UploaderQueue.java). For each new bg, there is an entry created there, (see UploaderQueue newEntry). 
What you should do, is save the xdrip db to file, open an sqllite browser and have an entry on the uploaderqueue table for each bg that you want to upload). Once the db file has changed, copy it back to xDrip and it will upload the data.
You can do the this, using SQL lite operations, or using local java code on pc (or python on pc) or even do it on the android code itself.
Make sure that you backup your xDrip data before you begin.

HTH
Tzachi

**Comment by StormeHawke** [comment]
> xDrip+ will not load data that was not set to be uploaded when it was created.

Perhaps this could be considered a feature request in that case, maybe an option somewhere under the uploader to enqueue all bloodsugars that haven't yet been uploaded.  It seems like this is something that any user who started with xdrip and later set up nightscout would want

**Comment by StormeHawke** [comment]
Otherwise can you point me to instructions for saving off the db file and reimporting it?

**Comment by tzachi-dar** [comment]
On the right side of xDrip on the top there is a menu.
Select import/export features there.

**Comment by StormeHawke** [comment]
Looks straightforward enough, except for these two fields:

action|bitfield_complete|bitfield_wanted

How would I determine which values to put in there?

**Comment by tzachi-dar** [comment]
operation_type = "create"
bitfield_wanted = NIGHTSCOUT_RESTAPI (==2)
bitfield_complete = 0

**Comment by StormeHawke** [comment]
awesome, I think I have it uploading data (at least, there are data points for 3 months ago).  Seems to be taking a while though - how frequent are the upload batches?

**Comment by tzachi-dar** [comment]
I think that uploader batched are 5 minutes apart.
It seems that there number is being set on the function UploaderQueue.getPendingbyType() and the default number is 300.
So, if I'm correct, you should be fine by now (uploading about a day data every 5 minutes), but if I'm wrong, you can try changing the default to something bigger to speed things up.

**Comment by StormeHawke** [comment]
So far my mlab db has ~4200 entries out of the ~17000 entries that were in the db yesterday when I hacked it.  Can't tell if it is still uploading them other than the data for the current time

**Comment by StormeHawke** [comment]
No more records have been uploaded today.

**Comment by tzachi-dar** [comment]
Is the current reading being sent to mlab?
Can you look at azure resource status? maybe you have uploaded too much data there?

**Comment by StormeHawke** [comment]
It's possible.  I wasn't seeing the current value for a while last night.  I'm using heroku.  I'd be willing to privately give you access to my site if it would help you diagnose, with the understanding that i'd change the passwords and such when we're done.  Passwords are already unique, not using them elsewhere

**Comment by tzachi-dar** [comment]
I'm afraid I can not look in the heroku site.
You can try and look in the xDrip logs and see if you can see any errors there. (start in the right top menu again).
You can also try to upload using the direct mongo method and see if that is working. There is no limit on the amount of data that you can use there.

**Comment by jamorham** [comment]
I think I probably need to add a mechanism to allow for back-filling of the data as the current implementation wasn't designed with that in mind but it shouldn't be too hard. 

I don't know whether doing this is going to introduce the potential for problems with duplicate data at nightscout though.

**Comment by AdrianLxM** [comment]
Nightscout does upserts if some data item is set correctly. I believe it was the "dateString" and type that had to match.
For the mongo upload it was this PR from tzachi: https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/commit/28c11dbee64fa0a7557839e1ba83d0ea4ea84d0a#diff-05711f4dc7a2fe190a27f694e738fe24

This would mean uploading the same data twice wouldn't cause duplicaitons.

**Comment by bryanw20** [comment]
I'd also like this feature added, or a way to force it myself. I'm not a programmer; I may try to teach myself.
But I'm using xdrip+ as a T2; didn't need any followers when starting out; didn't think about no Clarity link; finding it difficult to make reports any other way besides NS; so now I'd like to have a 3mo or so backlog of xdrip data sent to NS for making reports.

**Comment by jamorham** [comment]
The latest nightly has an option to backfill data. Find it in `Settings` -> `Cloud Upload` -> `API Upload` -> `Extra Options` ->`Back fill data`

**Comment by StormeHawke** [comment]
Outstanding! Thank you!

**Comment by bryanw20** [comment]
Yes thank you!

**Comment by jamorham** [comment]
@StormeHawke @bryanw20 Were you able to test this feature?

**Comment by AdrianLxM** [comment]
I tested it and it worked very well to backfill 2 to 3 months of data in about 30 to 40 minutes.
Many positive feedback on facebook, :+1:

**Comment by bryanw20** [comment]
Yes, it's working great! Thanks!
Just wish I paid attention when my phone died a couple months ago that the xdrip export saved to internal memory, not my SD card; so I lost all my old data :(
But yes NS now hass all the data my phone does. 
Thanks again!

**Comment by StormeHawke** [comment]
Having manually hacked my data into the upload queue for an endo appointment I don't really have any data to upload that hasn't already been uploaded.  That said, I'm fine with you marking this closed on the basis of others testing it successfully

**Comment by jamorham** [comment]
Okay thanks everyone. Marking as resolved.
