### ISSUE TITLE
No BG value on wear complication with "640G / Eversence" as HW Data source

### ISSUE THREAD

**Issue by gregorybel** [NightscoutFoundation/xDrip#1110]
I use the patched Dexcom G6 App.
BG values go to AAPS and AAPS broadcasts it back to Xdrip when using "640G / Eversence" as HW Data source.
On Wear complication, there is no BG shown (NULL NULL ()) in this particiliar case (otherwise wear complication works).

**Comment by Navid200** [comment]
@gregorybel Is this still the case?
What do others do?

**Comment by gregorybel** [comment]
@Navid200 still using my old self patched xdrip so I dont know if issue is still there. But I have provided a dirty workaround for this in another issue so maybe we could close this issue.

**Comment by Navid200** [comment]
If you are the only one who needs this and you have already found a solution, I don't see the point of leaving this open.
If you like to share your solution, I guess you can open a pull request?

**Comment by TRoth9** [comment]
Please do. I believe I have been experiencing this same issue just without AAPS in between. Using BYODA to Xdrip+ with 640G / Eversence as the data source. Seems to work on the Xdrip watchface, just not the complications as in #325.

**Comment by Navid200** [comment]
You can reopen this of course.  But, would you please make sure there is no other issue older than this that is reporting the same problem or anything related?
