### ISSUE TITLE
[Q] - Possibility for IOS devices as xdrip followers?

### ISSUE THREAD

**Issue by zshh** [NightscoutFoundation/xDrip#1111]
Hi,

Today entire household is on Android so we are running xdrip natively on "main device" as well as follower devices.

If one of the followers would to get iphone, is it possible to follow xdrip main device from ios?
(i am talking about follower devices only). I refuse to have iphone as main device with spike and having to battle apple with their limiations and renewing certificates and other crap that comes with it.

thanks

**Comment by Navid200** [comment]
@zshh Would you please close this issue if your question has been answered?
If not, woulc you please post in the xDrip support group on facebook?
https://www.facebook.com/groups/xDripG5
Thanks

**Comment by tolot27** [comment]
You can use [xdripswift](https://github.com/JohanDegraeve/xdripswift) in combination with Nightscout to follow the main xDrip instance.

**Comment by jbowler** [comment]
The problem with the forks (spike, xdrip4ios/swift) is that they don't, so far as I know, support the xDrip+ follower.  This works without an internet connection, or at least it seemed to last time my wife had an Android phone (xDrip+ follower, on a road trip).  This was before "Desert Sync", both phones were on the same local network (one of the phone's wifi hotspot), US mountains so pretty much no internet; no mobile coverage.

Clearly it needs an Apple developer, but maybe it would be possible to just have a follower perhaps with limited/no ability to input data.  Maybe it's already been done; the FB group is private so I can't search it.

**Comment by Navid200** [comment]
This is an old thread and the posts in it are not 100% up-to-date.
We now have a support channel here: https://github.com/NightscoutFoundation/xDrip/discussions
