### ISSUE TITLE
MiaoMiao 2 + 14 day 'too much data' error

### ISSUE THREAD

**Issue by arturusdent** [NightscoutFoundation/xDrip#1112]
I just received my MiaoMiao2 and so far have not been able to get it to work.   Initially, it was giving checksum errors.  Updated MiaoMiao2 firmware to 0007 per their website, installed and enabled OOP algorithm app, now I get the logs below:

Pixel 3 XL on Android 10
xDrip 11/22/19 nightly
MiaoMiao 2
No Tomato or Glimp apps installed

Any assistance would be appreciated.

![image](https://user-images.githubusercontent.com/58447587/70000977-22825d00-152a-11ea-8276-33bce850a1da.png)

![image](https://user-images.githubusercontent.com/58447587/70001019-3a59e100-152a-11ea-889d-58f5b6c1def4.png)

![image](https://user-images.githubusercontent.com/58447587/70001043-4776d000-152a-11ea-96f4-3d422bec5ae8.png)

![image](https://user-images.githubusercontent.com/58447587/70001064-5eb5bd80-152a-11ea-86f3-47bd0f61f8b8.png)

**Comment by tzachi-dar** [comment]
Hi,

For pixel 3 with android 10, it is a known problem. Your best bet is  to
downgrade to android 9. (I believe that if you open the oop there it will
freeze).

There is a discussion on how to get this working on
https://gitter.im/LibreOOPAlgorithm/Lobby.
Please read the last 3 days or so, to see what is going on.

Thanks
Tzachi

**Comment by Navid200** [comment]
@arturusdent Would you please close this issue if it has been resolved?
If not, please update.
Thanks
