### ISSUE TITLE
Request: Compatibility w/ Medtronic Guardian Connect 3 Transmitter

### ISSUE THREAD

**Issue by chrismcgt1d** [NightscoutFoundation/xDrip#1113]
I currently use the G6 and a 640g pump. It would be fantastic to push my integration further and use the Guardian 3 sensor (which as far as I understand upgrades from the v2 with bluetooth integration to connect with their own mobile app) with my xDrip and Nightscout setup to retain the phone/smartwatch/cloud upload flexibility but gain the Smartguard low BG protection on my pump. 

I feel like this is probably something that is being developed already but couldn't find anything in the issues or documentation.

Big thanks for all you do <3

**Comment by steve8x8** [comment]
Are you sure the Guardian can communicate with xDrip directly? I've only seen it to talk to the pump - which in turn can be read out rather successfully, using the 600SeriesUploader on any Android device that can (USB-) host the CNL2.4 stick.

**Comment by chrismcgt1d** [comment]
That's sort of the question I'm asking. The Guardian 2 could only talk to the pump. The 3 can talk to Medtronic's own mobile app via Bluetooth, so I assume it could also be made to talk to xDrip as well _without_ the clunky OTG dongle solution.

**Comment by DriverTicks** [comment]
Guardian 3 Connect CGM system can connect to phone directly, via bluetooth.

**Comment by steve8x8** [comment]
@DriverTicks you're right :'( - pardon my ignorance ...
but apparently nobody had yet looked into it :'(( so first the communication has to be understood
btw, the app requires Android 7.0+

**Comment by steve8x8** [comment]
@chrismcgt1d what about adjusting the title of this issue? You're requesting compatibility with Guardian Connect 3 transmitters, right?

**Comment by chrismcgt1d** [comment]
> Guardian 3 Connect CGM system can connect to phone directly, via bluetooth.
> https://www.medtronicdiabetes.com/products/guardian-connect-continuous-glucose-monitoring-system

This doesn't quite work for me as I use the android wear collector function of xDrip+ pretty regularly, which the official Medtronic app can't do as far as I'm aware

**Comment by Navid200** [comment]
@chrismcgt1d Would you please close this issue if your questions have been answered?
If not, would you please use the support channels?
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks
