### ISSUE TITLE
LibreTrendLatest.glucoseLevelRaw is zero

### ISSUE THREAD

**Issue by Bartlomiejsz** [NightscoutFoundation/xDrip#1119]
Hello. On newly connected Libre 1 with miao miao 2 I got error logs like on screen and xdrip hangs on initial data collection. Libre itself works fine because I can read glucose level in Libre link app.
What could be wrong in that case? 
![Screenshot_20191208-090610](https://user-images.githubusercontent.com/9566840/70386599-7a8de900-199a-11ea-9601-4eb855a07cbc.png)

**Comment by tolot27** [comment]
I'm getting the same error serveral times per minute, but with a Libre2 and the patched app. How did you solve it? Please can you reopen this issue?

**Comment by Artemdrip** [comment]
> I'm getting the same error serveral times per minute, but with a Libre2 and the patched app. How did you solve it? Please can you reopen this issue?

https://insulinclub.de/index.php?thread/26053-freestyle-libre-erfahrungen-mit-messgenauigkeit/&postID=582997#post582997

google translate will help you :)

**Comment by tolot27** [comment]
@Artemdrip guided me to the solution to disable the libre trend: xDrip+ Display Settings > Graph Settings > Show libre trend. Thx!

That raises the question, why this option was enabled by default. I assume, it is not related to the Libre2 (patched App) data source and should be disabled if this source is selected.
