### ISSUE TITLE
New 'Add Treatment' Dialog

### ISSUE THREAD

**Issue by ahaverty** [NightscoutFoundation/xDrip#112]
Hi All,
I forked @jamorham 's xDrip+ and added a new all-in-one 'Add Treatment' view with features:
I've modified it as I was finding the current add treatment entry slow to navigate.

1. Material Design Time picker (defaulting to now & restricted to < currentTime+1hr)
2. Native android keyboard with editView's and imeOptions for quickly cycling through the fields and submitting from the keyboard
3. Native inputType's for simpler input validation
4. DialogFragment View to retain visibility of the graph in the background
5. For **xDrip+** I've added quick suggestion buttons for carbs and insulin, for a quick entry similar to MySugr app (see video). Notice the suggestion disappears on editing any field, as to avoid confusion/outdated suggestions. _[I would love to make this dynamic based on what's being entered into the carbs field, but I have no experience with the calculations. If anyone can help there, I'd love to hear.]_
6. Toolbar 'ifRoom' add treatment button (My big fingers have constantly been hitting the wrong button in the current version)

Quick demo here: [https://www.youtube.com/watch?v=MKpDlzaXHOU&feature=youtu.be](https://www.youtube.com/watch?v=MKpDlzaXHOU&feature=youtu.be)
I'm interested to hear people's thoughts or if a PR would suit?

**Comment by rbaechle** [comment]
@ahaverty, i think this addition would be a great addition to xdrip plus. It would be great if someone could automate the calculating of the carb to insulin using the information under settings. Entering time would be easier using this interface. I have misentered information because carb, insulin, and time are not visible all at once untll the confirmation screen shows but then I have to cancel and start over. This would help. Thanks for the video showing how the interface would function.

**Comment by JonnyJohnson** [comment]
Is there also the possibility to add a switch from carbs in gramm to (in Germany used) Broteinheiten (BE)? The insulin dose is often calcuted using BE, where 1 BE = 12g carbs, or 1 KH (Kohlehydrateinheit) = 10 g?
If you could extend your dialog with these "units" it would be great either to use carbs in gramm or just BE/KH,

Thanks in advance,

**Comment by bryanw20** [comment]
This is cool, how do we get it added to a nightly update build?

**Comment by raymond-richmond** [comment]
I'll bump this one.  The current dialog drives me occasionally nuts as I forget sometimes to use 24h notation.  I like this proposal and suspect at most a little polish is all that is required.  I will also +1 the roundabout suggestion for bolus calculator/suggestor.

**Comment by wicky1988** [comment]
Whatever happened to this? I think it would be a great addition!

**Comment by ahaverty** [comment]
Sorry all, I implemented it into an unreleased branch derived from jamorham's repo. It has been working great for me, I'll look into PR'ing something when I get a chance 👌

**Comment by raymond-richmond** [comment]
Any chance you've had some time to look at integrating into the current master branch?
Current still driving me nuts. ;)

**Comment by ahaverty** [comment]
Sorry again, I'm not sure I'll have the time. If anyone knows their way around Java/android maybe you could pull out the good bits from my branch? https://github.com/ahaverty/xDrip-plus
It's unfortunately originally branched from xDrip+

**Comment by ahaverty** [comment]
Hi all, this conversation seems to be kicking off again over here if anyone has any good inputs: https://github.com/NightscoutFoundation/xDrip/issues/833#issuecomment-477341950

**Comment by asavageiv** [comment]
Do you want inputs here or on the other issue? It's unclear to me whether they should be merged. I would love to see an improved treatment dialog.

**Comment by Navid200** [comment]
@ahaverty Since you mentioned in this issue that you had no time to work on it, I would like to close this issue and let the other newer issue stay at least as long as it is active.  Please let me know if you feel this issue should stay open.

**Comment by ahaverty** [comment]
Hi @Navid200, I believe this addition was/is blocked until the main contributors/owners give some indication or answers to how people can add improvements/alternatives to the input dialogs. My suggestion in one of the threads was to allow passing data from third party apps via intents so that people could roll their own input dialogue apps and widgets without needing to merge everything into xDrip.

I'm also no longer using xDrip, so I'll close this issue now.
