### ISSUE TITLE
Suggestion: Shabbath Mode.

### ISSUE THREAD

**Issue by Seithx** [NightscoutFoundation/xDrip#1120]
I know this may be a request by a minority, perhaps, but still a great deal of users will benefit from this addition. 

To be more specific by what I mean by "Shabbath Mode":

1. App will run all defined functions using a predefined setting, say, run this and that every week on this day, from this hour till this hour, and can be adjusted every week according to what time Shabbath begins and ends.

2. After putting on this setting, on the defined times Xdrip will turn the screen on in predefined intervals, to avoid touching the screen.

3. Brightness will be set to the lowest setting and be forced to stay that way until Shabbath ends.

4. Airplane turned on, but with whatever functions needed to receive data from the MiaoMiao for example (my vase: I need both Bluetooth and GPS to.get signal, so this needs to be predefined by the user)

5. Turn all alerts that are on to silent, with no nudges. (user can choose to use vibrations, but I doubt people who care about Shabbath will need)

Thats all. Just a suggestion.

Take care,

**Comment by tzachi-dar** [comment]
I think that you can get almost all that you want with a watch that is always on.

Regarding alerts, I hope that you care for "pikuch nefesh" as much as you care for Shabbath.

**Comment by Seithx** [comment]
Hi Tzachi,

That's true. But some still don't have a watch or don't want it, it's just a suggestion.

Also, regarding Pikuh Nefesh, that's a complicated subject and even with that, if allowable, people would prefer to honour Sabbath as much as possible, and are already doing this manually, so it's just a matter of convenience. 

It does not contradict the suggestion, on the contrary, people can feel better checking the sugars.... 

Another suggestion: A widget that will stay on the screen, showing the sugar level, without needing to press the power button.

But, from your answer, I understand the suggestion is dismissed for the time being.

**Comment by tzachi-dar** [comment]
Hi,

I was just trying to help. Anyone that has the bw can try and implement whatever parts in your suggestion as he pleases.

Having the screen always on, is probably not possible as the battery will not hold for 24 hours.
We are having two tablets that show BG values and are always connected to the main power.
I also have a watch for the time that I leave the house.

Obviously, not everyone has the equipment that I have.
xDrip also have the option to speak the readings. Not perfect, but can give one a sense of what his BG is.
I'll add to my list, implementing of opening the screen every x minutes, but list is very long, so there is no promise I'll ever get to it.
As for alerts, well IMHO, this has nothing to do with what people want or don't want.
If low BG is a risk to life, alerts must be used. 
One can have the alert once per hour (hoping that once the hour has passed BG will already be stable).

HTH.

**Comment by Navid200** [comment]
@Seithx What do you currently use for this?
When you ask for a new feature, it is very helpful to help the developers appreciate the before and after.
Without it, there is no way to feel what hardship they are trying to resolve.

We need to prioritize the requests.  

But, it is not clear to me what you are asking
For example "App will run all defined functions using a predefined setting" is too vague.  What do you mean by pre-defined functions?  
It has to be clear what you need.  

I could be wrong.  But, this sounds like a very complicated change to the code.  I doubt we will do anything like this.  The reason is that we have open issues that are very minor mods and they have been open for years!
We don't have lots of developers currently.  They are very busy.
So, I don't want to get your hopes up.  But, there is absolutely no chance of anything happening if we don't know what this request is.
So, you can decide.

I will close this in 10 days if I don't hear from you and that will be OK.

**Comment by Seithx** [comment]
Hello,

Let me try and demonstrate what I want.

![IMG-20210227-WA0002](https://user-images.githubusercontent.com/46000455/109394757-4735d200-7931-11eb-99f9-ab2f965165ad.jpg)
![IMG-20210227-WA0001](https://user-images.githubusercontent.com/46000455/109394758-4866ff00-7931-11eb-9796-1d57d29fb3fb.jpg)
![IMG-20210227-WA0000](https://user-images.githubusercontent.com/46000455/109394760-48ff9580-7931-11eb-8f33-da35b7d62e31.jpg)
![Screenshot_20210227-191900](https://user-images.githubusercontent.com/46000455/109394762-49982c00-7931-11eb-9895-7a59d044a480.png)
![Screenshot_20210227-191854](https://user-images.githubusercontent.com/46000455/109394763-4a30c280-7931-11eb-94ba-7cc496a034f1.png)


Please see pictures attached. I am demonstrating a common scenario, where as shown, each reading raises by 0.1 which is below the high threshold, so it usually does not trigger, until it reaches my high setting (which is 85), so instead of having the ability to correct, I sometimes not notice and end up too high.

My request:

See the rising threshold setting, i am asking to add a 0.1 mg/dl option.

Same for the falling threshold.

That is all, so at least on the surface, it looks like a matter of just adding an additional option, for an existing feature. That is all.

Hope thats clear.

**Comment by Navid200** [comment]
I am so puzzled!
Are you saying all you wanted is what the  following single line describes?

Please add a third option to the threshold of the falling fast and rising fast alarms equal to 0.1mgdl?

Unless I am still not understanding.

**Comment by Seithx** [comment]
Oh, Im sorry, thought this was the thread about the threshold thing!

If you could refer my last comment to that, would be better, to avoid confusion.

App will run all defined functions using a predefined setting, say = screen on all the time every shabbath at time X, disable all unrelated operations (say, wifi, 4g) besides required functionality for Xdrip....

All functions required are mentioned in the original post.

**Comment by tolot27** [comment]
@Seithx Maybe the Always On Display (#1625) is an option for you. You can also try Tasker to configure your requirements. Some infos can be found in issue #122.
The few developers actively working on xDrip don't have time to implement every feature, especially not, if workarounds (may) exist.
