### ISSUE TITLE
Ticwatch E2 as standalone collects data from G5 every 10 minutes (not 5min)

### ISSUE THREAD

**Issue by aviadp81** [NightscoutFoundation/xDrip#1121]
Hi, I'm using Ticwatch E2 as standalone unit ,it works fine, but it collects data every 10 minutes, and not every 5 minutes like it suppose to do.
I entered into Bluetooth properties on the watch and saw that every 10 minutes the G5 device is shown there for 4 minutes and then disappear.
I assume it should be shown there all the time.

I'm using the latest version  (2019.12.05).

![image](https://user-images.githubusercontent.com/58710255/70478333-8507ca00-1ae3-11ea-96b6-61bd1d50402d.png)

![image](https://user-images.githubusercontent.com/58710255/70478345-8df89b80-1ae3-11ea-8ad4-9b30378a47b2.png)

**Comment by Navid200** [comment]
@aviadp81 Would you please close this issue if you have found an answer?
If not, could you please post in the xDrip support group on facebook?
https://www.facebook.com/groups/xDripG5
Thanks
