### ISSUE TITLE
xdrip not reading data from miaomiao 2

### ISSUE THREAD

**Issue by ajbesq** [NightscoutFoundation/xDrip#1124]
Miaomiao is connected in system status, but no readings are received. Have tried resetting Bluetooth and emptying cache, reinstalling xdrip, adding tags mentioned in another thread (see log), but not getting any readings. I have also tried the Tomato app and it doesn't seem to even be able to find the mm. I have used Glimp successfully in the past but wanted to try xdrip. New user so any help is greatly appreciated! 

![IMG-20191210-WA0010](https://user-images.githubusercontent.com/56056261/70585833-72e56480-1b93-11ea-85f9-bebb5a1100dd.jpg)
![IMG-20191210-WA0011](https://user-images.githubusercontent.com/56056261/70585835-737dfb00-1b93-11ea-893f-a95b4138ec5a.jpg)
![IMG-20191210-WA0009](https://user-images.githubusercontent.com/56056261/70585836-737dfb00-1b93-11ea-8240-f60287a10d73.jpg)

**Comment by tzachi-dar** [comment]
Which xDrip version? are you using the newest version?

**Comment by ajbesq** [comment]
Was using version 1905181006. Just updated to 1910270800, reset Bluetooth cache and now it's working! Thank you!!
