### ISSUE TITLE
Basal rates needed!

### ISSUE THREAD

**Issue by Nemz716** [NightscoutFoundation/xDrip#1125]
Please can basal rates and the ability to add various temporary basal rates be added to x-Drip+.

Thank you! 😁

**Comment by gaykeong** [comment]
I will totally support this, especially for those on pump, so that we can enter different basal rate for specific time segment and make adjustment for temporary Basal rate change, this is implemented on nightscout already, so please add that inyo xdrip too. Thanks!

**Comment by Navid200** [comment]
Closing this due to getting no response.

Can be reopened if you will kindly explain why this is needed considering what is stated in https://github.com/NightscoutFoundation/xDrip/issues/895.
