### ISSUE TITLE
G6 - Watch no longer syncing data to phone

### ISSUE THREAD

**Issue by meatychunks99** [NightscoutFoundation/xDrip#1127]
Started a new sensor last night. Between stopping the old and starting the new sensor I upgraded to the latest stable release.

After a couple of hours of warming up, the SSW3 started picking up readings - I have settings set to force watch as collector. However, the phone was showing 'Unknown G6 State'.

Eventually, I changed settings to force the phone to collect readings, and it connected and received the missing readings. It also pushed the readings to the watch.

The watch is used without the phone for most of the day (my daughter is wearing the sensor). She takes the watch to school and leaves the phone at home - we use the phone to sync with tidepool and with my phone during the night so that I receive alerts.

However, having switched off the option to force the phone to use the watch as collector, any data that is collected by the watch is not synced with the phone (this has always been an issue). We therefore have gaps in her data record, which we need for sharing with the medical team. Forcing the watch to collect had fixed this in the past, but this is the first time I've seen the watch collecting data but not pass it directly to the phone.

The system status is showing that the watch is collecting, it shows how long ago the watch got glucose data - it simply won't share that data with the phone.

I have since downgraded to the release version we were using previously, to no effect.

Any help very gratefully received.

**Comment by meatychunks99** [comment]
Surprised that no-one else has seen this issue. On the slim chance that anyone encounters this in future, I managed to resolve the issue this morning after using the option to 'refresh wear DB'.

There was nothing that I could see in the log reporting an issue - don't know if this scenario is reportable in the app.

**Comment by Navid200** [comment]
Closing issue as it has been resolved the next day.
Please kindly close the issue you open if you don't need support any longer.
