### ISSUE TITLE
Xdrip changes lock screen wallpaper

### ISSUE THREAD

**Issue by kaloyansarafov** [NightscoutFoundation/xDrip#1128]
I am using the samsung galaxy A50 currently and xdrip keeps changing the wallpaper to black with my current BG on the top left (see attached screenshot for more details) and I am wondering if this is a bug or if there is a way to fix it / turn it off.
![Screenshot_20191213-175916_Google 1](https://user-images.githubusercontent.com/53744293/70814288-d78f0200-1dd3-11ea-9acf-e5c4122e9294.jpg)

**Comment by aljinovic** [comment]
You can disable this in:
xDrip+ Display Settings > Number Wall on Lock Screen -> Use on Lock screen (OFF)

Also, you can keep it enabled and configure the wallpaper in "Configure Number Wall"

**Comment by Flalifred** [comment]
Are you using with DeCom G6?

**Comment by Lipman2** [comment]
For some reason, the top of the numbers is cut off on my phone (Pixel 5, Android 11), regardledd of the size and position I set. Am I missing something?

**Comment by tolot27** [comment]
@kaloyansarafov Is the problem solved? If yes, please close this issue?
