### ISSUE TITLE
G6 firefly (8G) 10-day restarts failing

### ISSUE THREAD

**Issue by scorchclaw** [NightscoutFoundation/xDrip#1129]
Since getting a G6 with an 8G serial number restarts on 10-days have failed. Saw previous posts advising to turn off preemptive restart, and other posts from months ago saying restarting these was impossible. Has anyone had any luck with either restarting them or looked into the how of dexcom blocking it to start working around it?

**Comment by joelm335** [comment]
I am not trying to be nasty, but there are hundreds of post in the Facebook group with instructions as to how to restart a sensor with an 8G/H transmitter.  You will need to remover the transmitter for 15 mins.  Do a search for details

**Comment by StephenBrown2** [comment]
Also read this: https://seemycgm.com/2019/08/01/restarting-dexcom-g6-sensors-updated/

**Comment by tolot27** [comment]
It is also discussed in #963 and #1084. Hence closing as a duplicate.
