### ISSUE TITLE
Sync disabled

### ISSUE THREAD

**Issue by doc77** [NightscoutFoundation/xDrip#113]
I have my phone set as the sync master and my tablet set as a sync follower. Last night sync stopped. I just looked at it now and saw that on the tablet "Disable all sync features" was checked. I thought that was strange because I hadn't touched the tablet since before sync was discontinued last night.

I waited for sync to resume, but it did not. Rebooted with no success. Then I looked at my phone and was astonished to see that "Disable all sync features" was checked there too! Reboot and sync has resumed.

This leads me to believe that there may have been a problem with the latest nightly apk. I updated both the tablet and phone last night before the sync behavior was disabled. Has this problem been previously reported?

**Comment by jamorham** [comment]
There were changes in the most recent nightly relating to disabling the sync processing earlier in the application life-cycle if that setting is enabled but looking at the code I can't see how that could result in the setting becoming enabled by itself.

Do you think there is any possibility that you could have enabled that setting previously?

**Comment by doc77** [comment]
@jamorham  No, I am certain that I did not enable the setting on either the phone or the tablet. The last thing I did before I went to bed the other night was update both devices (4/28/17 nightly). It was at that time the sync stopped until I discovered the problem the next day.

**Comment by jamorham** [comment]
Hmm. ok. So it is the May 3rd nightly which contained the changes to the sync subsystem. Can you confirm which version it was that you installed which gave you the problem?

**Comment by doc77** [comment]
7.98 MBxDrip-plus-20170425-b79a73d.apk

It was the 4/28 nightly. The 5/3 had not yet been posted.
