### ISSUE TITLE
Readings not matching true values

### ISSUE THREAD

**Issue by Neusegura** [NightscoutFoundation/xDrip#1131]
Hello everyone,

I recently got the miao miao 2 and downloaded tomato app....Tomato has not worked at all for me, no values matched the true ones, the graphs look crazy, and the alarms are not working well...so i just deleted it because I just cannot cope with it anymore.

I downloaded xDrip just now, before deleting tomato. but...do I need the Tomato in order to use Xdrip??

I have the librelink app which I always use to scan on my freestyle, but the values from it are not matching the xdrip values ( there is over 20mgdl difference between both - which also happened with tomato) ...even though i calibrated both - pls send help :( 

If not i will just send the miao miao back...

Thank you!!

**Comment by tzachi-dar** [comment]
It is not clear what are the true values that you refer to. Are this the librelink values?

It is also not clear what sensors you have.
In any case, please make sure you have the latest xDrip and install the OOP based on instructions from here:
https://medium.com/@miaomiaoreader/how-to-make-libre-us-14-days-sensors-work-with-miaomiao2-on-xdrip-35b431a40940

**Comment by Navid200** [comment]
@Neusegura Would you please close this issue if you are satisfied with the suggestion you have received?
Otherwise, would you please respond to it?
Thanks
