### ISSUE TITLE
calibration limits for libre2 too small

### ISSUE THREAD

**Issue by keencave** [NightscoutFoundation/xDrip#1138]
The Libre2 calibrations limit of +-20 mg/dL for the intercept seems to be too small. I recommend to open it up to +-30 mg/dL. 
Reason/test results: My last Libre2 has had a difference of +35 mg/dL between raw and blood readings (blood was higher) which was constant for at least the first 12 days. The last two days the difference increased to 45 md/dL. I used modified calibration limits with good success. +-30 should be save instaed of 20. This results in a effective low limit of 69 as the libre2 is limited to raw 39.

**Comment by LubomirKovalcik** [comment]
Same problem here. 2 libre2 sensors are 3mmol off glucose readings

**Comment by Navid200** [comment]
I have been told that this has been solved.  So, I am closing this issue.
Please reopen if I am making a mistake.
Thanks
