### ISSUE TITLE
considering speed of glucose changing and compare to blood glucose level

### ISSUE THREAD

**Issue by Brunchen** [NightscoutFoundation/xDrip#1141]
Hello,

I am using the xDrip+ and Libre 2. In xDrip+ several types of calibration exists. At the official website a video is shown (Last one with the train, title: How does the Sensor reading compare to Blood Glucose reading?) https://www.freestylelibre.com.au/resources#. 

Important here is, that the blood glucose ist always faster, than the libre 2 values. This is important, if the blood glucose is changing. The more it changes, the bigger is the difference between Libre 2 Values and blood glucose values.

Well I have the following question:
Does xDrip+ in the newest version considering this?

I do not have any software developer skills, so I have the idea to include the following equation, if it is not already implemented.

BC(t) = LC(t) + dLC(t)/dt * dt,xdrip+ * NB

known values
--------------
LC(t) = Libre glucose level, raw values (white dots in xDrip+)
dLC/dt = Derivation according to time , average speed of last/newest 3 or 4 LC(t) values, here dt represents the whole time of 3 or 4 values.
dt,xdrip+ = 5 min, every 5 mins the BC(t) will be updated

![Libre2_RawValues](https://user-images.githubusercontent.com/59091948/113685153-3b72c380-96c6-11eb-8897-69dde0caa258.png)

unknown values
-----------------
NB = calibration factor, i guess this will be between 0 and 1, easy to determine

target value
------------
BC(t) = calculated blood glucose level, we want to know, ease to calculate now

If you use this equation, the BC value will be lower, if LC is falling. And BC will be higher, if LC is rising up, shown in the official video of libre 2.

Please, what Do you think about this?

Thank´s for your Answer.

Please excuse my bad english.
Greetings

Bruno

**Comment by birdfly** [comment]
good idea, but how we calculate the NB factor for you mentioned that it depend on personal data

**Comment by Brunchen** [comment]
Hello, 

NB factor is an input value in xdrip+ and needs to be determined by finger stick measurment only once.
Please look in my attached excel sheet.

Thank you very much.

[speed of glucose.xlsx](https://github.com/NightscoutFoundation/xDrip/files/5041363/speed.of.glucose.xlsx)

**Comment by birdfly** [comment]
Hello,thanks for your info

based on the equation , it is still a liner model but with a fixed slope for Libre reading,the 2nd section【dLC/dt * dt * NB】work as offset. 

Theoretically, whatever calibration or correction ,we have to adjust both [slope] and [offset] at the same time . In your equation, the slope was fixed.

BTW ,I am still confused about the NB ,what is the definition and the way about how to calculate .

thanks

**Comment by Brunchen** [comment]
Hello,

> based on the equation , it is still a liner model but with a fixed slope for Libre reading,the 2nd section【dLC/dt * dt * NB】work as offset.

yes, but this offset is not static/constant any more.


> Theoretically, whatever calibration or correction ,we have to adjust both [slope] and [offset] at the same time . In your equation, the slope was fixed.

we have to pay attention to the difinition. you mean the slope of the function libre and blood glucose concentration.
in my approach, the slope depends on libre/time. thats totally different.


> BTW ,I am still confused about the NB ,what is the definition and the way about how to calculate .
of course in my suggested model we can add an additionally parameter for the slope and offset.

they can be calculated really easy, if the real blood finger pick glucose concentration is known. maybe four values a day. and then wen can vary these unknowns by using the least square method. the aim must be to equalize the calculated blood glucose and the real mesured finger picks values. this must lead to a minimize problem. and then we will get the factor NB and the two additionally for the slope and offset (your suggestion).


Of course, I am not am mathematican. If somebody has, please participate. :) 
But I think, this is a new and more precise calibration method. If somebody will or can add this into xDrip+, I will test it extensively. I will compare with the conventionally finger pick values and correlate them. Afterwards I will share my opinion and the results. 

Best regards.

Brunchen

**Comment by Navid200** [comment]
I may be misunderstanding the whole concept.

If you only calibrate when your trend is flat (horizontal), you will be OK and there will be no need to worry about the delay.

If your objective is to allow users to calibrate even when the trend is not flat, I understand the hope.  But, I would suggest that you use the recommendation of calibrating only when the trend is flat and forget about this idea.

The delay figure is just an estimate.  It varies from person to person.  It varies even for the same person when going up versus when going down.  It also could vary based on the location on the body.  There are so many different factors.

**Comment by Brunchen** [comment]
The concept is based on the measurement type. Calibration ist not neccessary and does not depend on flat trend. I never calibrated xdrip+.
The libre 2 raw values are wrong, because they are always delayed. Thes come from interstitial fluid and are not equal to the blood sugar concentration. With my equation this deficiency can be solved. 

I would be really thankful, if the equation would be implemented in xdrip+. So every can decide, whether to use it or not. Very easy.

**Comment by Navid200** [comment]
Please explain how you can resolve a delay without a time machine.

**Comment by Brunchen** [comment]
> Dexcom has a delay also. Any CGM does.

Yes, that why I want to adjust this disadvantage. No adjustment is currently being made in libre 2 and xdrip+.


> You can have a simulation that predicts what will happen to your interstitial fluid glucose later.

I think nobody wants to know the interstitial fluid glucose, because this one is not the real glucose level. The interstitial fluid glucose concentration is only required to calculate the above differential equation and should not be displayed in xdrip+. 


> Are you suggesting that we use a formula and calculate what the blood glucose should be now and show that on screen? I don't think that's a good idea because many will get confused.

Yes. I don't want anyone to get confused. I would like everyone to activate and test this correction themselves. Even if it were only possible in developer mode.

**Comment by Navid200** [comment]
> If you use this equation, the BC value will be lower, if LC is falling. And BC will be higher, if LC is rising up, shown in the official video of libre 2.

That would be erroneous under certain circumstances (close to peaks and valleys, where the sign of the derivative changes).  In other words, there are times when your blood glucose is increasing while your interstitial fluid is decreasing, and vice versa.

Think about when you have a meal.  The blood glucose starts going up and with a delay so does interstitial fluid glucose.  Eventually, your blood glucose reaches a peak and switches direction and starts going down.  However, your interstitial fluid glucose does not reach its peak at the same time.  It continues to go up for a while before it switches direction.

According to what you are saying above, your calculation will constantly raise the calculated blood glucose as long as the interstitial fluid glucose is increasing.  But, that's not what always happens in reality.

**Comment by Brunchen** [comment]
I do not agree with you. I can not understand why the glucose concentration in the blood increases while the interstitial fluid decreases. Let us assume this is the case, then the libre 2 measuring system would lose its approval and will be no longer used.

The concentration of glucose in the interstitial fluid depends only on the glucose concentration in the blood, because it reacts much faster. Never the other way around.
This is important for understanding and the basis of the abbott libre 2 measurement system.

The discussion without graphs and data does not get us any further here. Therefore I propose the following, if the differential equation is implemented in xdip+ (for the calibration plugin "none"), I want to share my experience, parameters and graphs here and make them public to other users. I am very optimistic that this will be successful. The addition of a few lines in the source code is probably faster than long discussions here.

Then we can scientifically analyze the data, discuss them and come to a conclusion.

**Comment by Navid200** [comment]
Even if a developer does what you hope, it will not be merged before similar questions are answered.

Have a look at the snapshot of the clip you linked in your first I have attached to this post.  You can see that blood glucose is going down while the interstitial fluid glucose is still going up.
![Screenshot 2021-04-08 082752](https://user-images.githubusercontent.com/51497406/114026725-90d4df00-9844-11eb-8e3c-93ee48f886fa.png)

It's because of the delay.
There is no way to know what the slope of the blood glucose is if all you have is the slope of the interstitial fluid.

**Comment by Navid200** [comment]
I would like to close this issue.
You can open a thread in the forums to discuss if you like.
https://github.com/Navid200/xDrip/discussions

**Comment by Brunchen** [comment]
The graphic is just a simple scheme. In my opinion this influence is available, but can be initially ignored. The first step must be to implement my above equation. That means, the locomotive(BG) and wagon(SG) are at the same side of the hill (increasing slope or decreasing slope). 

> It's because of the delay.
> There is no way to know what the slope of the blood glucose is if all you have is the slope of the interstitial fluid.

The slope of the blood glucose is not needed. Please check equation.

After this long and unsuccessful discussion, I have to assume that my equation suggested above will not find a way into xdrip + in the future. What a pity.

**Comment by tolot27** [comment]
> I think nobody wants to know the interstitial fluid glucose, because this one is not the real glucose level.

This statement isn't true. The interstitial fluid glucose level is indeed a real glucose level because it gets the glucose from blood capillaries. It is highly discussed whether interstitial fluid glucose should gain more attention during therapy. It plays an important role for CGM, already.

> After this long and unsuccessful discussion, I have to assume that my equation suggested above will not find a way into xdrip + in the future. What a pity.

Discussing potential features is important, always. Our resources are limited and we try to focus on fixing existing problems. If you could provide scientific literature which supports your idea, this will increase the change to get support sometimes in the future.

What you can do already is fetching the values from SQLite database and do you own analyses. You can also try to hire a developer which implements the idea for you and propose a PR.

**Comment by Jon-b-m** [comment]
Late to the game but you’re all making the assumption that blood glucose is before interstitial glucose and therefore more ”real”. But you can argue it’s the other way around. Interstitial glucose is affecting cells before blood glucose and therefore more important and more related to your symptoms of glucose levels (most importantly the low glucose).
