### ISSUE TITLE
Please provide Instructions for automated backup

### ISSUE THREAD

**Issue by Navid200** [NightscoutFoundation/xDrip#1145]
I have seen instructions for transferring the history to another phone.  So, you will not lose the statistics when you move to a new phone.
But, what happens if you lose your phone?  

It would help if it was possible to set up an automated backup routine.  For example, say you backup the data once a week.  Then, if you lose your phone, you will only lose one week worth of data at the most.

Is there an easily accessible file (please identify how to access) that I can backup, using an automated mechanism, and transfer to another installation of xDrip on another phone that would transfer the history?
Then, if I lose the phone, I can use the backups.

**Comment by UberQueiroz** [comment]
Have you discovered a way for backing it up?

**Comment by Navid200** [comment]
No,
I gave up.
I set up Nightscout. The first time, I saw the instructions for Nightscout, it seemed too complicated.  It took a while to set it up.
Now, what is stored on Nightscout is all my measurements, which is what I needed to be preserved in case I lost my phone.  So, mission accomplished although not as initially intended.

**Comment by UberQueiroz** [comment]
Do you know if there's a way of pulling back data from Nightscout to xDrip?

**Comment by Navid200** [comment]
Enable the following.
Settings/Cloud Upload/Nightscout Sync/Download data

But, Nightscout is more capable anyway.  I personally don't care if XDrip does not have all my measurements as long as Nightscout does.

**Comment by UberQueiroz** [comment]
Mine was already on, but it have never downloaded the nightscout database. I think maybe that's due to my plugins enabled on Heroku website settings. Can you tell me what plugins are you currently using?

**Comment by Navid200** [comment]
I haven't done any customization.  I don't know what I'm using.  Just the defaults.
I don't know if it has downloaded anything for me either.

**Comment by tolot27** [comment]
Settings -> Less common settings -> Save Database Daily

But you still have to automate the upload.

**Comment by Navid200** [comment]
> Settings -> Less common settings -> Save Database Daily
> 
> But you still have to automate the upload.

I don't think that's a solution.
Nightscout is a solution.  Because it does not create redundant data on the phone and it backs up the data off the phone.
