### ISSUE TITLE
No sound of BG Readings Missed Alert in silent mode

### ISSUE THREAD

**Issue by ARkaine2** [NightscoutFoundation/xDrip#1147]
I use:
Libre(1) sensor.
Miaomiao2 transmitter.
Honor 8A smartphone (as reader).
xDrip application.

xDrip sends message (about/when "BG Readings Missed") in Android notification panel, but it is without sound.
"Override Silent Mode" option in alerts settings is turned on and sound for alert is selected.

What can i do to prevent this?

**Comment by charliebravoAT** [comment]
Have the same issue since updating my Sony XZ2 Compact to Adnroid 10. Before updating, everything worked fine.

**Comment by Navid200** [comment]
@ARkaine2 Would you please close this issue if your question has been answered?
Otherwise, could you please post in the xDrip support group on facebook?
https://www.facebook.com/groups/xDripG5
Thanks

**Comment by Navid200** [comment]
Duplicate:https://github.com/NightscoutFoundation/xDrip/issues/193
