### ISSUE TITLE
Need help on: alarms in the phone and the smartwatch

### ISSUE THREAD

**Issue by etogonza** [NightscoutFoundation/xDrip#1155]
I have searched the forum but I have not managed to find an answer to the following. I need the alarms to only vibrate on the smartwatch (wear os) and not ring or vibrate on the phone.

it is a function that  WearOS already incorporates as standard "silence notifications on the phone when you wear the watch "and it works in other app notifications, but not in xdrip.

Is there any possible way to do it? Normally what happens to me is that the alarms sound on both the mobile and the clock.

I only find this working but i think there would be more easy way:

- Turn on alarms in watch.
- Put phone in airplane mode so now watch is fully standalone.

That helps me to sleep better but obviusly during the day  I can´t hold my phone in airplane mode.

Thank you very much.
![81813326_2536572036440515_5820595252121042944_o](https://user-images.githubusercontent.com/57047933/71765265-a39a8e80-2ef2-11ea-8e0f-4a863b35646d.jpg)

**Comment by Navid200** [comment]
> I need the alarms to only vibrate on the smartwatch (wear os) and not ring or vibrate on the phone.

If you don't want the alerts to vibrate or ring on the phone, you can choose the silent volume profile on the phone.

If this does not work for you, please open a discussions and we can talk:
https://github.com/NightscoutFoundation/xDrip/discussions
