### ISSUE TITLE
xDrip is closed when clearing running apps

### ISSUE THREAD

**Issue by LubomirKovalcik** [NightscoutFoundation/xDrip#1156]
Hello,

 I have change my phone and libre sensor to version 2.

Now I have:
**xDrip**: 6d4d283-2019.10.27
**Data source is:** Libre 2 Patched App

**Phone:**
Xiaomi mi 9
Android version: 10 QKQ1.190825.002

**Problem is:**
When I close all running apps in phone, then also xDrip is closed including floating notification. And xDrip is no more receiving any data or showing new data on smart watch. 

I have checked Notification Channels in Glucose Alerts Settings
I have checked Run Collector in foreground in Other misc options.

I used to have:
xDrip: 14fecb8-2019.01.10
Data source: Libre bluetooth (MiaoMiao)

Phone:
Xiaomi Redmi 5 plus
Android version: 8.1.0 OPM1.171019.019

Problem was not occuring here, I was able to clear ram / close all running apps in my phone and xDrip keep running.

**Comment by Navid200** [comment]
@LubomirKovalcik Would you please close this issue if the problem has been resolved?
Otherwise, could you please post in the xDrip support group on facebook?
https://www.facebook.com/groups/xDripG5
Thanks
