### ISSUE TITLE
Automatic calibrations with contour next one BT BG meter

### ISSUE THREAD

**Issue by etogonza** [NightscoutFoundation/xDrip#1157]
I need help please. It doesn't calibrate automatically, despite BG is flat and I've checked the option "automatic calibrate if conditions are ok". 
Last version of xDrip (nightly 31/12/19) I have the forzed watch collector function active
![2](https://user-images.githubusercontent.com/57047933/71765345-cf6a4400-2ef3-11ea-9ba9-081e4cf94550.jpg)
. What is happening? Thanks.

**Comment by Navid200** [comment]
@etogonza Would you please close this issue if you have got an answer to your question?
Otherwise, would you please post in the xDrip support group on facebook?
https://www.facebook.com/groups/xDripG5
Thanks

**Comment by Navid200** [comment]
If you have a similar issue, please first consult with the user community.  Links provided above. Please only open an issue if you are sure there is no solution with xDrip as is.
Please open an issue only to report a bug or to submit a feature request with no work-around.
Please don't open an issue just to ask a question.
Thanks
