### ISSUE TITLE
Put treatment reminders in notification channel

### ISSUE THREAD

**Issue by kalleelmer** [NightscoutFoundation/xDrip#1162]
The treatment reminder notifications end up in Other/Uncategorised. It would be helpful to have them in a notification channel so that sound, vibration and other preferences could be customised in Android settings. On my phone, these notifications are currently silent, and I always miss them.

**Comment by Navid200** [comment]
Is this still the case?  
What xDrip release have you tried?   What phone and what Android release?
Thanks

**Comment by kalleelmer** [comment]
@Navid200 Closing this since I am now using AndroidAPS with Nightscout in upload-only mode, so I can't tell if the issue persists.
