### ISSUE TITLE
Treatment points on Wear OS watch show at bottom of graph.

### ISSUE THREAD

**Issue by kalleelmer** [NightscoutFoundation/xDrip#1163]
I have enabled the option "Show Treatments" under "Android Wear Integration" and these items now show on the watchface. However, the finger sticks are at 0 on the vertical axis. The graph would normally zoom in on the target range, unless there are low or high values, but the finger sticks cause it to always range all the way down to 0.

**Comment by steve8x8** [comment]
Which xDrip version are you using, and - more important - what's your unit of BG measurement?

**Comment by kalleelmer** [comment]
My version is the stable release 6d4d283-2019.10.27 and I'm using mmol/l.

**Comment by Navid200** [comment]
@kalleelmer Have you asked from the user community?
You can do that using the following.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

**Comment by kalleelmer** [comment]
@Navid200 I am now using another watchface from AndroidAPS, so this is not applicable to my situation anymore and I don't know if the problem persists. From my point of view, the issue could be closed.
