### ISSUE TITLE
Feature test: Measurements/treatments syncing

### ISSUE THREAD

**Issue by zetric** [NightscoutFoundation/xDrip#1164]
Hi,

I did some testing of common steps concerning creating measurements or treatments. E.g. what happens if I create/change a measurement in xDrip/Nightscout and see if this is on the one hand possible in general and on the other hand synced to the other system.

See attached PDF with the test results.
[Nightscout_xDrip_Updates_Tests.pdf](https://github.com/NightscoutFoundation/xDrip/files/4038944/Nightscout_xDrip_Updates_Tests.pdf)

Example description of the first testcase for a better understanding:
I can create and delete BG check values in both systems and they are synced. Deletions are only possible in xDrip. Changes are not possible in both systems. The deletion of a value created in xDrip or Nightscout is not synced.

Hope that helps. Would be very helpful if more syncing would work in the future.

**UPDATE:**
Versions:
xDrip 6d4d283-2019-10-27
Nightscout 13.0.1 (docker)

Added versions in test sheet.

**Comment by tolot27** [comment]
Isn't this related or duplicated by #1196, is it?

**Comment by Navid200** [comment]
Thanks

We now have discussions.  You can post there and use the show and tell category.
https://github.com/NightscoutFoundation/xDrip/discussions
