### ISSUE TITLE
Trend arrow output

### ISSUE THREAD

**Issue by sfriedriszik** [NightscoutFoundation/xDrip#1165]
There is a discrepancy between the display of the trend arrow on the main screen and the output on the web server.
The information in the JSON interface differs greatly from the display on the main screen.

**Comment by Navid200** [comment]
@sfriedriszik Would you please provide more detail?
Can you show screenshots so that we can see what you mean by discrepancy?
Also include the xDrip version and any other detail we need to recreate and observe the problem.

**Comment by Navid200** [comment]
Please add your voice to the existing issues.
https://github.com/NightscoutFoundation/xDrip/issues/414
