### ISSUE TITLE
670g and xdrip

### ISSUE THREAD

**Issue by Mr-Enigma** [NightscoutFoundation/xDrip#1171]
hi, currently using libre + mm2 on xdrip but just got the 670g.

is there any way at all to connect the 670g to xdrip aswell aa the libre? would be great to use xdrip to send insulin requests to the pump.

**Comment by steve8x8** [comment]
You may *read* the pump, using the 600SeriesUploader - but controlling the pump, from xDrip or AAPS or younameit, it not possible (and perhaps never will be).

**Comment by Navid200** [comment]
Please consult with the user community.  Currently, we have the following two channels.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Please open an issue only if you have confirmed there is a bug and you are sure there isn't one already filed.  Or, if you want o submit a feature request that has no work-around and there is no existing issue already for it.
Thanks
