### ISSUE TITLE
Compile with current tool suite (v28) fails

### ISSUE THREAD

**Issue by juehv** [NightscoutFoundation/xDrip#1177]
I currently try to develop a new feature but the compilation fails with a current tool suite. I had to update several libraries (android-support, some wear apis) to make it build properly. Now I'm a bit concerned that the changes probably will not be merged to the main branch later. Do you have suggestions to proceed?

Cheers!

**Comment by Navid200** [comment]
You can post in the forums.
https://github.com/Navid200/xDrip/discussions
We can talk over there.

We are asking users to use this issues platform for either reporting a bug or requesting a feature.

**Comment by tolot27** [comment]
@juehv It is important not to update the Android Gradle Plugin and not to migrate to Android X. If you follow this advice, building the app and wear should be smooth. For further discussions please follow the link abouve.
