### ISSUE TITLE
Integration of watch Watlaa

### ISSUE THREAD

**Issue by xkamor** [NightscoutFoundation/xDrip#1179]
Watlaa is a new smart watch designed for diabetes. I asked the manufacturer if they will integrate it with xdrip+ and got this answer: 
Hi Marko

For xdrip android we do not know any timeline.
Xdrip swift for iphone is ready soon.
Diabox maybe 1-2 months.

Sorry for the wait.
Watlaa team

Is it possible to integrate from this side once they will update their firmware to support Xdrip swift or Diabox?

**Comment by cmarcosmoneo** [comment]
Hi, 
I am very interested on this topic. 
I would like to connect the Miao Miao 1 to the phone with XDrip+ Android (or IOS if Android version available yet) and the phone connected to the Watlaa watch. But when the phone is not near enough to the Miao Mioa 1 I would like the watch to be connected directly to the Miao Miao uisng the option "Force watch colletion". 
Does anyone know if this is possible? And can this be done with other watches?
Thanks a lot in advance!

**Comment by Navid200** [comment]
@xkamor Would you please use the support channels for asking questions?
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks
