### ISSUE TITLE
Missed Readings alert uses same sound as Forecasted Low

### ISSUE THREAD

**Issue by jamespaulley** [NightscoutFoundation/xDrip#1188]
When you choose a sound for Forecasted Low Alerts, the same sound is used for Missed Readings Alerts. Can we have independent sound selection for these, as users may rely on specific alert sounds to convey meaning.

**Comment by Diabeticliberty** [comment]
I may be misreading your post here and if I am then I will apologise in advance. The thihgvis though I have just looked at the 'predicted low sound' setting in the Extra Alerts section of the Alarms And Alerts menu section of Xdrip+ and you do have the option to set the alarm sound to pretty much anything in your phone or on your micro SD card.

**Comment by jamespaulley** [comment]
Thank you for replying. Yes you can select any sound for the Predicted Low alert, but then that sound is automatically used for the Missed Readings alert as well. It is not possible to have them as separate sounds as you cannot currently choose which sound the Missed Reading Alert. Actually, it might be BG Falling Fast alert sound that is overriding the Missed Readings Alert.

The request could be summarised as:

Please add the ability to select different alert sounds for the following items:
- BG Falling Fast and BG Rising Fast separately (currently there is one setting for both sounds)
- Missed Readings (Currently this seems to take the setting from BG Falling Fast)

I rely quite heavily on the meaning of each sound, so it would be good to be able to set them all properly.

**Comment by Diabeticliberty** [comment]
Yes I just checked and you are absolutely correct. I will have a bit of a tinker with my own tonight and if I manage to sort anything will report back to you tomorrow. In fact I will report back either way.

**Comment by jamespaulley** [comment]
Thank you! Basically it would be good to have a different unique sound for
all of the following alarms:
- Low alert
- Urgent low
- High alert
- Missed readings
- BG falling fast
- BG rising fast
- Low predicted

A bit more like what you can set in the official Dexcom G6 app.

By the way, if anyone wants them, I use the sounds from the Dexcom G6 App,
as they're quite well designed to convey each meaning.
https://drive.google.com/open?id=1_lTWcSuFgCE6cvpGeP0l2KorhxnOZ169

**Comment by Diabeticliberty** [comment]
Hello again I have been through pretty much every setting on my own set up and it seems that you are absolutely correct in your original post. The alarms are indeed the same

**Comment by jamespaulley** [comment]
Is there any update on getting this fixed? Thank you.

**Comment by jamespaulley** [comment]
Has any progress been made on this? I see it as being quite important personally.

**Comment by Navid200** [comment]
@jamespaulley Thanks for reporting this.
This seems quite the same as this one: https://github.com/NightscoutFoundation/xDrip/issues/555

Unless you disagree about the similarities, it is best to post in the same thread to signify that more people have the same request as opposed to opening new issues.  The more open issues we have, the less attention each single issue receives.

I suggest that you close this issue and add your voice to the other existing issue.
Thanks
