### ISSUE TITLE
XDrip G5, Android 10, Oneplus 7 Pro phone 

### ISSUE THREAD

**Issue by charding99** [NightscoutFoundation/xDrip#1190]
I have good connectivity during the day (with a few lost connections), But, during sleeping hours, my phone loses connection to my G5 every night. I have tried many settings without any success. I am guessing it is some type of deep sleep that is occurring with Android 10 because this did not happen on Android 9. I can always get it to reconnect by using "Restart Collector" in the "System Status" screen. I do have "Aggressive service restarts" enabled under "Less common settings" but it is not helping. I do have Xdrip marked as "Not Optimized" in Battery Optimization and have tried many of the suggestions I have seen here.  If anyone has foolproof workarounds, please post them. BTW, I am on OxygenOS 10.3.0

**Comment by 0xBABA** [comment]
I had a similar issue tonight with an OP6 (after using a nightly build that solved connection issues after i upgraded to Android 10). For me this was an unusual night since i did not plug in my phone to a charger overnight. does this occur when the phone is connected to power?

**Comment by charding99** [comment]
I rarely charge my phone at night. However, 2 nights ago, I had it plugged in all night and never lost a connection. So, it appears that something in Android 10 is affecting Xdrip when the phone is not plugged in and not in use for more than a certain amount of time. For me, it seems to be about 40 minutes after no use at night.

**Comment by 0xBABA** [comment]
This might also be related to both of us being OP users. OP is known for its battery saving strictness in doze mode (or whatever its called these days). I am not sure anything can be done about this on Xdrip development side. I believe there's a wake-lock feature hidden somewhere in Xdrip settings. You can try toggling that and see if there's any improvement - although beware this might turn you into an overnight charger kind of person....

**Comment by Navid200** [comment]
Have you disabled battery optimization of xDrip in Android settings?

**Comment by charding99** [comment]
I have disabled battery optimization for Xdrip but not other apps. It has
been working successfully for at least 8 months now. I am not sure whether
a phone update fix the issue or am App update fixed it. I try to stay
current by downloading new versions from github.

Craig Harding

**Comment by Navid200** [comment]
If this problem has not presented itself for 8 months, would you please close this issue then?
Thanks

**Comment by charding99** [comment]
Either a Phone firmware update or a newer version of xDrip resolved this issue.

**Comment by Navid200** [comment]
Thanks so much for the update

**Comment by allanlaal** [comment]
Issue persists on a generic Android 10 phone

Only keeping the System Status page open in xdrip will quarantee a sync

**Comment by Navid200** [comment]
@allanlaal Please post a screenshot of the G5/G6/Dex1 status page.

**Comment by allanlaal** [comment]
FIXED BY settings: bluetooth wake lock hack enabled
