### ISSUE TITLE
how to manage different insulin products with the same profile but different concentrations

### ISSUE THREAD

**Issue by gruoner** [NightscoutFoundation/xDrip#1192]
at the end of #1080 it came out we have an issue when managing the list of insulin profiles.
On the (worldwide) market we might have insulin products which provides the same insulin profile (curve of activity) but different concentrations.
Currently each configured and available insulin profile has a fixed defined concentration (defined in insulin-profiles.txt). The "normal" way would be defining a new profile (similar as quite the same one) but with a different concentration and name the profile with the defined concentration --> this will lead us to a very long list and on some mobiles (mostly with reduced screen sizes or in portrait) someone even cant see the full / long profilename and thus chooses the wrong one.
So we need another solution managing this list......

Any suggestions are welcome because i'm just using tablets and thus not stressed out with that issue......

**Comment by peeyes-dev** [comment]
You are all doing great service in developing xDrip+. 

For this, I have a suggestion. In the Treatment Profile Editor page. we can remove "acting" from description to save on screen real estate. In that space, we can add an integer multiplier field against applicable insulin [perhaps integer values of only 1 and 3 are applicable] which basically is used to either alter the concentration of the "base value" which is U100 or use the type and multiplier values to internal select different profiles onset/peak/duration as applicable from insulin-profiles.txt. Any thoughts. 

My first post here. Let me know if anything is amiss. Thanks.

**Comment by Navid200** [comment]
@gruoner Can we close this issue please?
We are asking the user community to use the support channels for asking questions instead of opening issues.
I hope you are OK with that.
Thanks
