### ISSUE TITLE
No Alarm sounds / Redmi Note 4

### ISSUE THREAD

**Issue by Bayo84** [NightscoutFoundation/xDrip#1193]
Good Evening

Until now i use Glimp. Now i move to xDrip+. I have one big problem. I set up alarms, but only two (high sugar / low sugar) work with tone for which I have set xdrip Default. Others work without sound. Information about the alarm appears (e.g. Other alert bg rising fast), the phone vibrates, but there is no sound. The phone is not muted, I tried with various alarms (system sound, downloaded MP3, etc.). Has anyone had such a case? Thank you for your help.

Bayo84

**Comment by razyogev** [comment]
@Bayo84 
Managed to resolve the exact same issue, at least for now, by removing both alarms and recreating them from scratch

**Comment by Bayo84** [comment]
I solved the problem. Settings --> App Management (or similar i have polish menu) -->xDrip+ --> Notifications (or similar) --> Allow sound.
Have a nice day.

**Comment by Navid200** [comment]
Closing as it seems you found a solution.
Thanks
