### ISSUE TITLE
Treatment syncs between master and follower (and viceversa)

### ISSUE THREAD

**Issue by Foxandxss** [NightscoutFoundation/xDrip#1196]
I have a master xDrip with miaomiao uploading to nightscout and also a follower that gets the data from nightscout.

If any of those two creates a new treatment, say 5 units of insulin, I can see the bolus on the phone that was created and also at nightscout. The other phone says there is no IOB and the green curve at the bottom is not displayed.

It is bad because I am the follower and I am the one that enters the boluses and my GF is always asking me: "Hey, do I have insulin?" She should be able to know as well.

Not sure if a bug, a missing feature or I am doing something wrong.

Thanks

PS: Adding a treatment from nightscout seems to appear on the phones. I removed it afterwards but xDrip didn't notice.

**Comment by jamorham** [comment]
One of the NightScout Follower options is to also download treatments. Check that this is enabled on both devices? I would expect it to work but if not I would say it is better to use the native xDrip+ sync feature to synchronize between the handsets.

**Comment by Foxandxss** [comment]
It is enabled in both devices. If not, adding directly at nightscout wont update the phone and it does. It is just from master to follower (or viceversa) via xDrip. Native sync is supposed to be enabled. I say supposed because it is a complicated thing.

**Comment by tolot27** [comment]
@jamorham Please assign this issue to me.

**Comment by Navid200** [comment]
@Foxandxss Is this still happening with the latest xDrip Nightly?

**Comment by tolot27** [comment]
This problem is not solved because #1403 is still a draft PR.

**Comment by Cagier** [comment]
Does anyone know if there is an earlier version of xDrip+ that does not have this issue? I would happily downgrade the follower phone to overcome this issue as we cannot see the treatments from school otherwise.

**Comment by Navid200** [comment]
As of the release on February 24, 2024, there is a new switch in the "Upload Treatments" submenu titled "Skip items from xDrip" enabled by default.
If you disable this switch, treatments uploaded by another xDrip will also be downloaded.

Please tell us if you experience any issues or have any questions.

Thanks for reporting this.
