### ISSUE TITLE
G6 sensor restarts on 81XXXX transmitter

### ISSUE THREAD

**Issue by Kaivish** [NightscoutFoundation/xDrip#1199]
Early december last year xdrip was doing the restarts/preemtive rrstarts nicely where sensor was up and running again in 5 min. Mow it fails to rrstart the sensor. It goes to sensor failed then try restart again and ends up at 2 hour warmup. One hour in it says sensor failed and starts the 2 hour warmup again. Restarts for dex g6 seems now broken. Anyway to fix this?

**Comment by nsghub** [comment]
Restarting a sensor with 8G transmitter is the same. Restarting with the official dexcom receiver works fine.

**Comment by Kaivish** [comment]
How do you restart with official receiver?
What I am hoping for is that the preemtive restart works again with the time travel option to skip the 2 hour warmup.

**Comment by Kaivish** [comment]
Rralosed when its trying the restart, it stops the sensor and starts it again and it says ready in abt 5 min, but on system status it is queued a request to stop the sensor! And it marks it as failed after that! ??

**Comment by nsghub** [comment]
I stopped the sensor on the official receiver and started it again. I think that's how xDrip does it as well. But apperently there is something different. The preemptive feature does not work with my 8G version. But your 81 should be fine.

**Comment by Kaivish** [comment]
It was fine before. But now its not working anymore. Thats the issue here. Installed the aug 2019 version. That worked fine as far as i can remember. Will try and see.

**Comment by adanvdo** [comment]
Just started an 8H transmitter today. should I turn the restarts off?

**Comment by tripmaker-j** [comment]
I'm using 8H now too. Preemptive restart became disabled. Regular restart is there but I've heard it won't work. Any hope on restoring that function?

**Comment by adanvdo** [comment]
@jamorham will this last nightly with firmware updates affect this at all? or is there still work in progress?

**Comment by adanvdo** [comment]
I can confirm auto-restarts do not work on the 8H transmitter, if the transmitter has anything to do with it. 
![Screenshot_20200222-020633](https://user-images.githubusercontent.com/26498008/75088393-9d03bd00-551a-11ea-93ad-5eb8ea0538a3.png)
it gets stuck in a loop as described in the OP.

xdrip restarts the sensor, warms up about 30-45 minutes, then logs another restart with a failed start notification. however, the status screen never displays failed, and the warmup countdown isn't reset.

after 2 failed restarts the warm-up countdown continued down to about 1.2 hours before I manually stopped the sensor.

**Comment by lazlow442** [comment]
Have had the same issue the last 3 times my 8H sensor ended. I downloaded the nightly build yesterday because I knew my sensor would be restarting today, but unfortunately it is stuck in the warm up loop. 
Has anyone been able to restart their sensor with the 8H transmitter?

**Comment by ThoR294** [comment]
Bump? Lol this sucks.  Current work around is remove transmitter, stop sensor, wait 30 min, reinsert transmitter and restart sensor.

**Comment by TheDonDan** [comment]
You're right, I am also hopping somebody finds an hack to enable preemptive
restarts again but in the meanwhile the the work around is as you
described, but if you short the sensors pins you can skip the 30 min
waiting procedure:

1.  stop transmitter in the xdrip app, wait that the transmitter is really
stopped (see status in xdrip).
2.  carefully remove transmitter (with something very slim, like a guitar
pick).
3.  short the two pins from the sensor with something conductive, (electric
wire or something else, it seam to discharge any capacitive charge on the
sensor, transmitter seams to use this info to know if the sensor was
already inserted for longer time)  this way no waiting necessary!
4.  reinsert transmitter.
5.  start it again with the original calibration code in xdrip.


After two hours you get values again, but in my experience at least the
first 12h are offset but it calms after that.

Am Sa., 25. Apr. 2020 um 18:59 Uhr schrieb ThoR294 <notifications@github.com

**Comment by Navid200** [comment]
Please don't follow the restart instructions provided here.  
Please access restart instructions on facebook:
https://www.facebook.com/groups/xDripG5/permalink/4521043737969086

@Kaivish Can you confirm that pre-emptive restart does not work for your 81XXXX G6?
Can you identify the first release that stops functioning properly with respect to pre-emptive restart?

**Comment by adanvdo** [comment]
> Can you identify the first release that stops functioning properly with respect to pre-emptive restart? 

I do not believe you will find a specific release where it stopped working since the problem is with the firmware on the firefly transmitters. When Dexcom started using these new transmitters restarts no longer worked on them

**Comment by Navid200** [comment]
@adanvdo That question was for Kaivish who started this issue.  
He has an 81XXXX transmitter.  He said that he could successfully use pre-emptive restarts.  But, later, he couldn't.  
So, to clarify:

@Kaivish If you have an 81XXXX, as you said you did in the first post, and if its firmware is 1.6.5.25, you can use pre-emptive restart.
If you cannot, please let me know which version of the code fails.

**Comment by Navid200** [comment]
This is a summary of what can or cannot be done with respect to G6 restart today.

You can only perform preemptive restart if the firmware version (shown on system status page) is 1.6.5.25.  That include all 81XXXX and some of 81XXXX.

If the serial number does not start with 80 or 81, the only way to restart requires temporary removal of the transmitter from the sensor.
One place you can see detail instructions is here:
https://www.facebook.com/groups/xDripG5/permalink/4521043737969086
If you don't have a facebook account, please ask in the Gitter room.
