### ISSUE TITLE
Adding onetouch verio flex?

### ISSUE THREAD

**Issue by bryanw20** [NightscoutFoundation/xDrip#120]
Sorry I'm kinda new (G5 & Xdrip user for only 3months now) Is this where we can ask for support & features?

My insurance only covers Verio meters; I try adding the onetouch verio flex; I can get it paired (with the phone & xdrip+). I can have it sync with its own app; but I get timeout errors when trying to sync with xdrip+
Timed out on : get new glucose records

I'm using latest nightly builds; currently xdrip ver: 381226d-2017-05.12

I'm using a Motoroloa G5plus phone, running droid 7.0

**Comment by jamorham** [comment]
I hope to get a chance to look at this next week as I've located someone with one of these meters.

**Comment by jamorham** [comment]
Can you tell me, when you scan for the meter in xDrip what is the full name of the meter it shows? It should begin OneTouch ?

**Comment by bryanw20** [comment]
Mine says: OneTouch J7RG

I can pair it with my phone.

When pairing in Xdrip it says: 
{bloop sound] Device from: LifeScan

Timed out on: Notify new glucose record


Let me know what I can do to help; not a programmer; but if you walk me thru something I can do it.
Thanks for looking into this; it would be awesome!

**Comment by jamorham** [comment]
Okay, thanks, I am working on this now. It appears that the meter doesn't comply with the well established bluetooth standard for glucose meters (that we already support), which means it instead needs special code to handle its *unique* protocol.

**Comment by bryanw20** [comment]
Of course not, why should anything covered by insurance be easy to work with... =(

But at least 2 of us in the Xdrip group would love you forever if you can figure it out!

I'll send you chocolate! ;) (or a meter if you need it)

**Comment by jamorham** [comment]
I have added support for the Verio Flex with about 500 lines of code in the June 8th nightly. Testing on Android 6 gave good results but I had less luck on Android 4.4. 

I had to alter some of the logic to accommodate it and so pairing and syncing for other devices will also need retesting.  

You need to have at least two blood tests on the meter I think before using the scan option. If it succeeds then you should get a message saying "enabled auto-start"

I found sometimes I had to turn the meter off for a while then turn it back on. Having the meter paired to multiple phones also seemed to cause indigestion.

Please test and let me know how it goes!!

Commit details: https://github.com/NightscoutFoundation/xDrip/commit/49bfb340c5fefa66cfed154a995ab1ec47122923

Release apk: https://github.com/NightscoutFoundation/xDrip/releases/download/2017.06.08/xDrip-plus-20170608-49bfb34.apk

**Comment by bryanw20** [comment]
AWESOME!  

Yes I updated this morning; and went to my meter, did the sync, and it stalled for a long while; but then connected & sysnced data! 
I enabled auto calibrate; but of course I was off by 25mml this morning; so xdrip said it will wait 15min to calibrate (steady arrow too)

I can see having the meter paired with multiple devices would be an issue; it genereates a new pairing code each time it pairs, so I assume when it generates a new code; the old code no longer works?

I will post to the xdrip group and ask for testing/feedback as well; do you still visit the group?

I saw I think one of these reqests on git hub, someone changed the treatment to all 4 at once, ie you can enter carbs, insulin, figer stick & time all on one 'page'; is that something that can be intergrated?
[Mine defaults to insulin frequently, and I'm not on insulin so I'd never input it; this would be an awesome addition also!]

**Comment by jamorham** [comment]
Okay so do you have it now working where you can take a blood test and it will automatically connect to the phone (while the phone is screen off) and sync that latest reading?

Another caveat is that there are some issues with the time synchronization. It will cause problems if the clock on the meter is changed when data hasn't been synced or on a new pairing to a phone where any of the last 15 readings had a different meter clock at the time of the test. 

It works by reading the current meter time and then calculating how different that is to the current phone time to calculate when the blood test actually occurred.  So long as you are always synced before changing the meter clock this shouldn't create any issues.  I am assuming the meter doesn't automatically adjust for daylight saving time.

If you're talking about the xDrip facebook group, I haven't ever been on there. I rely on other people to communicate there.

**Comment by bryanw20** [comment]
I have not tried with the phone screen off yet. I will tonight.

What else can I test for you?

**Comment by jamorham** [comment]
You should get to a stage where use of the meter with xDrip is completely seamless. Whenever you do a test you will get it syncing to the phone and with the automatic calibration enabled it will cherry pick the best values to use for calibration. If you are away from the phone then when you next turn on the meter or do a blood test it should sync all the previous readings (up to a maximum of approx 15 readings)

It should work when the screen is off and you shouldn't need to open xDrip app for the data to be synced and it should just work in the background forever. Those sorts of things over an extended period is what needs testing. Some of this depends on the quality of the phone bluetooth stack. The sound effects feature helps you know when its doing something even when the screen is off. You can turn this off if it bugs you.

Also you can check in the event log as you shouldn't get any entries relating to the glucose meter show up as these would normally indicate an unexpected error.

**Comment by TecMunky** [comment]
I have been using my Contour Next One meter.  I just updated to this latest version, and that meter is still working.  I also have a Verio Flex meter.  I intend to test that meter as well.  However, What problems can I expect to encounter when switching from the Contour to the Verio?  Earlier you mentioned there were problems relating to the clock on the meter - should I adjust the Verio meter clock before attempting the first sync?

**Comment by jamorham** [comment]
@TecMunky no sync before changing the clock. xDrip will work out the correct time from the offset of the meter clock from its clock but it can't do this if the clock was changed before the sync occurs, so always sync before changing the meter time. xDrip wont try to sync readings it already has so any clock confusion wont matter after a sync has occurred. The meter itself doesn't get confused but I don't really see how this is represented in the data and as the protocol is unique and undocumented I did the best I could as it seemed like a fairly small issue which shouldn't affect people during day to day use.

**Comment by TecMunky** [comment]
The clock is months off, and I need a new battery, so I will have to
correct those before I can test. So the clock will be changed before I can
sync. Considering this, what do I need to do? Should I take a couple
readings before trying to sync?

**Comment by bryanw20** [comment]
So when I got home, I left my phone sitting 10' away, screen off. Used the Verio; and before I knew it it was chirping/singing, whatever sounds it makes. 
Open xdrip and viola, there's a calibration in there! =)

I'm so happy!

Only entry in the log is:
BTGM time
prompting for cal. #mg/dl from: time stamp

**Comment by jamorham** [comment]
@TecMunky I think it will ignore readings which appear to come from a time before I implemented glucose meter support so you should be fine. Just change the clock before doing any new readings.

@bryanw20 nice one!

**Comment by bryanw20** [comment]
So I tried twice more using the flex, phone screen off, and this time it didn't auto sync.
But I think it was the flex not sending out the signal, I didn't see the little O spin on the screen.
If I went to xdrip, scan meter, it synced up again.

I think last night I did use the app for the meter to sync; so maybe I need to avoid doing that? I'll test that by not using it before my next calibration this evening.

**Comment by gwaltneyja** [comment]
Try turning the meter off and on again. Mine grabbed the 2 min old reading
straight away when it didn't right after it was taken.

**Comment by bryanw20** [comment]
I did cycle the meter, it still wasn't doing the sync emblem. I didn't want to cycle the BT as I think that triggers a new pairing code from the meter.
Will need to do some more tinkering.

**Comment by bryanw20** [comment]
OK, I think my new flex meter is flaking out. 
I tried again with phone off, but near by; no sync. but the meter didn't even try to sync, no O (sync symbol). BT icon is on.
Did a manual scan in xdrip & it sync'd
oped the onetouch app and it sync'd

but I just re-read the manual, it says it will show the BT icon for 4 hours after a reading; I just did it 15min ago, and my screen is blank.

So the awesome thing is it's working in xdrip, but now I think it's my meter not wanting to play nice.

I could try unpairing the meter, adding a couple samples, and trying pairing it again...?
I don't think I can call Verio, as it will sync with their app, and the manual says app needs to be open first.
Maybe next sample I take I'll ahve xdrip open & see what happens.

not a complaint, love the work done; just giving my feedback; don't take it away from me! =)

**Comment by bryanw20** [comment]
OK, I spent the last 2 days trying to get the Flex working with my phone! 
Ugh; even bought a brand new one (on sale $10 so not bad) But it wouldn't pair with my phone/OT app either.
Then this morning tried again & the original sync'd right up with xdrip again!

So hopefully it sticks this time & I can do some more testing!

So just being clear, it's my phone (Moto G5) that's having isssues, not xdrip!

**Comment by bryanw20** [comment]
Well it's working good for now; even did a double calibration with it automatically.

**Comment by jamorham** [comment]
The issues you've experienced may be due to android bluetooth flaking out.

Next time you don't get it syncing, try this, go in to the settings for the bluetooth glucose meter in xdrip and slide the slider at the top for off/on to turn it off and on again. Then see if it syncs after that. If it does then it implies we're losing the bluetooth connection after a while.

The meter doesn't push the data to the app, the app detects the bluetooth being enabled and the remote device coming on and then connects to it to ask for the data. The sync icon you see appears on the meter when it detects the app connecting and asking for data.

**Comment by bryanw20** [comment]
Thanks I'll try that.
I didn't think of it this morning when it did not auto sync again; I did a manual scan, it sync'd up. I'll try the slider next time.

**Comment by bryanw20** [comment]
Ok, just got home, did another meter reading, it did not auto sync; but cycle the on/off in xdrip meter sync did make it sync immediately.

So is it my phone that is stopping it?

**Comment by bryanw20** [comment]
I need to collect some more data; but it seems (atleast more often than not) after a meter sync; I lose G5 connection, I need to do a restart collector to get it back.

**Comment by bryanw20** [comment]
OK, my last 2 attempts I've needed to switch it off/on; followed by a loss of G5 signal for 15-30min after the sync.
Related??? I typically get 93-98% capture rate, a 30min drop is rare (unless out of range)

**Comment by ElyeM** [comment]
Hi, I have the verio flex, downloaded above APK, I can't turn on "Use Bluetooth Meter" setting,  it's disabled. 

Even if it's disabled, when I scan for meter I can find my meter and pair it. But not getting data. 

I have a OnePlus One phone, I can use one touch app.

**Comment by ElyeM** [comment]
Okay, scanned again, turned meter on and off, now it is working.

Thanks loads!!

**Comment by bryanw20** [comment]
I'm still only getting it to capture at random timing. It's been days of no connect; then suddenly it started working again (A new build perhaps?) but still not everytime. A day or 2 ago just out of nowhere it starting 'singing' its BT songs, I hadn't touched the meter in hours and was in another room when it happened!
I'm not losing G5 connection after a sync when it does decide to work. I have not been going into the settings an cycling it off/on either.

**Comment by ElyeM** [comment]
I have a weird issue, almost everytime after xdrip will sync with the meter to get the data, xdrip will miss next 2 readings from dexcom. 

I think it's only when I go into settings and scan for meter... 
I have to scan a lot of time otherwise it won't get data from meter.

**Comment by jamorham** [comment]
As far as I know this meter is now supported correctly. The mentioned issues I think are generic to do with various android bluetooth stacks.

**Comment by jettechfsr** [comment]
My Verio Flex is sync's ok now is readings from this meter suppose to be sent to be sent to Nightscout as well?  My Dexcom is still on order trying to get everything configured so when it arrives I have it all ready to go

**Comment by tanvirsgit** [comment]
hello, jamorham. can you please tell me what kind of processing does verio flex needs that differ from the standard ble protocol?

**Comment by rafaelrpedrosa** [comment]
@jamorham, how do i get the verie flex glucose messenger?
What should I write in which feature? so I get the data.

**Comment by rafaelrpedrosa** [comment]
@jamorham, how do i get the verie flex glucose measurement?

What should I write in which resource? then i get the data.
