### ISSUE TITLE
Problemas con enlace xdrip

### ISSUE THREAD

**Issue by gracar621** [NightscoutFoundation/xDrip#1208]
No soy capaz de conseguir abrir la aplicación de xdrip ....

**Comment by razerrazer** [comment]
¿Has intentado reinstalarlo?

**Comment by gracar621** [comment]
El archivo lo descargó pero el enlace no me deja abrirlo....no se si el problema es de mi teléfono o del mismo enlace....

**Comment by razerrazer** [comment]
Debe permitir aplicaciones desconocidas a través de su teléfono. Verifique en la configuración de seguridad.

**Comment by razerrazer** [comment]
Look at this link : https://www.applivery.com/docs/troubleshooting/android-unknown-sources/

**Comment by gracar621** [comment]
Muchas gracias 
Todavía no he sido capaz de instalarlo.....😔😔😔😔😔😔😔😔
Seguiré intentándolo 
Muchas gracias!!!!

**Comment by razerrazer** [comment]
¿Recibes algún mensaje de error?

**Comment by gracar621** [comment]
[Image]



Enviado de Samsung Mobile
Obtener Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by gracar621** [comment]
Lo puedes ver???
Yo creo qe el teléfono ya desactive lo que me dijistes

Enviado de Samsung Mobile
Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by razerrazer** [comment]
no puede ver su imagen, debe publicarla a través de un enlace.
