### ISSUE TITLE
No longer receiving BG Readings

### ISSUE THREAD

**Issue by JustSomeone555** [NightscoutFoundation/xDrip#1211]
Hi guys, 
I am using the xdrip with the libre sensor and using galaxy s10+ running android 10.
I have switched my sensor last night and it works fine - problem is that i get no readings with the MM to the xdrip app.
It worked fine up until that point with exception that when i first updated to android 10 it stopped working but was fixed thanks to some advice from people here.
I have made sure the MM is fully charged and tried the same workaround that fixed it for me after upgrading to android 10 (f.closed app remove bluetooth data &reconnect) to no avail.
Anyone else had this or can help with this? Should also note MM is connected to xdrip.
Here is a screen from the  logs
![Screenshot_20200128-080706_xDrip+](https://user-images.githubusercontent.com/59981979/73239715-9e54fa80-41a5-11ea-8196-0a6e12ce7eb4.jpg)
![Screenshot_20200128-080842_xDrip+](https://user-images.githubusercontent.com/59981979/73239721-a3b24500-41a5-11ea-8c7d-1e35e22cfaa0.jpg)
![Screenshot_20200128-080850_xDrip+](https://user-images.githubusercontent.com/59981979/73239726-a6ad3580-41a5-11ea-9608-bfc159effd95.jpg)

**Comment by LaNiSa2016** [comment]
Can you read the sensor manually with the libreapp?

What does MM mean?

Tried Force App, Clear Cache and Restart?

Witch Version of xDrip is installed?
