### ISSUE TITLE
bluetooth issues

### ISSUE THREAD

**Issue by jomonba1** [NightscoutFoundation/xDrip#1212]
Hi there, I am using the latest version (2020.01.26) with Miao Miao 2.

It has been running on and off during the last days, let me say that I started with the CGM since last Friday, but I was not able to keep the app running for more than... let me say more than 5 hours.
I tried with all the bluethooth settings (Less common settings -> Bluetooth settings -> Disable Trust Android Auto Connect... and many other setting that I have been reading in some other posts) but nothing is working.

Right now on System status I see this on **"Classic Status Page"**:
Bluetooth Device: None Set
Connection status: Not connected
On **"BT Device"**:
Bluetooth Device: Disconnecting
Bluethooth Pairing: Not bonded

I could fix the issue with the connection few times by clicking on the "**Not bonded**" message, the it changes to "**Disabled, tap to enable**", then I was clicking again on it and there was a message down on the screen saying "_This probably only works on HM10/HM11 and blucon devices at the moment and takes a minute_"

Sometimes it works, but now I lost the connection since 3-4 hours ago and it doesn't work anymore.

I am waiting for the next release to see if I can fix it by installing the new version but I think there are many people with this issues... 

On the other hand, let me say that the readings were not very trustable during these 2-3 days. I found differences about 50-60 mg/dL in many occasions. I was always calibrating hoping that the next reading would be more accurate but no, a couple of hours later again there were big difference between the reading and the BG, is that normal?

Sorry for this long message but I have been even thinking about giving back the device.

any help will be appreciated. Thank you!

**Comment by zip9** [comment]
Same as above. Using new MM2 updated to tomato firmware 7, used 3 nightly builds (on 2020.01.29). Phone is LG G6. Also having some issues getting a new sensor working. I have uploaded logs...and notice 'Error receiving too much data', and 'MissedReadingService' often when having issues. Please note, I can have several hours where everything works just fine, and can just do a bluetooth search on my phone to restart xdrip service at times. Starting a new sensor is a pain.....

**Comment by jamorham** [comment]
People with this problem can you specify which android version your phone is running?

**Comment by jomonba1** [comment]
My phone is an OnePlus 5
Android version 9

**Comment by zip9** [comment]
I have LG G6 running Android 9. Believe I have fixed my similar issue. Found a post on Facebook 'https://www.facebook.com/photo.php?fbid=10156380511723202&set=pcb.396158931107298&type=3&ifg=1&__tn__=HH-R&eid=ARArGupMk3C0qvWkK9PYtEI5d3fkmUB4j1c8SbyeYfiMV9166VSrv70e8HZSq6ZaxwrIQrgimzsoy7iG' and this fixed connection issues as well as increased MM2 battery life. jomonba1 please give this a try and see if it makes a difference for you.....

**Comment by tolot27** [comment]
@jomonba1 Could you solve the problem with the suggestion of @zip9? If yes, please close this issue.

@zip9 The link you provided in the previous comment is broken. Please can you describe you solution, briefly?

**Comment by Miri88** [comment]
Hello, I jave this issue top,anybody solved this problem? Link in Facebook dont work. Thanks

**Comment by Navid200** [comment]
@jomonba1 There are a lot of guides in the support channels.  There are people who can help.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Would you please use them?

Would you please close this issue if you don't have the problem any longer?

Otherwise, would you please update?

**Comment by jloor** [comment]
> I have LG G6 running Android 9. Believe I have fixed my similar issue. Found a post on Facebook 'https://www.facebook.com/photo.php?fbid=10156380511723202&set=pcb.396158931107298&type=3&ifg=1&__tn__=HH-R&eid=ARArGupMk3C0qvWkK9PYtEI5d3fkmUB4j1c8SbyeYfiMV9166VSrv70e8HZSq6ZaxwrIQrgimzsoy7iG' and this fixed connection issues as well as increased MM2 battery life. jomonba1 please give this a try and see if it makes a difference for you.....

Do you have the steps anywhere else? @zip9
