### ISSUE TITLE
New 8J dexcom transmitter problems with connection

### ISSUE THREAD

**Issue by Rebekahzw** [NightscoutFoundation/xDrip#1213]
Having issues with signal loss on xdrip with 8J serial code transmitters. Fb groups suggested it may be new firmware and I haven't seen anything on 8Js in the docs. I've set up fine using the instructions for 8G and 8H , but losing signal frequently..
Sometimes it helps if I go to my phone and unpair the dexcom in settings - but I'm unable to do this permanently (honor 10) plus sometimes if it does seem to work while paired and if it isn't paired means my phone can't find it all. 
You can see my settings in the pic...ive trialled unchecking allow ob1 unbonding (doesn't seem to have made much difference - maybe signal loss is a little less frequent). Have also shown system status page when working and not working.
Any suggestions for setting changes or other work around? Are there new xdrip options needed for 8J transmitters (currently using latest nightly build) 

At present it drops every 30 mins ish. I reconnect by using restart collector or sometimes unpairing or turning off and on Bluetooth but it doesn't stick. 
![Screenshot_20200129_113622_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/60288818/73374116-95e9e600-42b1-11ea-8e13-fe60adc7439f.jpg)
![Screenshot_20200129_095723_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/60288818/73374133-9b473080-42b1-11ea-83b9-73c52db1b319.jpg)
![Screenshot_20200129_095652_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/60288818/73374159-a39f6b80-42b1-11ea-9d89-7a4540214b8e.jpg)
![Screenshot_20200129_095640_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/60288818/73374168-a8641f80-42b1-11ea-9def-414db69b3693.jpg)

**Comment by jamorham** [comment]
Which version of xDrip are you using and which Android version is your phone?

**Comment by Rebekahzw** [comment]
Xdrip is latest nightly build. Phone is an honor 10 android 8.1

**Comment by jamorham** [comment]
Can you try the 29th Jan version to see if it makes any difference.

**Comment by Rebekahzw** [comment]
No difference..... Now seen this on system status. Don't know if its connected. Any idea? 
![Uploading Screenshot_20200130_183602_com.eveningoutpost.dexdrip.jpg…]()
