### ISSUE TITLE
Help need to install nightly build on jelly phone 

### ISSUE THREAD

**Issue by solims1** [NightscoutFoundation/xDrip#1214]
New to this forum . Anyone can guide me on how to install the latest nightly build on jelly phone , please .

Appreciate all the help

Thanks 
Sh

**Comment by steve8x8** [comment]
Go to jamorham.github.io, next to the QR code click on "Nightly", find the newest release, open assets, download apk file, open it (file manager, download list). When Android asks you to confirm that this came from a trusted source, confirm, install.
If there are problems with this workflow, provide details where they happened.

**Comment by solims1** [comment]
Much appreciated Steve , it worked for me .

**Comment by Navid200** [comment]
Seems your question was answered.
