### ISSUE TITLE
Add A Test Connection Option For Uploading Data

### ISSUE THREAD

**Issue by opticyclic** [NightscoutFoundation/xDrip#1215]
**Background:**
I am using a Dexcom G6 and wanted to upload the data so that it could be followed.

Settings - Cloud Upload - Dexcom Share Server Upload

Upload BG values as Dexcom Share = ticked
Dexcom USA based account = unticked
Dexcom Account Login = added username
Dexcom Account Password = added password
10 Character Dexcom Receiver Serial Number = SM00000000 (Default)

I don't have a Receiver. 
Does it matter if I leave this value?
Maybe add some pop up help on each section to explain.

How do I know that I have set everything up correctly?
I waited for a while and didn't see any activity.
I checked my password and it seemed to be wrong.
I changed it to a seemingly correct password.
I waited for a while and didn't see any activity.

Have I set something else up wrong?

I got distracted then came back and checked and there was data being sent and followed.

**Feature Request**
To make this more user friendly you should add a button that says "Test Connection".
I should then get feedback to say whether my password is wrong or whether everything is correct and the app was able to connect.
If it is able to connect it should also give info on roughly how long to wait before seeing data.
e.g.

    Connection successful!
    Please wait 5 minutes for the next data point to be uploaded before checking the follow app.

**Comment by steve8x8** [comment]
I'd expect this to be found in System Status - but I'm using neither a Dexcom nor Dexcom Share...

**Comment by Navid200** [comment]
@opticyclic Would you please ask your questions from the user community?
https://www.facebook.com/groups/cgminthecloud
https://gitter.im/jamorham/xDrip-plus
After you do that, please only open an issue here if you are certain that you have identified a bug or if you have a feature request that has no work-around.
Thanks

**Comment by Navid200** [comment]
xDrip is not user friendly unfortunately.
We can work on that.  
But if we were to prioritize, I would think that making xDrip as a collector user friendly is more important than making it user friendly as a master, which only matters if there is a follower.

I am going to postpone this as a feature request, which we will get to after we address some other issues.
