### ISSUE TITLE
Feature Request: Default plot maximum

### ISSUE THREAD

**Issue by dkumor** [NightscoutFoundation/xDrip#1216]
Currently, I have not been able to find a way to set the default range for the main glucose plot - the default plot goes to 250mg/dl. If possible, I'd love to be able to set a custom maximum value.

**Comment by LanFeusT23** [comment]
To add to that I would love to also set a custom minimum value. I'd rather have a 50 to 230mg/dl range than a 0 to 250!

**Comment by Navid200** [comment]
Those (min and max) are automatically adjusted based on the values present during the current 24-hour period.

**Comment by dkumor** [comment]
Yes, the max can increase based on the data, however, I have not noticed the max adjusting *down* below 250, even with no data.
