### ISSUE TITLE
Change Warm-up Time

### ISSUE THREAD

**Issue by Dugaldrowland** [NightscoutFoundation/xDrip#1217]
Using the G6+ transmitter/sensors (Transmitter SN 22xxxx) & xDrip (nightly 16/01/2020)
The G6+ only requires a 1 hour warmup as per documentation and xDrip starts receiving data before the standard 2 hour warmup time.
Is there a way to reduce this warm-up time to match the Transmitter/sensor?
Linked to this,we have had wildly out readings and a sensor failure at 10d. Inserted a new sensor and still way out after 5+ hours (more than 2mmol/L).
Please advise there are any setting that can be changed in addition to the warm-up time.
p.s. the temperature is always around -80deg C.

**Comment by Navid200** [comment]
@Dugaldrowland Would you please close this issue if it has been addressed already.
Otherwise, please show a snapshot of the G6 transmitter with the first two serial number characters being 22.

**Comment by Dugaldrowland** [comment]
Hi @Navid200 
I did not get a solution for this, however we are not using the G6+ anymore and the warm up is no longer an issue. I was also advised that the reported temperature is not associated with any readings.

**Comment by tolot27** [comment]
@Dugaldrowland
> The G6+ only requires a 1 hour warmup as per documentation and xDrip starts receiving data before the standard 2 hour warmup time.

Where did you read this? I've never seen a one hour warmup of G6 sensors. Our receiver also shows two hour warmup.

**Comment by Dugaldrowland** [comment]
@tolot27 
We had the G6+ here in South Africa for a while, but they discontinued it mid last year. The G6+ used the normal G6 sensors but ran for 14 days as well as had a 1 hour warm-up. We were very happy with it while we had it as is worked out quite a bit cheaper for us. My only issue was that the connection with xDrip was not very consistant.

**Comment by tolot27** [comment]
@Dugaldrowland I've send you a PM at Gitter.
