### ISSUE TITLE
xdrip web service is incorrectly sensitive to header capitalization

### ISSUE THREAD

**Issue by ecc1** [NightscoutFoundation/xDrip#1218]
Providing the API secret header as "API-Secret" or any capitalization other than "api-secret" results in a 403. It should be case-insensitive.

**Comment by jamorham** [comment]
I will correct this

**Comment by jamorham** [comment]
This should be fixed in the Feb 7th Nightly, please check thanks

**Comment by ecc1** [comment]
Confirmed, thanks for the quick fix.
