### ISSUE TITLE
Tasker features

### ISSUE THREAD

**Issue by jamorham** [NightscoutFoundation/xDrip#122]
Soon some work will be done to add a few additional Tasker features. 

This issue is an opportunity to suggest useful events/commands which could be included. 

Feel free to suggest anything, but please also explain briefly a usage scenario where the event/command would be used and how you would find it useful.

Easier and more generically useful to everyone events/commands are the most likely to be implemented first.

**Comment by bryanw20** [comment]
Is this the 'syringe' adding feature?

I'd like a 'default' option, or return to lased used (no it doesn't do this now; I frequently enter insulin by mistake; and I'm not on insulin yet, so I'd never select this option manually)

If it'd ask to make these changes or at least tell you how to make finger pricks calibrations when using this method. Right now it just logs them; but I don't think it gives instruction on how to change to use as calibration every time, or ask each time.


Personal wants right now are one touch flex BT sync/integration
Nightscout backfill (previous request is open)
Display options of High & Low in red, say <70 >250; but also a 'normal' range can be set say from 70-120 in green, and above normal >120 < 250 in yellow/orange

**Comment by jamorham** [comment]
@bryanw20 No, this is about Tasker features. Tasker is an app for scripting based on events. See: https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm

**Comment by juliatuttle** [comment]
I'd love to see a Tasker feature that tells me when xDrip+ is scanning for the G5, or when xDrip+ needs the network to upload things. In short, I'd like to be able to program Tasker to leave my phone in airplane mode except when it needs Bluetooth (for the G5) or Wi-Fi/mobile data (for Nightscout).

**Comment by jamorham** [comment]
@juliatuttle Can you explain what the use case is for this feature? thanks

**Comment by juliatuttle** [comment]
@jamorham It would let me significantly extend the battery life on a phone that's *only* doing xDrip+ by powering off unneeded radios between readings.

**Comment by old-square-eyes** [comment]
Being able to run a profile in Tasker based on the following events in xDrip
:: A definable, specific alarm was triggered in xDrip (maybe have slots to assign or dynamic named contexts). Could be used for lots. But I'd get Tasker to send out GPS coordinates on urgent low.
:: Force wake phone on missed reading threshold alert, and other debugging phone tasks (like reboot or airplane mode)
:: Control lights like Philips hue based on current BG

:: 
::

**Comment by jamorham** [comment]
@old-square-eyes So how about an event when alarms are raised with parameters of details of the alarm? I like the philips hue idea. I do something similar to this with a multi-colored led on a raspberry pi already and I think its very useful to have an ambient display.

**Comment by old-square-eyes** [comment]
Ah yes parameters would be great. Just wasn't sure what the Tasker special allowed to be exposed.

**Comment by old-square-eyes** [comment]
spec

**Comment by old-square-eyes** [comment]
Another one is toggling features in xDrip based on location (or any other profile). e.g. stop looking for my WiFi Wixels when on my work WiFi or disable WiFi Wixels altogether.

**Comment by doc77** [comment]
If you could expose the spoken treatment and keypad treatment routines (on the watch) as activities  so that floating icons could be placed on the watch face via the auto wear plug in.

That would allow a single tap right on the xDrip+ watch face to enter treatment instead of swiping and scrolling through a menu on the watch.

Thanks!

**Comment by kskandispersonal** [comment]
@doc77 Good idea.  We are working on treatments now.

**Comment by jamorham** [comment]
I've only done a small amount on this so far but there are new tasker actions in the may 30th nightly for restarting the collector and restarting the entire app.

**Comment by doc77** [comment]
@jamorham. Thank you for making it so drop dead easy 😊. Great implementation and UI!

**Comment by bryanw20** [comment]
I'm still not 100% sure what it can do; but is it possible via the tasker, to 'talk' to other programs? specificly a food tracker like mynetdiary? Then BG#'s & carbs could be transfered back and forth? 
As a T2 I'm more focused on what I eat, & what my #'s do for the next 2ish hours. Do I go over say 150, how long do I stay high, etc.

**Comment by kskandispersonal** [comment]
How about a command to import pump data, such as from the OmniPod, and upload to Nightscout??  Assuming xDrip+ has access to the pump data file (such as a csv)?

**Comment by themotoden** [comment]
Please, add:
- BG, Carbs and Insulin import to Tasker (as variable) and  back. Now I read BG Level via notification (AutoNotification plugin). So I can use it for my own algorithm of alarms, prediction etc.
- BG Level Alerts changeable via Tasker. I always change it to catch hypo/hyper of my son on my phone after meal/injection. I will change it remotely on his phone (via AutoRemote plugin) if you add this option!
Please, I need it very much!

**Comment by themotoden** [comment]
"VOLUME vibration only" is not working via Tasker

**Comment by juliatuttle** [comment]
Would love to be able to toggle "speak readings", so it can turn that on when I'm connected to the speaker on my bike.

**Comment by doc77** [comment]
I second the request to be able to toggle spoken readings via tasker!

**Comment by losteloquence** [comment]
Has anyone had any luck with the idea of Hue integration? For me this is a game changer. I work in my home office (with Hue lights) and my job often has me with tunnel vision, and I often forget to check my readings/trends, but having the lights change on me would force my hand and do a lot to tighten my control further. I think I read that IFFT no longer worked, but I'll dig more into that too.   I'm just getting started with xdrip and Nightscout, so much to learn still, and THANK YOU!

**Comment by old-square-eyes** [comment]
Yeah it was suggested above a while ago. I believe @jamorham was looking at egress Tasker contexts (which in turn could control Hue) but looks to have moved on to more pressing features so it might be on the backburner.

**Comment by jamorham** [comment]
Referencing https://github.com/NightscoutFoundation/xDrip/issues/148 to support enabling spoken readings or to emit the current reading and trend

**Comment by jamorham** [comment]
@juliatuttle @doc77 The Jan 1st Nightly has support for toggling speaking readings and alerts

**Comment by doc77** [comment]
@jamorham Thank you so much, not only for expanding Tasker support, but more for your tireless efforts to make xDrip+ a complete diabetes tracking solution.

**Comment by ferdytao** [comment]
I would love to add insuline prescription with Google assistant or Google home without touch my phone.

Thanks

**Comment by xannasavin** [comment]
Hi! I'm using xDrip since short time and tried to get the following running in tasker (without success so far):

Tasker should know the following information:

- Blood glucose level
- Alert levels (High, Low, falling, rising)

So it can send them through the MiBandTools App to my MiBand 2.
I did not find any hint if Tasker is getting the needed information in any case - please correct me if this is already the case :)

Best

**Comment by old-square-eyes** [comment]
@xannasavin You can poll the internal API with Tasker javascript for some of that info https://github.com/jamorham/xDrip-plus/blob/master/Documentation/technical/Local_Web_Services.md

**Comment by xannasavin** [comment]
thanks a lot @old-square-eyes for that insight - have to wrap my hand around it since I'm not super familiar with such kind of programming :D 
the "/3/18" part is for the conversion? If I need the mg/dl do I just need to remove this?

**Comment by old-square-eyes** [comment]
@xannasavin sorry that's just my script. It takes the last 3 BG values and averages then (divide by 3 you quoted). The divide by 18 is to convert to mmol/L as the internal web server is in mg/dl.

**Comment by Liknus** [comment]
@themotoden I'd like to get these two features too! This would make it much easier to show notifications on non-Wear OS/pebble devices!

**Comment by Liknus** [comment]
@old-square-eyes Hi! I've used part of yor code to show the current value of my glucose in the Mi Band 3.. 
```
var req = JSON.parse(global('HTTPD')); // Parse json
var sgva = req[0].sgv; // Set variable
asgv = (+sgva).toFixed(1); //
tk.setLocal("%asgv",asgv); // Return as variable to be used down stream
```
But I'd like to be able to see the direction of my glycaemia too (don't want the average of my last 3 values) through, if possible, an icon such as the arrow xDrip uses..
- upward if glucose level is rapidly rising
- upward sloped if it's rising
- flat if it is more or less stable
Is it possible to query xDrip+ to fetch that arrow and use it in the notification?

Thanks

**Comment by old-square-eyes** [comment]
Heya. Does req[0].direction help?

**Comment by Liknus** [comment]
@old-square-eyes Thanks for the prompt reply.. I'm not a developer.. So.. Where should I put req[0].direction in the code above? ;)

**Comment by wagnefrede** [comment]
Is there still any any help needed.I have build a Tasker Project which can be used with a  simple plugin. Called AutoRemote.
Its a plugin to easily read JSON automatically without any manual written javascriplet.

I have build a Graph Watchface with Watchmaker. But you can forwar the setted variables to any other supported device. 

I'm using that for my Samsung Galaxy Watch with Tizen OS. 

But I have a major questions. I've found the API endpoints for pushing values like heart rate and steps to xDrip. Can you tell me how do I do that? 

Do I need a Javascriplet or my JSON plugin to push steps/hr to xDrip? 

Because I only need to load this URL 
http://127.0.0.1:17580/sgv.json?steps=1234
in my Browser to add the steps. Looks like I don't need anything other than a Task which updates the URL with my current steps. 
 

Is there someone who can give me some tips or suggestions :) 
I really wann use this to push my steps and hr to xDrip.  

I don't wanna buy a WEAR OS device....not again....my Ticwatch isn't working properly...the screen freezes....really much less RAM.....and the Snapdragon wear 2200 isnt really prowefull....

**Comment by Navid200** [comment]
I hope it's OK to close this issue as it is not an issue that requires the developer's attention right now.
We can always reopen it.
