### ISSUE TITLE
Bluetooth protocol library

### ISSUE THREAD

**Issue by davystrong** [NightscoutFoundation/xDrip#1220]
I would like to extract the Bluetooth protocol for communicating with the Dexcom G6 into a separate library (I'm looking at pycom's Gpy using python, but really this might be useful for other things). I think it's mostly implemented in /app/src/main/java/com/eveningoutpost/dexdrip/Services/G5CollectionService.java, however this file is pretty complex given all the Android code for bluetooth. Can anyone point me to a protocol definition for talking to the G6 (I know there's nothing official) or was it simply coded directly in Java?

**Comment by andremauricio4** [comment]
Did you find anything on this subject? am also interested
Best regards,
Andre Mauricio / andremauricio (gmail.com)

**Comment by davystrong** [comment]
Sorry, no. I really haven't looked at it much since. If I do anything on it I'll let you know

**Comment by andremauricio4** [comment]
thanks!!

**Comment by Navid200** [comment]
@davystrong I don't think this is an xDrip issue.
You are welcome to use the xDrip Gitter room in order to communicate with users or developers.
https://gitter.im/jamorham/xDrip-plus

Would you please close this issue?
Thanks
