### ISSUE TITLE
Xdrip Prefs unfortunately stopped

### ISSUE THREAD

**Issue by FreThor** [NightscoutFoundation/xDrip#1221]
I'm using Samsung S9 with Xdrip+ in follower mode, build from 2019-10-27, and a Sony SW3.
I've been plagued with error message "Xdrip Prefs has unfortunately stopped" on the watch, more than 10 times a day, up to the point where it was becoming ridiculous.
Fortunately I managed to find a (sort of) solution which in any case should help locate the error. I (for some unknown reason) switched from Swedish to English settings and the problem was gone!
I've now been on English for about a week and haven't had a single error message.

**Comment by old-square-eyes** [comment]
@FreThor try "force google reboot" from the treatments voice menu. Good to know of this other workaround though.

**Comment by tolot27** [comment]
@FreThor Please can you try to reproduce this problem with the latest nightly and report the result here?

**Comment by Navid200** [comment]
@FreThor Would you please use the support channels, to consult with the user community, before opening an issue?
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

I am closing the issue.  If you like to reopen it, would you please respond to tolo27?

Thanks
