### ISSUE TITLE
Blucon Nightrider sync with 2 xdrip devices???

### ISSUE THREAD

**Issue by JoseBQ** [NightscoutFoundation/xDrip#1226]
Hi!
My wife has just changed her phone and installed xdrip on it.
She is unable  to sync her blucon nightrider with her new phone, but she can with her old phone.
The question is, can blucon nightrider sync with two different smartphones? (Each one with xdrip+).
Thanks.

**Comment by JoseBQ** [comment]
Should she unpair her old smartphone in order to get the information in the new one?

**Comment by parapenT1sta** [comment]
> Should she unpair her old smartphone in order to get the information in the new one?

Yes, You need to "Forget Device" under System Status menu.

**Comment by JoseBQ** [comment]
Thanks,  solved.
