### ISSUE TITLE
xDrip+ update mechanism does not work

### ISSUE THREAD

**Issue by emp-00** [NightscoutFoundation/xDrip#1228]
I'm currently using the nightly 2019-12-31 (alpha channel + auto update check enabled) 

Issue:
A) I haven't received any update notification ever since. In older versions this happened at least "sometimes"; I think around 3 times in a whole year.
B) Manually selecting "Check for updated version" only shows "Checking for update..." message for 3 seconds and then disappears. No effect. No update incoming.

Any ideas what's wrong? Samsung A8 phone, no other issues - xDrip+ running fine with Dex G6.

**Comment by jamorham** [comment]
Make sure you have the nightly channel selected: https://github.com/NightscoutFoundation/xDrip/wiki/How-to-get-the-Nightlies-on-Automatic-Update

**Comment by LaNiSa2016** [comment]
Got the Same Issue.

Set Nightly and Automatic. Manually display Check for updates and nothing happens.

Samsung S10e Android 10
Version 2020-01-29

**Comment by LaNiSa2016** [comment]
Today Update Works

**Comment by Navid200** [comment]
@emp-00 Is this still an issue?

**Comment by emp-00** [comment]
closed
