### ISSUE TITLE
Issue with flashing the wixel

### ISSUE THREAD

**Issue by wefink** [NightscoutFoundation/xDrip#123]
when i connect the wixel to write the usb-serial.wxl..it works...and flashes with the file..next when I open the terminal NinjaTerm or Putty  to write "AT"  or "AT+SBLUP" ,  i get no response or echo ...what is wrong???
thanks for help ( used the right port, right speed 9600 right stop bits and so on)
'but something is wrong...????
wefi

**Comment by AdrianLxM** [comment]
In case you use xBridge2, you need the usb serial wxl from @jstevensog 's repository, as the layout a what ports it is connected is different.
