### ISSUE TITLE
Feature request: "HI" display threshold

### ISSUE THREAD

**Issue by nhatier** [NightscoutFoundation/xDrip#1232]
Sensors have a range where they are quite accurate. Outside of that range, not so much. In my experience with the Freestyle Libre for instance, anything above 12-13 mmol/L (220-240 mg/dl) is likely higher in reality than it shows in xDrip. Using calibration to adjust those values will likely mess up either mid-range or low-range values.

I would like to be able to configure the threshold in xDrip above which it displays "HI" instead of the unreliable number, forcing me to do a real test (which I should do anyway) instead of using the displayed number.

For me, displaying HI above 12 / 220 would make sense. I suppose xDrip already shows HI for values above 28 / 500 but this is not something I want to test...

**Comment by Navid200** [comment]
@nhatier I'm sorry that we cannot implement every feature request.
If I understand you correctly, you can just ignore the values that are too high as a work-around.  Please correct me if you believe that statement is incorrect.
