### ISSUE TITLE
Authentication required for InPen 

### ISSUE THREAD

**Issue by lindylou417** [NightscoutFoundation/xDrip#1233]
I have been using xdrip+ on my Moto G6 play phone running Android 9 for some time. Thank you for the amazing program! I am trying to connect a new InPen to xdrip+. I uninstalled the InPen app. It seems like the pen is paired, because when I prime under system status it recognized that I tried boluses ,but says incorrect number of units dialed up for pairing or other error 14:25. And then say authentication: required. I have heard a sound play to indicate data transfer with pen. It isn't logging any boluses though. I have restarted my phone several times, and tried following the suggestions for pairing the InPen here on Github. Any suggestions?

**Comment by warsix4** [comment]
Hi @lindylou417 ! I have the same problem, I made an issue [here](https://github.com/NightscoutFoundation/xDrip/issues/1176) earlier this month.

**Comment by tolot27** [comment]
Duplicate of #1176.
