### ISSUE TITLE
I made a website for sharing working configs

### ISSUE THREAD

**Issue by Feromrk** [NightscoutFoundation/xDrip#1236]
Hello there,

I am always afraid of installing android updates since they broke the xdrip+ app functionality a few times in the past. I made a website where we can share working/broken configurations. Let me know what you think about it! It is available under the following URLs:

https://xdrip-supported.web.app/
[https://xdrip-supported.firebaseapp.com/](https://xdrip-supported.firebaseapp.com/)

Note: this project is work in progress, when you have suggestions on how I could improve something, please let me know

Edit added TODOs:
- add smart watch section
- implement a better table, so it is more usable on smartphones
- allow sharing the huge amount of all the xdrip settings (e.g. bluetooth) somehow
- allow sharing xdrip settings through the app somehow. maybe by uploading the xml settings file
- add sharethis buttons
- create pull request for adding this to docs somewhere
- create git repo and publish source code

**Comment by Feromrk** [comment]
Also, I will make it open-source and accept feature requests if people like using it. xDrip is a daily helper for me for me for many years, I would love to help out this way.

**Comment by tzachi-dar** [comment]
I think this is great initiative.
Many times people ask what phone is supported.
I think that having a place to show what BT settings were used will be very helpful.

And, if all goes well, adding an option to smart watches will be great.

Thank you for your contribution.

**Comment by zip9** [comment]
Hello....What do you want in these columns...Data Source (what is G6...a phone model? Something in XDrip+?....Security Patch(I assume the phones Android Security Patch Level)...Author(Where do I find that?) I filled in my settings - hope it helps others with US 14 day Libre and MM2.

**Comment by Feromrk** [comment]
> I think this is great initiative.
> Many times people ask what phone is supported.
> I think that having a place to show what BT settings were used will be very helpful.
> 
> And, if all goes well, adding an option to smart watches will be great.
> 
> Thank you for your contribution.

Awesome, thanks for your feedback!

**Comment by Feromrk** [comment]
> Hello....How do I upload my settings? .... and what goes in these columns...Data Source (G6?...a phone model? Something in XDrip+?....Security Patch(I assume the phones Android Security Patch Level)...Author(Where do I find that?) I filled in my settings - hope it helps others with US 14 day Libre and MM2. Let me know how the settings are shared. Good idea!

The author should come automatically from the login source (github, google, facebook etc.). I will make it editable, since apparently not all people have names registered with their accounts. Also I will add a better description of the columns. Awesome, thank you!

**Comment by doc77** [comment]
@Feromrk Thank you for building this. Great idea. I added my info and bookmarked it!
A watch section would be fantastic.

**Comment by LaNiSa2016** [comment]
> @Feromrk Thank you for building this. Great idea. I added my info and bookmarked it!
> A watch section would be fantastic.

100% Agree

**Comment by zip9** [comment]
Thanks for the reply Feromrk. In the same thought as the request for BT settings, any possibility of sharing XDrip settings...using the xml file that is available to generate in the app? May be a bit wishful, but users with the same hardware/software on their phone may assist others having issues with the many XDrip settings.

**Comment by Feromrk** [comment]
> Thanks for the reply Feromrk. In the same thought as the request for BT settings, any possibility of sharing XDrip settings...using the xml file that is available to generate in the app, but without any personal information? May be a bit wishful, but users with the same hardware/software on their phone may assist others having issues with the many XDrip settings.

@zip9 I like that idea. Will definitely come on my TODO list. Would be cool, if you could directly share the settings from the xdrip app without needing to upload it somewhere, since that is not very user friendly on smartphones. 
Just let your ideas out, doesn't matter how complicated they are =)

**Comment by Feromrk** [comment]
> @Feromrk Thank you for building this. Great idea. I added my info and bookmarked it!
> A watch section would be fantastic.

@doc77 thanks for your input =)

**Comment by Feromrk** [comment]
> > @Feromrk Thank you for building this. Great idea. I added my info and bookmarked it!
> > A watch section would be fantastic.
> 
> 100% Agree

@LaNiSa2016 got it! =)

**Comment by Feromrk** [comment]
Update: the hoster (firebase) has troubles with certificates, thats why only 1 of the 2 URLs is working currectly. I updated my first post.

**Comment by Feromrk** [comment]
> Update: the hoster (firebase) has troubles with certificates, thats why only 1 of the 2 URLs is working currectly right know. I updated my first post.

Issues resolved

**Comment by Feromrk** [comment]
Update: edited original post.
Note: I am currently working on my master thesis in computer science and have limited time available.

**Comment by Navid200** [comment]
@Feromrk Thanks for your contribution.
We would like to improve documentation.  I hope we can benefit from your expertise.
We are organizing the open issues.

You have done excellent work.  But, this is not an issue.  I ask you to please close this issue.
You can use the support channels to communicate with the user community.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

I hope we can ask you to contribute when we work out our documentation plans.

Thanks
