### ISSUE TITLE
G6 8G transmitter always shows Initial Calibration

### ISSUE THREAD

**Issue by jamespaulley** [NightscoutFoundation/xDrip#1239]
Restarting a G6 sensor with an 8G transmitter using the sensor's code causes the fly-out menu to always display "Initial Calibration". Calibrations do seem to take, however, but I'm not totally sure it's working correctly.

https://photos.app.goo.gl/aMdnUtsfd8rdGaht9

**Comment by jamespaulley** [comment]
Has this been addressed?

**Comment by Navid200** [comment]
You are correct that it always show the initial calibration option even after you have done calibrations already.
Yes, the calibrations are sent to the transmitter.

**Comment by Navid200** [comment]
You can ignore the messages.  Not, they still show up and have not been addressed yet.

**Comment by Navid200** [comment]
I am closing this issue.  
There is already work in progress to update xDrip to provide correct messages.
You can use xDrip as is knowing what messages you can ignore.  This is not elegant and hopefully will be addressed soon.
