### ISSUE TITLE
Ongoing notification wakes up display every 5 minutes.

### ISSUE THREAD

**Issue by jamespaulley** [NightscoutFoundation/xDrip#1240]
I'm using a Google Pixel XL with Android 10 and it's quite hard to get the ongoing notification to not wake up the display every 5 minutes. I have to have xDrip's notification set to "silent" via Android's notification setting, or the display will wake. If the notification is set to "alerting" the display wakes. If I enable "use notification channels" in xDrip, it doesn't seem to help.

Having the notification set to "silent" is fine, but the problem is that Android sticks it to the bottom of the notification cards under a "silent notifications" section. Ideally I would like to be able to stick the xDrip notification to the top, so I can quickly see it, and the small number in the notification bar is always visible.

**Comment by JimZam** [comment]
Good evening. I've the same problem in may Xiaomi Redmi Note 9 Pro. Only way to avoid it is prevent the phone from waking up when a notification (any notification) is received. I'm using Libre 2 patched app, not sure if xdrip as follower does the same thing (I tested this way before changing my phone and everything worked fine but I'm not sure if the screen waked up every 5 minutes...)
Any way to avoid it?
Thank you for your help and regards

**Comment by Navid200** [comment]
@jamespaulley Would you please explain what you mean?
Do you have the phone screen locked when this happens?
What notification exactly do you mean?
Would you please show a snapshot of it here?
Thanks

**Comment by jamespaulley** [comment]
Basically, if the ongoing notification is set to anything other than "silent" in the Android system settings, every 5 minutes the ambient display on the phone will illuminate, showing the time and notification icons. It seems to also do this if I enable "use notification channels". Do you have a phone there you could try to recreate the behaviour on?

**Comment by JimZam** [comment]
You can disable it: Look for Registry Notifications and see the channelID xdrip is using to display the glucose every 5 minutes. Now open Settings in your phone, look for xDrip app then Notifications. There look for the channelID and turn off Floating Notifications and Not show notifications in lock screen. If channelID is null, then change this in Ongoing Notifications.
I hope it works

**Comment by Navid200** [comment]
@jamespaulley This is already mentioned in the description, isn't it?

![Screenshot_20210327-001416](https://user-images.githubusercontent.com/51497406/112709701-fd89ca00-8e91-11eb-9708-401edf48318c.png)

**Comment by StephenBrown2** [comment]
I have that setting off, but my screen still wakes up on a new BG reading...

**Comment by Navid200** [comment]
I would like to know how I can recreate this problem.  
My phone, Android 9, never automatically comes on every 5 minutes.

**Comment by StephenBrown2** [comment]
Maybe it's actually an Android setting. I have "wake screen for notifications" turned on.

![Screenshot_20210622-170219.png](https://user-images.githubusercontent.com/1148665/123010398-c4bb9d00-d37b-11eb-88ab-b2e9fc622a5d.png)

**Comment by Navid200** [comment]
@jamespaulley What are your settings for notifications on lock screen?
https://support.google.com/pixelphone/answer/6111294?hl=en

**Comment by StephenBrown2** [comment]
Been running with the switch off and on for the last day, haven't watched my screen but I'm not sure it's made a difference.
@jamespaulley have you tried flipping that switch and seeing what happens?

**Comment by Navid200** [comment]
This sounds like the result of phone settings rather than an xDrip issue.
Please reopen if you believe this is an xDrip issue and include steps for recreating the problem.
