### ISSUE TITLE
commit xxx kills big letter battery warnings also for bluereader

### ISSUE THREAD

**Issue by MasterPlexus** [NightscoutFoundation/xDrip#1241]
@jamorham this commit ( https://github.com/NightscoutFoundation/xDrip/commit/79e3de03b2080a0db3a8f44373ae4536318c1ea8 )  deletes the big letters battery warning also for bluereader. Is there a other handling planned? 

I think it is not that big issue, as bluereader is only for Libre1 possible, and will be more and more decomissioned (also I could not test this, as I have no more L1 sensors). But for users wich still uses bluereader, it will delete the warning without any information bevor... just to notice

**Comment by tolot27** [comment]
@MasterPlexus Do you still use Bluereader? If not, please close this issue.

**Comment by MasterPlexus** [comment]
I have the blue reader, but did not use it, because it has no update for the L2 (sadly, because I think this will be a good idea if the Bluetoothstack of L2 will stop working). 

I don't know the usage of the blue reader today in the wild, so I could not say if this commit will be helpful for them.

I would say it could be dropped, as it is searchable, and could be reopened if needed.
