### ISSUE TITLE
Android 10 notification trend arrow points in wrong direction

### ISSUE THREAD

**Issue by jamespaulley** [NightscoutFoundation/xDrip#1242]
The downwards trend arrow icon in the persistent notification is pointing in the wrong direction on Android 10. I'm using a Google Pixel XL.

https://photos.app.goo.gl/bPSJRJ6TntrdqGBm7

**Comment by duncanbarnes** [comment]
Think this is a duplicate of my issue here:

https://github.com/NightscoutFoundation/xDrip/issues/1016

Might get a chance to delve into some of the xdrip code and have a look with all this down time although Android isn't something I develop on frequently.

**Comment by Navid200** [comment]
Duplicate: https://github.com/NightscoutFoundation/xDrip/issues/1016
