### ISSUE TITLE
where is api doc. can you give me link,thx

### ISSUE THREAD

**Issue by shean023** [NightscoutFoundation/xDrip#1244]
where is api doc. can you give me link,thx

**Comment by Navid200** [comment]
@shean023 Would you pleaser ask using the support channels.
Someone there may be able to answer your question.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

If there is no documentation for what you are looking for, we may have to create it.  There are other subjects that fall in that category as well.   

Please update.

**Comment by tolot27** [comment]
@shean023 There is only the [Web Service API](https://github.com/NightscoutFoundation/xDrip/blob/master/Documentation/technical/Local_Web_Services.md) exposed.
