### ISSUE TITLE
Calibration provided via syringe icon doesn't reset calibration timer.

### ISSUE THREAD

**Issue by PedanticAvenger** [NightscoutFoundation/xDrip#1246]
When resolving a calibration error (in this case insufficient calibration) using the syringe icon, when the calibration is accepted by the transmitter the timer for regular calibrations doesn't get reset.  I have 12hr calibrations and apparently need to enter it via the menu calibration option to have timer reset.

**Comment by dg77777** [comment]
I'm not sure that adding measure from syringe icon actually does anything. In my case seems it doesn't. Haven't found any documentation for it, but I think it should be done from the calibration menu (unfortunately it gives errors for G6).

**Comment by jamorham** [comment]
I think this issue should be resolved in the 26th May nightly.

**Comment by Navid200** [comment]
@PedanticAvenger Were you able to try the release jamorham mentioned?
Can we close this issue?
Thanks

**Comment by PedanticAvenger** [comment]
Referenced version addressed the issue.
