### ISSUE TITLE
Calibrations provided to G6 seem to be modified from what was entered.

### ISSUE THREAD

**Issue by PedanticAvenger** [NightscoutFoundation/xDrip#1247]
I may be reading this incorrectly or it could be cosmetic but when I entered a calibration, the value shown in the transmitter queue was 0.5 mmol/L lower than the value I entered.  I've verified this with a couple subsequent calibrations.  In the attached image, the calibration value provided was 7.0 mmol/L.

![image](https://user-images.githubusercontent.com/15637097/74851707-d4931f00-52f8-11ea-80c4-64734c2a05ac.png)

While it could be a perception bias I've felt for a while that my sensors calibrate low from what I provided and the amount it is off seems to align with this difference.

**Comment by jamorham** [comment]
Hi, when you have done this, can you tell me which menu item or other method you used to enter the calibration? Also if you look in the event log does it report the same value in there?

**Comment by PedanticAvenger** [comment]
In this particular case the value was entered via the syringe icon, I was watching closely as I was resolving a Insufficient calibration issue.  I will watch it again next calibration via the reminder/Calibration menu option to see if it presents the same.

**Comment by jamorham** [comment]
I've tried this with auto-calibration enabled and entering blood test values the same way and I can't get it to show anything in the queue other than the exact value I entered. Can you see if you can reproduce the problem?

**Comment by PedanticAvenger** [comment]
Will do.

**Comment by Navid200** [comment]
@PedanticAvenger Can we close this issue?

**Comment by PedanticAvenger** [comment]
I was unable to reproduce the issue reliably and after multiple updates has not shown up again.
