### ISSUE TITLE
G6 transmitter deaths after 25 and 24 days

### ISSUE THREAD

**Issue by IntoxRRR** [NightscoutFoundation/xDrip#1248]
I have a severe problem with a short lifetime of G6 transmitters.
The first one died after 25 days (8Gxxx, SB 2020-08-08, shelf life: 145/365, A: 279, B: 256, R: 8473 on it’s last day).
Now the second transmitter stopped working after 24 days! (8Hxxx, SB 2020-10-28, shelf life: 89/365)

xDrip (1910271159) didn’t receive data anymore. System status showed “Scanning…”. Transmitter BT device couldn’t be found by other devices either.
Now I’m wondering if their failures were really caused by an empty battery. Might it be possible to break a transmitter by settings or actions I perform from within xDrip? Is it just a coincidence that both transmitters broke after almost the same time span?
Any help highly appreciated!

**Comment by jamorham** [comment]
Can you update to the latest xDrip+ nightly. The version you're using pre-dates the firmware version of the transmitters you're using. I doubt it would cause the problem described but you should update anyway.

https://github.com/NightscoutFoundation/xDrip/wiki/How-to-get-the-Nightlies-on-Automatic-Update

**Comment by Lorekeks** [comment]
Hi @IntoxRRR , have you seen the similar post by @Dainem21? https://github.com/NightscoutFoundation/xDrip/issues/1167#
I also started a discussion on that in the German looper-group https://de.loopercommunity.org/t/transmitter-mehrfach-nach-4-wochen-kaputt/2992/2, but so far, no resolution has been found.

**Comment by tolot27** [comment]
@IntoxRRR and @IntoxRRR Is the problem solved with a newer xDrip version? If yes, please close this issue.

**Comment by IntoxRRR** [comment]
No, the latest version hasnt solved the problem. I had to buy a newer phone with android9. Running fine since then, with the same xDrip version.
