### ISSUE TITLE
Configurable range views

### ISSUE THREAD

**Issue by gregorybel** [NightscoutFoundation/xDrip#125]
It would be really great if you could add a setting to configure how many time in past we see the BG curve.
Same way as NS doest it for example with a 3, 6, 12 and 24 hours views.

Would it be possible?

**Comment by jamorham** [comment]
Some of this is dynamically scaled, for example as soon as a treatment simulation is in effect but otherwise it might be possible. 

I certainly could do it by optionally replacing the bottom zoom chart with buttons to select the time period. Would that work for you?

**Comment by gregorybel** [comment]
Hi

**Comment by gregorybel** [comment]
I think this is a really good idea and would love to see it!

**Comment by jamorham** [comment]
IF you long press on the xDrip icon on the app home screen you can enable time buttons. If you long press on a time button you can lock the view to that time period.

**Comment by gregorybel** [comment]
fixed
