### ISSUE TITLE
Feedback/Bug Reporting Broken

### ISSUE THREAD

**Issue by adanvdo** [NightscoutFoundation/xDrip#1250]
I noticed after updating to the 2/20 nightly that I cannot send logs or submit feedback/ bug reports. 

The app appears to attempt sending it and displays "Error sending feedback:"

This was reproduced on 2 devices.
![Screenshot_20200221-235320](https://user-images.githubusercontent.com/26498008/75086724-63748700-5505-11ea-8086-cc2eb24cb6d0.jpg)

**Comment by teleriddler** [comment]
I am experiencing the same issue with a slightly different message.

Version: Nightly Feb 17th 2021

Issue:  View Logs and hit "upload", when screen loads to input email address the error below is shown "Could not package up all logs, using most recent.   Same thing when using "Send Feedback to a develop" as I am guessing the underlying function is related that packages and send the logs files.

Email is never sent after hitting "send message".

![image](https://user-images.githubusercontent.com/7156327/109355702-e1d5d880-787f-11eb-9a4e-ae869eeb4a22.png)

**Comment by teleriddler** [comment]
Another user I was assisting with the same Feb 17th nightly version had the exact same issue running on Samsung M51.  I experienced it on my Samsung S7 Edge.

**Comment by Navid200** [comment]
I am puzzled what has caused this.
People have sent logs successfully recently:
https://github.com/NightscoutFoundation/xDrip/issues/1664#issuecomment-799351659

**Comment by Navid200** [comment]
I am closing this because I don't think this is a present issue.
Please reopen if you are still experiencing it.
