### ISSUE TITLE
Transmitter 8K.... doesn‘t connent

### ISSUE THREAD

**Issue by PeritoC** [NightscoutFoundation/xDrip#1253]
I tried to connect a G6 ID 8K____
I inserted the sensor but did‘nt start it. Then I pit the sensor in and waited for „Got Glucose“ or „Got no Raw“. None appeared.
The Transmitter randomly appeared in Bluetooth but didn‘t connect to xdrip.
After 3hours of switschin on and off Bluetooth I started the thing with the original Dexcom Receiver, that worked within minutes.
Please tell me how I could help with this.
Sincerely PeCa

**Comment by jamorham** [comment]
https://github.com/NightscoutFoundation/xDrip/wiki/Enabling-Debugging-for-OB1-collector

Please enable OB1 debugging and try again to connect and if it doesn't work submit logs from within xDrip and let me know when you have done.

Please also let me know which xDrip version is being used, the Phone and Android version and the dex firmware number if it shows within the xDrip status page for G5/G6 etc.

**Comment by PeritoC** [comment]
I am sorry I can‘t send you logs from within xdrip because the emailadress is missing.
Transmitter ID is 8K....
Firmware didn‘t show up
xdrip version 33e5f35-2020.02.20
Phone is SM-520F A5 2017
LineageOS 16.0 

Sincerely
Stephan aka Perito Castano

**Comment by PeritoC** [comment]
Hi,
I just sent the logs (castanoperito@gmail.com)

Sincerely
Stephan

**Comment by jamorham** [comment]
Thanks for your logs. I deleted your comment that included your email address for privacy and responded to you via email. The logs show that no connection is being made successfully from the phone to the transmitter.

**Comment by PeritoC** [comment]
Hi JamOrHam.
Thanks for caring!
I guess, my phone SM-A520F is a no go with Lineage 16.

Sincerely
Stephan

**Comment by xannasavin** [comment]
#1084 this issue might be related...

**Comment by Navid200** [comment]
Can we close this issue?

**Comment by PeritoC** [comment]
Yes, this issue can be closed.


Liebe Grüße 
Stephan

**Comment by Navid200** [comment]
Thanks
