### ISSUE TITLE
MiaomiaonV2 Battery Life

### ISSUE THREAD

**Issue by Diabeticliberty** [NightscoutFoundation/xDrip#1255]
I have posted in  another thread on here stating that since switching from Miaomiao V2 to V2 any and all negative issues that I had previously been experiencing with Xdrip+ thankfully are no more.  A matter for which I am truly thankful. What I am finding now however is that my sensor has another 4 days to run but my Miaomiao battery life is down to 15% and does not look like it will last the duration of the sensor. Is anyone else having the same or similar issues and have you found a fix please?

**Comment by zip9** [comment]
Similar experience. My MM2 seems to die a day or two early. I bought a clip on mount that works great with no adhesive, allows charging the unit. Search eBay for 'SNAP ON HOLDER FOR MIAOMIAO 2'. Came from Europe, so it took a while to arrive (about $13). Have seen comments that battery life gets better over the first few months....good luck.

**Comment by Diabeticliberty** [comment]
Many thanks for your advice. I charged my Miaomiao up and stuck it back on my sensor. 2 hours later Xdrip+ warned that even though the battery indicator was showing 100% when I stuck it down the charge was now less than 10% Pit must have been some kind of glitch as the battery indicator went back up to 100% a little while afterwards. I will have a look for the clip that you recommend

**Comment by Diabeticliberty** [comment]
I have just taken a look at the clip and it looks ok. I have found though that if you only apply the double  sided sticker to the rectangular section of the Miaomiao 2 and do not apply the round sticker to the round section you can remove the transmitter from the sensor without disturbing it. The bond seems to be acceptable and I have not had any adverse connection issues between Libre and Miaomiao.

**Comment by Navid200** [comment]
@Diabeticliberty Would you please close this issue if it has been resolved?
If not, would you please explain why you believe this is an xDrip issue?
You can always consult with the user community using the support channels.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks
