### ISSUE TITLE
BG broadcast issue with NFC and libre

### ISSUE THREAD

**Issue by gregorybel** [NightscoutFoundation/xDrip#126]
When I scan my libre over NFC with a few hours between each scan, then xdrip-plus broadcasts several times the same last value instead of broadcasting all new values since last scan.

See screenshot:

![2017-05-15 19 24 07](https://cloud.githubusercontent.com/assets/24234385/26554787/489b4828-4492-11e7-9f93-584e65a493b9.png)

**Comment by jamorham** [comment]
Thanks for reporting this. I'm trying to determine where the problem is originating from.

As a test can you do this:

Go to `Settings` -> `Inter-app Settings` and un-check `Send Display Glucose` then repeat your test and let me know if you get the same problem?

**Comment by gregorybel** [comment]
Hi John, 

I unchecked this and no more issue! 

Hope this help to fix issue. 
Thanks

**Comment by jamorham** [comment]
Okay thanks, this means that the feature called `Display Glucose` which includes noise compensation and calibration plugins will need to be updated to support data coming in out of sequence which I think is what is causing your issue here.

**Comment by gregorybel** [comment]
Jon, can you tell me where in the code you think the issue is then I will try to fix it and if I manage then will do a PR.

**Comment by AdrianLxM** [comment]
@gregorybel, it must be in this call: https://github.com/NightscoutFoundation/xDrip/blob/master/app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/BgSendQueue.java#L238

**Comment by gregorybel** [comment]
Thank you @AdrianLxM!
