### ISSUE TITLE
Tic Watch Pro 2020 if it serves as a Collector

### ISSUE THREAD

**Issue by Unrealsweb** [NightscoutFoundation/xDrip#1261]
Only every 10 minutes on the Ticwatch Pro 2020 if it serves as a collector

**Comment by Unrealsweb** [comment]
![TicWatchpro](https://user-images.githubusercontent.com/6748067/76161706-267bd780-6136-11ea-8fdf-181e2bb59842.png)

**Comment by Unrealsweb** [comment]
Version von 20 Februar

**Comment by mick711** [comment]
I use this watch with last version liké you and blucon and dont have this problem with Sony z5c.

**Comment by Unrealsweb** [comment]
TicWatch Pro 2020 + Sony Xperia 5 with Android 10

**Comment by Unrealsweb** [comment]
Can I somehow patch the watch?
developer options, and ADB debugging is enable, please Help me

**Comment by razerrazer** [comment]
Same problem here with my tic watch pro 2020 and miaomiao 2.

**Comment by Navid200** [comment]
Please consult with the user community to see if what you want can already be done, or if there is a work-around.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Please only open an issue to report a bug or for a feature request with no work-around.

**Comment by Navid200** [comment]
We can always reopen this.
Please update if you want to.
