### ISSUE TITLE
Ghost fingerprick calibration values entered.

### ISSUE THREAD

**Issue by tristanokeefe** [NightscoutFoundation/xDrip#1266]
### Logs submitted today as of 10:20am GMT with the comment tr*****.ok****@gmail.com.

At 07:19 this morning i had a ghost fingerstick calibration added that whilst not even entered by me, was also around 4 mmol above my current reading. I was not even in the same room as my phone at the time, which is slightly worrying. 

I have had this happen before as well but have never caught it  to get logs etc and then forgotten about it. Each time this happens it is a value that is straight away used for calibration and then i am required to override the calibration to ensure it does not screw with my calibration curve.

**Comment by jamorham** [comment]
Are you using a bluetooth glucose meter? What timezone are you in?

**Comment by tristanokeefe** [comment]
I am using no bluetooth glucose meter, i use an Accu-check mobile which doesnt have any bluetooth capability. I am in GMT

**Comment by jamorham** [comment]
Are you using Sync followers or Nightscout with the treatment download facility enabled?

**Comment by tristanokeefe** [comment]
I have nightscout enabled and 1 follower uses it but does not have treatment download enabled.

**Comment by okeetris** [comment]
Has just happened again. Have uploaded logs with same comment. This time I had recently done a blood sugar reading but not on a connect able blood meter. Had just taken my phone off a wireless charger and turned on the torch.

**Comment by simonpickering** [comment]
I have the same problem, but I had assumed mine was related to using my Bluetooth Contour Next One - I get both high and low readings and they are very very different to my actual blood glucose (and as I have auto-select calibration values it messes up my calibration as is the case for the OP). 

Interestingly I also eventually see the actual reading, but for some reason the ghost/phantom one is selected for auto-calibration. I need to double check and see if the actual reading appears at the same time as the phantom reading, but I have a feeling it doesn't appear until later/I unselect the phantom reading in the calibration readings page.

I've also sent in a pair of logs over the past couple of weeks with a comment about this. My email is almost exactly my github name + gmail.com. I'm about to send in another one now (the previous two I was low and the phantom was high, this one I'm high post-exercise and the phantom was very much lower. I've now switched off auto-cal!!!)

I'm happy to try to debug if you've any thoughts as to where to start.

**Comment by claresloggett** [comment]
I have had this issue happen too: ghost calibrations appearing when I have not entered any real fingerstick reading recently, and throwing my BGL calibration way out of whack. I've had it happen in the past but have only managed to document it properly this time. This time, there is a plausible cause: a real fingerstick reading entered some hours earlier was processed late for some reason, resulting in an apparent "ghost" calibration.

Here is a screenshot of xDrip+ just after it (incorrectly) calibrated. The "ghost calibration" of 5.8mmol/L happens around 18:13 and drives my CGM BGL to 5.6mmol/L - I did not enter a fingerstick reading at this time, and I didn't know where this calibration had come from. As soon as I saw this happen, I did a real fingerstick reading, and got a value of 11.7mmol/L. So the CGM reading before the "ghost calibration" had been quite accurate, and the 5.8 was way off. I entered the 11.7 reading and had to use "Override Calibration", indicating that xDrip+ really thought there had been a recent calibration. You can also see that about 3 hours earlier, there is a fingerstick reading that looks like the same value - that one is a real entry! I entered it using the Treatments dialog.

![2020-10-22 18 15 33](https://user-images.githubusercontent.com/1815107/97068274-e52b3000-1611-11eb-8681-1fa29685b7c8.png)

Here is the event log for the same time period:

![2020-10-23 23 27 30](https://user-images.githubusercontent.com/1815107/97068326-23285400-1612-11eb-820a-8b90f982eb47.png)

This seems to explain what happened. At 15:08 I entered a fingerstick reading of 5.8 mmol/L. I have the setting `Settings -> Less common settings -> Advanced calibration -> Use Treatment BG values` set to `Automatic`. So, this reading was queued as a calibration. But then at 18:13, about 3 hours later, it is apparently processed as a calibration and applied to the current sensor reading, not the past sensor reading. You can also see the (correct) BGL of 11.7 that I entered at 18:17 after I noticed all this had happened. 

I don't know if on past occasions I've seen this issue, if this kind of "late auto-calibration" might also have been the cause. It's plausible as I haven't in the past thought to check for earlier readings and perhaps they were much earlier - this time the earlier reading was at least still on the screen.

This issue happens only very occasionally but it's pretty unnerving when it does. In the worst case, if looping, this can cause over-delivery of insulin.

I'm using a Pixel 2 and a Dexcom G5, but the readings causing the problems are manually entered from fingerstick readings. I'm running Android 11 but have experienced the issue before and until recently was running Android 10. xDrip+ version is 14a03a7-2019.05.18. I'm happy to screenshot or upload more logs if that would help.

**Comment by claresloggett** [comment]
Another example occurred yesterday, this time making xDrip+ and AAPS think I was high rather than low:

<img src="https://user-images.githubusercontent.com/1815107/97384983-e9fb2700-1924-11eb-9e1a-aeaeeed966ad.png" width=50%>

<img src="https://user-images.githubusercontent.com/1815107/97384990-ec5d8100-1924-11eb-9d17-831f889a0cbf.png" width=50%>

As you can see from the log the true fingerstick reading was 4.3 mmol/L.

I won't post future examples, just wanted to show that the pattern in the logs seems to be consistent.

**Comment by Navid200** [comment]
@claresloggett 
What happens if you change the setting from Automatic mode to never use them?

**Comment by simonpickering** [comment]
Interestingly after a period of not having these ghost calibrations I'm now getting them quite consistently since changing phone. I've just uploaded a set of logs.

**Comment by Navid200** [comment]
I have never experienced this issue.  I have been using xDrip non-stop for more than 3 years now.  I started with G5 and now use G6.
I don't have a Bluetooth blood glucose meter.  I don't download treatments from Nightscout or anywhere else.
To calibrate, I just do that from the top left menu button.  I never enter a blood glucose reading into the treatment menu.
I always have automatic calibration disabled.

Is any of you who is experiencing this problem willing to do what I do and report if you still experience the problem?

If your problem is resolved and then all of you can confirm exactly which option is the cause of this, we may have a chance of finding the cause and solving the issue.

**Comment by simonpickering** [comment]
For me it comes and goes, I'd not seen any ghost points for months (with automatic calibrations turned on) and then they started again when I switched to a new phone afair. I can't see the phone having been the cause but rather (re)starting the sensor (which has afaicr been the case in the past). I disabled automatic calibrations after a few ghost points and they've not come back. I'll continue running like this and see if any occur (i.e. with Bluetooth connection but without automatic calibrations turned on) as it at least eliminates a single cause at a time.

I'll have to open another ticket for this, but it would be quite useful to be able to save the logs locally to look at (at the same time as looking at the code) as at the moment the only options are to email them somewhere and/or to screenshot them which is very slow and error prone.

**Comment by TiredNConfused** [comment]
Hi, I've been having this off and on. Have just uploaded logs. I had auto calibration turned on but have now turned it off to see if that stops it.

**Comment by claresloggett** [comment]
Right after I reported this issue, I switched auto-calibration off, and can
confirm that stops it from occurring.

Recently I've been trying out Libre2 sensors and therefore not using
xDrip+, but I've just started using xDrip+ again with different sensors so
I'll try turning auto-calibration back on after Christmas and see if the
issue recurs.

**Comment by Navid200** [comment]
Please disable automatic calibration and let us know if the problem stops.  

| User | Problem solved after disabling automatic calibration |  
|------|-----------------------------------------------------------|  
| @tristanokeefe | ? |  
| @okeetris | ? |  
| @simonpickering | ? |  
| @claresloggett | Yes |  
| @TiredNConfused | ? |

**Comment by simonpickering** [comment]
I can confirm that I've not had a problem since disabling auto-cal straight after my last post above (29 Oct) - I didn't respond as I was attempting to start digging into the code to see if I could add more than a confirmation!

**Comment by Navid200** [comment]
It seems auto-calibration is the cause.

**Comment by simonpickering** [comment]
Wontfix/not planned as the state rather than completed?

**Comment by Navid200** [comment]
It's closed, not completed.
