### ISSUE TITLE
A6 Medtrum

### ISSUE THREAD

**Issue by kimbersdiabetic1** [NightscoutFoundation/xDrip#1268]
Hello,

I have the 14th Feb 2020 Xdrip version. will the Medtrum A6 work with this and is it reliable? I know in July 2018 Jon had some issues with it.

Many thanks.

**Comment by kimbersdiabetic1** [comment]
Will this work Jon?

**Comment by Navid200** [comment]
@kimbersdiabetic1 Would you please close this issue if you have got an answer already?
If not, would you please post in the Gitter room?
https://gitter.im/jamorham/xDrip-plus
Thanks

**Comment by Navid200** [comment]
Closing dur to inactivity
