### ISSUE TITLE
Request adding Arabic language to Crowdin

### ISSUE THREAD

**Issue by abutmim** [NightscoutFoundation/xDrip#1270]
Hi,

Is it possible adding Arabic language to Crowdin?
and adding me to translate it?

Thank you

**Comment by Navid200** [comment]
@tolot27

**Comment by tolot27** [comment]
Arabic language was [added](https://crowdin.com/project/xdrip/ar) to Crowdin some time ago, but only 9% is translated.

**Comment by Xapper-al-Happer** [comment]
trust me I won't disappoint

**Comment by tolot27** [comment]
@Xapper-al-Happer You can join via https://crowdin.com/project/xdrip/invite?d=q665n465c5c5m4h5c3j4n4a3f3a3
