### ISSUE TITLE
Implement 36h Trend (>24h) as quick alternative to History

### ISSUE THREAD

**Issue by emp-00** [NightscoutFoundation/xDrip#1273]
Currently the max timespan in the xDrip+ main window is 24 h. Very often I would like to see my carbs and bolus just slightly before 24h. For example: When I start eating my breakfast only 5 mins later than the day before I have to use the History function to check which dose I used the day before and how the trend evolved. Looking up "what happened yesterday" is very important in daily life (for me).

It would therefore be great to add functionality extending the timespan in the main window e.g. to 36 h (3, 6, 12, 24, 36h).  Anybody else like this idea?

**Comment by ANDREAPIPPI** [comment]
I absolutely agree with emp-00. 
This could be very useful on some occasions.
Pippo

**Comment by Navid200** [comment]
This is a very good idea.  Would you please add your voice to the existing issue? 
https://gitter.im/jamorham/xDrip-plus
I am going to close this.  But, if you believe this should have a different issue, you can always reopen.
