### ISSUE TITLE
Extremely high resistance (5000+)

### ISSUE THREAD

**Issue by JfBrshie56** [NightscoutFoundation/xDrip#1276]
Ever since I started using XDrip+, I've had problems with transmitters not lasting the full 3 months. The one that just died (8H) lasted only 72 days. This never seemed to be a problem with the G6 app, but they don't support my Pixel 4 (Android 10), so I came to use XDrip+. 

Anyway, I just dropped a new transmitter into a new sensor and out of the box, it is sitting at 5888 resistance. The previous transmitter's last reading was 8264... It was an 8H transmitter, FWIW

I've never seen anyone mention any numbers this high before, typically they are more in the 1000 neighborhood. Is there anything that can be done? Is this number sensor or body chemistry related, or is it a function of the transmitter itself?

![Screenshot_20200320-113042](https://user-images.githubusercontent.com/62439443/77186231-92e4c800-6aa0-11ea-9f3e-5c9a8b559dad.png)

**Comment by emp-00** [comment]
For comparison - currently running an 8GC tx Firmware 2.18.2.88 for 27 days: VA 310, VB 293, Resistance 7707 (the ~1000-1500 neighborhood resistance was valid for 80 and 81 transmitters (.15 firmware); Dexcom has changed something with the 8G+ tx giving higher resistance. So it's normal I guess.

**Comment by jamorham** [comment]
I'm not sure if the resistance value either isn't available or isn't decoded properly on the 2.18.2.88 firmware but I would say that the reported value may not be useful. The voltages are really the only significant factor.

**Comment by Navid200** [comment]
@JfBrshie56 Would you please close this issue?
The temperature reporting format changed with a Dexcom transmitter firmware update. The reported temperature and resistance, for the same reason, have been incorrect. With recent releases of xDrip, those two parameters have been removed until the correct format is implemented.
