### ISSUE TITLE
Basal insulin recording

### ISSUE THREAD

**Issue by Abdullahsi** [NightscoutFoundation/xDrip#1277]
Dears 

First of all, many thanks for all helps & support, I notice that in xdrip only we can add our Bolus units but not Basal units, pls we need a feature to add our Basal units as well to be reflected in the reports so we can track our records 

Right now I add my Lantus units as a bolus & I add a note indicating that it is Lantus unit but I know that is not the right way to do it

thanks

**Comment by steve8x8** [comment]
What about converting your daily Lantus dose into a fake basal rate profile? (xDrip and most of the Nightscout infrastructure were never thought to be used by penners.)

**Comment by vytux-com** [comment]
Would be great to have this, as converting to fake rate doesn't help with tracking the injections especially if your dosage isn't the same every day.

To be honest the recording of pump rate seems a lot more redundant than manual dose recording

**Comment by vnniyB** [comment]
+1 I inject Lantus twice daily and checking the app helps if your not sure if you missed your alarm or not  ;) 
I was hoping to work on separating the IOB graph lines into separate lines based on insulin brand, however I think separating basal and bolus would be better. 
Not sure how that would look on the UI

**Comment by Navid200** [comment]
Closing this as it seems to be a duplicate.
Please explain why we need this issue to remain open if issue 1125 is also open and we can reopen this.
