### ISSUE TITLE
No display after update to Android 10

### ISSUE THREAD

**Issue by LavineDavid** [NightscoutFoundation/xDrip#1281]
I have successfully used the app for several months on an Note 9 running Android 9, with FSL-US 14 day sensors and an MM2. After update to the Android 10, they app no longer displayed any data.  It was not a connection issue as  it showed connection in System Status and the Event Log. It would display battery condition of the MM2 and the Sensor Age, along with any manual entries. Calibrations also disappeared from the Main Menu.

I upgraded to the Note 10 after numerous FB - XDrip group members said they were succesfully using it on Android 10.   I had hoped that the update had been a troubled install and that working from a fresh version of Android 10 that things might work.  No such luck, same situation - connects, collects data, displays only as mentioned above.

Please fix this issue!

thank you!

**Comment by LavineDavid** [comment]
Additional Note:

I am currently using the latest nightly build without success.  I deleted the app and went back to I  think it was something like Oct 27, which was the version that I had been on since the update, no success.  Deleted the app again and then reinstalled the latest build, still no success.

**Comment by derTuennes** [comment]
I can confirm that. Same at a Galaxy S20 with Android 10.

**Comment by JZhovner** [comment]
I can confirm that. Same at a Xiaomi mi 9 lite with Android 10.

**Comment by JZhovner** [comment]
https://github.com/NightscoutFoundation/xDrip/issues/1258#issuecomment-595393472

**Comment by annsera** [comment]
My pixel 2xl stopped working when I upgraded to 10 and my pixel 3xl, which is on Android 10, also isn't working.

Android 10 has some deferent permissions and although I have tried giving xdrip the ability to modify system settings, it's still not working.

**Comment by Navid200** [comment]
@LavineDavid Would you please close this issue if it has been resolved?
Otherwise, ,would you please update?
Thanks

**Comment by LavineDavid** [comment]
Resolved
