### ISSUE TITLE
Am I misunderstanding the Simulation settings?

### ISSUE THREAD

**Issue by steve8x8** [NightscoutFoundation/xDrip#1289]
I've caught a slight cold, and would like to adjust my simulation settings accordingly.
Normally, I'm rather happy with the (default, I think) settings of 12g carbs per unit, and 40 mg/dl per unit.
If I move the slider to 120% the insulin sensitivity would drop accordingly, to 33 mg/dl per unit, but at the same time, the carbs per unit would go up to 14.4. The product of both values stays constant. This looks wrong to me - as the glucose rise per carb (i.e., the ratio of both values, not their product) is supposed to stay the same. There's certainly something I must be misunderstanding? Latest xDrip nightly...

**Comment by Navid200** [comment]
@steve8x8 Would you please use the support channels for asking questions instead of opening an issue here?
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks

**Comment by Navid200** [comment]
I am closing this issue as there have been no answers over a year.  
It's more likely to get answers from the support channels.
