### ISSUE TITLE
Optional alert on REST API Upload error

### ISSUE THREAD

**Issue by zjedr** [NightscoutFoundation/xDrip#129]
Enhancement request.
Optional alert after x number of consecutive REST API Upload errors.
This alert would inform the user to potential network problems when trying to upload data to NS or their OpenAPS rig.
I my setup it would indicate a problem with my full time BT tether to my OpenAPS rig.

**Comment by roycesimpson** [comment]
+1
Sometimes my Azure NS site stops taking data and needs to be restarted.  I can't tell this is happening unless I go into system status and see that the rest api uploads are backing up.  Would be great to get notifications that this is going on so I can restart my ns site.

**Comment by TecMunky** [comment]
Also, the API error remains on the status screen for hours, even after uploading has subsequently succeeded.  I haven't figured out how or why the error disappears yet.

**Comment by jamorham** [comment]
The 16th Aug nightly now has this feature. It appears to work well in my local testing, please let me know. There is an extra option to turn the alerts on/off from the Rest API cloud upload settings page.

**Comment by jamorham** [comment]
Has anyone seen this alert be raised yet? @zjedr  ?

**Comment by zjedr** [comment]
I haven't done a controlled test and I thought it wasn't working but I got the alert for the 1st time today after an extended period of my openAPS rig being offline. When I got the alert it said it had missed 6 uploads, I would like to get the alert after 2 consecutive missed uploads.

**Comment by Navid200** [comment]
@zjedr Is this working?  Have you been able to test it?

**Comment by zjedr** [comment]
@Navid200, yes, this is working.

**Comment by zjedr** [comment]
@Navid200, yes this is working

**Comment by TecMunky** [comment]
> Also, the API error remains on the status screen for hours, even after uploading has subsequently succeeded. I haven't figured out how or why the error disappears yet.

Is there any information about when and why the message finally disappears?
