### ISSUE TITLE
Tidepool Treatment Times are Incorrect

### ISSUE THREAD

**Issue by asavageiv** [NightscoutFoundation/xDrip#1291]
Notice in the attached screenshots that the treatments given in the evening of April 3rd show up in the morning of April 4th.

If this is difficult to reproduce, it may have to do with timezone shifting or loading settings from a different phone. On March 21st I flew from Cambodia to Canada. A week later I changed phones and loaded the settings from the old phone to the new via QR code. Maybe these are irrelevant details, but maybe not.

<img width="997" alt="Screen Shot 2020-04-04 at 8 30 58 AM" src="https://user-images.githubusercontent.com/3028205/78450838-76738e80-764f-11ea-8803-f640b401ccfa.png">

<img src="https://user-images.githubusercontent.com/3028205/78450916-2943ec80-7650-11ea-8043-bd62780d9b3a.png">

**Comment by Navid200** [comment]
I would like to close this unless it is an xDrip issue.
If it is, would you please provide steps for recreating the issue?

**Comment by asavageiv** [comment]
Just close it. I think it is an xDrip issue, but moving across timezones is
probably rare enough for it to not be worth fixing.

**Comment by tolot27** [comment]
We need at least a reproducible procedure. If this would be an xDrip issue, other sync services like Nightscout should be affected, too.
