### ISSUE TITLE
please include HTTP "Date:" header in xDrip Web Service responses

### ISSUE THREAD

**Issue by ecc1** [NightscoutFoundation/xDrip#1304]
1. It's required by the HTTP spec.
2. It's a useful way for a rig to get the phone's time.

Please consider supporting the HTTP HEAD method too, which would be useful when just the time is desired, and the actual BG entries aren't needed.

**Comment by Navid200** [comment]
Has this been addressed?  
Can we close this issue?

**Comment by ecc1** [comment]
Yes, it works fine now, at least in the old 2020.11.27 version I'm running.
