### ISSUE TITLE
Diasend upload

### ISSUE THREAD

**Issue by razerrazer** [NightscoutFoundation/xDrip#1306]
It's there a way to upload your AGP data from xdrip to Diasend to share your data with your hospital?

**Comment by master3395** [comment]
Sadly there is no API to import data from Diasend.
I've asked them.
![image](https://user-images.githubusercontent.com/4199669/79757443-641a7580-831c-11ea-9443-6ea17d93b96d.png)

**Comment by tolot27** [comment]
Duplicate of #716
