### ISSUE TITLE
Support for Medtronic Guardian Connect 

### ISSUE THREAD

**Issue by jamorham** [NightscoutFoundation/xDrip#131]
I've received questions about whether support can be added for this data source. 

If anyone knows anything about it please get in touch. Thanks.

**Comment by Schoggiweggli** [comment]
Hey, what do you want to know about it ?

**Comment by tolot27** [comment]
#1649 implements a Medtronic CareLink follower. This might be a workaround until we have native support.

**Comment by Navid200** [comment]
Do we now have support for this after this PR was merged?  https://github.com/NightscoutFoundation/xDrip/pull/1649
So, can we close this issue now?

Or, is this different?

**Comment by Navid200** [comment]
I'm closing this issue because it has been inactive for a very long time.  We can reopen if needed.

**Comment by mortenfyhn** [comment]
I would love a clarification on how far anyone has gotten on interfacing directly with this, or interfacing with pumps like the Minimed Mobile 780G, without going via carelink. I'm also interested in contributing.

**Comment by tolot27** [comment]
Check this repository: [OpenGuardian](https://github.com/palmarci/OpenGuardian)
