### ISSUE TITLE
Feature Request: Scheduled Automatic Database Export

### ISSUE THREAD

**Issue by adanvdo** [NightscoutFoundation/xDrip#1311]
It would be very helpful if you could schedule a daily settings/database export.

If for any reason the settings or database are lost, this would provide a recent backup to import that will restore most of what was lost.

I reported in issue #1280 that my database is getting wiped about once every sensor session, but I appear to be the only one reporting this problem. Having access to a daily backup would be a nice workaround

**Comment by tolot27** [comment]
I wonder whether you have found "Save Database Daily" in the "Less common settings".

**Comment by adanvdo** [comment]
Just found this. thank you.
