### ISSUE TITLE
xDrip + blucon + libre does not receive data

### ISSUE THREAD

**Issue by mikimisz** [NightscoutFoundation/xDrip#1315]
Hi All,

I just started my adventure with F/CGM, I got Libre 1 on my arm for 3 days. I got blucon and xDrip installed on my phone.
I did all according to this https://github.com/gregorybel/xDrip-plus_old/wiki/How-to-use-Blukon-with-xdrip
And now I got such status in xDrip:
https://ibb.co/4JygtQY
and 
https://ibb.co/7CxwFGX

My phone:
Xiaomi Mi 9T, MIUI 11 -11.0.5.0 Global, Android 10.

For some restart it cannot receive any data.
For some it can receive some data from blucon - best so far 2/3.
But anyway it cannot receive enough good data to pass calibration.

Any idea what is wrong?

Thanks!
Michał

**Comment by mikimisz** [comment]
Please delete.
After XXth phone restart it has started.

**Comment by tzachi-dar** [comment]
I believe that your phone has problems connecting to the blucon.

Please try disabling/enabling "trust auto connect" and "use scanning"
Probably one of the 4 possible combinations should work well.

**Comment by mikimisz** [comment]
It seems I don'y have such options in that phone.
Any one have any experience with Xiaomi Mi 9T / Redmi K20?

**Comment by tzachi-dar** [comment]
They are in xdrip  under settings->less common settings->bluetooth options.

**Comment by Navid200** [comment]
@mikimisz Would you please close this issue if it has been resolved?
For asking questions, would you please use the support channels, instead of opening an issue?
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks
