### ISSUE TITLE
Miband 4 - data loss indication missing 

### ISSUE THREAD

**Issue by keencave** [NightscoutFoundation/xDrip#1317]
With the nightly 20200419 I get no indication on the Miband4 that no new data is available. The old watchface/display remain unchanged until new data come in. This is dangerous as one want to detect any data loss also on the watch. At a quick glance all seems to be OK. You have to check the time of the last reading with the current time tp verify that the data is valid.
Setup: Master phone with xDrip / patched LL app, xdrip sync master, xdrip snyc Follower phone with Miband4 attached.

**Comment by MasterPlexus** [comment]
@bigdigital , I think this is a case for you?

**Comment by bigdigital** [comment]
Hi. this is intended behaviour. Normally you should receive data every 5 minutes. The last bg reading would be displayed on the band wacthface, based on this time, you can consider ф relevance of the data. If xdrip wouldn't receive new data for 30 minutes. The xdrip will force the watcface uploading, and you should see  crossed out last glucose value like on this photo https://bigdigitalhome.files.wordpress.com/2020/01/prot1.jpg .

**Comment by 1337Reis** [comment]
For me it just shows the message no data on the miband 4. It's not willing to update. But if you send the new bg reading as a notification. It shows the notification. Band is authenticated and connected but not able to show the watchface on latest beta

**Comment by 1337Reis** [comment]
![15876814601115935766515599964976](https://user-images.githubusercontent.com/58448081/80156283-d3fe5980-85c3-11ea-8d50-6e1d52e6c2a3.jpg)

**Comment by keencave** [comment]
This seems to be unsafe. The time to display the crossed out last reading should be adjusted to 10 minutes like in xdrip.

**Comment by bigdigital** [comment]
I've checked xdrip source code, the data considered as stale after 11 minutes for most of the data sources, except librealarm, it use 13 minutes interval. I can add two update intervals, one for example can be set to 15 minutes. If there would be no new readings, this timer will update miband screen to see the crossed out last readings. After this, woudl be used second update interval (30 mins), it would update miband screen to show changes on the graph.

**Comment by keencave** [comment]
15 should be OK, that will give similar behaviour to the standard xdrip timers. So the crossed reading will appear after 15 minutes then?

**Comment by bigdigital** [comment]
Yes, except the night mode. In night mode would be used interval defined in th night mode settings.

**Comment by keencave** [comment]
Agree. This make sense.
