### ISSUE TITLE
Error after update to Android 10

### ISSUE THREAD

**Issue by dinizmauricio** [NightscoutFoundation/xDrip#1318]
I have a Samsung cell phone, model A70 and free with miaomiao I. Everything has always worked well. But after upgrading to Android 10, when the device restarts, xdrip does not connect to miaomiao. If I do the connection process several times, the connection happens (I don't know why).
Here is a link to the video explaining the problem: [https://youtu.be/QzKXYXmu5Ls](url)

In other groups people are complaining about the same problem. If anyone can help ...

thankful

Maurício

**Comment by Marcin249** [comment]
workaround:

Forget Bluetooth device in xdrip.
    Go to Settings - Apps - See all Apps - (3 dots on top right corner) - Show system apps - Bluetooth - Delete Data

**Comment by Navid200** [comment]
@dinizmauricio Would you please close the issue if it has been resolved?
You can use the support channels to see if there are any known solutions.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks
