### ISSUE TITLE
MiBand 4 - Not updating watchface if alarm is triggered

### ISSUE THREAD

**Issue by nshtg** [NightscoutFoundation/xDrip#1319]
Thanks for the MiBand 4 integration, it's great!

When an alarm is triggered on the MiBand (e.g. Low alert) the watchface is not updated to the new data.

Version: 19.04.2020

**Comment by nshtg** [comment]
@bigdigital

**Comment by bigdigital** [comment]
Thanks. I guess i found the problem. It seems it is related to the night mode feature. Does this problem happen in the time interval defined in the night mode settings? (by default it is between 11pm and 7am )

**Comment by nshtg** [comment]
I have night mode disabled and it happens during normal work hours too.

**Comment by bigdigital** [comment]
Hm, in this case, i can't reproduce such issue. Before alarm i receive a fresh actual BG data. After watchface has been uploaded, the alarm appears on the band and it vibrates 10 seconds (if not snooze alarm).  The next readings after alarm also updates on miband.  Can you show your xdrip miband setting and miband status info so i can try to replicate this problem?

**Comment by nshtg** [comment]
Screenshots attached!

[screenshots.zip](https://github.com/NightscoutFoundation/xDrip/files/4565353/screenshots.zip)

**Comment by bigdigital** [comment]
Hi, sorry for the delay in response. Can you please try the following apk version? https://www.dropbox.com/s/n4jmpsfsakia2vn/xdrip_miband_0.2.4.2.apk?dl=0

**Comment by Navid200** [comment]
@nshtg if you like to reopen this as an issue, please respond to the suggestion by bigdigital.
