### ISSUE TITLE
Request: add option to turn off "NO BLUETOOTH" vibration on Pebble watchfaces (trend face)

### ISSUE THREAD

**Issue by rstuckmaier** [NightscoutFoundation/xDrip#132]
When using the G5 with xDrip and a Pebble 2 I will often get "NO BLUETOOTH" alerts because the app will reset the bluetooth when it doesn't get a signal from my G5. Normally this isn't a huge issue but it wakes me up multiple times a night.
Some possible solutions:
1. A simple toggle to turn off this alert.
2. A scheduling option to turn it off at a certain time (like during the night) and turn back on automatically.
3. A delay in this alert (either always, or only after the app resets the bluetooth for a missed reading)

**Comment by jamorham** [comment]
Thanks for submitting this. Can you clarify, are you using the `Classic Trend`  watch face or the `Trend Clay Version` watch face?

I am assuming that this `NO BLUETOOTH` alert either bypasses the scheduled quiet time feature of the pebble or that you don't want to use that for other reasons?

**Comment by rstuckmaier** [comment]
I am using the `Classic Trend` watchface. I don't want to set xdrip to be completely silent because I do want low alerts still, unless I misunderstood the settings and low alerts would still override Quiet Time.

**Comment by jamorham** [comment]
Ok thanks for the clarifications. This gives me the information I need to look at the problem. Unlike the other alerts the `No Bluetooth` one is created by the watch face itself so it needs different handling the create an option for it.

**Comment by jamorham** [comment]
The 9th Aug Nightly should have support for this:

https://github.com/NightscoutFoundation/xDrip/releases

Install the latest release either via that link or by selecting the Nightly update channel within the app and accepting the download.

After that look in `Settings` -> `Smartwatch Settings` -> `Pebble` -> `Vibrate when no bluetooth` option which can be unchecked.

The setting requires an updated watch face, the easiest way to trigger reinstallation of this is to switch off and then on the top slider `Pebble Watch Integration` which should then prompt to install the watchface.

Please let me know if this works!

**Comment by rstuckmaier** [comment]
Thank you! It works perfectly. I even had to purposefully turn off bluetooth just to make sure.
