### ISSUE TITLE
Nokia 7.2 Android 10 display locked in landscape mode

### ISSUE THREAD

**Issue by Gdyet** [NightscoutFoundation/xDrip#1323]
Having downloaded android 10, once you view the xdrip display in landscape mode and rotate the phone back to portrait, the display is pinched up so that only half the screen is used. Tried with Nightly and beta versions 
![8E3E2B75-A51B-4C1F-9560-357B17465A6B](https://user-images.githubusercontent.com/36463701/80563761-18647c00-8a40-11ea-8af9-b53fd8a42adf.png)

**Comment by Navid200** [comment]
What do you mean by "downloaded Android 10"?
What phone is xDrip on?
Is the issue still happening?

**Comment by Navid200** [comment]
Duplicate: https://github.com/NightscoutFoundation/xDrip/issues/1269
