### ISSUE TITLE
SW50 Force Collector Problems 

### ISSUE THREAD

**Issue by jokellerweb** [NightscoutFoundation/xDrip#1324]
my setup (xDrip current nightly, Dexcom G6 with xiamoi M2 Lite and SW 50) was very stable, the smartwatch served as a collector. For some time now, after changing the sensor, I have had problems using the smartwatch as a collector.

xDrip and SW50 both function as data collectors without any problems. xDrip will then transmit the data to AAPS and the SW50 if "Force Collector" is not activated. But in "Force Collector" mode, the SW50 easily receives the values from the G6, but unfortunately does not transmit them to xDrip.

An older, previously safe nightly did not solve the problem.

i guess the problem is caused by the latest wear os update on april. 
![$R9IX0V7](https://user-images.githubusercontent.com/31852218/80609098-04b51780-8a38-11ea-8c96-593ef4f5d364.png)
![$RLWCDT6](https://user-images.githubusercontent.com/31852218/80609100-054dae00-8a38-11ea-9520-3866226e9b99.png)

**Comment by jokellerweb** [comment]
![Screenshot_20200429-164019](https://user-images.githubusercontent.com/31852218/80609357-447bff00-8a38-11ea-8499-3e0378eb0fe0.png)

**Comment by Unrealsweb** [comment]
reset wear DB then the smartphone should receive data again, possibly reset the Wear DB again

**Comment by Unrealsweb** [comment]
reset wear DB then the smartphone should receive data again, possibly reset the Wear DB again.
then restart watch and smartphone

**Comment by nicoleloop** [comment]
I am dealing with the same issues, but I am using a G5 sensor. The watch will get readings, and will incorporate calibrations...but will not transfer that data to my phone (Samsung s10+) which then if course doesn't send anything to AndroidAPS. Started a new sensor 8 hours ago. Null token every time. Turned off the smart watch's capability altogether... And the phone refuses to use any calibration I give it. Reset all calibrations...no dice. Stopped and restarted sensor...nothing. I'm losing my mind. I checked the box for calibration with inadequate data...still NOTHING.

**Comment by jokellerweb** [comment]
> reset wear DB then the smartphone should receive data again, possibly reset the Wear DB again.
> then restart watch and smartphone

 wear DB reset was not successful for me! 

A little cumbersome Solution: . Disconnet the watch completely and reset. Reconnect. Then it works again until the next sensor change.

**Comment by Navid200** [comment]
@jokellerweb Would you please close this issue if it has been resolved?
If no, would you please update?
Thanks
