### ISSUE TITLE
If I reset calibrations xdrip+ nerver connect again to xbridge2

### ISSUE THREAD

**Issue by JimZam** [NightscoutFoundation/xDrip#1327]
Good evening. I posted my question in the old xdrip github page...

Good evening. In the last stable release, 20191027-6d4d283, (and some nightly builds before it), if I insert a new sensor or reset calibrations and introduce new blood tests xdrip+ never connects to my G4 via xbridge2. If I reinstall the previous stable release, 20190518-14a03a7, it works fine, I'm able to reset calibrations and start again.
Thank you for your help

original post (there is someone else with the same problem)

https://github.com/StephenBlackWasAlreadyTaken/xDrip/issues/276

**Comment by Laura-Tanase** [comment]
I'm having the exact same problem, only with miao-miao and freestyle libre 1. Reinstalling 20190518-14a03a7 started showing up the BG's.

**Comment by Navid200** [comment]
Have you also asked in the support channels?
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

**Comment by Navid200** [comment]
If you like to reopen, please communicate what you found out the others were doing.
