### ISSUE TITLE
AAPS Extra statusline is broken

### ISSUE THREAD

**Issue by FreDiabetics** [NightscoutFoundation/xDrip#1331]
Every time xDrip receives that my loop is paused 
of currently waiting. It cuts the statusline in xDrip. 

The last chars are missing if 'loop deactivated' is shown.

Is there anybody else with this issue? 

-  **Loop deactivated: the last 7 characters are missing _-(spaces included)_**
![Screenshot_20200506-003253_xDrip+](https://user-images.githubusercontent.com/45721291/81122922-3d6e5880-8f32-11ea-9f34-ed812ba116e6.jpg)

-  **Loop activated**
![Screenshot_20200506-003915_xDrip+](https://user-images.githubusercontent.com/45721291/81122966-54ad4600-8f32-11ea-95e0-fd39460743c1.jpg)

**Comment by wagnefrede** [comment]
Nobody wanna help?!?!

**Comment by Navid200** [comment]
@FreDiabetics Would you please ask using the support channels to see if anyone else is experiencing the same behavior?
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks

**Comment by Navid200** [comment]
@tolot27 Is this a layout issue?

**Comment by tolot27** [comment]
> @tolot27 Is this a layout issue?

Yes, it is.

**Comment by Navid200** [comment]
@FreDiabetics What is the complete word if it did not have 7 characters missing?

**Comment by olorinmaia** [comment]
I have found a solution and making a PR to xDrip. Tested OK with latest AAPS with localization that has most letters.
Need to increase allowed text length from 40 to 70 to be sure. 
Example of the longest statusline from AAPS I could produce which is 64 letters, 70 should be fine.
Uzavretý okruh deaktivovaný
0,40 u/h 0,42U(0,43|-0,00) -0,14 29g

**Comment by Navid200** [comment]
This should be fixed as of the February 20, 2024 release.  If not, please let me know.

Thanks @olorinmaia for fixing it.
