### ISSUE TITLE
Connectivity issues and top banner not rendering in xdrip

### ISSUE THREAD

**Issue by sadafarahman** [NightscoutFoundation/xDrip#1333]
Hello,

The top banner where bg values are displayed is not being rendered. I am having connectivity issues. 'couldn't pair with miaomiao' despite resetting mm several times.

I thought reinstalling the app would sort it but still the same and now the app display is broken too. Have reinstalled several times now but no luck. Currently runni g the latest version, nightly build 05052020.

![15888211737438691575623970057864](https://user-images.githubusercontent.com/45926936/81250520-16d71d00-9019-11ea-8cd9-18bd069d9bd3.jpg)

**Comment by Navid200** [comment]
Take a snapshot, instead of posting as picture, using the phone itself and post please.

**Comment by Navid200** [comment]
If this is a serious issue and you need help, please respond.  We can always re-open.  
I'm sorry if I'm wrong.  But, it looks like you are playing a joke.  Diabetes is a serious disease.  It's no joke.
If I am wrong and you are serious, please respond.

**Comment by sadafarahman** [comment]
Hello,

Its ok to close if there is no fix. Yes I had this issue for weeks and months but managed to resolve it by going back a few versions of xdrip to install on my device, since I had no replies to this issue. And i have managed to maintain connectivity by not upgrading to latest versions.

Unsure if I’ll have the same if I did upgrade though.

Thanks

**Comment by Navid200** [comment]
There is no way to fix something we cannot experience or ask questions about.
Are you willing to recreate the problem, by updating to the release that caused this and then post a snapshot created from the phone itself instead of taking a picture of the phone?

**Comment by sadafarahman** [comment]
I will try and see if I am able to. This is for a Type1 child’s phone so I try and maintain status quo where possible to ensure continuity of service.

I will check the versions and see if I can re-create the bug/issue and let you know.

Thanks for responding.

Regards

**Comment by tolot27** [comment]
@sadafarahman Please post details about phone and android version. Please also try the latest nightly. Is 05052020 the latest working version?

**Comment by Navid200** [comment]
Please reopen the issue when you have the details.
