### ISSUE TITLE
Quick Question About Building xDrip

### ISSUE THREAD

**Issue by Roxy-3D** [NightscoutFoundation/xDrip#1336]
I'm having a little difficulty getting my changes (improvements!!!) to the watch face to show up.

Should I be building APK's,  or building Bundles?   (The reason I'm not sure is I never installed the watch face APK but the main xDrip app on the phone still was able to activate and add the xDrip watch face.)

Can somebody give me a hint how I get the new, updated code to the watch?  It seems I can't even uninstall applications on the watch.

Any suggestions will be much appreciated!!!

**Comment by tzachi-dar** [comment]
Start by connecting your watch to adb. See:
https://developer.android.com/training/wearables/apps/debugging

If you are using android studio, there are two apks that you can build.
After that you can install the watch apk to the watch.

**Comment by Roxy-3D** [comment]
THANK YOU!!!!

**Comment by tolot27** [comment]
Looks answered. Hence, closing it.
