### ISSUE TITLE
Show Tidepool and G6 data in xdrip

### ISSUE THREAD

**Issue by sneps85** [NightscoutFoundation/xDrip#1338]
Hi, it would be nice for me to show data from Dex Share follower and Tidepool data at the same time in Xdrip+. So i can have all my data in xdrip+, the cgm data in real time and the pump data on every usb upload on tidepool. Could you integrate that? Or does that already work somehow? I have a Tandem t:slim X2 with Deycom G6 and would like to have all the data visualized in xdrip+ with real time cgm data.

**Comment by Navid200** [comment]
Would you please use the support channels?
There are many individuals using the same combination you can reach there.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

**Comment by tolot27** [comment]
Currently, Tidepool is only available as upload target and not as follower service. I even don't know if Tidepool has a download API.

**Comment by Navid200** [comment]
So, the objective is to see what the pump shows also on xDrip.  The user still has to carry the pump because how else can they use it if they don't carry it.
Is this right?  The purpose of this feature is to replicate the data that the user already can see on the pump attached to them on the phone as well, right?

**Comment by tolot27** [comment]
> The purpose of this feature is to replicate the data that the user already can see on the pump attached to them on the phone as well, right?

Yes, that's right. Many users wear the pump under their clothes and hence cannot see the data on the pump, at least not always.

**Comment by Navid200** [comment]
>  I have a Tandem t:slim X2 with Deycom G6 and would like to have all the data visualized in xdrip+ with real time cgm data.

This seems to be the same as an existing request:
https://github.com/NightscoutFoundation/xDrip/issues/904
