### ISSUE TITLE
Ambiguous Carb Unit

### ISSUE THREAD

**Issue by vguttmann** [NightscoutFoundation/xDrip#1339]
I have the problem that I usually calculate my Insulin based on KEs (german meaning: Kohlenhydrat-Einheiten, english translation: Carbohydrate units), which equal 10g of carbohydrates. So then I multiply by my factor (for instance 1.25), and I directly get the amount of Insulin I need to inject. However, xDrip+ is very unambiguous when it comes to those units.

**Comment by tolot27** [comment]
So what is your exact problem? Unambiguous is fine for my. Ambiguity would be really bad. I'm also german and have no problems entering cabohydrates in xDip.

**Comment by vguttmann** [comment]
Oh, yes, typo. I meant that xDrip+ is a bit ambigous about that, and doesn't give Units. It just says "12 Carbohydrates". And that is what is a bit confusing. Maybe could someone fis that? I mean, it shouldn't be that difficult, just add a bit of text there.

**Comment by tolot27** [comment]
Please can you attach a screenshot displaying "x Carbohydrates". I try to figure out the corresponding language string. Feel free to suggest a new translation at [crowdin](https://crowdin.com/translate/xdrip/7/en-de?filter=basic&value=0).

**Comment by vguttmann** [comment]
I am on mobile data rn, so I can't upload a screenshot, but I can describe where it is (it's also ambiguous in the english version). It is the wizard on the main screen on the app that lets you enter insulin treatments, carbs and blood sugar level on a meter, and the time when that is. It has a little syringe as its icon. In english, it just says "carbs".

**Comment by AdrianLxM** [comment]
So it should basically give the unit "g" or "grams"?

**Comment by vguttmann** [comment]
Yeah, basically, or it should be mentioned in the walkthrough. Now I do rarely use this feature as I have to eyeball basically every meal, but for a beginner, it's a bit confusing. Not that big of a deal, but those are thee little tidbits that make it nicer.

**Comment by Navid200** [comment]
@vguttmann Please provide a screenshot.  It's really not fair to ask for a change to the code without even showing the existing problem.
I hate to go ahead and change something and eventually find out that was not what you were complaining about.

**Comment by tolot27** [comment]
Here is a screenshot. It should be 10 g carbs. Simply the unit is missing. 
![Screenshot_20210621-062955_xDrip+.jpg](https://user-images.githubusercontent.com/1370732/122707354-27b51300-d25a-11eb-8cd9-c76dd05e92fd.jpg)

**Comment by vguttmann** [comment]
Yep, that's exactly what I meant. Thanks!
