### ISSUE TITLE
[Feature Request] Different carb factors for different times

### ISSUE THREAD

**Issue by vguttmann** [NightscoutFoundation/xDrip#1340]
As every diabetic among you knows, the body reacts differently to insulin on different times daily, meaning that one unit of insulin for instance compensates for 7.5 grams of carbs in the morning and for 12.5 grams in the evening. It would be nice if that could be reflected in the calculations (even if I have to enter the factors for every time of the day manually, and the interpolation is only using linear interpolation).

**Comment by Stuggesjoerd** [comment]
This is already there. You can split the blocks so different carb factors can be used.

**Comment by vguttmann** [comment]
Where can I find it then?

**Comment by mk886714** [comment]
U can Split the block. Touch 3 sec.on time and the block splits

**Comment by vguttmann** [comment]
Where can I find it then? I've looked for it, but I can't find it.

**Comment by mk886714** [comment]
Touch/hold  time above block and after 3-5 sec. block splits and u can change time for your First block

**Comment by mk886714** [comment]
Sorry send me an email and i send a mp4 so u can see, my email mk886614@googlemail.com

**Comment by tolot27** [comment]
I'm closing this issue, as it is already implemented.
