### ISSUE TITLE
Miband 4 - Feature Request: European Formatted Date

### ISSUE THREAD

**Issue by Otto75so3e** [NightscoutFoundation/xDrip#1344]
@bigdigital could you add an option to show the date also in the european format.
5/19 (US)  vs. 19.5 (EU)

It can easily be mixed up if you used to the other way and the date is e.g 05/04.

**Comment by icaruswastaken** [comment]
I tried to have this in my own watchface. Sadly it is only possible by adding the dots to the background image, resulting in a bigger filesize. 

You can try mine if you like (dislaimer: use at your own risk).
Unzip the archive. save the files in your phones xdrip-folder.
In xDrip in MiBand Setting activate "use custom watchface" and set "image offset" to 160.

![watchface](https://user-images.githubusercontent.com/64895201/82669166-3d14d380-9c3b-11ea-95c5-381922a33c0c.gif)
[watchface.zip](https://github.com/NightscoutFoundation/xDrip/files/4668078/watchface.zip)

**Comment by bigdigital** [comment]
Yes, this is for what i've added the possibility to upload custom watchfaces. The same for https://github.com/NightscoutFoundation/xDrip/issues/1343 
It is possible to create own design and use it.
My main goal while designing custom watchfaces for xdrip was to reach the smallest possible file size to reduce uploading time.
@icaruswastaken to display dot near the date, you can use a divider from the time field with a dot image resource.  In such case there no need to add a dot to the bg and this significantly reduces watchface file size. 
Your design looks cool :)

**Comment by icaruswastaken** [comment]
Yeah! Didnt think of just using some unused graphic element. Thanks!

**Comment by Otto75so3e** [comment]
Hello you two,
Awesome, I think I can figure it out with the date thing. I just tried my modification with the Bluetooth indicator from #1343 (by the way: what is your thought about the automatic alarm for a lost connecton on the mi band?)

So basically to have the option to switch between the date format in the app we would need two more bin files:
- xdrip_miband4_main.bin
- xdrip_miband4_main_no_graph.bin
- xdrip_miband4_main_eu.bin (new)
- xdrip_miband4_main_no_graph_eu.bin (new)

Would you be willing to add this switch in the option menu into your next version? I would think a lot of users are more familiar with the European date. Not all are willing to try custom watchfaces.

**Comment by Otto75so3e** [comment]
Now part of the new Miband integration beta [ver 0.3 (25.08.2020)](https://bigdigital.home.blog/2020/08/25/new-xdrip-now-supports-miband-5/).
A huge thanks to @bigdigital
