### ISSUE TITLE
Cannot disable preemptive restart

### ISSUE THREAD

**Issue by detellis** [NightscoutFoundation/xDrip#1348]
Hi, I've seen the issues with 8H transmitters and restarts. But I can't seem to stop it from attempting to restart in day 9.

Xdrip has stopped on day 9 for the first two sensors I've used with this 8H. Using a Note 10 on latest firmware and updated to the most recent nightly.

Preemptive restart option checkbox is hidden, but maybe the option is still enabled under the hood from my previous older revision transmitter that supported preemptive. Restart Sensor is disabled.

**Comment by detellis** [comment]
Have exported Xdrip settings, I shall manually change the following to false as it is currently true:

ob1_g5_preemptive_restart

For reference, the preemptive values I could find were:

name="ob1_g5_preemptive_restart_extended_time_travel" value="false"
name="ob1_g5_preemptive_restart" value="true" 
name="ob1_g5_preemptive_restart_alert" value="true"
name="ob1_g5_defer_preemptive_restart_all_firmwares" value="false"

**Comment by jotomo** [comment]
> Preemptive restart option checkbox is hidden

It's a submenu you need to enter, there you can disable preemptive restarts :-)

**Comment by detellis** [comment]
Thanks for replying. That option is hidden for me, I believe because the transmitter serial begins 8H and is too new. 

I believe I've manually changed it by editing the settings XML. I suppose I could also have just entered a made up 80 serial number to get the option back in the UI to allow me to disable it in the regular way... 

Waiting a few more days to make sure it doesn't try to preemptively restart this sensor and then will close the issue. 

![Screenshot_20200527-001732_xDrip+](https://user-images.githubusercontent.com/22834927/82959403-85bbec00-9faf-11ea-8730-f9601b6ec1be.jpg)

**Comment by detellis** [comment]
Just to confirm that preemptive restarts are now disabled.  The sensor stopped on the 10th day as normal.
