### ISSUE TITLE
Broadcast Locally

### ISSUE THREAD

**Issue by CJiwan** [NightscoutFoundation/xDrip#1349]
Hi,

  I try to receive the Broacast "message" from xDrip.  I have activate the Broadcast locally.

  But on my app I do not receive any broadcast.  When I try my app with a System Broadcast that works.

  Can you help me to find any reason for that?  How can I check that xDrip send the Broadcast correctely?

Thanks
Christian

**Comment by MasterPlexus** [comment]
Did you try to specify your app as a named receiver in the interapp settings of xdrip?

**Comment by CJiwan** [comment]
Hi MasterPlexus.
Thanks four your feedback.  I find my problem.
To receive the broadcast from xDrip, I have add a filter but only with the name of the xDrip package.
In the source code I find the correcte name to configure correctely my intent filter.
Now that works fine :-)
Thanks
Christian

**Comment by MasterPlexus** [comment]
@CJiwan , fine. So you can close the issue ;)

**Comment by CJiwan** [comment]
Yes I close this issue :-)
