### ISSUE TITLE
About alerts

### ISSUE THREAD

**Issue by Air69** [NightscoutFoundation/xDrip#1351]
Can the rising（Falling） threshold be set to be adjustable?  Fixed 0.1mmol / l and 0.16mmol / l, too few options.
Or add 0.2, 0.25, 0.3, etc.  Thank you for your development, this project has benefited me a lot.@bigdigital

**Comment by bigdigital** [comment]
The alert thresholds can be adjusted directly in the xdrip settings. Just go to Settings-> Alarm and alerts -> Glucose level alert list and configure thresholds for low and high alerts.

**Comment by Air69** [comment]
> 警报阈值可以直接在xdrip设置中进行调整。只需转到“设置”->“警报和警报”->“葡萄糖水平警报”列表，然后为低警报和高警报配置阈值。

Hello there.  I may not be able to express clearly. What I am saying is that in other alarms, the rate of rise of blood glucose and the rate of decrease of blood glucose.

**Comment by Navid200** [comment]
Duplicate:  https://github.com/NightscoutFoundation/xDrip/issues/907#issuecomment-778728153

**Comment by Navid200** [comment]
A lower threshold, of 1, has been added. You can test it by updating to the latest Nightly build.
https://github.com/NightscoutFoundation/xDrip/releases/tag/2021.04.06

Please report here:(https://github.com/NightscoutFoundation/xDrip/issues/907) if you discover any unexpected behavior.
Thanks
