### ISSUE TITLE
Authentication Issue G6 Pixel 4 Android 10

### ISSUE THREAD

**Issue by cjkoral** [NightscoutFoundation/xDrip#1353]
I am trying to connect to xDrip+ for the first time.  

I started my transmitter and sensor using the Dexcom app this past week. 

I am using the latest nightly build

I am receiving the following error.

Any thoughts?
![xdriperror](https://user-images.githubusercontent.com/12025464/83197879-75b12300-a0fb-11ea-9faa-e09cead3a655.png)

@jamorham any thoughts?

**Comment by jamorham** [comment]
Which xDrip+ version are you using? Please try the latest nightly.

**Comment by cjkoral** [comment]
Closing issue. I kept uninstalling and reinstalling the nightly and at some point it worked. No idea how i got it over the line other than that.
