### ISSUE TITLE
transmitter reset

### ISSUE THREAD

**Issue by vchapichadze** [NightscoutFoundation/xDrip#1358]
I have tried resetting the transmitter several times and it seems to not work. Is it possible for the transmitter to work with xdrip+ even if it is past the 90 days limit, and the battery has been replaced or is it necessary to reset the transmitter.

**Comment by Navid200** [comment]
Depends on what transmitter you are talking about.  G5 or G6.
If G6, depends on the serial number.

**Comment by Navid200** [comment]
You can use any G5 in non-native mode.  You can use a G5 in non-native mode as long as it has battery regardless of the number of days.     

The last day you can start a sensor in native mode on a G5 is day 105.  
You can hard reset any G5 to day 0.


You can only use a G6 in non-native mode if the first two characters of the serial number are 80 or 81.
If you use a G6 in non-native mode, you can use it as long as it has battery regardless of the number of days.  In non-native mode, there will be no factory calibration.

The last day you can start a sensor in native mode on G6 is day 99.
You can only hard reset a G6 if the firmware version is 1.6.5.25 or earlier.
