### ISSUE TITLE
Code to communicate with Accucheck Guide 

### ISSUE THREAD

**Issue by Chakib-Temal** [NightscoutFoundation/xDrip#1361]
Hi 

first of all thank you for this work, thanks to you I have already managed to integrate the NeoTouch Flex and Reflect

I would also like to code a communication with my Accucheck guide, except that I don't understand too much

I can't find the BLE part that takes care of it

For flex and reflect I used `BluetoothGlucoseMeter` class 

```
if (mLastManufacturer.startsWith("LifeScan")) {
await_acks = true;
Bluetooth_CMD.empty_queue(); // Verio Flex isn't standards compliant
Bluetooth_CMD.notify(VERIO_F7A1_SERVICE, VERIO_F7A3_NOTIFICATION, "verio general notification");
Bluetooth_CMD.enable_notification_value(VERIO_F7A1_SERVICE, VERIO_F7A3_NOTIFICATION, "verio general notify value");
Bluetooth_CMD.write(VERIO_F7A1_SERVICE, VERIO_F7A2_WRITE, VerioHelper.getTimeCMD(), "verio ask time");
Bluetooth_CMD.write(VERIO_F7A1_SERVICE, VERIO_F7A2_WRITE, VerioHelper.getTcounterCMD(), "verio T data query"); // don't change order with R
Bluetooth_CMD.write(VERIO_F7A1_SERVICE, VERIO_F7A2_WRITE, VerioHelper.getRcounterCMD(), "verio R data query"); // don't change order with T
}
```

can you tell me the code that communicate with the Accucheck Guide please ?
is it With bluetooth or usb ? 

Thank's in advance

**Comment by srinivaskolla** [comment]
Hi, I have "AccuCheck Guide Me".  which is Bluetooth. I am able to connect it fine with this app. But not able to read the data from it. Other people are saying they can read it fine. I am investigating it.  You can use the same class BluetoothGlucoseMeter 
Thank you.

**Comment by srinivaskolla** [comment]
Finally make it work. Now it connects to "AccuCheck Guide Me". Let me know if you need some help.

**Comment by Chakib-Temal** [comment]
> Finally make it work. Now it connects to "AccuCheck Guide Me". Let me know if you need some help.

with the same code of BluetoothGlucoseMeter ?

i did not reallly understand , i can compile the application , but it's indicate that it's an app for a watch?? it indicate same for you ? 
because if I can run it on a smartphone, I can use the debugger to be able to block the execution and follow the code step by step


my solution for now :
so, i try to understand the code manually , for exemple for the TouchNeo , i have created a simple code to communicate with him by reading the code without running it on a device
https://github.com/Chakib-Temal/Android_BLE_Usb_Sensors/tree/master/app/src/main/java/com/example/bluetoothtest/Models/bleCallBacks/OneTouch

so did you know what part on code of `public void onCharacteristicRead` of `BluetoothGlucoseMeter ` class is used to communicate with the Accu chek Guide 

thank's

**Comment by srinivaskolla** [comment]
There are two modules. app/wear. You just install "app" when select in Android Studio

Basically BlueoothGlucoseMeter is the class which communicates to the "guide me". 

**- if (queue.isEmpty()) {**
This is where we add all the characteristics we are interested.  . So you can change the list here. I am interested in only "Accu Check Guide Me".  Problem is Accucheck don't have GLUCOSE CONTEXT characteristic.  So we need to delete that., like they did for "Diamond Mobile Mini".

 _If I don't delete this characteristic, I am not getting any data., as the program stuck is queue ( I think, I may be wrong)_

Main command which get the data from the device is .

_**Bluetooth_CMD.write(GLUCOSE_SERVICE, RECORDS_CHARACTERISTIC, RecordsCmdTx.getAllRecords(), "request all readings");**_

Hope this helps, let me know if you need more info.

**Comment by Chakib-Temal** [comment]
> There are two modules. app/wear. You just install "app" when select in Android Studio
> 
> Basically BlueoothGlucoseMeter is the class which communicates to the "guide me".
> 
> **- if (queue.isEmpty()) {**
> This is where we add all the characteristics we are interested. . So you can change the list here. I am interested in only "Accu Check Guide Me". Problem is Accucheck don't have GLUCOSE CONTEXT characteristic. So we need to delete that., like they did for "Diamond Mobile Mini".
> 
> _If I don't delete this characteristic, I am not getting any data., as the program stuck is queue ( I think, I may be wrong)_
> 
> Main command which get the data from the device is .
> 
> _**Bluetooth_CMD.write(GLUCOSE_SERVICE, RECORDS_CHARACTERISTIC, RecordsCmdTx.getAllRecords(), "request all readings");**_
> 
> Hope this helps, let me know if you need more info.

Thank's a lot Man , you saved my week 

i just run the App module on my Phone and i used the debug 

now i can communicate with the sensor , and get all my data 

i created a simple code Java to do it : 
[With FastBle](https://github.com/Chakib-Temal/Android_BLE_Usb_Sensors/tree/master/app/src/main/java/com/example/bluetoothtest/Models/bleCallBacks/Accu_chek_Guide)

thank's again

**Comment by Chakib-Temal** [comment]
Hi again 

the sensor sends the data without indication of the number of data inside it
is there any indication of the size data it gives ? (Number of data to wait )

**Comment by Chakib-Temal** [comment]
here is some standard BLE commands 

 * [1,1] Read all records
 * [4,1] Number of records
 * [1,6] Read last record received
 * [1,5] Read first record
 * [1,3,1,45,0] Read extract from record 45 onwards
