### ISSUE TITLE
Dexcom G6 Checking Auth Errors

### ISSUE THREAD

**Issue by zackallan** [NightscoutFoundation/xDrip#1365]
With the latest nightly build I have the following error messages in the log when trying to receive readings from the G6 transmitter.

Ob1G5StateMachine
Could not read after AuthRequestTX:
com.polidea.rxandroidble2.exceptions.BleGattCannotStartException:
GATT exception from MAC address …, with type
BleGattOperation{description='CHARACTERISTIC_READ'}

authentication notification  throwable: (CHECK_AUTH)
com.polidea.rxandroidble2.exceptions.BleDisconnectedException:
Disconnected from MAC='XX:XX:XX:XX:XX:XX' with status 19
(GATT_CONN_TERMINATE_PEER_USER)

When the phone connects to the transmitter the system status page shows several error messages: Power connect Errors, Examining Errors, Checking Auth Errors and Scanning Errors Errors. They accumulate every 5 minutes.
Due to the issue it is not possible to receive any readings from the transmitter.

Phone reboot, forgetting transmitter device and reinstalling xdrip+ did not help. The problem even persists when trying to connect with xdrip+ from another Android phone.

The Dexcom receiver does receive readings. BlueJay watch receives readings when using receiver slot and fails when using phone slot.

The issue occurred on transmitter day 4. On the first three days xdrip+ received readings without any problems.

The error log messages seem to be similar to issue #732 . As I was not able to reopen the issue and updating to the latest xdrip+ version did not solve the problem I opened a new issue.

Dexcom G6, 8Kxxxx Transmitter
Transmitter firmware: 2.18.2.98
Phone model: Nexus 6P
OS phone: Android 8.1.0
xdrip+: 9cfe91f-2020.06.11

**Comment by obodeldog** [comment]
Same here. Is there an solution?

**Comment by zackallan** [comment]
Unfortunately I had to replace the transmitter. I assume that the transmitter was in a faulty status as the Dexcom G6 app did not work either.

**Comment by fclingen** [comment]
I am currently seeing this problem.   Transmitter 8LQM1P on firmware 2.18.2.98.  The transmitter is only 84 days old,  and my next transmitter is stuck in medical insurance limbo so if anyone has s suggestion other than "replace the transmitter" i would greatly appreciate it

**Comment by tolot27** [comment]
Closing in favor of #1279

**Comment by zackallan** [comment]
In fact, I think that #1279 is a different issue. The error messages are not identical and when running into this issue the phone stops receiving any readings.
However you can keep this issue closed because I think that xDrip is not the cause of the problem as the official Dexcom app could not handle the transmitter either.
