### ISSUE TITLE
Ascending Alarm does not work !

### ISSUE THREAD

**Issue by xheliplus** [NightscoutFoundation/xDrip#1370]
Hi folks !
"High" and "Medium" alerts are too loud and shocking during night. Preparing a sound file that starts with lower sound level is ok as short workaround but no solution.
"Ascending Alarm" would be perfect,  but the selected sound file never starts playing. Phone only vibrates a short time.
Override phone Silent Mode is on
Force Speaker is on
Vibrate on alert is on
disable alert is off
Sound file was selected from System Sound/Alarm option. It is shown as alert Tone but it does not play if I press the Test button.
If I choose  "CHOOSE FILE" once more and go to "System Sound/Alarm",  I can see, that "Silent" is selected instead of my own former choosen sound file.
I'm on Update Channel (alpha) - latest nightly

This really should be fixed because not working alarms are dangerous!
xdrip+  ist really great !  Many features !  But bug fixing is important also.
Thank you very much !

**Comment by tzachi-dar** [comment]
Please allow it 5 minutes and it will play.

בתאריך שבת, 20 ביוני 2020, 11:35, מאת xheliplus ‏<notifications@github.com>:

**Comment by xheliplus** [comment]
Thank you for your answer!
I've been waiting for more than 30 minutes.
Unfortunately, the sound file doesn't play.
Does it really work for you, if you use the "TEST ALERT" button?

**Comment by xheliplus** [comment]
Update:
You are right. The ascending alarm works well. Only the "TEST ALERT" button fails.
So I will close this issue.
