### ISSUE TITLE
G6 Sensor Stopped after Missed Readings

### ISSUE THREAD

**Issue by adanvdo** [NightscoutFoundation/xDrip#1377]
today my sons 2.5 day old sensor stopped randomly. after checking the logs to see if he might have asked accidentally stopped it, I couldn't see anything other than the daily intent being scheduled and missed readings. The Stop Sensor menu option was still available and I had to switch to a new sensor. 

![Screenshot_20200703-194052](https://user-images.githubusercontent.com/26498008/86501639-b807f880-bd68-11ea-841d-84f126f03b85.png)

**Comment by adanvdo** [comment]
I tinkered with the app a bit after another occurrence of this. This happened to me again today. It happened around the same time as the first, about 2.5 days into the session after Missed Readings.

This time, after seeing the sensor stopped and it's status was all messed up, I reinstalled the app and imported everything. I noticed that the logs said no session data was on the sensor, so I stopped it and started it with the same code. 

I have now restarted my G6 sensor using the 8H firefly transmitter!!  @jamorham 

No idea what happened in the background but maybe there is something here that might help with performing restarts again on these.

**Comment by adanvdo** [comment]
![Screenshot_20200919-194614](https://user-images.githubusercontent.com/26498008/93691548-b838aa00-fab4-11ea-9165-8b50c3d001cb.png)
![Screenshot_20200919-194421](https://user-images.githubusercontent.com/26498008/93691552-ba9b0400-fab4-11ea-9641-9c3e50d4063f.png)
![Screenshot_20200919-194413-1](https://user-images.githubusercontent.com/26498008/93691554-bd95f480-fab4-11ea-8854-fe174237cda3.png)
![Screenshot_20200919-194245](https://user-images.githubusercontent.com/26498008/93691557-c090e500-fab4-11ea-92a9-158a50d8d331.png)
![Screenshot_20200919-193747](https://user-images.githubusercontent.com/26498008/93691558-c2f33f00-fab4-11ea-9d94-defec1f282ba.png)
![Screenshot_20200919-194413](https://user-images.githubusercontent.com/26498008/93691560-c686c600-fab4-11ea-98e4-b3b37f958a4c.png)

**Comment by Navid200** [comment]
@adanvdo Is this problem ongoing?

If yes, can you show all your xDrip settings?

Settings -> G5/G6 Debug Settings
Settings -> Less common settings -> Bluetooth Settings
Settings -> Less common settings -> Other misc options

If not, would you please close this issue?

**Comment by adanvdo** [comment]
> @adanvdo Is this problem ongoing?
> 
> If yes, can you show all your xDrip settings?
> 
> Settings -> G5/G6 Debug Settings
> Settings -> Less common settings -> Bluetooth Settings
> Settings -> Less common settings -> Other misc options
> 
> If not, would you please close this issue?

This has not happened again since September. I am still using the same device and settings I was. No idea what caused this or other issues I used to get.

Closing
