### ISSUE TITLE
Feature request: Support for LiteOS (HUAWEI Watch GT 2e or Honor MagicWatch 2)

### ISSUE THREAD

**Issue by twinko** [NightscoutFoundation/xDrip#1378]
Hello everyone,

thank you so much for all your effort in this projekt. Im really looking forward to buying a smartwatch. But WearOS is too battery hungry for me and i dont like to have a watch, thats lasting for 2 days max. Watches from Huawei and Honor have lightOS installed and last for about 1-2weeks. I would love to see my bloodsugar on one of these watches.

Sadly im not a dev, but i would provide logs and whatever you guys need.
A support for these watches would be awesome!

LiteOS is oprn Source: https://www.huawei.com/minisite/liteos/en/index.html
And there is already a community for watchfaces: https://forum.xda-developers.com/smartwatch/huawei-watch/page2

**Comment by twinko** [comment]
Sorry for pushing this issue but is it possible to raise some money for this feature? Moreover i didnt found a way to send some "coffee money" for all the great work that's be done to have this amazing xdrip app as it is right now.

**Comment by tolot27** [comment]
@twinko We are an open source community. If someone has time or is affected/interessted and a developer, it will take over this issue. They only way to support it is by spending the watch to a the developer. But even than, there is no guarantee that a watchface will be built in a short time.

**Comment by tolot27** [comment]
It is very unlikely that we found time to support this watch, especially we don't have the hardware to test it. Hence, closing this issue.
