### ISSUE TITLE
Remove Google Play Services dependency

### ISSUE THREAD

**Issue by felixsanz** [NightscoutFoundation/xDrip#1379]
It is possible to get this dependency removed? I don't want Google to steal all my data, i don't even know why this is required to run xDrip+.

Why it is needed? Is there any reason?

I don't use Wear OS, and the notification is already persistent so why need Google Messaging Services?

**Comment by jamorham** [comment]
xDrip+ follower mode, when enabled, uses Google Messaging. All payload data is encrypted with symmetric encryption and the key is exchanged out-of-band.

xDrip should run without Google Play Services installed if you want. This has been done successfully before but hasn't been that widely tested. It should pop up initially saying that play services isn't installed but then go quiet after that. 

There is also the option `Disable all sync features` in `xDrip+ sync settings` which should permanently disable this subsystem from being initialized, which might also help if you are getting issues.

**Comment by felixsanz** [comment]
@jamorham  Disabling all sync features only affects followers?

That popup made me think that xDrip+ wasn't going to work if i don't have Google Play Services. I didn't want to start a sensor to try and waste it

**Comment by tolot27** [comment]
It looks like it is working well without Google Play Services as reported in #519.

**Comment by edpomfret** [comment]
Looks like it's stopped the pop ups but both dex share follower and nightscout upload still working fine.

**Comment by Navid200** [comment]
If you have no Sync followers, you don't need the sync feature.
You can also use Nightscout follower scheme with no need to Google.

You can reopen the issue if you like.  But, I don't think we are going to remove the Google dependency right now as one of the available synch mechanisms (xDrip+ Sync Follower) depends on it.  The user doesn't have to use that mechanism.
It may eventually be removed.  But, right now, it is an option, which requires Google.
