### ISSUE TITLE
Contour Next One meter uploads duplicate BG readings

### ISSUE THREAD

**Issue by gregtcm** [NightscoutFoundation/xDrip#138]
First, I want to say I've been using the Contour Next One for the past month and I absolutely love it and the automatic upload to xDrip+ and automatic calibration.  What an amazing feature.

I didn't notice an issue for this yet, but I've been getting duplicate glucose readings in my Calibration Data Table.  Not all the time, and when it happens, it may happen anywhere between 1 and 5 or 6 times.  The entries can be minutes or hours apart.  I've been removing the duplicates manually from the data table with the "disable" functionality.

My setup:  DexcomG5 > SW3 > Samsung S7 (6.0.1) > both Mongo Upload and REST to my OpenAPS rig.
I had been running a nightly from early June, but have since updated to the nightly from 6/20.  I have recently started a new sensor (2 days ago) and have had the issue happen once since then (with only one duplication).

**Comment by diagnoe4** [comment]
I have the same observation with an Accu-Check Aviva Connect. It doesn't seem to be only Contour related but maybe all bluetooth glucose meters?

I have observed a bug with the Accu-Check Aviva Connect sync: sometimes historic glucose levels are suddenly populated on the graph at a wrong time. E.g. I would measure 5.3 at 8 in the morning. That same 5.3 would sometimes suddenly appear at 14:30 again after taking a measurement at say 16:00 but with no measurement happening at 14:30 and other measurements having happened between 8:00 and 14:30. Often these measurements would appear multiple times. This doesn't happen very often but does from time to time and did sometimes mess with the Libre calibration.

**Comment by muthijammy** [comment]
I have more data on issue of duplicate calibration triggering at random time. These seem to be triggerring conditions:

Meter connected to xdrip on mobile
Keep automatic calibration enabled in config
Do BG test and Dont calibrate using it (4:22 pm)
Open xdrip after 30 minutes
Earlier BG value randomly applied as calibration now(4:50 pm)

I had noticed this issue in past but didnt realise last step in trigger. It has been discussed in past in FB and I see below open issues raised without above triggers mentioned and open. 

Workaround seems to be disabling automatic calibration or click on BG in graph and calibrate every BG or delete BG. Can there be quick fix as time-is-money and delayed BG used for calibration is quite dangerous. Should I raise new issue or will get priority based on new comment?

https://github.com/NightscoutFoundation/xDrip/issues/138

https://github.com/NightscoutFoundation/xDrip/issues/790

**Comment by Navid200** [comment]
@gregtcm 
Is this still happening on the latest version of xDrip?
May 21, 2021

**Comment by Navid200** [comment]
This issue is not about double calibration.  It is rather about blood glucose readings being uploaded to xDrip more than once.

We can reopen if anyone is experiencing this issue.  Please post here if you do.
