### ISSUE TITLE
Heroku removing mLab MongoDB add-on.

### ISSUE THREAD

**Issue by master3395** [NightscoutFoundation/xDrip#1380]
Heroku removing mLab MongoDB add-on.
Is there any other "free" options to use?

![image](https://user-images.githubusercontent.com/4199669/87188964-0e88b000-c2f0-11ea-9cf6-ff3e951e9daf.png)

**Comment by dassystem** [comment]
Heroku and nightscout are no issues with xdrip+. You can host it yourself on a raspberry pi, even in a docker container. 

I came across a free and friendly nightscout hoster at https://ns.10be.de/de/index.html. Consider supporting it with a donation.

**Comment by UberQueiroz** [comment]
> Heroku and nightscout are no issues with xdrip+. You can host it yourself on a raspberry pi, even in a docker container. 
> 
> I came across a free and friendly nightscout hoster at https://ns.10be.de/de/index.html. Consider supporting it with a donation.

Thank you very much!

**Comment by yosepito** [comment]
if you follow the email instructions, you will be able to migrate to the new database. follow the link included in the email. Further instructions are available there, with several steps including changing a setting in heroku

**Comment by plmarcelo** [comment]
You also can have more info about it on: https://github.com/nightscout/cgm-remote-monitor/issues/5744

**Comment by Navid200** [comment]
@master3395 Do you still have any questions?
This is really a Nightscout question rather than an xDrip one, no?
Unless you disagree, would you please close this issue?

**Comment by master3395** [comment]
> @master3395 Do you still have any questions?
> This is really a Nightscout question rather than an xDrip one, no?
> Unless you disagree, would you please close this issue?

I went with the service below, works great.

> Heroku and nightscout are no issues with xdrip+. You can host it yourself on a raspberry pi, even in a docker container.
> 
> I came across a free and friendly nightscout hoster at https://ns.10be.de/de/index.html. Consider supporting it with a donation.
