### ISSUE TITLE
Xdrip+ isn't responding

### ISSUE THREAD

**Issue by getut** [NightscoutFoundation/xDrip#1381]
I opened an issue back in May but it didn't come back around. Still getting xdrip+ isn't responding wait or close about every 30 seconds. It is working with my Dexcom G5, its just popping that annoying message up no matter what app I'm in. I was the current version from xdrip nightlies in May and have tracked the nightlies all the way through to the current one as of this issue date, but still no changes.

**Comment by emp-00** [comment]
Can you post a screenshot of the "annoying message"? What does it say? Can you describe your issue in more detail?

**Comment by getut** [comment]
You would ask for a screenshot when I just took out a sensor last night and was going to start a new one today. Xdrip works for but isn't showing anything because of that. But here is the error.. the graph is just empty.[https://ibb.co/H2gPk1s](url)

**Comment by emp-00** [comment]
Sorry, cannot help you without some detail information - problem still completely unclear (to me). Link does not work.

**Comment by getut** [comment]
Copy that link into the browser. It doesn't work for me either clicking it from github page. I think github is modifying the link somehow. If you copy and paste into a browser it works.

**Comment by emp-00** [comment]
Try switching off all "battery optimizations" on your phone: 1) search for "battery" in your Androids settings and also check 2) under Apps/xdrip+

**Comment by tolot27** [comment]
@getut If you still have trouble, please ask for support at https://www.facebook.com/groups/xDripG5 or https://gitter.im/jamorham/xDrip-plus.

If it is solved, please close this issue.

**Comment by Navid200** [comment]
There is a thread on facebook that is related.  Adrian Lxm has made suggestions in that thread.     
https://www.facebook.com/groups/xDripG5/permalink/4713928492013942

**Comment by Navid200** [comment]
@getut Is this still a problem?

**Comment by tolot27** [comment]
@getut You still did not report your [environment}(https://github.com/NightscoutFoundation/xDrip/issues/new?assignees=&labels=&template=bug-report.md).

I'm experienced the same issue with xDrip running on LineageOS 17.1 until reboot.

**Comment by Navid200** [comment]
As you stated in your description, this is a duplicate:
https://github.com/NightscoutFoundation/xDrip/issues/1328
