### ISSUE TITLE
Smartwatch support: Ambient mode, round displays, bigchart linked to complication?

### ISSUE THREAD

**Issue by steve8x8** [NightscoutFoundation/xDrip#1383]
I'm planning to switch from a Sony SW3 (with the BigChart watchface, always-on) to a Fossil Sport gen4.

There are two major obstacles:
- The display is round, and information presented in the "corners" is swallowed (date, age of value).
- In always-on mode, people now can see (because of backlight on) the curve displayed (although dimmed).

I have considered changing to a complication, but there seems to be no way (that avoids pulling out the phone) to access the curve (as discussed in https://github.com/NightscoutFoundation/xDrip/issues/101#issuecomment-405647277 - there seems to be "treatment input" linked to double-tap of the complication, something I can also assign to one of the buttons).

I understand that up to now, none of the xDrip watchfaces has a separate (different style) ambient mode.
What does it take to create a watchface that, in non-ambient mode (i.e. activated), has the same information as the BigChart (perhaps better adapted to round displays), and, in ambient mode, presents the time in a heavily dimmed manner and little more than the current BG value and trend arrow?

(Related issues: #836 #1137)

**Comment by steve8x8** [comment]
Just noticed that a request for a round watchface already exists in #911 ...

**Comment by Navid200** [comment]
https://github.com/NightscoutFoundation/xDrip/issues/911
