### ISSUE TITLE
No wifi or mobile data, no information received via bluetooth

### ISSUE THREAD

**Issue by johnpc87** [NightscoutFoundation/xDrip#1386]
Hello,
I have been using Xdrip+ for a long time and realised that whenever I do not have wifi or mobile data on, Xdrip+ stops receiving data via bluetooth from my Miaomiao2 (and Freestyle Libre sensor). Is there a way to receive glucose info on Xdrip+ when you do not have wifi or mobile data on? 
This is quite common when you are travelling abroad or at night when you would like to keep on receiving your glucose measurements but not necessarily the rest of notification (or calls) from all the other apps in your smartphone.
Thanks a lot!

**Comment by Brunchen** [comment]
sometimes i have the same problem (do not have miaomiao2), you don´t need wifi or mobile data connection.
please try this:
- activate nfc and gps
- open libre 2 app and scan sensor
- change to xdrip+ and wait max. 5 min until the bg values appear again
- deactiviate nfc and gps

i hope this helps.

**Comment by Navid200** [comment]
@johnpc87 Would you please close this issue if it has been resolved?
If not, would you please use the support channels to find out how others may be addressing the same issues?
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks
