### ISSUE TITLE
xDrip no working Huawei P30 and Huawei SmartWatch 2

### ISSUE THREAD

**Issue by Manny669** [NightscoutFoundation/xDrip#1389]
Have Huawei P30 ELE-L29, EMUI TME. ES. Version 10.1.0.123;Android 10. Connected to Huawei SmartWatch 2.
Using Freestyle L 2, With MiaoMiao 2. Selected Hardware : Libre Bluetooth,
 SmartWatch Features : Android Wear Integration : send data wear watchface:on; enable wear collect service ×, Force Wear collect:x
Can't collect any readings from MiaoMiao; Bluetooth apparently conects to MiaoMiao(as indicated in Hw P30) . Appreciate your help.

**Comment by Navid200** [comment]
@Manny669 Would you please close this issue if you have got answers already?
If not, would you please use the support channels?
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Your questions will then be viewed by a significantly larger audience.
Thanks

**Comment by Manny669** [comment]
Hi, Navid. I didn´t get any answers; Could you please close it? I don't
know how to close it!!. Thank you.
