### ISSUE TITLE
Which smartwatch to buy?

### ISSUE THREAD

**Issue by guilhermetb** [NightscoutFoundation/xDrip#1397]
Hello, good night everyone, I need help to set up a setup for my father who is diabetic.

I live in Brazil and here the items are more expensive, I have in mind to buy a Smartwatch, a MiaMiao2, and a Freestyle Libre sensor to use with your Galaxy A30S cell phone.

I'm having trouble defining which smartwatch to buy that works with xDrip, considering https://www.banggood.com/, https://www.gearbest.com/, https://www.aliexpress.com/

I would like a device to be able to monitor/view the update every 5 min on my wrist, spending U$50 or R$250
Xiaomi Mi Band 5
Haylou Solar LS05
TicWatch S2
Amazfit Stratos 2
BW-HL3

Thanks in advance.
Kind regards,

**Comment by Marcio261** [comment]
I bought a mi band 5, but there is no xdrip version to work with it( for now )

**Comment by tolot27** [comment]
Please ask this at Gitter or Facebook: https://github.com/NightscoutFoundation/xDrip/issues/new/choose
