### ISSUE TITLE
Moto Display

### ISSUE THREAD

**Issue by JimZam** [NightscoutFoundation/xDrip#1400]
Good evening. Using the last nightly, 25th of July, I could see BG readings in my Moto G5 Plus - Moto Display for the first time in three years using this phone:
https://motorola-global-portal.custhelp.com/app/answers/indevice_detail/a_id/108313/p/30,6720,9583
I have had to reinstall xDrip and now it doesn't :-( Is there any way to enable it?
Thank you so much
Regards

PD: In the past someone asked about it. I swear it worked...
https://github.com/StephenBlackWasAlreadyTaken/xDrip/issues/135

PD2:
The first time it worked I was using LibreLink patched with a Libre 2 sensor. Now that it doesn't I'm using a Dexcom, don't know if the patched app sending readings to xdrip has something to do with the fact that BG appears in the Moto Display, could be??

**Comment by JimZam** [comment]
Confirmed, with the patched app it works, you can see the BG redings in the Moto Display.

**Comment by Navid200** [comment]
@JimZam Would you please close this issue if it has been addressed?
If not, please use the support channels:
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks
