### ISSUE TITLE
Connect libre2 with xdrip directly

### ISSUE THREAD

**Issue by merberaza** [NightscoutFoundation/xDrip#1402]
My son is going to use Libre2 and I want to connect it with Xdrip. I don't need Nightscout since I only use Xdrip at night with a mobile that is connected by bluetooth. During the day he uses the Libre reader. Could I use Xdrip without installing the patched app? I think that it should be posible since Libre2 has bluetooth. If it is posible, which one is the option to choose in "data source"? Thank you very much.

**Comment by tolot27** [comment]
No, it isn't possible to get data into xDrip+ without the patched app. It might be possible in the future but it will never be possible to use it side-by-side with the Libre reader because either the app or the reader can use Bluetooth to communicate with the sensor. As soon as you start a sensor with the librelink app, you cannot use the reader anymore. Even NFC will not work with reader.

**Comment by JimZam** [comment]
To be able to use the patched app you have to start the sensor with it, and your phone will be the only to receive alarms, it's not possible to use the reader and the phone to receive alarms at the same time. But the reader can read the sensor so your son can use the reader but not receiving alarms. On the other hand your xdrip wouldn't have connection during the day so it will be complaining all the time... Better option is xdrip and patched app in a phone with your son (I don't know the age of your son or if he has a phone) and xdrip in your phone as a follower.

**Comment by tolot27** [comment]
>But the reader can read the sensor so your son can use the reader but not receiving alarms.

Are you sure that this works? I've tried this and my reader complains that the sensor was started using a different device.

**Comment by JimZam** [comment]
Yes, you are right, I thought it worked but I have tried to read the sensor with the reader and I've not been able. I'd never tried before, just read the instructions from Androidaps "The sensor remembers the device it was started from. Only this device can receive alarms in the future."
Ok, I continued reading:
"During the 14 days you can use in parallel one or more NFC capable smartphones (not the reader device!) running the original LibreLink app for scanning via NFC. There is no time limitation to start that. You could use a parallel phone for example on day 5 or so. The parallel phones(s) could upload the blood sugar values into the Abbott Cloud (LibreView). LibreView can generate reports for your diabetes team. There are many parents who absolutely need this."
Sorry for my mistake :-(

**Comment by merberaza** [comment]
Thank you all very much. That is what i thought, that if we use patched app+ xdrip we won't be able to use the reader. Since we want to use it and use xdrip at nights we are going to buy the Bubble.
