### ISSUE TITLE
wearOS 2 complications issue

### ISSUE THREAD

**Issue by 0xBABA** [NightscoutFoundation/xDrip#1404]
I am using the following devices:
Dexcom 5G
Ticwatch E2 with wearOS 2.17 
Oneplus 6 Android 10 and Xdrip version 2020.07.13 set up as a nightscout follower.

The issue I am having is with the wear OS integration. when using the xdrip watchface - everything works properly. However, when I try to use the Xdrip complication on another watchface I get 'null null ()'.

I tried adding a blood calibration after switching to a different watch face as suggested [here](https://github.com/gregorybel/xDrip/blob/gregorybel-update-docu/Documentation/WatchGuide.md), but that did not seem to fix the issue.

Would appreciate any help with this.

**Comment by xannasavin** [comment]
I am using the Ticwatch Pro 2020 with the "Swift" Watchface (1€) and the xDrip complication - no issues so far. Maybe there is some permission error? Is the watchface allowed to read data etc?

**Comment by Navid200** [comment]
@0xBABA Would you please close this issue if it has been resolved?
If not, would you please use the support channels?
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks

**Comment by 0xBABA** [comment]
Hi @Navid200. For me this hasn't been resolved, I just keep using the Xdrip watch face instead of anything else.
I already tried the Facebook group on this issue in the past and received no response there, so if there's no point in this issue remaining open I can close it.

**Comment by rustymonkey** [comment]
Looks like the same issue reported at #303 and #325.

**Comment by JustusJustJustus** [comment]
I got exactly the same issue. I am using

- TicWatch or Asus Zenwatch 3 (current wos versions)
- Xdrip+ ( latest release as well as latest nightlies)
-  Xdrip Source is share follower
(- As a share follower the workaround of calibration does not work)

And yes. It is the same issue mentioned in #303 #325. The setup / sources might be different but the issue null/null is the identical one.

I would be very pleased if this could be fixed cause this hybrid usage of original dexcom app an xdrip has some advantages 

Thanks in advance

**Comment by farcusnz** [comment]
I too am having the same issue as the op. 
The xdrip watch face works fine whether the phone is the collector or the watch is the collector.
If using complications on a different watch face - if the watch is the collector - then the complication works fine.
If the phone is used as the collector then the complication displays null null.
using libre1, miaomiao2 and oop1 (on both phone and watch).
If I try the calibration fix on the phone it sends one reading to the complication display but then will not update after that, eventually returning to the null null display.
![watch](https://user-images.githubusercontent.com/29653298/117557446-10b1cb80-b0c7-11eb-8cea-bcfa8a804e86.jpg)

**Comment by Navid200** [comment]
For anyone experiencing the same problem, please use the existing issues to report:
https://github.com/NightscoutFoundation/xDrip/issues/303
