### ISSUE TITLE
MIUI 11.0.2.0.QCNMIXM completely breaks xdrip

### ISSUE THREAD

**Issue by kaloyansarafov** [NightscoutFoundation/xDrip#1407]
After downloading the newest MIUI version yesterday on my redmi 8, I am unable to connect to my transmitter, I have tried enabling and disabling every single option but have found no way to fix it, it only connects about once an hour if I keep restarting the collector and forgetting the transmitter. I will be downgrading to the previous miui version and highly discourage anyone to update to 11.0.2.0

**Comment by ANDREAPIPPI** [comment]
This looks strange, I use xDrip plus latest ni9ghtly with Xiaomi Redmi Note 7 and smartband Mi Band 4. Just yesterday I installed the MIUI Global 11.0.1, and I had absolutely no problem, even with the smartband.
Before istalling the previous MIUI, I suggest you to try to change some xDrip parameters to see if anything changes. Good luck!
Bye.  Andrea    :-)

**Comment by kaloyansarafov** [comment]
Hey, my issue is with 11.0.2 and not 11.0.1, and I also tried switching on or off pretty much every option and also checked the events log but didn't see anything out of the ordinary there, I am currently running the latest alpha build and had no problems until yesterday just after updating

**Comment by tolot27** [comment]
Is there something in the logs? Does it work now?

**Comment by kaloyansarafov** [comment]
I have started using the patched G6 app now since I couldn't get it to
work, and I do not know if it's still broken.

**Comment by Navid200** [comment]
So, I suggest we close this issue.
We don't have the bandwidth to address all the issues that we can experience and test.  Let alone those that the person who has discovered them is not using xDrip any longer.
We cam always reopen it.
