### ISSUE TITLE
Mi band 5 + xdrip

### ISSUE THREAD

**Issue by Marcio261** [NightscoutFoundation/xDrip#1410]
Is there any updates for xdrip to work with mi band 5

**Comment by Artemdrip** [comment]
https://bigdigital.home.blog/2020/01/23/future-of-the-xdrip-miband-project/

"I’ve begun the code adaptation for new miband 5. For now, can’t say how much time this can take. I’m planning to spend last summer days far away from the computer, so approximately, first beta would be at the end of the October. Regards,
Artem"

**Comment by Armandovi** [comment]
First of all a BIG THANK YOU for your work and your effort. I'm using it with my boy with the MI Band 4 but it was impossible for me to make it work with Android 10 in a Oneplus 6T (XDrip+ reads data from Nightscout but it does not upgrade the screen although it is connected with the Mi Band 4) Did you know about this? Is it a problem of Android 10 or the phone? Will this work with the MiBand 5?

**Comment by Artemdrip** [comment]
> First of all a BIG THANK YOU for your work and your effort. I'm using it with my boy with the MI Band 4 but it was impossible for me to make it work with Android 10 in a Oneplus 6T (XDrip+ reads data from Nightscout but it does not upgrade the screen although it is connected with the Mi Band 4) Did you know about this? Is it a problem of Android 10 or the phone? Will this work with the MiBand 5?

Sorry but I am not the developer of it. :)
I just quoted the developer's (@bigdigital) statement.

**Comment by Armandovi** [comment]
Well, I thought you were. In any case Also a BIG Thank you for giving us all these details

**Comment by Artemdrip** [comment]
New xdrip now supports MiBand 5 https://bigdigital.home.blog/

**Comment by Marcio261** [comment]
OMG!!! This are really excelent news😍 thank you!!

**Comment by Marcio261** [comment]
Im using it right now and untill now works excelent😎

**Comment by Artemdrip** [comment]
> Im using it right now and untill now works excelent😎

can you send a picture of how it looks like?

**Comment by Marcio261** [comment]
![IMG_20200826_141804](https://user-images.githubusercontent.com/59709015/91308405-26849800-e7a7-11ea-937a-c46d847ded61.jpg)

**Comment by Artemdrip** [comment]
it looks nice 👍

**Comment by Marcio261** [comment]
> it looks nice 👍

Very very good✌️ 
Thank you all😊

**Comment by Marcio261** [comment]
Hi there, full day using the xdrip on miband and i'm loving it💪
But i have notice that is some funcionalities left: breathing, stress, PAI and events.
And there is also the cicles( for women).
But untill now, working good.

**Comment by leitungum** [comment]
Hey there, I ve tried it today and the Installation went fine, but my Glucose Level is Not updating. Only from time to time. Do you have an Idea why that could be?

**Comment by bigdigital** [comment]
> Hey there, I ve tried it today and the Installation went fine, but my Glucose Level is Not updating. Only from time to time. Do you have an Idea why that could be?

Check the nightmode settings in miband menu. If you have enabled night mode, you will receive updated data according to the intervals configured in nigtmode intervals. 

>But i have notice that is some funcionalities left: breathing, stress, PAI and events.
And there is also the cicles( for women).

Thanks, will check if it is possible to add those settings. Meanwhile, you can configure these functionalities in mifit settings.

**Comment by leitungum** [comment]
> > Hey there, I ve tried it today and the Installation went fine, but my Glucose Level is Not updating. Only from time to time. Do you have an Idea why that could be?
> 
> Check the nightmode settings in miband menu. If you have enabled night mode, you will receive updated data according to the intervals configured in nigtmode intervals.
> 

Hmm, the nightmode is Off. And Just in Case, I ve set it to "live" (but still not activated)

**Comment by diegoka-85** [comment]
Non riesco ad impostare il quadrante o meglio riesco a metterlo ma la glicemia non cambia, rimane la stessa

**Comment by leitungum** [comment]
After un- und reinstalling everything several times, I still don't know what to do and how to solve the problem:
- no battery saving mods active (Xiaomi Mi9T)
- no "night mode" active
- mi band is authenticated and connected to drip
- mi fit app is deleted (tried with both, installed & uninstalled with same results/issues)
- "bg readings as notifications" is working fine (every 5 minutes)

the xdrip watch face is not updating: sometimes it works for 3 times (3x5min) then it takes 20min, 25min,....it seems to be random...

if I go to xdrip settings and change 10h to 24h, it takes 5 sec to change it in the watch face. but settings like "show weather", "show activity" etc. are not working. Seems like the lower part of the watch face is not updating.

If I deactivate "bg readings as notifications" it is also not going back to the regular watch face ....what it is supposed to be, right?


Please let me know if anyone has an idea what I can try, thanks :)

**Comment by vhredny** [comment]
> After un- und reinstalling everything several times, I still don't know what to do and how to solve the problem:
> 
> * no battery saving mods active (Xiaomi Mi9T)
> * no "night mode" active
> * mi band is authenticated and connected to drip
> * mi fit app is deleted (tried with both, installed & uninstalled with same results/issues)
> * "bg readings as notifications" is working fine (every 5 minutes)
> 
> the xdrip watch face is not updating: sometimes it works for 3 times (3x5min) then it takes 20min, 25min,....it seems to be random...
> 
> if I go to xdrip settings and change 10h to 24h, it takes 5 sec to change it in the watch face. but settings like "show weather", "show activity" etc. are not working. Seems like the lower part of the watch face is not updating.
> 
> If I deactivate "bg readings as notifications" it is also not going back to the regular watch face ....what it is supposed to be, right?
> 
> it seems it is trying to sync but sometimes after the syncing animation, there is this white cross on red and it says it "couldn't sync"
> 
> Please let me know if anyone has an idea what I can try, thanks

I have exactly the same problem. With mi band 5 Watchface is updating randomly. I tried everything what you said wihtout any success.

**Comment by drakk0** [comment]
![Screenshot_2020-09-01-20-07-19-670_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/779666/91904560-6c5cc700-eca5-11ea-92c0-8288db3bc555.jpg)

Phone: Xiaomi Mi9SE
Android: 10
Miui: 12
Miband 5
Xdrip + MiaoMiao2 + libre

I don't have issues with red sign after syncing - i saw it once. But I have issue like in screenshot. Syncing is triggered on xdrip side - but usually it ends with this error. Trying to force this manually works in 1 of 5 tries. 

Tried every Bluetooth settings available. 

I have idea of dumb solution - retrying until it will work ;). One notice - its easier to update couple seconds after xdrip get BG readings from miaomiao.

@bigdigital - did you noticed such behavior before?

**Comment by bigdigital** [comment]
> @bigdigital - did you noticed such behavior before?

Nope, never had such error. Looks like something happen with Bluetooth connection. Please try to enable the option "Disable hight MTU" which is located under experimental section in miband menu settings.  If this does not help, could you please send me a detailed error log? For this please go xdrip Settings->Less common settings-> Extra logging -> Extra tags for loggings and enter here “MibandService:d” (without quotes) . After this go to “Less common settings” -> View recent error interface. Leave enabled only “Low” checkbox . Search “Begin uploading Watchface” message and make a print screens till the error. You can send screenshots to my email bigdigital.kov@gmail.com

**Comment by davidmtml** [comment]
I'm having trouble getting this set up.

I installed the modified Mi Fit app, and succesfully had the auth key saved on the phone.  Then, I uninstall the modified app, and install the official app.  When I do this, it goes through and updates the firmware again.  Does this change the auth code?  When I go into xdrip it always says it can't connect.  I've tried entering the MAC manually, but then it says the auth key is wrong.  I noticed the modified app is 4.2.0, and the new version of the official app is 4.5.6.  Do I need to install version 4.2.0 of the official app??

**Comment by leitungum** [comment]
> I thought I saw that I can use the official xDrip app (which is what I've been doing, and it's the latest nightly from today, Sep 3 2020). Do I need to install the modified Mi xDrip app?

@davidmtml yes, you have to use the modified app

**Comment by davidmtml** [comment]
> > I thought I saw that I can use the official xDrip app (which is what I've been doing, and it's the latest nightly from today, Sep 3 2020). Do I need to install the modified Mi xDrip app?
> 
> @davidmtml yes, you have to use the modified app

Thank you!  I have downloaded the modified app and it is working great!  

I was using a version of xDrip from March that didn't have Mi Band listed under "Smart Watch Features" and when I updated to the latest official it was there.  Then I read something that said you could use the official xDrip app, but either they were wrong or I read it wrong!

**Comment by Klaus3d3** [comment]
The nightmode does not seem to work on my band 5. The screen keeps lighten up on new data.

**Comment by Marcio261** [comment]
> The nightmode does not seem to work on my band 5. The screen keeps lighten up on new data.

I think the nightmode does not suspend the data updates, but you can extend the interval of updates(120minutes maximum between updates, and also reduce the brightness).

**Comment by Klaus3d3** [comment]
Thats what i meant. The screen brightness does not reduce.

**Comment by bigdigital** [comment]
> The nightmode does not seem to work on my band 5. The screen keeps lighten up on new data.

During watch face update the screen brightness would be decreased (but it wouldn't be completely switched off).  Does it work like this for you? if not, could you please send me a debug log like described here ](https://bigdigital.home.blog/2020/08/25/new-xdrip-now-supports-miband-5/#debug) ?

**Comment by Sgathach** [comment]
Thank you so much for the new update corresponding to the Samsung Bluetooth issue!
It works very well so far, one slight issue when I reimported database and forgot data source was still set to dexcom follower. Switching miband transmission off and on again and sending Bg data manually resolved it :D
Is there a way to say thank you with a one-off donation somewhere without patreon?

**Comment by spartakcz** [comment]
Hello, I have a MiBand5 that I connect to xdrip_miband_0.3.2.6.  I see the xDrip dial, but no graph - only NO DATA.  I'm using OnePlus 8 with the latest version of OxygenOS (Android11).  Does anyone have a similar experience?

**Comment by stackenblochen** [comment]
> > I thought I saw that I can use the official xDrip app (which is what I've been doing, and it's the latest nightly from today, Sep 3 2020). Do I need to install the modified Mi xDrip app?
> 
> @davidmtml yes, you have to use the modified app

Is there any news on when the official xDrip app will support this awesome feature? I am using latest nightly build 2021.02.17 and although it has a miband entry under Smart watches section, there is no auth setting in there and I can't make xDrip connect to my miband 5. I do not want to switch to an "unofficial" build, so i hope the miband 5 auth support will be merged into official xdrip soon.

**Comment by smeisner** [comment]
> > > I thought I saw that I can use the official xDrip app (which is what I've been doing, and it's the latest nightly from today, Sep 3 2020). Do I need to install the modified Mi xDrip app?
> > 
> > 
> > @davidmtml yes, you have to use the modified app
> 
> @bigdigital Is there any news on when the official xDrip app will support this awesome feature? I am using latest nightly build 2021.02.17 and although it has a miband entry under Smart watches section, there is no auth setting in there and I can't make xDrip connect to my miband 5. I do not want to switch to an "unofficial" build (as I am scared to lose my otherwise very well working settings or introduce other complications with my Setup), so i hope the miband 5 auth support will be merged into official xdrip soon.


Me too!

I cannot get the Mi band working at all. Using a Google Pixel 3 and a Dexcom G6 (in case that matters).

I purchased a Mi Band 5, installed the official Mi app from the play store. Got my account and band working. I then uninstalled it so I could install the modified Mi app version. I got the auth code populated in the internal storage folder (**Internal Storage -> freemyband -> miband<mac addr>.txt**). Then I removed the nightly build of XDrip (what I normally run) and installed the Mi Band version (**b978bec-2020.11.27**) and it will not connect. I see the error "Cannot find band" so I add the band's MAC address. Then I get the 'auth failure and I need to correct the auth code' message.

I have no place to add the auth code; is the file location I specified above correct? Can I add the auth code someplace manually?
Also, Is the version of xDrip correct?

Thanks for all the great work so far!!

**Comment by smeisner** [comment]
Found my problem. It is working fine as I described, except when I replaced xDrip with the version for Mi Band, the new version was not in fact running. I checked the version number I cited above and discovered it was wrong. So I force stopped xDrip, uninstalled, installed xDrip+ and everything works!

But still, I am really looking forward to bringing support for Mi Band into the regular xDrip.

**Comment by stackenblochen** [comment]
> Found my problem. It is working fine as I described, except when I replaced xDrip with the version for Mi Band, the new version was not in fact running. I checked the version number I cited above and discovered it was wrong. So I force stopped xDrip, uninstalled, installed xDrip+ and everything works!
> 
> But still, I am really looking forward to bringing support for Mi Band into the regular xDrip.

Happy to hear it worked for you. I think it is important to actually uninstall the regular xDrip app from your phone before installing the miband one (this was the scary part for me). But I also went down that path and installed the mi band version of xDrip, and it worked quite flawless. All my settings etc were imported, and miband 5 was connecting immediately. I read somewhere in @bigdigital blog that he wants to wait for some other watch support to run stable until he wants to merge his xdrip version back to the official branch, si I guess this answers my question from above.

**Comment by nexero** [comment]
> > But still, I am really looking forward to bringing support for Mi Band into the regular xDrip.
> 
> I read somewhere in @bigdigital blog that he wants to wait for some other watch support to run stable until he wants to merge his xdrip version back to the official branch, si I guess this answers my question from above.

Here's his PR: #1659

**Comment by Aloomabut** [comment]
Hello, I am using carelink follower+ mi band xdrip version that support band 5, I am not able to customize what I want to see in watch face, I need to remove the weather and to add my heart rate, is it possible to add custom watch face and what are the steps, I tried to read Artem Blog , but still don't now how to do it?

**Comment by Navid200** [comment]
Consolidated all watch support requests:  https://github.com/NightscoutFoundation/xDrip/issues/1872
