### ISSUE TITLE
xDrip lost connection to sensor and forgot any past values

### ISSUE THREAD

**Issue by nsghub** [NightscoutFoundation/xDrip#1411]
xDrip was running fine for a very long time. Suddenly it lost the connection to the G6 in the middle of the night. A simple "restart collector" fixed the issue. But it also forgot the whole history. I thought it might be an issue with MongoDB as the size is almost at the 512 Mb limit. Nightscout has no problems showing the complete history.
Unfortunately even the xDrip logs prior to the event are unavailable.

Any thoughts?

![Screenshot_20200819-073351](https://user-images.githubusercontent.com/39347827/90596433-31f82200-e1ef-11ea-9ca6-ab7f45d11d4e.png)

**Comment by tolot27** [comment]
Do you have 'Save Database Daily' and/or 'Glucose Retention' enabled in 'Less common settings'?

**Comment by nsghub** [comment]
"Save daily" is enabled and retention was set to 0. I changed retention to 99 days now. Is there a simple cleanup command for MongoDB?

**Comment by tolot27** [comment]
> "Save daily" is enabled and retention was set to 0. 

Then you can restore the database from the last backup and maybe merge the new values manually.

> Is there a simple cleanup command for MongoDB?

I don't know. But it is not a MongoDB, it is a SQLite DB.

**Comment by nsghub** [comment]
With MongoDB I meant the acutal MongoDB at mlab.com ;)
I thought this might have been the issue, but it is still running fine.

I imported the xDrip backup file and only lost some values on the phone. There are no gaps in Nightscout. I still don't know what happend last night but I hope that was a one time thing.

**Comment by tolot27** [comment]
How much space is left on your device?

**Comment by nsghub** [comment]
About 4 GB. One zip file is about 7,5 MB in size. That shouldn't be a problem.

**Comment by nsghub** [comment]
Happened again.
I installed the nightly 200713 now (was 200725).

**Comment by tolot27** [comment]
Did it happen at about the same time? Do you have any services running which scan/clean the apps/phone?

Are you experienced with [logcat](https://developer.android.com/studio/command-line/logcat)? If yes, please can you write the Android logs to a file (`adb logcat -f logcat.txt`) and attach the relevant entries (time of potential db corruption) to this issue?

**Comment by nsghub** [comment]
I didn't take a screenshot from the logs, but the first item was the "xdrip-daily". I assume this runs always at the same time. There are no clean-up apps/services running. It is a Pixel 3a with the official google firmware.

I don't see any interesting entries in logcat:

`08-20 04:27:14.966  1367  1455 I chatty  : uid=1000(system) android.bg expire 3 lines
08-20 04:27:20.423  1367  1457 I chatty  : uid=1000(system) ActivityManager expire 14 lines
08-20 04:27:57.526  1367  1705 I chatty  : uid=1000(system) AlarmManager expire 1 line
08-20 04:28:04.553  1801 14007 D PowerUI : can't show warning due to - plugged: true status unknown: false
08-20 04:29:04.554  1801  2506 D PowerUI : can't show warning due to - plugged: true status unknown: false
08-20 04:30:04.562  1801  2961 D PowerUI : can't show warning due to - plugged: true status unknown: false
08-20 04:31:04.560  1801  9012 D PowerUI : can't show warning due to - plugged: true status unknown: false
08-20 04:31:09.556  1367  3974 I chatty  : uid=1000(system) Binder:1367_1B expire 2 lines
08-20 04:31:10.198  1367 28292 I chatty  : uid=1000 system_server expire 2 lines
08-20 04:32:04.563  1801 13493 D PowerUI : can't show warning due to - plugged: true status unknown: false
08-20 04:32:20.297  1367  1457 I chatty  : uid=1000(system) ActivityManager expire 20 lines
08-20 04:32:20.361  1367  3814 I chatty  : uid=1000(system) Binder:1367_13 expire 1 line
08-20 04:33:04.556  1801 13656 D PowerUI : can't show warning due to - plugged: true status unknown: false
08-20 04:33:08.427  1367  1367 I chatty  : uid=1000 system_server expire 8 lines
08-20 04:34:04.581  1801 13983 D PowerUI : can't show warning due to - plugged: true status unknown: false
08-20 04:35:04.557  1801 13999 D PowerUI : can't show warning due to - plugged: true status unknown: false
08-20 04:36:04.558  1801 14007 D PowerUI : can't show warning due to - plugged: true status unknown: false
08-20 04:36:08.642  1367  1972 I chatty  : uid=1000(system) Binder:1367_8 expire 3 lines
08-20 04:36:09.433  1367  1720 I chatty  : uid=1000(system) Binder:1367_4 expire 5 lines
08-20 04:36:09.474  1367  1894 I chatty  : uid=1000(system) Binder:1367_5 expire 18 lines
08-20 04:36:10.454  1367 28439 I chatty  : uid=1000 system_server expire 2 lines
08-20 04:37:04.550  1801  2506 D PowerUI : can't show warning due to - plugged: true status unknown: false
08-20 04:37:12.691  1367  1457 I chatty  : uid=1000(system) ActivityManager expire 11 lines
08-20 04:38:04.559  1801  2961 D PowerUI : can't show warning due to - plugged: true status unknown: false
08-20 04:39:04.561  1801  9012 D PowerUI : can't show warning due to - plugged: true status unknown: false
08-20 04:39:09.858  1367  2872 I chatty  : uid=1000(system) Binder:1367_D expire 3 lines
08-20 04:39:11.949  1367  1457 I chatty  : uid=1000(system) ActivityManager expire 3 lines
08-20 04:39:12.363  1367  3083 I chatty  : uid=1000(system) Binder:1367_12 expire 10 lines
08-20 04:40:04.554  1801 13493 D PowerUI : can't show warning due to - plugged: true status unknown: false
08-20 04:41:04.562  1801 13656 D PowerUI : can't show warning due to - plugged: true status unknown: false
`

Another thing just happened. I received readings but in the xdrip home screen there were values shown, only in the widget and on Wear OS. xdrip wanted me to start the source setup wizard.

I uninstalled and reinstalled the 200725 daily now. Fingers crossed!

**Comment by tolot27** [comment]
This issue is related to #1280 and #1341.

Please can you also enable verbose logging in settings >less common settings > extra tags for logging and then add there: `DailyIntentService:v,DatabaseUtil:v,UserError:v,BgReading:v`.

**Comment by nsghub** [comment]
Yes, seems like the same issue.
Extra tags for logging are added and log storage is enabled.

**Comment by tolot27** [comment]
> Is there really no log file on the disk? Or is it stored in the sqlite DB?

No log file on the disk, only the table `UserErrors` in the exported SQLite DB.

Did the error occured again?

**Comment by tolot27** [comment]
Closing it in favour of #1280. Please continue there.
