### ISSUE TITLE
Starting a new sensor without queueing a "stop sensor" first

### ISSUE THREAD

**Issue by dhermanns** [NightscoutFoundation/xDrip#1412]
Hi!

We are using xDrip with a G6 Sensor. Our case is:

1) An old sensor has been stopped.
2) the xDrip UI is still in "running" State
3) We place a new sensor and forget to stop the xDrip UI BEFORE placing the transmitter

The effect for us was:
4) Before we can start the new sensor with xDrip, we have to press "Stop Sensor" in the xDrip UI.
5) In the above case our newly placed sensor gets the "stopped" event.
6) Result: The newly placed sensor can't be started anymore.

Solution 1): It should be possible to reset the xDrip UI and issue a "Sensor Start" Queue Item with sending a "Sensor Stop" Item before.
Solution 2): Maybe #1376 would be another solution to simply delete a queued "Sensor Stop" item before it is send to the new Transmitter.

But maybe there is already another solution that I have missed so far?

Thx!

**Comment by nsghub** [comment]
The sensor itself is "dumb" and you can restart it. You need to remove the transmitter (I use a guitar pick) and let it unconnected for maybe 30 minutes or short cut the two sensor pins.

But I'm with you, the problem could be solved in xDrip. The issue exists even if xDrip already reports "sensor stopped".

**Comment by dhermanns** [comment]
Good hint - thx! Yes even if you stop the sensor you would have to take care that the queued item has been really send to the transmitter. Otherwise you would have the same problem. So #1376 would help there, too, right?

**Comment by nsghub** [comment]
Yes, deleting queued items would be nice.

**Comment by tolot27** [comment]
Closing it in favour of #1118.

**Comment by serafinimc** [comment]
Hi! I found this thread while encountering a similar issue as the initial one and the queue solution does not help in my case. The transmitter is working fine and the sensor shows as "stopped" but for some reason the UI still shows the "stop sensor" option and not the "start sensor" one. Is there a way to send a Start Sensor command or showing the button for Starting the Sensor? If I use Stop Sensor I will loose this one and its a brand new one.

**Comment by Navid200** [comment]
@serafinimc 

This is a brute force method to fix this.
Please read it all before attempting.

First, have a look at the following to know how to clear the queue.  You will need to do this reasonably fast.

Now, go to the status page, where you can see last connected.  The valve keeps increasing and just before reaching 5 minutes, it goes back to 0.
Tell me if you don't see it.

Wait for it to reset to 0.  Then, wait 10 seconds.  Now, stop sensor.
As soon as you approve stopping sensor, clear the queue.

If you do that exactly as I have explained, you will stop the xDrip session without stopping the session on the transmitter.

Now, restart the phone.  If you are using a G6, after connectivity is established again, xDrip will auto start its session.

Please ask me any questions you may have before attempting this.
If you stop the sensor and fail to clear the queue in less than 4 minutes, you may stop the session on the transmitter, which is not good.

**Comment by serafinimc** [comment]
That's awesome and it worked perfectly, thank you!
