### ISSUE TITLE
xDrip receives data from bubble but data is wrong

### ISSUE THREAD

**Issue by Archibald-rgb** [NightscoutFoundation/xDrip#1417]
I have upgraded my bubble device firmware to v2.8 and xDrip just stop working. This is a couple screenshot about it.
![Screenshot_20200824-131731](https://user-images.githubusercontent.com/61731785/91069447-18673800-e63e-11ea-9eb9-13405104a4dc.png)
![Screenshot_20200824-130519](https://user-images.githubusercontent.com/61731785/91069465-1ef5af80-e63e-11ea-8021-9991f094ca17.png)

**Comment by tolot27** [comment]
Does it work meanwhile or did you contact the bubble dev team?

**Comment by Archibald-rgb** [comment]
yes, it's working after i've upgraded xDrip
