### ISSUE TITLE
Anyone have xdrip+ still working with Sony SW3?

### ISSUE THREAD

**Issue by icewiz12** [NightscoutFoundation/xDrip#1419]
G6 working great with Galaxy S9 and xdrip+.  

Bought a NIB SW3 and let it do its updates. Enabled Wear OS as instructed in xdrip+ and even got a sync message on the phone.  No xdrip app on the watch, no watch faces, no sign of xdrip. 

xdrip app on phone shows watch services not running. 

Any thoughts as to how to get xdrip+ to show on the watch?

**Comment by jumalakarhu** [comment]
You need to update google play services on the watch. Either use adb (takes an effort) or (easy) unpair watch, remove wear os and install old android wear. I used this https://www.apkmirror.com/apk/google-inc/android-wear/android-wear-2-9-0-185084575-gms-release/android-wear-smartwatch-2-9-0-185084575-gms-android-apk-download/
Then pair watch and then within an hour or so xdrip is installed on watch.
To use watch as collector I have to tick "only use wear" in addition to "force wear...". Sometimes bg from watch is not displayed on phone. Use the treatment tab on watch and issue 1g carbs.

**Comment by icewiz12** [comment]
Amazing. I just figured this out ... and you posted just as I wrote up what I found.

Here it is for posterity. It's working just like jumalakarhu said.

Another update. I pretty much confirmed that the new Wear OS Android app will not load Google Play (Wear OS) to the watch. Without Google Play (Wear OS), many apps from the phone will never load to the watch.

I used this guide to sideload the Google Play (Wear OS) for Android 6 to the watch, and magically xDrip appeared within 15 minutes. I’m doing it on the 2nd watch now. Getting the watch and phone to both authorize debugging is an exercise in frustration, but if you try it, know that it’s possible. It’s a combination of having the right PC drivers for your phone (I needed Samsung USB) and watching your phone and watch for debug authorizations. When you are done, you can turn off all the debugging.

I’m imagining that for all of you that have it working that didn’t do this you set it up when Google Play Services were automatically located from the Wear OS app. When and if Google no longer supports Android 6 in Google Play Services, this route will shut down and only those with working watches will still be alive … any reset and the watch will no longer be able to load xDrip (unless someone finds a way to sideload the Android 7 services onto Android 6).

Hopefully this will help someone else.

https://forum.xda-developers.com/smartwatch/smartwatch-3/fix-app-sync-smartwatch-3-dead-t4121409

**Comment by tolot27** [comment]
Solved according to the steps described by @jumalakarhu and @icewiz12 .
