### ISSUE TITLE
Feature: Clear Ob1G5StateMachine Queue

### ISSUE THREAD

**Issue by savek-cc** [NightscoutFoundation/xDrip#1420]
When using G5/G6, commands to be sent to the sensor are stored in a "commandQueue" to be transmitted and handled on next connection.

Currently, it is not possible to reset/clear this queue.

Example: User entered a calibration in error. While it is possible to undo this calibration on the main screen, it is not possible to remove the calibration request from the command queue - so it is going to be sent to the G5/6 anyway.
Same is true for sensor stop or others. I ran into the problem of wanting to cancel a command to the G5/6 multiple times - but was unable to do so given the current application interface.

If you think, this feature might make sense (even if only running in expert mode), I could try to implement this and make a pull request - I don't currently really have an active insight into the ongoing development @jamorham .

**Comment by tolot27** [comment]
@savek-cc That would be a good enhancement. Please can you create a PR?

**Comment by Navid200** [comment]
@savek-cc  This is already implemented.
If you need to clear the transmitter queue, tap on the treatment menu (syringe symbol).  Long press on the microphone symbol at the bottom right corner of the keypad.  Enter "clear transmitter queue" without the quotes.

Please try it.  Unless there is a problem with it, would you please close this issue?

**Comment by savek-cc** [comment]
Problem ist the pronunciation of "queue" (google takes "cue"s) - but it can also be typed.

**Comment by savek-cc** [comment]
See above

**Comment by Navid200** [comment]
Thanks for clarifying that.
I understand that Google may misunderstand the verbal command, and when typed, the command works for sure.
Thanks a lot
