### ISSUE TITLE
collaboration information and contacts

### ISSUE THREAD

**Issue by tolot27** [NightscoutFoundation/xDrip#1421]
The [readme file](https://github.com/NightscoutFoundation/xDrip/blob/master/README.md#collaboration) states: `Please contact us if you want to get involved and study the collaboration guidelines before submitting any patches or pull requests.`
Unfortunately, no more details are provided. How to get in contact with you?

**Comment by Navid200** [comment]
There must have been an update.
That link goes no where now.

**Comment by tolot27** [comment]
Link fixed.

**Comment by tolot27** [comment]
With #1422 a link to CONTRIBUTING.md was added. This issue will be closed automatically after #1675 gets merged.
