### ISSUE TITLE
Xdrip+ with Samsung Active2 Watch

### ISSUE THREAD

**Issue by brunosaraivac** [NightscoutFoundation/xDrip#1424]
Hi guys, 
I would like to ask a little help. I have been reading for all day long and I still didn´t discover how I can see my blood sugar from xdrip+ on my watch samsung active2.
Is it possible to do it? Please help ;)

**Comment by Chechi-dia** [comment]
hey you have to use extra programms to that. Im using a combination of tasker and pujie black which i really like. I heard there is a different programm aswell called g-watch app which is an all in one solution with less customization as i understand it.

**Comment by tolot27** [comment]
Should work with the [G-Watch App](https://facebook.com/gwatchapp). See also #460.
