### ISSUE TITLE
Miband 4 - Feature Request: More Alarm Features

### ISSUE THREAD

**Issue by Otter3eso57** [NightscoutFoundation/xDrip#1425]
1. I think all alarms should be forwarded to the watch to be able to mute them without touching the phone. An option to select which alarms are send trough would be awesome. Alarms are missing for:
    A. BG rising fast
    B. BG falling fast
    C. Persistent High Alert
    D. Forecast Low
    E. Connection lost (xDrip to sensor)
    F. Calibration reminder

2. Additionally, it is not possible to mute an alarm right away through the watch because you have to wait a few seconds for the screen to upload (while the phone alarm is sounding). Maybe send the alarm first and wait for the user response and then update the screen. (The first moment you can see the uploaded screen is anyway after you muted or dismissed the alarm.)

3. Maybe add more detail to the notification text.

Old:
```
Alert
snoozed for
90 min

      00:17
```
New:
```
Alert LOW
snoozed for
90 min until
01:47
        0:17
```

**Comment by tolot27** [comment]
Thank your four your suggestions. But they cannot be addressed by the developers of xDrip, only by @bigdigital. Please suggest it at https://bigdigital.home.blog/2020/08/25/new-xdrip-now-supports-miband-5/ or contact @bigdigital directly.

**Comment by Nyan-Korea** [comment]
Hello.

I use Freestyle libre + Miao Miao 2 + Mi band 5 + Android(Galaxy 9 +)

I have two problems in using it.

1. Xdrip loses bluetooth Miao Miao 2 or Mi band5 usally one time in two days.
And it never connect it again by it self.
I have to connect it again in 'Bluetooth Scan' menu.

2. In Miband screen, I want to see the scaned time like (3 mins ago).
If it is not possible, I want to know that it past more than 5 minutes.
Now it show only the scaned time so I have to compare it by my self everytime I see the Mi band 5.

Thank you for the grate App.
Please give me feedback.

112fkdldjs@naver.com

**Comment by tolot27** [comment]
@Nyan-Korea Please open your first point as a separate issue and remove it here. It's a bug and not related to this feature request. Thank you!

**Comment by Otto75so3e** [comment]
Hello Nyan-Korea,
the values you see on the screen are just a background image. So it is not possible to show the elapsed time. Please see also issue #1317 

If there is no Bluetooth lost indicator on your screen and the value is not crossed out than the value you see is not older than 15 min.

**Comment by tolot27** [comment]
I'll close this issue because it is solved in the build available at https://bigdigital.home.blog. We are still waiting for @bigdigital to address the requested changes until we can merge #1659.
