### ISSUE TITLE
Estado do sistema: não ligado

### ISSUE THREAD

**Issue by sofiaxdrip** [NightscoutFoundation/xDrip#1426]
Uso o x drip no samsung Galaxy A10. Muitas vezes o programa pára de funcionar,  do nada, e quando tento reconectar não consigo e sempre está "estado do sistema: não ligado". Não entra de jeito nenhum. Baixo outras versões,  reinicio o celular, restauro configurações de rede...faço tudo...e,  eventualmente,  não sei usando qual opção acima, ele volta a ter sinal e aparece "ligado. O que pode estar ocorrendo?

**Comment by tolot27** [comment]
@sofiaxdrip Please can you change the title and your text to English?

**Comment by tolot27** [comment]
We can only support tickets written in English.
