### ISSUE TITLE
Is it possible to use simultaneously Miaomiao as CGM and Countour Next One for blood measures? 

### ISSUE THREAD

**Issue by bertothunder** [NightscoutFoundation/xDrip#1428]
Hi,

 We've been users of XDRip with Miaomiao for managing our children's T1 diabetes; so far, everything's great.

 However, now we have a Countour Next One BT blood measuring device, which would help a lot to automatically transfer each blood measure automatically to XDrip, simultaneously with MiaoMiao... or we thought so it was possible. 

 I've been able to configure and pair the Next One device, but it will only automatically transfer each blood measure **only** if I set it as the main source of data; I'd want to keep MiaoMiao via Libre Bluetooth as main source, but also receive any measure from Next One as it happen? Is that possible?

**Comment by tolot27** [comment]
Which version of xDrip do you use? For a long time, glucose meters are configured separately. I cannot found the Contour in the hardware sources, only in the glucose meters menue.

**Comment by bertothunder** [comment]
Sorry, didn't see any response on this until now. The release was one of the recent ones, but I misconfigured the part for the glucometer. After couple of more trials last week, I was able to make it work as I expected, so it uses CGM as hardware sources, and any measurement coming from the glucometer is automatically added, re-calibrating under the right conditions.
