### ISSUE TITLE
NightscoutUploader UnparseableDate

### ISSUE THREAD

**Issue by iversenshotrods** [NightscoutFoundation/xDrip#143]
Ive got a consistent error. Its titled "NightscoutUploader" and the description is "Unable to do REST API Download java.text.ParseException: Unparseable date: "2017-06-30T14:22--0700" followed by my correct Password/URL.

My URL has been cropped out of the image. The log comes up consistently but with different time signatures.

![19621304_10159448035685497_5412278459071094564_o](https://user-images.githubusercontent.com/19600470/27812775-32a9713e-6026-11e7-8133-63e698cf23e1.jpg)

**Comment by Aquarius83mn** [comment]
Hello, read and write here? For a other way to communication Medtronic Uploader > https://github.com/NightscoutFoundation/xDrip/issues/157

**Comment by jamorham** [comment]
This is an old issue but I believe I have previously resolved this bug. Can you let me know if you think that is the case? Thanks.

**Comment by jamorham** [comment]
Marking as resolved, please re-open if it reoccurs

**Comment by jwoglom** [comment]
I'm running into this right now on the 12/22 release. It seems to have occurred after switching timezones.

**Comment by jwoglom** [comment]
On closer inspection, the error message is slightly different, and it appeared to resolve itself in the span of a few minutes: https://i.imgur.com/uaWMYKU.png
