### ISSUE TITLE
Smart watch Xiaomi Haylou Solar LS05 + xDrip ?

### ISSUE THREAD

**Issue by DMax540** [NightscoutFoundation/xDrip#1431]
Hello! Can you please tell me, can I use this "Smart watch Xiaomi Haylou Solar LS05" with XDrip+ app?

I don't have Dexcom G5 sensors yet, I want to buy it. But I have this smart-watch. Buying other watches that will definitely fit is very expensive for me ...

**Comment by tolot27** [comment]
I suspect this is not possible, yet. This smartwatch does not run Wear OS or Tizen OS.
