### ISSUE TITLE
Bluetooth connected but unable to retrieve initial readings

### ISSUE THREAD

**Issue by verityjane** [NightscoutFoundation/xDrip#1433]
I have a miaomiao1, using xdrip. Randomly lost connection this morning - have tried all the usual (resetting MiaoMiao device, restarting phone, restarting collector, closing and opening Xdrip app, uninstalling and reinstalling latest xdrip app,  charged MiaoMiao to green light)
It connects and recognises the MiaoMiao on Bluetooth, but just displays the connecting initial readings. Can anyone help?
![Screenshot_20200908_112951_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/47474855/92537699-ae9d7f80-f234-11ea-9c69-e5b5b8f2b290.jpg)
![Screenshot_20200908_113404_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/47474855/92537703-b2c99d00-f234-11ea-993f-ad1ad6f46b24.jpg)

**Comment by tolot27** [comment]
Please can you enable verbose logging in settings > less common settings > extra tags for logging and then add there: `BluetoothScan:v,DexCollectionService:v` and post relevant lines here?

Please also contact the developers of MiaoMiao and ask for support.

**Comment by Navid200** [comment]
@verityjane Would you please close this issue if it has been resolved?
For questions about how to use xDrip, please use the support channels first to ensure your settings are correct.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks

**Comment by Navid200** [comment]
Please update if you want to reopen.
