### ISSUE TITLE
Android 10 in Samsung A80

### ISSUE THREAD

**Issue by izsapir** [NightscoutFoundation/xDrip#1434]
Hi, using Samsung A80, it worked pretty well until we have upgraded it to from Android 9 to 10, after that it didn't manage to connect to the transmitter, I got some help using the following link : https://forum.fudiabetes.org/t/upgraded-samsung-and-having-xdrip-issues-fixed/7057 , and it solved the problem,now it able to connect, but when I used the stop sensor and then the start sensor and even that I moved the clock 2 hours back, it still insists that we need to wait 2 hours until it will warm up, anyone know how it can be resolved?

**Comment by tolot27** [comment]
@izsapir Please provide xDrip version and devices you are using.

**Comment by izsapir** [comment]
thanks,
Devices: handset:  Samsung A80, Dexcom g5, Android 10 latest   
Xdrip version: latest build from 4 /sep/2020

**Comment by tolot27** [comment]
Sensor stops and starts are sent to the transmitter and the warm-up happens there. xDrip cannot override the Dexcom transmitter behaviour.

**Comment by izsapir** [comment]
thx for the answer, its strange as it didn't happen to me in the past, anyway we will move to G6 in few weeks so I will check it again, however, in the last few days we are facing  loss of connection, forget sensor and reconnect doesn't help, I haven't found the right formula to overcome the problem, but several combination of phone restartsBT restarts, solves the problem, but sometimes it takes more than1 hour until the xDrip is connecting again the G5, any suggestion( note that I faced the same issue in the previous G5 as well before I replaced it to the current one )?

**Comment by tolot27** [comment]
Maybe the transmitter battery is end of life? Do you use the Dexcom receiver side-by-side?

Please reopen this issue if the problem reoccurs with the G6 transmitter.

**Comment by izsapir** [comment]
I have no Dexcom receiver, it happened only after the  upgrade to Android 10, before that all was fine

**Comment by izsapir** [comment]
Hi, after factory reset ( and installation of the latest android patches ) all problems gone,  seems like the problems were related to the Android patches, thx anyway for the help !!!

**Comment by tolot27** [comment]
Thanks for your feedback. Nice to hear that it works now. 😃
