### ISSUE TITLE
Mi Band (5): Enhancements

### ISSUE THREAD

**Issue by ArthurusDent** [NightscoutFoundation/xDrip#1435]
I'm using a Mi Band 5 and would like to propose the following enhancements:

1. The colour of HIGH blood sugars is red but in xDrip+ it's orange. I think it should be the same as in xDrip+ or at least some light orange for better legibility, if that's a problem. EDIT: LOW values are in blue, which I also do not understand. Shouldn't they be red?

2. I'm coming from a Pebble and its watchface makes it easier to see how old the last received blood sugar is. Currently the Mi Band watchface displays the time at which the last bg was received. If I want to know how old the bg is I have to first look at the time of the bg and then at the current time and calculate the difference. It would be much easier, if the watchface calculated the passed time itself. The Pebble can do this on the watchface but I think the Mi Band can't. Can the Mi Band maybe just display something like "BG_delta, 5 min ago", "BG_delta, 10 min ago" etc.? Or "BG_delta, 5+ min ago", "BG_delta, 10+ min ago"? Maybe even with a colour change if it passes 15min?

3. I already expect this to be impossible but can the "Syncing" while updating the watchface be disabled?

4. xDrip+ doesn't show the steps and heart rate on the graph any more (compared to my old Pebble). Could this be added?

5. When I'm getting an alert on the watchface the bg is being displayed in small writing. Could the bg (and maybe also HIGH and LOW) be set to broad?

6. I believe that when writing the european way of writing the date there is missing a dot on the watchface. Currently it's 16.09 but I think it should be 16.09.

Great work so far, thank you! :)

**Comment by tolot27** [comment]
Thank your four your suggestions. But they cannot be addressed by the developers of xDrip, only by @bigdigital. Please suggest it at https://bigdigital.home.blog/2020/08/25/new-xdrip-now-supports-miband-5/ or contact @bigdigital directly.

**Comment by ArthurusDent** [comment]
I know that none of the regular xDrip+ developers write code for the Mi Bands. But I do asume that @bigdigital follows this project and therefore gets informed about issues. Just to make sure he is aware of this issue, I have now tagged him.

**Comment by bigdigital** [comment]
Hi.

1. Initially, the line colors was the same as in the xdrip, but many people use different lines preferences, and in some cases, they were hard to see on the small screen. So the line colors were hardcoded. In the future, i planing to implement a watchface config file. By using this config file it would be possible to change elements position and colors. This will allow achieving the different design of the wathcfaces.
2. Unfortunately such approach cannot be implemented on miband. The miband data is a static image, which is generated before watchface uploading. If you lose bluetooth connection, you wouldn't know how old the data on the screen.  For example if the latest watchaface was uploaded with text 5 min ago, and there would be some problem with the connection, you would see the outdated text until the next successful watch face uploading, which i think would be totally unacceptable. 
As for the outdated data highlighting. If the bg data considered as outdated (usually they considered as outdated if there were no new values during 15 min) then the BG data, would be crossed out. I guess this should be enough.
3. Not possible. This behaviour embedded into the miband firmware.
4. The heart rate should work. You would need to configure heart rate update interval in MiFit or any thirdparty application. To see heart rate data in xdrip, the options "Use Health Data" and "Heart Rate sensor" which is located in Settings -> Smartwarch Features -> Smart watch sensors,  should be enabled.
5. Do you mean to uppercase text?
6. Unfortunately the miband wathcface has a very limited functionality so there no way to add an additional dot after the month digits. Also, to be honest, i never saw such data format usage.

**Comment by Klaus3d3** [comment]
> 
> 
> Hi.
> 
>     1. Initially, the line colors was the same as in the xdrip, but many people use different lines preferences, and in some cases, they were hard to see on the small screen. So the line colors were hardcoded. In the future, i planing to implement a watchface config file. By using this config file it would be possible to change elements position and colors. This will allow achieving the different design of the wathcfaces.
> 
>     2. Unfortunately such approach cannot be implemented on miband. The miband data is a static image, which is generated before watchface uploading. If you lose bluetooth connection, you wouldn't know how old the data on the screen.  For example if the latest watchaface was uploaded with text 5 min ago, and there would be some problem with the connection, you would see the outdated text until the next successful watch face uploading, which i think would be totally unacceptable.
>        As for the outdated data highlighting. If the bg data considered as outdated (usually they considered as outdated if there were no new values during 15 min) then the BG data, would be crossed out. I guess this should be enough.
> 
>     3. Not possible. This behaviour embedded into the miband firmware.
> 
>     4. The heart rate should work. You would need to configure heart rate update interval in MiFit or any thirdparty application. To see heart rate data in xdrip, the options "Use Health Data" and "Heart Rate sensor" which is located in Settings -> Smartwarch Features -> Smart watch sensors,  should be enabled.
> 
>     5. Do you mean to uppercase text?
> 
>     6. Unfortunately the miband wathcface has a very limited functionality so there no way to add an additional dot after the month digits. Also, to be honest, i never saw such data format usage.

@2 the actual value will only be crossed when the phone losses the connection to the sensor but not to the band. Am i right? The crossing only happens with a watchface update. Or is there any trick?

**Comment by bigdigital** [comment]
Hello, sorry for the delay, haven't seen your question. In any case, i'll reply. Yes, I use a small trick here. When the values is not valid and connections between phone persist, would be generated and uploaded watch face with crossed value (like in xdrip apk). But if miband will lose connections with the phone, you also will see the crossing value. For this, I use a Bluetooth connection status icon, which was styled as a crossed line and displays above the bg value.

**Comment by Navid200** [comment]
@ArthurusDent Would you please close this issue if your questions have been answered?
If not, please use the support channels:
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks
