### ISSUE TITLE
problems writing to influxDB

### ISSUE THREAD

**Issue by user-hash** [NightscoutFoundation/xDrip#1436]
Wonderfull project with great functions, but I have problems writing to influxdb on my rpi4 using authentication.

Error is: Write to InfluxDB failes: java.lang.NullPointerException: attempt to invoke virtual methods "java.lang.Stink okhttpUrl.host()" on a null object reference

I have added the ip adress, port and auth i usually use, but I get this error.
Any ideas?
I would also suggest adding mqtt to the function list of xDrip, because its useful to get the data in nodered and manipulate it, before you write to the actual database.

**Comment by tolot27** [comment]
Please can you enable verbose logging in settings > less common settings > extra tags for logging and then add there: `InfluxDBUploader:v` and post relevant lines here?

It looks like there is a parsing problem with the URL of your RPI4.

**Comment by user-hash** [comment]
Besides the same error messege, It only displays the influx url, which it seems correct
http://{192.168.1.xxx}:{8086}
Im not using the latest xDrip version thought, because my Bubble wont work with it. Build I use is from middle of June.
Thanks for help!

**Comment by tolot27** [comment]
`http://{192.168.1.xxx}:{8086}` is not a valid URL. Please remove the curly brackets (`{`, `}`) and try it again.

**Comment by user-hash** [comment]
I know how IPs and port looks like, but instruction clearly says only replace the values in the curly bracket. 
Thanks for help, its working now and I can get values into Grafana!

**Comment by tolot27** [comment]
> Instruction clearly says only replace the values in the curly bracket.

I'll tag this issue with `status: needs docs review` as soon as I can create new labels. Please can you link the relevant line in the docs? It is indeed a simple fix.

**Comment by user-hash** [comment]
Thats great solution!
The line can be found in: Settings/Cloud Upload/InfluxDB/InfluxDB URI
"Replace example values in {}'s with your correct values"

**Comment by user-hash** [comment]
Many thanks for help!
Do you think its possible to export other values like prediction values set in settings, and real time prediction values?
If this is possible, you cold enter your - insulin, carbs, exercise, for the last xx days in xDrip, and send the values to the Rpi, which could suggest better start values, based on the data in the last xx days.
It should be possible to calculate more accurate data for results predictions, because carb ratio, insulin sensitivity, carb absorption, would be calculated by rpi depending on the values in last 14 days. It could easily set the ranges in hours too!
Im not a programmer, so its just an idea=)

**Comment by tolot27** [comment]
@user-hash Indeed, why not? You can open another issue with your feature request, if you like.

**Comment by Navid200** [comment]
@tolot27 What is the objective of this issue?  What needs to happen, in the xDrip code, for it to be closed?

**Comment by Navid200** [comment]
It looks like this has been resolved.  So I close it.  We can reopen if needed.
