### ISSUE TITLE
xDrip (with Libre 1 + MiaoMiao2 + Huawei Honor 8A) can't connect BT

### ISSUE THREAD

**Issue by ARkaine2** [NightscoutFoundation/xDrip#1437]
Please help.

I updated xDrip to Nightly build 4th Sep 2020 and it stopped to connect.

It stucks at:
![photo_2020-09-18_13-48-10](https://user-images.githubusercontent.com/31447095/93604514-23f41780-f9ce-11ea-8ce9-7a25db64955c.jpg)

In "Состояние системы" > "Classic Status page": Статус соединения: Не подключено.
![photo_2020-09-18_13-48-09](https://user-images.githubusercontent.com/31447095/93604553-2fdfd980-f9ce-11ea-9367-16d717c4a3a4.jpg)

In "Состояние системы" > "BT Device" ALWAYS: "Next Wake up: 5 мин".
![photo_2020-09-18_13-48-09 (2)](https://user-images.githubusercontent.com/31447095/93604599-4128e600-f9ce-11ea-9f06-a98d2bdf526a.jpg)

Seems that application has all necessary rights:
![photo_2020-09-18_16-38-33](https://user-images.githubusercontent.com/31447095/93604665-5c93f100-f9ce-11ea-85a2-13fe9fd6ac68.jpg)
![photo_2020-09-18_16-38-35 (2)](https://user-images.githubusercontent.com/31447095/93604670-5dc51e00-f9ce-11ea-8154-17c744b03c42.jpg)
![photo_2020-09-18_16-38-35](https://user-images.githubusercontent.com/31447095/93604771-81886400-f9ce-11ea-8a5e-a6aea6c698b2.jpg)

I deleted application and restarted smartphone.

**Comment by user-hash** [comment]
Try to use nightly version from June.
https://github.com/NightscoutFoundation/xDrip/issues/1368

**Comment by Villaton** [comment]
I have similar problem with Nokia 9 (Android 9) + MiaoMiao + Libre 1. This happens every time I reboot my phone. I can add logs, if needed.
Workaround is to: shutdown xDrip app, clear xDrip app data, reboot phone, start xDrip and do initial configs.
Yes, it means that calibration data is gone.

**Comment by user-hash** [comment]
Hey, I dont think this sis the same issue. I think you only need to manually connect the BT device after reboot, at least I have to do it on my device when I reboot it.

**Comment by Villaton** [comment]
> Hey, I dont think this sis the same issue. Try to manually connect the BT device after reboot, at least I have to do it on my device when I reboot it.

I have tried multiple Times (forget device->bt scan->select MiaoMiao), it's stuck on "Attempting connection" state.

**Comment by ARkaine2** [comment]
Thanks a lot for fix of this problem in new version!
This is a real life save.

**Comment by sgalles** [comment]
Same problem with **Libre 1 + MiaoMiao2 + Galaxy S8**
Actually after the initial install it worked for one day, then at some point the user activated airplane mode on the phone during the night, but the next day when bluetooth was reactivated, XDrip never reconnected (even after uninstall/reinstall + reset of MiaoMiao2 )

**Comment by Navid200** [comment]
Please use the support channels to see what other users are doing in similar situations.  You may find a solution already.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

If there is no solution or work-around, we can always reopen the issue.
