### ISSUE TITLE
New Feature Request: Integration of Ambrosias BluCon for Libre

### ISSUE THREAD

**Issue by osodebailar** [NightscoutFoundation/xDrip#144]
I think it would be a good idea to integrate the new NFC>BT Reader of Ambrosia ( www.ambrosiasys.com)
to read Abbott's Libre data.

**Comment by jamorham** [comment]
Can you try the Sept 6th Nightly and see if this works for you. Either download from the releases section or select the Nightly channel in the update settings. If nightly is not visible in the settings, first select Alpha and then go out of settings and back in and select Nightly.

**Comment by osodebailar** [comment]
Thx, i am testing Bluecon since the first integration in xdrip.
With the build of Sept 6th it is working very well since the last 24 Hours.
Data transfer and connection/reconnection is full working as far as i see.

In the moment the only thing are 2 log entries about 2 unkkown commands.

![screenshot_20170906-220536](https://user-images.githubusercontent.com/25795894/30174535-b4f3b3da-93fb-11e7-9558-c6954e750324.png)

**Comment by gregorybel** [comment]
Yes we will ask only one time after connection. Idea is to gather lots of these answers in order to find for what there are good. Reverse engineering is not yet finished.

**Comment by jamorham** [comment]
marking as resolved
