### ISSUE TITLE
Xdrip dropping Miaomiao connection

### ISSUE THREAD

**Issue by rdicey** [NightscoutFoundation/xDrip#1442]
After a reasonably long period running relatively smoothly, I am now losing Bluetooth connection to my Miaomiao every hour or two. I restart Bluetooth and clear the cache and it works again for a bit. Can anyone offer help please. I have reset Miaomiao and restarting phone multiple times.

Further to the above, the Xdrip connection to my Miband seems to fail at the same time and reverts to the standard watchface until connection is remade.
Is there a Bluetooth bug in Xdrip? 

System is as follows:
Libre 1
Miaomiao 2
Sony Xperia running Android 10
Miband 4

**Comment by tolot27** [comment]
@rdicey Which version of xDrip do you use?

**Comment by rdicey** [comment]
I upgraded to v 0.3.2 yesterday morning and am still having to reset Bluetooth every hour or so.

**Comment by bigdigital** [comment]
Hi. Could you please check if Miao Miao loses Bluetooth connection if you would use a latest nightly build so we can identify if this problem were caused by modifications in my 'xdrip_miband' apk? Thanks

**Comment by rdicey** [comment]
OK, so temporarily lose Miband on Xdrip? I'll do that and get back to you.

**Comment by bigdigital** [comment]
Yep. Only for the test. The xdrip_miband v 0.3.2 was synchronized with the latest official nightly build, but there were almost no changes in the xdrip core. So i suppose the problem should be also in the official nightly build. Also before you switched your xdrip, could you please send me error logs, will see if they would be useful. [Here ](https://bigdigital.home.blog/2020/08/25/new-xdrip-now-supports-miband-5/#debug)you can read how to do this.  Thanks.

**Comment by rdicey** [comment]
Sorry, I already changed over so can't send the logs. I should know within 2-3 hours if the problem is still there.

**Comment by bigdigital** [comment]
No problem, just noticed you use Miband 4. This band version already supported by official xdrip nightly build, so you can test together with miband4.

**Comment by rdicey** [comment]
Great, thanks

**Comment by rdicey** [comment]
Hi, I just checked and there is no MiBand option in Xdrip+ downloaded from https://github.com/NightscoutFoundation/xDrip/releases/tag/2020.09.04

**Comment by rdicey** [comment]
Hi BigD,
Run for 3 hours+ with no loss of service on Miaomiao. Uninstalled XDRIP+ and reinstalled v0.3.2

**Comment by rdicey** [comment]
Miband comms problem solved but still have some sort of Android battery saver cutting bluetooth connection to Miaomiao. Bluetooth is excepted from Battery Saver, but I can't find any way to Except the Bluetooth Midi services. Any ideas?

**Comment by rdicey** [comment]
Final update on this issue.
Miband connection issue solved in latest release, thank you.
Miaomiao connection problems traced to UK Gov NHS Covid tracking app causing Bluetooth conflicts.
