### ISSUE TITLE
Galaxy Note 20 5G "waiting to connect" BLE authentication errors

### ISSUE THREAD

**Issue by eurenda** [NightscoutFoundation/xDrip#1447]
Attempting to use nightly release edd2c2a-2020.09.04 with a 8K0### series transmitter on a Galaxy Note 20 5G with Android 10 and August 1 Security path for a NA region phone.

xdrip never gets past _waiting to connect_ message on UI when attempting to authenticate, logs updated via xdrip+
repeating errors show in event list:
`09:23 authentication notification throwable: (CHECK_AUTH) com.polidea.rxandroidble2.exceptions.BleDisconnectedException: Disconnected from MAX=XX:XX:XX:XX:XX:XX with status 19 (GATT_CONN_TERMINATE_PEER_USER) 20202-09-23 09:23:34`

**Comment by tolot27** [comment]
@eurenda Did you get it working?

**Comment by eurenda** [comment]
No, I have not got it to work, still get a rotating loop of* Brain State:
Waiting to connect Errors: [counter keeps updating with failures]* and
*Bluetooth
Link: Connecting.  *Tried everything from forgetting device, restarting
collector, to no avail.

**Comment by tswire** [comment]
Exact same issue with same xdrip version on Galaxy Note 20 Ultra

**Comment by eurenda** [comment]
Able to start sensor session with 2020.10.01 nightly build.   No sure if fiddling with settings led to this or if actual build changes allowed this.   Uploading screenshots of my settings in case these keep others. 
![Screenshot_20201004-155957_xDrip+](https://user-images.githubusercontent.com/1902827/95031828-e4375c00-066c-11eb-8bba-41a6f822b506.jpg)
![Screenshot_20201004-155951_xDrip+](https://user-images.githubusercontent.com/1902827/95031839-e994a680-066c-11eb-9afe-9ea958f45b21.jpg)

**Comment by eurenda** [comment]
![Screenshot_20201004-155951_xDrip+](https://user-images.githubusercontent.com/1902827/95057007-6134f680-06aa-11eb-8e1c-645a74337122.jpg)
![Screenshot_20201005-012930_xDrip+](https://user-images.githubusercontent.com/1902827/95057029-698d3180-06aa-11eb-8820-4ffba44d2e57.jpg)

**Comment by eurenda** [comment]
Fixed with 2020.10.01 nightly build,  see above comment screenshots

**Comment by Loushax** [comment]
9:00 pm i

Application data Visiomy. 3

OperationCount: 0

Fro

Ha

Executor: PooledThreadPo ple olExecutor[getTaskCount() = gu 2910, getCompleted TaskCount()

Ce

2910, getActiveCount() =

0, getLargestPoolSize() = 2, getMaximumPoolSize()

= 2 lisShut Down(),!

is Terminated(luuf:==== ApiService dumped info ====

ID: [194]

Action: com.google.android.g s.nearby.sharing.START_SERVIC

Visibility: 3

OperationCount: 0

Executor: PooledThreadPo olExecutor[getTaskCount() = 0, getCompleted TaskCount() = 0, getActiveCount() = 0, getLargestPoolSize() = 0, getMaximumPoolSize() = 1! is Shutdown(), lis Terminated()]

com.google.android.gms.nearb y.sharing.NearbySharingService

Version: v2 42

ve

5pr

God

POTY

We

LPO
