### ISSUE TITLE
Huawei SmartWatch as a collector

### ISSUE THREAD

**Issue by billymild** [NightscoutFoundation/xDrip#145]
This is a thread to stat what combos you have tried with xDrip+ for the Huawei to work as a stand alone collector. I have tried a few of the settings and will post here what combos are running and BT settings. 

If anyone else has tried and failed please post.

**Comment by billymild** [comment]
The standard the debug setting did not work. I don't know of a way to upload screenshots from my phone to this GitHub yet.

**Comment by kskandispersonal** [comment]
Which debug setting are your referring to?
Can you upload the screenshots to your desktop then to this thread?

**Comment by billymild** [comment]
![screenshot_20170708-114139](https://user-images.githubusercontent.com/29168607/27996426-62d24356-64a7-11e7-9961-c99eaf6ff87c.png)
![screenshot_20170708-114259](https://user-images.githubusercontent.com/29168607/27996427-62d60d10-64a7-11e7-9e92-23c1a0eb79af.png)

**Comment by billymild** [comment]
I tried another combo which also did not work. I used the following Debug settings. Log file attached as well. 

![screenshot_20170709-164118](https://user-images.githubusercontent.com/29168607/27997443-d96dd762-64bd-11e7-8bf3-5ecb1c052d59.png)
![screenshot_20170709-164309](https://user-images.githubusercontent.com/29168607/27997444-d96dec8e-64bd-11e7-9505-a74b16b6ec1a.png)

**Comment by billymild** [comment]
Tried with a new Debug setting Force G5 to UI Thread:
![screenshot_20170709-170026](https://user-images.githubusercontent.com/29168607/27997552-0ab894b8-64c0-11e7-83e6-0a9295162922.png)
![screenshot_20170709-170036](https://user-images.githubusercontent.com/29168607/27997553-0ab8ab10-64c0-11e7-8160-855ac8cc2714.png)

**Comment by kskandispersonal** [comment]
Thanks for these screenshots.  For the watch collector, you should enable the G5 BT settings on your watch via XDrip Prefs, not via the xDrip+ Settings.
https://github.com/NightscoutFoundation/xDrip/blob/master/Documentation/WatchGuide.md#xdrip-bt-settings

**Comment by billymild** [comment]
I cannot believe I missed that. So when I enable "Force Watch Collector" I need to go on the watch and change the various BT debug setting. 

When I changed this on the phone it didn't effect the watch at all? Is that correct? 

Any suggestions for a setting to try based on the logs.

**Comment by kskandispersonal** [comment]
Yes, that is correct.  Since BT functionality may be different on each device, the G5 BT preferences are not shared between phone and watch.
Sorry, no, the only pref for sure that much be set is the G5 Authentication for the latest G5 firmware.  It may be that none of the settings will help and perhaps we will need to implement another workaround.  See what you find in your testing.  Thanks!

**Comment by billymild** [comment]
I tried different settings on the watch(sorry don't know how to screenshot it). It appeared that none of the settings worked. Question is now what is the process of testing? I know back in the old days of this app it required a phone to be rebooted. Is that the case for the watch? 

Should I change the xDrip G5 Debug setting then restart collector only? Restart watch?

**Comment by jamorham** [comment]
The Huawei watch is now supported but you will need to apply patches to its rom to make it work correctly. First step is to download the "care pack" I have provided and look at the PDF guide for instructions of how to do it.

https://github.com/NightscoutFoundation/xDrip/wiki/Patching-Android-Wear-devices-for-use-with-the-G5

**Comment by jamorham** [comment]
Using the patch linked above I believe this issue is now resolved.

**Comment by jamorham** [comment]
Marking as resolved.
