### ISSUE TITLE
Compatibility with Android 11

### ISSUE THREAD

**Issue by BluntGoblin** [NightscoutFoundation/xDrip#1450]
I'm using xDrip with Libre1, MiaoMiao2 and Miband4 and my phone is a Pixel3.
Now, Google is in beta testing for Android 11, and the notification is still coming to me.
I'm concerned about compatibility with Android 11.
I'd like you to check the compatibility with Libre, MiaoMiao2 and Miband4 in the Android 11 environment.
Thank you.

**Comment by JeffWickstrom** [comment]
I am using a Pixel 2 XL and a Dexcom G6. Yesterday I upgraded xDrip to 2007131533. This morning I upgraded to Android 11. It is still working fine.

Thank you for your work you guys!

**Comment by Navid200** [comment]
@BluntGoblin Would you please close this issue if your question has already been answered?
If not, your best choice is to use the support channels to consult with the user community.  
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
There are many xDrip users who are already on Android 11.

**Comment by thifs** [comment]
does xdrip (and nightscout) works with  MIUI 12 para POCO, baseado no Android 10 POCO Launcher 2.0   ?? Xiaomi smartphone
