### ISSUE TITLE
Feature request: Better prediction input values based on real time adaptation algorithm values

### ISSUE THREAD

**Issue by user-hash** [NightscoutFoundation/xDrip#1452]
Hi, 
Let me say xDrip is a wonderful project!
I have idea for feature expansion and I think it would greatly improve xDrip overall.
Idea is about predictive prediction of values set in Predictive Simulation settings (carb ratio, insulin sensitivity, carb absorbtion rate), which would be based on real time adaption values xDrip calculates.
You start from default or you personal values and then use xDrip for entering all you carb, insulin and exercise values for x days. xDrip should then write real time predictive values in the database, which could be exported to be analized externally (PC, laptop, pi4) on even on the mobile phone itself, which i think it would be better solution.
 Goal is to get more accurate values for Carb ratio, Insulin sensitivity and Carb absorbtion rate, which could then be feed to xDrip, for the next calibration circle. The values could even be calculated depending on the time in day - morning, afternoon, evening,night.
Any opinion on the idea or if it is feasible anyway?
Thanks!

**Comment by tolot27** [comment]
"Predictive prediction" is repeated unnecessarily and quite confusing. Please can you update the issue title and description by removing these doublings and rephrase it if necessary.

**Comment by user-hash** [comment]
I did change the title, perhaps you can suggest better or not so confusing topic?
Its complicated topic to write about, but I think the author will understand what I meant with the title.

**Comment by tolot27** [comment]
> I would like to suggest to add Total Daily Insulin and Carb intake in xDrip. Could be useful for many calculations

Please open a separate issue for that. Thanks!

**Comment by tolot27** [comment]
> > I would like to suggest to add Total Daily Insulin and Carb intake in xDrip. Could be useful for many calculations
> 
> Please open a separate issue for that. Thanks!

Not necessary. Was fixed with #71.

**Comment by Navid200** [comment]
@user-hash 
There is another, older, issue that requests the same thing.
https://github.com/NightscoutFoundation/xDrip/issues/164
If you believe that what you are asking is different, would you please post in that thread and explain the differences?
Thanks
