### ISSUE TITLE
Incomplete Translation

### ISSUE THREAD

**Issue by ErickRosas** [NightscoutFoundation/xDrip#1454]
I am presenting here a completely new translation to Spanish (I do not know if this is the correct channel).
The old one, although a good effort, was lacking a lot of string and some of them were really incomprehensible (surely done directly using an automatic translator).
Unfortunately, some short strings like:

- Next Retry
- Next Wake up
- Request Data
- etc. 

are embedded deep on java scripts instead of being part of the language resources. This is impeding a complete translation of the program giving an impression of a patch work instead of a neat, professional application. I propose to move them, slowly, but steadily out of the way and where they belong. I am aware that this is a great effort and volunteer to do some of the work if approved (will need precise instructions since my experience with java is limited).
In the zip file I am also including 3 VBS to help translators do their job:

- Find_Diff.vbs: Extracts XML strings from the English resource file and compares them with the language file of your choice. As an output you get those strings not included in the language file that should be appended and translated.
- Strip.vbs: This script strips XML tags removing them from the language resource file of your choice. As an output you get an MS-Word document table and also an auxiliary text file called strip-xx.txt.
- Create_Table.vbs: Makes a table side by side of the English and the language resources files of your choice. As an output you get an MS-Word document table with the strings side by side.

I am also proposing to include an English-xx (x being the target language) glossary on each language so that the user can take full benefit of the xDrip+ author efforts (all the incomprehensible technical babble and acronyms should be clear for the lambda user).
As a last point I will like to thank all for their continuous efforts to make xDrip+ what it has become today: an excellent diabetes app for Android an AppleOS!

[xdrip.zip](https://github.com/NightscoutFoundation/xDrip/files/5288285/xdrip.zip)

**Comment by tolot27** [comment]
Thanks for your contribution. We translate xDrip using the semi-automated workflow system of [crowdin](https://crowdin.com). Please create an account at crowdin and add your suggestions there. Then, they will go through the translation workflow including proof reading.

Regarding to the fixed strings inside javascript, please create an issue for that and link to the corresponding code lines. That would be really helpful and easier to address.

**Comment by ErickRosas** [comment]
Mathias,

Did what you suggested and uploaded the translation there.

Sincerely
Emiliano Llano Díaz

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tolot27** [comment]
@ErickRosas Please can you close this issue if your translations got merged (the crowdin way).

**Comment by Navid200** [comment]
@ErickRosas Would you please respond to tolo27's request?

**Comment by ErickRosas** [comment]
Translation finished and merged
