### ISSUE TITLE
Error receiving too much data

### ISSUE THREAD

**Issue by fennieewongg** [NightscoutFoundation/xDrip#1455]
Hello! I'm using Huawei p30 android version 10 with the libre sensor. This set up used to work fine until recently, the calibrations were very inaccurate and if I tried to delete too many calibrations, or the calibrations that the graph line is on, the whole set-up would fail. Is this normal?? 

It happened again today to my 2 day old sensor and I've tried reinstalling the app a few times but to no avail. I keep getting the error message that says 'error receiving too much data' and it refuses to start up. Any help would be appreciated. Thank you 
![Screenshot_20201002_011825_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/59817719/94842915-86c5c400-044e-11eb-8fc1-98ff367b10c7.jpg)

**Comment by tolot27** [comment]
Please report the xDip version and your hardware environment (which Libre sensor, any bridge like blucon, etc.).

**Comment by fennieewongg** [comment]
@tolot27 hi I'm using libre 1 on Huawei p30. 
![Uploading Screenshot_20201006_203420_com.eveningoutpost.dexdrip.jpg…]()
Attached the screenshot of the version here

**Comment by fennieewongg** [comment]
![Screenshot_20201006_203420_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/59817719/95202190-8f821580-0813-11eb-8502-93fa0aec0052.jpg)

**Comment by Navid200** [comment]
@fennieewongg Would you please close this issue if it has been resolved?
You can use the support channels to ask questions.     
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks
