### ISSUE TITLE
Android 10 (LOS17) no connection to transmitter: "No valid timestamp stored for transmitter: 8K****"

### ISSUE THREAD

**Issue by serserio** [NightscoutFoundation/xDrip#1459]
The connection worked for 9 days now and I received very smooth sensor data, so I guess I don't have a faulty transmitter. Today I tried to extend the sensor life but unfortunately stopped the sensor AFTER I disabled the bluetooth connection. Since then everytime the OB Collector tries to bond with the transmitter, I get the error:

"No valid timestamp stored for transmitter: 8K****"...

...in the log view, and in the system status (2nd page) every 5 min or so it says Scanning Errors. 
Here is what I've tried to fix the problem:

- restarted collector several times
- rebooted the phone several times
- tried to "forget" the transmitter in the bluetooth settings
- deinstalled and reinstalled xDrip+

xDrip+-Version: a91b660-2020.10.01

**Comment by serserio** [comment]
xDrip+-Version: a91b660-2020.10.01

**Comment by Pamalosebi** [comment]
Same here.

**Comment by Pamalosebi** [comment]
I managed to start a new sensor through a modified version of the official app. (remove xDrip+ first!)
See here: [https://www.reddit.com/r/diabetes/comments/fqvmng/oc_build_your_own_dexcom_app_update_base_version/](https://www.reddit.com/r/diabetes/comments/fqvmng/oc_build_your_own_dexcom_app_update_base_version/)

Then when sensor and transmitter are started you can deinstall the app. And finally reinstall xDrip+.
That worked for me... but it is ofc not very elegant.

**Comment by serserio** [comment]
Thanks a lot for your answer! I will try this in the next sensor session. Currently I'm using a different transmitter, but of course it would suck if I had to dump it into the trash after barely 10 days. I will post if it works for me too.

By the way, [this](https://seemycgm.com/2018/06/11/restarting-g6-sensors-and-transmitter/) was what I tried (Option 2 on the site). One time this method worked to restart the sensor, but I guess you shouldn't do it exactly as in the post and never stop the sensor after disabling the bluetooth connection and the collecor, at least I think that was the reason the transmitter didn't want to work no more.

Any suggestions about this topic are appreciated.

**Comment by nicoleloop** [comment]
Nothing? Someone has to know at least some tiny way of getting a G6 transmitter to connect with an android 10 phone! Please? It connects to my bluejay watch, but I cannot find any way to calibrate it through the bluejay watch! And it simply doesn't want to connect to the phone's collector at All. Any help would be so greatly appreciated, anyone? 🙏🙏🙏🙏🙏🙏🙏🙏🙏

**Comment by mk886714** [comment]
If u have the dex Receiver, calibrate on it

**Comment by Navid200** [comment]
@serserio Hi,
Do you still have questions?
There are detail instructions for using G6 on facebook.
https://www.facebook.com/groups/xDripG5/permalink/4838757582864365

There are users who have Android 10 as well as 11.

If you are OK and don't have a problem any more, would you please close this issue?

**Comment by nicoleloop** [comment]
No, I was only confused briefly, I just couldn’t believe it was as easy as it seemed, lol.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by serserio** [comment]
@Navid200 Hi. The problem with the "invalid timestamp transmitter" never got resolved nor did I understand what it actually means. Also I wasn't able to restart a sensor with a fresh transmitter (8K...., Firmware 2.18.2.98.). If that is actually possible, I would appreciate a tutorial on it. I am not on Facebook and can't display the group since it's private, unfortunately.

**Comment by Navid200** [comment]
The invalid timestap log is a symptom of not having proper connectivity established between the device and the transmitter.  It requires correcting the xDrip settings.

To restart a G6, you will need to temporarily remove the transmitter from the sensor without causing damage.
Detail instructions are available in the facebook group.

I understand that not everyone likes to create a facebook account and join the group, which is very simple to do.  So, I am looking for options to bring the documentation out of facebook so that everyone can access it.  Have no idea when/if that will happen.

**Comment by Navid200** [comment]
If you need help restarting a sensor, or if you still get the timestamp error, please either post in the facebook group or in the Gitter room.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

**Comment by tolot27** [comment]
The invalid timestamp issue will be discussed in #1778.
