### ISSUE TITLE
Xdrip + Android Wear (Sony Smartwatch 3)

### ISSUE THREAD

**Issue by Dusikus** [NightscoutFoundation/xDrip#1462]
Hello! Where can I get Xdrip + version for android that works with Android Wear. In the last version that I have now, it is not supported. Want to use it with Sony Smartwatch 3. Thanks in advance for your help.

**Comment by tolot27** [comment]
Which version of xDrip did you install? Please post just the version information, no screenshot.

**Comment by tolot27** [comment]
@Dusikus Is your question answered? If yes, please close this issue.

**Comment by Navid200** [comment]
@Dusikus Please use the support channels for asking questions.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks
