### ISSUE TITLE
Dexcom Share to both EU and US servers at the same time.

### ISSUE THREAD

**Issue by flango** [NightscoutFoundation/xDrip#1464]
Hi, is it possible to get xDrip to be able to share to both US and EU servers at the same time?
I had to use xDrip to be able to share with my american friends, i live in europe.
But I would love to be able to share with my European friends too.
Can you please enable Dexcom upload for both EU and US servers at the same time, it would be amazing to not feel segregated like dexcom want the world to feel.

**Comment by tolot27** [comment]
@flango Currently, this is not possible. I've tagged your feature request as an enhancement.

**Comment by flango** [comment]
Thank you, it would be amazing if that ended up being possible.

**Comment by Navid200** [comment]
Would you please explain the problem?

If the follower knows which server the master is uploading to, can they not use that same server to follow?
Why does it matter where followers are located?

**Comment by tolot27** [comment]
It is better to use Nightscout to achieve this. It is very unlikely that it will ever be implemented.
