### ISSUE TITLE
Samsung watches

### ISSUE THREAD

**Issue by jo1st** [NightscoutFoundation/xDrip#1468]
Hello everyone. It has been a while. Always thank you for the hard work. I was wondering if there is the hope to implement natively Samsung watches support. I noticed that currently the watch support has increased a lot but still no Samsung. Any hope for some of you guys to find an option??? After all Samsung watches are very popular. Thanks

**Comment by eurenda** [comment]
Have you checked out Juraj Attal's G-Watch Service?  It depends on a
service companion app on your phone, but currently can show xdrip data and
AAPS data on the watch face including carbs, IOB, basal, and pump data.

I'm not sure he's received enough feedback from community, currently it
simply displays information, it cannot send pump commands like the WatchOS
watchfaces can, but perhaps with some feedback he may be willing to
incorporate.

Currently use it with my Galaxy Watch Active 2 and it works.

I thought I saw a #tizen-dev channel on discord, but it no longer seems to
be there.

**Comment by jo1st** [comment]
I thank you very much, installed it, followed all instructions but not
receiving levels from xdrip unfortunately. Note 20, Samsung watch

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by eurenda** [comment]
> I thank you very much, installed it, followed all instructions but not receiving levels from xdrip unfortunately. Note 20, Samsung watch 

I'm using it on a Note 20 with Active 2 watch, make sure you read instructions, I believe I had to add an identified receiver in xdrip+ under Inter-app settings , I have an entry there showing sk.trupici.g_watch which makes it work

![Screen_20201017_134410](https://user-images.githubusercontent.com/1902827/97092181-acca2880-15f6-11eb-9c8f-04290b14424f.png)

**Comment by jo1st** [comment]
actually is working now. thank you very much

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by tolot27** [comment]
As it is working now, I close this issue.
