### ISSUE TITLE
Phone Battery Level is sent to AAPS instead of Sensor Battery Level

### ISSUE THREAD

**Issue by Philoul** [NightscoutFoundation/xDrip#1469]
Hi,

I wanted to add Sensor battery level in AAPS User Interface, but I was a little bit disappointed to find "Phone Battery Level" instead of "Sensor Battery Level" behind key ```com.eveningoutpost.dexdrip.Extras.SensorBattery```...  (currently this value is not used in AAPS, that's why this bug was not detected earlier...)

See screenshot below (Sensor Battery Level 75, Phone Battery Level 97) and extract of Log captured in AAPS...

![Screenshot_20201017-102718_xDrip+ 1](https://user-images.githubusercontent.com/52934600/96332460-5f811080-1064-11eb-950c-a0e3834530a3.jpg)

2020-10-17 10:20:49.259 ? D/BGSOURCE: [IntentService[DataService]]: [XdripPlugin.handleNewData():42]: Received xDrip data: Bundle{ ...; com.eveningoutpost.dexdrip.Extras.SensorBattery => 97; ...; }Bundle

Note: detected with xDrip Nightly build 1st Oct 2020

**Comment by Philoul** [comment]
I'm not a specialist of xDrip code (I'm working on AAPS code...) but after a quick analysis, I suspect line 115 of BroadcastGlucose.java file:

May be 
```bundle.putInt(Intents.EXTRA_SENSOR_BATTERY, PowerStateReceiver.getBatteryLevel());``` 
could be replaced by something like
```bundle.putInt(Intents.EXTRA_SENSOR_BATTERY, BridgeBattery.getBestBridgeBattery());```

(not tested, it's just what I suppose after 1 hour of research into xdrip code)
=> If you think it's correct, I can make a PR if it could help...

**Comment by tolot27** [comment]
@Philoul Please create a PR. You analysis seem to be correct. @jamorham can review the PR.

**Comment by Philoul** [comment]
Thank's for your comment...
PR done.

**Comment by Philoul** [comment]
Do you think this PR could be included in the next nightly build version? I think proposed fix is simple with very few risks...
=> I did my PR on the Master branch two weeks ago, I don't know if it's the right way to do it on the xdrip + project because nothing has changed on this branch for a month, and I didn't find a "dev" branch like on AAPS project ...
Thank's
