### ISSUE TITLE
Compatible with new Medtronic 780G

### ISSUE THREAD

**Issue by iwanvandaele** [NightscoutFoundation/xDrip#1473]
Is xdrip + compatible with the new Medtronic 780G pump and Guardian Sensor 3?

Thx

**Comment by tolot27** [comment]
No, it isn't and no one is working on it, currently.

**Comment by iwanvandaele** [comment]
Ok thx for the answer, it's a pitty because xdrip is a real good app!

**Comment by tolot27** [comment]
You can decrypt the bluetooth communication protocol or create a patched app which sends the data do xDrip, if you like. Support is always welcome.
We are only very few active developers with limited time.

**Comment by michaelholderman** [comment]
I would love to help figure out how to get Nightscout to work with the 770/780g and Carelink. I have been using Nightscout for years with the 670g and also with the Guardian Connect system and now have a couple of 770g systems that I can use to test. Just not sure where to begin. Is there someone that has worked in this in the past that I could reach out to?

**Comment by tolot27** [comment]
Related to/duplicates #131

**Comment by Navid200** [comment]
Can we close this as a duplicate?
https://github.com/NightscoutFoundation/xDrip/issues/131

**Comment by tolot27** [comment]
Yes, it is a duplicate of #131.
