### ISSUE TITLE
Upload exercise data like step count to Tidepool

### ISSUE THREAD

**Issue by tolot27** [NightscoutFoundation/xDrip#1476]
@jamorham @pazaan Would it be possible for xDrip+ to send step count to Tidepool?  Does Tidepool support steps in its app?  xDrip+ displays steps graphically on the home screen (and History screen), allowing users to see the correlation between exercise and BGs. This would be a great feature on the Tidepool webapp.  Thank you!

_Originally posted by @kskandispersonal in https://github.com/NightscoutFoundation/xDrip/issues/581#issuecomment-459136952_

**Comment by tolot27** [comment]
@pazaan Is this exposed by the tidepool API and visualized in the web app, meanwhile?

**Comment by pazaan** [comment]
Tidepool's API has an `exercise` data type, but it is currently not rendered at all in the Web UI.

**Comment by tolot27** [comment]
@pazaan Are there any plans to implement this? If yes, can you link the issue here?

**Comment by pazaan** [comment]
https://tidepool.atlassian.net/browse/WEB-106
