### ISSUE TITLE
Logs show calibration has been accepted followed by cal has been deleted

### ISSUE THREAD

**Issue by Navid200** [NightscoutFoundation/xDrip#1478]
xDrip version: 67014b0-2020.07.25

G6 transmitter: 8J
Android 9
Motorola

I have unchecked Double Calibration under Settings, Less common settings, Advanced Calibration.
When I have needed to calibrate, I have used Initial Calibration under the top left menu (3 horizontal lines).

After entering the calibration, the readings on main screen show an impact.
But, the logs show: Calibration accepted by transmitter" in green.  And another log following in red: "Calibration with ID: *** appears to have been deleted".

Is the calibration successful?  Why is the red log present?

I can show an example of this issue in the facebook group:
https://www.facebook.com/groups/xDripG5/permalink/4494106780662782/

**Comment by tolot27** [comment]
As @Navid Fo mentioned at facebook:

>You haven't stated what transmitter you use.
>G6 with a serial number that does not start with 80 or 81 does not send raw data, which results in an empty calibration graph in xDrip.

**Comment by Navid200** [comment]
> As @navid Fo mentioned at facebook:
> 
> > You haven't stated what transmitter you use.
> > G6 with a serial number that does not start with 80 or 81 does not send raw data, which results in an empty calibration graph in xDrip.

I'm not sure what you mean by that.
The transmitter is a Dexcom G6 with 8J being the first two characters of the serial number as stated in my original post.

**Comment by Navid200** [comment]
There are some issues with the xDrip logs and messages since the G6 transmitter firmware updates by Dexcom.
I am closing this as it is a known behavior, which hopefully will eventually be resolved.
