### ISSUE TITLE
Spoken reading for partially sighted users

### ISSUE THREAD

**Issue by jamorham** [NightscoutFoundation/xDrip#148]
I received the following request via email, please comment and suggest the best ways this could be implemented.

>xDrip is really easy to use with my Dexcom G4, BUT, I am starting to lose my sight and would really love to have a speaking version.
 
>I know that xDrip+ will speak the reading every five minutes, but that would drive you mad if it was running 24 hours a day.
 
>What would be great is an easy way (maybe press & hold the home button) to hear my blood glucose reading PLUS the trend
 
>For example, I press & hold the home button and hear ‘6.7  Falling’.
 
>I wonder if this is something you may consider for a future release?

**Comment by AdrianLxM** [comment]
One candidate would be the `ACTION_CAMERA_BUTTON`.
On my phones I can add a gesture (on lineage under the setting "Gestures" with a hand/finger symbol. There are two settings called "Gestures") to start the camera. I hope this can be captured by xDrip if it has the Camera permission and an intent filter in the Manifest.

**Comment by doc77** [comment]
Could this be solved with a tasker profile, maybe with a swipe action, preprogrammed by the xDrip+ app?

**Comment by tzachi-dar** [comment]
I know that some android phones have extra buttons that can be used.
We might also do it using something like "shake to unlock" application.

Tzachi

**Comment by MasterPlexus** [comment]
Also maybe a button of a smartwatch can be used as a trigger (like the snooze app for the Pebble).

Not really the scope, but getting the idea, just to make additionally the trigger if a alarm happens, to let speak what is the alarm.

**Comment by jroth-haj** [comment]
What about a additional Widget to get the bg spoken?

**Comment by themotoden** [comment]
I think, Tasker can do this and much more, if add maximum possible features to xDrip+. In my opinion this will be the best way to develop the program. Each user can choose what he needs

**Comment by jamorham** [comment]
I think the tasker feature is a good idea. Another widget could also be useful. Once tasker support is added it is easy enough to just create a tasker app to do the same thing. I will be working on the tasker support shortly.

**Comment by themotoden** [comment]
This is great news!  Thank you!

**Comment by jamorham** [comment]
The Jan 1st Nightly includes Tasker support for speaking the current reading, switching speaking readings on/off and also switching speaking of alerts on/off. See the `SPEAK ON` configuration button from tasker 3rd party plugins and the other related ones. Please let me know if this works okay.

**Comment by doc77** [comment]
@jamorham Tested them all and they work great! Thanks!

**Comment by jamorham** [comment]
marking as resolved
