### ISSUE TITLE
Ability to start libre 1 sensors (xDrip+bubbleDevice)

### ISSUE THREAD

**Issue by Archibald-rgb** [NightscoutFoundation/xDrip#1480]
To start libre 1 sensor i need to launch another application and start sensor from there.

**Comment by tolot27** [comment]
You have to ask the bubble developers to integrate this feature. As long as it is not supported by the bubble device, it cannot be supported by xDrip.

**Comment by Archibald-rgb** [comment]
But they have own app with this possibility. And i was hoping they get read my question.

**Comment by tolot27** [comment]
Please provide a link to the app. Why not contact them directly?

**Comment by Archibald-rgb** [comment]
https://play.google.com/store/apps/details?id=com.outshineiot.diabox&hl=en_US&gl=US
I do not know how i can do that.

**Comment by tolot27** [comment]
@Archibald-rgb 
> I do not know how i can do that.

Just send them an e-mail. The address is listed at the Google Play page you have linked.

**Comment by bubbledevteam** [comment]
public static BridgeResponse getBubbleStart() {
        final BridgeResponse reply = new BridgeResponse();
        ByteBuffer ackMessage = ByteBuffer.allocate(3);
        ackMessage.put(0, (byte) 0x05);
        ackMessage.put(1, (byte) 0x01);
        ackMessage.put(2, patchInfoByte[0]);//patchInfo first byte support 0xDF(libre1) and 0x70 (libre pro/h)
        reply.add(ackMessage);
        return reply;
    }
    //response buffer   850101a538e400
           int first = 0xff & buffer[0];
            if (first == 0x85) {
                int status = 0xff & buffer[3];
                    --A3=not running,
                    --A4=starting,
                    --A5=running,
                    --A6=expiring,
                    --A7=expired,
                    --A8=broken(permanent error)
                }

**Comment by tolot27** [comment]
@bubbledevteam Please can you provide a PR or describe the source code briefly? It doesn't look like compilable.

**Comment by Navid200** [comment]
@Archibald-rgb Looks like your issue is with an app other than xDrip.
Can we close this issue please?
Thanks
