### ISSUE TITLE
xDrip not receiving IOB data from Nightscout

### ISSUE THREAD

**Issue by JimZam** [NightscoutFoundation/xDrip#1481]
Good morning. Till now I could see IOB and pump data in the Extra Line of xDrip, but suddendly it has dissapeared. xDrip (last nightly build, October the 1st) receives treatments (bolus and carbs) from Nightscout but not basal (there is no blue line on top). I haven't changed anything for a long time (at least in xdrip; I upgraded to AAPS 2.7 a couple of days ago). I've even installed a variant just with my heroku address and it's the same. I've no idea what can happen, any help is welcome.
Thank you in advance

Edit: maybe it's and AAPS issue, I've Local Broadcast enabled in AAPS so data should be received from Nightscout or AAPS...

**Comment by tolot27** [comment]
What version of xDrip did you use before? Does it work again, if you downgrade to that version?

**Comment by JimZam** [comment]
Hello. It seems to be related with the AAPS update, I've asked in their github page and I'm not the only one with this issue.
Thank you so much
Regards

**Comment by tolot27** [comment]
@JimZam Please can you link the correlating AAPS issue, here?

**Comment by JimZam** [comment]
Of course:
https://github.com/nightscout/AndroidAPS/issues/46

**Comment by Navid200** [comment]
@JimZam Looks like this issue has to do with AAPS and not xDrip.
Can we close this issue here then please?
Thanks
