### ISSUE TITLE
"SENSOR NOT FOUND"

### ISSUE THREAD

**Issue by Marcio261** [NightscoutFoundation/xDrip#1487]
Did anyone ever received this message?
I changed my sensor today, and also replaced miao miao. I did everything same as always, but today it gave me this error(the sensor is working fine on the libre monitor) and i don't know why. Can anyone help me? Thanks

**Comment by Marcio261** [comment]
![Screenshot_2020-10-27-17-21-41-104_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/59709015/97338101-017cd600-1879-11eb-9e7d-e2f685463488.jpg)

**Comment by tzachi-dar** [comment]
Make sure miaomiao is very tight to sensor.
Try also resetting the miaomiao.

בתאריך יום ג׳, 27 באוק׳ 2020, 19:22, מאת Marcio261 ‏<
notifications@github.com>:

**Comment by Marcio261** [comment]
Yeah, it was the first thing i did...reset and i make sure that it is well placed( i also have a holder band to make sure that the sensor and the miaomiao don't fall).
The only 2 situations that xdrip registed something was when i putt pressure on miaomiao and the sensor, but for the next minutes stoped again :(

**Comment by tolot27** [comment]
It looks like a problem of the sensor in combination with Miaomiao and not related to xDrip.

**Comment by Marcio261** [comment]
Yeah, i'm starting to think so... Well, i will wait for the Next sensor use.
Thank you for the help
