### ISSUE TITLE
Xiaomi Android 11 with G6 connection barely working

### ISSUE THREAD

**Issue by gfornax** [NightscoutFoundation/xDrip#1488]
Hi, I recently had to switch my old phone (where xdrip was working perfectly) to a xiaomi note 10, which I flashed with the latest EU ROM using Android 11.
Initially, xdrip was working ok for a few hours. Then I started getting error like "could not register app for bluetooth scanning" or no error, just shows scanning and nothing happens. 
Xdrip has full permissions and all battery optimizations are disabled.
The G6 transmitter is even listed in the bluetooth devices as bonded in Android, in xdrip it says connection status "Dexcom0L Authed". Weird...

What I tried so far was of course rebooting and rebonding the device (which sometimes helps for 1-2 readings), and also playing with the extended bluetooth settings. 
What also seems to help for a while is hitting "forget device" and "restart collector" just right before the 5min interval happens.
Unfortunately, nothing fixed it permanently so far.
Any hints how to get it running again?

**Comment by gfornax** [comment]
Short update: I managed to keep it running for several hours by syncing the manual action "forget device" + "restart collector" to right before the G6 interval - it works as long as the connection is not interrupted or they drift "out of sync".
So I guess the issue is that the "scanning" state of the collector can't be kept up for more than a few seconds - if there is no response from the G6, it stops working.

**Comment by gfornax** [comment]
Another update to probably narrow it down:
When the problem occures, the "Phone Service State" always cycles through everything normally but then stops at "Authenticated".

In this case, the event log shows this error:
`Error receiving indication: java.util.concurrent.TimeoutException: The source did not signal an event for 6 seconds and has been terminated`.
Sometimes the value for seconds changes a little, but this seems to be the characteristic error.

Other entries like the `Could not read reply to auth challenge` and `Could not read after AuthRequestTX` are always there, also after a successful read.

**Comment by tolot27** [comment]
Do you have Samsung Workarounds enabled? If yes, please disable it.

**Comment by gfornax** [comment]
I tried both and could not note any difference.
But I found another factor: Using the original Dexcom transmitter in parallel usually instantly triggers the issue as long as it is running, probably due to the additional processing time.

**Comment by tolot27** [comment]
@gfornax If you still have trouble, please ask for support at https://www.facebook.com/groups/xDripG5 or https://gitter.im/jamorham/xDrip-plus.

If it is solved, please close this issue.

**Comment by gfornax** [comment]
Okay, not exactly solved but after some messing with the bluetooth stack it went down from frequently to about weekly.
So I guess there is still an issue somewhere, but the impact is not that critical anymore.

**Comment by JimmyFoks** [comment]
I have the same problem, it is repeated once a day. Is there a solution?
