### ISSUE TITLE
Force collection on smartwatch does not work on any watch except Sony Smartwatch 3

### ISSUE THREAD

**Issue by Vaughanabe13** [NightscoutFoundation/xDrip#149]
Based on my own experience with 5 android wear watches and everyone else's experience documented in the facebook group, I have come to the conclusion that there is only one single watch that works when running the collector service, and that is the Sony SW3. I have also tried the original Moto 360, Moto 360 Sport, Moto 360 v2, Zenwatch 2, Zenwatch 3, and Zenwatch 3 after upgrading to Android Wear 2.0. Other reports say that it does not work on the huawei, the nixon, LG sport, urbane, etc. 

While they all work with xdrip as a regular watchface viewer, none of them except the SW3 will get readings at all. Every indication on my ZW3 right now shows that it is working - watch is listed correctly in the xdrip app settings, force collection is enabled, location permissions are enabled on the watch, all the settings between the phone and watch match up, Dexcom shows up in the bluetooth settings menu of the watch, Android Wear is listed as the collector both on the watch and phone, etc. But no readings ever come in, even after hours of waiting. Tried multiple restarts of both phone and watch, tried leaving the phone off or in airplane mode. Tried toggling scan constantly and wake screen before reading options. Tried toggling aggressive service restarts. Tried manually restarting the collector.  I even factory reset the watch twice. Nothing works. 

I am hoping someone working on the code can work on this further because to me, being able to run the collector service on my watch is the single most important thing about the app and I know others feel the same way. Apple/Dexcom is now catching up because the Apple Watch will be able to function as a standalone collector with the G5 now.  For now I will continue using the Smartwatch 3 but I don't think it is a good solution for the future since the SW3 can only be bought through ebay and old stock that is quickly running out, and there are other issues with that watch such as the nasty battery drain bug.

I understand this will probably be a challenge to figure out why the other watches aren't working. I would even be willing to send my zenwatch 3 to a developer who is serious about working on it. I think it is that important for the future of the G5 and xdrip.

**Comment by kskandispersonal** [comment]
Thanks for the feedback.  Yes, each wear device seems to use a different BLE implementation.  There are a few other watches that seem to work well as the collector, including the LG Urbane and the original Zenwatch.  I haven't tried them myself though.  I agree, support for the newer watches, esp w/ Wear 2.0, should be added.  It is a TODO but unfortunately, I am not able to address it right now.  If other dev members have time and would like to investigate the issues, maybe they can contact you if you are still willing to provide the Zenwatch 3 temporarily for dev.  I, myself, only have the SW3 (two of them) but to find workarounds for a specific watch, I do think the watch will be required as a lot of debugging will most likely be required.

**Comment by Vaughanabe13** [comment]
You say the Urbane works, but I see reports in the xdrip G5 facebook
community that say the LG Urbane does not work as the collector. Multiple
reports say it doesn't work if you search the group.  I'm hearing the LG
Urbane 2nd edition doesn't work either: " I'm using the Urbane 2nd edition
paired with phone as collector, but I've not been able to "connect"
directly from watch to transmitter. Bluetooth report on watch shows Dexcom
as "disconnected"." Another post on March 31 from Richard Sample has
multiple people confirming the LG Urbane 2nd edition doe not work. I don't
see any comments at all on the group about the zenwatch (original), only
the zenwatch 2 and 3 which both don't work. It could be that these posts
were all from a time when the software was immature, I don't know. But
there isn't a single post I can find from anyone who had success on any
watch except the Smartwatch 3.

I'm willing to send the zenwatch 3 or an original moto 360 that I have
laying around and can't use (since only my SW3 works) if anyone wants to
work on it. Just send me a message and I'll ship it to you.

**Comment by jamorham** [comment]
I've tried a number of things with the zenwatch 2 including even changing the bluetooth chip firmware but I haven't been able to resolve the core problem yet which is that after bonding the g5 transmitter doesn't agree with the bonding parameters.

The next steps are to look at the really low level bluetooth data exchanges, but its rather complicated and even if that shows why its not working it may still not allow it to be fixed. I am expecting if it is fixable then it may require for example a custom modified rom being flashed to the watch to make it work.

It might work with pre-nov-2016 g5 transmitters which were less strict about the bonding but I don't have one of those to test with.

**Comment by Vaughanabe13** [comment]
Thanks so much for working on it. I personally wouldn't have a problem
loading a custom ROM on my watch if that's the only way to make it work. At
least a working solution could be explored and ported to other watches and
potentially updated over time.

**Comment by jamorham** [comment]
Okay, I have produced a rom patch for the Zenwatch 2 which makes it work with the G5. I may well be able to repeat this process for other smart watches but it is fiddly and I only have a Zenwatch to experiment with at the moment.

**Comment by lskeele1** [comment]
How would one get the rom patch for ZW2?  I have one, and I'm very eager to make it work as an independent collector from the phone. I love this project!

**Comment by jamorham** [comment]
Patching the Zenwatch2 to work with the G5, PDF guide -> https://drive.google.com/open?id=1lPpjkiyiASLThoYFDpL9Pfor4fW3-4OK

All the required files in a care package zip file: https://drive.google.com/open?id=1Gk_Fbi98AkjLmSBTmVJ7_pq9dy7xF7Ld

Please let me know how you get on with this. If you're using windows instead of Linux then you will need to get set up with the ADB and FASTBOOT tools there as well as probably get universal adb drivers installed. I am slightly hazy on this process and it needs documenting in the guide.

**Comment by jamorham** [comment]
Oh and you should use any xDrip+ from the 23rd Nov nightly onwards as this has the updated wear component which can take advantage of the system level permissions on the patched zenwatch.

**Comment by lskeele1** [comment]
Thanks!  Traveling now, but will give it a try when I get home and let you know how it goes.

**Comment by jamorham** [comment]
I've also now produced a patch for the LG G Watch (W100)

Patching the LG Watch PDF Guide: https://drive.google.com/open?id=1pgabdYX-vMjSjyb0G5jbgoTko9gJxxCT

All the required files for the LG g in a care package zip file:  https://drive.google.com/open?id=1z2ovSF66V_k7H49Wi_VHuBqPi0_2xpwk

**Comment by lskeele1** [comment]
Reporting success on patching the Zenwatch 2!  @JamorHam, you’re amazing!  Here’s my report, in case you find anything helpful.  First the good: My watch (I have the smaller version of the ZW2) has a near 100% collection rate.  I initially tried to patch with Windows, but couldn’t seem to find the right drivers, so I switched to my RPi3.  (I had previously manually updated to Wear 2.0 on Windows, but something was not working right on this one.  As far as instructions go, though, I found this to be helpful in terms of getting ADB and Fastboot to work with Windows: https://www.androidsage.com/2016/03/04/install-marshmallow-ota-for-asus-zenwatch-2/.)  Anyway, back to my update.  Using my RPi3, I followed JamorHam’s instructions, and the patch worked well.  A few notes: First, I used the command line rather than the swipe to boot into Fastboot mode.  When I did, the watch said, “Fastboot Mode” rather than “Fastboot CSC.”  Not sure, but I think this may be a difference in the international version of the watch.  When I tried to unlock the bootloader, it told me that the bootloader was already unlocked.  (Maybe this was from sideloading the OTA update to Wear 2.0?)  I did not get a message on the watch screen about unlocking the bootloader, and the watch did not do a factory reset during this process – it retained my data.  Everything else went according to the instructions.  I uninstalled and reinstalled xDrip+ on the watch, and on the phone.  The only other difference (related to not doing a factory reset) was that my watch didn’t do a fifteen-minute initial boot – it was a normal restart.

Now, the minor inconveniences.  After one day of use, I’ve had very significant decrease in battery life on the watch.  It hopefully won’t be a huge deal, because I plan to use my phone as the primary collector, and the watch only as a backup.  But the other problem is that I can’t seem to get the phone to be the collector.  My Sony SW3 shifts back and forth seamlessly between the watch and phone.  But, when I try to make the phone (Moto G4) the collector, it just misses readings until I set the watch to be the collector again.  Also, it appears to be draining my phone battery.  Note that, when I patched the ZW2, I also updated to the Nov. 24 nightly build.   I’ve noticed that, in this build, some of the Bluetooth settings are checked that I don’t think were checked before (though I’m not sure): Bluetooth Wakelocks and Close GATT.  I’m going to play around with these settings, and also “Try the new OB1 G5 Collector” to see if I can get this solved.  Thanks again for your work on this!

**Comment by Vaughanabe13** [comment]
I would love to know what settings you have on your ZW2 that may be
impacting battery life. For example, do you have gestures and tilt to wake?
Do you have ambient display enabled? Brightness? Etc.

Great work, I think this is awesome progress! Unfortunately I think battery
life will always be a concern but with improvements in the new processors
and hardware configurations that might be partially mitigated.

**Comment by Vaughanabe13** [comment]
Just an update: I sent jamorham 4 more watches to patch. He is doing great work.

Zenwatch 3
Fossil Q Founder 2.0
Polar M600
Moto 360

**Comment by jamorham** [comment]
@lskeele1 great to hear that you've been able to repeat my process and apply the patch to the zenwatch. I recommend using the OB1 collector and I would hope that this would use less battery than that classic collector

**Comment by lskeele1** [comment]
OB1 Collector is working better.  After most of a day, battery life is much better than before, and the phone and watch are now switching properly when I check/uncheck the "force wear" box.  (It usually misses about two readings during the transition, but that's no big deal to me.)  Both watch and phone look as if they will easily make it one full day, which is all that I'm looking for.  @Vaughanabe13, I keep ambient display on because I want to view my glucose level quickly, and I've found that waking the screen takes a half second or so.  Other than that, normal settings: brightness 3, no gestures, but yes tilt to wake.

**Comment by Vaughanabe13** [comment]
Very interesting, thanks. Yes I agree that it's helpful to have ambient
display on. I was hoping that was the case and that you weren't getting
terrible battery life with the display off. It sounds like the OB1 is
working great. Very excited to try another watch finally!

**Comment by Shuralon** [comment]
Can i help somehow to get the Huawei Watch Active working?

**Comment by jamorham** [comment]
@Shuralon can you give the exact watch model number?

**Comment by Shuralon** [comment]
In the settings it just says "Huawei Watch", so i guess the first gen all have the same hardware just the style is different. https://www.gsmarena.com/huawei_watch-7687.php

**Comment by jamorham** [comment]
@shuralon is there anything written on the back? How technical are you, do you have access to a linux device like a Linux PC or Raspberry Pi? Would you be confident to do some guided investigative work to examine its internals using android development tools?

**Comment by Shuralon** [comment]
In the back its just "Huawei Watch" again. I'm studying Computer Engineering so I have access to a linux PC and a RPi. Would like to do that, just tell me what to do.

**Comment by jamorham** [comment]
@Shuralon ok drop me an email  jamorham at gmail or do a private chat on gitter and I can give you more detailed instructions without cluttering this issue ticket

**Comment by jamorham** [comment]
List of watches currently supported:
https://github.com/NightscoutFoundation/xDrip/wiki/Patching-Android-Wear-devices-for-use-with-the-G5

I have recently added the ZenWatch3 and Polar M600

**Comment by kretch** [comment]
Which watch ( except sw3) with lte connectivity works with xdrip+ as standalone collector and nightscout uploader?

**Comment by Vaughanabe13** [comment]
kretch, developer jamorham has been working on adding additional watches that work as the standalone collector with xdrip+, however the other watches do require some work to patch the bluetooth. If you go to the post above yours you will see he added a link with the supported watches that he was able to get working so far. I hope that helps.

**Comment by kretch** [comment]
Thanks! I looked at the list but didn't see any watch there that has Cellular connectivity

**Comment by jamorham** [comment]
@kretch is there a particular watch you would like it to work with?

**Comment by kretch** [comment]
@jamorham Either the huawei  2 with 4g,or the LG urbane 2 with 4g- both use
the Snapdragon 2100 soc

**Comment by IslePilot** [comment]
@jamorham Do you know if the Fossil Gen 3 Q Venture will ever be on the list?  I just got one for my wife and I would love to get it set up for her.  Thanks.

**Comment by kellestyle** [comment]
@jamorham I second the question on the fossil gen 3... I'm "following" dex running from android wear app on iPhone and it says "this device isn't supported" when i try to download the app to the watch
I thought all android wear devices can run the apps from google play store, but apparently not fossil. I love the watch-but need the thing to work with nightspot or follow. help!?

**Comment by jamorham** [comment]
@IslePilot @kellestyle I only have a Fossil DW2e to work with at the moment - I am assuming this is a different watch? If someone is willing to send me a watch to work with (which I will send back when complete) then there is a chance I can produce patches for it as has been done with other watches.

I have absolutely no idea what would happen with running xDrip watch face on android wear connected to iphone. I think you can run the watch stand-alone if it is sometimes near to an android wear device (or using wifi/cloud connection) but I don't know how you'd side-load xdrip on to a watch connected to apple device and crucial features - eg calibration are not present on the watch-face and it needs a companion handset somewhere to achieve that.

**Comment by ldkbyj** [comment]
@jamorham Thank you for your effort. Do you have a plan for LG Watch Sports (androind wear 2.0) ?

**Comment by kellestyle** [comment]
I returned it, just too much trouble! Thank you for the kind reply! 

Kelle Carthey, RN 
Director of Nursing Services
Brothers Healthcare

**Comment by siblues** [comment]
Please excuse my very simple question but when you are talking about force collection on the watch does that mean the watch is receiving the G5 readings on it's own without the phone?I need a watch that can receive the readings without needing the phone nearby.I am unable to have my phone on me at work and I may need to resign if I can't find a work around.Thanks

**Comment by ldkbyj** [comment]
@siblues  I think you need Sony Smartwatch 3 or below watches.
https://github.com/NightscoutFoundation/xDrip/wiki/Patching-Android-Wear-devices-for-use-with-the-G5

**Comment by Klaus3d3** [comment]
Hi guys,

can anyone of you having a pazched watch other than th sony, can tell me if the collector is reliable with the blukon? I can't get my Sony to work properly. Only in forced mode, it collects sometimes something. If it's in the "Phone out of range" mode, it just does nothing.

**Comment by jamorham** [comment]
@keencave any reports about blucon with patched watch? for @Klaus3d3

**Comment by no1jeeves** [comment]
Hi ladies and Gents, 
Does anyone know if the Nixon Mission SS watch is compatable as a collector?, it is as far as I have found the only one with 10ATM water resistance, and recommended for swimming and surfing, others that are IPX8, or IP68, are not recommended for these activities as per the standards they are tested too, Thanks

**Comment by borijess** [comment]
I have a Polar M600 that I patched. Was working great but I rebooted and factory reset watch. My question is do we have to patch every single time I reboot watch or factory reset? Or is the patch permanent?

**Comment by lskeele1** [comment]
I just bought a Verizon Wear24 because it was cheap on major clearance.  Has anybody tried using one as a forced collector (I just got it today, and no luck so far)?

**Comment by Vaughanabe13** [comment]
Personally I wouldn't even bother with the wear24, it's a highly flawed watch that's already on its way out and won't be available soon.

**Comment by Antonio2001** [comment]
Good evening from Spain. I have several questions that probably you can answer... I have a Dexcom G4 + xbridge. Does all this apply to it? The link says "Patching Android Wear devices for use with the G5":
https://github.com/NightscoutFoundation/xDrip/wiki/Patching-Android-Wear-devices-for-use-with-the-G5
Does Pebble work as a standalone collector? I suppose it doesn't but I can't find anywhere the answer (although there isn't a "Collection Service" option in xdrip+ for it)
And which smartwatch would you recommend? Sony Smartwatch 3 has batttery problems, Moto 360 doesn't keep the screen always on. Any suggestion?
Thank you so much in advance
Regards

**Comment by Vaughanabe13** [comment]
Pebble does not work as the collector, nor do watches from other manufacturers like Garmin, unfortunately. The Pebble can be used as a secondary display for glucose but you would still need a collection device (phone or watch or receiver).

Currently I am using the Zenwatch 3 as my main collector device and I would say it's not quite the best experience, but it's probably good enough in most scenarios. The collection rate is pretty good, battery life is pretty good and easily lasts a whole day, screen quality is nice and the watch as AW2.0. I don't use my watch a lot except for basic notifications and texting, and I end up with about 30-50% battery at the end of a long day when running the collector all day. I then charge my watch on the night stand while I'm sleeping and then use my Pebble for vibration alerts while I'm sleeping (if BG gets out of range). So for me the battery life on the ZW3 is good enough with the screen always on, but if I were using the watch heavily all day, battery life might drop more and I would be less comfortable making it through a whole day without charging.

Comparing the ZW3 and the Sony SW3, I think the Sony probably does a better job functioning as the collector. It works out of the box without any modifications, the collection rate is higher than the ZW3 and very stable with very few dropouts, and because of that it feels more reliable. I also like that you can leave the display always on but disable the backlight. I think my battery life ends up being about equivalent to the ZW3, however in bright sunlight the SW3 is much more readable thanks to the transflective display. With my ZW3 on auto-brightness, I have to tap the screen to wake it up so the display can brighten enough where I can actually see it in daylight. That backlight usage can drain battery quickly if you are in the sun all day, so the SW3 wins that battle. However, the SW3 screen quality is not very good indoors and has an ugly yellow tint to it, compared to the beautiful AMOLED display on the ZW3. Also the SW3 has better waterproofing, although I wouldn't consider it a waterproof watch because the screen has been known to leak when fully submerged. But I would trust it more than I would trust the ZW3, which is not waterproof at all.

I would not suggest the moto 360 if you want a watch that you can leave the display always on. The processor is slow and the battery is bad.

So I guess my current recommendation would be go with the SW3 if you are primarily outdoors or near water, and go with the ZW3 if you spend more time indoors or in an office environment.

**Comment by Antonio2001** [comment]
Thank you so much for your quick and really enlightening answer, Vaughanabe13.
Kind regards

**Comment by lskeele1** [comment]
@jamorham I originally used the smaller ZW2 (without the speaker) for this process.  I recently got the larger version (with the speaker), and was able to modify it to work as the collector, but during the process, I lost the ability to use the watch as a speakerphone.  The speaker on the watch still plays media (e.g., Pandora), but, during a call, the microphone and speaker do not work.  Any thoughts on why this would be the case or how to remedy it?  As always, thanks!

**Comment by cybernissart** [comment]
Have a smartphone running nightly build 190318, and a SW3 running 10.0.84 GPS version.
Collector on smartwatch does not work, when phone is out of range or off.

Don't know if it was broken by an interim build somewhere, as it was working previous weeks ago somehow.

Would you have troubleshooting steps/method to address it on watch?

How to check if BT binding and association password if correctly pushed from phone to watch?
Can we connect through BT association menu perhaps (it fails in my case)?

Is adb the only method to check for this?

**Comment by ralf-ms** [comment]
I can't get my Huawei Watch 2 working with Libre Blucon (force wear collection service).
Is this also caused by incompatible bluetooth implementations/versions or is this an entirely different issue?

**Comment by paaascal** [comment]
Hello i Do water sports and need a watch that can collect freestyle libre data WITHOUT the phone around.  I happen to be on the ocean for long hours and simply need to see my bs and go to shore if it starts dropping...  Is the swr50 the only one that can do this WITHOUT the phone or are there others?

When I have. The phone around I use xdrip...  

Thanks

**Comment by no1jeeves** [comment]
Hi, the libre freestyle is an NFC device, not a transmitter, I don't think
that anyone makes a watch with NFC,

**Comment by paaascal** [comment]
Google.ca type Nfc smartwatch ;)

**Comment by patelrupesh** [comment]
hi,
I have just bought Sony Smartwatch 3 after reading on a lot of weblinks that this watch seamlessly as a collector without needing any modifications to the ROM however unfortunately my SW3 doesn't give any readings when selecting the option of "Force Wear Collection Service" - though I do see on the watch a message saying that "Force Wear Enabled". I just see the last reading with the strikethrough line on the xdrip+ watchface. Can someone please help as this is the 2nd watch that I bought (First one was Huawei 2 - that too didn't work).

Thanks,
Rupesh

**Comment by SimonPhilpott** [comment]
@patelrupesh same as me. I've walked Xdrip versions right back to 13th March and none of them collect via the smartwatch 3. I did notice that 30th March and previous versions of Xdrip showed the Blucon as 'bonded# which for me at least using the phone ads a huge amount of reliability for re-pairing when dropping in and out of range. 

![screenshot_20180702-090801_xdrip](https://user-images.githubusercontent.com/6833057/42153376-daf3308c-7dda-11e8-9496-bc4674a83641.jpg)
![screenshot_20180702-090819_xdrip](https://user-images.githubusercontent.com/6833057/42153378-db1c118c-7dda-11e8-8c6c-b6e856dab275.jpg)
![screenshot_20180702-090831_xdrip](https://user-images.githubusercontent.com/6833057/42153379-db3cb2d4-7dda-11e8-833b-9332eb22fb58.jpg)

**Comment by patelrupesh** [comment]
That's unfortunate to read Simon. Does anyone have a solution for this please - Sony smartwatch 3 as a collector? I hope someone might know how to get this working as there are plenty of users on the internet saying that they have been using the SW3 as a collector.

**Comment by patelrupesh** [comment]
Can someone please assist?

Thanks.

**Comment by Vaughanabe13** [comment]
The SW3 does work as a collector, although sometimes it can be a pain to get it working. Here are the settings that work for me.

- Make sure your Hardware Data Source is set to G5 Transmitter and that your Dexcom Transmitter ID is correct.
- In G5/G6 Debug Settings in the phone, check "Use the new OB1 Collector". I also have "Allow OB1 unbonding" and "Allow OB1 initiate bonding" checked. Check "Authenticate G5 before each read" and do not check "Unbond G5 for each read." You can try both ways with the "Scan for G5 constantly". It doesn't need to be on, but sometimes I seem to get better/quicker connections when I leave it on. Either way it doesn't seem to make much difference.
- Go to "Smart Watch Features->Android Wear Integration."  Ensure AW Integration is enabled, enable the wear collection service, enable "Force Wear Collection Service." 
- Go to "Less common settings" and check "Aggressive service restarts." I'm not sure if this is necessary or not but I tend to always leave it on.

Now, sometimes the settings between the watch and the phone get out of sync. For example, make sure the "Force Wear Collection" setting is enabled in both the watch settings and the phone. Sometimes it will only be set in one or the other. Make sure they both are enabled. 

After you change all these settings, start your sensor session (if it isn't already started). I also like to go to the System Status screen and tap "Restart Collector" just for good measure. On this page, you want to  see in the Connection Status "DexcomW2 Authed, FW:1.0.4.10" which means your collector is properly bonding to the G5 transmitter. 

More things you need to do: In the SW3, make sure the software of the watch is up to date, by performing a software update through the Android Wear interface. Then go to the Permissions settings in the watch settings, and go to Xdrip+ and enable all the permissions including location. YOU WILL NOT GET ANY READINGS UNLESS PERMISSIONS ARE ENABLED.
Make sure the xdrip+ is the selected watch face, and again make sure the settings are synchronized with the phone settings.

Next you should perform a system restart of both the watch and the phone.

Next you may need to pair your Dexcom sensor to the watch. Within the first 4-8 minutes of running the collector on the watch using Force Wear Collection, you will get a pop-up on the watch screen that shows your Dexcom transmitter ID and asks you to pair bluetooth. Make sure you are watching the watch face during this time because this is time sensitive. Accept the pairing procedure, and then you should start getting readings within 10 or 15 minutes max. You only have to pair your transmitter once, but you will have to do this step again in the future when you get a new transmitter with a different ID. 

Once you start getting readings, you can go into the phone app and enter your BG calibration (I believe calibration from the watch is currently unsupported).

**Comment by Vaughanabe13** [comment]
You could try going back to a previous version of xdrip+ and trying that.
It's certainly possible that something has broken compatibility. I really
can't speak to the blucon personally since I don't use it and I'm not an
xdrip developer, sorry. I really wish there were official
transmitter-to-watch products out there and that it didn't have to be
something cobbled together.

**Comment by simondavies560** [comment]
We had an Asus Zenwatch 2 working very effectively with a build from some
time in the middle of January (sorry, can't remember the exact build), and
had some temporary success with a March 12th build with Ticwatch, but that
connection has always been very flaky. Definitely suggest rolling back to
older versions, Sony SW 3 does seem to have been the watch of choice
historically.

**Comment by RicardoFBCoelho** [comment]
Saw this very interesting topic. I am looking for a Smartwatch myself to connect with Libre – my aim is to set up a CGM. I’ve seen a few reported watches like Sony SW3, Finow Q1 and several models from Ticwatch that do this without the smartphone.

However, I would like to ask if anyone has experience with any model from Samsung such as Samsung Gear 3 or the new Galaxy watch. In theory, they should have the tech to work but they operate on Tizen OS and not Android Wear.

I appreciate all the help.
Thanks,

Ricardo

**Comment by betulin** [comment]
Hi, I am trying to set up a s. watch as standalone collector. S. watch should get  readings when MM is out of range of the phone and when it's back to phone range, it would connect to the it and synchronize the readings taken by the  Swatch.  Also,  I'd like to follow both, the SW and phone on my own phone. It could be on IOS or Android or both, not problem. I'd really appreciate any suggestions are wellcome Thank you
Hi, I am trying to set up a s. watch as standalone collector. S. watch should get  readings when MM is out of range of the phone and when it's back in phone range, it would connect to it again and s.watch's readings should be syncc.  Also,  I'd like to follow both, the SW and phone on my own phone. It could be on IOS or Android or both, not problem.I could use, Xdrip or Spike or NS. I'd really appreciate any suggestions are wellcome.
I've been reading about . I'd like to tell  you what I have found so far:
1. The Sony SW3 works as an standalone collector but it is not possible to follow it as a follower. Neither in xDrip nor in NS. It does not require any patch but it is sometimes hard to get connection
2. Those watches, which are full Android and have sim, basically works as if they were a phone. They allow standalone connection, follow-up with xDrip as a follower and since they have sim and data connection, they also allow to see it in NS. Unfortunately,  its, battery is too short. They are not submersible.
3. There are some Smartwatches with Android WOs which can working as standalone collectors after applying a patch. Some of them has sim card. However, this is only described for the dexcom g5 sensors and I do not know, for sure, if they shoul be patched or not using MM. They are more expensive . They have a very good battery and they are submersible.
4. The iwatch, so far, do not work as standalone  collectors, they need the iPhone nearby
I'd appreciate any corrections,  suggestion, information  could me set up an standalone collector that can be follow, good battery, IP68 .

The 3rd option would be the best for me but I don't know if they work with MM without patching. I'd prefer not to patch, because I don't feel confident enough to go through it

Thanks a lot

**Comment by tKostka** [comment]
@jamorham: I tried to patch my new Polar M600 with the BT fix but was getting error during the install in the TWRP shell:

> ERROR : with firmware patch A
> ERROR : with firmware patch B
> ERROR : could not patch BT
> ERROR : with demigod mode
> ERROR : with demigod-2 mode

I've tried several times, with several reboots.
It seems there was an Update from Polar recently, the Bulid Number of my M600 ist different from the number in the PDF Guide: OWDB.180305.008 vs OWDB.180305.0**15**
Is this the problem? If so, would it be possible to get an updated patch?

By the way, I made this with my Windows 10 Notebook. To help other Windows users, you may add the following in your future PDF guides.
I was missing a smartwatch driver for fastboot, so i had to download and manually force windows to use the android google driver (https://developer.android.com/studio/run/win-usb).
The fastboot commands are different from Linux. In the Windows shell it is just `fastboot oem unlock` (not fastboot –i 0xda4 oem unlock) and `fastboot boot twrp-polar-m600.img`. The fastboot option -i is not available in Windows.

Thanks for all of your work, i'm using xDrip for years now. I hope you can help with this problem.

![polar-build-nr](https://user-images.githubusercontent.com/11375777/45904048-10684300-bdec-11e8-9766-a1c2cd0502c0.png)
![polar-versions1](https://user-images.githubusercontent.com/11375777/45904049-1100d980-bdec-11e8-882a-7d559e379cb5.png)
![polar-versions2](https://user-images.githubusercontent.com/11375777/45904050-1100d980-bdec-11e8-9013-8e99c1352327.png)

**Comment by SimonPhilpott** [comment]
I've had a pretty good experience with using a Miao Miao over the top of my Libre and removing the SW3 from its strap and putting it into a small roll pouch around my neck. That got me back in the water for most activities.  Most roll pouches for electronics are IPX8 and support touchscreen use which banded with the (flakey) IP68 rating is about as reliable as things are going to get. 

The Nixon Mission would be a great step, but that being said it;s no use if the Miao Miao remains as IP68. You're only as waterproof as item with the lowest rating after all.

**Comment by heygar** [comment]
I just recently started messing with this with my ZW3. I'm looking for a smartwatch I can wear out on a catamaran cruise of sorts. Lots of water activity.
I've decided to try the Misfit Vapor as I can get a used one for ~$50 on Ebay. 
Has anyone had any luck running the Vapor as a collector? Or is it totally impossible?

**Comment by Braintelligence** [comment]
@heygar did you have any luck with the vapor?

**Comment by heygar** [comment]
The bidding went above my comfort level for the risk of it not working.
I'm still looking for a water proof wear OS watch I can confidently use as a stand alone collector.

**Comment by lee-b** [comment]
I've noticed that this works (on a Huawei Watch Pro 2) with Glimp, but not XDrip, for some reason.

**Comment by Navid200** [comment]
It seems the issue this thread was opened for was already addressed.
