### ISSUE TITLE
ticwatch pro 3 standalone not working

### ISSUE THREAD

**Issue by paaascal** [NightscoutFoundation/xDrip#1490]
with miaomiao2, canadian freestyle 1 and oneplus5 on android...  

what dooo i neeed to do to get stand alone to work again?! 

thanks

**Comment by tolot27** [comment]
> what dooo i neeed to do to get stand alone to work again?!

Does it means that it worked before? If yes, what did you change? Have you looked at the other issues related to ticwatch?

**Comment by paaascal** [comment]
yes it worked in the past, i didnt change anything, xdrip changed something in one of their updates 2 years ago... havent been able to get it working since... wrote to jamorham, no answer.

**Comment by tolot27** [comment]
@paaascal Hence, it did not work for two years now? Did you created an issue earlier? Ah yes, #1079. Why did you close them? Does not speed up anything, if new issues are created.

Will closing them in favour of #1079.
