### ISSUE TITLE
Xdrip+ mi band 4 Legal Time issue

### ISSUE THREAD

**Issue by ANDREAPIPPI** [NightscoutFoundation/xDrip#1493]
Hi. 
I use xDrip+ with MIAO MIAO 1, Freestyle 1 (14 days EU) and Mi band 4 without problems, but at the end of the Legal Time (Oct 25) and return to Civil Time (1 hour back) Mi Band 4 time is unchanged, so actually it's 1 hour forward.
Anyone else with the same problem?
What have I to do to correct this issue, without creating more
issues with Smartphone/Xdrip+/Mi bamd coupling?
Thank you.
Andrea   :-)

![IMG_20201101_002637](https://user-images.githubusercontent.com/32884006/97792057-7897ce80-1bd9-11eb-8121-9522f6b7e43a.jpg)
![IMG_20201101_002501](https://user-images.githubusercontent.com/32884006/97792067-9fee9b80-1bd9-11eb-9ba3-aa9c5610e577.jpg)

**Comment by Otto75so3e** [comment]
The time is not syncronised between xDrip and the Miband. The time on your watch is from the initial setup with MiFit. The solution is to connect with the MiFit app to sync the new time.
I would prefer it too if xDrip would sync the time to the Miband. Maybe every hour or so. On my band the time drifts slowly away and I have to correct it with the MiFit app.

**Comment by ANDREAPIPPI** [comment]
Hi Otto75so3e, thank you for your reply. 
Just a doubt: if I install once again the (original) Mi Fit apk, then I'll have to repeat all the procedure to link Mi Band 4 to xDrip, using the modified Mi Fit app?
This is not so nice for me, I still remember the problems I had and time needed for the first installation.
If your reply is yes, then I think we should ask to the developers if they could possibly allow xDrip to sync the time to the Mi Band.
Do you agree?
Andrea   :-)

**Comment by tolot27** [comment]
@ANDREAPIPPI Please report back if you could solve the time sync with the Mi Fit app. Later we can change this issue into a feature request.

**Comment by ANDREAPIPPI** [comment]
Hi tolot27 .
Yes, I tried and now as you see Mi Band 4 and Phone have the same Local Time, but I had to make once again all the procedure to link xDrip with Mi Band, and this, even if not difficult, takes a lot of time.
So I think it would be nice to have automatic time sync between Xdrip and Mi Fit.
Can you please do it?
Thanks a lot.
Andrea   :-)
![IMG-2](https://user-images.githubusercontent.com/32884006/98120633-7c17a800-1eae-11eb-8057-d4db5b333359.jpg)
![IMG-1](https://user-images.githubusercontent.com/32884006/98120662-83d74c80-1eae-11eb-9f31-34dac5dde1f0.jpg)

**Comment by tolot27** [comment]
@bigdigital Is it possible to implement time sync?

**Comment by bigdigital** [comment]
I don't think the time sync feature should be implemented in the xdrip. Normally the time syncing should be done by specialized applications like mifit, etc. In my case, the switching to daylight saving time was automatical (i use official mifit).  Also, time sync works fine when i change the time zone on my phone. For faster time sync it is enough to open mifit application, and in some case need to enable/disable Bluetooth connection.

**Comment by ANDREAPIPPI** [comment]
Hi bigdigital.
I understand what you say, but probably not all systems are the same, as at least two of us (and surely more) have this problem. 
I tried with the original mifit and, as I told, it solved, but I had to repeat again all the Mi Band/xDrip connection procedure, and this is a frustrating and time consuming operation.
My request: is it possible, or is it too difficult, to synch Mi Band with xDrip time?
If too difficult, never mind, if not, could you, please?
Thank you whatever will be your reply, we already appreciate very much your work.
Andrea   :-)

**Comment by Navid200** [comment]
@ANDREAPIPPI Would you please close this issue if your questions has been answered already?
You can ask your questions using the support channels.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks

**Comment by ANDREAPIPPI** [comment]
Closed.
