### ISSUE TITLE
Statistic: the percentage sum is not equal to 100%

### ISSUE THREAD

**Issue by Philoul** [NightscoutFoundation/xDrip#1496]
See screenshot below:
The 3 values are truncated (not rounded), so the sum equals 98% in this screenshot and not 100%
My suggestion would be to round the High and Low percentages to the nearest integer value  and calculate the "in range value"  with 100% complement ... 

High=5/283=1.77 => 2%
Low=8/283=2.83 => 3%
In=100-(2+3) = 95%

![Screenshot_20201105-064728_xDrip+](https://user-images.githubusercontent.com/52934600/98295046-32fc4c80-1fb1-11eb-92ed-5e2189601eb2.jpg)

**Comment by user-hash** [comment]
Hey,
I noticed the same, but I think you should not use xDrip if you don't have diabetes.
Just kidding, thats perfect result..Im only a few days 98% in range, but im very happy=)
Could xDrip gamification help with better results in general with young T1D?
Im thinking on achivements for your blood sugar levels like 1,2,7, ... days in range. A positive incentive could give young and old people more encintive to keep their blood sugars in the range...just an idea

**Comment by Philoul** [comment]
Hi,
I'm T1D and I use xDrip + AAPS, I selected this day for my screenshot (yes, it's one of my best days I mostly have about 80% in range), because the sum is 98% (I think it's worst case)
Generally, sum equals 99%, and it's only when results of the 3 calculated percentages are exactly integers that sum equals 100% (quite never).
I'll propose a PR soon with a little modification of percentage calculation to always get 100%...

**Comment by AdrianLxM** [comment]
Back in the day when I added that, I had too many days that summed up to 101%

If many want rounding than the implicit flooring through integer division: no objections. @Philoul if you want to take this: feel free to, would be great. If I should do it or you need assistance, please drop me a message in slack.

**Comment by Philoul** [comment]
To avoid a sum above 100%, "In range" percentage calculation is not the same than High or Low range percentage calculation...

@AdrianLxM can you review https://github.com/NightscoutFoundation/xDrip/pull/1498 and tell me what do you think about it ?
Thank's

**Comment by Navid200** [comment]
This is a good improvement.

But, relatively speaking, the fact that this page, as well as the PGI page, doesn't show the High and Low level figures is a more serious shortcoming.

The PGS you see here is a function of the Low and High levels.  
You see the in-range percentage on this page.  But, what is the range?  Well, as it stands, you have to go to another page to see what the range is.  Why?  Why not include those figures here as well?  
This page as is is definitely incomplete.

**Comment by tolot27** [comment]
@Navid200 That is good point you mentioned. Please can you create another issue for it? A PR is available for this issue, already and waits for merging.

**Comment by Navid200** [comment]
@tolot27 
I created this a while ago.
https://github.com/NightscoutFoundation/xDrip/issues/1483
Is that OK?  Or, is there anything else I should do?  
Thanks
