### ISSUE TITLE
Reset the Wahoo Elemnt Roam because Xdrip connection is not working

### ISSUE THREAD

**Issue by derboo1** [NightscoutFoundation/xDrip#1500]
I tried to setup my Wahoo elemnt to get my glucose data while bycing. Unfortunately the instruction from here: https://github.com/NightscoutFoundation/xDrip/wiki/How-to-use-the-Wahoo-Elemnt-Bolt-cycle-computer-as-a-collection-device is not working for me. I have libre 2 sensors. I guess this is just working with the dexcom?

I only get a big "Scanning" in every page of my wahoo and showing the data is not functional. 

I tried reset my wahoo and also I tried to follow the manual on "How to turn it off again". At least for me the section is not detailed enough. I still have the "Scanning" entry on my wahoo. How do I turn this off to not see it on the wahoo anymore.

Thanks a lot in advance

**Comment by derboo1** [comment]
Sorry guys. I'm just too stupid. I just saw how I can reorganize the data on my wahoo elemnt and can change the order of the data including my glucose data. Problem is solved

**Comment by scammels** [comment]
ive also tried this and get the same, 'scanning' appear, so did you close this issue because youwere able to remove the Scanning datafield from the Wahoo? or were you ever able to get it to work?

**Comment by derboo1** [comment]
No it is not working! I still have the scanning field 🙄

**Comment by davemap** [comment]
I'm having the same issue, have you made any progress?

**Comment by nahuis** [comment]
You should connect the wahoo to a computer as a USB device. There is one strange file, don't remember the name but you will recognise it. Just delete that one.

**Comment by nahuis** [comment]
Bytheway, there is a suboptimal workaround for Libre users at issue 
#1654

**Comment by nahuis** [comment]
This issue can be closed.

**Comment by tolot27** [comment]
It is not possible to use an Android Wear device as an collector for Libre2 or newer sensors.
