### ISSUE TITLE
New mongodb uri format is not supported by xDrip+

### ISSUE THREAD

**Issue by Cagier** [NightscoutFoundation/xDrip#1502]
After migrating from the old mlab to the newer MongoDB Atlas version, xDrip no longer seems to be able to upload directly to the database. You can use the new "mongo+srv://" URI prefix in the cloud parameters but the logs seem to show that this is subsequently being rejected.

![IMG_20201109_191257](https://user-images.githubusercontent.com/10944929/98587491-21bd8380-22c2-11eb-8920-ad6595a11d0d.jpg)

**Comment by sulkaharo** [comment]
FYI Nightscout does not support direct to Mongo uploads anymore (it never really did, the fact it worked after REST API was introduce was incidental), so the "correct" fix here is to remove the Mongo uploads entirely and/or label it as something no Nightscout user should use.

**Comment by Cagier** [comment]
That's a pity. I use both so that I can keep a second site running for redundancy. I did read earlier today  that Atlas also support the old URI format (but it is less future-proof) so I might try that anyway and if it works then it works. Thanks for the info anyway.

**Comment by tolot27** [comment]
@sulkaharo Shall we remove the MongoDB upload or just make them visible in the engineering mode, only?

**Comment by sulkaharo** [comment]
Engineering mode would make a lot of sense. As pointed out in the thread, there's valid use cases for it like backups and possibly other experimentation, but I'd love a solution that reduces the likelihood a user who doesn't know exactly what they're doing assumes it's the good way to upload data to Nightscout.

**Comment by tolot27** [comment]
I'm still unsure whether we should add support for the URI scheme `mongo+srv` or just disable the setting except in engineering mode.
@sulkaharo Do I understand you correctly that the new URI scheme is just not supported but still possible?
Are there any differences between `mongo` and `mongo+srv`.

**Comment by tzachi-dar** [comment]
We should make it very clear that uploading to nightscout sites is not supported and will not work.
There are other legitimate uploading/downloading supported ways, for example uploading of libreblock data.

I intend to try and handle this in a week or two.

**Comment by tolot27** [comment]
@tzachi-dar What do you try to handle? The clear statement not uploading to nightscout or uploading of libreblock data?

**Comment by tzachi-dar** [comment]
I have made many experiments to download from a mongodb, and failed.
Looking at https://stackoverflow.com/questions/50916467/how-to-connect-to-atlas-m0-free-tier-cluster-correctly-via-java-driver this seems possible. I have tried this, but failed.

Other places suggest that it would not work, and we should move to stich.
For example: 
https://jira.mongodb.org/browse/JAVA-3245


https://stackoverflow.com/questions/59538402/how-to-properly-connect-mongodb-atlas-to-an-application-on-android-studio-that

https://stackoverflow.com/questions/55110874/how-do-i-connect-an-android-app-to-mongodb-stitch

So, I wonder if the correct thing to do is move to stich / keep fighting for a workaround on mongo, or simply use nightscout rest api.

**Comment by tzachi-dar** [comment]
Actually, looking at https://stackoverflow.com/questions/50916467/how-to-connect-to-atlas-m0-free-tier-cluster-correctly-via-java-driver this is not android. So, it seems to me that we are either at stich or at rest api.

probably rest should be simpler.

Thoughts?

**Comment by sulkaharo** [comment]
From Nightscout perspective, users only using REST would be the right way forward

**Comment by tzachi-dar** [comment]
@sulkaharo I'm trying to upload a document to a new collection in nightscout but my code fails with error 404

Here is the code that I'm trying:

url = 'https://snirdar3.herokuapp.com/api/v1/libre'
payload = {'some': 'data'}
payload = {"_id":"5fd370324e412324f4d253a5","device":"xDrip-LimiTTerWifi","date":1607692311331,"dateString":"2020-12-11T13:11:51.331Z","sgv":134,"delta":-12.55,"direction":"SingleDown","type":"sgv","filtered":131176.46075,"unfiltered":131176.46075,"rssi":100,"noise":1,"sysTime":"2020-12-11T13:11:51.331Z","utcOffset":120,"mills":1607692311331}
headers = {'content-type': 'application/json',
           'api-secret': 'xxx'}

response = requests.post(url, data=json.dumps(payload), headers=headers)
print(response, response.content)

If I upload the same data to the entries collection this works. So, I wonder if nightscout only supports uploading to a fixed set of collections.

**Comment by sulkaharo** [comment]
Yes, Nightscout only supports the predefined collections and data formats

**Comment by tzachi-dar** [comment]
Should it be complicated to add another collection to it?

**Comment by sulkaharo** [comment]
Depends - what's the use case? The system expects treatment data with carbs and insulin to live in /treatments and CGM data to live in /entries and from data model perspective the only justification for a new collection would be the addition of completely new type of data.

**Comment by tzachi-dar** [comment]
The system should not do anything with the data. Only allow to upload and download it.
Basically we are talking about libre readings. There are pis that collect and write them and then xDrip reads them.
They used to write to mongo directly, but now it is not possible.

**Comment by sulkaharo** [comment]
If you're storing Libre readings, why not store them in /entries? Nightscout is not a general data storage for CGM apps to store data for their own use, vs an ecosystem component to allow interoperability - if you want to push data into Nightscout, it should play nice with the built-in visualisation and alarms and you should assume apps other than the uploader will access it, so it should be stored in places apps expect to be in and in format that complies with the core Nightscout field spec.

**Comment by sulkaharo** [comment]
Actually - has xDrip been using the mongo connection to upload data to arbitrary collections, not just the ones Nightscout uses?

**Comment by tzachi-dar** [comment]
Well xDrip had the possibility to store data to a mongodb. Some of this data was stored to collections that nightscout was not aware of. Some of them were stored to DBS that were not connected to NS at all...
With the move to atlas, xDrip has lost the ability to write directly.
I'll try to see if using the entires collection can be used, or maybe we need another rest service to be installed on heroku.

**Comment by tzachi-dar** [comment]
OK, I got a web service that is bringing the node calls... No need for a change in nightscout.

**Comment by tzachi-dar** [comment]
I have created a PR to start using rest at least for reading libre blocks.
https://github.com/NightscoutFoundation/xDrip/pull/1557

**Comment by tolot27** [comment]
@tzachi-dar If you link the issue with the PR (as I did), it will be closed automatically, if the PR is merged. 
Please can you briefly describe, why it is necessary to directly download/upload to a mongoDB?

**Comment by tzachi-dar** [comment]
When using libre, there are a few ways to have all house coverage.
One of the methods is shown here: https://github.com/tzachi-dar/LibreAllHouse
This methods is based on rpis that can be contacted directly by xDrip or they can write to a mongodb.

The PR sent allows xDrip to read from this mongodb (using rest api as mongo is not supported by android any more).
The main advantage of this method is that xDrip does not have to be on the same wifi network with the pis.

**Comment by Navid200** [comment]
Is this still an issue?
Can we still use mongoDB?

**Comment by sulkaharo** [comment]
You absolutely should not use MongoDB data injection with Nightscout.

**Comment by Navid200** [comment]
xDrip users who like to have a repository of their blood glucose readings can use Nightscout as long as they follow the clear instructions.  

Mongo is a no go and we were supposed to switch to Atlas.  And one can even set up a new Nightscout account as well, again following the clear Nightscout instructions.

If anyone likes to make changes to Nightscout, the suggestions should be made on the Nightscout site, not xDrip.

I am closing this.  
If you want to reopen, please explain why not being able to upload to MongoDB is an xDrip issue.

**Comment by 01erster** [comment]
> xDrip users who like to have a repository of their blood glucose readings can use Nightscout as long as they follow the clear instructions.
> 
> Mongo is a no go and we were supposed to switch to Atlas. And one can even set up a new Nightscout account as well, again following the clear Nightscout instructions.
> 
> If anyone likes to make changes to Nightscout, the suggestions should be made on the Nightscout site, not xDrip.
> 
> I am closing this. If you want to reopen, please explain why not being able to upload to MongoDB is an xDrip issue.

Nightscout implementation is based on heroku - unfortunately heroku itself does not support mongodb itself anymore. Means whenever xdrip is configured to push values towards to nightscout those values will not be stored in mongodb. Support stopped on Mon Oct 22 53928 01:06:47 UTC+0200 (Central European Summer Time). Now idea is to write data directly into mongodb+srv - at least not to loose any data at all. Might be there any chance to enhance mongodb supporting with new uri +srv ?

**Comment by Navid200** [comment]
> Now idea is to write data directly into mongodb+srv - at least not to loose any data at all. Might be there any chance to enhance mongodb supporting with new uri +srv ?

It's always a good idea to anticipate the questions before they come up.
For any proposal, the best approach, in my opinion, is to clearly identify what the advantage of what you are suggesting is over what we already have.

I am using Heroku and all my readings are stored in Heroku through Nightscout.  What would be the advantage of what you are suggesting over what I haver now?

**Comment by sulkaharo** [comment]
@01erster your description of how Nightscout works is entirely inaccurate. Nightscout requires MongoDB to work and there is no situation where a Nightscout instance will run and accept data if it cannot connect to a Nightscout instance. The support that was deprecated was mLab, which was a company used to host MongoDB. Heroku has never supported MongoDB hosting. The currently recommended service for Nightscout is Atlas, which hosts Mongo, which is subsequently accessed by the Nightscout server runtime running in Heroku.

Nightscout still does not support direct data injection into MongoDB and while this works for some scenarios, we do not test this during development and injecting data to MongoDB directly can cause Nightscout to behave unexpectedly. Thus my original statement still stands - if someone is asking for the MongoDB injection to be changed for use with Nightscout, this is not a supported use case and might completely break going forward.
