### ISSUE TITLE
"Liver sensitivity" and "maximum standard influence of the liver"

### ISSUE THREAD

**Issue by ARkaine2** [NightscoutFoundation/xDrip#1509]
What do these settings do?
Seems that they are important.

**Comment by emp-00** [comment]
FYI seems to the identical to this issue: https://github.com/StephenBlackWasAlreadyTaken/xDrip/issues/210

**Comment by ARkaine2** [comment]
And 1 more ask:
It will be fine to have insulin curve setting in.

**Comment by tolot27** [comment]
> And 1 more ask:
> It will be fine to have insulin curve setting in "Low prediction values".

What do you mean by this? Is it a feature request? If yes, please open a separate issue for it and describe in detail what the request is.
