### ISSUE TITLE
SiDiary-Export did not contain other Therapeutic Data (KH,IE, ect)

### ISSUE THREAD

**Issue by MasterPlexus** [NightscoutFoundation/xDrip#151]
It seems that only the CGMS Data are included in the Export for SiDiary. For a overall-View and discussion with the doctor a complete export should be possible.

**Comment by MasterPlexus** [comment]
I have a short look to the sources, and think the implementation will not that difficult. So I'll try it in my Fork. If everything is ok and working I'll come back, if ok for you, with the changes...

**Comment by AdrianLxM** [comment]
@MasterPlexus, that would be great. I wrote the export at a time where there was no treatment data in xDrip.
Do you know the import format specifications for SiDiary? Can CGM-Data and Treatments be mixed together?

I think it would be best to export a second file with MBG data (from calibrations ans also those not used as calibrations) including the carbs (does SiDiary expect g of carbs or German "BE"?) and insulin.

I'm looking forward to hearing how it goes :+1:

**Comment by MasterPlexus** [comment]
@AdrianLxM I know the format more or less, and yes it could be mixed. All what needs to be done is to name the right fields in the header. Nevertheless I can request the data structure, if I have problems, from the SiDiary-Team ;) 
May also a interface could be possible, to transfer the data via gmail to Sidiary-online, to let import it there in the background (used that in the past for Glimp-Data). But this should be the next step what I have in mind.

I'm not sure if it will be the best to separate the files by datatype. May it could be interested to made settings available which kind of data should be included in the export-File? We will see. At first I will try to implement just the rough Export all in one, just to check that everything comes in a way that the data could be well imported. After that we can see how to increase the export ;)

**Comment by MasterPlexus** [comment]
Doing it a little bit. Locally it works, but I wondering in that the time stamp seems to be not absolute. In my build environment the emulator is 2 hours ago to nowtime, and the export had the same move in the time-export. But maybe this is something I did not recognized before in Java or SQLite-library...
If you want to have a look (for sure,the implementation is more rough then nice ;) )
https://github.com/MasterPlexus/xDrip/commit/4b9e101bce926690721b31fedf0dd6858632f8e9

**Comment by AdrianLxM** [comment]
Does it import correctly if treatments and BG values are not set in ascending order?

Maybe it helps to add the timezone to the formatter:
``` 
df.setTimeZone(TimeZone.getDefault());
java.text.DateFormat df = new SimpleDateFormat("dd.MM.yyyy;HH:mm;");
```

**Comment by MasterPlexus** [comment]
Yes, this makes no issue. The order can be as you want in the CSV file. 
OK. Will test the timezone tomorrow, with the other corrections ;)

**Comment by MasterPlexus** [comment]
So did the translation (CHO) and some typos. Also tried the Timezone, but bring no change.As this will only are a problem if the time of the Phone is set to a other area, this is not a urgent problem think. 

Could it be, that the BloodTest is an not used Table, and all Measurements are stored in the Calibration-Table? So I did not Include the BloodTest for now...

https://github.com/MasterPlexus/xDrip/commit/11a4a88f5fe1a82fb39ec3a784b88bf80d0c42cf

PS: I'm up to not so familiar with the CSV in Android studio, so I made in mistake two commits with the same description :(

**Comment by MasterPlexus** [comment]
@AdrianLxM , could you explain, what the Table BloodTest is for? I assume that this table will be filled not by manual entrys of the user, but if there will put also Values from other places (like bluetooth Measurement or something else what I did not know), that this should be also in the export... Forme the question ist, is there, if this table will be used, then also every time a entry in the Calibration-Table? If yes, then I would say only those the calibration-Table for BG export. If the answer ist sometimes yes sometimes no, it could be difficult to know the duplicates (may they are marked). If the answer will be no, then I would include the table anyhow (but can not test the result)...

**Comment by MasterPlexus** [comment]
Made a Pull request for that:
https://github.com/NightscoutFoundation/xDrip/pull/154
