### ISSUE TITLE
Wear OS Watch Collects, but does not update phone BG (SW3 / SWR50 / Huawei Watch 1)

### ISSUE THREAD

**Issue by old-square-eyes** [NightscoutFoundation/xDrip#1511]
I got a new phone Galaxy Note 20, Android 10 with October security patch. Usually I happily collect from my Sony Smart Watch 3

My old phone was S8 on Android 9, and the phone itself collected as well as the SW3.

Now on a new setup, I'm having issues. I experience this on the current xDrip Alpha, but also on tonight's Nov patched nightly (with and without Android 10 workaround). So not related to this change I don't think.

- Phone collected (direct) fine for 24hrs... though hard to say with backfill. But I didn't notice any issue.
- Then started missing 3 out of 4 readings (may log a separate issue for the phone drop outs - this is mostly about the watch)
- Making my SW3 collector, and I get similarly odd results. Sometimes it also misses readings. But sometimes I get a good run on the watch, but BG is not synced back to the phone.
- Phone status tells me "watch received glucose", so not sure why BG doesn't sync.
- Treatments on watch DO sync to phone

Anyone know why the phone couldn't get BG from the Watch? Might have to factory reset it.

Edit: Factory reset watch, side loaded Google Play Services, same issue. Watch collects, but phone doesn't get data, but does get Status updates.

![Screenshot_20201116-220239_xDrip-](https://user-images.githubusercontent.com/25760491/99313130-e7587580-28c3-11eb-9518-c06cf7ec0f18.jpg)

With Wear logs enabled...

![Screenshot_20201116-224405_xDrip-](https://user-images.githubusercontent.com/25760491/99313232-0e16ac00-28c4-11eb-8f8c-28400ab1302d.jpg)

With extra Nano logs enabled...

![Screenshot_20201116-232611_xDrip+](https://user-images.githubusercontent.com/25760491/99313293-2686c680-28c4-11eb-8518-70291a925c51.jpg)

**Comment by old-square-eyes** [comment]
Hi @tolot27 thanks for the reply. I tried exporting DB, uninstalling, reinstalling, importing settings and DB. Phone collects. Switch to Wear, enable location services on Wear and watch collects. But still no BG sync to phone.

I tried the above again, this time clearing cache and data beforehand. Same result. Here are some new logs from the second attempt with Wear taking over...

![Screenshot_20201120-090806_xDrip+](https://user-images.githubusercontent.com/25760491/99718683-1ebb6200-2b10-11eb-81bd-99a1a139607b.jpg)

**Comment by old-square-eyes** [comment]
I'm actually in a bad way now. My phone is dropping BG A lot too.

**Comment by old-square-eyes** [comment]
Phone went dark on collection. Had to switch back to watch (with no phone sync) while I re-setup my old Galaxy S8. Will have to format watch and pair it back to that.

**Comment by old-square-eyes** [comment]
Had to reset my phone again for another reason and I tried the approach of the two step GPS upgrade. Same issue. Will reset Wear again and try again but wait a bit longer between them this time.

**Comment by tolot27** [comment]
@old-square-eyes Please can you provide the xDrip version you are using? In your first post you mentioned "current xDrip Alpha", but you did not provide a version number. We need at least a version tag, like 2020.11.15 for the [Nightly build 15th Nov 2020](https://github.com/NightscoutFoundation/xDrip/releases/tag/2020.11.15).

**Comment by old-square-eyes** [comment]
@tolot27 sorry, my point was that it was both on an older alpha and the latest 2020.11.15. So It must be something to do with moving from Android 9 to Android 10 (perhaps the process of migrating data with SmartSwitch), or at least new hardware. FWIW the version I am on currently is 2020.10.01.

Though, I have cleared xDrip data, reinstalled xDrip, cleard Google Play Services (GPS) data - which unfortunately unpairs and factory resets the watch.

The watch collects fine, the phone updates this as status, but seems stuck in its ability to sync BG. Logs seem to show the phone going through it's watchdog processes of restarting collector etc, when it doesn't need to.

**Comment by old-square-eyes** [comment]
![Uploading image.png…]()

**Comment by old-square-eyes** [comment]
Seems to have resolved itself after days of factory resets, playing with GPS versions through ADB. I lost xDrip prefs off the device and got it back on by installing an older Android Wear version. Then forced collection on and off a few times and finally saw this popup...

![](https://files.gitter.im/56a24fd4e610378809bdae01/RUT1/20201126_114702.jpg)

Once accepted I could collect from Wear and sync to phone. I'd love to know what removes that permission, and also what triggers the request for it (since banging my head against the wall doing the same stuff didn't get a prompt in the previous two weeks). Can it be manually triggered?

**Comment by daclaw2k** [comment]
Hi, I'm having similar issues, I get BSL updates on my SW3 watch but it doesn't send them through to my phone unless both devices are manually reset - my phone is a google pixel 3XL.
Have tried deleting xdrip+ and unpairing / formatting my watch, the only thing I've found to help is an older Google Play services - however i'm now getting BSL dropouts on my watch.
Does anyone have a SW3 with a high capture rate who can let me know what Google Play Services version they are running?

Thanks!

**Comment by daclaw2k** [comment]
> Hi, I'm having similar issues, I get BSL updates on my SW3 watch but it doesn't send them through to my phone unless both devices are manually reset - my phone is a google pixel 3XL.
> Have tried deleting xdrip+ and unpairing / formatting my watch, the only thing I've found to help is an older Google Play services - however i'm now getting BSL dropouts on my watch.
> Does anyone have a SW3 with a high capture rate who can let me know what Google Play Services version they are running?
> 
> Thanks!

Ok - after hours and hours of trial and error - I seem to have found a solution for this.

On my Google Pixel 3XL in the Settings under Security -> Trust agents -> Turning OFF Smart Lock seems to have fixed the problems between watch and phone for me.
Trust agent allows the phone to bypass security checks (no pin/fingerprint etc required) under certain circumstances ie. when the phone is in a certain location / connected via bluetooth to a specific device.
There must be some sort of glitch with bluetooth when the trust agents are enabled, has been running fine for the last 8 hours with a high capture rate, also automatically reconnecting after either device has been out of range.

**Comment by old-square-eyes** [comment]
@daclaw2k nice one. And that's very interesting in the context of ongoing BT glitches too. I don't use trust agents, but Smart Lock IS enabled. I can't test as my issue resolved per the post above. But it's certainly another weapon in the arsenal when troubleshooting BT, and not something I had ever played with.

**Comment by old-square-eyes** [comment]
This has happened for me on Huawei Watch 1

**Comment by old-square-eyes** [comment]
Reinstalled xDrip prefs from watch and got the location request (again), and it's collecting and syncing to the phone now. Nice one. Two BG in a row too. Though I don't thinkn this process is available on Wear 1.5 (SWR50). Resync apps might work from the Wear OS phone app.

**Comment by Navid200** [comment]
@old-square-eyes Looks like there is a solution.  Can we close this issue then please?
