### ISSUE TITLE
Feature request: "Insulin curve" setting in "Low prediction values"

### ISSUE THREAD

**Issue by ARkaine2** [NightscoutFoundation/xDrip#1512]
You know (ultra-)short-acting insulins (like Fiasp/Apidra/NovoRapid/ActRapid) have different duration.
But they also have different CURVE of acting (their: start, peak, "main acting", "tail" etc.).

By default, if I understand graph correctly there's "linear" curve in xDrip (here's screenshot):
![photo_2020-11-17_12-19-16](https://user-images.githubusercontent.com/31447095/99378920-b03c9100-28d0-11eb-81fc-6cc760059a2b.jpg)

So my ask is about making "Insulin curve" setting in that will probably be somewhere in "Low prediction values" like:
"Insulin Sensitivity" in "PREDICTIVE SIMULATION SETTINGS"
or
"Insulin duration in hours" in "Low level prediction values"

Maybe "Insulin curve" setting should have:
Main "slider".
Curve in/out.
Minimum/maximum values.
Or you know better.

If it's not too difficult to be ralized, not dangerous and won't be bugged. :D
Thanks.

**Comment by tolot27** [comment]
@ARkaine2 Did you see PR #1388? I believe it covers what you request.

**Comment by ARkaine2** [comment]
**tolot27**,
I'm new to (or not so good at) xDrip / GitHub.
Can you please provide me some info (or link to guide) abut:
How can I install these profiles?

I see there master and possibility to download .ZIP. 
But how to install it to smartphone where's xDrip installed?

**Comment by tolot27** [comment]
@ARkaine2 I recommend to wait till the PR is merged into master by jamorham. Otherwise, you have to build your own xDrip using Android Studio.

I'm closing this issue because I believe it is fully covered by #1388. Providing config settings for insulin curves to users is quite dangerous, IMHO.
