### ISSUE TITLE
Feature Request: Extended Bolus

### ISSUE THREAD

**Issue by danielharrelson** [NightscoutFoundation/xDrip#152]
I know it is called different things on different pumps, combo bolus, extended bolus, etc.

Would it be possible to integrate this into the app for when you bolus say 7 units, and you take a certain percentage now, and the rest of the percentage over the course of so many hours?

Example tonight I took 8 units of insulin, i took 45% now, and the remainder 55% over the course of the next 5 hours.

Something like that could be really helpful.

:) Thanks for all the hard work guys and gals.

**Comment by acron0** [comment]
+1

**Comment by Otterinaround** [comment]
I am an endorsement for this one also. Would an option under the insulin treatment be the way to go? As in the option to extend the bolus? 
Then of course a section where there is a demarcation of the percentage to be extended and the period to extend over. 

This will probably mean script that pretends the user is putting in doses at regular intervals with each input having its own degradation curve. mmmm lots o data crunching and lots of zones to trip over.

**Comment by Tornado-Tim** [comment]
I would also support this as well

**Comment by debsies** [comment]
+1

**Comment by Navid200** [comment]
@danielharrelson What is the status of this issue?
Has it been addressed?

**Comment by danielharrelson** [comment]
@Navid200 I'm not sure.

I have different use case for NightScout now than I did previously. You can close this if you wish.
