### ISSUE TITLE
FEATURE REQUEST: Different "Carb absorption rate" for food with different glycemic index

### ISSUE THREAD

**Issue by ARkaine2** [NightscoutFoundation/xDrip#1525]
I have idea to improve "Predictive Simulation Settings".
You can there set "Carb absorption rate".
It's important parameter.
That's why I think it should be improved.

I'm talking about:
"Carb absorption rate" should be customizible for let's say fast/med/slow carbs (based on different food glycemic index) (which, if necessary, combinible) like different graphs for different insulins in "Multiple Insulin Types" or definible by user in number values.

Thanks.

**Comment by simonpickering** [comment]
I also think this would be useful as I've noticed that while the general algorithm works for a meal with a mix of GI types, it's not very good for specific food stuffs at either end of the spectrum.

With that said it would require a different predictive algorithm to make it worthwhile, which is probably a different feature request.

I'm also conscious that the best solution here may be to use a different app to input relevant data about food/drink consumed (so it could be all singing and dancing with meal planning, food db, etc., or just a basic set of input fields - XDrip doesn't need to care) and for XDrip to simply provide an end-point to allow upload of this data into XDrip via its web API for use internally in the prediction algorithm.

**Comment by tolot27** [comment]
This issue is similar to #1519 and addresses the same problem by adjustment of the carb absorption rather than by choosing it during/with the carb input.

Having both options would be quite confusing. If I remember correctly, most loop systems require that GI/GL is provided during carb input.

**Comment by Navid200** [comment]
@ARkaine2 Would you please close this issue and add your request to the existing issue?
https://github.com/NightscoutFoundation/xDrip/issues/1519
Thanks

**Comment by Navid200** [comment]
@ARkaine2 
Please use the existing open issue to propose any additions or improvements.
If you believe that this should be open for a reason, please explain why before reopening.
Thanks
