### ISSUE TITLE
Continual pairing requests after recent Android update.

### ISSUE THREAD

**Issue by cutlerphoto** [NightscoutFoundation/xDrip#1527]
I'm on 11-27 daily. Having problems with a constant android pair request notifications that I cannot silence or connect. "Unpair before bonding" is not checked.

"Could not read reply to auth challenge....."

"Prompting user to notice pairing request with sound. On android 10+ you have to manually pair when requested." are a couple of errors seen.

**Comment by tolot27** [comment]
Which sensor do you use?

Did you follow the recommendations provided in recent comments of #1494?

**Comment by cutlerphoto** [comment]
G6

I found this during searching of google for resolutions after making my
post, sorry for that!

my phone had auto-updated just before this started happening as well.

*Ryan Cutler*
CutlerPhoto.com
[c] 720.507.7926

**Comment by cutlerphoto** [comment]
After uninstalling and reinstalling the newest daily and clicking pair
again, it hasn't alerted me in three hours now though! I believe

**Comment by cutlerphoto** [comment]
It's started disconnecting now, 2 hours down. Restarted phone, bluetooth, updated xdrip+ to Nov. 27th. Has disconnected 4-5 times since pairing new transmitter. Stayed connected fine to my Tandem, though.

**Comment by tolot27** [comment]
@cutlerphoto Could you solve your issue or did you got support at Facebook or gitter?

**Comment by cutlerphoto** [comment]
Hey Mathias,

I actually switched back to my OnePlus 6t and the issues haven't occurred
on that phone.

On my Moto G8 Power (international) - even with newest android updates,
xdrip from 11/24 or whichever is newest stable, it would drop connection
about 4-6 times a day.

Sometimes I could get the connect request to pop up again, but sometimes it
just wouldn't without a restart.

**Comment by tolot27** [comment]
@cutlerphoto Maybe, someone at https://www.facebook.com/groups/xDripG5 or https://gitter.im/jamorham/xDrip-plus can assist you verifying the settings. Please ask their and if nothing helps, we need some debug logs to dig into this problem.

**Comment by Navid200** [comment]
@cutlerphoto Hi,
There should be no frequent pair request as soon as you update to an xDrip release of November 27, 2020 or later.
If you have updated and are still experiencing the pair request, please confirm.
Otherwise, would you please close this issue?

If there is problem with maintaining connectivity, we can help you, but that is a different issue, not related to what is described in the title of this isuue..

**Comment by cutlerphoto** [comment]
It does actually still happen if I'm away from the phone for 5 minutes when it attempts a read. It then fails to bond again without a restart. Airplane mode can also fix it.

**Comment by Navid200** [comment]
The recommended settings, which have helped many if not all:
https://www.facebook.com/groups/xDripG5/permalink/4838757582864365

**Comment by meksor** [comment]
Could I ask you to post these somewhere else than facebook?
People without an account cannot see this...

**Comment by Navid200** [comment]
I am bringing gradually bringing them here:
https://github.com/Navid200/xDrip/wiki

**Comment by meksor** [comment]
Awesome, thank you :heart:
