### ISSUE TITLE
UPLOAD CGM and Carbs FROM XDRIP data TO CARELINK

### ISSUE THREAD

**Issue by henriquejourdan** [NightscoutFoundation/xDrip#1530]
Hi
I'm using libre+ miau miau + 640g + xdrip + nighscout.
My doctor uses carelink portal.
At this point only blood and meal+bolus are avaiable on Carelink: uploaded from bayer USB pen: no CGM.
With this data, reports are very inaccurate.

I would like to upload CGM glucose data + carbs from XDRIP to carelink portal, Is this possible ?

THANKS

**Comment by Navid200** [comment]
@henriquejourdan Can you not use Nightscout for creating reports to submit to your doctor?
That's what most of us do.

**Comment by henriquejourdan** [comment]
Thanks for the reply. 
Did you ever checked the carelink reports?


Also I probably will upgrade from 640 to 780g and there is no way to connect this pump with xdrip.
So I think the easier way is to connect xdrip & carelink portal  to upload cgm and download bolus/blood check before meals.

**Comment by Navid200** [comment]
I have never used carelink.  
Nightscout provides all I need.

But, this is not about whether carelink is better or not.  It is about what is necessary.  
We have a very small number of volunteers who do the development.  

I will add a postpone label to this issue and close it.
This will allow us to reopen when we have addressed more pressing matters, the one's that have no work-around.

**Comment by tolot27** [comment]
@henriquejourdan CareLink only supports Guardian sensors as CGM source and not Libre. It is also not a general resource like Nightscout. If your doctor uses only CareLink and changes your therapy from the linked 640G/Guardian system to the unlinked 640G/Libre devices, he/she cannot accept to see the Libre values in CareLink. In that case, he/she have to use LibreLink. But there is no combined few the data.

**Comment by benceszasz** [comment]
@henriquejourdan your doctor will not be able to see your pump + CGM in CareLink, but there are severeal alternatives:
1) Nightscout online reports: you can upload pump data using 600 series uploader + Libre CGM data using xDrip
2) Nightscout reporter PDF offline reports: if your doctor prefers offline PDF reports you can generate very similar reports with Nightscout reporter (you need to have all your data in Nightscout, same as in case of 1) option)
3) Tidepool telemedicine system: you can upload pump data using Tidepool uploader (very similar to CareLink Uploader) and feed CGM data from xDrip. Your doctor can create a Clinical account and you can share your data with him/her.

**Comment by Navid200** [comment]
I am going to close this because I see no promise that this may even be possible.
I am happy to convert this to a discussion.  Please let me know if you like that.
Or, you can just start a discussions.
