### ISSUE TITLE
Error when I try to start Dexcom G6

### ISSUE THREAD

**Issue by Skyiriz** [NightscoutFoundation/xDrip#1535]
Hi I have the Dexcom G6 but I can't start it because I get an error when I try to start it check this:
![2](https://user-images.githubusercontent.com/59254552/101066234-6ae9b600-3596-11eb-85ad-8fc08c87dd06.jpg)
![3](https://user-images.githubusercontent.com/59254552/101066245-6fae6a00-3596-11eb-9569-ae25d702f51e.jpg)
![1](https://user-images.githubusercontent.com/59254552/101066255-7341f100-3596-11eb-9cd4-36975ca99da9.jpg)
I leave you the logs and my settings:
![11](https://user-images.githubusercontent.com/59254552/101066541-d764b500-3596-11eb-9c82-80fa987246f5.jpg)
![10](https://user-images.githubusercontent.com/59254552/101066550-d92e7880-3596-11eb-9fde-a4c4f6469774.jpg)
my settings are [https://androidaps.readthedocs.io/en/latest/EN/Configuration/xdrip.html#xdrip-settings](this) 
My phone is samsung galaxy s8.

I tried to;

- Stop sensor
- Restart your phone
- Start sensor with code 0000 (four times zero)
- Wait 15 minutes
- Stop sensor
- Start sensor with “real” code (printed on the adhesive protector)

But it didn't help long after a few seconds the problem reappears. Help me pls!!

**Comment by Navid200** [comment]
If you need help bringing your system back up, you should first post on facebook.  
https://www.facebook.com/groups/xDripG5
If it is established that there is an issue with xDrip, only then, should you open an issue here.  You could be waiting here for a very long time for anyone to respond.

**Comment by emp-00** [comment]
@Skyiriz : Have you worked thru this excellent setup guideline? Please do, probably solves your issues: https://androidaps.readthedocs.io/en/latest/EN/Configuration/xdrip.html

**Comment by Skyiriz** [comment]
Yes, as I said above, I used these settings but it didn't help

**Comment by Navid200** [comment]
You explained above that you stopped sensor and then started sensor.  Did you remove the transmitter in between?
