### ISSUE TITLE
Battery Optimization Whitelisting request?

### ISSUE THREAD

**Issue by ANDREAPIPPI** [NightscoutFoundation/xDrip#1536]
Hi. 
I'm using Libre 1 (14 days EU), MiaoMiao1 and xDrip-plus-20200725-67014b0, and suddenly a few days ago, opening xdrip+ it appeared the strange (at least for me) request of a "Battery Optimization Whitelisting", that you can see in the attached image.
I searched among the xdrip+ settings, but didn't find it.
So I updated to latest xDrip-plus-20201127-b978bec release with the hope to solve the issue, but the advice was still there.
Someone has the same issue?
It's very annoying because appears every time I open xdrip, lasting for a few seconds then disappearing.
Thank you.
Bye
Andrea     :-)

![Screen-1](https://user-images.githubusercontent.com/32884006/101104144-c170e780-35ca-11eb-86dd-37983dd25961.jpg)

**Comment by tolot27** [comment]
That's a feature of your phone/Android. You have to turn of battery optimization for xDrip in the system settings.

**Comment by ANDREAPIPPI** [comment]
Thanks a lot, tolot27, it solved.
I'll close this issue, Bye.
Andrea  :-)

**Comment by ANDREAPIPPI** [comment]
Solved.
Closed
