### ISSUE TITLE
Problem with xDrip

### ISSUE THREAD

**Issue by endlesshowl** [NightscoutFoundation/xDrip#1540]
Hello, I just bought a mi band 5 to link up with my fresstyle libre 2. I installed the apk Libre 2 patched. I installed xDrip but when it asks "What type of Libre Bridge device do you use?", it doesn't appear the opcion "Libre2 patched".
What could I do?

Thanks

**Comment by tolot27** [comment]
@endlesshowl You did not mention the xDrip version you are using.
The nightly indeed have this option:

![Screenshot_20201205-141324_xDrip+](https://user-images.githubusercontent.com/1370732/101244035-5c211180-3704-11eb-949d-074a59facaf2.jpg)

**Comment by endlesshowl** [comment]
I downloaded the last version I found, here you have a photo

**Comment by tolot27** [comment]
There is no photo attached. Please do not add fotos. Instead, write the version number here.

You should install the latest version from the [releases page](https://github.com/NightscoutFoundation/xDrip/releases).

**Comment by endlesshowl** [comment]
Sorry; i don't know why the photo is not attached. Here you have the one I downloaded: xDrip-plus-20201127-b978bec.apk

**Comment by tolot27** [comment]
That's the newest version. Indeed, there is "Libre2 (patched App)" listed in the Settings > Hardware Data Source.

**Comment by endlesshowl** [comment]
Thanks!, I could do it the way you say. Now I don't know the next step to link xDrip with the mi band 5..

**Comment by tolot27** [comment]
Sorry, this is not a support forum. Please search the existing issues and ask for help in the Facebook group [xDripG5](https://www.facebook.com/groups/xDripG5) or the Gitter room [xDrip-plus](https://gitter.im/jamorham/xDrip-plus).

**Comment by endlesshowl** [comment]
Ok, thank you for your help anyway
