### ISSUE TITLE
X drip with blucon and US 14 day sensors

### ISSUE THREAD

**Issue by jsmithcpo** [NightscoutFoundation/xDrip#1542]
Let me preface by saying I have no clue what I am doing.  I have a blucon nightrider with an android phone, and android wear watch.  Until a few weeks ago, I was using the combination fine with the blucon app installed on the phone.  My phone died, I got a new one, now I no longer have the blucon app on the watch.  I lost the ability to get my BG readings on my watch.  Stinks.  I used to have a nightscout site I set up and used x drip as a follower, then pinging to my watch.  As the blucon solution was working fine when the M Lab transition happened, I didn't migrate my database.  I was very, very busy and didn't have time to work on it.  Now it's too late.  Is there a way to setup nightscout from scratch(all the links are currently broken, which means I am assuming the guides are broken), or is there a way to setup x drip to pull the readings that the blucon app collects and push them to my watch?  I have no clue what I am doing, I need help.  I'm an average middle aged man with limited technical knowledge.  I tried setting x drip as my software to collect from the blucon.  It pairs to the transmitter fine, but I am assuming because US 14 day sensors are garbage, it is not reading the sensors.  The only readings I get are "low."  Any ideas how to get my BG back on my watch again?  I don't have the cash for new collectors, watches, etc.  Covid has been financially hard.

**Comment by nickb24** [comment]
I would start by posting on Facebook here: https://www.facebook.com/groups/xDripG5
Github issues should be reserved for problems with the application code. I think you would get a lot more support on Facebook than here on Github.

**Comment by tolot27** [comment]
@jsmithcpo nickb24 pointed you to the to the Facebook already. You can also ask at https://gitter.im/jamorham/xDrip-plus.
