### ISSUE TITLE
Xdrip

### ISSUE THREAD

**Issue by fedechan** [NightscoutFoundation/xDrip#1546]
How can I download and install xdrip for iOS

**Comment by nickb24** [comment]
xDrip for iOS does not exist. 
A similar app exists for iOS: https://spike-app.com/

**Comment by tolot27** [comment]
The main page clearly states "xDrip+ is an unofficial and independent Android app ...".

**Comment by tolot27** [comment]
@JohanDegraeve ports xDrip to iOS: [xdripswift](https://github.com/JohanDegraeve/xdripswift)
