### ISSUE TITLE
Hard reset transmitter G6 

### ISSUE THREAD

**Issue by davide1985** [NightscoutFoundation/xDrip#1552]
Hello,
I have to reset the g6 transmitter with 8H serial as more than 100 days have passed since the first start. Is it possible to do it? Thanks

**Comment by JMgithubdex** [comment]
With an 80xxxx or an 81xxxx a "hard reset transmitter" works, but those old transmitters need a new battery first, of course. I use that method since January 2020, with only a few minor problems. It works very well.

**Comment by emp-00** [comment]
@davide1985 : To answer your question- **no**, it is still not possible to "hard reset" 8G,H,J,K etc transmitters. There have been multiple attempts and some progress was reported half a year a go but AFAIK never fully succeeded in a working procedure. Prevented by built-in "security measures".

**Comment by tolot27** [comment]
I've added an entry in the [FAQs](wiki/Frequently-Asked-Questions-(FAQs)).

**Comment by StephenBrown2** [comment]
[Fixed link](https://github.com/NightscoutFoundation/xDrip/wiki/Frequently-Asked-Questions-(FAQs)) (@tolot27's has `issues` in front of `wiki`)

**Comment by tolot27** [comment]
@StephenBrown2 Thanks, I've fixed in inplace. Before, I was using the syntax to auto-generate the link which won't work.

**Comment by davide1985** [comment]
Thanks everyone for the answers
