### ISSUE TITLE
revise source text strings and their translations

### ISSUE THREAD

**Issue by tolot27** [NightscoutFoundation/xDrip#1554]
Some English source text strings contain unusual characters (spaces, quotation marks, smileys, etc.) and should be corrected. Their translations should also checked.

- [ ] remove smileys (sample: [setting_disabled_](https://crowdin.com/translate/xdrip/7/en-de?filter=basic&value=0#q=setting_disabled_))
- [ ] remove bracket artifacts
- [ ] remove unnecessary spaces, especially in URLs
- [ ] revert variable name translations (written within curly brackets `{})
- [ ] try to correct anglicism like denglish
- [ ] disable translations of strings which never appear in the GUI (i. e. title_activity_nav_drawer, navigation_drawer_open and navigation_drawer_close)
- [ ] disable translations of numbers (i. e. zero_zero_zero_zero)

**Comment by tolot27** [comment]
IMHO, we should enable 'Push Sources' at crowdins GitHub integration as well because sometimes, the original English text has to be corrected. In theory, this could produce merge conflicts if the same string is changed by an xDrip PR which is rarely the case.
But if we do not enable it, we will lost the changes made at crowdin or getting out of sync with github, as it happened recently (#1559).

**Comment by jamorham** [comment]
Could you give me an example of the last 4 items so I understand what these mean and what is planned to be changed. Some items might be as they are for a reason.

**Comment by tolot27** [comment]
@jamorham The linked PR contains many of the fixes. Some of the problems listed above were fixed previously. I cannot remember on the anglicism, anymore.

**Comment by tolot27** [comment]
Some of the tasks are still not fixed. I'll check this soon.

**Comment by Navid200** [comment]
Thanks for all the improvements.  
I am closing this issue for now.
Considering there have been two PRs that have been merged since this issue was originally opened, would you please update the description and reopen, or create a new issue to contain only the remaining tasks?

Thanks
