### ISSUE TITLE
Typo on English string

### ISSUE THREAD

**Issue by parapenT1sta** [NightscoutFoundation/xDrip#1559]
Start to work around noisy readings even on very low noise levels (engineering mode **ony**)

https://crowdin.com/translate/xdrip/7/en-pt#2196

**Comment by tolot27** [comment]
Thanks for reporting it. I've fixed this already but it got overwritten by the last sync between crowdin and GitHub.

Please add this information to #1554 and close this issue.

**Comment by tolot27** [comment]
@jamorham If fixed it again in crowdin. Hopefully, "Push Sources" is activated.

**Comment by tolot27** [comment]
Fixed
