### ISSUE TITLE
BG graph is missing in small widget

### ISSUE THREAD

**Issue by Brunchen** [NightscoutFoundation/xDrip#1560]
With the latest xdrip+ ("xDrip-plus-20201218-056b822.apk") I´ve got a problem.
In my xdrip+ widget:
- the white dots and 
- the two lines (for high and low glucose level) dissapeared.

Please look at the picture.
![android](https://user-images.githubusercontent.com/59091948/102686508-74a32880-41e8-11eb-9124-32961518bfe5.jpg)

**Comment by emp-00** [comment]
Just for information - this seems to be an undesired effect of this change in the 2020-12-18 nightly build:
"**Merge pull request #1024 from k2s/widget:
_widget improvements_**"

**Comment by tolot27** [comment]
@k2s Please can you have a look?

**Comment by tolot27** [comment]
It is strange but after installing the "Nightly build 13th Jan 2021" I run into the same problem but for all widget sizes. I've updated all nightly builds in between but never had this problem until today. If I go step-wise back, the graph appears only after installing "Nightly build 16th Dec 2020". Will look into, tomorrow.

**Comment by jamorham** [comment]
This should be resolved in recent nightlies, please confirm thanks

**Comment by cybernissart** [comment]
Graph is effectively back since 2101151518 for small width widgets (2x1,3x1), whereas it was only visible for 4x1 till that build.

**Comment by tolot27** [comment]
Fixed with 1d757ed.
