### ISSUE TITLE
[Feature Request] please add Lyumjev to multiple insulin types

### ISSUE THREAD

**Issue by FreDiabetics** [NightscoutFoundation/xDrip#1561]
More and more people are using Lyumjev that's why I like to have it in xDrip below is the acting profile of Lyumjev peak is about 55 minutes 

![Screenshot_20201220-140451_AndroidAPS.png](https://user-images.githubusercontent.com/45721291/102714142-fec4bd00-42cc-11eb-88ee-7227dfc5fba2.png)

**Comment by tolot27** [comment]
We still need the exact function/values to calculate the maximum and duration of action.

**Comment by Navid200** [comment]
I am closing this issue because we have consolidated all insulin requests: #1898
You can continue the conversation here in this issue about this particular request.

Please don't post in the consolidated table issue. Please either use this issue or [Discussions](https://github.com/Navid200/xDrip/discussions) for any conversations.

**Comment by master3395** [comment]
> Does anyone has access to https://www.healthgrades.com/drugs/lyumjev/pharmacology?

Parameter for Insulin Effect | LYUMJEV7 units | LYUMJEV15 units | LYUMJEV30 units

Time to first measurable effect | ~17 minutes | ~17 minutes | ~15 minutes
Time to peak effect | ~120 minutes | ~138 minutes | ~174 minutes
Time for the effect to return to baseline | ~4.6 hours | ~6.2 hours | ~7.3 hours

![image](https://user-images.githubusercontent.com/4199669/178121503-e3a31745-d640-4978-ade0-3e40edda8f40.png)

Type 1 Diabetes – Adults
Mealtime LYUMJEV + basal insulin | Mealtime HUMALOG + basal insulin | Postmeal LYUMJEV + basal insulin

Number of randomized subjects (N) | 451 | 442 | 329
HbA 1c (%) (mean) a,b
Baseline | 7.3 | 7.3 | 7.4
Adjusted mean change from baseline | -0.12 | -0.04 | 0.1
Estimated treatment difference versus HUMALOG [95% CI] | -0.08 [-0.16, 0.00]c |   | 0.14 [0.05, 0.22]

Type 2 Diabetes – Adults
Mealtime LYUMJEV + basal insulin | Mealtime HUMALOG + basal insulin
Number of randomized subjects (N) | 336 | 337
HbA 1c (%) a,b
Baseline mean | 7.3 | 7.3
Adjusted mean change from baseline | -0.36 | -0.38
Estimated treatment difference versus HUMALOG [95% CI]c | 0.03 [-0.08, 0.13]

![image](https://user-images.githubusercontent.com/4199669/178121621-cc47eded-fc1a-4a5d-a73d-d09d3fd83222.png)

Following a standardized test meal, treatment with Lyumjev demonstrated statistically significantly 
lower 1 hour and 2 hour postprandial glucose. The treatment difference was - 1.34 mmol/L [95 % CI: -
2.00, - 0.68] and -1.54 mmol/L [95 % CI:- 2.37, - 0.72], respectively compared to Humalog

**Comment by rombobellogia** [comment]
Has this not been added yet? If you are aware, could you please link a build in the reply? Thank you all!
