### ISSUE TITLE
Stand-alone Smartwatch for Libre + BluconNightrider

### ISSUE THREAD

**Issue by FHeloise** [NightscoutFoundation/xDrip#1562]
I am trying to select a SmartWatch which would act as a standalone collector for XDrip+ & would not need a phone in range. 

I have read the smartwatch guidance, however wanted to know the minimum requirements for a freestylelibre sensor + bluconnightrider transmitter setup.  I have previously used this combination easily on a Samsung phone, but have switched to an iPhone which obviously doesn’t support XDrip+ (and also has huge bluetooth connectivity issues).  I’ve used Spike, but cannot afford an Apple Watch...

I would like to be able to use just the smartwatch to run Xdrip+ (without having to carry around the spare Samsung).

I understand you need gps + Bluetooth + need to enable force collection, but can the watch have a generic android OS, or would it only work as a standalone device if it runs on Wear OS? 

Many thanks for any advice!

**Comment by tolot27** [comment]
This is neither a bug report nor a feature request. Please ask at the support forums, either at Facebook or Gitter (https://github.com/NightscoutFoundation/xDrip/issues/new/choose).
