### ISSUE TITLE
Automatic update not finding updates anymore

### ISSUE THREAD

**Issue by t1dast** [NightscoutFoundation/xDrip#1563]
### Automatic update does not find updates anymore
When I tap "check for updates", I get a toast message reporting that xdrip checks for updates. After that nothing is happening - although I'm not on the latest build.

### Environment
- The last automatic update that worked was to "Nightly build 27th Nov 2020". I've first realized this a few days ago. Today, I updated to the second-latest nightly (from 16th December). It didn't succeed either to show there is an update to the build from 18th Dec. When I check the logs, I can see it notices a difference to my version on wearos each time I request the update check but no other message show up.
- I'm on a Nokia 7 with December 2020 security patches.

### Expected behavior
In the past, the screen showed up with the option to download the latest version. I'm not sure about the expected behaviour in case there is no update - I'd expect a notification about being up to date.

### Actual behavior
Nothing happens after the initial "Checking for updates .." toast.

**Comment by t1dast** [comment]
I just realized that I was saying "automatic" and described the manual workflow. Needless to say the automatic check does not provide results either.

**Comment by tolot27** [comment]
Do you have your own build of xDrip installed or the public version?

**Comment by Navid200** [comment]
Are you sure you are still on the "Nightly" channel?

**Comment by t1dast** [comment]
I am and have been using the APK published here. I double checked my settings and I am still on nightly.

Is there a log tag I could whitelist to get more detailed log entries?

**Comment by ralf-ms** [comment]
Same here, I've checked that I'm on the nightly channel, but updates will not be found

**Comment by t1dast** [comment]
I've checked the code and added tag filters. Maybe someone can hint me at why I don't get any log entries? I've added "jamorham update:v" but no entries showed up. Anyway, assuming the log just wasn't written but the update check is working, I checked the URL and it seems the service reports the November 27th as the latest nightly!
https://xdrip-plus-updates.appspot.com/update-check/nightly responds:

> 2011270800
> https://github.com/NightscoutFoundation/xDrip/releases/download/2020.11.27/xDrip-plus-20201127-b978bec.apk?
> 11716485
> 
> 6726580bc7ef215fd0c79859ccf9ea0b381fc9bd99210de8f64d7ad06e55a12c

**Comment by tolot27** [comment]
@jamorham It looks like your [update-check](https://xdrip-plus-updates.appspot.com/update-check) does not work correctly. I thought it only provides updates till `2011270800` because I added a warning to the release of 2020.12.10. But after removal of this warning, the update-check did not recognize newer releases.

**Comment by tolot27** [comment]
jamorham posted at gitter: "Recent changes to the CI server caused the issue, the nightly update channel should be working again now."
I can confirm that it works, now.
