### ISSUE TITLE
xDrip application stops receiving data

### ISSUE THREAD

**Issue by alxsimo** [NightscoutFoundation/xDrip#1566]
### Subject of the issue
xDrip foreground services seems to stop, no data is received in xDrip.

### Your environment
**xDrip version:** 2020.12.18
**Datasource:** Libre2 (patched app)
**Device:** Xiaomi Mi9

### Expected behavior
xDrip app should keep running in background, receive and show data sent by the Libre2 (patched) app.

### Actual behavior
In Events log shows this:

**FOREGROUND**
```
Got exception trying to use Android 10+ service starting for DoNothingService java.lang.IllegalArgumentException:
foregroundServiceType 0x00000008 is not a subset of foregroundServiceType attribute 0x00000000 in service element of manifest file
```

### Screenshots

<img src="https://user-images.githubusercontent.com/579465/102773956-59701e80-438a-11eb-8a6d-610eafe2a443.png" width="250" />

**Comment by tolot27** [comment]
Which is the latest working version?

**Comment by tolot27** [comment]
The exception can be fixed, easily. But I'm unsure whether this fixes the problem of not receiving data.

**Comment by alxsimo** [comment]
@tolot27 sorry but cannot remember, I always try to stay updated with the latest nightly

Maybe getting the service not killed by Android is a first step. I'll happily add any needed info,

**Comment by tim162** [comment]
I am having the exact same bug on Samsung Galaxy A50 @Android 10 and Libre2 patched app. I'm currently using my own build but it's based on the latest commit to master branch that was done 3 days ago. This is when the bug started to appear, I haven't figured out if it's triggered by anything as sometimes it doesn't occur for several hours and sometimes it occurs several minutes after one another.

**Comment by alxsimo** [comment]
Yes, thanks also for the report @tim162, same behavior for me

**Comment by tolot27** [comment]
@tim162 Please can you merge PR #1568 into your build and test whether it works?
