### ISSUE TITLE
HOW TO UPGRADE XDRIP?

### ISSUE THREAD

**Issue by Marcio261** [NightscoutFoundation/xDrip#1570]
Hi folks, 
I want to know how do you guys upgrade your xdrip versions? Do you just select the option "search upgrade" and its automatically transfered, or do i need to transfer the new version and uninstall the older one?
I exported my database(from the older version) and transfered the newest version and install it. But when i tried to import the data(exported from the older version) into the newest, it did nothing, and i think i have already lost all of my Database :(
Pls can you tell me the right way to upgrade?
Thanks you since now :)

**Comment by tolot27** [comment]
This is neither a bug report nor a feature request. Please ask at the support forums, either at Facebook or Gitter (https://github.com/NightscoutFoundation/xDrip/issues/new/choose).

Just do "Check for updated version" and install it. It is always wise to do a backup of the database and settings beforehand.
