### ISSUE TITLE
Crash on sensor start

### ISSUE THREAD

**Issue by JelmerFokkema** [NightscoutFoundation/xDrip#1572]
OnePlus 7pro
Android 10
Latest 3 nightly,s 

App crashes on sensor start, perfectly repeatable on every type of sensor input Oop2 or not doesn't seem to matter. Erasing app memory clears the problem.

**Comment by emp-00** [comment]
Can you post the error messages you are getting and the xDrip Event Log after the app "crashes"? What does "Oop2" mean? More information needed.

**Comment by JelmerFokkema** [comment]
Hi and Merry Christmas

Oop2 is the external algorithm for libre2 sensors.
I,ll try and post a error log later. Went back to te G6 and killed the
Libre2 because of skin/tissue issues. Problem is that when the app dies the
only solution is to reinstall or erase memory.

Latest release works perfectly with the Dexcom G6 by the way.. It actually
automatically started the sensor on takeover.

Thanks,

Regards Jelmer

Op vr 25 dec. 2020 17:09 schreef emp-00 <notifications@github.com>:

**Comment by MarvelousMarvin** [comment]
Dexcom g6 sensor start let's xdrip 23 december crash. Going back to 27 November solved the problem for me. Same issue.

**Comment by JelmerFokkema** [comment]
Problem appears to be in the Dutch translation. Being pointed to this by a fellow Dutch Xdrip user it seems native English don't have the problem. Simply setting the slider to English seems to be enough. 
![Screenshot_20210101-112454](https://user-images.githubusercontent.com/51903932/103437260-c35bb400-4c25-11eb-9ae1-a19b0258b1da.jpg)

**Comment by jamorham** [comment]
At what point exactly do you get the crash? When the Sensor Start menu item is used or after readings start?

**Comment by JelmerFokkema** [comment]
Literally the moment you press start sensor. It's perfectly repeatable with every sensor type. Only a automatic G6 start (great new feature) didn't cause the problem. 
As said above switch to English and nothing seems wrong

**Comment by jamorham** [comment]
Okay, I'm on it.

**Comment by jamorham** [comment]
Can you try the latest nightly and let me know if that resolves the issue. Many thanks

**Comment by MarvelousMarvin** [comment]
![Screenshot_20210103_172350_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/40701484/103483603-a8856d00-4de8-11eb-9540-b44b89591d70.jpg)
Looks like the crash issue has been resolved

**Comment by JelmerFokkema** [comment]
@jamorham great work mate all appears to be well again 👍

**Comment by tolot27** [comment]
But the deadlock itself is not solved.

**Comment by JelmerFokkema** [comment]
You want to reopen? I have had no deadlock issues at all.

**Comment by tolot27** [comment]
> I have had no deadlock issues at all.

@JelmerFokkema So you don't get the deadlock messages in the error log, as @MarvelousMarvin gets?

**Comment by JelmerFokkema** [comment]
No deadlock at all. So my issue was completed. Marvin I think is running the app without problem now also not having to revert to 27/11 again. 

Thanks for the support

**Comment by MarvelousMarvin** [comment]
![Screenshot_20210104_102347_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/40701484/103520189-0c567700-4e77-11eb-827d-c3b0a24fd6d8.jpg)
Haven't got any deadlock issues in the past hours.
