### ISSUE TITLE
xDrip cannot start a G6 sensor in no-code mode with a new (8J) transmitter

### ISSUE THREAD

**Issue by Navid200** [NightscoutFoundation/xDrip#1573]
xDrip version: July 25, 2020
Dexcom G6
Transmitter serial number: 8J****
Phone (Android 9) runs xDrip as the collector

We were able to run in no-code mode, using xDrip, by entering 0000 as the calibration code.  I did that whenever I restarted my sensors with my 81 transmitters.  

With newer transmitters (I have tried 8J), after entering 0000 as the calibration code, no readings are ever provided after the warm-up period, and the transmitter eventually issues an error.

The Dexcom app can start a sensor (with new transmitter) in no-code mode apparently.  I personally have no experience with that app.  It would be great to be able to do the same using xDrip.

**Comment by emp-00** [comment]
@Navid200 : Is there a good reason for using "0000" as calibration code? As you know - All 8G+ (Firefly) transmitters can only be used in "Native Mode" anyway - therefore the sensor needs the calibration code to be able to show "correct" BG values. 

Manual calibration in xDrip (non-native mode like with 80/81 tx's) does NOT work anymore with these transmitters so you must calibrate them natively in the transmitter... I always use the factory code also for restarts => no problems. Only need to calibrate once after the restart since values are always consistently too high, e.g. 130-150 instead of real 100 mg/dl (due to built-in trauma compensation). One single calibration fixes this issue for me.

**Comment by Navid200** [comment]
@emp-00 
Yes, there is.
In no-code mode, G6 behaves as a G5.  Hence, the factory calibration, which is only valid for the first 10 days becomes disabled in no-code mode.  
The Dexcom app offers that.  So, the fact that the transmitter is limited to Native mode is irrelevant.  The transmitter is in Native mode and in no-code mode, it behaves as a G5 with the Dexcom app.

I would like xDrip code to be modified so that it can offer the same capability to those who use xDrip.

I enter the code also and calibrate to correct the significant, dangerous error because that's all I can do. 
But, there is no reason not to improve things.  That's the purpose of these issues, isn't it?

There is a very good reason to fix this bug.
I always worry someone may inject insulin, not realizing the error, and cause a hypo.

**Comment by emp-00** [comment]
@Navid200 : Sorry, I was not aware this is still possible with the 8G+ transmitters. 

However, I still don't understand the reason for doing this. Does this avoid the "BG jump" (trauma compensation)? I think you need to calibrate anyway - for sure anyway in non-native mode... So why not running native and using the factory calibration code? For me this works fine - only one calibration needed after restart and that's it. When restarting I guess everybody is aware of "the side-effects". Doesn't non-native mode have more chances for calibration errors? At least this is my personal experience -> been running 80/81 (non-native) and G6+ tx's. Native works much better for me. But OK, that's just my view of things. If there's a need for fixing this as requested - fine!

**Comment by Navid200** [comment]
Yes, it avoids the BG jump.  The trauma existed even with G5.  But, G5 did not offer factory calibration.
The only reason you get the jump in readings when you use the original code with a sensor that is not new is that the factory calibration engages starting from day 1 when you are really on day 11.

When you operate in the no-code mode, G6 behaves as if it was G5 relying on daily calibrations.  In that mode, G5 asked for a new calibration once every 12 hours.  G6 asks for one calibration a day in no-code mode.

So, if this is fixed for xDrip, the user will have options, each with its pros and cons:
1- No-code mode where you will have to calibrate once a day when you restart (and twice a day for the first day)
2- Use the code and make sure to correct the significant error before engaging your closed loop system.  Otherwise, you are up for a serious hypo episode.

I don't understand why you keep bringing up native versus non-native.  This request has nothing to do with that.  This request is related to Native mode only.  There is no other option since the transmitter does not send raw data.

**Comment by nickb24** [comment]
@Navid200 After the warm up period with a no-code start, do you get a calibration error when trying to calibrate? 

I too like to restart my sensors after 10 days using the no-code. The issue I have is calibration errors. After some debugging I determined it's not the xDrip app, but the new firmware on the firefly transmitters. Using the Dexcom app also gives the same calibration errors. It doesn't happen every time I do a sensor restart, but it happens often.

**Comment by Navid200** [comment]
Please have a look at the Dexcom G6 user guide.

https://s3-us-west-2.amazonaws.com/dexcompdf/G6-CGM-Users-Guide.pdf

Please go to section 7.4 Calibrating
You will see the following followed by more detail about the no-code operation.

"If you didn’t enter a sensor code, you’ll need to do daily calibrations after completing
your initial calibrations".

Since it is in the manual, one can contact Dexcom and ask for a replacement if the transmitter is really the culprit.


Going back to your first question, it's been a long time since I tried this.  So, I am not 100% sure.  But, I believe the error was obvious right away after the warm-up period was over.
In case you are wondering why I have opened this case now if it has been a while, I was told by Jon that he suspected this was due to more security measures, for anti restart, Dexcom has put into their new transmitters.

I wanted this to be on the record because I see people recommending code 0000 for new transmitters on facebook.  I want the issue to be on the record so that I can refer people to it if they ask me for a record of the problem.  So, thanks for sharing your experience.

**Comment by nickb24** [comment]
@Navid200 If you can confirm that the error recieved after the warmup is a calibration error, then I can confirm this is not an xDrip error. Therefore this issue can be closed because there is nothing that can be done in the xDrip code.

Unless there was a way to overcome the error, but for that we need more information from users. For myself I can confirm that I was able to overcome the error and successfully get readings after a no code restart. I took about 1-2 hours after the warmup but it finally accepts the calibration values and then starts to work. I think what finally did it was to enter 3 glucose values at the same time with all the same value. You need to check the transmitter queue in the status page that shows 3 values in the queue before it makes the next connection. I'm not sure if it was just random luck or not so more testing is needed. 

Perhaps better user error codes are needed. The calibration error code in xDrip is too genetic. When I got the code I stopped the xDrip app and started the Dexcom app. It connected and then showed me a more clear message. Something like calibration rejected please wait until xxxx time to try again (which was 15 mins in the future). Even trying to calibrate with the Dexcom app would continue to result in an error and telling me to wait. However after an hour I tried to calibrate again and that time it worked.

**Comment by emp-00** [comment]
I second the proposal "_Perhaps better user error codes are needed._" @nickb24 - your concrete proposal adding "Please wait at least 15mins before entering another calibration" to the xDrip error message makes perfect sense to me and should be very easy to implement. This could be a concrete action item from this issue. Agreed?

**Comment by nickb24** [comment]
> I second the proposal "_Perhaps better user error codes are needed._" @nickb24 - your concrete proposal adding "Please wait at least 15mins before entering another calibration" to the xDrip error message makes perfect sense to me and should be very easy to implement. This could be a concrete action item from this issue. Agreed?

I agree that better error messages should be displayed like it is on the Dexcom app. I will take a look at the decompiled Dexcom code and see if there is a clear 1 to 1 relationship with the error code and the text displayed to the user. I want to make sure that if xDrip reads error code 1 for example from the transmitter that it will always equal to the same text message to display to the user. I don't want a situation where for example error code 1 would equal different error messages depending on the state of the transmitter (warming up, after a warm up, after warmup from a no-code, etc).

**Comment by nickb24** [comment]
I've completed a preliminary analysis. Comparing the code here [https://github.com/NightscoutFoundation/xDrip/blob/master/app/src/main/java/com/eveningoutpost/dexdrip/G5Model/CalibrationState.java](https://github.com/NightscoutFoundation/xDrip/blob/master/app/src/main/java/com/eveningoutpost/dexdrip/G5Model/CalibrationState.java)

With the following from the Dexcom code:
![image](https://user-images.githubusercontent.com/2193756/103367458-1fda9a00-4a93-11eb-86f9-a5f5bfc529e8.png)

I've found a few error messages that should be cleaned up. For example:
SensorFailedStart with hex code 0x16 is actually listed in the Decom code as SensorFailed**DueToRestart**. xDrip only shows the error as "Sensor Failed Start". Adding the part about Restart would be a good addition.

**Comment by emp-00** [comment]
Many thanks & appreciated! Could you develop this further into a Pull Request?

**Comment by nickb24** [comment]
> Many thanks & appreciated! Could you develop this further into a Pull Request?

I'm working on it now. But I will need to see how this effects the G5 and non-firefly G6.
https://github.com/nickb24/xDrip/tree/g6_error_msg

**Comment by Navid200** [comment]
@nickb24 If the problem is using no-code after a restart only, using no-code with a new sensor should work fine with no errors.  

In 7 days, I will restart using 0000 and report what error I get.
5 to 10 days after that, I will start a new sensor with 0000 and report if I get any errors.

**Comment by Navid200** [comment]
I just successfully restarted using 0000 through xDrip.  It is currently working fine in no-code mode after the 2-hour warm-up.  So far, there have been three consecutive readings.

The only thing I did differently this time is that I re-enabled "Double Calibration" under Advanced Calibrations.  Previously, I had it disabled when a restart with code 0000 had failed.

Please let me monitor this for the next 24 hours to confirm that everything is working.  I will then close this.

**Comment by Navid200** [comment]
Woke up this morning with no readings.  Was shocked to see there was no connectivity.  This has never happened to me with a G6 that I can recall.

The event logs don't show anything I can recognize.  At 1:38, there is a log that I don't understand.  At 1:53, there is "Error count Error count reached: 2".  And at 1:55, I see the first log that shows there is no connectivity.

I tapped on "Forget Device", and the connectivity was re-established and I saw a message on screen that calibration is needed.  

At this point, I went to settings and disabled double calibration.  I then used initial calibration from the top-left menu of xDrip to enter a single calibration, which went through with the usual errors I always get when calibrating a new G6.

Everything seems to be OK again.

![3](https://user-images.githubusercontent.com/51497406/103654147-81878200-4f33-11eb-8bb2-24b608fec350.png)
![4](https://user-images.githubusercontent.com/51497406/103654149-81878200-4f33-11eb-8b02-d67a39340a95.png)
![5](https://user-images.githubusercontent.com/51497406/103654150-82201880-4f33-11eb-96bc-b99757f05345.png)

**Comment by nickb24** [comment]
I see you have the issue described here #1279 but I'm not sure if that's why you weren't getting any glucose values.

At 1:38 the session start time was reported from the transmitter, therefore it was communicating with the transmitter. Did you receive glucose values at that time?

To get a better idea of what's going on it would be best to enable the extra debug information as seen here: https://github.com/NightscoutFoundation/xDrip/wiki/Enabling-Debugging-for-OB1-collector

**Comment by Navid200** [comment]
@nickb24 As far as I know, everyone has that issue.  Don't you?  
I have not seen one log from a new G6 that does not show those messages consistently every 5 minutes.

The last reading was at 1:42.

Thanks for the link to how to enable the extra debug.

**Comment by nickb24** [comment]
@Navid200 I've been running my own version with this PR applied: https://github.com/NightscoutFoundation/xDrip/pull/1551
I've been running it for 2 months now with no issues and my logs don't have the error message. 

If you run the app with the extra debug logs, that would help in diagnosing the issue if it happens again. You can turn it off after.

**Comment by Navid200** [comment]
@nickb24 Thanks.

The link tells me I can enable the extra logs by scanning.  But, it doesn't say how I can disable it.  How can I disable it when I am done?

**Comment by nickb24** [comment]
@Navid200 Go to Settings -> Less common settings -> Extra Logging Settings -> Extra tags for logging
Delete all the tags shown there and press ok.

**Comment by Navid200** [comment]
Multiple people, including myself, have successfully restarted a G6 (8J****, 8L****, and 8Q****) using the 0000 code.
That's why I closed this issue.
