### ISSUE TITLE
Skagen Falster 3 Smartwatch Patch

### ISSUE THREAD

**Issue by cjkoral** [NightscoutFoundation/xDrip#1576]
The Skagen Falster 3 cannot be used as a collector

I would like a patch for the device to alleviate the bugs present in wearOS devices described in the wiki

My alternative currently is to not use the device as a collector

What would be helpful information for me to add to facilitate this request?

**Comment by jlecount** [comment]
Is there any objection to this patch?  I was looking to get this watch at some point if xdrip supported it...

**Comment by tolot27** [comment]
@cjkoral Please can you link the bugs you are observing?

**Comment by cjkoral** [comment]
The top log here is what I get if I try to force it as a collector. @tolot27 

![Screenshot_20210808-192324](https://user-images.githubusercontent.com/12025464/128652244-3ce3367e-3129-4a87-8b74-7073ba89e308.png)

**Comment by tolot27** [comment]
We still don't know anything about your environment (Android/WearOS version, xDrip version, Phone).
Did you sideload the wear apk? What is the watch showing?

**Comment by cjkoral** [comment]
@tolot27 

WearOS = 2.50.0.386517539.gme
Android = Pixel 4 Android V 11

**Comment by tolot27** [comment]
@cjkoral xDrip version? Side loaded? Does xDrip wear runs fine so far?

**Comment by cjkoral** [comment]
@tolot27 sorry, clicked enter early. see above

**Comment by tolot27** [comment]
Did you asked for support in the xDripG5 group at Facebook (https://www.facebook.com/groups/xDripG5) or the Gitter room at https://gitter.im/jamorham/xDrip-plus? If not, please ask their, first.

**Comment by tolot27** [comment]
Please disable any calibration settings on both phone and watch.

Also, we still don't know which sensor do you use. Dexcom G5/G6 or Libre 1/2/US/Pro?

**Comment by cjkoral** [comment]
Oh yah, G6.

and i just turned all the calibration settings off.

**Comment by cjkoral** [comment]
@tolot27 I checked in the group and others have had the same experience with the Falster 3 not being able to be used as a stand alone collector. There was no workaround that anyone had found thus far.

**Comment by tolot27** [comment]
It is hardly possible to support every watch and without having a specific model causing trouble it is impossible to debug.
Either you and the other users at Facebook can narrow it down further or we cannot suuport it.
Please also try to disable the phone collector. The error message shown at the screenshot is caused by syncing the data from wear to App and is not related to the wear collector. We need some logs of the wear, not from the phone.

**Comment by Navid200** [comment]
Consolidated all watch support requests: https://github.com/NightscoutFoundation/xDrip/issues/1872
