### ISSUE TITLE
treatment bg values are silently used for calibration despite answering "no" or setting to "never"

### ISSUE THREAD

**Issue by gfornax** [NightscoutFoundation/xDrip#1580]
Like the headline says, my xdrip uses treatment bg values for calibration no matter what I do.
I noticed this several months ago but stopped caring about it since the G6 calibration still seems broken and doesn't work for me since the firefly transmitters. Maybe this affects other data sources as well.
Nonetheless, it is a major safety issue, as usually users have a good reason for not wanting a certain treatment value to be used for calibration - e.g., when they now the slope is very high. I personally ended up with some sensors that were dangerously off due to this bug.

### environment
same on stable releases, 20200713 nightly , 20201001 nightly, 20210217 nightly.
Dexcom G6 native, 8H transmitter.
Setting "Use Treatment BG values" set to "Ask me every time" or "Never use them"
Automatic Calibration off
no Calibration Plugin
Using mg/dl

### Expected behavior
If I answer the dialogue with "No" or set the setting to "Never", I expect a treatment BG value to show up on the graph and nothing else.

### Actual behavior
After entering the value, instantly there is a calibration inserted to the queue items. And this is (as long as it was still working with the older transmitters) actually sent to the transmitter.

### Steps to reproduce the behavior:
Set settings like described above
Main screen, tap treatment, select fingertip button, enter a value, confirm
If xdrip is configured to "ask", select "No" in the dialogue box.
Check "System Status", calibration is queued.

**Comment by Navid200** [comment]
Can you try this with a more recent release?  For example, January 29, 2021.

**Comment by Navid200** [comment]
Are you sure calibrations are submitted to the transmitter.  Do you see the log saying calibration was accepted by the transmitter?

**Comment by gfornax** [comment]
I just tried with the latest nightly build. It still happens, I can answer both questions with a definite yes.
Despite answering "no" and despite xdrip showing the _Sensor data fails sanity test - Cannot Calibrate! raw:-0.1..._ message.
The calibration is shown right after the next sync in the dexcom transmitter.

**Comment by Navid200** [comment]
Would you mind posting a screenshot that shows the receiver showing the result of the calibration?

**Comment by gfornax** [comment]
Sure, here you are. Oh and it is already up now, no worries.

![IMG_20210223_183010](https://user-images.githubusercontent.com/5310025/108883291-8ef0ec80-7605-11eb-9b49-fe699ca55414.jpg)
![Screenshot_2021-02-23-18-30-20-899_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/5310025/108883334-9c0ddb80-7605-11eb-9ba0-0505358d62dc.jpg)

**Comment by Navid200** [comment]
I thought your readings show a jump, which you concluded was caused by the calibration.  But, you are showing some logs.
Would you please explain how you conclude from the log from the receiver, you are showing, that the transmitter has received a calibration?

**Comment by Navid200** [comment]
Would you also please show (or tell us) the firmware version of your transmitter?

**Comment by gfornax** [comment]
I attached the log as well so you can see what happend in xdrip where I entered the BG reading..

Let me just translate what you see in the first picture with the dexcom receiver (where I did NOT enter a calibration):
```
Time of insertion
Sensor expiration time
Last calibration
Last calibration value
```
So by the last two lines, you can see the Dexcom receiver shows the BG reading I entered in xdrip, but chose to be discarded.
Dexcom Receiver FW is 5.1.2.0.26, Transmitter FW is 2.18.2.98

**Comment by Navid200** [comment]
Thanks.  Have no idea why the calibration is sent even though when you have disabled automatic calibration.
Let's wait for someone who knows to respond.

**Comment by Navid200** [comment]
We may indeed have a bug.  But, instead of focusing on fixing the bug, I'd rather focus on making sure no more calibrations are sent to your transmitter unless you intend to do that.  
My suggestion is the following:

Uncheck the following
Settings -> Less common settings -> Advanced Calibration -> Automatic Calibration

On the same page, tap on "Use Treatment BG Values".
Check "Automatic mode".

**Comment by gfornax** [comment]
No worries, since I know about it my workaround is to not enter BG values in xdrip and use the dexcom device for calibration.
What makes this bug dangerous is that it can really take a while until you realize what actually happens.
If there are things I can try to provide more details for looking into it just let me know, I'll be happy to help.

**Comment by Navid200** [comment]
I am not a developer.  There aren't many.  They can ask you for detail in order to solve this.

What I know is that every time you send an unintended calibration to an 8H transmitter, you are rolling the dice!  If the transmitter has a fit, and believe me it can, you will have no readings possibly for hours.
What I suggested should stop your BG treatment values to be sent as calibrations.

Your first post says that you are using October 1, 2020 release.
I also recommend that you upgrade your xDrip to the November 27, 2020 release.

**Comment by gfornax** [comment]
Agree, I'll give it a shot next time it is necessary.
I updated the initial post as I have used the Feb 17 2021 release today for the confirmation.

**Comment by Navid200** [comment]
@gfornax Can you try the release of April 11, 2022 or more recent and see if you still experience this?

**Comment by gfornax** [comment]
@Navid200 confirmed, still happening with nightly build from May 3rd 2022

**Comment by Navid200** [comment]
Thanks for testing.
Would you please show this page so that we can see your settings?
![Screenshot_20220503-100827](https://user-images.githubusercontent.com/51497406/166469351-3f2e24eb-e5e4-49f3-978f-ef40841eacf4.png)

**Comment by gfornax** [comment]
It was set to "Ask me every time" and I answered the prompt with "no" (do not use the value)

**Comment by Navid200** [comment]
@gfornax Thanks.
Would you please show a screenshot of the logs corresponding to when it happened?
Please blackout any user IDs that may appear in the logs.

**Comment by Navid200** [comment]
@gfornax Never mind.  I just tested and can see the problem.  Thanks so much for reporting this.  I will open a PR to fix this.

**Comment by Navid200** [comment]
@gfornax Would you please try the release: May 6, 2022:
https://github.com/NightscoutFoundation/xDrip/releases/tag/2022.05.06
and let me know in case you still experience this problem?
