### ISSUE TITLE
FR: Change percentage of low battery indication/info

### ISSUE THREAD

**Issue by ARkaine2** [NightscoutFoundation/xDrip#1585]
<details><summary>This one:</summary>
<p>

![photo_2021-01-03_00-43-09](https://user-images.githubusercontent.com/31447095/103468530-8a752980-4d62-11eb-9c9c-69d524288438.jpg)

</p>
</details>

Please.
Thanks.

**Comment by tolot27** [comment]
Please can you describe your feature request in more detail?

**Comment by ARkaine2** [comment]
**tolot27**,
I mean that when it becomes 25% of transmitter's battery charge, text is getting red.

I'd wish to specify (for example) 10% to indicate (become red when it's) low battery charge.
-- in similar way as we can specify low battery charge in alerts settings.
Probably it should be in another section of settings (maybe somewhere in graphic changes).

**Comment by Navid200** [comment]
So, you can get an alarm exactly at your chosen percentage.
But, that's not enough.  
You want to change the color of the battery voltage on the system status page as your chosen percentage.
Is that right?

Can you explain how/why this is a requirement?

**Comment by Navid200** [comment]
I am postponing this. 
In absence of a response to my question for clarification, I have to assume this is a nice-to-have rather than a necessity.
We will get to these issues when the time is right.
