### ISSUE TITLE
Xdrip stops receiving data from G6 after Bluetooth failed to register error and requires reboot.

### ISSUE THREAD

**Issue by jredders** [NightscoutFoundation/xDrip#1587]
### Subject of the issue
The latest nightly (and the previous few) stop receiving data from my Dexcom G6 after 6-24 hours and the G5/G6 Status Bluetooth Link: shows "Failed to register application for bluetooth scan" in red.

### Your environment
- What version of xDrip.
c6c289d-2021.01.03 
- What type of hardware data source and how do you get your data there
Dexcom G6 8Mxxxxx transmitter
- Is your issue specific to a device like and Android phone or a smartwatch?
Google Pixel 4A running Android 11 December 5 and now January 5 security patch
- All settings related to the issue, e.g. activated auto calibration.
G5/G6 Debug Settings (all others not listed are disabled)
[x] Use the OB1 Collector
[x] Native Algorithm
[x] Minimize Scanning
[x] G6 Support
[x] Allow OB1 unbonding
[x] Allow OB1 to initiate bonding
Bluetooth Settings (all others not listed are disabled)
[x] Turn Bluetooth on
[x] Bluetooth Watchdog
[x] G5 Bluetooth Watchdog
[x] Trust Auto-Connect
[x] Use Background Scans
[x] Allow blucon unbonding

### Expected behavior
XDrip should keep receiving data from G6 device.

### Actual behavior
XDrip fails to receive data from G6 device after 6-24 hours with the "Failed to register application for bluetooth scan" and requires a phone reboot to begin receiving data again.

### Steps to reproduce the behavior:
Let XDrip run.
It seems like going out of range, so that a reading is missed can trigger it sometimes, but not always.  Also, pairing bluetooth headphones or a heart-rate monitor can also trigger it sometimes.  Seems like anything that changes bluetooth on the phone in some way can be the trigger.

NOTE: I uploaded LOGs showing this happening over multiple reboots.

**Comment by nickb24** [comment]
I am running a Pixel 2 with the following settings that are different from yours if you want to try:

1. [ ] Minimize Scanning
2. [ ] Bluetooth Watchdog
3. [ ] G5 Bluetooth Watchdog
4. [x] Close GATT on BLE disconnect

**Comment by jredders** [comment]
I'll try those settings and see what happens.  It would be really nice if there was a Wiki page somewhere that people could submit their working Phone + CGM maker/rev + settings.

**Comment by Navid200** [comment]
@jredders 
These settings are working for almost all phones.
https://www.facebook.com/groups/xDripG5/permalink/4603084736431652

**Comment by jredders** [comment]
@Navid200 Thanks!
For the Default Bluetooth Settings for Dexcom G5 and G6 https://www.facebook.com/groups/xDripG5/permalink/4539569289449864,
Does the G5 Bluetooth Watchdog still need to be on when using a G6?

For the G5/G6 Debug Settings page for Dexcom G6 https://www.facebook.com/groups/xDripG5/permalink/4651137871626338, you should tell people to click into the Preemptive restarts and make sure it's disabled, since it's not obvious at all and if you had a G5 running native mode before, you might have had it on.

**Comment by Navid200** [comment]
G5 Bluetooth Watchdog is set even for G6.

Yes, it is unfortunate that the preemptive restart setting is not visible.  That is why I opened this bug:
https://github.com/NightscoutFoundation/xDrip/issues/1528

There is a lot of information that we can give people.
For example:
https://www.facebook.com/groups/xDripG5/permalink/4612029002203892

But, I often get people who are really in a panic.  One of my objectives, on facebook, is to support individuals who need help but are not very tech savvy.  Think of a diabetic single mother who is trying to feed the kid and also prepare for tomorrows work etc. and have their sensor stop working.

When I write something, I need to avoid driving people away by making it too complicated or too long.
So, I agree with you that is a very important piece of information.  But, there is a lot more and I have to draw the line somewhere.

**Comment by jredders** [comment]
Oh I completely understand.  I'm a computer engineer and I still have problems keeping this all working. :)

**Comment by Navid200** [comment]
Are there still any problems?

**Comment by jredders** [comment]
I have not seen any "Failed to register application for bluetooth scan" errors since I disabled Minimize Scanning yesterday.

However, I also realized I had enabled WearOS integration when I was playing around with an old WearOS watch to see if they had made enough improvements lately to look at it again (they haven't), so I also disabled that and unistalled WearOS.  So, it could have been related to having WearOS and Garmin connected or WearOS enabled but no watch connected (battery is dead after a day+ of non-use).

Finally, the sensor has been in it's death throws of tons of sensor errors and I just haven't gotten around to changing it yet.  I'll let you know if I see any issues once I start the new sensor later today.

**Comment by jredders** [comment]
Well, my sensor came back from the dead last night, so I didn't change it and this morning I just lost G6 readings 30 minutes ago and the status is the dreaded "Failed to register application for bluetooth scan".  So, it seems that the turning off Minimize Scanning reduces the occurrence, but does not fix the problem.

**Comment by Navid200** [comment]
Does a phone restart always brings it back?

Did you follow all the steps on facebook?
https://www.facebook.com/groups/xDripG5/permalink/4603084736431652

What do event logs show?

**Comment by jredders** [comment]
So, I realized this happened because my Garmin 645 watch vibrates when it loses Bluetooth connection.  While XDrip was showing the error, my Garmin Connect software was also unable to talk to my watch.  I manually turned off Bluetooth and turned it back on.  After a little while, the Garmin reconnected, but XDrip was still still showing the error.  I manually force-stopped XDrip and then restarted the collector and it eventually started working again.

Looking through the logs it's been dorked since 1 AM last night and has been attempting to stop/re-start bluetooth a whole bunch of times since then.  It basically got no data from 1-9 AM (then backfilled to 6 AM), which happens to coincide with when I was sleeping.  I wonder if this is a phone deep-sleeping problem?  I have XDrip set to not-optimized, but it's rather a strange coincidence that it all started when I set the phone down and went to sleep and was able to get things working again when I woke up and picked up the phone.  The death at 10AM also coincides with the phone having been set down for a while.

**Comment by Navid200** [comment]
There is a lot we can talk about on facebook.  There are existing posts I can refer you to.
Depending on the phone, there are additional settings that need to be set other than disabling battery optimization.

If you establish there is a problem with the code, then you can come here and open an issue.

**Comment by leonbohmann** [comment]
Could any one of you post the steps described in your facebook? I dont have facebook so I cant view the pages you supplied..

**Comment by Navid200** [comment]
@leonbohmann Hi,
I can.  But, ...

There is a place and purpose for the facebook group.  And there is one for Github.
May I ask why you cannot create a facebook account?  You don't have to install it on a mobile.  You can have it only on your desktop or laptop or ipad.
You don't have to live on facebook.  Only use it to access this page about xDrip.  I know many people hate facebook.  I have issues with facebook myself.  But, I don't understand why it has to be so black and white.

If you ask why not explain everything here, my answer is that , at least the way I understand it, this here is meant to be a place where we open issues for the developers to fix the code.  
It is not meant to be used as a forum to share experiences and ask for help.  That's what facebook is meant for.  I don't want to encourage the practice of opening an issue here as soon as someone has a problem using xDrip.

**Comment by jredders** [comment]
Note: This could possibly be related to this recent memory leak fix in RxAndroidBle https://github.com/Polidea/RxAndroidBle/commit/75b854fa028380d0d6cb44ec9c4c2f27ac5533bf
See this note here: https://github.com/Polidea/RxAndroidBle/issues/607#issuecomment-575131202
They have not released a new version since the commit of the fix though.

**Comment by leonbohmann** [comment]
> It is not meant to be used as a forum to share experiences and ask for help. That's what facebook is meant for. I don't want to encourage the practice of opening an issue here as soon as someone has a problem using xDrip.

As long as your answer helps to provide a solution to the initial (actual) programming-related issue posted by @jredders it is perfectly valid to discuss the solution in here, without having to use facebook. In this case its not even about facebook, why not just post the solution here so everybody on github can access it?

**Comment by jredders** [comment]
Well, I can tell you that the "solution" provided on Facebook does not help.  I still have to reboot my Pixel 4A every ~24 hours to fix the issue once it starts.

**Comment by nickb24** [comment]
Do you have the option "Close GATT on BLE disconnect" checked or not? I suggest having it checked.

**Comment by jamorham** [comment]
When you get the message saying `failure to register` and need to reboot the phone I am pretty sure this happens when the actual Bluetooth stack in the android operating system fails. This is why you need to reboot to fix it and toggling Bluetooth off/on isn't sufficient to reset it. I have seen this before on Android 7-8.1 of various platforms but particularly with broadcom chipsets and definitely traced it to the stack itself, but I thought it was fixed in Android 9+ so if the Pixel 4a is up to date then I'm surprised to hear of that issue being reported there.

**Comment by Navid200** [comment]
@jamorham This is on Moto G7 Android 10.
He says restarting the phone fixes it.
Is this what you mean.  Or, is this a different error?

![2](https://user-images.githubusercontent.com/51497406/104678578-be811080-56b9-11eb-9733-7af61e92e0b3.jpg)

**Comment by tolot27** [comment]
> When you get the message saying `failure to register` and need to reboot the phone I am pretty sure this happens when the actual Bluetooth stack in the android operating system fails.

I cannot really belive this because other apps running fine at the same time. Even if some devices getting disconnected, the apps reconnect them automatically, whereas xDrip does not. I suspect that the additional RxAndroidBle stack is responsible for it.

Maybe, sometimes I can get access to such a device and can debug it, too.

**Comment by jamorham** [comment]
@Navid200 thats the same error

@tolot27 When I saw this issue previously the whole bluetooth stack was down, no bluetooth functions would work at all in any app.

**Comment by jamorham** [comment]
For anyone who is experiencing this issue, what happens if you go to Android Settings -> Apps -> xDrip and then force stop xDrip and wait a minute or so and re-open it. Does that resolve the problem?

**Comment by Navid200** [comment]
@jamorham 
I will communicate that test on facebook.  I should have results soon.

**Comment by Navid200** [comment]
Case 1: Samsung S10 Android 10; uses AAPS as well
force stop did not resolve the problem.

**Comment by jredders** [comment]
I just started getting the "Failed to register" messages again and XDrip has tried to resolve it by turning off and turning on Bluetooth twice so far this time.  The second time it seems like it wasn't able to turn Bluetooth back on, or leaves it off for longer than I thought before re-enabling.  I noticed that my Garmin watch had disconnected.  I turned it on manually and restarted XDrip's collector.  The Garmin watch reconnected as soon as Bluetooth was enabled and I was able to sync it with Garmin Connect, so Bluetooth wasn't totally dead.  XDrip was also able to connect after a few minutes.  So, at least when it first starts seeing the "Failed to register" errors occur, it can recover simply by turning off and turning back on Bluetooth.

**Comment by Navid200** [comment]
@jamorham 

Case 1: Samsung S10 Android 10, G6 8L****, Nov. 27, 2020 release; uses AAPS as well
Force stop did not resolve the problem.

Case 2: Pixel 4 XL, Android 11, G5 42****, Nov. or Dec. 2020 release (TBD) ; uses AAPS
Force stop did not resolve the problem.

**Comment by tolot27** [comment]
I don't know whether it is important to remove the xDrip widget as well. I also recommend to turn off Bluetooth and switch it on after a while and before xDrip is started again.
@Navid200 Please can you ask the users if the have other Bluetooth devices connected at the same time and if they continue to work or reconnect automatically?

**Comment by jredders** [comment]
I tried restarting the collector, force stopping XDrip, removing the widget, force stopping, toggling Bluetooth manually, then restarting and nothing worked. My Garmin 645 kept syncing just fine through it all. Rebooting the phone fixed it as always.
Any chance it's related to the message about switching to scan always mode due to errors?
![Screenshot_20210116-103818](https://user-images.githubusercontent.com/9410439/104817531-6b0ce080-57e7-11eb-8fec-021414ea2f9d.png)

**Comment by dspnikder** [comment]
There are two known existing bugs that hasn't been adressed, there is a PR for them which fixes both. One is there is a new format for one of the info messages, the other that there is a mismatch in the current understanding of what the characteristics services offer which means there are attempts to READ instead of INDICATE in three places. That this causes intermittent problems and issues that manifest in different ways depends on
1: your Android version
2: the vendor of the BT software stack and in most cases hardware
3: Possibly some other unknown factor like phone vendor modifications in the layer between application and hardware.

Considering this was first reported in March last year and the PR has existed since November I can only hope that someone notices.

**Comment by Navid200** [comment]
Case 1: Samsung S10 Android 10, G6 8L****, Nov. 27, 2020 release; uses AAPS as well
Force stop did not resolve the problem.

Case 2: Pixel 4 XL, Android 11, G5 42****, Jan. 15, 2021 release; uses AAPS
Force stop did not resolve the problem.

Case 3: OnePlus 6 Android 10, G5 42****, Jan. 15, 2021 release; uses BlueJay as well

**Comment by Navid200** [comment]
@jredders Any updates on this?
Are you still experiencing this issue?

**Comment by jredders** [comment]
No I am not. Unfortunately, I have no idea why it stopped happening.

**Comment by Navid200** [comment]
Thanks for the response.
I suggest you close this issue.  It can always be reopened if it is experienced again.  
And, it can be found in searches.  Closing it does not wipe everything off.

**Comment by ElyeM** [comment]
I'm having the same issue.
When I force stop xdrip and open it again I do get 1 or 2 readings and then it stops again. 

Most of the time I use bluejay, so I am getting the readings through the watch, but when I don't use the watch I have this issue. 
![Screenshot_20210416-143715](https://user-images.githubusercontent.com/4944797/115069257-519c3300-9ec1-11eb-9fda-3faa02507b14.jpg)

**Comment by Navid200** [comment]
@ElyeM Do your settings match the following?
https://github.com/Navid200/xDrip/wiki/G6-Recommended-Settings

If not, change them to match.

**Comment by ElyeM** [comment]
> @ElyeM Do your settings match the following?
> https://github.com/Navid200/xDrip/wiki/G6-Recommended-Settings
> 
> If not, change them to match.

Yes, everything matches, besides the "Bluetooth Watchdog" And I still have the problem when I dont use my BlueJay.
I use AndroidAPS and it messes up things when I completely turn off an on the Bluetooth, Any other solution?

**Comment by Navid200** [comment]
@ElyeM What do you mean besides the Blurtooth Watchdog?  Why the exception?
