### ISSUE TITLE
Wear OS complication customization

### ISSUE THREAD

**Issue by gmartin01** [NightscoutFoundation/xDrip#1592]
Is it possible to change the data shown on the Wear OS complication?
I am currently using the  Skymaster Pilot as linked in the documentation
![wear-complication-short](https://user-images.githubusercontent.com/27729077/103772368-6a11cd00-4ff7-11eb-908d-e7ee5d192051.png)

my old eyes are having a difficult time reading the small font for the bg
is it possible to customize the data provided via the complication ?

**Comment by tolot27** [comment]
Questions should be asked at the Facebook group or Gitter room.

Currently, customization is not possible. You can reopen this issue and turn it into a feature request after you have discussed it at the channels mentioned above.
