### ISSUE TITLE
Brand New G6 Sensor gives "Sensor Failed Start" Error

### ISSUE THREAD

**Issue by RTKurek** [NightscoutFoundation/xDrip#1599]
I am fairly new to my G6 and am trying to use it with xDrip+. However, I can't seem to get a sensor started in the app at all. After a few attempts, the app finds the transmitter and starts warming up, but some time into the warmup I get multiple errors saying "Sensor Failed Start". No idea why this is seemimgly happening all of a sudden. I've searched for this error but have only found reports from people trying to restart a sensor after 10 days. I'm using a brand new sensor. 

I'm using a transmitter starting with "8M" and I'm using nightly build 20210108. The master build didn't seem to find the transmitter at all.

Any ideas? Let me know if there's any data that would help diagnose the problem.

**Comment by emp-00** [comment]
@RTKurek : Have you already worked thru this comprehensive setup guide: https://androidaps.readthedocs.io/en/latest/EN/Configuration/xdrip.html

It explains all relevant settings - just check it from top to bottom and then you should be good to go. If not please post your Event Log and other information as requested in the "bug report" template here.

**Comment by RTKurek** [comment]
Went through it more precisely this time with a new sensor and it appears to be working. Not sure what's different this time.

Unfortunately I had to remove the previous sensor as I kept getting errors in both xDrip and the official Dexcom app. It seems like hitting "Stop Sensor" forces you to insert a new sensor, even if it's only been inserted for a few hours. Unfortunate, but good to know for the future...

**Comment by tolot27** [comment]
> It seems like hitting "Stop Sensor" forces you to insert a new sensor, even if it's only been inserted for a few hours.

That's not true. Please ask at the support channels how to do this in the future.

**Comment by Navid200** [comment]
A G6 transmitter has a crude restart detection mechanism.  It can trigger even with a brand new sensor!
To avoid it, make sure to keep the transmitter out of the sensor for at least 10 minutes before starting.

So, after the old sensor has stopped, or after you stop the old sensor, wait for it to stop.  Then, remove the old sensor from your skin.
Now, set a timer for 10 minutes.  Don't snap the transmitter into the new sensor before the timer runs out.

If  you have got to a point that subsequent start attempts, on a new sensor, proceed to result in a sensor failed start error, you will need to perform a restart:
https://navid200.github.io/xDrip/docs/Restart-G6-sensor.html
