### ISSUE TITLE
A question about Dex Share feature

### ISSUE THREAD

**Issue by Nyan-SouthKorea** [NightscoutFoundation/xDrip#1602]
Hello. I uses XdripApp very usefully. Thank you very much.

I use it like this below.

Dexcom G6 -> Dexcom G6 official App -> enable Dex Follower -> Use Dex Share feature in Xdrip -> Put my Dexcom ID and password in Xdrip -> I get my suger level in Xdrip -> I send it to my Miband 5

So I have a question. My friend says that Dexcom will shut down the Dex Share feature for Xdrip. But itisnot official but I am just worried about it.

So I want to undersand that how Dex Share feature works.
What I guess is: 
Guess 1: Xdrip pretends to be like official Dexcom Follower App and get into Dexcom's server and get suger level to Xdrip from Dexcom server.
Guess 2: Dexcom made a feature 'Dex Share' for third party App like Xdrip and this feature can close any time when Dexcom wants anytime.

If Guess 1 is right, I don't have to worry because offical Dexcom Follower feature will be keep using. So that Xdrip Dex Share also can be keep used well.
If guess 2 is right, I have to find out the close date of Dex Share feature and find other way to use Miband with using official Dexcom App.

My email is 112fkdldjs@naver.com
Thank you for repying me. Have a nice day.

**Comment by tolot27** [comment]
Please ask in the support forums.
DexShare is not specifically developed for xDrip. It is developed for the Dexcom Follow app.
