### ISSUE TITLE
miao miao 2 stopped capturing

### ISSUE THREAD

**Issue by JustasBan** [NightscoutFoundation/xDrip#1603]
![Screenshot_20210111-111123](https://user-images.githubusercontent.com/69078002/104162800-f65c2f80-53fd-11eb-97a6-83b9145349f8.png)

![Screenshot_20210111-111956](https://user-images.githubusercontent.com/69078002/104163376-00caf900-53ff-11eb-9314-4f6aeba060dc.png)

This happened out of the sudden. Tried reinstalling the app, updating to newest version - same results. Also, after initial calibration it stopped capturing too. 

Used some older version at the beginning, now using 2021 -01-08 day version and libre 1 with miao miao 2.

**Comment by tolot27** [comment]
Please ask at the support channels (Facebook, Gitter), first!

**Comment by Amunhateb** [comment]
@tolot27 mb you could at least point to Facebook Gitter groups where to ask?
https://jamorham.github.io/#xdrip-plus doesn't have any info on these
github says only about gmail jamorham directly

I have same issue with Bubble + libre 1. After resetting all calibrations

**Comment by tolot27** [comment]
Most likely you have overseen it as you have created this issue after you have clicked on "New": https://github.com/NightscoutFoundation/xDrip/issues/new/choose

**Comment by Amunhateb** [comment]
@tolot27 sry, it wasn't me who created this issue. Thx for pointing to community.

**Comment by JustasBan** [comment]
hey, sorry to respond that late. Now the app works just had to calibrate with two results. Oddly, it usually worked with one. For support channels - duly noted!

**Comment by Navid200** [comment]
Sounds like the issue is resolved.
Thanks
