### ISSUE TITLE
FR: Trend Alert

### ISSUE THREAD

**Issue by ARkaine2** [NightscoutFoundation/xDrip#1604]
Not just BG Rising/Falling Fast Alert, but alert for tend with defined settings (let's say from start relative value to +3 mmol per 1 hour).

<details><summary>Something like this:</summary>
<p>

![photo_2021-01-10_09-29-52](https://user-images.githubusercontent.com/31447095/104172116-6671b200-540c-11eb-872d-d677781ad9a6.jpg)

</p>
</details>

**Comment by tolot27** [comment]
At the time you have marked, the BG was rising and you got an alert, if configured. It is based on the increase of the BG over time (Other Alerts -> Bg rising fast) or reaching a threshold (Glucose Level Alert). You can even configure forecast alerts.
How should a trend alert be different? Please explain in detail.

**Comment by ARkaine2** [comment]
BG Rising/Falling Fast works in short period of time (I think that it can act in 2--3 data recives from transmitter [= 10--15 mins]) and only with "extreme" BG changing (something like: minimum is 2x times ±1> BG).

With BG Rising/Falling Fast we specify only falling/rising amount parameter -- which is fine when we wish to indicate/alert extreme+short-time BG changing.

But I'd wish to have indication/alert of more long-timed BG rising (about 30--60 minutes) which often is more smooth than that can be specified with BG Rising/Falling Fast.

-- it can be useful for diabetics with problematic night/sleep. :)

...

The problem (for me) is that with BG Rising/Falling Fast function we can't: 
1. Specify to make alert from more smooth BG changing.
2. Specify period of time to calculate BG changing that will make alert.

I want to have alert (for example) with:
+0.3>+0.3>+0.3>+0.3
= +1.2 BG per 20 mins.

Or:
+0.2>+0.2>+0.2>+0.2>+0.2>+0.2
= +1.2 BG per 30 mins.

Or:
+0.3>+0.3>+0.3>+0.3>+0.3>+0.3>+0.3>+0.3
= +2.4 BG per 40 mins.

Or it can have different values of rising:
+0.1>+0.4>+0.2>+0.4>+0.1>+0.2>+0.5>+0.1
But still:
+2> (+2.0) BG per 40 mins.

<details><summary>Example:</summary>
<p>

![photo_2021-01-10_09-29-52 cvc](https://user-images.githubusercontent.com/31447095/104309011-28db5a80-54da-11eb-89bb-90299b3a0ab1.jpg)

</p>
</details>

...

Maybe it should "calculate"/"indicate" 2--3 point's values to exclude noises.


<details><summary>Example:</summary>
<p>

![photo_2021-01-10_09-29-52 cc](https://user-images.githubusercontent.com/31447095/104309017-2a0c8780-54da-11eb-8c7d-68ca2849d636.jpg)

</p>
</details>

Thanks.

**Comment by Navid200** [comment]
@tolot27 
Isn't this a duplicate?
Would there be any reason to implement this before the following?
https://github.com/NightscoutFoundation/xDrip/issues/907

**Comment by tolot27** [comment]
@Navid200 Indeed, it is related to #907 but it duplicates it half because @ARkaine2 also requests to specify the period of time to calculate BG changings for the fast alert.

**Comment by Navid200** [comment]
@tolot27 So, can we ask @ARkaine2 to post in that thread and suggest an addition to it?
Keeping two issues open knowing they have common parts could cause redundant activity by two different developers.  Since we don't have enough developers, let's do everything we can to use their limited time efficiently please.

**Comment by Navid200** [comment]
@ARkaine2  Please look at the following two open issues, which both outdate this new one.
https://github.com/NightscoutFoundation/xDrip/issues/311
https://github.com/NightscoutFoundation/xDrip/issues/907

All of these feature requests are about the fast rising and fast falling alerts.

I don't see a reason to favor this request to those two.    I suggest adding new requests to the older ones to show that more people are in favor of it.  Having slight variations of the same issue open in multiple issues only creates unnecessary clutter. 

Would you please add your request to https://github.com/NightscoutFoundation/xDrip/issues/311 and close this one?

Thanks

**Comment by Navid200** [comment]
Please add your feature request comments to the existing open issue.
Thanks
