### ISSUE TITLE
'no' string not translated in initial calibration dialog box

### ISSUE THREAD

**Issue by cybernissart** [NightscoutFoundation/xDrip#1608]
Version of xDrip: 2101081940

### Expected behavior
Code should use translated string instead of native english string.

### Actual behavior
'NO' is displayed instead of translatef string 'NON' in case of french language for current screenshots exemple

### Steps to reproduce the behavior:
1. Start New sensor menu
2. Wait for readings...
3. Dialog box will be prompted asking to calibrate

### Screenshots

![Screenshot_2021-01-12-09-03-55-189_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/24457611/104287984-80b49a00-54b7-11eb-86e6-4f7b0e4bbe7d.jpg)

**Comment by tolot27** [comment]
The "No" is hardcoded at https://github.com/NightscoutFoundation/xDrip/blob/c6c289d888021c2c97bc157c24eea3dba171bffb/app/src/main/java/com/eveningoutpost/dexdrip/Home.java#L2662.
