### ISSUE TITLE
Hello, Can you build in xDrip An automatic screen wake-up at high and low blood glucose values with threshold input? And a screen duration on switch via hook as with voice announcement?

### ISSUE THREAD

**Issue by Aquarius83mn** [NightscoutFoundation/xDrip#161]
@jamorham The idea is that at night the alarm automatically the screen of the mobile phone in the dark, best with On switch-off switch. And a permanent screen switch because otherwise always the same screen goes off a switch for on off goes sowas? As is the case with the voice announcement of the values. Is that possible? Thank you for your reply.

**Comment by Aquarius83mn** [comment]
@jamorham Perhaps simply synonymous with a time from 0 to 24 clock where you can then adjust when he should go with the screen?

**Comment by AdrianLxM** [comment]
Hi @Aquarius83mn,

there are two ways you can already do something similar:

1) xDrip does have a daydream feature. On a German phone you will find it in the phone settungs under **Display -> Bildschirmschoner**. There you can select xDrip+ as screensaver.

2) If you enable developer mode, you do have the option to keep the screen on when charging. On a German phone you will find this at **Entwickleroptionen -> Aktiv lassen**.

cheers, Adrian

**Comment by Aquarius83mn** [comment]
@AdrianLxM Hello, you can neither use Daydream nor active screen on the uploader mobile phone since this a charging cable on the Uploader mobile phone needed. This in turn is technically not there at the charging port the Enlite Contour Next 2.4 to read out depends. So I ask because of the switches since it does not remain active because no load is available. For example, a screen monitor for alarm high or low with time control? And a hook for screen on off, with Enlite measuring device on mobile phone is neither developer options display active nor DayDream usable because this is only when the mobile phone is loaded thereby. I want to say I as an individual (as opposed to mothers with children or orphaned) need not always 2 xDrip mobile phone at night would give me yes. This would have to be installed only as an authorization or? For display on alarm or via hook and time control. As said the meter of the Enlite CGM hangs permanently on the charging connection with OTG cable therefore does not function active display and Tagdream also not have it extra tried does not display.,

In gernan @AdrianLxM 

Hallo, man kann weder Daydream noch aktiver Bildschirm benutzen am Uploader Handy da dies ein Aufladekabel am Uploader Handy benötigt. Dies wiederum geht ja technisch nicht da am Ladeanschluss das Enlite Contour Next 2.4 zum auslesen dran hängt. Deswegen frage ich wegen den Schaltern da es nicht aktiv bleibt weil kein Lade Vorgang vorhanden ist. Zum Beispiel ein Bildschirmerwachung bei Alarm Hoch oder Tief mit Zeitsteuerung? Und ein Haken für Bildschirm an aus, mit Enlite Messgerät am Handy ist weder Entwickleroptionen Display Aktiv noch DayDream nutzbar weil dies nur geht wenn das Handy dabei geladen wird. Ich will damit sagen ich als Einzelperson (im Gegensatz zu Müttern mit Kindern oder Verwadnten) brauche ja nicht immer 2 xDrip Handy nachts würde mir ja eins reichen. Das müsste man doch bloß als Berechtigung erteilen einbauen oder? Damit Display bei Alarm angeht oder per Haken und Zeitsteuerung. Wie gesagt das Messgerät des Enlite CGM hängt ja dauerhaft am Ladeanschluss mit OTG Kabel daher funktioniert Display aktiv nicht und Tagdream auch nicht hab es extra ausprobiert Display bleibt nicht an.,

**Comment by Aquarius83mn** [comment]
@AdrianLxM I see I have an inactivity screen that would address notifications? But xDrip itself has no adjustable notification which would send on high or low a notification to the display or? Otherwise it would probably be more appropriate. Or do you know an app which you can adjust so that you react to updates of xDrip and then the display turns on?

**Comment by AdrianLxM** [comment]
You are right, always-on screen features are something for a follower phone in this case.
Or the Xperia Z phones you have mentioned, that have a USB port and a separate charger port.

The screen is one of the most battery consuming components. Adding this to a phone that is already hard to charge as the port is needed for the CNL? I don't think an always-on screen would be useful here.

There are some Tasker capabilities that you could try, I'm not sure in what state they are.

Yes, there is a notification that can always show the currend BG and trend on the lock sceen :) You will get it by going to "Settings->Less common settings->Other misc options->Run collector in foreground".

------
Ja, da hast du Recht, Always-On Features sind etwas für das Follower Handy in dem Fall.
Oder die Xperia Z Handies, die du erwähnt hast, die einen USP port und einen separaten Lader haben.

Der Bildschirm eine der energiehungrigsten Komponenten. Das zusammen mit einem Handy, das schon schwer zu laden ist, weil der Ladeanschluss für das CNL benötigt wird? Ich denke nicht, dass da ein Always-On Bildschirm sinnvoll wäre.

Es gibt ein Tasker-Plugin. Ich weiß jedoch nicht in welchem Zustand das gerade ist.

Ja, es gibt eine Notification, die sogar immer anzeigt wie der  aktuelle Wert und trend ist. Auch auf dem Lock-Screen :) Die findest du unter "Settings->Less common settings->Other misc options->Run collector in foreground".

**Comment by Aquarius83mn** [comment]
@AdrianLxM Yes, then it becomes difficult, you can times a turn off button in xDrip install? Because if there is no data transfer, the collector always stays on, and beeps every now and then because he gets no value. Got the Collector.

Ja dann wird es schwierig, könnt ihr mal einen Ausschalten Button in xDrip einbauen? Weil wenn es keine Daten überträgt bleibt der Collector immer an, und piepst ab und zu weil er keinen Wert bekommt. Hab den Collector an.

**Comment by AdrianLxM** [comment]
It might work to simply switch to another collection service ("hardware data source") and stop the sensor session in xDrip. Maybe even "stop sensor" is enough.

In order to not having to do that you can go to "Settings->Alarms and Alerts->Missed Reading Alerts" and disable that alert. Then it won't alarm on missed readings.

**Comment by Aquarius83mn** [comment]
@AdrianLxM Can you ask Jon if you incorporate into the Android Uploader also a Collector caused not only the xDrip remains but also the Android Series Uploader. I just see an error he finishes himself from time to time simply in the background xDrip is then still on it gets however no values more. Can Jon make a Collector in the Android Series Uploader? So that the Android Series Uploader can not stop? See image

In german

Kannst du Jon fragen ob man in den Android Uploader auch einen Collector einbaut der verursacht das nicht nur xDrip anbleibt sondern auch der Android Series Uploader. Ich sehe gerade einen Fehler er beendet sich ab und zu einfach im Hintergrund xDrip ist dann noch an es bekommt aber keine Werte mehr. Kann Jon einen Collector in den Android Series Uploader machen? Damit sich der Android Series Uploader nicht unbemerkt beenden kann? Siehe Bild

![ashampoo_snap_donnerstag 24 august 2017_20h28m28s_006_](https://user-images.githubusercontent.com/22836158/29682342-f8952f02-890a-11e7-99a7-17532cc7a3eb.jpg)
](url)

**Comment by Aquarius83mn** [comment]
@AdrianLxM  Can you somehow adjust the Android Uploader can not finish? Otherwise, the values will no longer occur. It remains unchanged the Android Uploader. If I now in Android Uploader would go on it goes.


Kann man irgendwie einstellen das der Android Uploader nicht beenden kann? Sonst kommen die Werte nicht mehr an. Es bleiibt unverändert das Android Uploader zumacht. Wenn ich jetzt in Android Uploader reingehen würde geht es an. 



![ashampoo_snap_donnerstag 24 august 2017_20h35m07s_007_](https://user-images.githubusercontent.com/22836158/29682569-c45105a8-890b-11e7-87f9-c9667c791df8.jpg)

**Comment by Aquarius83mn** [comment]
@AdrianLxM Have now looked after 20 minutes at a time comes a new value, you have an explanation why it interrupted then far forward? Have the same key and everything and 640 as source and follower cell phone is Android emulator on pc. Can not explain the sender has you got an idea? It's only wifi on this phone.


Hab jetzt geschaut nach 20 Minuten auf einmal kommt ein neuer Wert hast du eine Erklärung warum es solang unterbricht dann weiterschickt? Hab den gleichen Key und alles und 640 als Quelle und Follower Handy is Android Emulator on Pc. Kann mir die Sendelücke nicht erklären hast du eine Idee? Es ist nur Wlan an diesem Handy an.


![ashampoo_snap_donnerstag 24 august 2017_20h40m05s_008_](https://user-images.githubusercontent.com/22836158/29682762-7b487d5e-890c-11e7-8c5b-ca964501191e.jpg)

**Comment by AdrianLxM** [comment]
Hi @Aquarius83mn, xDrip only receives broadcasts form the 600 series uploader but otherwise is unrelated. The repo where you can also open issues is here: https://github.com/pazaan/600SeriesAndroidUploader/issues
It is likely that the 600series uploader has a faillover timer that restarts everything after 20 minutes.

Hi @Aquarius83mn, xDrip empfängtnur Broadcasts vom 600series uploader aber ist sonst unverbunden. Das Repository in dem du auch Issues öffnen kannst findest du hier:  https://github.com/pazaan/600SeriesAndroidUploader/issues
Es ist wahrschienlich, dass der 600series uploader einen Ausfallsicherungs-Timer hat, der ihn wieder nach 20 Minuten startet.

**Comment by Aquarius83mn** [comment]
@AdrianLxM Thank you for this Info, other Question to the xDrip Batterie Status Master Handy? What I just noticed is when I do the phone in a pocket or box and use a follower cell phone, I see or notice but not when the master cell phone is empty. Do you think Jon is possible to make the batteriestatus of the master mobile displayable in xDrip? Maybe with battery warning as with the Smartwatch? Or can the battery status of the master mobile phone already? So that mothers, parents, relatives can see when the master cell phone is empty and I also. Because I prefer it is also on the Follower mobile phone the values to see (because the OTG cable is not yes with the measuring device?) Can you ask him times questions Batteriestatus Master xDrip mobile phone on the follower mobile phone? Is empty or is it already? 







Was mir Gerade aufgefallen ist wenn ich das Handy in eine Tasche tue oder Box und benutze ein Follower Handy, sehe oder merke ich aber nicht wann das Master Handy leer wird. Denkst du es ist Jon möglich den Batteriestatus des Master Handys einblendbar zu machen in xDrip? Vielleicht mit Batteriewarnung wie bei der Smartwatch? Oder kann man den Batterie Status des Master Handys schon abrufen? Damit Mütter, Eltern, Verwandte sehen können wann das Master Handy leer wird und ich auch. weil mir es auch lieber ist am Follower Handy die Werte zu sehen (weil das OTG Kabel ja nicht dran is mit dem Messgerät? Kannst du ihn mal Fragen Batteriestatus Master xDrip Handy am Follower Handy anzeigen lassen? Am besten mit Alarm auf Follower wenn Akku bald leer ist oder geht das schon? :)

**Comment by AdrianLxM** [comment]
@Aquarius83mn Battery should be synced: https://github.com/NightscoutFoundation/xDrip/commit/e2a6c5b7034f0cde3a8e48536199a55fbec0b7b4

**Comment by Aquarius83mn** [comment]
@AdrianLxM Do you mean the battery status indicator from the pump battery? So because I mean the battery level of the master cell phone, do you know as I mean because you have not noticed on the follower mobile phone so otherwise if the mobile phone battery of the master cell phone is empty, you know what I mean?

Pumpe Status is on, what i see in xDrip is the Pump Statut Battery? I mean the Master Handy Status Battery, for followers?

Meinst du die Batterie Status Anzeige aus der Pumpenbatterie? Also weil ich meine den Batterie Stand des Master Handy, weisst du wie ich meine weil man am Follower Handy ja sonst nicht mitbekommt wenn die Handy Batterie des Master Handys leer wird,weisst du was ich meine?

**Comment by Aquarius83mn** [comment]
@AdrianLxM Here this mean i in a picture :), th
![ashampoo_snap_donnerstag 24 august 2017_21h14m53s_009_](https://user-images.githubusercontent.com/22836158/29684310-c5689f4a-8911-11e7-8f24-860eea3e2c1e.jpg)
anks

**Comment by Aquarius83mn** [comment]
@AdrianLxM Do you think that would go Which one of the xDrip Master mobile phone can send the battery level to the follower mobile phone? That would be great

Denkst du das würde gehen Das man vom xDrip Master Handwerk der Batterie Stand an das Follower Handy senden kann? Das wäre echt toll
