### ISSUE TITLE
xDrip+ Does not ask for the sensor insertion time - I have to wait the full warmup time

### ISSUE THREAD

**Issue by winni67** [NightscoutFoundation/xDrip#1613]
### Subject of the issue
I tried to start an already started Dexcom G6 sensor session in xDrip+.
In xDrip+ I start the sensor, but xDrip+ doesn’t ask me for the sensor insertion time.
Therefore I have to wait the full G6 warmup time.
Xdrip+ is receiving the G6 glucose data and broadcasts it to other apps like AndroidAPS, but in xDrip+ themselves, you have to wait the full 2 hours for the first glucose data shown to you. In my opinion, this is a bug.

### Your environment
"Nightly build 13th Jan 2021".
G6 Native
- Is your issue specific to a device like and Android phone or a smartwatch? No. Same on a second smartphone.

### Actual behavior
I tried to start an already started sensor session in xDrip+. XDrip+ asks me for the calibration code and directly starts the warmup phase. XDrip+ never shows a glucose value. But the Dexcom reader and AndroidAPS shows glucose values. xDrip+ only shows on the Home Screen „Please wait while sensor warms up! (120 minutes) and counts down, bofore the first value is shown.
But the sensor session was already started by another device and xDrip+ receives the Glucose values and broadcasts them to AndroidAPS, but xDrip+ doesn‘t show them on the Home Screen.
With the Dexcom App, it‘s no problem to start an already startet sensor. There after a few minutes, the values are shown.

### Steps to reproduce the behavior:
For example:
1. Stop Sensor
2. clear transmitter queue (I work with two sensors for a while and don‘t want to stop the old sensor session, that sends the data to a second device - here the dexcom reader)
3. change transmitter id to the transmitter on the already started sensor (I startet the new sensor with xDrip+ on a second smartphone)
4. Wait to the first connects to this new transmitter
5. Start Sensor
6. Enter the G6 calibration code
7. Missing the question for the sensor insertion time
8. Wondering about the 120 minutes to wait for the first glucose value shown on the Home Screen
9. I can see the glucose values in AndroidAPS

**Comment by Navid200** [comment]
You don't need to "start" if you have an active session.  All you need to do is to establish connectivity and the readings will start showing.

The request for insertion time was removed from G6 intentionally because you cannot enter any time other than now when you start a G6 sensor.

**Comment by Navid200** [comment]
Please note that with a G5, if the sensor has been on you more than 2 hours, you can start and enter a time prior to now and the warm-up will end sooner than 2 hours accordingly.

But, you cannot do soaking with G6.  It would interfere with factory calibration, which G5 did not have.  You are supposed to start sensor as soon as you insert sensor, with G6, for best accuracy benefitting from factory calibration.

**Comment by winni67** [comment]
Yes I started the G6 one day before yesterday with another device than my loop smartphone. Yesterday I only wanted to switch the running G6 session to my loop smartphone. But I didn‘t find any documentation on the AAPS website how to do this. This case seems not to be documented. Thanks for the hint to not press „Start Sensor“. I will try it the next time and report my experience here. Do you know how long I have to wait then for the first values? Kind regards.

**Comment by Navid200** [comment]
@winni67 
There is some documentation on facebook.
https://www.facebook.com/groups/xDripG5/permalink/4838757582864365/
That is the best place for having questions and answers to gain and share experience.

If everything is set up correctly, xDrip will pick up a session in progress in 10 to 15 minutes.  It may take a few more read cycles (5 minutes each) to also populate the battery information.
