### ISSUE TITLE
Free 2 + MiaoMiao 1 + Xdrip

### ISSUE THREAD

**Issue by AlbertoTryingTech** [NightscoutFoundation/xDrip#1616]
I can't get this combination to work: Free 2 + Miaomiao 1 + Xdrip. Xdrip does not show any readings (BG Readings Unavaible) however in System Status everything seems correct. Could you help me, please?

I have tried to do all this:

**Miaomiao 1 firmware** → is updated to version V39

**Miaomiao 1 battery** → is 100%

**Smartphone battery** → is 100%

**OOPAlgorithm** → is running in the background, I have downloaded this app from MiaoMiao's website, the Android “battery optimization” option is disabled for this app (also for Xdrip).

**OOPAlgorithm 2** → I have tried to install "OOPAlgorithm 2" to see if it worked but not

**Xdrip version** → I have tried with the latest version of Xdrip and with previous ones

**Reinstall** → I have tried reinstalling Xdrip and OOPAlgorithm several times.

**Readings** → on several occasions it has received some data and immediately the connection is cut off and it stops receiving them (I have tried in these cases to restart the collector but it does not receive readings again).

**Android** → I have tried on a Sony Xperia phone with Android 5 and on the other hand, on a Motorola C Plus phone with Android 7 but neither worked.

**Reset the MiaoMiao** → I have tried to reset it by pressing the button for several seconds but it does not fix the problem
Clearing the Bluetooth cache → does not fix the problem

**Restarting the phone** → does not fix the problem

**Bluetooth paired** → I have made sure that Miaomiao 1 is not paired with Android, it is paired with Xdrip.
MiaoMiao manufacturer → I have done what it says in this link but it doesn't work https://miaomiaoreader.medium.com/how-to-make-libre-us-14-days-sensors-work-with-miaomiao2-on-xdrip-35b431a40940 

**Error message in Xrip log** → got null pointer trying to set cccd descriptor

**Somes screenshots** →

![1](https://user-images.githubusercontent.com/77694072/105081429-78012c80-5a92-11eb-8cbe-acc75aa57404.jpg)

![2](https://user-images.githubusercontent.com/77694072/105081470-86e7df00-5a92-11eb-9b16-0450c6ad69a8.jpg)

![3](https://user-images.githubusercontent.com/77694072/105081460-83545800-5a92-11eb-8970-e39625fb34ba.jpg)

![0](https://user-images.githubusercontent.com/77694072/105081449-7fc0d100-5a92-11eb-8db2-83f0220595c5.jpg)

**Comment by LubomirKovalcik** [comment]
I have exactly same problem, expect I get reading sometimes.

First I had problem exactly like you, without any readings.

Then I have tried Tomato app, updated MiaoMiao through Tomato app.

Then I uninstalled Tomato app and used xDrip again.

However problem is that I am only getting reading once in a time, otherwise there is still this error: **got null pointer trying to set cccd descriptor**

And also readings are unreliable.

**Comment by harentius** [comment]
I have very similar situation with Free 1 + MiaoMiao 2 + Xdrip.
However I get some readings
![Screenshot_2021-01-21-08-20-54-780_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/4300680/105295073-31125480-5bc2-11eb-84f8-b2bb7c9ff5f4.jpg)

**Comment by crazysugarnl** [comment]
Have also the same problem, when i use the newest version it is not working,

If i use an very old version, version e14bae1-2020.07.13, then i get data from the miao miao2 (my setup is miao miao2,OOPAlgorithm 2, freestyle libre 2 and the old version number e14bae1-2020.07.13)

When i use this it works but update it to any newer version it won't work, receiving no data

**Comment by crazysugarnl** [comment]
Hope there comes a more up to date version that will work with freestyle libre 2 sensor, miao miao2 and the data option libre Bluetooth.

**Comment by izywizy** [comment]
I just connected my first L2 to with MM2 and xdrip and collecting and displaying fine and also sending to Oppo smart watch.

I updated MM2 to firmware 7, using MMs oop2 and xdrip of 15th Jan.

Originally tried to use my backed up settings but that failed so set up from scratch and BINGO! and sensor had been started 3 days prior. My phone is OnePlus8 with android 10.

You should join the Facebook xdrip group and maybe you can put your MM back in it's box ;-)

![Screenshot_20210126-223741](https://user-images.githubusercontent.com/36773149/105915293-6f2ad080-6027-11eb-92b0-e4cb5e586008.jpg)

![Wear OS Screenshot](https://user-images.githubusercontent.com/36773149/105916776-5a4f3c80-6029-11eb-8798-c796369e80b4.png)

**Comment by LubomirKovalcik** [comment]
Ok, but original post is about miaomiao 1. Has anyone working MM1 with LIBRE2? 
I sometimes have libre2 sensor with broken bluetooth, so I can not used patched app...

**Comment by LubomirKovalcik** [comment]
I have found out, that sometimes glucose is not shown also without "Got null pointer trying to set CCCD descriptor"

In default log environment it goes like this:

**DexCollectionService**
10:44 Received buffer after 295 seconds, starting again. Already acumulated 369 bytes. 
10:44 Starting to acumulate data expectedSize = 369. 
**LibreUtils**
10:44 decodeSerialNumber = 0MH001*****
**NGCReaderX**
10:44 HandleGoodReading called
**LibreBlock**
10:44 Backtrack: NFCReaderX::HandleGoodReading -> LibreBlock::createAndSave
10:44 Backtrack: NFCReaderX::HandleGoodReading -> NFCReaderX:SendLibrereading
**DexCollectionService**
10:44 We have all data that we need 369 checksum_ok = true
0x00000 ............ (all data here)



From logs it seems like LibreOOPAlgorithm is not called or not giving any result back??

**Comment by LubomirKovalcik** [comment]
So from discussion on FB group I found out working combination:

MM1 fw39
xDrip 2021.01.05
OOPAlgorithm 2

And the trick is to **DISABLE OOPAlgorithm processing in xDrip settings.** Not sure why and it does not make sense, but it works this way and OOPAlgorithm is still called in logs.

**Comment by Navid200** [comment]
Sounds like you have identified a solution.
Thanks for the feedback.
