### ISSUE TITLE
Significance of brown band on firmware version?

### ISSUE THREAD

**Issue by GReventlov** [NightscoutFoundation/xDrip#1619]
![signal-2021-01-23-104006](https://user-images.githubusercontent.com/14355544/105606495-cc90fa00-5d67-11eb-9096-0a400bba1551.png)
Screenshot attached. New transmitter, and the experience has been pretty unreliable on Android 10/Moto Power. Getting lots of "brain state" errors.

**Comment by nickb24** [comment]
All this means is that your firmware version is known and that it's a G6 firefly version. 
Source: https://github.com/NightscoutFoundation/xDrip/blob/62816d8e5ef35610723aa6658b56e2964fc55f1c/app/src/main/java/com/eveningoutpost/dexdrip/Services/Ob1G5CollectionService.java#L1943

**Comment by tolot27** [comment]
This is neither a bug report nor a feature request.
Nickb24 answered the question. Hence, closing it.
