### ISSUE TITLE
"Possible Sync Problem" pop-up - What is the solution when the followers are working perfectly?

### ISSUE THREAD

**Issue by Navid200** [NightscoutFoundation/xDrip#1626]
Multiple facebook posts have reported this pop-up.
https://www.facebook.com/groups/xDripG5/permalink/4902788579794598/
https://www.facebook.com/groups/xDripG5/permalink/4913632698710186/
https://www.facebook.com/groups/xDripG5/permalink/4783402735066517/

I suspect this happens when someone has had a smart watch, which is not active any longer. 
It keeps popping up. 

I found this:
https://github.com/jamorham/xDrip-plus/blob/master/app/src/main/java/com/eveningoutpost/dexdrip/GcmActivity.java
Looking at that code, I can see that enabling "Desert Sync" will stop the pop-up.  However, I don't know the ramifications of enabling Desert Sync when not needed.

I can see a "Disable all sync features" under xDrip Settings -> xDrip+ Sync settings
But, I am not sure if that could cause issues with AAPS or other followers. 

What exactly is someone who is getting this pop-up supposed to do?
![1](https://user-images.githubusercontent.com/51497406/106298736-428ed880-6222-11eb-852c-c6ca568dd6c0.jpg)

**Comment by tolot27** [comment]
> I suspect this happens when someone has had a smart watch, which is not active any longer.

We still need to know if that's the case and the xDrip version is used. At least one of the users has an older version running.

**Comment by Navid200** [comment]
The xDrip version is quite recent (2021).
Since I opened this issue, I have learned a lot thanks to @nickb24.

One of the users did not have any followers.  As advised by nickb24, I asked them to disable "Be master for followers".  They stopped receiving the pop-up.

There is another user who indeed has followers.  The followers are all receiving readings correctly.  Yet, this pop-up keeps coming up.
In this case, looking at the code, I noticed this (please see the attached image).  Based on that, if "Desert Sync" is enabled, the pop-up will never show up.  I asked them to enable Desert Sync.  They did and the pop-ups stopped.

I have been told by @nickb24 and @jamorham that this problem is due to Google.  But, I am not sure how to proceed to resolve it.  So, I tell the users that enabling Desert Sync is not a solution but only a very crude work-around.
That is the reason I have left this open.
![Screenshot 2021-01-31 171237](https://user-images.githubusercontent.com/51497406/106520265-8267f100-64aa-11eb-9457-3cbce5cd7735.png)

**Comment by Navid200** [comment]
Will open if I get more data.
