### ISSUE TITLE
Last BG value not shown on Main Screen and Widget

### ISSUE THREAD

**Issue by skavan** [NightscoutFoundation/xDrip#1629]
This may be user error (me), or an incompatibility issue.
**Background:** 
Latest xDrip version, connected to Patched Dexcom G6 App via 640G/Eversource Option.
Works great except for:

**Problem:**
The current BG Level and Arrow, is missing from both the main display and the widget. I am running on a brand new Samsung S21 Ultra. See the two pics below.
Any help would be greatly appreciated. This app is absolutely phenomenal.

![2021-01-31_14-12-36](https://user-images.githubusercontent.com/2557753/106395329-bae6cc80-63cf-11eb-8bb5-c840eb244aff.jpg)
![2021-01-31_14-21-22](https://user-images.githubusercontent.com/2557753/106395331-bde1bd00-63cf-11eb-84b3-38ba955ef225.jpg)

**Comment by tolot27** [comment]
You did not provide your environment information which was requested with the bug report template. Please add the missing information, especially Android and xDrip version.

BTW: In two weeks, nobody knows what the "latest xDrip version" is.

**Comment by skavan** [comment]
Sorry. Here you go...

Android 11, Samsung One UI version: 3.1
xDrip+ version: e14bae1-2020.07.13.

**Comment by tolot27** [comment]
Please can you try the latest nightly?

**Comment by skavan** [comment]
tried latest. same issue.

**Comment by tolot27** [comment]
@skavan Please can you provide your screen resolution? Please also try to lower the resolution to WGHD (2560x1440) or even FHD (1920x1080) or corresponding values your phone provides.

**Comment by skavan** [comment]
My 3 available screen resolutions are:
1. WQHD+: 3200 x 1440
2. FHD+ : 2400 x 1080
3. HD+ 1600 x 720

It was using #2, but I have tried the other two settings. Unfortunately no change.
Happy to keep trying stuff.

s.

**Comment by skavan** [comment]
Don't know if it's related, but I also get a "Please start Sensor for best results" Toast, every so often.
I'm not connected to the sensor via xdrip though.

**Comment by tolot27** [comment]
Do you see any errors in the log? What happens if you enable graphical trend arrows (long-pres on the blood icon or xDrip+ at the top)?

**Comment by skavan** [comment]
Tried all the settings like graphical trend arrow.
In logs, I see the following RED item and a couple of other ones....pasted below.

![image](https://user-images.githubusercontent.com/2557753/106398565-85e37580-63e1-11eb-8e24-b27ac3706ecb.png)

![image](https://user-images.githubusercontent.com/2557753/106398592-add2d900-63e1-11eb-978c-3fdcdf647017.png)

**Comment by skavan** [comment]
Oh wow...it's started working!
Here's what I did:
I just went and turned the sensor on. Even though there isn't one!

**Comment by skavan** [comment]
Of course, before I did this, it said Start Sensor, not stop sensor!

![image](https://user-images.githubusercontent.com/2557753/106398687-584afc00-63e2-11eb-8fc7-6bd946a2b160.png)

**Comment by tolot27** [comment]
Good to know. I'll raise another issue for this or change the title.

Regarding to the red error in the logs: Please disable "Automatic Crash Reporting".

**Comment by skavan** [comment]
Thanks. p.s. would be good to set a BG color for widget. It's transparent, which on a light background makes it tough to read. I'm also totally stuck on how to enter carbs/get a treatment dialog - like this from your screen shots...
I should probably start a new issue. It's a quite game changing piece of software BTW.

![image](https://user-images.githubusercontent.com/2557753/106398856-3c942580-63e3-11eb-857d-71e1040cf752.png)

**Comment by tolot27** [comment]
Please ask at the support channels, first!

**Comment by Navid200** [comment]
Can we close this issue please?

**Comment by skavan** [comment]
Yup. Thx.
