### ISSUE TITLE
Adding time to predictive low alert

### ISSUE THREAD

**Issue by AdrianLxM** [NightscoutFoundation/xDrip#163]
"Low predicted in 40 minutes at 6:45pm"

On the phone the notifications automatically get the minutes since rising added. On pebble watches not.

**Comment by jamorham** [comment]
In your example is "6:45pm" when the alert message was raised or when the Low is predicted to happen?

**Comment by Navid200** [comment]
@AdrianLxM Hello,
Is this still a problem?

**Comment by AdrianLxM** [comment]
I currently have no pebble to test this. Hopefully someone else can chime in.

**Comment by Navid200** [comment]
I close this until someone can confirm that this is still a problem and provide detail to jamorham.
We can always reopen.
