### ISSUE TITLE
New feature: Import settings from file system

### ISSUE THREAD

**Issue by master3395** [NightscoutFoundation/xDrip#1631]
It might be easy to keep it in 1 folder and 1 file to export/import.
But sadly not everyone has "SD" to save to or load from.
And I can't seem to find a good way to restore the settings.
If I click export settings, it goes to the "download" folder.
But if I try and import, it does not work, the image below will show that having the new config file in downloads does not let it get imported.
So maybe let us find the file and click import instead of an auto check for 1 location?
(The app has all permissions the phone can give, OnePlus 8 Pro EU, android 11)

![image](https://user-images.githubusercontent.com/4199669/106401182-0aa2b380-6423-11eb-9fd8-5f1a5e3b48f0.png)

**Comment by SimonPhilpott** [comment]
This is similar to the following and would address both things. https://github.com/NightscoutFoundation/xDrip/issues/1622

**Comment by Navid200** [comment]
Why do you think it doesn't work?

I just tested this on Jan.29, 2021.  But, I don't think there is anything new about it.  It worked with much older versions as well.

I emptied the Downloads folder.
Under Import/Export features, tapped on Load/Save Settings on SD card.

Tapped on LOAD all settings from SDCARD.  Got the message could not load preferences.

Then, tapped on Save all settings to SD card.  It saved xDrip-export in the Downloads folder.
Changed the Hardware data source from disabled (test phone) to Nightscout follower.
Went back to Load/Save Settings on SD card and tapped on Load all settings from SDcard. 
It worked.  The data source was back to disabled.

**Comment by master3395** [comment]
> Why do you think it doesn't work?
> 
> I just tested this on Jan.29, 2021. But, I don't think there is anything new about it. It worked with much older versions as well.
> 
> I emptied the Downloads folder.
> Under Import/Export features, tapped on Load/Save Settings on SD card.
> 
> Tapped on LOAD all settings from SDCARD. Got the message that could not load preferences.
> 
> Then, tapped on Save all settings to SD card. It saved xDrip-export in the Downloads folder.
> Changed the Hardware data source from disabled (test phone) to Nightscout follower.
> Went back to Load/Save Settings on SD card and tapped on Load all settings from SDcard.
> It worked. The data source was back to disabled.

I re-installed the app, I hit export on the default settings.
Yes, it does save to the download folder, if you don't have an SD card.
But then I changed several settings to see if it changed back to default when importing.

And the error message came, and the settings were not changed.

**Comment by Navid200** [comment]
@master3395 On the phone that is experiencing this, would you please go to Android Settings -> Apps -> xDrip+
and post a screenshot?

**Comment by master3395** [comment]
Was this what you wanted?
![image](https://user-images.githubusercontent.com/4199669/107570934-7686d800-6bea-11eb-98ff-666884df5bbd.png)

**Comment by master3395** [comment]
> @master3395 On the phone that is experiencing this, would you please go to Android Settings -> Apps -> xDrip+
> and post a screenshot?

Was this what you wanted?
![image](https://user-images.githubusercontent.com/4199669/107570978-843c5d80-6bea-11eb-9ecd-5f53903be0d4.png)

**Comment by Navid200** [comment]
No,

The capability to import settings is not a new capability.  And it has been tested and used by many on different devices.

You obviously have problems with it.  The first ting to verify is to give permission to xDrip to access storage.  

Go to Android Settings -> Apps -> xDrip+

**Comment by master3395** [comment]
> No,
> 
> The capability to import settings is not a new capability. And it has been tested and used by many on different devices.
> 
> You obviously have problems with it. The first ting to verify is to give permission to xDrip to access storage.
> 
> Go to Android Settings -> Apps -> xDrip+

I have given the app all permissions there is to give.

![image](https://user-images.githubusercontent.com/4199669/107640149-23586800-6c72-11eb-8f7d-59aeb1920e7b.png)

**Comment by Navid200** [comment]
@master3395 If you have a fecbook account and post in the xDrip facebook support group, this will be sorted out.  You will get 10 times the number of responses there letting you access the experience of many more people.
https://www.facebook.com/groups/xDripG5

**Comment by Navid200** [comment]
What version of xDrip have you experienced this on?

**Comment by master3395** [comment]
> What version of xDrip have you experienced this on?

It's related to the other suggestion also in a way.
Mentioned [Here](https://github.com/NightscoutFoundation/xDrip/issues/1622)

![image](https://user-images.githubusercontent.com/4199669/107677337-6fb79e00-6c9a-11eb-9e5b-62ac8e151730.png)

**Comment by Navid200** [comment]
There is always room for improvement.
If you look at the pull requests, you will see that it takes a very long time for a change to be approved.  One of the reasons is that a fix should not cause any new malfunctions even for older devices.  And it takes time and effort to verify that.

I don't think anyone disagrees that what you are suggesting for is an improvement.

My only point is that you should be able to import settings as is with the existing code.  

The other issue you have linked to is exactly the same in that sense.  After you export settings, you can easily rename the file, may be give it a date suffix.  Again, it is an improvement.  But, you can accomplish the objective with the code as is.

Put those in contrast with a scenario where a parent cannot follow her child's readings because a new version of Android has broken the xDrip code.  
Therefore, she cannot send the kid to school.  
If I have a say, I would prioritize the latter case.

**Comment by Navid200** [comment]
@master3395 Would you mind attaching the file so that I can have a look at it?
The file is inside a folder named xDrip-export inside your Downloads folder.  The filename is com.eveningoutpost.dexdrip_preferences.xml.

**Comment by master3395** [comment]
> @master3395 Would you mind attaching the file so that I can have a look at it?
> The file is inside a folder named xDrip-export inside your Downloads folder. The filename is com.eveningoutpost.dexdrip_preferences.xml.

Sure, had to remove the text inside "cloud storage" :)
[com.eveningoutpost.dexdrip_preferences.txt](https://github.com/NightscoutFoundation/xDrip/files/6358613/com.eveningoutpost.dexdrip_preferences.txt)

**Comment by Navid200** [comment]
@master3395 Is your SD card set up as internal storage?
Or, is it just plugged in and used as is?

**Comment by master3395** [comment]
> @master3395 Is your SD card set up as internal storage?
> Or, is it just plugged in and used as is?

There is no SD card on this phone.
OnePlus 8 Pro does not have an extra SD cardholder.
That's why I suggested a "chose location" feature.

**Comment by Navid200** [comment]
@master3395 Would you please export the settings again and try importing again?
Then, would you please show the event logs?

**Comment by Navid200** [comment]
Actually, this may be an Android 11 issue:  https://github.com/NightscoutFoundation/xDrip/issues/1547
I'm not sure why only some people experience it though.

**Comment by Navid200** [comment]
What do you see at the following on your phone?
Settings -> Privacy -> Permission manager -> Files and media

**Comment by master3395** [comment]
> What do you see at the following on your phone?
> Settings -> Privacy -> Permission manager -> Files and media

![Uploading Screenshot_20210507-010243.jpg…]()

**Comment by master3395** [comment]
> What do you see at the following on your phone?
> Settings -> Privacy -> Permission manager -> Files and media

![Screenshot_20210507-010243](https://user-images.githubusercontent.com/4199669/117376148-cebf3480-aed0-11eb-918b-9ebb4e5ad28f.jpeg)

**Comment by Navid200** [comment]
@master3395 Would you please try 3 consecutive times?
Does it work the third time?

**Comment by Navid200** [comment]
@master3395 
Would you please try to import the settings again?  If it fails, would you please try a second time right after?  If it fails again, would you please try a third time?
There are reports that attempting 3 times has worked.  
Knowing if it works for you or not is very beneficial for troubleshooting purposes.  Think of it as helping us figure out what the cause of the problem is.

Thanks

**Comment by master3395** [comment]
> @master3395
> Would you please try to import the settings again? If it fails, would you please try a second time right after? If it fails again, would you please try a third time?
> There are reports that attempting 3 times has worked.
> Knowing if it works for you or not is very beneficial for troubleshooting purposes. Think of it as helping us figure out what the cause of the problem is.
> 
> Thanks

Might try in 3 days when I change sensor.
Can't be bothered trying to set everything up again while I already have a sensor reading. (Has already been a big issue before).

**Comment by Navid200** [comment]
Of course

**Comment by master3395** [comment]
> @master3395
> Would you please try to import the settings again? If it fails, would you please try a second time right after? If it fails again, would you please try a third time?
> There are reports that attempting 3 times has worked.
> Knowing if it works for you or not is very beneficial for troubleshooting purposes. Think of it as helping us figure out what the cause of the problem is.
> 
> Thanks

Ït worked on the first try, the second try, and the third try now.

When I exported to SD, it created a new folder under /download/ named xDrip-export

I currently have version: e47fa3-2021.08.04
Code: 2108041822

**Comment by Navid200** [comment]
@master3395 
So, it's working now?
Fantastic.
Thanks so much for reporting and thanks for staying with it until it was resolved.
I don't know what was causing it and what resolved it though.  But, it's fantastic that it's working now.  Thanks
