### ISSUE TITLE
Deadlocks messages on actual nightly

### ISSUE THREAD

**Issue by swissalpine** [NightscoutFoundation/xDrip#1635]
As written on gitter: Since some nightlys I see deadlocks ...

![Screenshot_20210203-182346](https://user-images.githubusercontent.com/12517693/106784858-140f6400-664d-11eb-8d76-efb88aaa23a7.png)

xDrip+ Nightly
Version e89e23d-2021.01.29

Dexcom G6, 80....., Firmware 1.6.5.25

**Comment by JimZam** [comment]
Me too. What does it mean?
Thank you

**Comment by Navid200** [comment]
Would you please include in the first post what CGM and transmitter this is about so that it becomes a self-contained issue?

**Comment by swissalpine** [comment]
Dexcom G6, 80....., Firmware 1.6.5.25

**Comment by old-square-eyes** [comment]
These are mine G6, 80, 20210111

I seem to see them more collecting from Wear (patched Huawei 1)

![Screenshot_20210207-074651_xDrip+](https://user-images.githubusercontent.com/25760491/107127100-ba42be80-6918-11eb-9020-43ae872d62ab.jpg)

**Comment by swissalpine** [comment]
I don't wear a WearOS watch.

**Comment by old-square-eyes** [comment]
Sorry for the red herring, I turned off Wear collection and still see the deadlocks. Some periods seem worse than others. Maybe walking in and out of range. Will have to test that theory though.

**Comment by tolot27** [comment]
Please try [Nightly build 8th Feb 2021](https://github.com/NightscoutFoundation/xDrip/releases/tag/2021.02.08) which should have addressed this problem.

**Comment by old-square-eyes** [comment]
Haven't seen anymore errors since upgrading several hours ago.

**Comment by swissalpine** [comment]
Thanks a lot for the fix: The deadlock errors are gone!

**Comment by swissalpine** [comment]
I close this issue.
