### ISSUE TITLE
Error: xDrip looses connection often for up to 1hr, error in the logs: "No Transmitter mac address"

### ISSUE THREAD

**Issue by xannasavin** [NightscoutFoundation/xDrip#1636]
### Subject of the issue

Since the last nightlies (from January) xDrip has issues again in connecting the transmitter. It has downtimes of over an hour in between until it is able to reconnect.
The error message shown in the logs (I just uploaded the logs) is
"No transmitter mac address" followed by a note that location permission is missing. I double checked and xDrip has the location permission enabled.
This started already with the Nightly of January I installed and now got worse with the latest nightly of February.
It looks like the missing mac address is not the root of xDrip not being able to connect, since after phone reboot the transmitter connects again and can be read, but the error is spamming the logs again.

#### version of xDrip 
xDrip-plus-20210204-ea2c013.apk

#### type of hardware data source 

Dexcom G6 (Transmitter Serial 8JXLGT)

Huawei P30 Pro, EMUI 10.1.0, Android 10

Ticwatch Pro 2020

#### settings related to the issue

hard to tell, I did not change my settings over the past year. 

### Expected behavior

Well, a stable connection to the transmitter with as minimum downtimes as possible would be great of course.

### Actual behavior

xDrip looses connection pretty regulary, needing between 30min and 1hr to be able to reconnect.

### Screenshots

![Screenshot_20210205_105851_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/48352696/107020382-18e62c00-67a3-11eb-83f0-4345ec3eb71a.jpg)

**Comment by Navid200** [comment]
There is no similar experience in the community on facebook.  We have transmitters in use from 8G all the way to 8Q.
The only blackout is the 2-hour warm-up once every 10 days.
Do you have a facebook account to ensure your settings are correct?
https://www.facebook.com/groups/xDripG5/permalink/4838757582864365

**Comment by xannasavin** [comment]
Hi @Navid200 thank you for your answer and the link.

I checked the settings and they where almost the same. I changed the following ones to meet the screenshots:

### Other Misc: 
unchecked the Samsung Workarounds (though I had them active since the very beginning)
Did not check the "battery optimization warning" since I don't see the point why it should not warn?


### G5 Debug
"go on without calibration" is checked since I don't use calibrations
unchecked the "minimize scanning"
checked the "allow OB1 disconnect" though I had troubles last time with that option active

Let's see how it will work with those settings, will get back soon

**Comment by Navid200** [comment]
The battery optimization was an oversight on my part.  Will correct in a few hours.  Thanks so much for the feedback.  Please let me know how it goes.

**Comment by Alamo04** [comment]
If I see that right,  there is no location service running, or xdrip has no permission to use it.
Without location permission Bluetooth and XDrip didn't work.

**Comment by xannasavin** [comment]
@Alamo04 as written above, xDrip has full location service permissions. Bluetooth is of course turned on.
@Navid200 so far connection seems more stable - will continue observing for another day or so

**Comment by Navid200** [comment]
@xannasavin Would you mind showing your current logs after having updated the settings?

**Comment by xannasavin** [comment]
Sure, here you go. 

The error from above seems to be gone at the moment. It still displays the "missing location service" error, which is quite strange since - as said - xDrip has full location permission.

In between there was also a security update for the ROM, not sure what else changed there.
I still expirience minor "downtimes" (1 reading gets missed in between here and then) but at least no more those up to an hour missed readings.

![2021-02-07 14 40 06](https://user-images.githubusercontent.com/48352696/107148218-69e85280-6952-11eb-9f4d-2fa8d1c429d6.jpg)

**Comment by Navid200** [comment]
Are you sure the phone is on Android 10, and not 11?

**Comment by xannasavin** [comment]
![2021-02-07 15 50 13](https://user-images.githubusercontent.com/48352696/107150056-36aac100-695c-11eb-85d8-ae9450b5a6d6.jpg)

100% :D

**Comment by nickb24** [comment]
The error messages for location services you are seeing are for your smart watch. If you are not using your smart watch as a collector I would disable that setting from the smart watch.

**Comment by xannasavin** [comment]
Hey @nickb24 thanks a lot for that hint!
Indeed I am not using the watch as collector, those settings are unticked on the watch and also in xDrip). however I granted xDrip on the watch now the location permissions - just in case... The watch is soleley to display the measurements.
will come back soon if everything seems solved now. (just right now I am missing another reading >< )

**Comment by xannasavin** [comment]
Thanks again @nickb24 and @Navid200 looks like this is solved for me.
