### ISSUE TITLE
Maximum Sync Queue size Exceeded!  pop-up comes up frequently on the master

### ISSUE THREAD

**Issue by Navid200** [NightscoutFoundation/xDrip#1638]
There is one master and two followers.
The followers are xDrip Sync  followers.
The followers receive readings, no problem.

The master gets the pop-up "Maximum Sync Queue size Exceeded!" frequently.
It pops up any time an entry is made on the master.

I see this pop-up on line 755 of GcmActivity.java

@tzachi-dar I am sorry for tagging you.  I wonder if you can give me any hints as to what could trigger this if the followers are working fine, and if there is a way to stop the pop-ups.

I see this issue that has the pop-up in common:  https://github.com/NightscoutFoundation/xDrip/issues/499

This is not an issue that I myself have experienced.  This is coming up on facebook.  I can get more detail from them if you guys tell me what you need.

**Comment by tolot27** [comment]
Important environment information like xDrip version is missing. Commit f4a1b6a fixed something with the queue. Maybe, a recent version does not have this issue.

**Comment by tolot27** [comment]
Isn't it a duplicate of #1626?

**Comment by Navid200** [comment]
I am waiting to get a response to my request for the revisions.
It is related that both seem to be caused by Google services.
However, this one is triggered somewhere else in the code, where enabling Desert Sync makes no difference.

This one is more annoying because there doesn't seem to be a way to stop the pop-ups on the screen.

**Comment by Navid200** [comment]
Will open if I get more data.

**Comment by Navid200** [comment]
First report on facebook that updating to February 11, 2021 has stopped the pop-ups.

**Comment by Atterna** [comment]
I still get the pop ups :/ Libre 2 EU + bubble, nigtscout and master to a follower. Everything seems to be working as intended. I try to ignore the message but after months it's starting to bug me. Hope it'll be gone soon.

**Comment by Navid200** [comment]
@Atterna What scheme are the followers on?
If you use Nightscout follower, and disable xDrip sync on the master, you will not get this pop-up anymore.
