### ISSUE TITLE
Several glucose meters support simultaneously

### ISSUE THREAD

**Issue by checkatillo** [NightscoutFoundation/xDrip#1643]
For now you're only allowed to use one glucose meter at a time. Once you're connecting a new one, xdrip won't receive values from the previous one

It would be great to be able to add as many glucose meters as needed. Then it's easier to keep all the values in the app and thus in Nightscout

I'd appreciate this as I'm using several Bluetooth glucose meters (even of the same kind) to avoid forgetting it somewhere (I have a spare one at work and one is always laying in my jacket's pocket)
To have all the values I repair the current glucose meter with xdrip every time I switch

**Comment by Navid200** [comment]
You can just enter the reading from your meter manually into xDrip, right?

**Comment by tolot27** [comment]
> You can just enter the reading from your meter manually into xDrip, right?

That's not the question. xDrip supports receiving data from only one paired glucometer. @checkatillo asks if more than one glucometer can be paired and used as bg input.

**Comment by Navid200** [comment]
I understand the question.  
Is there a point in making the code more complicated just to accomplish something that is not necessary?

Where do we draw the line?  
When do we say, yes this can be done, but, please let's wait for a few more developers to join the very small group before we continue to make the xDrip code more and more complicated?

**Comment by tolot27** [comment]
This is a nice-to-have feature with low user impact. We postpone it until we have more developers.

**Comment by szantos** [comment]
> This is a nice-to-have feature with low user impact. We postpone it until we have more developers.

Totally agree: would be very nice to have, but since it won't impact many users, it's okay to be postponed.
