### ISSUE TITLE
FR: Alarm clock

### ISSUE THREAD

**Issue by ARkaine2** [NightscoutFoundation/xDrip#1644]
It will be nice to have  in xDrip alarm clock or (maybe even better) timer that (with choosable sound) can be spedified like insulin/carbs/BG, but in FUTURE time.

**Comment by Navid200** [comment]
You can use your smartphone alarm, can't you?
What exactly do you expect xDrip to do that you cannot do with a regular clock included with Android?

**Comment by tolot27** [comment]
@ARkaine2 We don't have the time to reinvent the wheel. Instead, we like to focus on the existing bugs and features. xDrip has a lot of features and settings, already and it is hard do support it. We are a very small dev team.
Contributions and PRs are always welcome.
