### ISSUE TITLE
FR: Actrapid as basal insulin

### ISSUE THREAD

**Issue by ARkaine2** [NightscoutFoundation/xDrip#1645]
I need very much:

1. Actrapid as basal (in prediction simulation) should have blue pipette/dropper (like other [more long-acting] basal insulins) — so, there will be indication/difference of another (basal) insulin with certain units specified. 

2. Use Basal Activity ("Plot basal activity on graph and incorporate in predictive model") checkpoint should  work with Actrapid as basal.

Maybe to realize this in xDrip's insulins' profiles should be added ActrapidBasal or Actrapid2 profile.

Please. 
All my compensation is based on it.
Thanks.

**Comment by gruoner** [comment]
Hi ARkaine2

do u use actrapid as a basal profile? We are using it as bolus for the morning.... Do we have more insulin products with "multiple" usages? 
When we want do include or exclude profiles from prediction we might define a switch for each of them.

**Comment by dubidrubi** [comment]
Agree with @gruoner... We also use Actrapid as a bolus one before meals... Never heard about using it as a basal one

**Comment by Navid200** [comment]
@ARkaine2 Please close this issue if it has been resolved.
If not, please respond to the questions posed to you.
Thanks

**Comment by Navid200** [comment]
Please respond to the suggestions before reopening.
