### ISSUE TITLE
Libre 2 + MiaoMiao 2 + xDrip sudden extreme high values

### ISSUE THREAD

**Issue by Danielvisser** [NightscoutFoundation/xDrip#1646]
Hello,

Since I switched to the Libre 2 sensor (used Libre 1 before), nothing has been working like it's supposed to. I've followed this guide to make the Libre 2 sensor work with xDrip (& MM2): https://miaomiaoreader.medium.com/how-to-make-libre-us-14-days-sensors-work-with-miaomiao2-on-xdrip-35b431a40940.

This seemed to be working, except for the regular crashing of OOPalgorithm, causing xDrip to not receive any data. My second Libre 2 sensor seemed to be broken. It constantly gave the message: "Glucose reading is unavailable. Try scanning again in 10 minutes". This went on for about 6 hours before I decided to place a new one (my third libre 2 sensor). This third sensor seemed to be working fine the first two days, but is now doing the exact same thing. xDrip shows sudden extreme high values, while my BGC is actually 5.3 (mmol) (see screenshot). I've never experienced any of these issues with the Libre 1.

![image](https://user-images.githubusercontent.com/11757183/108054484-ff6c9c00-704e-11eb-8a4f-20dff0d2e531.png)

I hope someone here recognizes the issue and can help me out. I do not have the luxury to burn through these sensors so fast..

**Comment by ksilive** [comment]
It broke down probably.
Did you hit a vein, did the sensor bleed for example?

**Comment by Navid200** [comment]
@Danielvisser Have you asked  your question from the support channels?
When you opened this issue, you must have seen the suggestion.  But, here there are again:
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

I will have to close this unless it is either a feature request or a bug report.  Is it?
You can close it yourself too.
