### ISSUE TITLE
xDrip confuses G5 with a G6 and performs a preemptive restart on day 9 as well as on day 6

### ISSUE THREAD

**Issue by Navid200** [NightscoutFoundation/xDrip#1647]
### Expected behavior
Dexcom G5 can be used in Native mode.  But, since G5 sends raw data, you can still access the calibration graph.  And xDrip removes "Initial calibration" from the menu after initial calibrations have been submitted and replaces it with "Add calibration".

### Your environment
The problem was observed with the February 11, 2021 release, and February 3, 2021.

### Actual behavior
Calibrations are sent to the transmitter and are accepted by the G5 transmitter.  However, xDrip logs show they are rejected by xDrip.
![tempFileForShare_20210216-234941](https://user-images.githubusercontent.com/51497406/108206590-96d7fa80-70f4-11eb-93a3-64454447f949.jpg)

Logs show calibrations have been rejected.
No access to adding calibration in the top left menu as only initial calibration is shown there.
No access to calibration graph.
Empty calibration data table.

The symptoms match the behavior of xDrip with a device that does not send raw data like a Firefly G6,

After installing the January 29, 2021 version, the problem was resolved. 

### Steps to reproduce the behavior:
Install xDrip release February 11, 2021
Start a G5 sensor in native mode
Apply initial calibrations
Check calibration data table, or check the logs.

@viq:hackerspace.pl reported this in the Gitter room.
Another individual reported it on facebook where the calibration graph being missing and the calibration data table being empty were reported.
The calibration rejection logs were reported by both users.

**Comment by jamorham** [comment]
The screenshot implies that a bloodtest was delivered from a bluetooth connected glucose meter which it believes was ~9000 seconds old. If the finger stick test was just done recently then we need to determine if the clock on the meter is correct or if there is an issue with the user's local timezone vs the clock on the meter and if that is the source of the >1 hour rejection message. It may also be (more likely?) that there were multiple tests synced from the meter and that only one of those was used and the other rejected which is why there is a report of success and also rejection in the screenshot.

We also want to know the transmitter firmware version to determine the issue regarding raw.

**Comment by Navid200** [comment]
You are talking to him in the Gitter room.
The firmware version is 1.0.4.15.

**Comment by jamorham** [comment]
Please try the 17th Feb nightly to see if it resolves the issue.

**Comment by viq** [comment]
Sorry for screenshot, attaching what happened when I calibrated using the `2021.02.17` version. I don't know where this "calibration beyond 4 days" is coming from. The dot from syncing with glucometer appears right there, and clicking on it is how initiate calibration 

![xdrip_logs](https://user-images.githubusercontent.com/639461/108288118-575ced00-718c-11eb-9767-834b8a594d56.png)

**Comment by Navid200** [comment]
If you tap on the top left menu button, and on calibration graph, what does it show?  Is it empty, or does it show your initial calibrations?

**Comment by viq** [comment]
It does show some calibrations. Currently it shows three from today, and one from 5 days ago.

**Comment by Navid200** [comment]
Did you just update to the new version and calibrated?
Or, did you start the sensor after updating and then, calibrated?

**Comment by viq** [comment]
Update and (single) calibrate.

**Comment by Navid200** [comment]
OK
Please let us know the next time you start the sensor.  Only then, will you have to provide initial calibrations again.  Only then, will you know if the issue has ben resolved or not.

**Comment by viq** [comment]
Sensor session should be restarted in a few hours, so we should know soon.

**Comment by viq** [comment]
It seems to be working. What should I show to verify it?

**Comment by Navid200** [comment]
Would you please show the log showing that you started a sensor followed by initial calibration that xDrip did not complain about?  You may need to post multiple screens if they don't all fit.
You can also show the calibration graph.

**Comment by viq** [comment]
Attaching screenshots:
![Screenshot_20210218-152053_xDrip+](https://user-images.githubusercontent.com/639461/108372547-3aadcd00-71ff-11eb-901b-b98937b31693.png)
![Screenshot_20210218-152445_xDrip+](https://user-images.githubusercontent.com/639461/108372558-3da8bd80-71ff-11eb-9f13-953c8882a169.png)
![20210218_152906](https://user-images.githubusercontent.com/639461/108372574-40a3ae00-71ff-11eb-8fd0-af0e2e023b81.png)

**Comment by Navid200** [comment]
@jamorham Are those "calibration appears to have been deleted" logs expected?

**Comment by Navid200** [comment]
@jamorham Would the following advice to the user community be valid in your opinion?

If you use G5 in native mode, avoid the following releases of xDrip: February 3, 2021 to February 11, 2021 inclusive.

**Comment by Navid200** [comment]
Considering this is a new firmware, hopefully, we will be able to hard reset it.

**Comment by Navid200** [comment]
@jamorham Is this a new firmware too?

1.0.4.14

Should it be added to the code?


![152023351_800007287256778_1308029528575491858_o](https://user-images.githubusercontent.com/51497406/108576647-5cd14900-72ec-11eb-8ed1-3f2a483af37d.jpg)

**Comment by viq** [comment]
FYI, `2021.02.17` just restarted my G5 sensor at 9 days, after previously restarting it at 6 days.

**Comment by Navid200** [comment]
Correct me if I'm wrong.  You never started a fresh session after upgrading to 2021.012.17.
You just upgraded and kept using the session that was in progress.
I think xDrip never recognized your transmitter as a valid G5 when you started the current session.
xDrip was updated so that it is.
  You need to start a fresh session (not a restart).

**Comment by viq** [comment]
Then why did it restart the session at 6 days?

**Comment by Navid200** [comment]
The restart on day 9 is the behavior of xDrip when dealing with a G6.
It seems to me you never gave a chance to the new code to do its job by performing a fresh start.  But, if you like to argue to differ, you are entitled of course.
I leave you to it.

**Comment by viq** [comment]
Yeah, I accept that it restarted at 9 days because it thinks it's a G6. I'm just surprised it **also** restarted at day 6, which implies it **also** thinks it's a G5. So it kind of thinks it's both??
Do you think I should stop this sensor and start it anew, or just wait a few more days for it to die and see how a new one will behave?

**Comment by Navid200** [comment]
That's up to you.
I guess there are pros and cons with either one of those choices.
If you stop now and start again, you will lose all your calibrations and will have to start calibrating again.
If you wait for the sensor to die and try then and we discover that the problem still exists, our report to the developers will be delayed by a few days.

As it only affects you directly, I'd say it's your choice.
I will support you either way.

**Comment by Navid200** [comment]
@viq Any update?  
Have you still not started a new sensor?

**Comment by viq** [comment]
I did a stop and start on the same one, since it's still working fine as far as I can tell. Though I'm not sure it'll continue doing so long enough to get conclusive results within it's lifetime.

**Comment by Navid200** [comment]
So, after you did initial calibration, the next time looking at the top left menu, you had add calibration instead of the same initial calibration, right?

**Comment by viq** [comment]
Yes.

**Comment by Navid200** [comment]
Great.
If it ever performs a restart on day9, please post here and we will reopen.  I don't think that will happen.

For now, I close this.

**Comment by viq** [comment]
That sensor just got restarted on day 9.

**Comment by viq** [comment]
The logs look very confusing.

**Comment by viq** [comment]
The logs look very confusing.
![xdrip-2021-03-05-123203](https://user-images.githubusercontent.com/639461/110110536-44166800-7daf-11eb-9087-0fe3972157cc.png)

**Comment by Navid200** [comment]
The only solution I am aware of, until a developer addresses this, is to go back to the release of January 29, 2021.

**Comment by viq** [comment]
I'm not necessarily looking for a solution right now, just reporting that this is something that someone may want to look at.

**Comment by Navid200** [comment]
So, you are OK with a restart on day 9 as well as on day 6 every time?

**Comment by viq** [comment]
Every time, for ever to come? No. But I can probably live with it for some weeks more, if it's useful to someone working on this.

**Comment by Navid200** [comment]
>I'm not necessarily looking for a solution right now,

I am not even using G5.  I use G6.  
I opened this issue for people like you who still use G5.  I have no problem with helping.  
But, when you make a statement like that, I wonder what am I missing.  If he is not looking for a solution, why am I bothering?
I have no idea why you had to make that statement.  Do you?

**Comment by viq** [comment]
Sorry for my poor wording. What I meant is that I'm not necessarily looking for a quick workaround like downgrading the app, and I'm fine living with the issue for a while and using the version with the bug if it allows someone to get useful information to fix this.

**Comment by Chris2001** [comment]
Thanks to @Navid200 I switched to the 20210129 version to tackle a problem with the original dex reader (signal lost for hours) with the current 20210308 version. OTOH I now sometimes don't have any values for 15 minutes. Using a 1.6.5.25 fw with old 80xxxx transmitter ... thanks all ...

**Comment by Navid200** [comment]
@Chris2001 Would you mind showing/sharing your current settings from the following page?
Settings -> G5/G6 Debug Settings

**Comment by Chris2001** [comment]
> 
> 
> @Chris2001 Would you mind showing/sharing your current settings from the following page?
> Settings -> G5/G6 Debug Settings

Thanks, but I think that was just a temporary glitch, everything seems to work fine now with the 20210129-version.

**Comment by viq** [comment]
With recent nightlies G5 sensor was restarted only on day 6. No restart happened on day 9.

**Comment by Navid200** [comment]
@Chris2001 Would you please explain the problem you experienced with the March 8, 2021 release?
Please don't use Acronyms (dex reader) as everyone may not know what you mean.  I suppose you meant Dexcom receiver?

**Comment by Chris2001** [comment]
> 
> 
> @Chris2001 Would you please explain the problem you experienced with the March 8, 2021 release?
> Please don't use Acronyms (dex reader) as everyone may not know what you mean. I suppose you meant Dexcom receiver?

Yes, sorry, I meant the original Dexcom Reader. It was blocked for hours not receiving any values when I was using the current nightly. After switching back to the older version (29.01.2021) everything went to normal again (both devices, the original reader as well as my phone with Xdrip+ receiving values every 5 minutes now).

**Comment by Chris2001** [comment]
Ok, today I had a preemptive restart for the G6 (still using the 20210129 version) and again the G6 is now treated as a G5 from now on (as it seems). Also there were sensor errors for about 30 mins ... I guess I will revert to 20201115 next week ....

**Comment by Navid200** [comment]
@Chris2001 Are you saying it restarted your G6 on day 6?  Or, what do you mean by G6 being treated as a G5?

And why would you use November 15, 2020?  There is a note under that release telling you "connectivity issues have been reported ...".

**Comment by Chris2001** [comment]
No, I used preemptive restart (automatic) on day 9. Now the system will aks for calibration every 24 hours (not a big problem of course). November 15 did not show "conectivity issues" with my Pixel 4a

**Comment by Navid200** [comment]
@Chris2001 If you don't enter the sensor code correctly, or if you enter 0000 as the code, you will be operating G6 in "no-code" mode.  In that mode, you will be asked to calibrate once a day.
None of this is related to this particular issue.

**Comment by Chris2001** [comment]
I didn't enter 0000, I started the sensor like always with aeproper code that was acceptet. But after the preemptive restart (day 9) it now seems to be running in "no-code" mode. Sorry for the fuss, it really isn't a big problem. Everything else works just fine, also the precision is still very high.

**Comment by Navid200** [comment]
I didn't know that was the case.  Thanks for reporting it.  
How did it behave before after a preemptive restart?  I have never had a G6 that could perform a preemptive restart.

G6 uses factory calibration, which only covers 10 days.
After restarting a G6, factory calibration cannot continue because there is no characteristic programmed for day 11 or 12 or 13 etc.
So, what you describe makes perfect sense to me.  After a restart, it automatically switches to no-code mode as factory calibration is not valid any longer.

**Comment by Chris2001** [comment]
> How did it behave before after a preemptive restart? I have never had a G6 that could perform a preemptive restart.

Sorry again for the confusion, I have an old 80... transmitter with replaced battery (firmware 1.6.5.25) ... with the preemptive restart you can do 'time travel' back to day 3, so it normally works flawlessly (it did before). So the transmitter really theoretically will work in *factory calibraton mode* until it fails. Normally sensors work for me between 15 and 25 days like that (after that the values get unreliable especially when there is sudden change, up or down).

**Comment by Navid200** [comment]
The time travel capability may have been removed.  Although, I am not 100% sure.

**Comment by Navid200** [comment]
I am closing this issue because I believe the original issue has been resolved.

I will be learning more about the time travel.  We can talk more about it here if needed in the closed issue, or somewhere else.

**Comment by Chris2001** [comment]
>  We can talk more about it here if needed in the closed issue, or somewhere else.

Thanks, highly appreciated ...
