### ISSUE TITLE
Can we rename "HbA1c est" to "GMI", and update the formula?

### ISSUE THREAD

**Issue by Navid200** [NightscoutFoundation/xDrip#1653]
A Hemoglobin A1C blood test result represents the average blood glucose over the past 3 months.
A daily A1C makes no sense.  Your A1C test today represents your average blood glucose over the past 90 days.  Your A1C yesterday represented your average blood glucose over the period starting 91 days ago and ending yesterday.  Your day to day A1C variation is minimal.  

A paper was published, in 2008, (https://care.diabetesjournals.org/content/diacare/31/8/1473.full.pdf) suggesting a correlation between A1C test results and average blood glucose over the past 90 days.  
The paper presents the results in the following figure.
![F1 large](https://user-images.githubusercontent.com/51497406/108604420-da906580-737b-11eb-972f-72566a4b0805.jpg)

The paper presents a line in that graph representing the correlation.  The line is a linear regression fit.  
In that graph, the horizontal and vertical axes are A1C test results at the end of month 3 and calculated average blood glucose during the past 3 months respectively. 
Using the formula (linear regression), suggested in this paper, one can use the average blood glucose readings over the past 3 months to estimate what their A1C test results would be today.  You can see in the graph that this is just an estimate and there could be considerable error.

The correlation between those two figures is only suggested when the average blood glucose is over the period of the past 3 months.
There is no suggestion that if you know your daily average blood glucose today, you can use the same formula to estimate what your A1C would be today.  Your A1C today should be calculated using your average blood glucose over the past 90 days.  

But xDrip offers a calculation that has no significance and could be quite misleading.
Go to the Statistics page in xDrip from the top left menu.  Swipe right twice.  On that page, you can see a set of parameters including HbA1c est.  At the top of the page, you can see the following options:   TD, YTD, 7D, 30D and 90D, which stand for today, yesterday, last 7 days, last 30 days and last 90 days.
You can see that all the parameters (including A1C est) are affected as you change the options.  So, you can choose TD (today) and you will still get a value for HbA1c est.
It doesn't end here.  Go to Settings -> Less common settings -> Extra Status Line.  Enable "Extra Status Line".  Enable "A1c DCCT".  Now, go back to the main screen.  You will see A1c reported under the current delta.  The value reported is not the estimated A1C based on the average over the past 90 days.  Rather, it is the estimated value, using the formula, based on the daily average. 

This is an incorrect use of the formula, which could result in misleading information.
I suggest the following 2 changes:

1- The estimated A1C should be blanked out on the Statistics page unless the 90D option is selected.
2- When the extra status line is enabled and A1C is chosen to be shown, the correct estimated A1C (based on the average blood glucose over the past 90 days) should be shown. 

If you like to offer the option of seeing daily average blood glucose, please do just that; don't use it to calculate A1C; present the daily average as is; don't call it A1C; call it AG.

**Comment by MasterPlexus** [comment]
I understand what you mean, and what your fears here are. I could just say that I never Missunterstand the value. For me it tolds if I select one week, that the hba1c will be this value if I will have the same sugar arrangement in the next 3 month which I had in the last week. So a prospective view. 
As far as I know, other systems donut the same way, also Libre view calculates the hba1c if only values are scanned for some days and not all 90 days. 
But as I said, I understand what you mean, as this could be misunderstood by some users. May some alignment , mark or short explanation will be helpful if the value is not based on the last 90days.

**Comment by Navid200** [comment]
Thanks for that.  I agree it would be perfect if there could be a note added.

Can we have a note emphasizing that for HbA1c only, the value shown is what it will be and not what it is?

**Comment by philou78** [comment]
The International Diabetes Center names this calculated value as follows:
"GMI (glucose management indicator): Calculated from average glucose; estimates your future lab A1c"
(http://www.agpreport.org/agp/agpreports#SMBG_AGP)

This is very important to get this value for each selected period. It helps people who need to improve their A1C even though it really estimates A1C only for the 90D period due to the lifespan of hemoglobin.

**Comment by Navid200** [comment]
@philou78  Thanks for that link.

This is a paper that describes GMI:  
https://care.diabetesjournals.org/content/diacare/41/11/2275.full.pdf

"This Perspective will address why a new name
for eA1C was needed, why GMI was selected as the new name, how GMI is
calculated, and how to understand and explain GMI if one chooses to use GMI as a
tool in diabetes education or management".


Should we then change the name on the xDrip statistics page from Hb1c est to GMI, and make the slight modification to the formulae as described in the paper?

**Comment by MasterPlexus** [comment]
@navid200 for me this looks feasible and logical. I will get that, and try to made a pull request. It will need some time of course, but it will bring me back into the code which I missed ;)

If an other one will get this point faster just state it here, not to do it double.

**Comment by Navid200** [comment]
OMG, it was just a suggestion.  Thanks a lot.
Please let's make sure Adrian (@AdrianLxM) will be OK with this.  Please don't make a change unless he approves.

**Comment by AdrianLxM** [comment]
I would _not_ like to have a value showing another timeframe than selected.

**Comment by Navid200** [comment]
@AdrianLxM The only suggestion is to change the name from A1C to GMI.
And I haven't read the paper fully yet.  I think they have made a slight modification to the formulae by combining the results of 4 different studies.
The value will always be based on the selected range as is now.

**Comment by MasterPlexus** [comment]
May we could change the Titel to gmi, if the time slot is different than 90 days. And let 90days then for 1ac.
Anyway, I'll check then also the formula's , but I feel the established ones as sufficient at the moment. Not sure if a change of 0.1 of the value at the end will bring a big help, knowing the Situation that also the measurements could have some diffs.

**Comment by Navid200** [comment]
Not what I expected.  The two look quite different.  
Will do more research.
Please let me know if anyone has any explanation.


![Screenshot 2021-02-23 214330](https://user-images.githubusercontent.com/51497406/108939776-3bd86300-7620-11eb-9225-1e2c2dd80e8f.png)

**Comment by Navid200** [comment]
The Dexcom app is also using the updated formula:

![164204007_10225567122631653_3147251438616353955_n](https://user-images.githubusercontent.com/51497406/112695828-23e04300-8e5b-11eb-8004-fd299250f99d.jpg)

For the same average, xDrip would currently have an A1C est of 5.8.

**Comment by rraider89** [comment]
Might I suggest that we consider the usability of the app vs the value of using exact scientific terms? Most users will just be confused by adding yet another unknown acronym and will not benefit from a descriptive change that requires further understanding. If you're the rare person schooled in the GMI/A1C differentiation the reading isn't fooling you anyway.  Dealing with diabetes and installing/using Xdrip is a real feat for even the technically and scientifically oriented among us, and every effort should be made not to hinder the usability.

**Comment by rraider89** [comment]
> I have explained the details here so that it can be seen what the source of the information is.
> Someone who has only been using xDrip to see their estimated A1C, without paying attention to where the estimated A1C came from, can continue to do so.
> Why would updating xDrip affect its usability in a negative way?
> 
> I have put a hold on this to see if the new (updated) formula is used universally or not.
> We should not update if no one picks it up.
> 
> But, can you explain how using an outdated calculation, by xDrip, is going to help someone who has difficulty establishing connectivity with their sensor, or anything else you are having difficulty with?

Sure. You wrote "Can we rename "HbA1c est" to "GMI", and update the formulae?". The HbA1c est is helpful, even for one day for understanding how you've done for the day, assuming your performance continued at this pace for 90 days. Even if the more accurate GMI has become the standard on Dexcom and Libre apps, its still highly unlikely that most current users and all new users would understand what GMI is. It will be quite some time if ever that doctors and educators and books start using the term GMI to help patients understand an estimate not used iby doctors or in clinical settings. If the goal is to be more accurate in our language we shouldn't do so at the expense of the term losing its value due to users not knowing what the acronym is or what it means. I think the idea of adding GMI to the existing HbA1c est is a good idea. Perhaps "HbA1c est / GMI" or "GMI (HbA1c est)".

**Comment by tolot27** [comment]
@rraider89 No, the HbA1c is an estimation of the long-term glucose binding to hemoglobin. Hence, it is not useful to understand the daily performance. Please use TIR instead, which gets increased attention in therapy.

**Comment by rraider89** [comment]
I think you're being too technical and not practical. A daily estimate of your hba1c tells you what your HbA1c would likely be if your blood sugar performed exactly like it did today for the next 89 days. If you're shooting for a Hba1c below 5 then it's helpful to know that today's hba1c estimate was 4 or 7 or whatever.

**Comment by tolot27** [comment]
> I think you're being too technical and not practical.

No, it is a medical and biological point of view. You cannot influence the HbA1c just by one good or bad day. Consider the extreme case that you are on every odd day at 200 mg/dl on average and on every even day at 40 mg/dl on average. Your measurable HbA1c would still be near optimal optimal even if your TIR is 0% on every day. Hence, it is absolutely useless to predict it just for one day. Please consider the TIR for daily use.

**Comment by szantos** [comment]
A slightly other aspect, but it also addresses the HbA1c estimation:

Please consider using a weighted average for HbA1c estimation instead of an arithmetic average to have a better approximation.

[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4771657/](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4771657/)

**Comment by Navid200** [comment]
We should not make this change until we are certain this new index has gained enough popularity.
The conversation can continue even with the issue closed.
Please don't open a new issue if you are interested in the same.  Please post here.

**Comment by Navid200** [comment]
There seems to be a new (2024) publication related to GMI: https://scholar.google.com/scholar_url?url=https://diabetesjournals.org/care/article-pdf/47/6/906/764767/dci230086.pdf&hl=en&sa=T&oi=ucasa&ct=ufr&ei=UybzZtfrJ_-_6rQP_ofw-Aw&scisig=AFWwaeaEaKQfnRYYCaAlkcLUXBK6  

I am glad we did not switch to the new formula.  I still have not read the whole thing.  But, the summary seems to suggest that one should focus on time in range rather than trying to predict A1C.
