### ISSUE TITLE
Please add a note to the following two xDrip releases

### ISSUE THREAD

**Issue by Navid200** [NightscoutFoundation/xDrip#1655]
When we had the frequent pairing request fiasco in early November of 2020, the developers worked tirelessly to come up with a solution, test it, and release it (November 27, 2020 release).  And it took a very short time to successfully solve the problem for the community.
Many thanks for your great work.

In the process, two new versions were released that were work-in-progress.  Those are November 15 and November 26, 2020.
People still install those and ask why they have connectivity issues.

Would you please either remove those two releases from public access, or add the following note to each visible to anyone who may attempt to download?

_Connectivity issues for Dexcom transmitters have been reported._

**Comment by tolot27** [comment]
I've added "Connectivity issues for Dexcom transmitters have been reported. Do not install this build if you are using Dexcom hardware source" to the description. But how does it help in general? Nobody will read this information if nightly updates are installed.

**Comment by Navid200** [comment]
Thanks so much for adding those notes.
I think if the note stops one person from installing, it is still a step forward.

I understand your concern. 
Can we not remove those two releases from the list?

**Comment by Navid200** [comment]
_Nobody will read this information if nightly updates are installed._

If someone is using the nightly channel in their automatic update now, they will never get those releases.  They will get the latest nightly.

If they were on the nightly channel and right after having got one of those two releases, they changed their channel to the beta channel, they will still be on those releases.  Not much we can do about that.  I advise people as soon as I see them using one.

But, what you have done now hopefully stop people from installing them now.

**Comment by Navid200** [comment]
Thanks a lot
