### ISSUE TITLE
FR: Additional (secondary) horizontal (BG) lines.

### ISSUE THREAD

**Issue by ARkaine2** [NightscoutFoundation/xDrip#1656]
Hi,

I need (very much!!!) intermediate horizontal (BG) lines in main xDrip's view/screen.
(probably it should be realized like an option [with opacity %] for those, who doesn't need it)

<details><summary>Something like:</summary>
<p>

![109043769-596a0300-76da-11eb-987a-d102c599e552](https://user-images.githubusercontent.com/31447095/109145062-a4cbf200-776a-11eb-9022-15d86d4d9b3a.jpg)

</p>
</details>

Because it helps me to coordinate my action/thoughts about compensation based on xDrip's predictions.

Thanks.

**Comment by emp-00** [comment]
Please specify, what exactly do you mean: really MORE lines than we already have? 
Can you edit the picture and show how your proposal should look like?
![image](https://user-images.githubusercontent.com/60714349/109062535-5aa22c80-76e8-11eb-8ade-257e170aa7c6.png)

**Comment by tolot27** [comment]
What should these lines represent? Currently, I don't see any reason why we should add additional lines. We already have the lower and upper bound lines which are really helpful for therapy.

**Comment by ARkaine2** [comment]
**tolot27** ,
ATM lines represent only even numbers (in mmol/l) (and we also can specify lower/higher range and target glucose).
I talk about predictions (prediction simulation): 
We can see/compare how insulin will low/affect BG per each hour.
But there are no "intermediate" values (for odd numbers) to see these changes in more details.

**emp-00** ,
`Can you edit the picture and show how your proposal should look like?`
<details><summary>It's nice, but I'd wish one more line. :D</summary>
<p>

![109062535-5aa22c80-76e8-11eb-8ade-257e170aa7c6 c](https://user-images.githubusercontent.com/31447095/109144606-10618f80-776a-11eb-91e9-4a5308a95b11.png)

</p>
</details>


<details><summary>If follow my ask/idea "directly", it would look like:</summary>
<p>

![109062535-5aa22c80-76e8-11eb-8ade-257e170aa7c6 — копия cc](https://user-images.githubusercontent.com/31447095/109144633-18213400-776a-11eb-9442-9ead56523d71.png)

</p>
</details>

As you can see, there's nothing awful.

**Comment by tolot27** [comment]
@ARkaine2 I did not get it. You just draw a horizontal line at about 128 mg/dl. But I don't see any benefit of this line.

**Comment by ARkaine2** [comment]
**tolot27** 
Benefit is that with "intermediate" lines we can know BG change more precisely per each period of time.

<details><summary>Something like:</summary>
<p>

![photo_2021-02-25_13-19-15 ссс](https://user-images.githubusercontent.com/31447095/109146920-17d66800-776d-11eb-8557-cde6c8080ebd.jpg)

</p>
</details>

Without these lines we have to rely on the eye; эut with these lines we can even "draw" insulin action by multiple injections / combining insulins and xDrip will predict them correctly / more precise.

**Comment by emp-00** [comment]
Sorry, I also don't understand what exactly you are proposing: Your screenshot shows a prediction down to a severe Hypo => this information should trigger you eating something to avoid the Hypo. For me this is more than enough information. What's the benefit of extra lines or boxes?

**Comment by tolot27** [comment]
@ARkaine2 It looks like you like to do some more sophisticated analyses. Maybe it is easier for you if you import the xDrip database in your statistics program of choice and do the stuff there?

**Comment by Navid200** [comment]
@ARkaine2 Do you just want a horizontal line that you can position (move up or down) on the screen?

**Comment by Navid200** [comment]
We can always reopen this if you make it clear what you are requesting.  
There is no way a developer can develop something if it's not clear what he/she is supposed to develop.
