### ISSUE TITLE
Wrong German translation in "Werte vorlesen" menue

### ISSUE THREAD

**Issue by utzaki** [NightscoutFoundation/xDrip#1657]
The German translation in the "Werte vorlesen" menue seems not to be correct. It is supposed to be "..zur Sprachausgabe von ..." instead "..zur Spracheingabe von...". Small difference, but totally different meaning.

xDrip version 2021.02.03
![image](https://user-images.githubusercontent.com/53113714/109111509-55210280-7739-11eb-96a7-6f7fd9bcb76b.png)

**Comment by tolot27** [comment]
Thanks to bringing this to our attention. Please suggest further translation changes at https://crowdin.com/project/xdrip
