### ISSUE TITLE
Feature: Suspend for X minutes / until reactivated

### ISSUE THREAD

**Issue by SandraK82** [NightscoutFoundation/xDrip#166]
An option for only over night Libre-CGM users (LimiTTer, bluecon, transmitter, bluereader) would be welcome to disable xDrips complete functionality for a given period of time, or until reactivation (like the alarms)

**Comment by jamorham** [comment]
Hi Sandra, Can you explain what the use case for this is? Is it for when the bridge device is disconnected temporarily?

**Comment by SandraK82** [comment]
I received multiple questions from people who are only wanting over night cgm with libre and blueReader. Therefore Xdrip does alarms all the day currently. 

Von meinem iPhone gesendet

**Comment by tzachi-dar** [comment]
BG alarms, and missed reading alarm can be set per time of day.
What alerts are they getting?

Thanks
Tzachi

**Comment by SandraK82** [comment]
Ah, I was not aware of this possibility!

**Comment by jamorham** [comment]
The Sept 22nd nightly includes a new data source option of `Disable Collection` which switches the collector off. Please let me know if this helps. You should be able to change data source to this which will shut down the collector. If you still get problems with alarms etc please let me know.

**Comment by Navid200** [comment]
@SandraK82 If you are happy with the outcome, would you please close the issue?
Thanks
