### ISSUE TITLE
Device is marked as bonded but we are being asked to bond so attempting to unbond first

### ISSUE THREAD

**Issue by Navid200** [NightscoutFoundation/xDrip#1664]
xDrip version: 2020.11.27

G6 8K

Moto G Power (2020)

It is Andoid 10, not 11.

All xDrip settings are the recommended settings.

### Expected behavior
After the user taps on pair in response to the pair request once, the pair request should never appear again.

### Actual behavior
This is not the frequent pair request.   xDrip has already been updated to November 27, 2020.  
But, occasionally (once every few days), the device unpairs.

### Steps to reproduce the behavior:
I cannot reproduce this issue

![1](https://user-images.githubusercontent.com/51497406/109706634-3078c080-7b67-11eb-9472-7f7c8182725c.jpg)

@nickb24    @jamorham 
I'm so sorry for tagging you guys.  I have never seen this before.  It is on facebook.  I don't understand why this happens.

**Comment by Navid200** [comment]
I have already asked the user if she had an old phone with xDrip or Dexcom app on it.
Waiting for a response.

**Comment by Navid200** [comment]
I hope that it is another device that is competing for attention and causing the unbonding.  I will update as soon as I hear back.
So, I am closing this.    
But, we can still use it to communicate.  So, please let me know if you have any ideas.

**Comment by Navid200** [comment]
The only other device is the Dexcom receiver.

**Comment by tswire** [comment]
Adding to this. 

Samsung Galaxy S21 Ultra
Android 11
Feb 1, 2021 Security patch (most updated version)
Dexcom G6
All xdrip settings correct based on posted recommendations
Running xdrip nightly Feb 11th version (was on most recent with same problem, downgraded to Feb 11th, no change)
Happens daily but randomly.  Cannot find trigger.  Only have Galaxy Watch paired as other device. 
I reinstalled xdrip (over existing), "forgot" transmitter in System status, asked to repair minutes later.  nothing seems to fix.
![xdrip1](https://user-images.githubusercontent.com/30097654/110698274-719e4f80-81bb-11eb-92fb-29aeec6956d7.jpg)
![xdrip2](https://user-images.githubusercontent.com/30097654/110698284-74994000-81bb-11eb-8dbc-72329739819a.jpg)

**Comment by Navid200** [comment]
Would you please try the latest xDrip release, March 8, 2021?

**Comment by tswire** [comment]
will do and report back here

**Comment by tswire** [comment]
Same issue after updating to march nightly.

**Comment by jamorham** [comment]
Can you use the log upload when this has happened fairly recently and include some reference in the log upload that I can use to identify yours. Also what firmware version is reported on the G6 status page?

**Comment by tswire** [comment]
Many disconnects last night. How do I upload the log?

**Comment by Navid200** [comment]
Go to event logs.
At the bottom, tap on "Upload Logs".

**Comment by tswire** [comment]
I uploaded them (twice, first one forgot to include all errors).  Let me know if you got them.
![xdrip3](https://user-images.githubusercontent.com/30097654/110790930-a05e0980-823f-11eb-97e6-8e42eb5b9b0d.jpg)

**Comment by Karumble** [comment]
Hi guys, I found this while looking for the same error. I have a new Galaxy S10+ and an old S7 with the app installed but its off and it keeps ocurring every 5min. (have to accept the bonding manually) Happy to get updates. Hope it was ok to post here.

**Comment by Navid200** [comment]
@Karumble Please update xDrip at least to November 27, 2020.  That will stop the frequent pairing request.  It is not exactly what this issue is about.
You can find more detail about the issue you are experiencing here:
https://www.facebook.com/groups/xDripG5/permalink/4603084736431652

**Comment by tswire** [comment]
Interesting to note, since middle of the night when I was woken up to pair, I have had no pairing requests all day.  I have confirmed that it's not localized to home (other bluetooth devices) since it did it around 7:30pm yesterday while out at an appointment.  I sure hope I don't have another awful sleep due to this!  lol  thanks for looking into it

**Comment by Navid200** [comment]
@tswire You can go to Settings -> Hardware Data Source
and scroll all the way down and tap on disable collection.

Then, use xDrip on your old phone and set it up to collect.  In the morning, you can do the opposite.  To enable collection, you go back to the hardware data source page and select G5/G6 Transmitter.

You should never have both phones collect from the same transmitter at the same time. So, disable one before enabling the other.

There is no way to know how long this is going to take.  So, please be patient.

**Comment by vguttmann** [comment]
I had the same problems on a Samsung A40 with Android 10. I have now upgraded to the March nightly, and have so far not had any problems.

**Comment by rhyspeck92** [comment]
I am experiencing the same issue
Xdrip version 2021.02.17
Samsung s21 ultra (android 11)
G6 8M
All xdrip settings as recommended, the device will ask to pair at least twice a day, majority of the times its early hours of the morning.

**Comment by tswire** [comment]
Sounds like a samsung s21 ultra specific bluetooth stack issue. You have exact same issues as me. I don't think the failure time matters as mine was random but only a couple times per day. For what it's worth, I switched to dexcom build your own app temporarily and solid for 2 days with no disconnects. Not promoting it just saying it works and needed something to work while the devs take a look at this

**Comment by Navid200** [comment]
Solving a device-specific issue is extremely challenging, if not impossible, when the developer doesn't have access to the specific device.
So, please be patient.

**Comment by tswire** [comment]
Absolutely. 100% agree and will be patient

**Comment by rhyspeck92** [comment]
I was orginially build your own dexcom app but wanted to switch back to xdrip as I find it better for infomation, but I was getting frequent signal loss from it like 7/8 times a day from 5 mins to over 30 mins, at first I thought it might of been the new transmitter I am using so I rang dexcom and they couldn't do anything due to me being on android 11.... I may try dexcom app again until issue is resolved

**Comment by jamorham** [comment]
@tswire Sorry the log doesn't contain enough information, can you enable ob1 debugging see here: https://github.com/NightscoutFoundation/xDrip/wiki/Enabling-Debugging-for-OB1-collector and then submit log after it happens again after that is enabled. thanks

**Comment by jamorham** [comment]
Additionally, is this only happening when syncing data from glucose meter is enabled? If so please try disabling bluetooth glucose meter integration feature and rebooting phone and see if the issue still occurs. Thanks

**Comment by Navid200** [comment]
@rhyspeck92 Please use the link that jamorham has provided, and follow the instructions there, to enable OB1 debugging.  When the disconnect happens next time after having enabled OB1 debugging, go to event logs and upload.  Before submitting, add the following to the message to identify yourself:
1664_rhyspeck92

**Comment by rhyspeck92** [comment]
i how now enabled the OB1 debugging via the QR code in the link, i will keep you updated to see if it has helped with the pairing requests, just to add i am not using any glucose meter, just xdrip and G6.
thankyou

**Comment by Navid200** [comment]
@rhyspeck92 Thanks for enabling the debugging.  Please note all that does is to produce more detail logs.  That is not meant to fix the issue.
With more details in the logs, jamorham may have a better chance of figuring out what could possibly be causing the disconnect.

**Comment by rhyspeck92** [comment]
Ahh I see :) well I will keep you posted, when it next asks for a pair
request I will screen shot the event logs and post

**Comment by rhyspeck92** [comment]
No problem will do 👍

**Comment by rhyspeck92** [comment]
As requested event log has been sent when pairing request was made with OB1
debugging enable

**Comment by jamorham** [comment]
@rhyspeck92 thank you for the logs. They apparently show that the phone simply is not using the bonded connection causing the transmitter to complain. This smells like a framework bug, but it may be possible to work around. Can you confirm that you have both the `Minimize Scanning` and `Avoid Scanning` options set to enabled in the advanced G5 settings?  These are the default work-arounds for Android 10+ and I'm concerned from your logs that they may not be enabled. Can you check that and if not see if they make any difference? Thanks.

**Comment by rhyspeck92** [comment]
Thanks for getting back to me I have no enabled both minimize scanning and
avoid scanning to see if this helps

**Comment by jamorham** [comment]
@rhyspeck92 ok try this setting as a test for a work-around: Uncheck the setting `Allow OB1 unbonding` - I would like to know what this does when turned off for you. What I am hoping is that even you might get a pairing request, if you ignore it then following readings may work without intervention. Could you try that and see if it helps at all? This may not work but it is the next thing to experiment with.

**Comment by rhyspeck92** [comment]
Of course I will try these settings as recommended and update you

**Comment by Navid200** [comment]
@rhyspeck92 Any updates?

**Comment by rhyspeck92** [comment]
Seems to be working alot better I've had no pairing requests so far but
I've had a couple of sensor errors and it's kicked back in around 45 mins
later

**Comment by Navid200** [comment]
I think sensor error is something else.  It could be caused by anything that could cause readings that seem unexpected to the transmitter.  It has nothing to do with loss of connectivity.  I'm not saying you should ignore them.  I'm saying we can talk about those somewhere else.

**Comment by Navid200** [comment]
@tswire Have you had a chance to try the settings @jamorham suggested?  Or, are you still on the Dexcom app?

**Comment by tswire** [comment]
I am still on dexcom and just had to switch transmitters so didn't feel comfortable testing right now. Nex sensor I will. Sorry
________________________________

**Comment by Navid200** [comment]
@jamorham 

> Can you confirm that you have both the `Minimize Scanning` and `Avoid Scanning` options set to enabled in the advanced G5 settings? These are the default work-arounds for Android 10+ 

  
When you say default work-arounds for Android 10+, does it mean if someone installs xDrip on Android 11 and selects G5/G6, those two settings will automatically be set?

Are those two settings that anyone on Android 11 should set?

**Comment by jamorham** [comment]
@Navid200 yes those settings should automatically be set. If that isn't working then I need to review that code.

**Comment by Navid200** [comment]
@jamorham Thanks

And should those also be set for Android 10?

Sorry, I am not sure Android 10+ means 
a: only above 10 
or 
b: 10 and above.

**Comment by gfginter** [comment]
I was having major issues with this since upgrading to my s21 Ultra. When it was asking to reconnect it was turning on my screen so my battery was draining like crazy as well. Minimize Scanning and Avoid Scanning options were set to disabled by default so after seeing this thread I enabled them this morning. Will report back after a day or two on my experience and can provide logs if need be.

**Comment by gfginter** [comment]
Well I can report back that there is no difference in behavior I am still getting bond state unpaired.

**Comment by Navid200** [comment]
@gfginter Thanks for reporting.
Please enable detail logs:  https://github.com/NightscoutFoundation/xDrip/wiki/Enabling-Debugging-for-OB1-collector

Would you please now disable "Allow OB1 unbonding" while still leaving minimize scanning and avoid scanning settings enabled?

**Comment by rhyspeck92** [comment]
Since I have enabled this I haven't had any pairing requests since

**Comment by Navid200** [comment]
@rhyspeck92 Please confirm you mean since you _disabled_ "Allow OB1 unbonding".
And thanks so much for the update.

**Comment by rhyspeck92** [comment]
I have disabled "Allow OB1 unbonding" and have "minimize scanning" and
"allow scanning" enabled, I have been running for around a week now without
a pairing request.

**Comment by gfginter** [comment]
> @gfginter Thanks for reporting.
> Please enable detail logs: https://github.com/NightscoutFoundation/xDrip/wiki/Enabling-Debugging-for-OB1-collector
> 
> Would you please now disable "Allow OB1 unbonding" while still leaving minimize scanning and avoid scanning settings enabled?

I did disable AllowOB1 unbonding and it still asked to pair. I am doing it again. Should I also disable "Allow OB1 initiate bonding" ???

I have enabled the detailed logs as requested.

**Comment by rhyspeck92** [comment]
Yes Allow OB1 initiate bonding, I have this enabled

**Comment by Navid200** [comment]
@gfginter No, you should not.  
You should exactly follow the advice of jamorham, the developer, in this thread, and only that.

What version of xDrip are you using.  Please check on your classic status page to find out.

**Comment by rhyspeck92** [comment]
It says to have it enabled in the docs, I was never told to turn it off

**Comment by gfginter** [comment]
I will only follow jamorham's advice, thank you. I am on the latest nightly 17cbcf0-2021.03.08

**Comment by Navid200** [comment]
@rhyspeck92 I fear multiple conversations are going on.  That's why some of us quote people to make it clear whom we are talking to.

I understand that you are happy because after following jamorham's work-around approach, you have not had any more pair requests.   That is great.  If a new release comes out to address the work-around, I will post here to inform everyone.

In the meantime, please don't change any of your settings and report if the problem occurs again.
Thanks

**Comment by rhyspeck92** [comment]
No problem, thanks again for all the help and support, if any problems
arise I will update you 🙏

**Comment by gfginter** [comment]
I successfully made it through last night without disconnecting. Of course I will continue to monitor throughout the day and let you know if I begin to experience issues again. Thanks for all you do.

**Comment by vguttmann** [comment]
For anyone reading this in the future: An update to Android 11 seems to be safe. I updated my Samsung A40 this night, and so far, there were no problems with the March 26th nightly build.

**Comment by Navid200** [comment]
@gfginter and @rhyspeck92, any updates?

**Comment by rhyspeck92** [comment]
Mine seems to have been working fine :) occasionally but not often I don't
get a reading for like 7/8 mins instead of the normal 5 mins but apart from
that it's been perfect

**Comment by gfginter** [comment]
@Navid200 I have had no issues either. Have been upgrading to the nightlies with no problem.

**Comment by Roozeboom007** [comment]
xDrip version: 2021.05.10

G6 8H

OnePLus 7T

It is Andoid 11.

All xDrip settings are the recommended settings.

Twice a day Signal loss, which is not automatically resolved. Restarting the phone does help. With xDrip version 2020.07.25 this problem was not present
![Screenshot_20210516-194952](https://user-images.githubusercontent.com/58114624/118409753-4a1ca500-b68c-11eb-9d18-20d36b33d6ce.jpg)
![Screenshot_20210516-194959](https://user-images.githubusercontent.com/58114624/118409754-4b4dd200-b68c-11eb-9d17-549e2028e93c.jpg)
![Screenshot_20210516-195032](https://user-images.githubusercontent.com/58114624/118409755-4b4dd200-b68c-11eb-8287-9f288b64dd8c.jpg)

**Comment by charliegenge** [comment]
Hi @jamorham ,

Xdrip is whitelisted with not battery optimisation (as far as I can tell) and it has no restricted permissions.
![Screenshot_2021-08-28-10-47-08-414_com.google.android.permissioncontroller.jpg](https://user-images.githubusercontent.com/9430283/131214012-e3a3d8ed-c87f-4be2-9d82-fb6d1eda1c8b.jpg)
![Screenshot_2021-08-28-10-46-26-293_com.android.settings.jpg](https://user-images.githubusercontent.com/9430283/131214015-c04d1c7c-b5da-4da5-85df-fe12ec170bda.jpg)

Thanks,

Charlie

**Comment by supercoiler** [comment]
Hey, also ran into this problem on my Pixel 6 Pro using the same exact settings from my S21+. I then disabled "Allow OB1 unbonding" and had the other two settings already. Also unchecked the Samsung buggy workaround. It no longer asks to re-pair but still asks to bond when it is. Sometimes it goes as long as 45 minutes and the only way to get it going again is to unpair the sensor. Then it connects normally. But it never seems to work longer than 2 hours without messing up again. May temporarily go back to my s21+ until this problem is resolved. Or until that upgrades to Android 12 and if I have the problem again. I really love Pixel phones, only downfall is we get updates first and become the guinea pigs...

**Comment by supercoiler** [comment]
Really? Even if you're not using a Samsung?

**Comment by Navid200** [comment]
> Really? Even if you're not using a Samsung?

xDrip only uses the Samsung work-around if it is needed.  But, if you disable the setting, xDrip will not be allowed to use it even if it needs to.

**Comment by icnich** [comment]
Has this original issue been remedied?

**Comment by Navid200** [comment]
@icnich I ask everyone to go through these steps:
https://navid200.github.io/xDrip/docs/Intermittent.html
There are a few devices that need to disable "Allow OB1 unbonding".  For example, Samsung S21.

If you are asking if xDrip works by default for all devices with the default settings, the answer is no.

**Comment by icnich** [comment]
@Navid200 thank you so much for the super quick reply (and just, you know, your contributions in general)! I'll run through these

**Comment by JoernKO** [comment]
Hi,
I have had a new smartphone for a few days, a Samsung S21 Ultra with Android 11. Unfortunately, I have constant disconnections between the Dexcom G6 sensor and XDrip. A connection is only established after restarting the smartphone and only lasts about an hour. After that, the connection is no longer re-established. I have granted the app all the required permissions. It worked without any problems with the previous Samsung S10 smartphone. I am happy to help with troubleshooting. 

I have exactly the same behavoir and the Message "Device is marked as bonded but we are being asked to bond so attempting to unbond first"

**As mentioned in the thread, I have now disabled the setting "Allow OB1 unbonding".** Was this really a solution for the problem. 

It looks like that this setting prevents the connection from beeing disconnected.

22:09 "Device is marked as bonded but we are being asked to bond so attempting to unbond first"
22:09 "Would have tried to unpair but preference settings prevents it. (unbound)

Any help with this problem?

Regards
Joern

**Comment by Navid200** [comment]
@JoernKO Yes, for your phone, that is the solution.
Make sure you go over every setting here:  https://navid200.github.io/xDrip/docs/G6-Recommended-Settings.html

Then, for your phone, disable "Allow OB1 unbonding" only from those recommended settings.  

Please open a discussions and I can see why you are still having problems if that doesn't help:  https://github.com/NightscoutFoundation/xDrip/discussions

**Comment by Navid200** [comment]
Would everyone please try the latest Nightly and see if enabling "Allow OB1 unbonding" still causes problems?

https://github.com/NightscoutFoundation/xDrip/releases/tag/2022.06.09

**Comment by bsw-del** [comment]
> Would everyone please try the latest Nightly and see if enabling "Allow OB1 unbonding" still causes problems?
> 
> https://github.com/NightscoutFoundation/xDrip/releases/tag/2022.06.09

Trying it out now.

**Comment by charliegenge** [comment]
This seems to have worked for me, thanks so much for your help

**Comment by Navid200** [comment]
The G6 collector has been tweaked multiple times since this was opened.
This problem must have been resolved already.

Please have a look here for the current suggested approach:
https://navid200.github.io/xDrip/docs/Intermittent.html
