### ISSUE TITLE
Xdrip+ ios

### ISSUE THREAD

**Issue by idocalm** [NightscoutFoundation/xDrip#1665]
Hi, I wanted to know the position in the dec process of the ios version and suggest having a xdrip+ version for ios phones. I heard of Spike but its ful of lags and bugs.
Are you planning on this option?

**Comment by Navid200** [comment]
Please don't open an issue just to ask a question.
You can post your questions, about xDrip, here:
https://gitter.im/jamorham/xDrip-plus
Or here:
https://www.facebook.com/groups/xDripG5
Thanks
