### ISSUE TITLE
Failure to acquire data over night 

### ISSUE THREAD

**Issue by walkerpayne** [NightscoutFoundation/xDrip#1669]
### Subject of the issue
Hello all, I am running into a repeating issue where the signal is missed every night when I'm sleeping. I have read that this is potentially a bluetooth issue, where the phone is somehow altering/reducing bluetooth capabilities overnight to reduce battery drain, which causes signal loss. It is unclear to me whether this is an xDrip bug OR an Android bug, which is why I am posting it here.

### Your environment
Dexcom G6 8N---- transmitter
Oneplus 7T running Android 10 (BN 100.13.HD63CB)
Xdrip e14bae1-2020.07.13

Xdrip bluetooth settings:
Turn Bluetooth on ENABLED
Bluetooth Watchdog ENABLED
G5 bluetooth watchdog ENABLED
Close GATT on BLE disconnect ENABLED
Use background scans ENABLED
Bluetooth Wakelocks ENABLED
Android settings:
xDrip app battery optimization setting is "Don't optimize". I saw reference to some other battery optimization settings
Under Battery optimization > advanced optimization, the xDrip app is NOT listed as restricted via "adaptive battery".

### Expected behavior
Readings should continue as normal from 12am to 7am (example times). 

### Actual behavior
Upon waking up (7-730AM), xDrip shows "signal missed, X minutes ago" with no readings for the past X hours overnight. Upon reconnecting with the Dexcom transmitter, the buffer fills in an hour or two of readings (back to, for example, 5AM), but data from 12AM to 5AM is missing). Readings are normal and accurate throughout the day.

**Comment by Navid200** [comment]
I responded to your post in the Gitter room.
Do you have a feacebook account.
All the settings are described there:
https://www.facebook.com/groups/xDripG5/permalink/4838757582864365

Please only use the issues platform to report a bug after you use the support channels to confirm that you are using xDrip properly.
Please respond to my suggestions in the Gitter room.
If the two of us conclude that this is a bug, we can reopen this issue.
