### ISSUE TITLE
[Feature Request] User-changeable Insulin profiles without a custom version

### ISSUE THREAD

**Issue by vguttmann** [NightscoutFoundation/xDrip#1670]
### If you need support for xDrip, PLEASE DO NOT FILE A TICKET HERE
For support, please post a question to the xDripG5 group at Facebook (https://www.facebook.com/groups/xDripG5) or visit the Gitter room at https://gitter.im/jamorham/xDrip-plus.
Please also search the existing issues for similar ideas before opening a new feature request.

### Is your feature request related to a problem? Please describe.
The Insulin profile for Levemir does not match my onset and peak profile

### Describe the solution you'd like
A way to tweak the onset, peak and duration values of various insulin types. Possibly in the settings app, or potentially through modifying the insulin profiles file. The easiest solution I can think of is to make a user-accessible xDrip directory which contains the insulin profiles file

### Describe alternatives you've considered
Forking the repo and making a customised build

**Comment by Navid200** [comment]
@vguttmann Would you please have a look at the following?
https://github.com/NightscoutFoundation/xDrip/issues/718
If you can add your suggestion to that existing open feature request, please do and close this issue.

Otherwise, please explain what makes this request completely different.

**Comment by Navid200** [comment]
Duplicate:  https://github.com/NightscoutFoundation/xDrip/issues/1259

Closing the issue because there is another already.  You can add your comments to the existing issue.
Thanks
