### ISSUE TITLE
Signal lost Dexcom Reciver 

### ISSUE THREAD

**Issue by JayJay265** [NightscoutFoundation/xDrip#1676]
With the version from May 8th, the Dexcom receiving device only shows signal loss.

**Comment by Navid200** [comment]
@JayJay265 Please post in the facebook group or the Gitter room, describe the problem in detail.  Include the phone brand and model, the CGM and transmitter, and include the year when you specify the xDrip version.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

Please don't open an issue here as a first step.
If you are sure that there is a bug and you want to report it, please follow the instructions provided to you when you start opening the issue.

Thanks for helping us supporting you.
