### ISSUE TITLE
Support for "Libre Pro" Sensors

### ISSUE THREAD

**Issue by anirudhreddy28** [NightscoutFoundation/xDrip#1677]
### Is your feature request related to a problem? Please describe.
We notice that Xdrip currently does not support Libre pro sensors. We in India primarily use Libre Pro as our CGM and we are struck with using the Native apps like Tomato (for Miao Miao) and Link Blucon (Ambrosia Blucon). Most of them are happy with the Native apps but with the recent server issues Miao Miao had, we are interested to see a possibility of using these DIY apps. There are hundreds (possibly thousands) who could benefit with this addition.

### Describe the solution you'd like
We know that Xdrip already supports Libre 1, Libre US 14 day, Libre US 10 day etc.. We would like the similar support for Libre Pro as well

### Describe alternatives you've considered
At this moment only alternatives we have have are the native apps and they have been unreliable in many times and also providing us limited functionality for those who are interested in DIY Closed loop technologies. 

### Additional context
I am on DIY Closed loop using Libre Pro + Tomato + Nightscout. There are few others using exactly the same setup. But with this setup, we can use it only when we are connected to internet. If we could get the Xdrip support Libre Pro sensors, it would be helpful to do closed loop in offline mode as well.

**Comment by Navid200** [comment]
Would you please post in the existing thread?
https://github.com/NightscoutFoundation/xDrip/issues/1329
