### ISSUE TITLE
Performance issues "xDrip+ isn't responding. Do you want to close it?"

### ISSUE THREAD

**Issue by renegadeandy** [NightscoutFoundation/xDrip#1681]
### Subject of the issue
Many times each day, when I open xDrip+, typically by pressing on a widget on my phone's home screen, the app opens, instantly, and things are great.

Also many times each day when I open xDrip+, by pressing on a widget on my phone's home screen, the screen goes black, and I get an android OS warning saying "xDrip+ isn't responding. Do you want to close it? 

Version :39e880d-2021.02.17
Code: 2102171920
Data source: tomato, libre 1 via miao mao 1
Phone: Honor 9
Watch: xDrip+ watch face on Fossil explorist gen 4
Uploader configured to NightScout
My Honor 9 phone stands with 2gb memory free at nearly all times, and all other apps including AndroidAPS open instantly, no problems.

### Expected behavior
The app opens immediately without this hang every time.

### Actual behavior
When the application screen goes black, or hangs, it can hang there for around 20 seconds before the popup from android disappears, or the 'wait' ends.

I am happy to assist here, I would like to understand, what is xDrip+ doing when it is not responding during these times, and how can we fix it.

### Screenshots
![Screenshot_20210317_125549_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/831013/112017227-53bedc00-8b25-11eb-9cb1-a7fb90b731a0.jpg)

**Comment by Navid200** [comment]
Please add your comments to the existing issue and we can talk about them there.
https://github.com/NightscoutFoundation/xDrip/issues/1328
