### ISSUE TITLE
Support for Bubble Mini

### ISSUE THREAD

**Issue by parapenT1sta** [NightscoutFoundation/xDrip#1682]
As far I know Bubble Mini uses the same protocol of Bubble but it seems the name of Bubble Mini needs to be added to the list.

**Comment by tolot27** [comment]
Can you create a PR for it or ask the @bubbledevteam ?

**Comment by parapenT1sta** [comment]
@tolot27 I asked them, since was only yesterday that I was able to check the Bubble Mini.

Btw, do you know when this will be merged? https://github.com/NightscoutFoundation/xDrip/pull/1662

**Comment by tolot27** [comment]
> Btw, do you know when this will be merged? #1662

No, I don't. The PR is ready for merging, now. Only jamorham can merge.

**Comment by parapenT1sta** [comment]
@tolot27 I left a message in Gitter group. Hopefully he can see it.
