### ISSUE TITLE
Hello,

could there be an option to add a insulin with flexible values. For example: I use Tresibia as basal but it works 2 h less than on other people. 

### ISSUE THREAD

**Issue by BarryVerdammt** [NightscoutFoundation/xDrip#1683]
### If you need support for xDrip, PLEASE DO NOT FILE A TICKET HERE
For support, please post a question to the xDripG5 group at Facebook (https://www.facebook.com/groups/xDripG5) or visit the Gitter room at https://gitter.im/jamorham/xDrip-plus.
Please also search the existing issues for similar ideas before opening a new feature request.

### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.

**Comment by Navid200** [comment]
Would you please post your comments in the existing (linked) issue?
https://github.com/NightscoutFoundation/xDrip/issues/1259

Please let me know if you think this, for some reason, is different.

Thanks

**Comment by BarryVerdammt** [comment]
Sorry, i didn't found it.

Navid200 ***@***.***> schrieb am Fr., 26. März 2021, 04:08:

**Comment by Navid200** [comment]
> Sorry, i didn't found it. 

Here:  https://github.com/NightscoutFoundation/xDrip/issues/1259

**Comment by BarryVerdammt** [comment]
I didn't found it before you sent me the mail before. I'm new to GitHub. I
got it now. Again: nice work. I appreciate.

Navid200 ***@***.***> schrieb am Fr., 26. März 2021, 13:28:
