### ISSUE TITLE
Tasker support, add medtronic cgm values directly from tasker. 

### ISSUE THREAD

**Issue by raferg** [NightscoutFoundation/xDrip#1684]
So with the help of one plugin to Tasker it is possible to read cgm values from the alerts. How complex is it to add in a plugin for adding these values directly to xdrip (and then upload to mongodb/heroku etc)?

**Comment by raferg** [comment]
I've got https://play.google.com/store/apps/details?id=com.balda.notificationlistener installed in Tasker and am referencing the %nltitle variable to get the value out - how to publish this to nightscout (or xdrip) is the part that I think is quite achievable.

**Comment by Navid200** [comment]
Whether something is easy to implement or not is not on its own going to determine if it is going to be implemented or not.

Whether it is necessary, how easy it is to test, and how disruptive it may be to existing features are more important.

There is an existing open issue you can add your comments and suggestions to.
https://github.com/NightscoutFoundation/xDrip/issues/131

If this needs to be a separate open issue, please explain why and we can reopen it.
