### ISSUE TITLE
Bluetooth, Android 10, disconnects when not on charge

### ISSUE THREAD

**Issue by Navid200** [NightscoutFoundation/xDrip#1687]
### If you need support for xDrip, PLEASE DO NOT FILE A TICKET HERE
We went over this in the facebook group and tried all the recommendations.

### Your environment
xDrip: March 8, 2021
G6 8P
Oppo Reno 2, Android 10

### Expected behavior
Proper connectivity on or off charger

### Actual behavior
Since update to Android 10, there are frequent disconnects.  When the phone is on charge, there is no disconnect.

Android settings have been adjusted not to optimize the battery use of xDrip and allow xDrip to run in the background.

After installing Dexcom and disabling xDrip, the Dexcom app has no issue.

**Comment by tolot27** [comment]
Is it Android 10 or device dependent? Hence, is it limited to Oppo Reno 2 or not?
Is the Android 10 a custom or stock ROM?

**Comment by Florinho55** [comment]
Its the OPPO stock ROM...Color OS 7.1

**Comment by Navid200** [comment]
Every time I have seen this behavior, after an upgrade to Android 10, it has been resolved after the battery optimization was disabled and after the xDrip settings were corrected to match the recommended Android 10 xDrip settings.

This is the only case I have seen where the problem has persisted.

I forgot to add to the first post, which I will add now, that the Dexcom app has no issue on the same phone.

**Comment by tolot27** [comment]
> Its the OPPO stock ROM...Color OS 7.1

Hence, it could also be a problem with the vendor specific adaptions to Android.

I don't believe that his is a general issue with Android 10.

Are there any uploader/follower services configured?

**Comment by Florinho55** [comment]
Yes, Navid and me thought the same. OPPO has a very strict battery saving management, so probably thats a point. Yes, I use Nightscout. But the Upload ended after Update to Android 10, too. At least I guess it is the Upload - the page only says "client loading" forever and ever

**Comment by tolot27** [comment]
@Florinho55 Can you disable Nightscout and test if BT disconnects still appear? Likely, they will appear because xDrip is now "blacklisted" as consuming too much energy.

**Comment by tolot27** [comment]
It is also likely that you can see a warning in the logs that NightscoutService does not have proper foreground permissions. I've tried fixing this but it's not easy because every xDrip service requests foreground bluetooth permissions and not foreground data transfer permissions.

**Comment by Navid200** [comment]
@Florinho55 When you have time to test the suggestions, please uninstall the Dexcom app first.
Then, go back to xDrip and as suggested, disable Nightscout under Settings -> Clod Upload -> Nightscout Sync.
Then, see if the occasional disconnects stop.
If it does, the problem then becomes how to fix Nightscout upload.

I am sorry I suggested that we focus on the connectivity issue and forget the Nightscout issue.  It turns out they were directly related.

**Comment by Florinho55** [comment]
Like just disable the API-Upload? There is no specific Nightscout Sync at xdrip, but API Upload

**Comment by tolot27** [comment]
As Navid200 posted. I've updated his comment.

**Comment by Navid200** [comment]
@Florinho55   This is what the page looks like.
![Screenshot_20210329-134232](https://user-images.githubusercontent.com/51497406/112877698-13b3a800-9095-11eb-88ec-850557ed1245.png)

**Comment by Florinho55** [comment]
Interesting...its a bit different in the German version...
![Screenshot_2021-03-29-19-49-01-30_2dd2c1bcb8f659cd696bcba2072f751b](https://user-images.githubusercontent.com/81444904/112878179-e7fde580-90c7-11eb-84ad-9f3cd77d3184.jpg)

**Comment by Navid200** [comment]
Looks like it is disabled already.
Do you still get those xDrip logs about Nightscout?

**Comment by tolot27** [comment]
> Interesting...its a bit different in the German version...

No, except the translation. You can swith to English (Settings -> xDrip+ Display Settings -> Force ... Text and Choose a specific language) for screenshots or to compare settings.

**Comment by Florinho55** [comment]
Since I installed xdrip again just like 20 Minutes ago it hasnt started collecting yet. The last time I re-installed it it needed some time to get the session again...

**Comment by Florinho55** [comment]
Too happy too early...lost connections again :(
![Screenshot_2021-03-29-20-51-54-59_2dd2c1bcb8f659cd696bcba2072f751b](https://user-images.githubusercontent.com/81444904/112885137-aaea2100-90d0-11eb-8b8e-8a00d63656b9.jpg)

**Comment by Navid200** [comment]
And the logs.  The latest page should be good to start with.

**Comment by Florinho55** [comment]
![Uploading Screenshot_2021-03-29-21-08-09-94_2dd2c1bcb8f659cd696bcba2072f751b.jpg…]()

**Comment by Florinho55** [comment]
Update: Android asked to get  xdripon Whitelist. I confirmed. And after like 5 minutes its now collecting again.

![Screenshot_2021-03-29-21-17-56-91_2dd2c1bcb8f659cd696bcba2072f751b](https://user-images.githubusercontent.com/81444904/112888115-403ae480-90d4-11eb-9a1f-818edfe3e0d5.jpg)

**Comment by Florinho55** [comment]
And another Update:
Today xdrip is connecting itself and sometimes it works (without me pairing or anything else). But after like two or three collections it stops again

**Comment by Navid200** [comment]
And it works perfectly if you put the phone on charge?

**Comment by Florinho55** [comment]
Yes, without a problem

**Comment by adanvdo** [comment]
I have a device with Android 10. A Moto E7. I have Battery Optimization disabled but run into frequent connection problems when the battery is below 15% I am not sure if there is another power profile on android where you can control these types of things.

I also have the Allow OB1 unbonding unchecked. I have no problems with connectivity unless the transmitter is old or the battery is under 15% like said

**Comment by tolot27** [comment]
@Navid200 Is this problem not related to Bluetooth?

**Comment by Navid200** [comment]
@tolot27 This was a puzzle for me when it was posted in the facebook group.
I opened this issue to bring it to the attention of the developers.
Now, it seems to be better to be moved to the discussions.

**Comment by Navid200** [comment]
I am sorry that we were not able to solve this.
But, the symptoms suggest that Android interferes with xDrip, running in the background, in order to preserve battery.
We can always reopen this if it helps.  But, I am closing it now and ask that you open a thread in the discussions if the problem persists:
https://github.com/Navid200/xDrip/discussions
