### ISSUE TITLE
MiaoMiao 1 with Libre 2

### ISSUE THREAD

**Issue by renegadeandy** [NightscoutFoundation/xDrip#1689]
I use a MiaoMiao v1 with Libre on Xdrip+ for many years - its' great.

Now i got a Libre 2, but the xdrip+ just reports checksum errors. What can I do to make it work?

Tomato firmware is 0036 if that helps

Latest version of xDrip+ beta channel

**Comment by DIajo** [comment]
I don't thnik that MiaoMiao v1 works with Libre 2. You need MiaoMiao v2, Bubble or you can just use the patched LL-App (in this case you don't need smart reader anymore).

**Comment by renegadeandy** [comment]
This page : https://miaomiao.cool/products/miaomiao-smart-reader states that MiaoMiao v1 is compatible with libre1 and libre2 using xDrip+.

**Comment by Navid200** [comment]
Would you please not open an issue to ask a question?
That was explained when you opened this issue, wasn't it?

Would you please do some research first using facebook or the Gitter room before opening an issue here?
We don't have the required manpower to do all the work for you.  So, we are asking you, as a member of the community, to help us.  Does that not make sense?

If everyone who has a question, opens an issue here, there will be no way to coordinate and address them all.

We can always reopen this and turn it into a valid issue after you try the suggestions given to you using the support channels.
