### ISSUE TITLE
Range values missing in statistics in german translation

### ISSUE THREAD

**Issue by cr582** [NightscoutFoundation/xDrip#1694]
Version: d1ae1cd-2021.04.06

TIR is missing on statistics page as soon as I'm using the system language (in this case German). As soon as I set "force english text" it is fixed. See screenshot

![Screenshot_20210407_215405_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/62606176/113928173-b505d100-97ee-11eb-92bd-d40b2c19458c.jpg)

![Screenshot_20210407_215333_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/62606176/113928498-31001900-97ef-11eb-96b6-8b19b8f5e83f.jpg)

**Comment by tolot27** [comment]
This is a duplicate of #1641 and will be fixed with #1698.
