### ISSUE TITLE
Implementation of Oneplus Smartwatch

### ISSUE THREAD

**Issue by 1337Reis** [NightscoutFoundation/xDrip#1695]
Hi devs,

is the Oneplus Watch going to be implemented as wearable device into xdrip?
I'd love to see it as an option.
https://www.oneplus.com/de/oneplus-watch

Thank you for your great work and support

Best regards
1337Reis

**Comment by Navid200** [comment]
You may get more responses if you post this in the support channels:
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

**Comment by tolot27** [comment]
OnePlus watches using RTOS rather than Wear OS. Hence, we cannot support it because of lack of developers and watches and because there is no SDK available for OnePlus.
