### ISSUE TITLE
Dex Share Follower Complication Null

### ISSUE THREAD

**Issue by CmSCMU** [NightscoutFoundation/xDrip#1701]
Hello, I'm running 2021.03.08 XDrip+, on a Samsung Galaxy Note 20 Ultra, and using a Ticwatch E W300 (Wear OS 2.26). I use the official Dexcom app to collect data and the share follower feature to get it into Xdrip. I have tried to see if this issue exists already, but it seems all threads are a couple years old.

I can get the Xdrip watchface to display BG readings, but when I try to send readings to the Skymaster watchface (as was recommended in the smartwatch guide) all I get is null (see picture).

I think there might be an issue with complications and Dex Share Followers, but I can't tell if it's been resolved or not (and if so, how).

Is it possible to be a Dex Share Follower and send the data via complications? 
![20210420_082438](https://user-images.githubusercontent.com/12651921/115396360-e305f080-a1b2-11eb-9dba-3d64af6fa473.jpg)

**Comment by Navid200** [comment]
@CmSCMU Have you asked this question in the facebook group or the Gitter room as you were asked to when opening this issue?
https://github.com/NightscoutFoundation/xDrip/blob/master/.github/ISSUE_TEMPLATE/bug-report.md
If yes, please provide links.
If not, please close this issue.

**Comment by CmSCMU** [comment]
I have: https://www.facebook.com/groups/xDripG5/permalink/5303342963072489

Arguably, it hasn't been long since posting, but I've scoured the Internet for a while now. I got a responses from one person in the FB thread, but it seems very few people use Dex Share Follower as the source. Most people are using their phones or their watches as the collector. I can find some issues from 2018 about followers and complications, but nothing as of late. 

In the SmartWatch guide by GregoryBel, the only null issue troubleshooting discussed is the calibration fix, which isn't possible as a follower (I get the "Got impossible slope calibration" error).

**Comment by SBee76** [comment]
I've been researching this also for a wear os watch, and apparently it is not possible when xdrip is a follower, much to my frustration

**Comment by Navid200** [comment]
@CmSCMU Is this not related this this issue?  
https://github.com/NightscoutFoundation/xDrip/issues/303

If yes, would you please post in that issue and close this one?

**Comment by CmSCMU** [comment]
> @CmSCMU Is this not related this this issue?
> #303
> 
> If yes, would you please post in that issue and close this one?

How do I close this one?

**Comment by Navid200** [comment]
@CmSCMU You should be able to tap on close at the bottom.
But now that I have your consent, I close it for you.  Thanks
