### ISSUE TITLE
Screen Rotation issue

### ISSUE THREAD

**Issue by farcusnz** [NightscoutFoundation/xDrip#1711]
In Xdrip (versions 06/04/21, 13/04/21 & 24/04/21) on android 10 (Xiaomi Mi A2 - android one)
When rotating the screen to landscape, then returning to portrait, Xdrip does not reconfigure to portrait correctly.
Have been able to reproduce this on a friends Pixel 3 - also on android 10

![screenrotation1](https://user-images.githubusercontent.com/29653298/116798851-b6a18b00-ab47-11eb-92f7-fc13fb04810b.png)

**Comment by Navid200** [comment]
@farcusnz Would you please post in the thread linked on the next line?
https://github.com/NightscoutFoundation/xDrip/issues/1269
We can talk about it there.
