### ISSUE TITLE
Amazfit GTS 2e & xDrip integration

### ISSUE THREAD

**Issue by shiruba69** [NightscoutFoundation/xDrip#1712]
Help me please.
Requires xDrip and Amazfit GTS 2e integration.

I am a user, not a programmer.

Ready to help with testing, I have this watch.

I think it's real if there is integration in the Mi Band and even found options for integrating with the GTR, but they are round, and the GTS is square. They have different dials.

**Comment by tolot27** [comment]
Please ask in the support forums as shown before you created this issue: https://github.com/NightscoutFoundation/xDrip/issues/new/choose.
