### ISSUE TITLE
"Firmware version unknown! Please report" - What you should do when you see this

### ISSUE THREAD

**Issue by Navid200** [NightscoutFoundation/xDrip#1713]
This is a message that a Dexcom user sees on the system status page if their firmware is new and unknown.

![1](https://user-images.githubusercontent.com/51497406/116949588-b4772380-ac50-11eb-88ad-de25b5c679ef.png)

The problem is that even after it is reported, xDrip still shows the same message, in red.  It looks like it requires an action from the user. 

### Describe the solution you'd like
Can we add a url so that the users can see the detail of what they need to do?
https://github.com/Navid200/xDrip/wiki/Report-Firmware

**Comment by emp-00** [comment]
Much more simple suggestion from my side: 
Just change the message to "Please report and upgrade to latest nightly when available"

**Comment by Navid200** [comment]
What the user should do is explained [here](https://github.com/Navid200/xDrip/wiki/Report-Firmware).

**Comment by Navid200** [comment]
Let's see how the latest will handle this.
