### ISSUE TITLE
G6 Firmware version 2.27.2.103 unknown 

### ISSUE THREAD

**Issue by tkalfaoglu** [NightscoutFoundation/xDrip#1719]
Hi -- xdrip+ wanted me to report this.. so here goes.. 
The system status says 
Firmware version:   2.27.2.103 Unknown! please report.

The transmitter code starts with 8S if that helps.
Many thanks for great software..
-t

**Comment by tolot27** [comment]
Related to #1713

**Comment by Navid200** [comment]
@tkalfaoglu If you update to any xDrip Nightly release of March 30 or after, that message will be cleared.
  
I close the issue now.  Thanks for reporting.
