### ISSUE TITLE
different size action bar and no "menu" button in the "settings" submenu...

### ISSUE THREAD

**Issue by mukich** [NightscoutFoundation/xDrip#1721]
As a perfectionist, I tried to find how to change the action bar in the "Settings" and "Find notes" submenus. In addition, there is no "Menu" button in the "Settings" submenu. Maybe someone knows the Java programming language better, tell me how to change it. As I understand it, these submenus use a custom action bar. Tell me how to install a standard action bar?
![rte](https://user-images.githubusercontent.com/38015067/117815141-d5053600-b26d-11eb-9d5c-c063f85a3cad.jpg)

**Comment by tolot27** [comment]
I suspect, this issue does not even has to do with xDrip and its usage itself. It looks like it is an app programming related question.
