### ISSUE TITLE
Xdrip ubnormal graph

### ISSUE THREAD

**Issue by eliasmp245** [NightscoutFoundation/xDrip#1725]
Why is this ubnormal graph??is the libre sensor causes this or miao miao?

Thanks in advance
![Screenshot_20210515-124508_xDrip+](https://user-images.githubusercontent.com/80071305/118356233-dc358800-b57c-11eb-8a0d-05148e2cad11.jpg)

**Comment by Navid200** [comment]
While you were opening this issue, you were given instructions as to what you should use for asking questions.  I repeat it here:
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
