### ISSUE TITLE
 xDrip occupies too much storage space on the phone

### ISSUE THREAD

**Issue by NickAlbanese85** [NightscoutFoundation/xDrip#1730]
Xdrip version: 17cbcfo-2021.03.08
code:210308´1944
downgradable to: 1603091400

phone: Samsung j7 2016

Android 8.1.0

from yesterday (05-18-2021) to today (05-19-2021) the spaces change from 791 megas to 836 megas only in one day

save database daily is not enable

**Comment by Navid200** [comment]
@NickAlbanese85 Would you please edit your post as explained below so that it can be better managed?

1- Please change the title to:  xDrip occupies too much storage space on the phone

2- Add xDrip version.

3- Add phone brand and model.

4- State the rate at which the size is increasing.  If you don't have this detail right now, you can wait 48 hours to find out how much it has grown and add that to your post.

5- State that you don't have "Save Database Daily" is not enabled on Settings -> Less common settings

**Comment by NickAlbanese85** [comment]
Xdrip version: 17cbcfo-2021.03.08
code:210308´1944
downgradable to: 1603091400

phone: Samsung j7 2016

from yesterday (05-18-2021) to today (05-19-2021) the spaces change from 791 megas to 836 megas only in one day

save database daily is not enable

**Comment by NickAlbanese85** [comment]
![xdrip](https://user-images.githubusercontent.com/53303294/118825496-1ced1400-b891-11eb-8256-2e52826c1eef.jpeg)

**Comment by tolot27** [comment]
Do you have verbose logging enabled (less common settings - extra logging settings - extra tags for logging)?

**Comment by NickAlbanese85** [comment]
![xdrip3](https://user-images.githubusercontent.com/53303294/118838554-2760db00-b89c-11eb-909b-769440b56e62.jpeg)

**Comment by tolot27** [comment]
What about the verbose logging?

**Comment by tolot27** [comment]
You could also do a backup of the database and look at its uncompressed size.

**Comment by NickAlbanese85** [comment]
yes, right now i will make that backup and maybe unistall and re-install if there is no another solution posible

**Comment by NickAlbanese85** [comment]
768 megas uncompressed size!

**Comment by tolot27** [comment]
At what is the largest table inside the SQlite database? I assume, `UserErrors`.

You still did not report whether you have extra logging enabled or not. I assume that this is the main reason of having such a large xDrip database.

**Comment by NickAlbanese85** [comment]
Here is a resume , make with sqlite_analyser 


* Page counts for all tables with their indices ***********

DESERTSYNC........................................ 144634      73.5%
USERERRORS........................................ 37184       18.9%
LIBREBLOCK........................................ 8337         4.2%
BGREADINGS........................................ 5633         2.9%
UPLOADERQUEUE..................................... 610          0.31%
TREATMENTS........................................ 55           0.028%
CALIBRATION....................................... 38           0.019%
REMINDER.......................................... 9            0.005%

**Comment by NickAlbanese85** [comment]
save database daily is not enable

**Comment by NickAlbanese85** [comment]
> ¿Tiene habilitado el registro detallado (configuraciones menos comunes, configuraciones de registro adicionales, etiquetas adicionales para el registro)?
> 
> ¿Qué "Retención de glucosa" ha establecido? 0?

Glucose Retention 120 days

**Comment by tolot27** [comment]
```
DESERTSYNC........................................ 144634 73.5%
USERERRORS........................................ 37184 18.9%
```
As you can see, most of the space is occupied by the desert sync feature. Do you really use it? If not, disable it in the "xDrip+ Sync settings".

Also, quite a lot of messages are logged to the USERERRORS table. I've asked you several times, if you have enabled some verbose logging (search the settings by "Extra tags".

**Comment by Navid200** [comment]
@NickAlbanese85 

Please go to Settings -> xDrip+ Sync settings -> Desert Sync
Is it on?

Please go to Settings -> Less common settings -> Extra Logging Settings -> Extra tags for logging
Please show what you see

**Comment by NickAlbanese85** [comment]
> logged

![Screenshot_20210522-153123_xDrip+](https://user-images.githubusercontent.com/53303294/119237482-6a78b380-bb13-11eb-899d-12aa85c325e8.jpg)

**Comment by Navid200** [comment]
@NickAlbanese85 
Please tap on "Etiquetas extra para el registro", and show what you see.

**Comment by NickAlbanese85** [comment]
> @ NickAlbanese85
> Por favor toque "Etiquetas extra para el registro" y muestre lo que ve.

![Uploading Screenshot_20210522-164808_xDrip+.jpg…]()

**Comment by Navid200** [comment]
@NickAlbanese85 Please upload it the same way you uploaded the previous images.
We cannot see the last image.

**Comment by NickAlbanese85** [comment]
Solucionado

Gracias a un desarrollador argentino hemos encontrado el inconveniente se daba en que xdrip contenia un fallo que reseteaba la aplicacion al menos 30 veces al dia, por lo cual no podia llegar a 24 horas para limpiar datos viejos y asi iba cargando cada vez mas y mas datos.

La solucion consistio en generar un backup de los datos para su reparacion, desinstalar y reinstalar la aplicacion.

**Comment by Navid200** [comment]
This is a translation by Google:

Solved

Thanks to an Argentine developer we have found the problem that xdrip contained a bug that reset the application at least 30 times a day, so it could not reach 24 hours to clean old data and so it was loading more and more. data.

The solution consisted of generating a backup of the data for its repair, uninstalling and reinstalling the application.
