### ISSUE TITLE
Readings Marked "Bad"

### ISSUE THREAD

**Issue by doc77** [NightscoutFoundation/xDrip#1739]
A blood glucose reading can be marked as a "Bad" reading in the Bg Data Table, and that reading will not be used in statistical analyses. This happens routinely for "pressure" lows, initial new sensor readings, and end of sensor on Dexcom.

It would be visually very valuable to have the dots making up the main graph to have a different user defined color for readings marked "Bad" in the Bg Data Table.

This could be implemented in the xDrip+ Color Settings.

![Screenshot_20210524-220126_xDrip+](https://user-images.githubusercontent.com/15315426/119433426-d86fd700-bcdb-11eb-983b-2cbd361cccd0.jpg)

This screenshot shows that at about 5am I had a pressure low. (Finger stick read 89.) It would be valuable to make those five or so bad readings a different color.

**Comment by Navid200** [comment]
@doc77 
There is already an open issue that you opened before:  https://github.com/NightscoutFoundation/xDrip/issues/874
If there is any additional information you would like to add, would you please add it to the existing open issue?

There is already an open PR for this: https://github.com/NightscoutFoundation/xDrip/pull/1732

Would you please not open redundant issues?
Would you please close this issue?
