### ISSUE TITLE
xDrip issue: master recieving readings but followers receive missed readings

### ISSUE THREAD

**Issue by hassanatta9855** [NightscoutFoundation/xDrip#1744]
My xDrip is working and I am the master, I am recieving readings but the rest of my followers also do receive the reading but just in the form of missed readings. For example the phone shows my blood sugar level is 100 and is going down, my parents do receive the reading but it show missed reading since 60 minutes on them.
![Screenshot_2021-06-04-03-26-15-727_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/85319197/120719994-b7ca2d00-c4e4-11eb-808f-5e2c004d4ecb.jpg)
See in the picture above as master it will show the reading correctly but that is what my parents see even thought it's the correct reading it says that it has been missed since 1 hour even though it's not and it just keeps sending new readings but doesn't change missed reading. What should I do?

**Comment by Navid200** [comment]
@hassanatta9855 
> What should I do?

You should have followed the instructions you were given when you attempted to open this issue.

**Comment by Navid200** [comment]
Please post in support channels.  If no one has an answer for you, we will ask you to open an issue here.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

**Comment by Navid200** [comment]
Please open a thread either in the facebook group or in the gitter room (see above).  We will help you there.
