### ISSUE TITLE
Libre2 scan shows "NFC invalid data" for too short time

### ISSUE THREAD

**Issue by steve8x8** [NightscoutFoundation/xDrip#1752]
### Subject of the issue
When priming xDrip with a new L2 sensor, several NFC scans are required.
If there's a problem, the issue is only presented for a too short period of time. Waiting a few seconds after the scan confirmation vibration, one will only see the notofication disappear.

### Your environment
xDrip version 2021.05.21 with recommended settings
Sony Xperia Z3compact running LineageOS 17.1
Libre2 sensor (already active)

### Expected behavior
I'd expect the error message to be still available/readable after more than a few seconds, so proper action can be taken. If there's a request to "try again" as in the "NFC invalid data" message, having to confirm ("OK") would help.

### Actual behavior
Error message disappears after a too short time when the display is still facing away.

### Steps to reproduce the behavior:
NFC scan a "new" sensor to connect to xDrip as L2/BT
(This error to happen seems to be a timing issue - 60 seconds are hard to estimate)

### Screenshots
Cannot be done as I already don't make it in time to _read_ the message

**Comment by Navid200** [comment]
@steve8x8 Please have a look at the event logs under the top right menu.
Is there no log related to the message?

**Comment by Navid200** [comment]
The messages shown on screen are just notifications.  There is usually a log message generated at the same time, which can be used for troubleshooting.

Please use the communication channels to connect with us first.  If there is a reason to open an issue, we will encourage you to open one then.

https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
https://github.com/Navid200/xDrip/discussions
