### ISSUE TITLE
After NFC Scan of Libre 2 no BG readings appear in xDrip

### ISSUE THREAD

**Issue by Thomas-Wolff** [NightscoutFoundation/xDrip#1758]
Hi all,
I have a problem with the NFC scan of my FSL2 sensor running in xDrip via OOPAlgorithm2 since I updated xDrip to build 11 June 2021.
The build from 21 May was still running correctly. It only came up when I updated to build 11 June 2021 2 days ago. One NFC scan is enough and the BT connection to the sensor is disabled and needs to be re-established. Also, after a BT loss of about 15 minutes, I noticed that after an NFC scan, the missing records were not filled in either, which the 21 May version still did without any problems.
Best regards Thomas

**Comment by Navid200** [comment]
@Thomas-Wolff 
You say: 
Has anyone possibly had the same experience with this build and can possibly tell me more about this?

The best place to ask this question is not here.
It is either in the facebook group:
https://www.facebook.com/groups/xDripG5

Or, the Gitter room:
https://gitter.im/jamorham/xDrip-plus

After you ask there, if it is confirmed that this indeed is an issue and there is no work-around, we can always reopen this issue.

**Comment by adenis76** [comment]
I have trouble today with latest nightly from 11.6.2021. After xdrip update blucon stop receiving data from libre 1 and NFC scan stop working. Error message is that sensor clock didn't advance. After xdrip version downgrade everything working again without problems.

**Comment by Thomas-Wolff** [comment]
What does this mean, going back to the construction of 21 May 2021?

**Comment by Navid200** [comment]
@Thomas-Wolff I am just asking you to confirm that you experience the problem wit the June 11, release and you are not experiencing the problem with the May 21 release.  Can you confirm please?

**Comment by adenis76** [comment]
Yes, exactly.

**Comment by Thomas-Wolff** [comment]
just as the construction of 21 may is o.k.

**Comment by jk1993** [comment]
I have noticed similar on the latest build, where an NFC scan appears to do nothing when there are missing data points. But if you go to "Show Libre trend" then you can see the per-minute values and there seem to be lots of them but it does not update the main graph. When this happens, in the logs there are plenty of logs saying "Removing data point" so I suspect it could be that OOP2 is seeing these readings as invalid and removing them from the main graph. I have also been seeing the "Sensor age did not advance" and "Sensor age has gone backwards" quite a few times

**Comment by jamorham** [comment]
@tzachi-dar could you take a look at this? thanks

**Comment by tzachi-dar** [comment]
@jk1993 Are you using libre2 or libre 1?
@adenis76 Are you sure this is libre1? Are you running with the oop on blueon? (if yes which of them)?
@Thomas-Wolff were you able to receive data using libre2 bluetooth connection?

A request for all, can you please send me your xDrip db to tzachi.dar@gmail.com
If that is not possible, can you send a printing of the logs with the problems?

Thanks
Tzachi

**Comment by adenis76** [comment]
I am 100% sure that is libre 1. I am not running any of oop.

**Comment by tzachi-dar** [comment]
@adenis76 
Can you share your logs with me?

Please press the 3 points to the right.
Then please go to backup->back of db.
Once the back up of the db will finish there will be a share button there.
Can you then share it with me at. (tzachi.dar@gmail.com).

Thanks
Tzachi

**Comment by adenis76** [comment]
I am just send you screenshots of logs and I will send you database in few minutes.

**Comment by jk1993** [comment]
@tzachi-dar I'm using libre 2 with OOP2. I will try and send you a db export tomorrow

**Comment by Thomas-Wolff** [comment]
did you get the log file?

Greetings Thomas

 

Von: tzachi-dar ***@***.***> 
Gesendet: Sonntag, 20. Juni 2021 00:11
An: NightscoutFoundation/xDrip ***@***.***>
Cc: Thomas-Wolff ***@***.***>; Mention ***@***.***>
Betreff: Re: [NightscoutFoundation/xDrip] NFC-Scan Problem mit xDrip bau vom 11 Juni 2021 (#1758)

 

@adenis76 <https://github.com/adenis76> 
Can you share your logs with me?

Please press the 3 points to the right.
Then please go to backup->back of db.
Once the back up of the db will finish there will be a share button there.
Can you then share it with me at. ***@***.*** ***@***.***> ).

Thanks
Tzachi

**Comment by tzachi-dar** [comment]
@adenis76 I have received your db, but I don't understand what the problem is. Any chance that you can run with your phone attached to a pc and run with adb? (If not, we can try getting this information in a different way).

Thanks
Tzachi

**Comment by adenis76** [comment]
Unfortunately I can't do that now. You can send me on email step by step instructions and I will do it tomorrow. Thank you.

**Comment by tzachi-dar** [comment]
@adenis76 let's try something simpler:
Please go to settings->less common settings->extra logging-settings->extra tags for logging:
Set there:
Blukon:v,BgReading:v

Please run with the version that is creating problems for 30 minutes, and send me the logs again.
It should give us more information about what is going on.
Please also let me know, what time you have been running with the new version.

Thanks
Tzachi

**Comment by adenis76** [comment]
I am send log file via xdrip feedback. Is there some way to save them and send directly to you? I think problem is starting after NFC scan. In feedback I am include message that log file should be send to you. I am try 11.6 and 19.6 nightly build and they are creating same problem after NFC scan.

Best regards.

**Comment by tzachi-dar** [comment]
@adenis76 
Please press the 3 points to the right.
Then please go to backup->back of db.
Once the back up of the db will finish there will be a share button there.
Can you then share it with me at. (tzachi.dar@gmail.com).

**Comment by tzachi-dar** [comment]
@adenis76 I have received your db, and looking at it.
Are you not getting any readings at all with the new build
Can you let me know at what time there should be a gap in the readings?

**Comment by tzachi-dar** [comment]
@adenis76 I can now see some problems in the logs, but I think that readings should exist.
Did you see a place in the graphs that had no readings?

**Comment by Thomas-Wolff** [comment]
@tzachi-dar, the outage was exactly from 11:20 to 11:41.

**Comment by tzachi-dar** [comment]
OK,
I think that I now understand what the issue is.
I'll try to create a version with a fix tonight.

**Comment by tzachi-dar** [comment]
There have been two issues here:
1) Make sure we always use only the first 0x158 bytes of the data.
2) In the case of libre2, also allow flags == 0 as a legal packet.

The following link should solve both. Please try it.
Please note:
1) The file will be downloaded with a .zip extention. Please remove it (it should be apk).
2) You will need to remove your version before you can install this version. Please backup your settings and db, and only then, do the uninstall and install.

https://drive.google.com/uc?id=1pgbkt3zwe5WJcjqv_Tc4_ZbXUxtbExH2&export=download

Thanks
Tzachi

**Comment by hapvlz** [comment]
Hi Tzachi,

I've tested, this version works amazing so far.
Thank you a lot!
