### ISSUE TITLE
Watchface Data not updated

### ISSUE THREAD

**Issue by blocklist** [NightscoutFoundation/xDrip#176]
After the commit https://github.com/NightscoutFoundation/xDrip/commit/bf50e0f9f9759c815b4283dadccca2319d4cb264 the Watchfaces does not updated automaticly.

I have set the Checkbox to "on", wait 15 Minutes, change it to "off", wait 15 Minute. Only when the Checkbox was changed, the Data was updated once a time. But not after the changing automatically.

The last own Build, from where it works, was https://github.com/NightscoutFoundation/xDrip/commit/d3ca3a7494c3e60cce230dfa386beaabb3e3c716

![screenshot_2017-09-12-12-01-31](https://user-images.githubusercontent.com/491321/30327881-f494af28-97cd-11e7-806b-c8acb23b5310.png)
New value is incoming on xdrip app
![20170912_120141](https://user-images.githubusercontent.com/491321/30327884-f84cedb0-97cd-11e7-9b5e-9cb817e40287.jpg)
But not on the Watchface.

**Comment by kskandispersonal** [comment]
@blocklist Please see comment to you on GitHub commit for this issue.

**Comment by blocklist** [comment]
@kskandispersonal found it. Case closed. Thx!
