### ISSUE TITLE
"Removing point glucoseData" No results shows up

### ISSUE THREAD

**Issue by hapvlz** [NightscoutFoundation/xDrip#1763]
Hello,

FreeStyle Libre 1
xDrip version is: cc96742-2021.06.19
Xiaomi Mi 8 Pro Android 10 QKQ1

Problem appear since: 2021-06-20 16:34 (Could be related to latest update?)
Error attached on screenshot below -

![3e26b95e-9547-428e-8d36-4edfb0c0ce3c](https://user-images.githubusercontent.com/34927858/122908597-95456a00-d354-11eb-8618-a525892ef3e0.jpg)

Glucose data is being recognized in other applications like Glimp, or mine custom application.
It looks like a bug but the logs do not really explain what cause xDrip to not show the results.

![0e86fbf4-8bf9-4d7a-9a80-fb544bd98ccb](https://user-images.githubusercontent.com/34927858/122910005-076a7e80-d356-11eb-9b74-e65324384ab4.jpg)

Thanks.

**Comment by Navid200** [comment]
@hapvlz Please have a look at this open issue:
https://github.com/NightscoutFoundation/xDrip/issues/1758
If you are describing the same problem, please close this.  There is no reason to have multiple open issues for the same matter.

**Comment by Navid200** [comment]
Please post any Libre-related issues that are specific to the June 11 release in this link and avoid opening new issues:
https://github.com/NightscoutFoundation/xDrip/issues/1758

The developers are working on resolving that.
In the meantime, either provide feedback through that open issue, or revert to the previous release and wait for the next release.
