### ISSUE TITLE
sound dropouts with Pixel 4a & soundcore BT devices

### ISSUE THREAD

**Issue by bryanw20** [NightscoutFoundation/xDrip#1766]
Hi sorry if not the right place to ask, FB Group didn't have an answer.
I got a new Pixel 4a; when using Soundcore BT devices (speaker or earbuds) I get several seconds of garbled/muted sound occasionally. I happens the same time a glucose request from my Dex6 happens; but not everytime. Once an hour, or 2-3 times in a row. it goes away after about 30 seconds.

I do not have the same issue with other brand audio devices.
I did not have this problem on my moto G power with Soundcore (Anker) devices.
I do not have this issue on the Pixel in safe mode; or if collection is disabbled; so leads me to believe it's DEX/Xdrip<>Soundcore related.
Any tips on settings to try in Xdrip or BT settings on the phone?

I'm currently using Artem's amazifit band version; I havn't seen a mainline version include the Amazifit band 5 watch yet (I see the option; not a place to enter the code) ver. a99220758-miband-intergration-2021-01-05
This is the version I was using on the Moto with Soundcore and no issues.

Thanks for looking

**Comment by Navid200** [comment]
Have you posted here?
https://gitter.im/jamorham/xDrip-plus

**Comment by bryanw20** [comment]
Thanks, No but I will.

**Comment by bryanw20** [comment]
So haven't confirmed it yet, but some experimenting it seems if I turn off the watch in xdrip (miband for me) the garbled sound problem goes away.
