### ISSUE TITLE
xDrip + Libre2 = calibration problem

### ISSUE THREAD

**Issue by AxelFR2** [NightscoutFoundation/xDrip#1768]
xDrip + Libre2 = calibration problem
Help please 

We can calibrate the Libre2 with an offset of -40 mg/dl to +20 mg/dL [-2,2 mmol/l to +1,1 mmol/l]  

does anyone know how to change these levels? sometimes I need to correct more than +20 mg/dL (+1,1 mmol/l )  but i can't do it.

**Comment by Navid200** [comment]
Please don't open an issue in order to ask a question.
Please post questions here:
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

**Comment by MasterPlexus** [comment]
@axelfr2 : but to answer your question shortly: no, there is no official way to change this limits, as they are safety limits. It is too dangerous, that in low areas the sensor will not provide proper data as it has its own border. Then you will get into a great hypo without noticing it. That's the reason why. A sensor which has this big difference should be replaced.
