### ISSUE TITLE
Question about calibration

### ISSUE THREAD

**Issue by ARkaine2** [NightscoutFoundation/xDrip#1774]
Please, help. 

Does the last calibration on certain BG affect on different BG sensor data/values which were calibrated previosly?

If yes, this means that last calibration "shifts" all BG data/values (even that were calibrated previosly), and there's "subquestion":

What's the point of calibrating sensor on different BGs?

Thanks.

**Comment by Navid200** [comment]
@ARkaine2 Would you please not open an issue just to ask a question?
Your questions are very important and we need to address them absolutely.
Would you please allow us to help you by asking your questions using the identified channels?  Is that going to be a problem?
Would you please explain why?

Those channels are:
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
