### ISSUE TITLE
Dynamically Detect Dexcom Warm-Up Duration

### ISSUE THREAD

**Issue by joshbohmer** [NightscoutFoundation/xDrip#1779]
Rather than assume warmup durations by firmware version, G6 exposes this information dynamically through the 0x52 opcode. This allows for G6 transmitters with non standard warmup durations to display correctly

To retrieve current warmup time
Issue the following to the Command UUID after authentication
`0x5202 + CRC16`
This will return as an example
```
53 xx xx xxxx 201C xxxx (Stock G6)
53 xx xx xxxx 100E xxxx (Stock G6+)
```

1C20 = 120 Minutes Sensor Warmup (Stock G6)
0E10 = 60 Minutes Sensor Warmup (Stock G6+)

**Comment by Navid200** [comment]
I don't think xDrip cares about what the transmitter warm-up time is in native mode.
I think in native mode, as soon as the transmitter starts transmitting readings, xDrip shows them.
That's why when you start a sensor from t:slim, you don't have to also start from xDrip.

**Comment by joshbohmer** [comment]
xDrip assumes a 120 minute warmup when it starts a sensor. We do get dot points on the graph and broadcast data... But the xDrip interface continues to count down 120 minutes and doesn't display the BG reading. It's very confusing for users

**Comment by Navid200** [comment]
I don't think that happens.
You can start a sensor and have everything come up and working.  If now your phone dies, all you need to do is to install xDrip on another phone and enter the transmitter ID.  You don't have to start.  It will take a while, may be up to 20 minutes, for the new phone to sync with the time base of the transmitter.  After that happens, it will start showing readings.  It definitely doesn't take 2 hours.

**Comment by Navid200** [comment]
Again, we may be talking about different things here.
There are messages xDrip shows that I don't like.  I have seen a message stating that xDrip is doing an auto start!  I really don't like that message.   But, shortly after, you will get readings.

**Comment by joshbohmer** [comment]
![Uploading Screenshot_20210124-201627_Chrome.jpg…]()

**Comment by joshbohmer** [comment]
![Screenshot_20201121-160345_xDrip+ variant2](https://user-images.githubusercontent.com/3621222/164154312-e8530842-6449-4cd0-ab0b-e7b63d99ca51.jpg)

This is what happens... Specifically when session is started from xDrip

**Comment by Navid200** [comment]
I may understand what you are talking about now.

**Comment by joshbohmer** [comment]
Yes this is working as expected now
