### ISSUE TITLE
Wrong collector name for blukon

### ISSUE THREAD

**Issue by gregorybel** [NightscoutFoundation/xDrip#178]
Under system, it still shows "LimiTTer" as collector.
Could you please fix to "Blucon"?

**Comment by michalterbert** [comment]
One more thing - in system status, filed Collection Method has wrong value for Blucon (should be Ambrosia Blucon/Blucon/Libre Bluetooth not LimiTTer).

**Comment by jamorham** [comment]
Please try the Oct 7th nightly. I have reworked the "Classic Status" page a little and there is now more sophisticated hardware naming based not just on the selected data source type. Please let me know how it looks.

**Comment by gregorybel** [comment]
this is fixed, thanks!

**Comment by mrinnetmaki** [comment]
I think what is still sent to Nightscout devicestatus, via Nightscout Sync (REST-API), when extra option Upload bridge battery is selected,  is "LimiTTer":

```
{
    "_id": {
        "$oid": "5a48a211b137da15c44a78fe"
    },
    "device": "LimiTTer",
    "uploader": {
        "battery": 100
    },
    "created_at": "2017-12-31T08:38:41.007Z"
}
```

**Comment by tuckdesign** [comment]
I don't see this fixed.

**Comment by gregorybel** [comment]
screenshot?

**Comment by MasterPlexus** [comment]
I'm guessing he means the upload name of the bridgebatt to nightscout. I've seen the field in source code to fix, and made it in my source. The pull request is available (within the speak pull). I'm sure it will be available soon when jamorham will find the time for it.

**Comment by tuckdesign** [comment]
No. Hardware Data Source is set to Libre Bluetooth and in System Status I see:
![screenshot_2018-01-25-21-03-54](https://user-images.githubusercontent.com/4937790/35409830-ac06f224-0213-11e8-9117-7ec19cdb6438.png)

**Comment by gregorybel** [comment]
fixed after getting one reading
