### ISSUE TITLE
Samsung Bluetooth may broken.... again

### ISSUE THREAD

**Issue by mistermintsgh** [NightscoutFoundation/xDrip#1780]
I've been having issues with my Samsung Galaxy S21U (Exynos) since the June security update. I thought it was potentially a problem with an updated version of xDrip, but even after going back several releases the issue persists.

I am getting frequent signal missed, or disconnected issues.

Setup: Libre 1 and MiaoMiao 1
Android 11
MM1 firmware: 39

For signal missed, this happens several times a day, I would estimate at least once every couple of hours, if not slightly more, and requires me to forget the device, and restart the collector, and scan for Bluetooth devices to reconnect. This usually fixes the issue, if not after the first attempt, it will after a couple of tries.

2nd issue appears when using other Bluetooth devices, particularly ones that are constantly talking/streaming information to/from the phone (e.g. headphones). If I try to listen to music using my Galaxy Buds Pro either the phone or xDrip seems to have trouble getting a connection to the MM1 when it polls every X minutes. Before you know it, you've been disconnected for 30 or more minutes while listening to music. When trying to reconnect through Scan for Bluetooth, xDrip is unable to see the MM1 at all to attempt connection.

This issue doesn't appear to affect the system when connected to a BT devices that doesn't require a constant back and forth transfer (e.g. my Garmin watch is connected, and will only connect to the phone periodically for new information). However, if I go for a run and turn on the tracking function, the watch is constantly telling my phone the GPS co-ordinates of where I am, and the phone then uploads these in real time to show a tracking map on the web, which looks to relate to the paragraph above.

**Comment by Navid200** [comment]
@mistermintsgh Do you mind posting in the support channels if you haven't already?
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

If you have already, would you please provide links to the threads?

**Comment by Navid200** [comment]
@mistermintsgh I have been told that nothing can be done, to the xDrip code, to change this.

>He can try the normal BT fixes, like deleting BT configuration, or flipping the values of "trust auto connect" and "use scanning"


If you like to add any other info to this thread, you can always do that.
I am going to close this as I have been told this is not an xDrip issue.
