### ISSUE TITLE
RuntimeException: Cannot find preference screen within search result

### ISSUE THREAD

**Issue by tolot27** [NightscoutFoundation/xDrip#1781]
Searching the settings for "back-fill" and clicking on the top-most hit "Back-fill data Tap to send historical data to Nightscout" (if English is the UI language) results in a `java.lang.RuntimeException: Cannot find preference screen within search result`.

The log shows:
```
jamorham PREFS
Got error trying to highlight search results:
java.lang.RuntimeException: Cannot find preference screen
within search result
```

Any version of xDrip is affected.

**Comment by tolot27** [comment]
I've traced the bug down to the library `search-preference.aar`. This library is self-compiled from repository [ByteHamster/SearchPreference](https://github.com/ByteHamster/SearchPreference) and there are many never versions available. Unfortunately, non of these versions work with xDrip. It looks like `search-preference.aar` was cloned and modified around version [v1.2.6](https://github.com/ByteHamster/SearchPreference/releases/tag/v1.2.6).

@jamorham Do you know who modified the original library?

**Comment by tolot27** [comment]
I've found [Adapted for using in PreferenceActivity Context](https://github.com/CrazyXacker/SearchPreference/commit/d8f0558b68a23b14f81d97971a09b5fd3a7347f9) but this commit introduces some other changes and it will not introduce `SearchConfiguration.getKeysList()`.

**Comment by jamorham** [comment]
This is easy to resolve see: https://github.com/NightscoutFoundation/xDrip/commit/87ac6fc1f57ac40d89f79fa77a6daa13e8379074

**Comment by Lupum1001** [comment]
Opened another pull request with more fixes.


Is there a way to screen for this issue automatically, either by linting the xml or writing unit tests?

**Comment by Lupum1001** [comment]
https://github.com/NightscoutFoundation/xDrip/pull/2114#issuecomment-1122833173
https://github.com/NightscoutFoundation/xDrip/pull/2114#issuecomment-1122837054
Sorry about the relocation @tolot27; I just have a preference for discussing further fixes in the context of the issue than the individual pull request if that's ok.

> This will also find root nodes of `PreferenceScreen`. I don't know whether they need an `android:key` attribute or not.

To my knowledge anything of the type Preference, or its subclasses will need the `android:key` defined. There's at least one exception which is **PreferenceCategory**, but PreferenceGroup may be another.
https://developer.android.com/reference/android/preference/Preference

**Comment by tolot27** [comment]
> Sorry about the relocation @tolot27; I just have a preference for discussing further fixes in the context of the issue instead of the individual pull request if that's ok.

I try to keep the developer related discussions separated from the user-relevant discussions to not "pollute" the issues. But this issue is more like a dev issue. Hence, I'm fine with it.

> > This will also find root nodes of `PreferenceScreen`. I don't know whether they need an `android:key` attribute or not.

> To my knowledge anything of the type Preference, or its subclasses will need the android:key defined.

The docs do not state that the `android:key` attribute is required. If it is really required, we have to add it to the root nodes, too.

[Android Developers > Docs > Reference](https://developer.android.com/reference) states: 

"This class contains a key that will be used as the key into the [SharedPreferences](https://developer.android.com/reference/android/content/SharedPreferences). It is up to the subclass to decide how to store the value."

We have to verify if the addition of the missing `android:key` attribute changes the storage of the preferences and introduces incompatibilities during import.
