### ISSUE TITLE
xdrip crashes on current WearOS

### ISSUE THREAD

**Issue by schmadde** [NightscoutFoundation/xDrip#1784]
After the latest Update of Ticwatch Pro 3 GPS(Wear OS 2.28, system version H MR2, Google play services 21.24.18) xdrip no longer works. I had xDrip-plus-20210628-14c806e.apk installed before from the older wear os release (installed automatically) which still worked but wouldn't communicate with the 20210710 release on the phone. Phone app tried to update the watch app but was caught in an infinite loop (update finished -> wear version fixer tried to install over and over again).

Tried to install via adb (with and without "-g") then xdrip crashed on startup. Also the 210210628 didn't install anymore. 

In the wear OS logs I see a problem with a android.webkit.WebView. Stacktrace is:

07-19 09:57:08.263   756  1847 I ActivityManager: Process com.google.android.packageinstaller (pid 20955) has died: cch+6CEM 
07-19 09:57:08.490 21159 21159 E AndroidRuntime: FATAL EXCEPTION: main
07-19 09:57:08.490 21159 21159 E AndroidRuntime: Process: com.eveningoutpost.dexdrip, PID: 21159
07-19 09:57:08.490 21159 21159 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.eveningoutpost.dexdrip/com.eveningoutpost.dexdrip.LicenseAgreementActivity}: android.view.InflateException: Binary XML file line #90: Binary XML file line #90: Error inflating class android.webkit.WebView
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2914)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6680)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #90: Binary XML file line #90: Error inflating class android.webkit.WebView
07-19 09:57:08.490 21159 21159 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #90: Error inflating class android.webkit.WebView
07-19 09:57:08.490 21159 21159 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at com.eveningoutpost.dexdrip.LicenseAgreementActivity.onCreate(LicenseAgreementActivity.java:33)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7144)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7135)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2894)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6680)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-19 09:57:08.490 21159 21159 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
07-19 09:57:08.491 21159 21159 E AndroidRuntime: Caused by: java.lang.UnsupportedOperationException
07-19 09:57:08.491 21159 21159 E AndroidRuntime: 	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:241)
07-19 09:57:08.491 21159 21159 E AndroidRuntime: 	at android.webkit.WebView.getFactory(WebView.java:2424)
07-19 09:57:08.491 21159 21159 E AndroidRuntime: 	at android.webkit.WebView.ensureProviderCreated(WebView.java:2419)
07-19 09:57:08.491 21159 21159 E AndroidRuntime: 	at android.webkit.WebView.setOverScrollMode(WebView.java:2484)
07-19 09:57:08.491 21159 21159 E AndroidRuntime: 	at android.view.View.<init>(View.java:4807)
07-19 09:57:08.491 21159 21159 E AndroidRuntime: 	at android.view.View.<init>(View.java:4948)
07-19 09:57:08.491 21159 21159 E AndroidRuntime: 	at android.view.ViewGroup.<init>(ViewGroup.java:659)
07-19 09:57:08.491 21159 21159 E AndroidRuntime: 	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
07-19 09:57:08.491 21159 21159 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:403)
07-19 09:57:08.491 21159 21159 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:348)
07-19 09:57:08.491 21159 21159 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:331)
07-19 09:57:08.491 21159 21159 E AndroidRuntime: 	at android.webkit.WebView.<init>(WebView.java:318)
07-19 09:57:08.491 21159 21159 E AndroidRuntime: 	... 34 more

I am not too familiar with Wear OS, can anybody have a look at that?

**Comment by Navid200** [comment]
This issue platform is not a forum.  Not many people look at these on a daily basis.  Please don't open an issue by default as soon as you have a problem.
Please post in the support channels first.
If someone else has seen the problem, or if someone else has a work-around, that's where you can find out because those channels are seen by many every day.

These are the support channels as you already have seen them when you opened this issue:
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

After you do that, if it is established that this is an issue, an issue will be opened.
Please help us maintain this as efficiently as we can.
Thanks

**Comment by Navid200** [comment]
https://github.com/NightscoutFoundation/xDrip/issues/1648
