### ISSUE TITLE
APK mi fit for mi band 6

### ISSUE THREAD

**Issue by Juanaan003** [NightscoutFoundation/xDrip#1785]
Hello, I have bought the Xiaomi mi band 6 and I can't connect it with the mi fit app that I currently have. I was wondering if there is another new version that works with the new band or if the creators are going to release a new version. Thanks

**Comment by Navid200** [comment]
Please don't open an issue to ask a question.
You say this page when you were attempting to open this issue.
https://github.com/NightscoutFoundation/xDrip/blob/master/.github/ISSUE_TEMPLATE/bug-report.md#if-you-need-support-for-xdrip-please-do-not-file-a-ticket-here

As it asks you, please use the support channels:
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
