### ISSUE TITLE
String update during Bounding with blukon

### ISSUE THREAD

**Issue by gregorybel** [NightscoutFoundation/xDrip#179]
Under system status/Bt devices when clicking on Blueooth pairing, when we see this message: "This probably only works on HM10/HM11 devices at the moment and takes a minute"

Could you please remove it or change it for blukon?
Thanks

**Comment by jamorham** [comment]
Does the bluetooth pairing/bonding work correctly with blucon when this message is displayed?

**Comment by gregorybel** [comment]
How should I best test this? I think it works, but not sure.

**Comment by gregorybel** [comment]
never Seen again
