### ISSUE TITLE
Tasker plugin vanished

### ISSUE THREAD

**Issue by doc77** [NightscoutFoundation/xDrip#1797]
2021.08.02 seems to have wiped out the tasker plugin. Reinstalling 2021.07.31 restores the plugin.

**Comment by Navid200** [comment]
The developers are aware.
Would you please use the existing open issue to communicate with the developers?
https://github.com/NightscoutFoundation/xDrip/issues/1796

**Comment by jamorham** [comment]
@doc77 can you try: https://github.com/NightscoutFoundation/xDrip/releases/download/2021.08.02b/xDrip-plus-20210802-a8bca99.apk does this resolve the issue?

**Comment by doc77** [comment]
@jamorham  No, tasker still has not received the plugin. It shows in my task as "unknown plugin"

**Comment by jamorham** [comment]
@doc77 okay I will try something else and revert to you with another update.

**Comment by jamorham** [comment]
@doc77 can you briefly describe what your tasker action that is having problems does? I'm trying to figure out which part of the interface you are using.

**Comment by doc77** [comment]
@jamorham  The actions  I use in the plugin are Snooze, Speak On, Speak Off, and Restart App.  But the whole plugin does not register with Tasker in 2021.08.01 a or b.  Tasker fires the "Missing Plugin" notification every time a task is called using xDrip+, and the task does not fire.  I use them in Profiles that continue to work fine except for the xDrip actions contained within them.

**Comment by tolot27** [comment]
@jwoglom Do you have any idea what the cause of the problem could be? IMHO, we need more unit tests.

**Comment by jwoglom** [comment]
Just from looking at the xDrip commit history between 7/31 and 8/2, I have no idea why this would've been broken, unfortunately. Nor am I incredibly familiar with the lifecycle of how xDrip registers as a tasker plugin. 

Shot in the dark, could the token preprocessor changes by @jamorham from August 1st have implicitly changed an identifier which tasker uses to identify the xDrip plugin? My understanding from looking at the commit is that it adjusted a large number of package names. If the java class inside xDrip which implements the tasker plugin was used as an external identifier then changing these package names could've broken an already set-up tasker configuration.

**Comment by jamorham** [comment]
@doc77 it is a significant issue because we need to resolve any regressions introduced by changes. I think there is a good chance that the issue is due to the package renaming which could affect inbound intents from Tasker. I'm slightly surprised though as mine have been working fine but there are a few different ways tasker can be set up so that could be it. 

I don't think we need package renaming for the tasker interface as it isn't used with databinding afaik (which is why the packages names are being lowercased) - so I have reverted that and will roll another build that you can try out.

**Comment by jamorham** [comment]
@doc77 does this version resolve the issue for you: https://github.com/NightscoutFoundation/xDrip/releases/download/2021.08.02c/xDrip-plus-20210802-053ad95.apk ?

**Comment by doc77** [comment]
@jamorham  Thank you so much. This seems to do the trick. I appreciate all of your hard work on this project.

**Comment by tolot27** [comment]
Issue is solved by excluding Tasker from package renaming. Nevertheless, we need Tasker unit tests.
