### ISSUE TITLE
Don't open an issue to report problems with the latest Nightly 

### ISSUE THREAD

**Issue by Navid200** [NightscoutFoundation/xDrip#1798]
If you are experiencing any issues with the latest Nightly, please post in this open issue:
https://github.com/NightscoutFoundation/xDrip/issues/1796

Please DON'T open a new issue.

There is work in progress.  
There is no need to flood the issues platform with more and more new issues.

**Comment by tolot27** [comment]
We cannot prevent people doing this but we can enhance the issue template to include a reference to any issues labeled with [build-nightly](https://github.com/NightscoutFoundation/xDrip/issues?q=is%3Aissue+label%3A build-nightly).

**Comment by doc77** [comment]
@Navid200  Since #1796 really doesn't pertain to #1797 except that it is a problem with a latest nightly build, perhaps you should rename the issue "problems with the latest nightly build". 
And #1797 pertains to 2021.08.02, and #1796 pertains to 2021.08.01.

**Comment by Navid200** [comment]
@doc77 It was renamed already by tolo27.
Thanks

**Comment by Navid200** [comment]
@doc77 There would be no 2021.08.02 if 2021.08.01 did not cause  the problems it did.
Now, there is also a 2021.08.02b.  
Are we now going to have another issue opened for 2021.08.02b?

**Comment by doc77** [comment]
@doc77   I am on the Nightly Update Channel, and every update is installed. The Tasker issue did not exist in 2021.08.01, and I first noticed it in 2021.08.02, and it continued in 2021.08.02b.
I am not a programmer, but this seems like pertinent information.
How would you report it, especially since it is not an issue with 2921.08.01?

**Comment by Navid200** [comment]
@doc77 I have and I am asking you to please report it in this issue now that you have been told we are struggling to address the issues the user community is experiencing:
https://github.com/NightscoutFoundation/xDrip/issues/1796

There is one problem.  By using the same open issue, you help jamorham because he can see everything in one place instead of having to go back and forth between multiple issues.

**Comment by Navid200** [comment]
@doc77 Please note that 2021.08.01 does not exist anymore.  No one will get it now.  Of course, those who have already updated to it, will have it until they update.
Very likely, 2021.08.02 will be removed soon as well.

This is an ongoing issue.  It's the same issue manifesting itself in many different ways.
