### ISSUE TITLE
Add a preference to toggle watch face toasts

### ISSUE THREAD

**Issue by badgerpapa** [NightscoutFoundation/xDrip#180]
Add a preference to enable or disable the watch face detail toast messages (steps,  a1c estimate,  etc). "Treatment processed" should be configurable separately if at all.

**Comment by kskandispersonal** [comment]
What about the extra status toast message, which provides a1c, and other fields as shown on the phone xDrip+ extra status line?  This popups now when you tap the BG.

**Comment by badgerpapa** [comment]
Ideally I would like the option to disable that as well. My personal use case is watch for immediate data, phone for additional detail. A1c and long term averages fall in the latter category.

**Comment by old-square-eyes** [comment]
Keen for this too. Never use toasts on Wear. On SW3 I can't pull down the menu to see the date without a toast covering it.

Could the info perhaps be accessed from a button in the three dot menu?

Like a page, rather than a toast.

**Comment by jamorham** [comment]
@old-square-eyes I have also had problems with the toasts popping up when I try to access the menus

**Comment by jamorham** [comment]
I believe this should be resolved now in the recent updates to the Wear component. 

@badgerpapa have you been able to test the new preferences item?

**Comment by badgerpapa** [comment]
I have. It works perfectly. Thanks.

**Comment by jamorham** [comment]
Marking as resolved
