### ISSUE TITLE
Getting an unknown firmware version and told to report

### ISSUE THREAD

**Issue by nicking44** [NightscoutFoundation/xDrip#1802]
System screen
![Screenshot_20210805-111703](https://user-images.githubusercontent.com/7844132/128375536-002b97e3-79bf-4894-b197-187185c33d93.png)
Errors event list
![Screenshot_20210805-111847](https://user-images.githubusercontent.com/7844132/128375716-41ff48a3-e97f-4712-a577-2e33c37770d2.png)

**Comment by Navid200** [comment]
@nicking44 Thanks

Please follow the instructions here:
https://github.com/Navid200/xDrip/wiki/Report-Firmware
