### ISSUE TITLE
Freestyle Libre 3 Support

### ISSUE THREAD

**Issue by twinko** [NightscoutFoundation/xDrip#1804]
I already found a closed Issue.

But wanted you to inform, that it is already possible to order the new freestyle libre 3 Sensors and the IOS App is already available:

**Official Libre 3 Website:**
https://www.freestylelibre.de/libre/freestyle-libre-3-entdecken.html#scannen
**Official Libre 3 IOS app:**
https://apps.apple.com/de/app/freestyle-libre-3-de/id1525101160

Do we need to wait for the Android version to have it been cracked and to accomplish xdrip support?

Regards

**Comment by Navid200** [comment]
Please don't use this issues platform for brainstorming, informing others, informing developers, asking questions, ...
The issues platform is meant to be used by the developers to solve/track issues and new features.

There are already two support channels you can use for communicating with the developers as well as other users:
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

After you use those channels, the developers may ask you to open an issue if/when needed.
