### ISSUE TITLE
AOD Bug report 

### ISSUE THREAD

**Issue by FreDiabetics** [NightscoutFoundation/xDrip#1806]
Hey Guys, 

I don't know why it isn't possible to set a static postion for the aod widget. Most of the time it's not possible to clearly read the widget because its shown on top of the other aod displays. 

Please add an option to bypass this. I love this aod feature but in it's current state it's not usable.

![IMG-20210809-WA0000](https://user-images.githubusercontent.com/45721291/128669150-e6e436a8-5abe-4cfc-9d3d-a859894fe374.jpg)

**Comment by Navid200** [comment]
@FreDiabetics Would you please report this here?  https://github.com/NightscoutFoundation/xDrip/issues/1625

If there is a reason you believe this should be in a different issue, please explain and we can always reopen.
Thanks
