### ISSUE TITLE
"Motion Tracking" feature in S21 phone not working

### ISSUE THREAD

**Issue by reijoahola-nightscout** [NightscoutFoundation/xDrip#1813]
I used xDrip+ Motion Tracking feature successfully with my older phone Samsung Galaxy S9 / Android 9 (SM-G960F). Then I upgraded into Samsung Galaxy S21 5G / Android 11 (SM-G991B/DS). Unfortunately Motion Tracking seems not to work. It was automatically disabled with a note "... may be incompatible with your phone". Has somebody successfully used Motion Tracking with S21. Is there possibly something what I should do to correct the situation ?

xDrip+ version: the latest Nightly Builds, now 2021.08.04 but probably the same problem in earlier releases.

xDrip+ configuration: Data source 640G/Eversense (patched G6 app = BYODA).
Android Wear Integration = ON (Wear OS watch)

<img width="400" src="https://user-images.githubusercontent.com/45634868/129604090-e10f7fe1-880c-4745-94d0-00ddd6a89a8d.jpg" />

**Comment by tolot27** [comment]
Did you ask in the support groups (FB, Gitter) as it was described in the issue template?

**Comment by reijoahola-nightscout** [comment]
> Did you ask in the support groups (FB, Gitter) as it was described in the issue template?

Yes, I opened a question at first in xDrip Fb group. I was recommended to open an issue about this.

**Comment by tolot27** [comment]
Did anyone experience the same problem?
Are there any further log entries? I assume there are some further permission needed.

Please can you enable extra logging (`ActivityRecognizer:v`)?

**Comment by tolot27** [comment]
Android 10 changed the Activity API and also the permission. It is sometimes auto-granted. Please can you check in your system permission settings, whether `Activity Recognition` is granted to xDrip?

**Comment by reijoahola-nightscout** [comment]
> Android 10 changed the Activity API and also the permission. It is sometimes auto-granted. Please can you check in your system permission settings, whether `Activity Recognition` is granted to xDrip?

Yes, App Permissions for xDrip+ has "Physical Activity" ON if it is the same as "Activity Recognition". It was also ON in the old phone.

But then I noticed that "Change system setting" was OFF in the new phone and ON in the old phone. I am now testing with that if it helps.

**Comment by reijoahola-nightscout** [comment]
> Did anyone experience the same problem?
> Are there any further log entries? I assume there are some further permissions needed.
> 
> Please can you enable extra logging (`ActivityRecognizer:v`)?

How is extra logging (`ActivityRecognizer:v`) enabled ?

**Comment by tolot27** [comment]
> How is extra logging (`ActivityRecognizer:v`) enabled ?

Settings->Less common settings-> Extra logging -> Extra tags for loggings

**Comment by reijoahola-nightscout** [comment]
I sended Error and Event List directly from xDrip+. Still using Nightly Build 2021.08.04.

**Comment by reijoahola-nightscout** [comment]
Extra Logging gave this additional info: "Received ActivityRecognition we were not expecting!" and after that xDrip+ disabled Motion Tracking again.

**Comment by Navid200** [comment]
My understanding is that motion tracking may not work on all phones.
It also is not directly related to blood glucose.
So, I am going to close this.  We can reopen if needed.
