### ISSUE TITLE
Nightscout Sync (REST-API) disabled after scanning BlueJay's QR Code

### ISSUE THREAD

**Issue by bchris21** [NightscoutFoundation/xDrip#1816]
**xDrip version:** abe5f80-2021.08.18

**Phone:** Xiaomi Mi6 MIUI 11.0.6
**Android Version:** 9 PKQ1. 190118.001
**CGM:** Dexcom G6 (Transmitter 8R####)
**xDrip Core Version:** v2191
**BlueJay Firmware:** 2191

**Issue description:**  
After initial BlueJay GTS setup with scanning QR Code, BG values stopped being uploaded to Nightscout. After short investigation I have realized that Nightscout Sync (REST-API) was disabled. Issue replicated multiple times after resetting BlueJay GTS to factory default settings.

### Screenshots  
![Screenshot_20210825_204625.jpg](https://user-images.githubusercontent.com/4725280/130847982-529d76c2-5671-42a6-9e10-523e6cb653ad.jpg)

**Expected behavior:**
After synchronization between xDrip and BlueJay GTS, Nightscout REST-API setting should stay enabled.

**Actual behavior:**    
Nightscout REST-API setting is disabled after successful QR Code sync procedure.

### Steps to reproduce the behavior:   
1. Open QR Code in BlueJay GTS to initiate sync procedure.  
2. Scan the QR Code with xDrip.  
3. Navigate on xDrip setting: Menu - Settings - Cloud upload - Nightscout Sync (Rest-API).  
4. Check if the toggle button is now disabled (OFF).

**Comment by Navid200** [comment]
@bchris21 Can you try the latest nightly?
https://github.com/NightscoutFoundation/xDrip/releases/tag/2021.09.02
Just install over your current version.  Please don't uninstall first.
If you experience any unexpected behavior, you can install any other version over to undo.

**Comment by bchris21** [comment]
Hello @Navid200. Just installed and works like a charm.

- Reset my son's BlueJay GTS to factory settings.
- Requested QR to scan and setup.
- Pairing done successfully.
- Nightscout settings were not altered as before.

Many thanks to you and @jamorham for your fast support/fix. 👌🏻

**Comment by Navid200** [comment]
Great!
Thanks for feedback.

**Comment by tolot27** [comment]
Fixed with 727aeaffc6354edf4bced6a95531a1758cad4c4e.
