### ISSUE TITLE
xdrip mi band 5 and carelink follower for 770g insulin pump

### ISSUE THREAD

**Issue by Fhusain9696** [NightscoutFoundation/xDrip#1819]
hello, issue with mi band 5 and carelink follower for 770g , xdrip, any available version?

**Comment by Navid200** [comment]
Sorry,

Would you please not open an issue just to ask a question?

https://github.com/NightscoutFoundation/xDrip/blob/master/.github/ISSUE_TEMPLATE/feature-request.md
