### ISSUE TITLE
Feature Request: Mi Band 6 Support

### ISSUE THREAD

**Issue by Troplo** [NightscoutFoundation/xDrip#1820]
Hello,

I'm wondering if supporting the Mi Band 6 is possible, especially considering the earlier Mi Band's are supported, as having a notification or a watch-face with glucose data would be very handy.

Thanks.

**Comment by Navid200** [comment]
@Troplo There is already an issue for Mi Band 5:  https://github.com/NightscoutFoundation/xDrip/issues/1410

Please add your request to that issue.  It is true that the two are different.
However, it is highly unlikely to add support for this one before that.
