### ISSUE TITLE
Galaxy Watch4 series (WearOS3) complications not working in follower/broadcast mode

### ISSUE THREAD

**Issue by FreDiabetics** [NightscoutFoundation/xDrip#1822]
This is tested on Galaxy Watch4 classic. 
If I'm using the "xDrip+ complication provider" it always shows "null / null" or "/null". 
I'm using build-your-own-dexcom-app to recieve my values, xDrip+ datasource is set to "640G/Eversense". 
All default xDrip+ watchfaces are working fine just the complication provider isn't. As you can see on the pictures.

For "G6 Native" datasource everything works fine, but I need the Dexcom reports for my endo.

![20210907_191547.jpg](https://user-images.githubusercontent.com/45721291/132386112-17a16fab-2580-4ce1-898e-3ef8f4d6c083.jpg)
![20210907_191625.jpg](https://user-images.githubusercontent.com/45721291/132386123-ffce0e4c-1596-4b2a-98d2-25e1b4d97545.jpg)
![20210907_191716.jpg](https://user-images.githubusercontent.com/45721291/132386135-67798bef-802f-4758-bc1d-135936048b5f.jpg)

**Comment by t1dude** [comment]
I can confirm that I'm having the same issue. Looking forward to a solution 🙃👍Don't hesitate to ask if you need more information or testing.

**Comment by reijoahola-nightscout** [comment]
I remember that this was discussed earlier with Wear OS2. The problem probably is also with Wear OS2.

**Comment by FreDiabetics** [comment]
> I remember that this was discussed earlier with Wear OS2. The problem probably is also with Wear OS2.

if this is really the case, it is all the more shameful that this problem has not yet been resolved.

**Comment by Navid200** [comment]
@FreDiabetics Please add your comments to the existing issue:
https://github.com/NightscoutFoundation/xDrip/issues/303

Please explain why if you believe this needs to have a dedicated issue.

**Comment by FreDiabetics** [comment]
Please Stop closing my issues!!! 

I think it needs this new Issue because nobody cares about the old one....

**Comment by FreDiabetics** [comment]
> @FreDiabetics Please add your comments to the existing issue:
> https://github.com/NightscoutFoundation/xDrip/issues/303
> 
> Please explain why if you believe this needs to have a dedicated issue.

Please Stop closing my issues!!! Really annoying!! Are you one of the developers? 

I think it needs this new Issue because nobody cares about the old one....

**Comment by Navid200** [comment]
@Post in the Gitter room and we can discuss.
