### ISSUE TITLE
[UX] "Add treatment" shortcut on graph

### ISSUE THREAD

**Issue by BenoitAnastay** [NightscoutFoundation/xDrip#1824]
There is a "Add note" button when we click on a graph.

My idea is to add a treatment shortcut with the time value prefilled with the one of the plot we clicked on the graph.

I tend to enter carbs late, when we forget to log one I tend to click on the graph to add the missing one.

It seam that ppl may tend intuitively to click on the graph and add note instead of adding treatment (maybe because of others software that only support text)

Another suggestion is to parse entered note and if someone entered units (carbs or others keywords) as note, poping an infobox asking if the user meant to enter a treatment

To unclutter the UI we can maybe use pictograms on the footer, instead of text (not sure if it'll help or confuse ppl)

**Comment by Navid200** [comment]
This capability already exists.
When you opened this, you were asked to please post in one of our support channels to make sure this should be an issue before you open one.
Did you?

Would you please post first in the support channels before opening an issue?
https://github.com/NightscoutFoundation/xDrip/blob/master/.github/ISSUE_TEMPLATE/feature-request.md

**Comment by BenoitAnastay** [comment]
@Navid200 I'm not sure to understand I see no shortcuts to such things

There two types of buttons one for note and for specific to blood test

```
switch (type) { case PointValueExtended.BloodTest: final String fuuid = uuid; final View.OnClickListener mBtOnClickListener = new View.OnClickListener() { @Override public void onClick(View v) { Home.startHomeWithExtra(xdrip.getAppContext(), Home.BLOOD_TEST_ACTION, time.toString(), fuuid); } }; Home.snackBar(R.string.blood_test, message, mBtOnClickListener, callerActivity); break; default: final View.OnClickListener mOnClickListener = new View.OnClickListener() { @Override public void onClick(View v) { Home.startHomeWithExtra(xdrip.getAppContext(), Home.CREATE_TREATMENT_NOTE, time.toString(), Double.toString(ypos)); } }; Home.snackBar(R.string.add_note, message, mOnClickListener, callerActivity); break; }
```

What I would like is opening treatment with time prefilled after I clicked a PointValue

I do not thing that there is such implementation or it's kinda hidden
