### ISSUE TITLE
Turn Off Alarm by Turning Phone

### ISSUE THREAD

**Issue by Marco77577** [NightscoutFoundation/xDrip#1830]
### Is your feature request related to a problem? Please describe.
I have alarms set at night. However, sometimes, while sleepy at 4am in the morning, I seem to be cognitively unable to turn off the alarm by first unlocking the phone, and then cancelling the notification. By the time I achieve this, I am wide awake, and so is my partner and anyone else sleeping in the same ~room~house.

While getting me to wake up is the purpose of the alarm, shooting my adrenaline levels to other dimensions is clearly overkill.

### Describe the solution you'd like
When starting an alarm, listen to the phone's sensors and turn the alarm off, if the phone is turned around (such that the screen is now facing towards the ground/night stand/bed, and vice versa).

### Describe alternatives you've considered
In addition to listen to the accelerometer in the phone, we could use the proximity sensor to allow tapping your phone with your hand to turn off the alarm.

### Additional context
Detect phone flips: https://stackoverflow.com/a/22952085/1139514

What does the community think of this idea?

**Comment by Navid200** [comment]
Not indentical, but similar request:
https://github.com/NightscoutFoundation/xDrip/issues/73

Would you please post in the closed issue I have linked and add your suggestion?

Allowing the alert to be dismissed too easily defeats the purpose of the alert.

With respect to not waking up your partner, or anyone else, please try the ascending volume profile:
https://github.com/Navid200/xDrip/wiki/Ascending-Volume-Profile

**Comment by Navid200** [comment]
Using the support channels is the best way to ask the opinion of the community:
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
