### ISSUE TITLE
Android 10 NightScoutFollowService exception

### ISSUE THREAD

**Issue by jrsokolow** [NightscoutFoundation/xDrip#1831]
Hi,

I am running xDrip+ (stable version) and Android APS on Jelly 2 with Android 10.

My set up if following.

I have NightScout receiving BG from Medtronic 640 uploader.

xDrip reads BG from NightScout and should send it locally to Android APS where xDrip is set as BG source.

Problem is that sending BG from xDrip to APS is not working or works once and then not.

In xDrip event logs I see following exception

"Got exception trying to use Android 10+ service starting for NightscoutFollowService java.lang.IllegalArgumentException: foregroundServiceType 0x0000....08 is not subset of foregroundServiceType attribute 0x00000000 in service element of manifest file"

Please help :)

**Comment by tolot27** [comment]
I've discovered this exception a while, too. But it had no effect on functionality, at least for me. I already dig into it a bit. The reason for the exception is that the data sync services of xDrip do not have the right foregroundServiceType. I can provide a fix, soon.

**Comment by jrsokolow** [comment]
> I've discovered this exception a while, too. But it had no effect on functionality, at least for me. I already dig into it a bit. The reason for the exception is that the data sync services of xDrip do not have the right foregroundServiceType. I can provide a fix, soon.

**Comment by jrsokolow** [comment]
Hi @tolot27, thanks a lot. Fix will be available in nightly build? Could you let here now when it is there ?

**Comment by tolot27** [comment]
> Hi @tolot27, thanks a lot. Fix will be available in nightly build? Could you let me know here when it is there ?

Please look at the corresponding PR and try the linked apk. Report back, if your problem is solved.

**Comment by tolot27** [comment]
> @tolot27 I have tested and bug is still there

Did you mean your problem with not sending BG from xDrip to APS? Is the exception gone?

**Comment by jrsokolow** [comment]
> > @tolot27 I have tested and bug is still there
> 
> Did you mean your problem with not sending BG from xDrip to APS? Is the exception gone?

Problem with sending BG from xdrip to aps is still there and bug in event logs is also there. So nothing has changed. I have checked in system status that I have installed version provided by you.

**Comment by jrsokolow** [comment]
@tolot27 I am wondering, maybe I should build xDrip for android 10 specifically? Currently I was using latest stable version downloaded from xdrip github page.

**Comment by tolot27** [comment]
@jrsokolow Please try the new apk available at https://www.dropbox.com/s/gsmxydjq8jqoocm/xDrip_20210923_7282febf4_DataForegroundServiceTypes_debug.apk?dl=0.

The exception should be gone but I'm sure, the root cause of your problem is different because regardless of the exception, NightscoutFollowService is started, anyway.

> Problem is that sending BG from xDrip to APS is not working or works once and then not.

What is correct: it is not working or it works just once after starting xDrip? In my opinion, your setup does not make much sense to me. Sending data from one xDrip (likely another phone) to Nightscout and using an xDrip instance with NightscoutFollowService as bridge/broadcaster to AAPS it not recommend. Why don't you use one xDrip instance as primary BG collector and broadcaster to AAPS?

**Comment by tolot27** [comment]
> > Problem is that sending BG from xDrip to APS is not working or works once and then not.
> 
> What is correct: it is not working or it works just once after starting xDrip? In my opinion, your setup does not make much sense to me. Sending data from one xDrip (likely another phone) to Nightscout and using an xDrip instance with NightscoutFollowService as bridge/broadcaster to AAPS it not recommend. Why don't you use one xDrip instance as primary BG collector and broadcaster to AAPS?

Ah, got it. Because you need NightScout to receive the BGs from Medtronic 640 uploader. Would #1649 an option for you?

**Comment by jrsokolow** [comment]
> @jrsokolow Please try the new apk available at https://www.dropbox.com/s/gsmxydjq8jqoocm/xDrip_20210923_7282febf4_DataForegroundServiceTypes_debug.apk?dl=0.
> 
> The exception should be gone but I'm sure, the root cause of your problem is different because regardless of the exception, NightscoutFollowService is started, anyway.
> 
> > Problem is that sending BG from xDrip to APS is not working or works once and then not.
> 
> What is correct: it is not working or it works just once after starting xDrip? In my opinion, your setup does not make much sense to me. Sending data from one xDrip (likely another phone) to Nightscout and using an xDrip instance with NightscoutFollowService as bridge/broadcaster to AAPS it not recommend. Why don't you use one xDrip instance as primary BG collector and broadcaster to AAPS?

Hi @tolot27, I have tested and exception is not there any more. Thanks a lot.

**Comment by jrsokolow** [comment]
> > > Problem is that sending BG from xDrip to APS is not working or works once and then not.
> > 
> > 
> > What is correct: it is not working or it works just once after starting xDrip? In my opinion, your setup does not make much sense to me. Sending data from one xDrip (likely another phone) to Nightscout and using an xDrip instance with NightscoutFollowService as bridge/broadcaster to AAPS it not recommend. Why don't you use one xDrip instance as primary BG collector and broadcaster to AAPS?
> 
> Ah, got it. Because you need NightScout to receive the BGs from Medtronic 640 uploader. Would #1649 an option for you?

I will check that, thanks
