### ISSUE TITLE
InfluxDB - change or add numeric field for "direction"

### ISSUE THREAD

**Issue by michalterbert** [NightscoutFoundation/xDrip#184]
Hi,
First - thanks for Xdrip+ and InfluxDB support.
I'm using InfluxDB as a Cloud Upload - everything looks good, but maybe we can add new filed to transform string value "direction" to something numeric?

Now in DB we have:
```
time                delta   direction     filtered noise rssi unfiltered value_mgdl value_mmol
----                -----   ---------     -------- ----- ---- ---------- ---------- ----------
1506024103759000000 -4.414  Flat          164588   1     100  164588     136        7.5739263617482
1506024401373000000 -7.827  FortyFiveDown 156823   1     100  156823     128        7.14297321437499
```
Field "Direction" is now string, but Grafana can not visuale this filed (only on single stat as a text, without alerts, without mapping/colors), On Grafana's github is now open issue to add avability for mapping and colorize strings in singlestat plugin, but if you could add new filed with numerc value I would like to use them in grafana to visualize arrows, for ex Flat as a 0, next I can map 0 in Grafana to → :)

My mapping suggestion:
```
 3  = DoubleUp
 2  = SingleUp
 1  = FortyFiveUp
 0  = Flat
-1 = FortyFiveDown
-2 = SingleDown
-3 = DoubleDown
```

Guys, What do you think?

**Comment by jamorham** [comment]
Direction is just calculated from the delta so I would have thought something could be done with that already. Tagging @pimeys who produced the influx integration.

**Comment by pimeys** [comment]
@michalterbert How I visualize the direction, I just get the derivative from `value_mmol`:

```
SELECT derivative(mean("value_mmol"), 5m) FROM "glucose" WHERE $timeFilter GROUP BY time($interval) fill(null)
```

And then display it in its own graph:

![delta](https://user-images.githubusercontent.com/34967/30814859-aa2c0c6c-a211-11e7-984d-ebe2506e9b85.png)

Now it's nice to hear somebody else is using the InfluxDB integration. I still don't really know how to adjust the graphs for calibration, and do I even have all the data available to do that. Also I'm very interested about dashboard other people have been doing with Grafana.

**Comment by michalterbert** [comment]
I'm working on it (dashboards) - also are avaliable on my fork of this git repo :)

![image](https://user-images.githubusercontent.com/15417117/31293051-16e2c6b2-aad6-11e7-911b-36eee20d6081.png)

@pimeys are you sure that direction can be visualize by derivatice form value_mmol?
my example: 
![image](https://user-images.githubusercontent.com/15417117/31293127-5dbd85cc-aad6-11e7-808a-217585022a11.png)

But Direction from influx db is FortyFiveUp :/ For my the best form of visualize this will be SingleStat and transform from integer to string/char  (↑ → ↓ ↘) so if you add to code this small part - will be great :+1: 

I'm also using grafana notification (alerts) and Slack integration - I have realtime alerts on my phone whe my son has low or high level of glucose :)

What is a problem with adjust the graphs for calibration, could you put more lights on this?

**Comment by michalterbert** [comment]
Ok, I have update :)
more or less:
![image](https://user-images.githubusercontent.com/15417117/31294708-4760955c-aadc-11e7-9941-c9fe446b8e32.png)
Correct me if I am wrong.
Query - Last Delta (float)
And effect:
![image](https://user-images.githubusercontent.com/15417117/31294738-61108732-aadc-11e7-9d15-b5314540367a.png)
Thanks!

**Comment by pimeys** [comment]
I like that. I made an arrow too, but what kind of color settings you use?

![trend](https://user-images.githubusercontent.com/34967/31295648-a3df2a0c-aadf-11e7-811d-1434b6c3e482.png)

**Comment by pimeys** [comment]
This Grafana plugin I found also very useful to see the big picture:

https://grafana.com/plugins/petrslavotinek-carpetplot-panel

Set it to override the relative time from the settings to something like 1 month to see a pattern where you're hyper and where hypo.

I use the average per hour over a month, with the query:

```
SELECT mean("value_mmol") FROM "glucose" WHERE $timeFilter GROUP BY time($__interval) fill(null)```

And spectral color scheme, so hardcore hyperglycemias are red, down from yellow -> green -> blue.

**Comment by sodesignberlin** [comment]
Hi,
I also would love to set up my own local server with influxdb as you guys did –
My problem is, that I dont have the skills nor the know how to do it the propper way. The rare Info I found on the net is not foolproof enought for me :( 
I dont know what exacrtly what kind of hardware I need (rasperyp?), nor what I have to install on it to work with my working xdrip/libre/Smartphone setting. 
I would be wonderfull if someone could give meand maybe other people a starting point or a kind of description of your personal setup. Maybe a kind of tutorial or Dokumentation coud result out of this question?
Thanks, Wolfgang

**Comment by michalterbert** [comment]
> Hi,
> I also would love to set up my own local server with influxdb as you guys did –
> My problem is, that I dont have the skills nor the know how to do it the propper way. The rare Info I found on the net is not foolproof enought for me :(
> I dont know what kind of hardware I need (rasperyp?), nor what exactly I have to install on it to run with my working xdrip/libre/Smartphone settings.
> It would be wonderfull if someone could give me and other people a starting point or a kind of description of your personal setup.
> Thanks, Wolfgang

Hi,
Please send me an email - michal@jakicukier.pl, I have nice platform InfluxDB + Grafana for xDrip purpose - please check jakicukier.pl :)

**Comment by razerrazer** [comment]
I'm working on it (dashboards) - also are avaliable on my fork of this git repo :)

What i can see so is there any of this code on your github repository ?
I would like to have your dashboard on my grafana server.

**Comment by Navid200** [comment]
What is the status of this issue?
Can we close it?

**Comment by michalterbert** [comment]
My dashboard (json file).
[dashboard.txt](https://github.com/NightscoutFoundation/xDrip/files/6048146/dashboard.txt)

Please close issue.
