### ISSUE TITLE
Intermittent connection loss with Dexcom G6

### ISSUE THREAD

**Issue by janvitos** [NightscoutFoundation/xDrip#1843]
### Subject of the issue
Hi! I bought a Soyes 7S Android 6.0 phone for my diabetic son to use as a collector for his Dexcom G6. This is a tiny phone (2.5 inch screen) that he will be able to carry everywhere, like at school and grand-ma's house. Most companies don't make properly sized phones for kids, so this device is really ideal.

Unfortunately, the connection between xDrip on the Soyes 7S and the G6 drops intermittently. When the Soyes 7S and the G6 are connected, xDrip works great. But eventually, after some time (can be 10 minutes or hours), xDrip can't connect to the G6 anymore and shows Signal Missed until I manually turn Bluetooth OFF and ON or reboot the phone.

### Your environment
- xDrip Nightly 2109022014
- Dexcom G6
- Soyes 7S Android 6.0 phone with Mediatek MT6580 CPU
- Battery Optimizations are disabled
- xDrip settings have been left at default
- Also tried using the xDrip settings for G6 provided here https://github.com/Navid200/xDrip/wiki/G6-Recommended-Settings

### Expected behavior
When connecting to the Dexcom G6 with xDrip, I expect the connection to remain stable.

### Actual behavior
The connection between the Dexcom G6 and xDrip often drops, leaving xDrip without readings until I manually restart Bluetooth or reboot the phone.

### Steps to reproduce the behavior
1. Connect the Dexcom G6 to xDrip
2. Wait until the connection drops between both devices (it can take 10 minutes or hours before the connection drops, but usually it will take less than an hour)
3. The connection will never get reestablished until manual action is taken
4. The following entry appears many times in the log:
```
MissedReadingService
Aggressively restarting collector service due to lack of reception
```

### Personal notes
I have lots of experience with xDrip. I've been using it for about 2 years and had all kinds of different setups, like Libre Whole House, which was awesome, but we switched to Dexcom G6 because it is now covered by the public health insurance plan in Quebec. I currently have xDrip running perfectly on 3 phones (Samsung Galaxy S10, Huawei P40 Pro and Motorola G7 Power) with the G6. The Soyes 7S is the only phone that is giving me trouble. I've also troubleshooted many issues with xDrip before and will gladly assist in troubleshooting this issue further.

**Comment by Navid200** [comment]
Would you please either post in the facebook group, or in the Gitter room?
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

We will try to help you, and everyone else, resolve problems with using xDrip that way.
If it is then determined that we need a change to the xDrip code, that's when an issue needs to be opened here.

**Comment by janvitos** [comment]
Sure, thanks.

**Comment by Navid200** [comment]
![244419452_1377707012623216_6300000213746098651_n](https://user-images.githubusercontent.com/51497406/136076681-8978ce76-2db1-4b17-927f-f5f7d0b199f0.jpg)

**Comment by janvitos** [comment]
Hi,

Today I received my SIM card for this phone and realized the 3G data connection doesn't even work.

So I decided to return the phone as the Bluetooth connection seemed to disconnect intermittently and the 3G data didn't work.

Thanks @Navid200 for your help.

I will be switching to a Palm Phone PVG100, and hopefully, it will work perfectly with xDrip and the Dexcom G6.
