### ISSUE TITLE
Let the collector watch be the Sync Master

### ISSUE THREAD

**Issue by rudiruderboot** [NightscoutFoundation/xDrip#1845]
Hi, I think it would be lovely to give smartwatches with internet connectivity the ability to become the Master in xDrip Sync operations. Thus it could skip the phone as sender and would broadcast values in times the phone is turned off or out of reach. Is that technically possible?

**Comment by Navid200** [comment]
It may be
Please let's talk about it first in the Gitter room.  If what you are asking for is like asking us to change xDrip to run on iOS, even though it is a request, we will not be able to do it in this repository.

In other words, let's find out if what you are suggesting is even possible before we have feature request for it.
