### ISSUE TITLE
Option to show Master battery level on xDrip+ Sync Followers

### ISSUE THREAD

**Issue by janvitos** [NightscoutFoundation/xDrip#1848]
### Device information
* Dexcom G6
* Palm Phone PVG100
* Android 8.1
* xDrip+ Nightly 49817a5-2021.10.04

### Is your feature request related to a problem? Please describe.
My 6-year-old child has a phone with xDrip+ that is set up as a Master. My wife and I both have phones that are set up as xDrip+ Sync Followers. Since he's young and not yet able to manage his diabetes by himself, we monitor his glycemia at all times, like when he's at school or doing activities away from home. 

His phone has a small battery that sometimes doesn't last all day, and he's not good at checking the battery level before it dies. So when that happens, we get some missed readings until he notices his phone is dead and plugs it. Unfortunately, as xDrip+ Sync Followers, we cannot see the battery level of his phone to warn him. The interruption can sometimes last 30+ minutes, so if his blood sugar drops during that time, he can have hypoglycemia.

### Describe the solution you'd like
As xDrip+ Sync Followers, we'd like to be able to see the battery level of the Master device. That would be incredibly useful as we could tell our son in advance when to plug his phone. So it would be awesome if xDrip+ Sync Followers could have an option to see the battery percentage of the Master.

### Describe alternatives you've considered
We thought about setting up a low battery alert, but we'd also like to monitor the battery level as a precaution. He fiddles with his phone a lot and might accidentally put the phone in silent mode, so in case this happens, we'll be able to contact the person in charge of him and let them know he needs to plug his phone.

**Comment by tolot27** [comment]
@janvitos You are right, I've mixed it with Nightscout Follow because that's how I use it. I've tried xDrip Sync as well but it did not work for me if the master is not connected to WiFi.

> we monitor his glycemia at all times, like when he's at school or doing activities away from home.

Do you really get the data if he is not connected to a WiFi?

**Comment by inscara** [comment]
@tolot27 this is clearly not a duplicated ticket. Please, re-open it. This doesn't have to do with WiFi connection problems either, since that's not mentioned in the original ticket. This is just to make Xdrip+ more child compliant since that's something that is still missing from the market.

**Comment by tolot27** [comment]
Hmm, the Sync Master/Follower is using [Google Cloud Messaging](https://developers.google.com/cloud-messaging), which is now deprecated. Maybe, that's the reason why it does not work stable and this feature request cannot be implemented, easily.

@janvitos Please add your device models and Android versions to your initial message.

**Comment by janvitos** [comment]
> Did you have a look at the System Status Followers page? In my opinion, the battery of the master is reported

I wish I had that information as well, but I don't see it on any of my follower devices.
![Screenshot_20211012_112707_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/10037804/136985438-6303ae56-8b7e-43bf-84a8-c5b4314b0f7a.jpg)

**Comment by Navid200** [comment]
The master battery level is now shown on the follower status page as of the 2024.12.17 release.
