### ISSUE TITLE
Connecting Wixel directly to the phone usb for Dexcom G4

### ISSUE THREAD

**Issue by sarunia** [NightscoutFoundation/xDrip#185]
It will be possible with xDrip+ to add data directly from Wixel only by USB connection?
When connect Wixel to OTG USB port and use USB terminal all datas are available for Dexcom G4.
http://photouploads.com/image/TbV

**Comment by tzachi-dar** [comment]
It is possible using a program called dexterity.
What you will need to do is to connect dexterity to the usb port and have
it read the data.
That done, you need to tell xDrip to take the data form dexterity.

But do you really want to connect the wixel to a phone? How will you charge
the phone?

**Comment by sarunia** [comment]
The power for wixel is not important at the moment. Phone charging can be modified. I would like to send experimentaly data directly from wixel to xdrip+ but I can not program the application. Is it possible to switch Wixel from work to standby mode by app xdrip+ ?
thanks

**Comment by Navid200** [comment]
@sarunia Would you please close this issue if you have found an answer?
If not, would you please use the support channels?
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks

**Comment by Navid200** [comment]
Closing this for now due to inactivity.
If the issue still persists and you have found no work-around, would you please update?
