### ISSUE TITLE
Notification Channels for Android O/API level 26

### ISSUE THREAD

**Issue by jwoglom** [NightscoutFoundation/xDrip#186]
Using Android 8.0, applications must support notification channels in order for users to change the priority and importance of notifications. This would likely require upping the target SDK from 23 to 26 in order for this to be implemented, but it would be extremely useful for those on Oreo. There could also be different channels for different types of notifications, which could for instance allow a user to make low/high alerts urgent and appear on the lock screen, but persistent blood sugar data hidden and at a lower priority.

**Comment by jamorham** [comment]
I am thinking that this should be possible by changing the compile sdk version but not changing the target sdk version and using `notificationCompat` with the new instantiation method that specifies the channel id. Most of the android documentation says that we should be able to do this without invoking the extra platform restrictions that targeting sdk 26 would bring. 

As far as I know `notificationCompat` will examine the running platform version and enable the required features. They have depreciated the instantiation which doesn't include channel id and you can use this without targeting sdk 26. Quite why they don't just revert to a default channel id of the application name is beyond me, especially if not doing that results in degraded performance on Oreo.. 

https://developer.android.com/guide/topics/manifest/uses-sdk-element.html has some details but it is also wrong that it ignores the breaking changes introduced in sdk 23 relating to permissions. So I am not 100% sure it can be trusted.

The next step would probably be for me to produce a test version which implements these changes. There are often severe behavioral changes between even sub revisions of the support libraries so it is something that does need to be approached cautiously to avoid breaking other random things.

**Comment by jamorham** [comment]
I have started implementing this and upgraded the build sdk and tools. It wont solve your original problem yet but if this works then I think making the changes I detailed previously will then work.

Can you please test the 7th Oct nightly to make sure that it doesn't suffer any problems with data reception which might imply that simply changing the build sdk version is causing Android 8 restrictions to apply. You may recall that google documentation is ambiguous on this point.

**Comment by jwoglom** [comment]
Will try; is there a good way to quantitatively see whether or not there are data reception problems? (Is there a log of missed readings somewhere that I can look at?)

**Comment by jamorham** [comment]
It is possible to enable the `Extra Status Line` `capture percentage` to give you an absolute metric but I would expect that if the changes trip up the extra restrictions in android 8 then there will be quite a serious drop in performance which you will notice pretty quickly.

**Comment by jwoglom** [comment]
@jamorham I've been using the nightly for a week now on a Nexus 5X. My phone generally has a lot of issues with lag/automatic killing of background apps, but I'm currently getting a capture rate of 84% for what that's worth. I've run into a few instances where the phone has disconnected and hasn't read readings from the transmitter for about 20-30 minutes, but in I think most of those cases the official dexcom receiver lost contact with the transmitter as well, so I don't think the app or Android power saving is at fault.

Have you or anyone else tested this nightly and found any problems?

**Comment by jamorham** [comment]
I will mark this issue as resolved as the Notifications Channels support is now present in the nightlies.
