### ISSUE TITLE
Give option to save Error and Event List log file locally

### ISSUE THREAD

**Issue by simonpickering** [NightscoutFoundation/xDrip#1864]
It would be useful to be able to save the Error and Event List (3 dot menu > "View Events Log") data to a local file (as well as the current option of being able to email it [somewhere, but who knows where? :)]).

This would make it easier to share the log data in a searchable form (currently there are lots of screengrabs attached to issues) as well as letting users do their own debugging by comparing the log data and source code

**Comment by tolot27** [comment]
You can use [DB Browser for SQLite](https://sqlitebrowser.org) read the sqlite db contained in the exported zip. UserErrors is the table of interest. You can export it to CSV as well.

Indeed, this is just for experienced users feasible.

**Comment by Navid200** [comment]
The following are from developer conversations related to this request.

1- There should be an option to save the logs to a local zip file.

2- A note should be added to inform the user that there isn't much point uploading the logs before communicating with developers.  We currently ask users to use Discussions to communicate with developers.

3- There should be an emphasized warning, before save/upload,  that logs can contain sensitive information - not limited to glucose values, transmitter ids, web upload/nightscout endpoints/passwords etc and that users should only share logs privately with core developers and not post them publicly etc etc.

**Comment by Navid200** [comment]
Starting with the August 2, 2024 release, you can save logs locally.
