### ISSUE TITLE
Ability to disable calibration entries from Calibration Graph activity

### ISSUE THREAD

**Issue by simonpickering** [NightscoutFoundation/xDrip#1865]
It would be useful to be able to disable calibration values from the "Calibration Graph" screen (LHS 3-line menu > "Calibration Graph") by clicking on them and offering a dialog with the option of ignoring them.

This functionality is available from the Calibration Data Table screen, but the graphical presentation is easier (to understand what to disable) and it makes logical sense to offer the facility from both activities.

**Comment by Navid200** [comment]
https://github.com/NightscoutFoundation/xDrip/issues/720
