### ISSUE TITLE
Additional main screen graph interactions

### ISSUE THREAD

**Issue by simonpickering** [NightscoutFoundation/xDrip#1866]
Currently one can tap on finger prick blood glucose measurements and see what they are/get the option to use them for calibration. All good.

One can also tap on historic CGM data and get the time/value, as well as tapping on the prediction curve to get the same data. For both of these it would be good to add a title/blurb to say that it's either recorded CGM or modelled/projected data.

One can also click on other curves, which have different (unlisted) axes - i.e. the insulin curve and the carbohydrate on board curves (as well as others, and I've no idea what they represent!). 

These all return values in mmol/l (of mg/dl if you must), which is wrong. It would be nice to return a message saying what the curve is as well as the actual value and time pair - this would also help with people understanding what all the different curves mean.

**Comment by Navid200** [comment]
Please don't open an issue as a first step.
Please use the support channels to consult with the users and developers.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Some of the items you are asking for already exist.  
We will bring those up in the support channels as well when you use them.
