### ISSUE TITLE
Standard Notifications/Alerts that sound only ONCE

### ISSUE THREAD

**Issue by noctividus** [NightscoutFoundation/xDrip#1868]
**Problem**:
I have specific sounds for each alert. Sometimes, I'm working and an alert fires. Maybe I'm holding my baby, maybe I'm putting a kid to sleep, maybe I'm digging a hole or doing the dishes or in a meeting. I would like to hear that alert, but I don't want to hear it forever. Sometimes I can't get to my phone, unlock it, navigate to the app, press down volume, then go to the menu, click snooze, click the time, etc. 

It takes 5 steps to silence an alert-
1. Unlock Phone
2. Open App
3. Click Menu
4. Select Snooze Alert
5. Select Snooze Duration

Any diabetic will tell you that being able to quickly silence an alert is very important. Generally, when an alert fires, I want my phone to STFU as quickly as possible. 

**Desired Solution-**
Option for an alert to play an alert sound ONCE (Like every other GD notification that ever was on any phone, including those amber alerts)
Bonus- Choose how many times the sound plays before automatically silencing. 

**Alternatives I've considered-**
1. Ditching X Drip (But nothing is better)
2. Chucking my phone against a wall (But anger towards inanimate objects is pointless)
3. Making a 10 minute alert tone that has like 2 beeps up front followed by 9:55 worth of silence.
4. Pre-snoozing alerts. 

#1 and 2 are not acceptable. 
#3 is a viable alternative, but it's such a stupid way to fix a problem that shouldn't even be a problem. 
#4 kinda defeats the purpose of an alert. If I knew it was going to happen, I wouldn't need it to happen in the first place.

**Comment by Navid200** [comment]
Please don't open an issue as a first step.  How do you know if your suggestion has never already been requested before?
How do you know if the developers have not already considered your request and for a good reason decided against it?
How do you know if what you are requesting, or something close, is not already possible?

Please use the support channels as a first step:
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
https://github.com/Navid200/xDrip/discussions

**Comment by noctividus** [comment]
Well, that answers a lot of questions.

**Comment by noctividus** [comment]
Look at this perfect bug report that Navid dismissed right out the gate then went back and decided it was worth looking into-
https://github.com/NightscoutFoundation/xDrip/issues/1862

Great way to alienate people trying to help make the app better by reporting issues. Does marking issues as invalid make you look better or something? How about a non-patronizing response? 

I request that someone re-open this.

**Comment by Navid200** [comment]
There are too many open issues.  There are bugs that need to be fixed.  But, with 177 open issues, the developers are going to have a hard time going through them all to decide which one to focus on.

There are a lot of issues that are just questions.  The user community can answer many of such questions.
The support channels are frequented by the users as well as the developers.  Many users know things about xDrip that some developers don't!  Not every developer knows everything about xDrip.  But, the user community is huge.  When you use the support channels, you tap into their knowledge as well as that of the developers.

There are issues that are duplicates.   It's pointless to have redundant open issues.  Having a discussion first allows us to confirm that there isn't a related open, or closed, issue already.  The support channels are perfect for having such a discussion.  How can a user know if their request is redundant or not if we have hundreds of open issues?  

If everyone who has a request opens an issue and we leave them all open, we will end up with thousands of open issues.  How is that going to help anyone?  What would that do other than diminishing the significance of every single open issue?

We have open issues that date back to 2017.  What makes you think having an open issue is going to resolve it right away?

xDrip is maintained by volunteers.  It doesn't help to alienate anyone; neither users nor the volunteers.  
We have developers whose time is extremely valuable.   xDrip would go down the toilet if they washed their hands off the repository.  I don't want them to have to spend time looking at issues that may just be redundant or incomplete or invalid.   Their time can be used more efficiently considering that we only have a very small group of developers.

xDrip is free.  We are continuously improving it.  We are continuously supporting the user community.  
We seriously consider feature requests.
However, it is impossible to make everyone happy.  

What I asked you, which is what I ask everyone, is to please let's have a conversation first before having an issue.  After that is done, we can reopen the issue if it is the best course of action.
