### ISSUE TITLE
Compatibility w/ Medtronic Guardian Connect 4 Transmitter

### ISSUE THREAD

**Issue by phicks1** [NightscoutFoundation/xDrip#1869]
I have recently started using the new Medtronic Guardian 4 sensors & transmitter with my 670G pump. It would be great if the transmitter could be integrated directly with Xdrip.
There is a section in the transmitter manual “Open Source Software Disclosure”
This states:
“This document identifies the OSS that may be separately called, executed etc by this product”
The source / object code …can be obtained here: http://www.ouah.org/ogay/hmac/

This leads to https://github.com/ogay/hmac 

Does this help develop an interface between Xdrip & the Guardian 4 transmitter?

**Comment by Navid200** [comment]
@phicks1 Would you please have a look at the existing issue?
https://github.com/NightscoutFoundation/xDrip/issues/131
I know that it's not exactly the same device.  But, don't you think it is closely related?
Would you please add your opinion and request to that existing issue?

**Comment by phicks1** [comment]
I don't think this is a duplicate of #131 which is requesting an i/f from Guardian Connect to Xdrip
ie Guardian 3 transmitter -> Guardian Connect -> Xdrip
My issue is requesting a direct i/f 
ie Guardian 4 transmitter -> Xdrip
...using published open i/f

**Comment by tolot27** [comment]
It is a duplicate. The Guardian Connect CGM system consists of a sensor, a transmitter, a serter and the receiver (app/pump). Even if the transmitters are not compatible between 640G and 670G, they are the Guardian Connect transmitters. There is no standalone "Guardian Connect".

None of the transmitters are currently supported by xDrip.

**Comment by Der-Schubi** [comment]
@tolot27 Thats not totally right. When connected to a pump, its called Guardian Link 3, the transmitter has GL3 written on it. For use with the app only, it is called Guardian Connect 3 with GC3 on the transmitter. These two things are often mixed up.

**Comment by tolot27** [comment]
> @tolot27 Thats not totally right.

Do you mean my last statement: '"There is no standalone "Guardian Connect".'

> When connected to a pump, its called Guardian Link 3, the transmitter has GL3 written on it. For use with the app only, it is called Guardian Connect 3 with GC3 on the transmitter. These two things are often mixed up.

Does it mean that the GL3 transmitter can only connect to a pump and the GC3 transmitter can connect to a pump and to a phone app?

Thanks for the clarification. Anyway, we are talking about the Guardian Connect CGM system connectable to an app.

**Comment by Der-Schubi** [comment]
Yes, I meant your last statement.
I don't know how the connection of the app works together with newer pumps. Maybe the app connects to the pump directly.
I only have a 640G with the "old" 2.4GHz non-bluetooth Guardian 3 transmitter.
I'll switch to Guardian Connect 3 in a few weeks and run the pump without a link to the sensor, to be able to see the valuen on my phone.
Maybe I can help with integration. I don't have any experience with Android apps, but I coded on AOSP directly for many years.
