### ISSUE TITLE
Mi Band 4 + xdrip - bolus data incomplete (lack of space on Mi Band screen, unnecessary data to be removed)

### ISSUE THREAD

**Issue by twiniars** [NightscoutFoundation/xDrip#1870]
The bolus data shown on Mi band 4 is incomplete (cut). The problem lays in to short line on Mi Band, and to much data to be shown. I attach the picture. Left arrow points the missing "u" data. Right arrow points the unnecessary data. In my opinion the very simple solution to this problem is to remove the part of the info containing "at" pointed by right arrow.

![IMG_20211031_134158](https://user-images.githubusercontent.com/264535/139584161-a58685fc-fda8-41ad-8264-bbf742a3fdaa.jpg)

**Comment by nightscout-ricsi** [comment]
Have you tried [this fork](https://bigdigital.home.blog/) of Artem?

**Comment by twiniars** [comment]
As you recommended, I installed xdrip update v0.5.3(31.08.21) from https://www.patreon.com/posts/xdrip-update-v0-55564921. I realized that on space was removed between "u" and "g" values. Still, the line is incomplete due to unnecessary " at". In the real example at attached photo below, it should be 1.5u25g instead of cut .5u25g .

![IMG_20211031_225546](https://user-images.githubusercontent.com/264535/139602559-f2385b31-b854-48ae-ad34-8e63ed52356a.jpg)

**Comment by nightscout-ricsi** [comment]
You should contact Artem, he is develpong that fork, and it has not been merged here.

**Comment by tolot27** [comment]
As long as @bigdigital is not finalizing #1659 we cannot merge it and cannot do anything supporting MiBand better. Please request the changes from @bigdigital.

**Comment by nightscout-ricsi** [comment]
@bigdigital have just released a patch for this on his patreon site.
