### ISSUE TITLE
0.05 unit insulin resolution

### ISSUE THREAD

**Issue by williamohicks** [NightscoutFoundation/xDrip#1878]
I only use 19 units of Humalog per day and often do microboluses of 0.05-0.1 units since my Tandem t:Slim allows for that small of a bolus.  When I go into xDrip+ to add a treatment it allows me to enter 0.05 but displays it as 0.1.  

Any chance you guys can simply go in and reduce the resolution size for that entry?

Thank you

<img width="350" src="https://user-images.githubusercontent.com/94026030/142481381-196f714f-99eb-4921-8332-8325eca124e1.jpg" /> <img width="350" src="https://user-images.githubusercontent.com/94026030/142481384-8763251f-9d1f-43ee-8939-bd3240146d53.jpg" />

**Comment by tolot27** [comment]
Indeed, it is possible. For carbs, up to three decimal digits are shown on the top right, which does not make much sense for carbs:

<img width="350" src="https://user-images.githubusercontent.com/1370732/142738880-659b8a9e-f507-47fe-9dda-75aa09e871b8.png" />

**Comment by Navid200** [comment]
> Indeed, it is possible. 

Do you mean it is possible to use xDrip as is to do what the poster requests?
He is showing that xDrip currently rounds the second decimal point.

Or, do you mean it is possible to change xDrip to do what the poster requests?

**Comment by williamohicks** [comment]
This is for insulin boluses not carbs.

Thanks!

**Comment by tolot27** [comment]
> This is for insulin boluses not carbs. Thanks!

Yes, we know. I've just explained for some treatments there are more than one decimal points shown at some places. That means, we have to fix the decimal numbers for treatments in general.
Currently, we focus on bug fixes and implementation of unit tests. At some point, we will implement this request.

**Comment by williamohicks** [comment]
Thank you.  I can't wait to see how that will affect the predictions on insulin burn out and quantities I use.

**Comment by tolot27** [comment]
The referenced PR will fix it.

**Comment by Navid200** [comment]
@williamohicks When you get a chance, please update to the latest Nightly release, June 28, 2022.  Does it fix the problem?
