### ISSUE TITLE
Can't add insulin 

### ISSUE THREAD

**Issue by bhallnz** [NightscoutFoundation/xDrip#1881]
![Screenshot_20211127-222852_xDrip+](https://user-images.githubusercontent.com/1878485/143675876-f2297170-0ffd-4fa7-a2b8-9ed5fd9a8574.jpg)

Not ability to add a reading?

**Comment by tolot27** [comment]
Please use the support channels as described at https://github.com/NightscoutFoundation/xDrip/issues/new/choose.

You need to configure insulin before you can enter it.
