### ISSUE TITLE
Dex Share follower does not receive data (with older EU account)

### ISSUE THREAD

**Issue by Harrinator** [NightscoutFoundation/xDrip#1884]
**Subject of the issue**
Dex Share follower (using xDrip+) doesn't receive any data (worked fine for many months until November 30th). 

**Your environment**
I don't believe this is related to my hardware/settings (Android 11). It worked fine until November 30th. No changes made to hardware and Android OS.
Software: xDrip+ using Dex Share follower
xDrip+ version is: 9ff5104-2021.11.23  (has been updated today because of the described problem; previous version showed the same problem)
xDrip+ is used by me (= follower of my daughter) using "Dex Share Follower" as data source
The data is uploaded by the Dexcom G6 App (used by my daughter).

**Expected behavior**
Dex Share follower (using xDrip+) should receive data from Dex share servers.

**Actual behavior**
No data is received by xDrip+. Error message in the log file:
"Get Share Data Failed: java.lang.NumberFormatException: For input string: "Flat"
The Dexcom follow app functions normally.

**Steps to reproduce the behavior:**
Set xDrip+ to Dex Share follower with matching credentials and server.

**Comment by Navid200** [comment]
>Dex Share follower doesn't receive any data

1- Please edit your post and make it clear that you are talking about xDrip using Dex Share follower.  I am 99% sure that's what you mean.  But, let's make it as clear as possible what the follow app is (xDrip).

2- Also, please clarify what uploads to the server.

3- What happens if you use Dexcom follow app instead of xDrip?  Will it work then?

**Comment by Harrinator** [comment]
Okay, I just did. Here are my answers:
1. Yes, XDRIP+ is used by me using "Dex Share Follower" as data source ( I follow my daughter)
2. The data is uploaded by the Dexcom G6 App (used by my daughter).
3. The Dexcom follow app works fine.

**Comment by Navid200** [comment]
If you also add your points 2 (under your environment) and 3 (under actual behavior, you can add it to xDrip not working) to the first post, I can delete all my posts.  You can delete your additional posts too.  
Then, it will be easier (only one post) for the developers to get everything as fast and as easy as possible.

**Comment by Harrinator** [comment]
Dear Navid,


Okay, I will do.


Thank you for your quick reply!


Best regards,


Harald



GANEC GmbH
Dovenkamp 16
D-22952 Lütjensee



Tel:   +49 (0)4154/6025-14
Fax:  +49 (0)4154 6025-16
E-Mail: ***@***.***
Webseite: http://www.ganec.de
WebShop: http://www.ganec-shop.de

Geschäftsführer: Harald Hiß


Amtsgericht Lübeck, HRB 9566 HL
Umsatzsteuer-Identifikationsnummer: DE 267 509 966
Sitz der Gesellschaft: Trittau




Original Message processed by david® 
Re: [NightscoutFoundation/xDrip] Dex Share follower does not receive data (with older EU account) (Issue #1884) 1. Dezember 2021, 04:57 Uhr 
Von Navid 
An NightscoutFoundation/xDrip 
Cc (2) Harrinator|Author 


If you also add your points 2 (under your environment) and 3 (under actual behavior, you can add it to xDrip not working) to the first post, I can delete all my posts. You can delete your additional posts too.
Then, it will be easier (only one post) for the developers to get everything as fast and as easy as possible.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 

To: ***@***.***
    ***@***.***
Cc: ***@***.***
    ***@***.***


-- 
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by Navid200** [comment]
Is the user name an email address?

**Comment by tolot27** [comment]
This issue is not related to the user name. It looks like Dexcom changed the BG arrow indicator value from a number to a string because the following exception is raised:

```
Get Share Data Failed:
java.lang.NumberFormatException: For input string: "Flat"
```

**Comment by Harrinator** [comment]
No. It is a "normal" name (only characters).






GANEC GmbH
Dovenkamp 16
D-22952 Lütjensee



Tel:   +49 (0)4154/6025-14
Fax:  +49 (0)4154 6025-16
E-Mail: ***@***.***
Webseite: http://www.ganec.de
WebShop: http://www.ganec-shop.de

Geschäftsführer: Harald Hiß


Amtsgericht Lübeck, HRB 9566 HL
Umsatzsteuer-Identifikationsnummer: DE 267 509 966
Sitz der Gesellschaft: Trittau
o




Original Message processed by david® 
Re: [NightscoutFoundation/xDrip] Dex Share follower does not receive data (with older EU account) (Issue #1884) 1. Dezember 2021, 06:12 Uhr 
Von Navid 
An NightscoutFoundation/xDrip 
Cc (2) Harrinator|Author 


Is the user name an email address?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 

To: ***@***.***
    ***@***.***
Cc: ***@***.***
    ***@***.***


-- 
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by Harrinator** [comment]
Okay, I see. So then other user are affected, too? What can be done to solve the problem?








Original Message processed by david® 
Re: [NightscoutFoundation/xDrip] Dex Share follower does not receive data (with older EU account) (Issue #1884) 1. Dezember 2021, 07:00 Uhr 
Von Mathias Walter 
An NightscoutFoundation/xDrip 
Cc (2) Harrinator|Author 


This issue is not related to the user name. It looks like Dexcom changed the BG arrow indicator value from a number to a string because the following exception is raised:
Get Share Data Failed:
java.lang.NumberFormatException: For input string: "Flat"
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 

-- 
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by SBee76** [comment]
I've also had this issue. Have not received data from dexcom share for 798 minutes. It is currently 17:04 AEST , 1 December, 2021. 
![Screenshot_20211201-170310_xDrip+](https://user-images.githubusercontent.com/74168666/144187490-a4987379-ca1e-43e1-ab5e-21f7238c7815.jpg)

I have not had any issues with receiving data from dexcom share before. I've sent through an error log via the xdrip app also.

**Comment by tolot27** [comment]
@Harrinator You cannot do anything except waiting until we have fixed this issue in xDrip. I've explained the root of the issue already in https://github.com/NightscoutFoundation/xDrip/issues/1884#issuecomment-983315112.

It is unlikely that a solution will be available before tonight (20:00 CET). Hence, please be patient.

**Comment by andersgb1** [comment]
> @Harrinator You cannot do anything except waiting until we have fixed this issue in xDrip. I've explained the root of the issue already in [#1884 (comment)](https://github.com/NightscoutFoundation/xDrip/issues/1884#issuecomment-983315112).
> 
> It is unlikely that a solution will be available before tonight (20:00 CET). Hence, please be patient.

Tonight at 20? That's damn fast and impressive! Thanks for fixing it.

**Comment by Harrinator** [comment]
> @Harrinator You cannot do anything except waiting until we have fixed this issue in xDrip. I've explained the root of the issue already in [#1884 (comment)](https://github.com/NightscoutFoundation/xDrip/issues/1884#issuecomment-983315112).
> 
> It is unlikely that a solution will be available before tonight (20:00 CET). Hence, please be patient.

Thank you for you quick answer. A fix until this evening is much faster than I had expected. That is indeed very impressive. Thank you very much. xDrip is a great solution. I appreciate your work and efforts.

**Comment by bjornoleh** [comment]
> This issue is not related to the user name. It looks like Dexcom changed the BG arrow trend indicator value (slope) from a number to a string because the following exception is raised:
> 
> ```
> Get Share Data Failed:
> java.lang.NumberFormatException: For input string: "Flat"
> ```

Thanks for looking into this. I suppose you are aware of the potential solution they are working on for NS?

https://github.com/nightscout/share2nightscout-bridge/pull/51

**Comment by SBee76** [comment]
> @Harrinator You cannot do anything except waiting until we have fixed this issue in xDrip. I've explained the root of the issue already in [#1884 (comment)](https://github.com/NightscoutFoundation/xDrip/issues/1884#issuecomment-983315112).
> 
> It is unlikely that a solution will be available before tonight (20:00 CET). Hence, please be patient.

Thanks. Just heard from a friend who actually spoke to AMSL (Dexcom Australia) today and apparently they did a big update and their servers have been down all day. Unsure if this is useful information for anyone, but thought I should mention it. My above post was also me just trying to offer information, as I can't help in any other way. I've always been happy to wait.

**Comment by RayJayVaughn** [comment]
I got the same issue. The issue occured Nov 30th in the evening.

I do suspect Dexcom having caused this by a change or incident within their environments.

At the same time xdrip lost the connection my original Dexcom app went down and was not usable anymore showing 'your device is not compatible' although it was officially declared as being compatible by dexcom. They seemed to have an serious incident which lasted at least one or two hours. Had to reinstall everything several times.

Dexcom service calling me today admitting they had an incident. 

Now the Dexcom app works again. The xdrip one does not.

Hope this information might help fencing it.

**Comment by savek-cc** [comment]
I think it's not only the follower function but also the uploading to dexcom servers from within xDrip+?

**Comment by Jorge-1234** [comment]
I have the same problem. Dexcom share does not Work with xdrip. SOS

**Comment by Navid200** [comment]
@Jorge-1234 
Please stop flooding this issue with help requests.  It doesn't help.  It only makes it harder for developers to get the info they are looking for, which is all contained in the very first post.

You can post in the discussions if you like to chat and share experiences and talk about alternatives while waiting for this to be fixed:
https://github.com/Navid200/xDrip/discussions/130

**Comment by tolot27** [comment]
> I think it's not only the follower function but also the uploading to dexcom servers from within xDrip+?

I believe it is just the following function because now I can receive the old values sent from xDrip.

**Comment by Harrinator** [comment]
Thank you very much for fixing this problem so fast! I am very grateful. Just one question: where can I download the fixed version?

**Comment by Navid200** [comment]
@Harrinator https://github.com/Navid200/xDrip/wiki/Download-xDrip

**Comment by Harrinator** [comment]
Thank you very much! 

To: ***@***.***
    ***@***.***
Cc: ***@***.***
    ***@***.***


-- 
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by samgray85** [comment]
Hi

I am also having this issue.

I use Decom Share on Samsung S10.

It stopped working along with everyone else last week

I installed the Dec 2 update, made no other changes. This is the error that results

I have an email address for a username

![dexcomerror](https://user-images.githubusercontent.com/86637332/144978899-215de129-3945-42d2-8462-f6e444c66645.png)
![dexcomerror2](https://user-images.githubusercontent.com/86637332/144978908-b15551dd-7cba-49aa-99fd-45cbe34894ef.png)
![dexcomerror3](https://user-images.githubusercontent.com/86637332/144978911-054becbe-567a-4ded-b09b-238910475329.png)
![dexcomerror4](https://user-images.githubusercontent.com/86637332/144978916-9844fe23-f766-429d-ad81-012a8cf81f7c.png)
