### ISSUE TITLE
Get Share Data Failed: java.io.EOFException: End of input at line 1 column 1 path $

### ISSUE THREAD

**Issue by fzelins** [NightscoutFoundation/xDrip#1886]
### Subject of the issue
xDrip is not getting any data from Dex Share servers. It was working fine till they updated website, now after that even newest xDrip version does not work for me. 

### Your environment
- What version of xDrip: efb7508-2021.12.02
- What type of hardware data source and how do you get your data there: data source is DexShare, using dexcom app
- Is your issue specific to a device like and Android phone or a smartwatch? I guess no, seting up follower on other phone with same xdrip version throws same error. 

### Expected behavior
xDrip should be getting data from DexShare servers

### Actual behavior
xDrio is not getting any data from DexShare servers, and just throwing error: Get Share Data Failed: java.io.EOFException: End of input at line 1 column 1 path $

**Comment by Navid200** [comment]
Please don't open an issue as a first step as you can see in the directions.

**Comment by Navid200** [comment]
Please consult with us first.
https://github.com/NightscoutFoundation/xDrip/blob/master/.github/ISSUE_TEMPLATE/bug-report.md

**Comment by tolot27** [comment]
Duplicate of #1297
