### ISSUE TITLE
Number wall on lock screen causing other apps to restart

### ISSUE THREAD

**Issue by CountScotula** [NightscoutFoundation/xDrip#1891]
External Android apps appear to restart at the precise Xdrip+ polling interval. (Chrome web content refreshes, clearing unsubmitted input fields; social media feeds refresh to the top of the scroll; YouTube videos stop and reset to the beginning; etc.)

Observed after I migrated to a new phone. Current specs:

Google Pixel 6 Pro
Android 12 (5 Nov 2021 update) build number SD1A.210817.037.A1
Xdrip+ nightly build version efb7508-2021.12.02
Collectors for Dexcom G6 on which behavior was observed: 640G/EverSense, Dexcom Share

The full narrative of the behavior observed was reported first in [this discussion thread](https://github.com/Navid200/xDrip/discussions/150).

**Comment by Navid200** [comment]
Suggestion from @jamorham: 

If apps are being interrupted generally when xDrip is doing something then I would expect it is memory pressure. If the user has a large number of historical readings they could enable the data retention settings to automatically prune the database and see if that helps.

**Comment by CountScotula** [comment]
Thanks for passing on that suggestion, but I don't think limiting the history will help in this instance. This is a new phone (Pixel 6 Pro) and so it's a relatively new install of Xdrip+. The history only goes back to November 9, 2021. And I first noticed this behavior ... oh, about a week after that date.

**Comment by Navid200** [comment]
@CountScotula So, when you installed xDrip on this phone, you did not restore a database from your previous installations on your previous phones?

**Comment by CountScotula** [comment]
@Navid200 I did not. I use Xdrip+ mainly for display on my watch and for its predictive features that seem more useful to me than my OmniPod bolus calculator. So, I only backed up and restored my settings from the old installation, not the db.

**Comment by Navid200** [comment]
What apps have you installed on the phone other than xDrip?

I mean no matter how powerful your phone is, if you install enough apps on it, you can bring it to its knees.

**Comment by CountScotula** [comment]
Oh, very many. But fewer than on my Pixel 4 that preceded it with 6GB RAM. The Pixel 6 Pro has 12GB RAM. I really really don't think this is a resources problem. Remember too, I'm *only* seeing this happen when Xdrip+ polls. If I was blowing it out, I'd see this with many more intensive operations.

**Comment by Navid200** [comment]
There are other xDrip users who are using that same phone.

Sometimes, it's very easy to identify the cause of a problem.
But, that's not always the case.  Then, the only thing left to do is to suspect everything.

Considering there are other users who are using that phone with xDrip, I suspect you have an app that is the cause of the problem.
My suggestion is meant to help us identify that app.

**Comment by CountScotula** [comment]
Oh, I understand that. I'm just doubting the idea that the *number* of apps aren't bringing my phone "to its knees."

Presumably if it were a particular app, it would be one that the permission to run in the background, yes? As I understand Android, apps without this permission are held in stasis when not active. Would it be useful to know which apps on my phone have that permission?

**Comment by drudeboy** [comment]
I came across this through Google. Pixel 5 with the same issue since the Android 12 update.
Every time xdrip polls Facebook or Web browser refreshes.

**Comment by tolot27** [comment]
I cannot image xDrip is the root cause of this behavior because xDrip does nothing special. Maybe, this is caused by the Bluetooth stack. Can anyone connect it to a computer and use logcat to monitor what happens?

**Comment by teamoth** [comment]
I'm just commenting to say that I'm also experiencing this issue on a Pixel 4a running Android 12 and xDrip+. I have barely any other apps on the phone. This definitely isn't a lack of resources issue. I have xDrip+ working with Freestyle Libre, miaomiao and Miband4 watch. It's got so bad that I am now carrying 2 phones, an old Pixel 1 for xDrip etc and my 4a for everything else. Someone on the xDrip Facebook page pointed me this way. It's nice to see that I'm not the only one with this issue! Tim

**Comment by Navid200** [comment]
| Who | Phone | Android | xDrip |  
|-------|--------|----------|-------|  
| @CountScotula | Pixel 6 pro | 12 | 2021.12.02 |  
| @drudeboy |Pixel 5 | 12 | |  
| @teamoth | Pixel 4a | 12 | |

**Comment by teamoth** [comment]
Thanks for doing that table. I've been trying various recent versions and they all have this issue. The latest I tried is: 2022-01-15
As there is some interest in this issue I'll switch back to using the 4a with xDrip+ again and endure the annoyance. Maybe I can help with some testing or something.

**Comment by michaelrdix** [comment]
Wow I've been experiencing this issue ever since getting my Pixel 6.  I always figured it was a bug in the new Android 12 system.  But I would post on reddit and could never really find anyone else having the issue.

If it is Xdrip causing this, it would explain why a lot of people aren't.

I think we can rule out Bluetooth as the issue because my Bluetooth is never enabled.  I use Xdrip with the Dexcom Share setting.

**Comment by teamoth** [comment]
Hi michaeld427. As I understand it from googling a while ago, this issue occurs with Dexcom as well as xDrip+. By that I mean that people solely using Dexcom (not in combination with xDrip+) are experiencing this, so in your case it may be Dexcom that is causing the issue. I was fairly certain this was a Bluetooth issue, but as I have no experience with Dexcom, I'm not aware of what communication protocol that uses.

**Comment by michaeld427** [comment]
> Hi michaeld427. As I understand it from googling a while ago, this issue occurs with Dexcom as well as xDrip+. By that I mean that people solely using Dexcom (not in combination with xDrip+) are experiencing this, so in your case it may be Dexcom that is causing the issue. I was fairly certain this was a Bluetooth issue, but as I have no experience with Dexcom, I'm not aware of what communication protocol that uses.

The G6 app is on another phone that my son keeps on him.  I use Xdrip on my phone.  This issue is occurring when Xdrip polls Dexcom via Share.

**Comment by tolot27** [comment]
> I think we can rule out Bluetooth as the issue because my Bluetooth is never enabled.

Does it also occur if you disable Dexcom Share (set hardware data source to "Disable Collection")?

**Comment by michaeld427** [comment]
> > I think we can rule out Bluetooth as the issue because my Bluetooth is never enabled.
> 
> Does it also occur if you disable Dexcom Share (set hardware data source to "Disable Collection")?

Good idea, interesting result.  So I did this and the issue still occurred.  However it did not correspond with the reading times (which right now occurs on the XX:X2 and XX:X7 minutes) as it has been doing.  Instead it did it about 2 minutes late (XX:X4).  However I still believe that it is related to something Xdrip is doing.  This is because the app restart issue corresponded with a BG Radings Missed alert.  So even though there was no data source selected, it still triggered that alert, so it was doing something.

**Comment by michaeld427** [comment]
I Uninstaller Xdrip and installed Dexcom Follow.  I had that setup for 2 hours and experienced no issues.  I was using it a lot and certainly would have.

I reinstalled Xdrip and it started happening shortly after again.

I also tried disabling all the Bluetooth options in Xdrip (even though it shouldn't have tried to use them), but that had no effect.

**Comment by tolot27** [comment]
Is there any chance that you can connect your mobile to a PC and run adb logcat?

**Comment by michaeld427** [comment]
> Is there any chance that you can connect your mobile to a PC and run adb logcat? Where do you live? It would be really nice to debug this.

I'm not familiar with that, but if you could give me instructions I can do it tomorrow.

Do I need to be doing it while the issue occurs?

Does it share any sensitive information?

**Comment by tolot27** [comment]
> > Is there any chance that you can connect your mobile to a PC and run adb logcat? Where do you live? It would be really nice to debug this.
> 
> I'm not familiar with that, but if you could give me instructions I can do it tomorrow.

A good install instruction is provided at [How to Install and Collect ADB logs on android device](https://support.citrix.com/article/CTX232375). I assume you running Windows, correct?

Afterwards, you need to open a command line window and execute the following commands:

With `adb shell pidof 'com.eveningoutpost.dexdrip'` you determine the process identifier (PID) of xDrip. Afterwards, please execute `adb logcat --pid=<pid> -d > xdriplogcat.log` but replace <pid> with the previously defined PID. This will dump the last log entries to a file named xdriplogcat.log in the current folder (as can be seen on the command line). Please send me this file via Gitter or drop it here.
Also, please list the exact time (of your mobile) when the issue occurred.

> Do I need to be doing it while the issue occurs?

No, logcat fetches the log entries from a 2 MB ring buffer. About one hour log entries should fit into it.

> 
> Does it share any sensitive information?

No, it does not. Just the log entries xDrip produces. If you enable Dexcom Share, also the BG values will be logged.

**Comment by michaeld427** [comment]
> > > Is there any chance that you can connect your mobile to a PC and run adb logcat? Where do you live? It would be really nice to debug this.
> > 
> > 
> > I'm not familiar with that, but if you could give me instructions I can do it tomorrow.
> 
> A good install instruction is provided at [How to Install and Collect ADB logs on android device](https://support.citrix.com/article/CTX232375). I assume you running Windows, correct?
> 
> Afterwards, you need to open a command line window and execute the following commands:
> 
> With `adb shell pidof 'com.eveningoutpost.dexdrip'` you determine the process identifier (PID) of xDrip. Afterwards, please execute `adb logcat --pid=<pid> -d > xdriplogcat.log` but replace with the previously defined PID. This will dump the last log entries to a file named xdriplogcat.log in the current folder (as can be seen on the command line). Please send me this file via Gitter or drop it here. Also, please list the exact time (of your mobile) when the issue occurred.
> 
> > Do I need to be doing it while the issue occurs?
> 
> No, logcat fetches the log entries from a 2 MB ring buffer. About one hour log entries should fit into it.
> 
> > Does it share any sensitive information?
> 
> No, it does not. Just the log entries xDrip produces. If you enable Dexcom Share, also the BG values will be logged.

File attached.  When the issue occurred, the time on my phone was 8:43.
[xdriplogcat.log](https://github.com/NightscoutFoundation/xDrip/files/8117112/xdriplogcat.log)

**Comment by michaeld427** [comment]
Here is that full log with Dexcom still enabled.  I will send another one
next time with it disabled.

**Comment by michaeld427** [comment]
10:33 is about when the app restarted.  It was Chrome in this case.

**Comment by michaeld427** [comment]
xdrip id is 17806

I had all other apps swiped closed except for Xdrip and Brawl Stars.  Restart occurred at about 13:08.

[xdriplogcat_michaeld427_dexshareDisabled_AlertsSnoozed.log](https://github.com/NightscoutFoundation/xDrip/files/8119171/xdriplogcat_michaeld427_dexshareDisabled_AlertsSnoozed.log)
.

**Comment by michaeld427** [comment]
I don't think I had Dexcom Share disabled last file.  This new one has data source disabled and all alerts snoozed.  Restart occurred just a bit after 14:27 (I counted to 45 before the time changed to 14:28)
[xdriplogcat_michaeld427_dexshareDisabled_AlertsSnoozed2.log](https://github.com/NightscoutFoundation/xDrip/files/8119653/xdriplogcat_michaeld427_dexshareDisabled_AlertsSnoozed2.log)
.

**Comment by tolot27** [comment]
Okay, thanks so far. One last test. Please save your settings and uninstall/reinstall xDrip. Please do not import existing database or load settings. Just disable hardware source. Does other apps still crash frequently? If yes, please provide that last log with the new PID. Before you do the test, please increase the logcat ringbuffer size with `adb logcat -b main -G 5M`.
Afterwards, you can load your previously saved database/settings.

**Comment by michaeld427** [comment]
> Okay, thanks so far. One last test. Please save your settings and uninstall/reinstall xDrip. Please do not import existing database or load settings. Just disable hardware source. Does other apps still crash frequently? If yes, please provide that last log with the new PID. Before you do the test, please increase the logcat ringbuffer size with `adb logcat -b main -G 5M`. Afterwards, you can load your previously saved database/settings.

Right now I am testing with the "Allow interruptions" notification option turned off.  So far, I have not had any crashes, so fingers crossed.  Could be related to that somehow?  Like the interruption is interrupting the apps?  I'm going to leave it this way for a while and see if this issue truly has gone away.

I have already installed Xdrip from scratch as well.  I actually factory reset my phone, without restoring any data (cause others said sometimes restoring data during a new phone can cause issues) and without restoring any app backups (within the apss like Xdrip allows).

**Comment by michaeld427** [comment]
> It is a valid trace to look for the interruption settings. 😄 Please can you post a screenshot of the setting you've turned off? I've found the following options:
> 
> <img alt="" width="350" src="https://user-images.githubusercontent.com/1370732/155226856-4abdcb9f-cdb4-4e65-8125-bc08617efbf7.png">
> 
> It would be good to know if you have this options on also for Reminders or Calendar events and test if one of these events would also crash your currently opened app.

![Screenshot_20220222-170708](https://user-images.githubusercontent.com/76007398/155227861-bf6c59c2-8514-49c8-83fb-27657cd3b03e.png)

**Comment by michaeld427** [comment]
Here's my screen similar to the one you posted. 
![Screenshot_20220222-171004](https://user-images.githubusercontent.com/76007398/155228137-8641f4a6-2fa7-47fe-a02c-f63880c9bb45.png)

**Comment by michaeld427** [comment]
It seems turning that option off does indeed stop the issue from happening.  I have that option enabled normally because I want to make sure that no alerts are missed ever.  I don't think it is normal that it would force other apps to restart (especially when Xdrip isn't alerting anything).

**Comment by tolot27** [comment]
@michaeld427 Thanks for finding the correlation with the notification interruptions. Please can you test what I mentioned in https://github.com/NightscoutFoundation/xDrip/issues/1891#issuecomment-1048255839? Try an SMS receive as well. xDrip should be not running during this test.

**Comment by michaeld427** [comment]
> @michaeld427 Thanks for finding the correlation with the notification interruptions. Please can you test what I mentioned in [#1891 (comment)](https://github.com/NightscoutFoundation/xDrip/issues/1891#issuecomment-1048255839)? Try an SMS receive as well. xDrip should be not running during this test.
> 
> Rationale is to find out if the phone has a general problem with interrupting notifications.

SMS notifications have never caused an issue for me.  I just tested a calendar event and a reminder, neither of which caused an issue.

**Comment by tolot27** [comment]
Do you have the "Notification Channels Use the Android 8+ notification channel feature." enabled in "Alarms and Alerts" -> "Glucose Alerts Settings"? Please can you switch this option and try if it helps if alarm interruptions are enabled?

**Comment by michaeld427** [comment]
I thought I posted this before, but I guess I didn't.  So after switching off the Allow interruptions and Override Do Not disturb, as I expected... I wasn't getting properly alerted during the night because of those settings.  So, I turned those options back on because I'd rather deal with the issue than miss alerts for our son.  The funny thing is after turning those options back on, the issue never came back.

So, either just toggling that option off and on apparently resolved the issue... or it is possible there was another setting in Xdrip that maybe I changed that resolved it.

I did test turning off that option you last mentioned and either way I had it, it didn't cause the issue to reappear.

**Comment by CountScotula** [comment]
I've been following all this troubleshooting you folks have been doing and decided to follow along a bit myself, uninstalling everything, reinstalling, and re-setting my config option-by-option. I think I found what was causing the issue ... for me, at least.

It seems to be the **Number Icon in Notification Area** options in **Display Settings**. This used to work just fine on my Pixel 4 and I think I ported the settings over to my Pixel 6. And when I tested the settings on my Pixel 6, it always did the **123** display thing as expected, so I never thought much about it. But the display didn't reliably "stick". And now that I've disabled the setting, I am not seeing any crashing of other apps whatsoever.

I did also disable the **Number Wall on Lock Screen** option too and haven't bothered to turn it back on, so there is a small chance this could be involved. But my money is still on the notification area option.

It's a little misleading to suggest that if the test "passes," one can use the notification area option without issue, so it may be wise to rethink how this setting works. But AFAIC, my issue is resolved.

**Comment by michaeld427** [comment]
I am using the Number Icon in the Notification Area currently without issue.  I did notice that I currently do not have the Number Wall on Lock Screen enabled, which I normally do.  I will test turning that back on and see if that causes the issue to come back.

**Comment by tolot27** [comment]
@CountScotula Thanks for reporting your findings. Do other apps crash again, if you enable **Number Icon in Notification Area**? Or asked another way, can you reproduce the crashes?

**Comment by michaeld427** [comment]
After turning Number Wall on Lock Screen back on, I immediately started getting the crashes again.

**Comment by CountScotula** [comment]
Oh, how interesting. I did not see crashes with the number in the notification, so I turned that back **off** and turned the lock screen option **on**. And I _still_ didn't see crashes.

And then I turned them both on. No crashes yet. So I've no idea at this point. I'll leave them both on for a while though and see if it returns.

**Comment by CountScotula** [comment]
Okay, the restarts showed up with both options on. So then I disabled the notification area option. Still saw crashes with just Lock Screen, like @michaeld427 sees. And then I reversed it so just Notification Area was on. No crashes.

So yeah. I think that's where the issue lies. Lock Screen. Darn. That was a useful feature.

**Comment by michaeld427** [comment]
I'm just glad we narrowed it down.  I can live without that for now.  I was getting close to getting a new phone because the crashes were driving me crazy.

I believe it was also interfering with my third party launcher as well.  I always assumed they were 2 separate issues.  But I use Nova Launcher and quite often using the app switcher button, it would just get extremely flaky.  Freeze up for several seconds and then sometimes just completely stop working (I'd have to either reboot the phone or kill the Pixel Launcher specifically).  Since the app crashes have stopped, I don't think this issue is occurring anymore either.  So, I think the issue was also maybe "restarting the launcher" which technically is an app.

**Comment by teamoth** [comment]
Disabling the "Number Wall On Lock Screen" has fixed this issue for me on my Pixel 4A with Miaomiao and Freestyle Libre! Thanks for sussing this out! So nice not to have my Pixel apps reloading all the time. 👍

**Comment by Navid200** [comment]
@CountScotula Would it make sense to change the title to something like the following?  
And regardless, thanks for figuring out what the cause was.
  
"Number Wall on Lock Screen causing other apps to restart

**Comment by Navid200** [comment]
We may be able to find out why this happens and solve it.  So, I would like to keep this open please.  Please let me know if I am overlooking something in that respect.

**Comment by mkitchingh** [comment]
Just wanted to add, I experience this too. I decided to to spend some time today focusing on what was causing it. For me, it force closes clash of clans and clash royal. It also causes the camera to quit recording if you have are actively recording. I narrowed it down to only occurring when xDrip+ refreshes. This is a new Pixel 6 pro with plenty of free resources. It happened on my previous Pixel 4XL as well. It started on that phone when I upgraded to Android 12.

**Comment by michaeld427** [comment]
> Just wanted to add, I experience this too. I decided to to spend some time today focusing on what was causing it. For me, it force closes clash of clans and clash royal. It also causes the camera to quit recording if you have are actively recording. I narrowed it down to only occurring when xDrip+ refreshes. This is a new Pixel 6 pro with plenty of free resources. It happened on my previous Pixel 4XL as well. It started on that phone when I upgraded to Android 12. I have no disabled the lockscreen feature.

Did you try disabling the lockscreen number display? That is what we have found to be causing it.

**Comment by mkitchingh** [comment]
> Did you try disabling the lockscreen number display? That is what we have found to be causing it

I just did after finding this post. I had a typo in my comment. It should have said "I have now disabled the lockscreen feature". I will confirm it fixes it, but I definitely had this exact issue. It has been bugging me for a long time, and I decided to sit down today and really troubleshoot.

**Comment by mkitchingh** [comment]
Any news on this issue? Any hope for a fix?

**Comment by Navid200** [comment]
@mkitchingh Only developers who have a Pixel phone can work on this.  We already have a shortage of active developers.  This additional restriction does not help.

**Comment by mkitchingh** [comment]
> @mkitchingh Only developers who have a Pixel phone can work on this. We already have a shortage of active developers. This additional restriction does not help.

Got it. I was just checking. I didn't know this was an issue that was unique to Pixel phones. If it would help, I would be willing to donate and used pixel to the cause. I would just need to know what the oldeest acceptable model would be.

**Comment by mkitchingh** [comment]
Here's the easiest way. Have it set to pull data from Dexcom share. Play clash of clans, and have a active game while the lock screen does the 5 minute refresh.

**Comment by jamorham** [comment]
@mkitchingh and what problem is seen when the 5 minute refresh happens?

**Comment by Navid200** [comment]
@CountScotula Can you answer JamOrHam?

**Comment by mkitchingh** [comment]
> @mkitchingh and what problem is seen when the 5 minute refresh happens?

Sorry. I was offline most of yesterday. 100% agree with @michaeld427 answer.

**Comment by jamorham** [comment]
So testing with Pixel 4 XL. I have Numberwall enabled for lockscreen and I have an active game of Clash of Clans for 20+ minutes and I don't see any interruption or crash. If I lock the phone the lockscreen has the correct value there. I haven't been able to reproduce the issue yet.

**Comment by mkitchingh** [comment]
> So testing with Pixel 4 XL. I have Numberwall enabled for lockscreen and I have an active game of Clash of Clans for 20+ minutes and I don't see any interruption or crash. If I lock the phone the lockscreen has the correct value there. I haven't been able to reproduce the issue yet.

Can you confirm the Android OS version? It didn't start on my 4 XL until I updated to Android 12. I will try to reproduce on my 7 pro.

**Comment by michaeld427** [comment]
I stopped using it back when the issue was discovered (last March).  I turned it back on a bit ago to see if there was any more information I could provide.  So far it has not happened yet.

**Comment by jamorham** [comment]
@mkitchingh Pixel 4 XL is on Android 13 in this test.

**Comment by mkitchingh** [comment]
I had it 100% of the time on Android 12. I am not currently able to reproduce it on Android 13. I will keep testing, but it seems it could be resolved.

**Comment by mkitchingh** [comment]
I believe this issue has been resolved.

**Comment by Navid200** [comment]
> I believe this issue has been resolved.

Music to my ears!

We can always reopen if needed.
Thanks
