### ISSUE TITLE
Add label to widget (and main screen)

### ISSUE THREAD

**Issue by savek-cc** [NightscoutFoundation/xDrip#1894]
When using one phone to monitor the BG of multiple persons (e.g. 2 children), it would be nice to be able assign each a label (e.g. Name) - and also have this label visible on the xDrip main screen and startscreen widget.
(Using xDrip-Variants in this szenario)

**Comment by Navid200** [comment]
Please open a discussion (https://github.com/Navid200/xDrip/discussions), as you were asked to do when you were opening this issue, and I will then explain the existing options in the discussion.
Please don't open an issue as a first step as you were asked not to do.

**Comment by savek-cc** [comment]
For anyone finding this in the search - followup at https://github.com/Navid200/xDrip/discussions/159
