### ISSUE TITLE
[LEMFO LEMP 9.1] Unable to start Bluetooth Service (Dexcom / MiaoMiao / Bubble)

### ISSUE THREAD

**Issue by parapenT1sta** [NightscoutFoundation/xDrip#1895]
A friend of mine bought a LEMF LEMP with Android 9.1 hoping was going to work like the previous models running Android 7.1.1 with MiaoMiao and Bubble but in fact he is unable to use it.
xDrip cannot start the Bluetooth Service, at least it seems. Since I have Dexcom, I tried to connect Dexcom on xDrip and the same issue, tried all settings, then I installed Dexcom Built Your Own App and it connects with no issue.

xDrip with Dexcom: Phone Service State: Service Stopped
xDrip with Bubble or MiaoMiao: Phone Service State: Full Service Stopped

Is anything that I can debug for further investigation or this is a case where nothing can be done? 

![PXL_20211222_133826035](https://user-images.githubusercontent.com/608650/147102779-961e657b-9ce6-4d9e-a91c-1c7c4593d19c.jpg)
![PXL_20211222_133001731](https://user-images.githubusercontent.com/608650/147102784-154e6b2d-1703-4b59-9af8-de87e095e7d6.jpg)
![PXL_20211222_132054744](https://user-images.githubusercontent.com/608650/147102786-a33e572c-86d7-4f47-b9fc-8e59b586e053.jpg)

**Comment by Navid200** [comment]
Any issue opened before discussing with developers will be closed right away.

https://github.com/Navid200/xDrip/discussions

**Comment by parapenT1sta** [comment]
Ok !
Close it! :-D

**Comment by parapenT1sta** [comment]
https://github.com/Navid200/xDrip/discussions/161

**Comment by parapenT1sta** [comment]
Just adding this information for future reference:
I think I found the issue running the extra logging Ob1G5CollectionService:v, just let me know if it helps, this is the only information I could get. It seems this Full Android 9.1 Watch is detected as an Android Wear (this option is disabled on xDrip) or is not related? 

Can you provide me the extra logging tag for Libre Bluetooth service? If there is any to compare the information.

![PXL_20211224_000513351_2](https://user-images.githubusercontent.com/608650/147301511-4895844f-7c7b-47df-9779-a078b966642f.jpg)

![PXL_20211224_000520661 MP](https://user-images.githubusercontent.com/608650/147301543-835284ba-4ad2-4fd2-919a-e982e249c451.jpg)

![PXL_20211224_000534290](https://user-images.githubusercontent.com/608650/147301521-aedd7059-3ca9-4e57-9540-800fc2b2cfbf.jpg)
