### ISSUE TITLE
Watch Face Not allowing me to toggle on alerts?

### ISSUE THREAD

**Issue by musashiasano** [NightscoutFoundation/xDrip#1896]
![watch](https://user-images.githubusercontent.com/53202739/147197749-40ab9a6d-7595-4b7e-9b18-7528f815e46f.jpg)

Hi there, I recently bought a Samsung Watch 4 and used the method below to get the Xdrip Watchface on it. 

https://www.youtube.com/watch?v=EV0sakMFLEQ

I basically use Wear Installer and enable ADB to force it on there. Anyway, as you can see from the image for some reason I can't enable alerts. Everything else seems to work fine except for this. It's just greyed out. Is there anything I can do to enable this?

**Comment by Navid200** [comment]
Please don't open an issue as a first step.
![Screenshot 2021-12-23 081139](https://user-images.githubusercontent.com/51497406/147245444-deeb64bd-5b50-491c-b616-4ec52d5ffbfe.png)

Please use discussions instead:
https://github.com/Navid200/xDrip/discussions
