### ISSUE TITLE
Session start failed: clock not synchronized or other error

### ISSUE THREAD

**Issue by SuperTone** [NightscoutFoundation/xDrip#1927]
Good afternoon. The dexcom g6 sensor stopped. I couldn't launch it.
In the "event log" I found the error "Session start failed: clock not synchronized or other error"
I tried restarting the sensor and even performing a hard reset of the transmitter, but to no avail. 5 minutes after the start, it gives a message that the sensor is stopped and offers to start (and so on in a circle)
Then I changed the sensor to a new one - the same mistake.

Has anyone encountered this problem?

hdrip+ (Last updated Nov 2021)
samsung s10+ (android 11)

![photo_2022-01-11_17-27-02](https://user-images.githubusercontent.com/1871587/148961537-3b0d7d74-db49-4850-8340-d313ce4bbc63.jpg)
![photo_2022-01-11_17-27-17](https://user-images.githubusercontent.com/1871587/148961542-34e7cab6-d8fb-4cf2-8575-01b52fa2c199.jpg)
![photo_2022-01-11_17-27-23](https://user-images.githubusercontent.com/1871587/148961543-a0c4f66a-2f94-467a-b5b5-a074617aaae4.jpg)
![photo_2022-01-11_17-27-27](https://user-images.githubusercontent.com/1871587/148961544-5a2acf4e-0325-457c-864f-f00d873742be.jpg)

**Comment by Navid200** [comment]
@SuperTone Please open a discussion, not an issue when you have a question.
https://github.com/NightscoutFoundation/xDrip/discussions
