### ISSUE TITLE
Feature Request: Allow user to choose if Nightscout upload uses noise smoothed or unprocessed data

### ISSUE THREAD

**Issue by sulkaharo** [NightscoutFoundation/xDrip#194]
My assumption is most people expect xDrip uploads to replicate the same data as displayed in the app. As per the gitter discussion, the uploads currently always use unprocessed data, while xDrip displays data smoothed for noise. I'd love the app to implement support for choosing what gets uploaded, where the default behavior would be for the uploads to match the xDrip display, with an optional override to upload smoothed/unprocessed data. This would be especially useful for households that rely on Nightscout for data display (mixed iOS / Android houses).

**Comment by AdrianLxM** [comment]
Would you like to test this, please?
https://github.com/NightscoutFoundation/xDrip/pull/196

**Comment by jamorham** [comment]
This should now be present in the Oct 8th Nightly. Enable it within the REST-API settings in xDrip.

**Comment by sulkaharo** [comment]
Yay will test today, you guys rule

**Comment by jamorham** [comment]
Any joy with testing?

**Comment by sulkaharo** [comment]
Flipped the toggle on, haven’t noticed issues so far. I’ll compare the display on xDrip and Nightscout later today

**Comment by sulkaharo** [comment]
I still think the user assumption is the uploads match the glucose displayed in xDrip and uploading the unfiltered data is a special case, so I’d make the toggle default to enabled. With the recent improvement to upload the noise data, I’m not sure what the use care for the raw uploads is.

**Comment by gitanO0** [comment]
Where's this toggle again? I looked in the rest-api upload area of settings and in the "extra settings" area.  Not seeing it.  I have the 10/8 build.

**Comment by jamorham** [comment]
You should find it in `Cloud Upload` -> `Rest API` -> `Send Display Glucose`

If not try upgrading to the Oct 10th Nightly as there were actually 3 nightly versions on Oct 8th.

**Comment by jamorham** [comment]
@sulkaharo that preference default can be changed for new installations at a later point. First we much ensure that testing is successful.

**Comment by gitanO0** [comment]
Ok, I just upgraded to the 10th and I see the setting now.  Thx.

**Comment by sulkaharo** [comment]
The comparing between the data in Nightscout and xDrip display, I can't find any anomalies. The sensor output is currently clean though, might need to change a day or two to get CGM noise (the CGM is 13 days old now, should get some noise soon).

**Comment by jamorham** [comment]
How is this looking? Should I mark this as resolved?

**Comment by jamorham** [comment]
I will mark this as resolved. Please re-open it if further work is needed.
