### ISSUE TITLE
Droid Z-Force connection trouble

### ISSUE THREAD

**Issue by PolarDog23** [NightscoutFoundation/xDrip#198]
Not sure if Google/Motorola refreshed something but the G5 transmitter is no longer able to reliably connect to the phone.  The transmitter shows up in the phone's bluetooth listing, but the screen gets hung up on the "Please wait, need 2 readings from transmitter first" message.  Battery is good.  Any thoughts?  I am back to using the Dexcom receiver...

![screenshot_20171007-072322](https://user-images.githubusercontent.com/17293710/31308758-d2a9bc3c-ab41-11e7-9b7b-93d51fdfe769.png)

![screenshot_20171007-084048](https://user-images.githubusercontent.com/17293710/31308627-a0ec5c88-ab3f-11e7-898b-06d6e8ac4c07.png)

**Comment by jamorham** [comment]
Try rebooting the phone. If the non OB1 collector used to work for you then try switching back to that to see if that works.

Otherwise I will need more log information. To enable full logging for OB1 you need to go in to `Less Common Settings` and set the extra debug log tags to `Ob1G5CollectionService:v,Ob1G5StateMachine:v` and then let it try for a bit and the logs should be much more detailed after that.

**Comment by PolarDog23** [comment]
Thanks for your help!  Two things:

1) I think I actually have a problem with the transmitter as I am having
trouble also with the Dexcom receiver.  This may be the root of my problem.

2) Is there a recommended list of settings?  I appreciate that the task of
documenting each and every setting is very challenging, and I think it is
done very well.  I'm interested in selecting those options from the many
that would "put me in the middle of the fairway"

In lieu of any answer to 2), I should probably close this issue.

Many many thanks for all the hard work you do!

Eric

**Comment by Navid200** [comment]
@PolarDog23 There are two support channels.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

You can find recommended settings for Dexcom in the facebook group.

Would you please close this issue unless you have any other questions?
Thanks

**Comment by Epod123** [comment]
There does not appear to be a way to "close" this.  I see no "close" button next to the green "comment" button.
