### ISSUE TITLE
Ambrosia blucon - No pairing with bluetooth

### ISSUE THREAD

**Issue by wastlkl** [NightscoutFoundation/xDrip#201]
On Sunday i tried to connect a blucon sensor with "xDrip - Nightly build 7th Oct 2017".
The connection was not possible, because the window of the bluetooth code was not popping up.

**Comment by jamorham** [comment]
Try the Oct 10th nightly, I think this should fix the problem for you

**Comment by jamorham** [comment]
I assume this is now resolved

**Comment by wastlkl** [comment]
Hallo NightscoutFoundation,
Many thanks for your efforts.
I don't testet it again, because I'm using now my former version from 09.09.2017.
On next monday i will see, then i am going to set a new sensor for my son.
But I confide in you, that the problem is now fixed.
Thank You so much for Nightscout.Now it is much easier and simple to observe the glucose of our son in the night and at school.
Kind regardsAlexandra and Klaus


-------- Ursprüngliche Nachricht --------
Von: Jamorham <notifications@github.com> 
Datum: 16.10.17  22:34  (GMT+01:00) 
An: NightscoutFoundation/xDrip <xDrip@noreply.github.com> 
Cc: wastlkl <mail@familie-wastl.de>, Author <author@noreply.github.com> 
Betreff: Re: [NightscoutFoundation/xDrip] Ambrosia blucon - No pairing with
  bluetooth (#201) 

I assume this is now resolved

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/NightscoutFoundation/xDrip","title":"NightscoutFoundation/xDrip","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/NightscoutFoundation/xDrip"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jamorham in #201: I assume this is now resolved"}],"action":{"name":"View Issue","url":"https://github.com/NightscoutFoundation/xDrip/issues/201#issuecomment-337032026"}}}
