### ISSUE TITLE
App not showing up in Play Store on Wear OS watch

### ISSUE THREAD

**Issue by erizzo** [NightscoutFoundation/xDrip#2011]
Wear OS version: `2.33`
xDrip+ version: `49817a5-2021.10.04`
Phone Android version: `12`

The ["Watch Guide" instructions](https://github.com/jamorham/xDrip-plus/blob/master/Documentation/WatchGuide.md#enable-xdrip-android-wear-integration) say to install the app via Play Store _on the watch_, but when I look under "Apps on your phone" it's not there. I have installed a few other apps that way in the past.
 I installed xDrip+ on my phone via the QR code from the main page.

**Comment by Navid200** [comment]
Please kindly don't open an issue to communicate a concern.  Please use the discussions instead:  https://github.com/NightscoutFoundation/xDrip/discussions

Is this open issue related to what you are describing:
https://github.com/NightscoutFoundation/xDrip/issues/1648

**Comment by Navid200** [comment]
Please explain if this is something not addressed by the links and we can reopen.
Thanks

**Comment by erizzo** [comment]
#1648 is indeed the same problem I was experiencing. The Wear Install third-party app solved it for me. Thanks.
