### ISSUE TITLE
Ways to improve the Reminders feature

### ISSUE THREAD

**Issue by jamorham** [NightscoutFoundation/xDrip#2044]
There are a number of places where there is room for improvement within the Reminders feature. I'll list these on a single issue.

- [x] Swiping off a reminder from the notification area or lock-screen causes it to be snoozed. For many applications cancel/rescheduling the reminder as the default operation may be preferred.
- [x] If using a repeating reminder, for example to remind for a regular cannula change. If this is then performed a day late, the rescheduling sticks to the original schedule when the user might well wish to reschedule to the time period in the future from when the change was actually done.
- [x] The user interface doesn't make it constantly clear the different functionality of swipe left/right on the list screen.
- [x] There is no visibility or synchronization of reminders to followers (this is a bit more tricky to resolve)

I've been working on some fixes for these issues and should have something ready to address much of this soon.

**Comment by Navid200** [comment]
Is there anything a user can do using xDrip reminders that they cannot do using Google Calendar?

**Comment by jamorham** [comment]
@Navid200  I'm probably not the best person to comment on that as I don't use google calendar so am not familiar with its feature set.

The most significant feature is for scheduling repeating reminders such as cannula changes etc. When it is reminding it has an exponential backoff on the snoozing and can be set to only remind during the day. There can be speech announcements and it has options to detect home wifi so it only reminds you to do certain tasks when at home etc.

**Comment by jamorham** [comment]
Addressed in https://github.com/NightscoutFoundation/xDrip/commit/25a60e71b4e16469f44798d621dc610b943ecf76

**Comment by tolot27** [comment]
> Addressed in [25a60e7](https://github.com/NightscoutFoundation/xDrip/commit/25a60e71b4e16469f44798d621dc610b943ecf76)

Does this commit addresses all four subtasks? Please check all addressed subtasks in the topmost comment.

**Comment by jamorham** [comment]
Items 1-4 have been addressed. 

1) Lock screen dismissal is better handled now and there is a new menu item `Cancel by Default` which allows notification dismissal to cancel instead of snooze.

2) Late cancellations (> 1 day) now have a pop-up dialog asking whether to use old or new timing, whether to stick to the old time schedule or use a new one of the current time + interval period.

3) When there is at least 1 reminder present in the UI there is a small text box at the bottom to remind the swipe off direction for snooze vs cancel/reschedule as previously shown in the introductory showcase help.

4) Reminders can also have a `Graph Note` which indicates on the graph via a note icon when a reminder alerts. This is also synchronized with followers but is just a read-only indication.

**Comment by tolot27** [comment]
Great, thanks. Hence, we can close this issue, can't we?
Hopefully, someone will add this to the xDrip documentation.

**Comment by tolot27** [comment]
With the new reminder feature I get acoustic alarms even if they are snoozed for a certain amount of time. No notification is shown. That's a bit wired.

**Comment by Navid200** [comment]
I hope you don't mind me closing this.  We can always reopen if needed.
