### ISSUE TITLE
Rewrite History after calibration is only done on master, should be done also on followers

### ISSUE THREAD

**Issue by dideldum** [NightscoutFoundation/xDrip#206]
When Rewrite History in the settings is enabled, this is only applied on the master, who adjusts the curve to the calibration value(s).
On the follower this does not happen. Followers thus have a sudden jump in the curve, also showing then completely wrong tendency arrows.
Followers should adjust the curve to calibration values at least, if they are configured in the settings to rewrite history like the master.
Maybe followers should be forced to rewrite history if the master is set to rewrite, regardless the setting in the follower.

**Comment by TecMunky** [comment]
I like the idea of having followers rewrite history when a calibration is performed, and I would prefer that this depend on the setting on each follower device.  This seems a much simpler task than re-sending rewritten data from the sync master to sync followers.

**Comment by Navid200** [comment]
@dideldum Would you please close this issue if you are satisfied?
If not, would you please respond to the suggestion you have received?
Thanks

**Comment by dideldum** [comment]
@Navid200 I'm sorry, that I cannot confirm, that this issue is resolved. It has not been resolved for a very long time, and now I don't use xDrip+ anymore, so I don't know, if the followers handle a rewrite history with a calibration now as it is done on the master.
Nonetheless I close this issue.

**Comment by TecMunky** [comment]
This would still be a useful feature

**Comment by tolot27** [comment]
@TecMunky Do you experiencing the same problem?

**Comment by Navid200** [comment]
@TecMunky Rewrite history is a graphics setting, not a calibration setting.
I don't see how we can (and why we should) have the graphics manipulations on master to be transferred to the follower or vice versa.

Please explain what feature exactly you are talking about.

**Comment by TecMunky** [comment]
When a calibration is executed, the readings for up to the last 3 hours are
adjusted on the Master.  All followers do not see any adjustment of the
data, and thus show different data than the Master.  I would prefer that
followers would also see the same data immediately after a calibration.

This is not a critical issue for me.  Just a minor annoyance.

**Comment by Navid200** [comment]
I don't think we will expand rewrite history or extend it to any other platforms.
https://github.com/NightscoutFoundation/xDrip/issues/366#issuecomment-894306546
