### ISSUE TITLE
S22+ bluetooth constant paring request

### ISSUE THREAD

**Issue by Schizm1** [NightscoutFoundation/xDrip#2071]
I just upgraded to an S22+. Installed the newest nightly build as I had on my old device. I transferred all settings via QR code. Unfortunately I'm getting intermittent bluetooth paring request for the transmitter. I've tried resetting the BT and all basic functions. Is this a phone or xdrip issue? 
![Screenshot_20220408-154204_xDrip+](https://user-images.githubusercontent.com/25514585/162543356-ce786875-8474-467e-b38b-221fef0ed8a1.jpg)
![Screenshot_20220408-154212_xDrip+](https://user-images.githubusercontent.com/25514585/162543358-e5ee2e59-1ffb-4d4c-b9c1-49ad85618ac1.jpg)

**Comment by Navid200** [comment]
To start, please adjust all settings to follow:
https://navid200.github.io/xDrip/docs/G6-Recommended-Settings.html

**Comment by Schizm1** [comment]
Thanks, one setting was different from what I had. See if it makes a
difference

Mike

**Comment by ChanceHarrison** [comment]
@Schizm1 Did it make a difference for you? Would love to know if it worked or not (so the issue can be closed or we can troubleshoot more 🙂).

**Comment by Schizm1** [comment]
Thanks for getting back to me. It seemed to help but not resolved. Prior to
the instructions it asked me every 5 minutes. Now maybe a couple times a
day.

Mike

**Comment by ChanceHarrison** [comment]
Also, you mentioned that you changed one setting that was different from the recommended settings, but I don't think you mentioned which setting you changed. It might be helpful to know what setting it was that you changed. In any case, it sounds like your current settings match the recommended settings?

**Comment by Navid200** [comment]
We can talk about this better in the discussions.  If the problem persists, please open a discussion and we can go over the best approach for your device:
https://github.com/NightscoutFoundation/xDrip/discussions
