### ISSUE TITLE
Accu-Chek Guide Meter

### ISSUE THREAD

**Issue by kallnap** [NightscoutFoundation/xDrip#208]
Hi,
I connected my AC Guide meter via BT to my Samsung S5 mini using the latest nightly of the xdrip+ app. Unfortunately I am not able to switch the slider under "use Bluetooth Meter" to on. Is this a known issue or am I just too stupid?
Thanks

**Comment by TecMunky** [comment]
For some meters, you have to take a BG sample before you can switch the slider on.  For instance, I use the Contour Next One, and that is what I had to do.

**Comment by kallnap** [comment]
Thank you, will try. Unfortunately it did not help

**Comment by jamorham** [comment]
This meter has never been tested. I haven't been able to obtain one. I'm not sure if they are available in the UK.

**Comment by kallnap** [comment]
Thank you for commenting. This explaines a lot. I assume that every meter has its own perks although there is the BT standard.

**Comment by TebbeUbben** [comment]
The Accu-Chek Guide is standard conform, so it works with xDrip. I tested it a moment ago.

**Comment by TebbeUbben** [comment]
Try the following instructions:

On the meter:
- Settings
- Wireless
- Pairing
- Pair device

On your phone:
- Open xDrip
- "Settings"
- "Glucose Meters"
- "Scan for Bluetooth Meter"
- Select your meter
- Enter the code your meter displays
- Go back
- Turn on "Use Bluetooth Meter"

**Comment by kallnap** [comment]
Danke, das sind ja gute Nachrichten.
 

-----------------------------------------------------------------------------------------------
Dr. Tobias Kunstmann
Martin-Kärcher Str. 34
68623 Lampertheim
Telefon mobil: 0157 86899087
E-Mail: tobias.kunstmann@web.de

 
 

Gesendet: Mittwoch, 06. Dezember 2017 um 18:37 Uhr
Von: "Tebbe Ubben" <notifications@github.com>
An: NightscoutFoundation/xDrip <xDrip@noreply.github.com>
Cc: kallnap <tobias.kunstmann@web.de>, Author <author@noreply.github.com>
Betreff: Re: [NightscoutFoundation/xDrip] Accu-Chek Guide Meter (#208)


Try the following instructions:

On the meter:


	Settings
	Wireless
	Pairing
	Pair device


On your phone:


	Open xDrip
	"Settings"
	"Glucose Meters"
	"Scan for Bluetooth Meter"
	Select your meter
	Enter the code your meter displays
	Go back
	Turn on "Use Bluetooth Meter"

**Comment by jamorham** [comment]
@kallnap did you manage to get this to work?

**Comment by jamorham** [comment]
I will mark this as resolved.
