### ISSUE TITLE
Nightscout uploader bug with multiple insulin profiles

### ISSUE THREAD

**Issue by sudousercom** [NightscoutFoundation/xDrip#2087]
Hi! In setting i choosed Fiasp as short, and lantus as long, in xdrip it shows correctly, but prediction line for lantus has 4-6 hours for lantus, but it works all 24 hours.
And then all data uploaded in my nightscout, and it shows basal lantus doses as fast bolus insuline.

How i can fix these issues, or it need to be updated in code?

### Your environment
xdrip version is4f493d3f9-2022.02.17, code 2022021722
nightscout is latest stable version

**Comment by Navid200** [comment]
Would you please explain why you didn't open a discussion, as you were a sked to, and went ahead and opened an issue?

**Comment by sudousercom** [comment]
> Would you please explain why you didn't open a discussion, as you were a sked to, and went ahead and opened an issue?

Sorry for inconvenience, but i found related issue (https://github.com/NightscoutFoundation/xDrip/issues/1158) and just opened new, if it needed, i can create new discussion about my problem

**Comment by Navid200** [comment]
Please don't open an issue unless advised by a developer.
You can open a discussions.
