### ISSUE TITLE
Problem connectivity phone and blukon

### ISSUE THREAD

**Issue by JoanoToxo** [NightscoutFoundation/xDrip#209]
Hi,
I have an Huawei PRA-LX1 phone with Android 7.0
I had installed 08/09/17 nigtly version xdrip and it worked fine.
Yesterday I automatic updated to 26/10/17 nigtly version xdrip and it does not work.
I installed 26/10/17 stable version xdrip and it does not work.
I installed 08/09/17 nigtly version xdrip and it now is does not work!!!!
I had attachment the capture screen:
The initial screen says:
It need 2 reads first. It hangs.
The log says:
Fetch read error...please check the connectivity and re-initiate... or maybe battery is low.
etc.

The battery is new.

Please, Can you help me?

regards
![pantalla1](https://user-images.githubusercontent.com/22658071/32100469-26dfb86a-bb14-11e7-9a99-823205ea39cb.jpg)
![pantalla2](https://user-images.githubusercontent.com/22658071/32100475-29a7fe68-bb14-11e7-926c-80397e1f5f10.jpg)

**Comment by JoanoToxo** [comment]
It is the battery

Thanks

**Comment by gregorybel** [comment]
Hi

Battery is really low, try with another on. With cheap battery it may happens.

Gregory
