### ISSUE TITLE
Faulty initial calibration

### ISSUE THREAD

**Issue by Thomas-Wolff** [NightscoutFoundation/xDrip#2096]
After the installation of the build of 2 May 2022 Bulid: 10d07c1 an initial calibration was requested in xDrip although 'OOP2 algorithm calibation' was set to false.

Calibrated blood levels 148 mg/dl and 151 mg/dl to sensor 135 mg/dl. The next sensor value read after calibration was 233 mg/dl.
There may be something wrong with the calibration, please verify.

At the moment updated back to the last construction from 1 May 2022.

Attached are the screenshots of the calibration table and the corresponding data table.

![Bild1](https://user-images.githubusercontent.com/59526802/166307795-ca5ea3b9-d673-4eb7-8671-a6ba1b7feddf.jpg)

![Bild2](https://user-images.githubusercontent.com/59526802/166307834-b63b4acc-f1bf-4b4b-ae52-2ebb8e1eb089.jpg)

Kind regards Thomas

**Comment by Navid200** [comment]
>There may be something wrong with the calibration, please verify.

Indeed, there may be.
Would you please open a discussion and describe?
https://github.com/NightscoutFoundation/xDrip/discussions

We have asked everyone to do this; to open a discussion and allow us to verify.  Would you please be so kind to follow the instructions?

**Comment by Thomas-Wolff** [comment]
I will do, thank you very much
