### ISSUE TITLE
Stuck on collecting inital readings screen while connecting to Bluecon

### ISSUE THREAD

**Issue by isuran** [NightscoutFoundation/xDrip#210]
On data collector running.  In logs only Error code 1(sqlite_error), error or missing database.

**Comment by jamorham** [comment]
Try switching to the latest nightly and see if the problem persists:

https://github.com/NightscoutFoundation/xDrip/wiki/How-to-get-the-Nightlies-on-Automatic-Update

**Comment by hotpickle** [comment]
i had the same issue, and toggling airplane mode worked for me!

**Comment by jamorham** [comment]
@isuran did you get this resolved?

**Comment by isuran** [comment]
changed phone, Samsung j3  Bluetooth is to unstable...

**Comment by stroudie11** [comment]
Completely off topic I have blundered in here just trying to connect my Libre via Bluecon Nightrider and seem to be on the developer side of the app not the user. Please can someone give me a link to use on my Samsung S5 phone?

Many thanks if you can.

afisher301@gmail,com

**Comment by jamorham** [comment]
@stroudie11 what kind of link is it that you are looking for?

**Comment by stroudie11** [comment]
Hi JamOrHam thanks for replying,

I have been a Dexcom user for 10 months and having heard about Bluecon
Nightrider turning Libre into a direct competitor giving alarms when used
with xDrip +.

Having purchased Libre sensors and reader plus the Nightrider I was keen to
install the system however I have not got very far.

On one of the forums I was given the following link as one that had enabled
him to use your app.

https://github.com/NightscoutFoundation/xDrip/releases

This brings up your nightly list of updates. However the guy helping me
says the following should happen -

“then click the menu button at top left (the three horizontal lines) then
in Settings/Hardware Data Source, select "Libre Bluetooth". Then scroll
back to the main menu, click again and select "Bluetooth Scan". From the
screen that opens, click "scan" at top right. Wait a while and you should
hopefully see BLUxxxxx listed as a found bluetooth device (xxxxx will be a
series of numbers). That'll be xDrip+ saying it's found your blucon. If you
get nada, try stabbing the blucon with the cocktail stick again till it
flashes red, then do the 'scan' routine again. Once you eventually get
BLUxxxxx showing, click that entry, it'll then bring up an input screen
where you need to type in the last 6 numbers printed on the side of your
specific blucon. That'll pair blucon and xdrip so they can talk to each
other. There's then a screen comes up which asks you to input a couple of
meter readings, then there's a bit of waiting while it gets a few values
from the sensor. If it's worked, after about 10 minutes, you should be able
to go the home screen and see a pretty little graph with some blue dots on
it. You'll get another blue dot every 5 mins.”

However there are no menu bars on the screen.

An additional issue that I have been having is that on my phone I get a
message saying GitHub no longer supports my web browser and I should
upgrade to the latest version of Chrome or Firefox.

I have installed the latest Chrome but still get the message.

Please can you point me in the right direction and comment on the
instructions above as to how accurate they are.

Do you have a manual on how to use xDrip?

Stroudie

**Comment by stroudie11** [comment]
Hi JamOrHam,

At last I have finally worked out the problem - nothing to do with xdrip
but my phone which is running on chrome was set to download only from
Play.  Once I had cancelled this the latest version came straight on down.

14 days wasted!

Only question now is if there is a manual - I know I will struggle over
several days and it would be helpful.

Many thanks and a good new year to you.

Stroudie

**Comment by tuckdesign** [comment]
Guys, I have the same problem. Tried different versions, but BluCon is always stucked on first screen (never gets those 2 readings)

**Comment by tuckdesign** [comment]
I tried libre bluetooth with iOS version of xDrip+ and it is working fine (unfortunately only on iPhone, not iPad)

**Comment by stroudie11** [comment]
Hi

My problem was so long ago that I had forgotten all about it.

Once I had realized that the problem was with Play I got xdrip up and
running just following what other guys had told me and what was in the
Bluecon box.

Another 14 days of struggling and have had Herokuapp also functioning so
anyone can follow my blood sugars.

Not sure what your problem is are u trying to calibrate xdrip on android
phone?




On Thu, Jan 25, 2018 at 8:18 PM, Krunoslav Đaković <notifications@github.com

**Comment by tuckdesign** [comment]
xDrip and libre are not working on android. they connect but no data is received by tablet. gets stucked on screen where is says that it needs 2 measuring.

**Comment by stroudie11** [comment]
Hi Krunoslav,

Sorry cannot help but if you go to the facebook page listed below this is
just fo the use of people using Bluecon Nightrider and they can probably
help.

https://www.facebook.com/groups/1880872478868072/

On Thu, Jan 25, 2018 at 9:24 PM, Krunoslav Đaković <notifications@github.com

**Comment by gregorybel** [comment]
make sure your Blucon is not paired with your iPhone when trying with android phone. so delete pairing.

2 values need 10minutes so you need to wait enough.

otherwise look here:

https://github.com/gregorybel/xDrip-plus/wiki/How-to-use-Blukon-with-xdrip

**Comment by stroudie11** [comment]
If only I had this advice when I spent 14  days trying to connect xdrip+ up

**Comment by Navid200** [comment]
@isuran Please close this issue if your problem has been resolved.
For everyone, there are two support channels available.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks
