### ISSUE TITLE
Strange characters in BT Scanner

### ISSUE THREAD

**Issue by osodebailar** [NightscoutFoundation/xDrip#211]
![screenshot_20171028-202138](https://user-images.githubusercontent.com/25795894/32137356-6fb6e710-bc1e-11e7-8351-2654586e5b17.png)

**Comment by jamorham** [comment]
Presumably you have `Engineering Mode` enabled? It will show the raw bluetooth advertisement detail which is used when preparing automatic configuration for new hardware types like Rfduino.
