### ISSUE TITLE
Android 13 xdrip+ wont pair to  G6 transmitter

### ISSUE THREAD

**Issue by liam8lili** [NightscoutFoundation/xDrip#2112]
On android 13,  the   Dexcom G6 transmitter wont pair with the device and is constantly opening pair prompts, but upon accepting them it still does not pair and the service state remains on connect request with a time beside it
![Screenshot_20220510-000344](https://user-images.githubusercontent.com/72522185/167559033-ea344f28-9fde-4019-8545-2730909e6afb.png)
.(device Pixel 4 XL)

**Comment by Navid200** [comment]
When you went to open this issue, you must have seen a note asking you not to open an issue unless requested by a developer.
Did a developer ask you to open this issue?

If not, please as you must have seen the request we have there, please open a discussion instead:
https://github.com/NightscoutFoundation/xDrip/discussions
