### ISSUE TITLE
Available: 2 different AW smartwatches to donate to a developer willing to work on "Force collector" problems

### ISSUE THREAD

**Issue by Vaughanabe13** [NightscoutFoundation/xDrip#214]
I posted about this in the G5 facebook group already.

I bought 2 Android Wear watches, the Fossil Q Founder 2.0 and the Polar M600. The Q Founder 2.0 has the Snapdragon Wear 2100 chipset and the Polar M600 has a MediaTek MT2601 chipset. I specifically bought those watches because I hadn't seen any confirmed cases of whether or not these chipsets would function in "Force Collector" mode to collect readings. Also, both of these watches have AW2.0 updates available for them.

As it turns out, I could not get either watch to work under force collector mode in the latest alpha channel release of xdrip+. So I tried to return the watches to Amazon and Amazon refunded my purchase, but they said I do not have to return the watches and that I may donate or otherwise discard them. The exact words from Amazon are "On this occasion, we don't require you to return the original. You're welcome to keep, donate or dispose of it - whichever option is most appropriate and convenient for you."

Both of these watches are brand new, never worn. I want to donate them to developers in the group who have some spare time to investigate why the force collector option does not work on watches other than the Smartwatch 3. I think this is something that is extremely important for the future of xdrip and unfortunately I don't have the time or expertise to work on it myself.

Please let me know if you would be interested.

Product pages:
https://www.amazon.com/Polar-Smart-Sports-Watch-black/dp/B01I5GC2CY/ref=sr_1_3?ie=UTF8&qid=1510340514&sr=8-3&keywords=polar+M600
https://www.amazon.com/Fossil-Founder-Touchscreen-Smartwatch-FTW2119/dp/B01EQZPVCG/ref=sr_1_2?s=apparel&ie=UTF8&qid=1510340529&sr=1-2&nodeID=7141123011&psd=1&keywords=fossil+q+founder+2.0

**Comment by jamorham** [comment]
This sounds like it could be useful. I have just produced a firmware patch for the Zenwatch 2 to get it to work so a similar strategy may be possible with these watches as well.

**Comment by Vaughanabe13** [comment]
Sounds excellent. I'm sending you an email.

**Comment by jamorham** [comment]
Thanks so much for your help with this, the Polar M600 and Asus Zenwatch3 are now supported:

https://github.com/NightscoutFoundation/xDrip/wiki/Patching-Android-Wear-devices-for-use-with-the-G5

**Comment by abherrma** [comment]
@Vaughanabe13 how does the M600 work w/ xdrip? would like to have a fitness watch that can get g5/g6 data directly from the transmitter (w/o phone).
