### ISSUE TITLE
Guardian Connect

### ISSUE THREAD

**Issue by Schoggiweggli** [NightscoutFoundation/xDrip#215]
Since Medtronic is reaaaaally slow at releasing an Android App or even update the iOS one to be considered a competition for Dexcom, is it possible to get it to work with xDrip?

I i am stuck with an iPhone because of it and i would love to change the device.

**Comment by hartlijn** [comment]
For now only in combination with android uploader phone with the BG Meyer attached via OTG cable.

**Comment by Schoggiweggli** [comment]
@hartlijn that's for the Pump combination. Guardian Connect is a standalone bluetooth transmitter.

**Comment by shtefanilie** [comment]
@Schoggiweggli any news? Did you try with xdip? Does it work?

**Comment by Schoggiweggli** [comment]
> @Schoggiweggli any news? Did you try with xdip? Does it work?

I don't know, sorry. Changed to Dexcom G6 a year ago and gave up on Medtronic entirely.

**Comment by tolot27** [comment]
Duplicate of #131
