### ISSUE TITLE
xDrip+ integration with Yourloops (Diabeloop)

### ISSUE THREAD

**Issue by fjpezuela** [NightscoutFoundation/xDrip#2155]
There are more and more users using the Yourloops platform (users using the Diabeloop device).

https://www.your-loops.com/

It would be great to be able to integrate with the Yourloops platform and be able to download the data from the platform (bolus, basal, carbohydrates, corrections, etc).

Thank you very much

**Comment by Navid200** [comment]
Please follow the request you saw when you were opening this issue to start a discussion instead:
https://github.com/NightscoutFoundation/xDrip/discussions
