### ISSUE TITLE
Add Web Follower Setting for Custom "Next poll in" Frequency 

### ISSUE THREAD

**Issue by gilla013** [NightscoutFoundation/xDrip#2185]
Hi dev team,

Next poll in is always 5 min and can not be set lower. Though w/ my libre 3 I believe lowering this would result in a shorter reading interval which also displays on my watch.
If I am wrong about this sorry, but if this is correct, please add this as a parameter in the Web Follower Settings. 

KR,

G. Pauli

**Comment by Navid200** [comment]
Thanks for the suggestion.

Would you please open a discussion and make this suggestion there?
https://github.com/NightscoutFoundation/xDrip/discussions

This is what we ask everyone to do.

Thanks for your help and support.
