### ISSUE TITLE
Feature Request: Support for Dexcom Share Servers as Data source

### ISSUE THREAD

**Issue by Saarpit** [NightscoutFoundation/xDrip#220]
Dear all, is it possible to add the support for dexcom share servers (US and outside US) as data source in XDRIP? I already use the nightscout app with this feature, but XDrip+ is more powerful!
The prediction feature is very nice, so I want to have it. I already user XDrip+ as a follower.

**Comment by musicman0329** [comment]
Would nightwatch meet your needs? I'm unsure if it has the prediction features or not...
http://stephenblackwasalreadytaken.github.io/NightWatch/

**Comment by Saarpit** [comment]
Dear Caleb,

thank you for your reply. I'm already using nightwatch for monitoring the
blood sugar of my daughter. But unfortunately the is no predition right
now. There are also some more bugs. E.g. it isn't possible for me to
disable the alerts for a time because I can't the the ok button :-) The
development in the xDrip project is still alive. And as I mentioned before,
we already used xDrip before and the prediction algorithm  was a very nice
feature.

Thanks in advance and best regards
Eric

Caleb Seekell <notifications@github.com> schrieb am Di., 5. Dez. 2017 um
20:53 Uhr:

**Comment by tubes41** [comment]
This already indirectly works...
1) Use Nightscout to collect the data from the Dexcom Share servers: http://www.nightscout.info/wiki/welcome/nightscout-with-ios-and-dexcom-share
2) Setup xDrip+ as a Nightscout follower: https://jamorham.gitbooks.io/xdrip-plus/content/xdrip-plus-nightscout-viewer.html

**Comment by tolot27** [comment]
It is implemented as `Dex SHare Follower`, isn't it?
