### ISSUE TITLE
Dexcom G5: Periodical interrupt of connection

### ISSUE THREAD

**Issue by osodebailar** [NightscoutFoundation/xDrip#221]
We have periodical interrupts of connection and data is missing.
Smartphone:
 Huawei Mate 10 Lite
In the attachments you see all log data and the xdrip configuration. 

Tell me if you need more information and special log data.

![23899450_2158640774161862_1458836355_n](https://user-images.githubusercontent.com/25795894/33254191-d7f7474e-d347-11e7-915a-305f94160090.png)
![23972369_2158640634161876_740043660_n](https://user-images.githubusercontent.com/25795894/33254192-d80edc7e-d347-11e7-9ce2-54cdaaad5449.png)
![23972600_2158640560828550_970481028_n](https://user-images.githubusercontent.com/25795894/33254193-d82514da-d347-11e7-8153-a92e537b4e4d.png)
![23972618_2158650257494247_181067997_n](https://user-images.githubusercontent.com/25795894/33254195-d83b5330-d347-11e7-8ec2-c826e37dda34.jpg)
![24008550_2158651737494099_756225606_n](https://user-images.githubusercontent.com/25795894/33254197-d852a4f4-d347-11e7-85ad-6ec3dd39a2b9.png)
![24008717_2158640617495211_138374348_n](https://user-images.githubusercontent.com/25795894/33254199-d86a11a2-d347-11e7-9b6e-452b3aec24a6.png)
![24008743_2158640990828507_960862993_n](https://user-images.githubusercontent.com/25795894/33254200-d8842844-d347-11e7-9ea8-8ca0542af126.png)
![24008756_2158651714160768_1848961447_n](https://user-images.githubusercontent.com/25795894/33254201-d89c249e-d347-11e7-9563-aaed55009271.png)
![24019897_2158640537495219_41728244_n](https://user-images.githubusercontent.com/25795894/33254202-d8b353d0-d347-11e7-94e0-1ba71d87224d.png)

**Comment by jamorham** [comment]
What does your main graph look like? Are the data points missing regularly or just randomly?

**Comment by ryanmccutchen** [comment]
Im also seeing drops in connections regularly, and several users in the Facebook group are mentioning the same thing - all on recent builds. It seems to be regularly and not randomly.

Im using a S8 with today's build. All users report similar issues that the connection drops consistently and restarting the collector brings it back. I am using the OB1 Collector with no other debug settings. I have been playing around with different BT settings but no changes in behavior.

This is some of the drops. For me it happens the most at night while sleeping, and at work. I cant really determine why - in all cases I keep my phone close to me.

![image](https://user-images.githubusercontent.com/7481799/33408572-045809b4-d52c-11e7-958d-35c1c6348a92.png)

**Comment by osodebailar** [comment]
Same here :
![01_n](https://user-images.githubusercontent.com/25795894/33417688-c9949492-d5a2-11e7-8c9a-df14081c5633.png)
![02_n](https://user-images.githubusercontent.com/25795894/33417689-c9aa7cee-d5a2-11e7-95d7-7292ba8bf4a7.png)

**Comment by jamorham** [comment]
Can you enable the debugging for the OB1 collector so we can gather more event logs to investigate in more detail:

https://github.com/NightscoutFoundation/xDrip/wiki/Enabling-Debugging-for-OB1-collector

**Comment by osodebailar** [comment]
Jon i am very sorry. The problem with the Huawei occured to a friend of Mine. He bought it last week for xdrip and AndroidAPS. But due to the problem he changed the mobile to a Sony xperia which does its work very well. So we can't reproduce the situation anymore.

**Comment by jamorham** [comment]
Ok, I think the Huawei issue is likely to be due to its non-standard power saving features. I think it has a concept of something called "Protected Apps" which is like the battery optimization whitelist. I don't think we have a way to control this programatically, but either disabling it or adding xDrip to its whitelist can help I think.

**Comment by jamorham** [comment]
@ryanmccutchen do you see anything in the `System Status` tabs when it is in the state of not receiving, for example a warning about slow wake ups ?

**Comment by AlexanderDemko** [comment]
Hello! I have the same problem on Huawei Honor 9.

While I am using my phone; or the phone is charging, there are minimal connection issues.
While the phone's display is on sleep mode or screen lock, the capture rate is approx. 10%

I can collect any log data if necessary.

**Comment by Navid200** [comment]
@osodebailar If you are not experiencing this problem, would you please close the issue?

For anyone with this problem or any other similar connectivity issues, please post on facebook:
https://www.facebook.com/groups/xDripG5

**Comment by Navid200** [comment]
Closing it for inactivity.
