### ISSUE TITLE
Wahoo collection removal not working 

### ISSUE THREAD

**Issue by dkshores63** [NightscoutFoundation/xDrip#2253]
Hey Happy Tuesday!  I have manged to get my Wahoo Bolt bike Computer working with my Dexcom G6 and Displaying my BG readings! It is great!  It is a long story on how I did it, but I am trying to remove it from my old Wahoo so whomever is using it next, won't have the Scanning message forever taking up space on the screen.  I have used Start USB Configuration command with xdrip collector disabled as suggested in the wiki, but it doesn't work.  The BG value continues to be displayed.   Part of the long story mentioned above..  and suggestions?

**Comment by Navid200** [comment]
We are asking everyone not to open issues as a first step.
That's why this request is visible when you attempt to open an issue.
I am curious, did you see it and chose to ignore the request?  Or, did you not see the request?

In the meantime, I am closing this issue so that we are not being unfair to those who follow the request.

**Comment by dkshores63** [comment]
I'm not sure what you mean first thing?  I did various searches and applied those results.   It didn't solve the issue.   Maybe I'm misunderstanding my next step here?

What should I do next then?

Thanks for your input

DKS

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Navid200** [comment]
I'm sorry I wasn't clear.
Please open a discussion here:  https://github.com/NightscoutFoundation/xDrip/discussions

Please ask your question there.
If it turns to be an xDrip issue, we can always reopen this issue.

Thanks
