### ISSUE TITLE
OB1 + SSW3 Status page does not show G5 transmitter information. 

### ISSUE THREAD

**Issue by musicman0329** [NightscoutFoundation/xDrip#226]
When using the new OB1 collector and in conjunction with a Sony Smartwatch 3, the status page in xdrip+ does not show any transmitter info. There are no battery stats, no firmware version, no temperature, etc. Shutting OB1 off restores this information. I am using xdrip+ 2017.11.13. 
![24254691_499501523769101_2150739023329392956_o](https://user-images.githubusercontent.com/15910886/33569094-8f0742aa-d8f6-11e7-921b-0a2a3ab768b7.jpg)

**Comment by doc77** [comment]
As a workaround, if you go to the G5 status page, then immediately go to the events log, you will see the battery info as the first entry.  OB1 is collecting the data it's just not displaying it.

**Comment by musicman0329** [comment]
I can confirm that the workaround does work... ;)

**Comment by jamorham** [comment]
This should now be resolved, please try the latest nightly and let me know. Thanks

**Comment by doc77** [comment]
@JamOrHam Works like a charm! Thanks so much!

**Comment by jamorham** [comment]
Marking as resolved

**Comment by musicman0329** [comment]
Yep, works great.
