### ISSUE TITLE
How to delete calibrations?

### ISSUE THREAD

**Issue by thedewi** [NightscoutFoundation/xDrip#227]
My latest Freestyle sensor is relatively noisy, and several calibrations have become attached to noise. I didn't realize I could only edit the last. How can I remove the rest?

**Comment by thedewi** [comment]
If I keep adding more, will any bad ones eventually become insignificant?

**Comment by thedewi** [comment]
Solved by enabling Datatables (under Settings > Less common settings >  Show Datatables) and flagging questionable entries.

**Comment by tzachi-dar** [comment]
Probably not relevant but for the record...

Go to settings->Less common settings -> enable show databases.
Go to calibration data table.
press a long click on the calibration you want to cancel.
