### ISSUE TITLE
Nightscout Sync (REST-API) Back-fill not sending calibrations

### ISSUE THREAD

**Issue by thedewi** [NightscoutFoundation/xDrip#228]
Back-fill is successfully adding/replacing BG entries, but not calibrations.

I'm not sure about treatments because I don't have any at the moment, but it would be ideal if all types of data that are normally uploaded would be sent with Back-fill, making it possible to migrate between Nightscout instances without losing data.

**Comment by Navid200** [comment]
@thedewi Would you please close this issue if the feature has already been implemented?
If not, you can consult with the community using the support channels to see if a work-around exists.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

If indeed you feel this is required, please update.

Thanks

**Comment by Navid200** [comment]
If you experience the same, please report and I will re-open.
