### ISSUE TITLE
When CamAPS reports reports ≤2.2 or ≥22.3 xdrip leaves an empty gap

### ISSUE THREAD

**Issue by majabux** [NightscoutFoundation/xDrip#2292]
### Subject of the issue
https://github.com/NightscoutFoundation/xDrip/discussions/2008#discussioncomment-3458602

“The notifications CamAPS gives when exceeding the dexcom ranges report ≤2.2 or ≥22.3 which xdrip seems to be unable to interpret and the value is empty. Is there anyway these values could be interpreted as the values at the top or bottom of the range?”

### Your environment
Nightly build 6th July 2022 using Companion as data source to read from CamAPS.

### Expected behavior
When exceeding the dexcom range the values could be interpreted as the highest or lowest values rather than leaving a gap in the data.

### Actual behavior
Gaps in data, xdrip logs show “Did not find any matches”.

### Steps to reproduce the behavior:
Using CamAPS as data source wait for a
BG reading below 2.3 or above 22.3.

### Screenshots
See discussion thread.

**Comment by jamorham** [comment]
Thank you for a well described issued ticket. Please try the latest nightly to see if this resolves the issue.

**Comment by PieterDeBruijn** [comment]
Yesterday we got two 2.2 measurments through xDrip+, so this seems to be working on the low end at the very least.

**Comment by Navid200** [comment]
@majabux Please provide feedback.

**Comment by majabux** [comment]
We’ve not had any out of range readings yet… I’ll keep you posted.  I’ll post it on the CamAPS Facebook groups this evening asking for other xdrip users feedback too.

**Comment by Navid200** [comment]
@majabux Of course.  And I hope you will not have out of range ever.  I am sorry I hadn't thought about the ramifications of what I was asking.  Please do not intentionally go out of range.
Thanks

**Comment by majabux** [comment]
@Navid200 no apology needed, I understood you were asking as I reported the issue.  I have posted on the CamAPS groups asking others to update and monitor too.

**Comment by majabux** [comment]
I had feedback in the CamAPS Facebook group.  When greater than 22.3 there is still a gap in the xdrip data, the photo shows what’s in the log.  Is this expected? 
![1E6F44A7-E985-49CB-B563-56F5A77D4CF6](https://user-images.githubusercontent.com/55636308/187873958-679ab491-8793-4693-9e07-1e7971adc0b8.jpeg)

**Comment by jamorham** [comment]
I can fix that. Its currently capped at 400 but I will raise the limit. It shows the value is being read properly now though.

**Comment by jamorham** [comment]
The Sept 2nd Nightly (available now) raises this limit. Please let me know if that resolves the issue. thanks

**Comment by majabux** [comment]
Following my daughter having a high tonight I can confirm it’s working now, xdrip+ is reporting as “High” when over 22.3.  Many thanks for your efforts at resolving this. 
![17FF175B-4E6E-4D1E-B8B2-EBAD24E1C16D](https://user-images.githubusercontent.com/55636308/188284873-79fb2809-cdd7-4f2d-bad5-a46ae2c31bd3.jpeg)

**Comment by jamorham** [comment]
Please close this issue if it is now resolved. Thanks

**Comment by majabux** [comment]
Thanks again!
