### ISSUE TITLE
Nightly build 20171203 failing to receive transmitter readings

### ISSUE THREAD

**Issue by tim2000s** [NightscoutFoundation/xDrip#231]
When trying to start a new sensor, xDrip+ appears to hang in the receive three sensor readings state and can take a long time to progress to calibration, sometimes never doing so. It hung like this for me for 24 hours and took a reinstall and six hour wait before it would calibrate. 

Following calibration, it only took readings every ten minutes and then lost connectivity and wouldn’t reconnect.

**Comment by jamorham** [comment]
Which data source are you using?

**Comment by jamorham** [comment]
Try the latest nightly and see if that improves things for you.

**Comment by tim2000s** [comment]
Using G5. Latest nightly never seems to get to 3 readings, hanging at 2.

**Comment by jamorham** [comment]
@tim2000s can you confirm that you are using the 6th Dec nightly? Which phone model are you using and are you using the OB1 G5 collector or the original one?

**Comment by tim2000s** [comment]
I have been using the 6th Dec nightly, a Sony Xperia X Compact and the OB1 G5 Collector. I uploaded a set of logs last night where I'd had it disconnect from the transmitter for hours.

**Comment by jamorham** [comment]
Can you try the Dec 15th nightly? https://github.com/NightscoutFoundation/xDrip/releases/download/2017.12.15b/xDrip-plus-20171215-a87d7b8.apk or select the Nightly update channel.


Thanks.

Jon

**Comment by tim2000s** [comment]
Will do.

**Comment by tim2000s** [comment]
That’s hung on the first radio button and hasn’t yet pulled any data. I’m probably going to go back to the Dexcom app just because I need it to loop, and will try again at the next sensor change.

**Comment by jamorham** [comment]
It implies you're not getting any data at all. I would be interested to know what you get in the G5 System Status page while this is happening. I appreciate if you have no time to test this, but please let me know if you get any more information.

**Comment by tim2000s** [comment]
@jamorham I’ve been doing some digging into this over the past couple of days. It seems to be affected by Android Wear. 

When Wear is installed, even without a watch connected, even if xDrip+ is not set to use Wear, it loses connectivity to the transmitter. As soon as i uninstall Wear, everything works.

**Comment by tim2000s** [comment]
For info - running on a Pixel with Android 8.1 and an active BT hotspot for OpenAPS.

**Comment by jamorham** [comment]
Does your wear installation have watches it would try to connect to configured? I found that having watches which wear was hunting for but not finding killed bluetooth.

**Comment by tim2000s** [comment]
I did a clean uninstall and forget of all watches. Then the transmitter stayed connected but when reinstalling Wear it couldn’t find the watch. It seems that 8.1 is rather more picky on some aspects of the Bluetooth front than perhaps older versions are. In the meantime the phone happily connected to an OpenAPS rig and Combo via Bluetooth.

**Comment by Navid200** [comment]
@tim2000s What is the status of this issue?

**Comment by Navid200** [comment]
Android and xDrip both have changed dramatically since this issue was opened.
If you have issues similar issues, please post in the support channels.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
