### ISSUE TITLE
Backfill missed G5 readings

### ISSUE THREAD

**Issue by MarkMpn** [NightscoutFoundation/xDrip#232]
After switching recently from the Dexcom Share app to xDrip+, the main difference/drawback we see is it not backfilling any readings that are missed while the phone is out of range of the sensor. Although the missed readings aren't helpful for immediate treatment, they are useful when looking back over trends to adjust basal rates etc.

I haven't done any Android or Bluetooth development before - I'd be happy to help out with developing this but I'd need someone to point me in the right direction to get started.

**Comment by jamorham** [comment]
This is a complex issue, back filling is not supported in the raw data collection mode which xDrip uses.

**Comment by TheDonDan** [comment]
+1

**Comment by triplem** [comment]
Since the same Algo as Dex is used, could this be implemented? This is a rather nice feature.

**Comment by pimeys** [comment]
This now works if you enable OB1 collector and native algorithm in the debug settings.

https://github.com/NightscoutFoundation/xDrip/wiki/Guide-for-using-OB1-G5-Internal-Algorithm-Feature

**Comment by Navid200** [comment]
@MarkMpn Is this still an issue?  
If not, would you please close the issue?
