### ISSUE TITLE
Nightly version 2122091407 & 2122091408

### ISSUE THREAD

**Issue by master3395** [NightscoutFoundation/xDrip#2347]
Hello.

I have a OnePlus 8 Pro Android 12.1
I have been trying to get the latest version of xDrip+ 2122091408.
But every time I try to install it.
It falls back to 2122091407, which I already have installed.

I restarted the phone, to make sure that wasn't an issue.
I have checked that all permissions are given to xdrip+ and everything is given.
I have tried external download and install, still says "finished" at the end, but it returns to 2122091407.

**Comment by Navid200** [comment]
Please don't use these issues as a first step when you have a problem.
Please, instead open a discussion as instructed when you attempted to open this issue.
https://github.com/NightscoutFoundation/xDrip/discussions
