### ISSUE TITLE
Pixel 2 compatibility issues?

### ISSUE THREAD

**Issue by BrianOrb** [NightscoutFoundation/xDrip#235]
I just got a pixel 2 and the version of xdrip+ I downloaded a few months ago (xDrip-plus-20171006-1a08760.apk) works fine.

But after it upgrades itself it stops collecting data and if I restart the sensor like I did this morning, it gets stuck on the collecting initial readings pop up.

I'm going to remove it and install the old version again to see if it start working again...

Information:

Phone: Google Pixel 2
Android: 8.0.0 Security patch Nov 5, 2017
Build: OPD1.170816.025

Working version: xDrip-plus-20171006-1a08760.apk
Failing version: xDrip-plus-20171113-20a4313.apk

Using Dexcom G5

Latest version worked on my Nexus 6P...

How can I help debug this?

**Comment by jamorham** [comment]
When you got stuck on the collecting initial readings what status information did it show? No readings at all or getting up to 2 etc?

Jon

**Comment by cduarte** [comment]
I am using moto g4 and with wxBridge Wixel
After I click at start sensor and chosse the date of start...
stay at this screen
![img_4978](https://user-images.githubusercontent.com/810062/33871743-f67f78d0-defa-11e7-91cf-de0fd9c69a2a.jpg)

**Comment by BrianOrb** [comment]
On mine, I believe it had all three circles filled in.

**Comment by jamorham** [comment]
Can you try the latest nightly to see if that resolves the issue:

https://github.com/NightscoutFoundation/xDrip/wiki/How-to-get-the-Nightlies-on-Automatic-Update

**Comment by taylor85b** [comment]
Just got my Dexcom today and I'm just learning that the Dexcom app is still incompatible with my Pixel 2.  How frustrating, anybody have an update?

**Comment by tobiasAPS** [comment]
On my Pixel 2 it also gets stuck on the collecting initial readings with no readings at all. I have just sent the logs, and hope this helps.

**Comment by tobiasAPS** [comment]
It's working now. The problem was that my Dexcom was still paired to my old my phone.

**Comment by jamorham** [comment]
Marking as resolved, please re-open if issues persist.

**Comment by jseaber** [comment]
> It's working now. The problem was that my Dexcom was still paired to my old my phone.

@tobiasAPS - Did you remember how you unpaired your old phone from your Dexcom? I tried xDrip's System Status -> "Forget Device" button on my old phone, but my new Pixel 2 still hasn't collected any readings after 30 minutes.
![screenshot_20181022-124658](https://user-images.githubusercontent.com/9965388/47309661-9e596880-d5fa-11e8-9095-7f9296a67224.png)

**Comment by jseaber** [comment]
Aha, the old phone managed to _not_ forget the device. Setting it to airplane mode, then hitting Forgot Device worked.

New phone is now collecting.

@jamorham - Bug ^^ ?
