### ISSUE TITLE
Adjust past not working when calibrating using BG from Bluetooth meter

### ISSUE THREAD

**Issue by TebbeUbben** [NightscoutFoundation/xDrip#236]

**Comment by Navid200** [comment]
Would you please update?
Is this still the case?
Are there any work-arounds?

**Comment by Navid200** [comment]
I'm not even sure what "Adjust past" is.
Please explain exactly what this is and we can reopen it if needed.

**Comment by tolot27** [comment]
"Adjust past" is simply "rewrite history". See https://github.com/NightscoutFoundation/xDrip/search?q=Adjust+past
