### ISSUE TITLE
Glycemia history graph - no detailed view possible back in the past

### ISSUE THREAD

**Issue by AliQ101** [NightscoutFoundation/xDrip#2411]
Discussed in https://github.com/NightscoutFoundation/xDrip/discussions/2410

**Subject of the issue**

It seems that there is something wrong in glycemia history graph view, I can see a full detail history only for 30 days back and then each one day more back is almost twice short in detailed view (with no possibility to extend).

I went through the Nightly releases chain and Nightly build 3rd Aug 2022, stable, https://github.com/NightscoutFoundation/xDrip/commit/e13a76ec2a89c287a9d61171e7c79e01b632c0de-2022.08.03 is the last version that is ok. 
Next Nightly build 18th Aug 2022, https://github.com/NightscoutFoundation/xDrip/commit/c649f9de2ba7c8fc5929ccad3d8c5526a937db3b-2022.08.18., has started the issue in glycemia history graph view.

**Environment**
I have tested with different mobiles (Android 9) and different data source (i.e. historical data was taken from G6, Libre1/MM1, Libre follower) with the same results.

**Why is needed**
We use notes (description of foods, activity, etc.) with combination of glycemia history graph to see what was reaction to some kind of foods/activity.

**Comment by jamorham** [comment]
I am testing a fix for this issue and will update when ready for wider testing. Hopefully only a few days.

**Comment by jamorham** [comment]
Please try the Nov 5th nightly to see if it resolves the problem. thanks

**Comment by jonprogers** [comment]
I was able to replicate this issue when it was logged but installing the Nov 5th nightly the problem has gone away so it looks fixed to me - thank you!

LG G5 running Android 8 with Dexcom G6 in native mode

**Comment by Navid200** [comment]
@AliQ101 Would you please try the November 5, 2022 release (https://github.com/NightscoutFoundation/xDrip/releases/tag/2022.11.05) and see if it fixes the problem?
It has for me.

**Comment by AliQ101** [comment]
Fixed also for me. Thanks, we can close the issue.

**Comment by Navid200** [comment]
@AliQ101 Thanks for reporting
