### ISSUE TITLE
Slope siempre en 1

### ISSUE THREAD

**Issue by Emisanduc** [NightscoutFoundation/xDrip#2439]
Buenos días, tuve que reinstalar la aplicación y desde entonces en el gráfico de calibración el slope siempre está en 1 y el intercept ronda entre -50 y -140 dependiendo la calibración. Se me está haciendo imposible mantener calibrado xdrip por lo que la funcionalidad de evitar la prueba capilar se perdió. Quisiera saber cómo puedo solucionar el inconveniente. Desde ya muchas gracias
![4BADE1E9-FA4E-4AB2-9641-58F55DB128FA](https://user-images.githubusercontent.com/96702567/200464716-cfbd7bd0-512a-41ba-929f-1a16528dd262.jpeg)

**Comment by Navid200** [comment]
Please do not open an issue.
Instead, please open a discussions here:  https://github.com/NightscoutFoundation/xDrip/discussions
