### ISSUE TITLE
Confirm alert will sometimes not snooze alert

### ISSUE THREAD

**Issue by tanja3981** [NightscoutFoundation/xDrip#247]
Every now and then I can not confirm an alert and reappears every minute. This happens with as well with snooze from my pebble
I need to confirm it several times before it keeps quiet until the snooze time is done.

**Comment by jamorham** [comment]
Can you check your System Status tab and let me know which version of xDrip you are using?

**Comment by tanja3981** [comment]
Here is the current system status which includes the version. (should be
the latest stable).

Let me know if you need anything else.

Am 02.01.2018 13:01 schrieb "JamOrHam" <notifications@github.com>:

Can you check your System Status tab and let me know which version of xDrip
you are using?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/NightscoutFoundation/xDrip/issues/247#issuecomment-354752780>,
or mute the thread

**Comment by jamorham** [comment]
Can you try with the latest nightly: https://github.com/NightscoutFoundation/xDrip/wiki/How-to-get-the-Nightlies-on-Automatic-Update and let me know whether this is still a problem? Thanks

**Comment by tanja3981** [comment]
The issue seems to be fixed.
although it didn't occur on every alarm, I tried it for 2 days now and it happened once again.
thanks!
