### ISSUE TITLE
Aidex - When Aidex is used, number and arrow is not displayed

### ISSUE THREAD

**Issue by jamorham** [NightscoutFoundation/xDrip#2470]
### Discussed in https://github.com/NightscoutFoundation/xDrip/discussions/2469

<div type='discussions-op-text'>

<sup>Originally posted by **andyrozman** November 16, 2022</sup>
If Aidex is used as source, Number and arrows are not displayed... 

Is this configuration problem (something not configured correctly) or is problem with my integration... This was my 1st help to Xdrip project in last 7 years (I did something small about 8 yrs ago I think) and I might have done something wrong... 

Any help with this would be welcome</div>

**Comment by jamorham** [comment]
PR reference: https://github.com/NightscoutFoundation/xDrip/pull/2312

**Comment by jamorham** [comment]
@andyrozman does this fix the problem: https://github.com/NightscoutFoundation/xDrip/commit/344deb4be19d42886f53a9064e3497bc4ad8ee1b ? available in today's nightly.

**Comment by jiresongit** [comment]
> @andyrozman does this fix the problem: [344deb4](https://github.com/NightscoutFoundation/xDrip/commit/344deb4be19d42886f53a9064e3497bc4ad8ee1b) ? available in today's nightly.

Yes this fixes for me, thx.

![Screenshot_2022-11-16-21-19-57-222_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/78233260/202297255-4b6971dc-afe6-4e15-8be8-d909cfe3a60b.jpg)

**Comment by jamorham** [comment]
Can we confirm this issue is fully fixed so I can close this issue? thanks

**Comment by Navid200** [comment]
@andyrozman  Would you please tell us if this has been fixed for you using the latest nightly?
Thanks

**Comment by andyrozman** [comment]
Yes. Sorry about not notifying you. 

Issue seems to be fixed. Several users reported that now value is displayed for them. Thank you for such fast fix.

This issue can be closed.

**Comment by Navid200** [comment]
Wonderful, thanks for confirmation and thanks to JamOrHam for fixing it.
I take the liberty of closing the issue then.
Thanks
