### ISSUE TITLE
New feature request - Add GVI and PGS calculations in Statistics and History

### ISSUE THREAD

**Issue by kskandispersonal** [NightscoutFoundation/xDrip#248]
Nightscout has added these new metrics to measure glycemic variability index, and patient glycemic status.  I think it would be useful for xDrip+ users as well to view in Statistics and History.

https://www.healthline.com/diabetesmine/a-new-view-of-glycemic-variability-how-long-is-your-line#3

**Comment by AdrianLxM** [comment]
I absolutely agree!

@sulkaharo, how did you do the smoothing before the data gets processed? It would be really nice if you could point us to the sourcecode in cgm-remote-monitor!

**Comment by kskandispersonal** [comment]
I'm adding this feature based on NS' implementation.  However, I'm getting different results from NS as compared to xDrip+ using my own db.  # of readings below, in and above seem to be off from NS, sometimes significantly over more than a day.  One reason might be that NS does NOT exclude BGs < sensor threshold, `where("calculated_value > " + CUTOFF)`.  I know for me I have quite a few lows over time, and by excluding this number, GVI and PGS will be off.  xDrip excludes this number for Status line, History and Stats.  Would it make sense to make its exclusion a preference instead?  So that for those who have frequent lows, these values can be included in the Stats and History?

**Comment by jamorham** [comment]
Does this now work? Can I mark this as resolved?

**Comment by sulkaharo** [comment]
@kskandispersonal I should hide the data showing the number of records in Nightscout as those are not correct after filtering happens. Do the percentages match roughly? The intent with the NS filtering was to remove the worst noisy records and the effect of single missing records. Was the issue mentioned above that data above and below certain thresholds should be filtered out?

**Comment by AdrianLxM** [comment]
@sulkaharo xDrip treat everything < 39 as special value (error state) as  LOW get mapped to 39 and there is nothing below LOW. If those values will be used in Nightscout, then the statistics will be different.

I've added the same two filter passes to xDrip like you did to Nightscout now.

**Comment by kskandispersonal** [comment]
Yes, xDrip results match pretty close to NS now after Adrian added your two filters.  Thanks to you both!!

Eg (from my DB):
7 Days
NS  GVI 1.21 PGS 35.62
xDrip GVI 1.18 PGS 34.26
30 Days
NS  GVI 1.23 PGS 37.52
xDrip: 1.18 PGS 37.38
90 Days
NS GVI 1.22 PGS 29.21
xDrip: 1.19 PGS 30.35

**Comment by dv1** [comment]
One comment on this. Using the defined time in range for PGS seems odd, since both GVI and PGS are supposed to reflect how close (or far away) your BG control is to that of a non-diabetic. With that in mind, I think PGS calculation should _not_ involve the defined range, but either a hardcoded 70-110 range, or a second configurable range just for PGS.

**Comment by feikmeyer** [comment]
I have a question: Is the PGS (patient glycemic status) the same as the PGS (personal glycemic state) defined here: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5467104/ ?

Where can I find information on how the patient glycemic status is calculated?

**Comment by ireneusz-ptak** [comment]
@kskandispersonal: Same question from me - calculated PGS value seems too high, especially if you take a look at this graph with sample PGS values: 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5467104/figure/f4/

**Comment by kameamea** [comment]
The PGS value in xdrip depends on your personal upper and lower limits. Try lowering your upper limit from 180mg/dL to 120mg/dL and you'll see an dramatic increase in your PGS statistics value.
This makes no sense at all.
I guess this article describes the PGS concept:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5467104/
This article states:
... percent time in range (70–180 mg/dL) ...
So those limits should be used in xdrip as well for PGS calculation

**Comment by dv1** [comment]
> However the first article states:
> ... percent time in range (70–180 mg/dL) ...
> So those limits should be used in xdrip as well for PGS calculation I guess

I agree. Otherwise, the PGS is barely useful. A "bad" PGS due to a poor time in range could actually reflect better BG control due to the range being something like 70-110, while a "good" PGS with high time in range would actually reflect poor control due to a range of 40-400.

The 70-180 range is a consensus made by the ADA and others. Let's use that.

**Comment by tolot27** [comment]
Merged with #283 thus, closing it.
