### ISSUE TITLE
No fata from CamAPS 

### ISSUE THREAD

**Issue by challengediabetes** [NightscoutFoundation/xDrip#2482]
When I choose connection method "Companion App ", No data is transferred/read into xDrip.  Over a period of 24h only 1 or 2 readings are comming through and these are not correct.

I have tried different versions without any luck.
I run XDrip  and CamAPS on a galaxy S10 with Android 12

What can I do to get my BG readings on my Garmin fenix?

**Comment by steve8x8** [comment]
https://bionicwookiee.com/2022/08/21/mixing-camaps-with-xdrip/ has a tested procedure - did you omit allowing xDrip to read notifications, or have notifications themselves been tampered with?

**Comment by Navid200** [comment]
Please don't open an issue unless when you are asked  by a developer.  
Please open a discussion instead:  https://github.com/NightscoutFoundation/xDrip/discussions
If you are asked to open an issue, please include a link to the discussion.
