### ISSUE TITLE
always keep wifi on during sleep Android 13

### ISSUE THREAD

**Issue by jamorham** [NightscoutFoundation/xDrip#2495]
### Discussed in https://github.com/NightscoutFoundation/xDrip/discussions/2485

<div type='discussions-op-text'>

<sup>Originally posted by **master3395** November 21, 2022</sup>
Hello, i have noticed that with the latest Android 13
You will get annoying messages about enabling "always keep wifi on during sleep".
But this option was removed after Android 12. (Not just Samsung like pointed out on the site below, I use OnePlus)
https://eu.community.samsung.com/t5/galaxy-s21-series/wifi-keep-on-during-sleep-setting-missing-after-latest-update/td-p/5152555

This warning comes from time to time.
I have given xDrip+ all perms that it asks for and more.

```
xDrip+ 
Version: 344deb4-2022.11.16
Code: 202211618
```

![image](https://user-images.githubusercontent.com/4199669/202935185-98aa46e8-7b30-4e6c-b290-4afd5f59780d.png)
</div>

**Comment by jamorham** [comment]
This should be resolved in the Nov 27th nightly. Please confirm? thanks

**Comment by Navid200** [comment]
@master3395
Would you please update to the Nov 27 release and report if the problem has been resolved?

**Comment by master3395** [comment]
> 

I have not gotten any popups for 2 hours, it seems to be fine now.
![image](https://user-images.githubusercontent.com/4199669/204150264-da549d0b-8238-4070-ab08-cabad4c53b89.png)

**Comment by Navid200** [comment]
@master3395 
Thanks,
We can always reopen this issue if needed.
Please report here if you get that pop-up again with this release or any after.
