### ISSUE TITLE
wanted to move from heroku to google cloud issus with opening the virtual monitor next day

### ISSUE THREAD

**Issue by Tinawenn** [NightscoutFoundation/xDrip#2496]
I wanted to bring nightscout to google cloud. 
I began yesterday. Today I wanted complete in when I click on SSH in the virtual machine instanze I end up with this failure. But I don't understand it. Did I somethin wrong? What to do now? I was on point 4 according the installation manual. When I stoped yesterday I was not sure wether I typed in the right  user ID and passwort. But now i cannot go on.

Thank you for your help!

Sie sind nicht berechtigt, eine SSH-Verbindung zu dieser Instanz herzustellen. Sie benötigen die folgende IAM-Berechtigung: compute.instances.setMetadata.

**Comment by tzachi-dar** [comment]
Please try that again (if you haven't done that).
If this does not help, please try to restart the machine (it can be done on the right side next to the ssh, there are 3 dots. presses on them and select shutdown, and then start).

**Comment by Tinawenn** [comment]
Now I got the informatin about a problem with my billing method.
Account shows 0,00 EUR, shows the credit card number. I received also a e-mail with request to send a photo of credit card and passoport -> sent it to them. But problem still exits.
I've choosen Oregon because South Carolina and Iowa didn't work. 

nightscout konnte nicht gestartet werden: This API method requires billing to be enabled. Please enable billing on project #529774726142 by visiting https://console.developers.google.com/billing/enable?project=529774726142 then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry.

**Comment by Tinawenn** [comment]
After confirming payment terms a few times and logout and login in google it is possible to continou. Mabye they changed the pament conditions? Or free services?
When I had choosen Iowa or South Caroline there was the failure message that is is not free with "one of the options" I had choosen for the virtual machine or operating setup, according to the manual. Maybe it was the e2-micro.

**Comment by tzachi-dar** [comment]
If status is showing something in red, you will probably have to pay for the machine.
Make sure to install in a free zone.
I think there are still places on the west regions - us-west1-b

**Comment by Tinawenn** [comment]
There was nothing in red. And open amounts are 0,00 EUR.

**Comment by Navid200** [comment]
@Tinawenn Please don't open an issue as a first step.  Instead please use discussions.  
https://github.com/NightscoutFoundation/xDrip/discussions

Please don't use issues to consult with developers.
We now have discussions open.
Please let us encourage users to use discussions instead of encouraging them to open an issue as soon as they have an unexpected experience.

**Comment by Navid200** [comment]
Please don't continue this conversation here.
