### ISSUE TITLE
Question - How to compile and obtain the apk file?

### ISSUE THREAD

**Issue by Hexonium** [NightscoutFoundation/xDrip#250]
I would help to improve the french translation for xDrip+, but I don't know how to compile and get the apk file (in order to test my changes). Could someone explain how to do it? Thank you :)

**Comment by tzachi-dar** [comment]
To get the code start with:
git clone https://github.com/NightscoutFoundation/xDrip.git

From here I think that the simplest way will be to install android studio, and let it compile it. (file open and point to that directory).

A different way, is to write "gradlew build" in the root directory, but if you did not compile any android program on your computer you will have to install an sdk.

**Comment by AdrianLxM** [comment]
The AndroidAPS Wiki has a guide how to build AndroidAPS with Android Studio.
http://androidaps.org

You can basically do the same with xDrip in this repository.

**Comment by Hexonium** [comment]
Thanks, it works! I had to downgrade from java 9 to java 8.
