### ISSUE TITLE
Samsung S22 Android 13 (Xdrip version e1376e-2022.08.03) Blue tooth drop outs 

### ISSUE THREAD

**Issue by andrewkerr1991** [NightscoutFoundation/xDrip#2523]
Hi There, 

Navid Fo has kindly been supporting me on X drip FB group but has asked me to post on here as we are running out of ideas. 

I am running Xdrip version e1376e-2022.08.03 on a Samsung S22 ( photos attached for reference) , every night I am getting a drop out which is disconnecting X drip and Android APS.  I have followed the suggestions on the guide below and all settings in x drip are set as per G6 guide (bluetooth & other misc options)

https://navid200.github.io/xDrip/docs/Intermittent?fbclid=IwAR1YFO-i5TLiCsqy9fPYSHXXAtTRAs_ZdBFkDZPEkxs08wNvXd9NLRsNTj0

Here is the link to the FB discussion for reference also. 

https://www.facebook.com/groups/xDripG5/posts/8298621840211238/?comment_id=8298775933529162&reply_comment_id=8311128955627193&notif_id=1669842195940451&notif_t=group_comment_mention

I have attached the screenshots of xdrip version and event logs, so hopefully this will help. 

Does anyone have any ideas how I can stop this drop out ? 

![Bluetooth settings](https://user-images.githubusercontent.com/59082024/205458380-4f420434-a757-4e2f-a1e7-e11ae23c5df6.jpg)
![Debug settings 1](https://user-images.githubusercontent.com/59082024/205458382-aa6c77c6-c3b1-4b42-b114-62f451f72155.jpg)
![Debug settings 2](https://user-images.githubusercontent.com/59082024/205458384-cd745805-1eb6-4ed1-8124-41234e10dfca.jpg)
![Debug settings](https://user-images.githubusercontent.com/59082024/205458385-a77c3e66-943e-4702-ab64-d08a56efd82e.jpg)
![Event log 1](https://user-images.githubusercontent.com/59082024/205458386-4c11a734-2a09-4c55-a9d6-6dcc9fe3faff.jpg)
![event log 2](https://user-images.githubusercontent.com/59082024/205458387-96b76ce1-d047-4e6a-a943-d2ee10183280.jpg)
![event log 3](https://user-images.githubusercontent.com/59082024/205458388-ede08952-f42b-4a35-93e6-684b6c2738de.jpg)
![event log 4](https://user-images.githubusercontent.com/59082024/205458389-0da2b47d-a1be-4cf5-be06-81ce416902b1.jpg)
![event log](https://user-images.githubusercontent.com/59082024/205458390-dc037ba7-b102-43b5-b7aa-8f98c9b4702b.jpg)
![other misc options](https://user-images.githubusercontent.com/59082024/205458391-e6f50a30-6003-46c0-b4a7-566b57e8d88a.jpg)
![S22](https://user-images.githubusercontent.com/59082024/205458394-f3a3fbae-8e42-457a-b6a0-10a0ee575e54.jpg)
![Xdrip system status](https://user-images.githubusercontent.com/59082024/205458395-f6eb76ba-ce13-47c7-a8c6-e25463e3a27f.jpg)

Thanks

Andrew

**Comment by Navid200** [comment]
Please pay attention to the instructions.
Never open an issue when you are asked to open a discussion and are given a link to it.
Here it is again:
https://github.com/NightscoutFoundation/xDrip/discussions
