### ISSUE TITLE
Blucon Connected but no Values

### ISSUE THREAD

**Issue by alwayssimifuzi** [NightscoutFoundation/xDrip#253]
Hey!
My Blucon is connected (New Battery from Varta, CR2032) but there are noe Values.
I tried changing the Freestyle Libre, but doesn't change anything.

There is no other App.

Log says: Got Nack on cmd 010d0900 and Libre Sensor has been removed, its direct above my Libre, with NFC I get Values.

![image](https://user-images.githubusercontent.com/34485830/34471006-a2c143ba-ef3d-11e7-9b43-531f461df9b3.png)

Would be very nice if someone can help me :)

**Comment by jamorham** [comment]
@gregorybel @keencave  any ideas?

**Comment by alwayssimifuzi** [comment]
I also contacted Ambrosiasys, it doesn't Work with Linkblucon App

**Comment by gregorybel** [comment]
Then your Blucon might be unfortunately broken. 
Or is there a pairing issue? Can you delete the pairing and pair again? Under BT status, does it show 'bonded'?

**Comment by tzachi-dar** [comment]
It seems like there is pairing, but it says libre sensor is out.
Can you measure the voltage of the battery (or simply try another one?)

**Comment by alwayssimifuzi** [comment]
Yep, there is a pairing. The Battery is brand New, manufacturer is VARTA, I'll try another new one.

**Comment by alwayssimifuzi** [comment]
Closed - The Device is broken, now I have to send it to Ambrosiasys, they will replace it.
