### ISSUE TITLE
Web Server header responses CR+LF issue

### ISSUE THREAD

**Issue by gazhay** [NightscoutFoundation/xDrip#2549]
From :- 
[Discussion](https://github.com/NightscoutFoundation/xDrip/discussions/2445#discussioncomment-4382163)

I use xDrip with a libre2, however I wanted to display the latest sugar on screen during zwift cycling.

To do this I used node to fetch the url
http://<phoneip>:<xdripPort>/pebble

The return from the GET has invalid headers.
Protocol states headers are followed by \r and \n they seem to only contain \n

Node throws an insecure header violation.
Other programmatic GET libraries do the same. You can force some to ignore the insecure header response, but it seems inadvisable to disable security for a whole node application to deal with this one invalid response.

Would seem the correct solution is to have xdrip response use the CR-LF specified in the protocol?

There may be compatibility issues in fixing this, so it may be advisable to expose these responses on a different port number or enable a flag within the settings to enable this mode?

**Comment by jamorham** [comment]
Please try July 8th nightly which should resolve the issue.

**Comment by Navid200** [comment]
@gazhay 
Would you please test?

**Comment by Navid200** [comment]
We can reopen if needed.  But, changes have been made to address this concern and unless they are tested, we cannot keep this open.
