### ISSUE TITLE
Blucon can not pair at a standalone smartwatch and an android tablet

### ISSUE THREAD

**Issue by dimis28** [NightscoutFoundation/xDrip#255]
Dear All,

Since now i have used the blucon at my lg mobilephone without any problem. I have bought an android tablet and a standalone android smartwatch but blucon does not pair either with the tablet neither with the smartwatch. I do not try to connect all the devices at the same time. For example at the smartwatch other the other devices was inactive...and when i am trying to connect from bluetooth option of the smartwatch it is says wrond password key....any thoughts??? from xdrip status i insert the pin but it is not bonded at all....any thoughts??? 
![26197841_1679973895382716_3072841371593373285_o](https://user-images.githubusercontent.com/21019084/34496070-cc7ddcae-f000-11e7-9d9b-8121ae2a89d6.jpg)

**Comment by gregorybel** [comment]
did you delete pairing from your LG phone?

**Comment by dimis28** [comment]
![26231187_1680565945323511_2577969189723383043_n](https://user-images.githubusercontent.com/21019084/34513769-8a4cd9e4-f072-11e7-9a0a-26e6c706e8c8.jpg)
![26166986_1680565891990183_7648117871052953243_n](https://user-images.githubusercontent.com/21019084/34513770-8a81a836-f072-11e7-9d67-740b1537ac96.jpg)
![26167622_1680565818656857_167502423296422486_n](https://user-images.githubusercontent.com/21019084/34513771-8aaf0bfa-f072-11e7-80a2-0e7b267d5128.jpg)
![26220046_1680565748656864_107635456180128668_n](https://user-images.githubusercontent.com/21019084/34513772-8ad8010e-f072-11e7-9c7e-e425e1cd6da1.jpg)

**Comment by dimis28** [comment]
Manage to unpair blucon with my lg....when i am inserting blucon 6.digits at xdrip message status down.at center xdrip pairing....at system status blucon is not connected when i tap to bond this probably work at hm10 device.it would take 1 minute. I am trying to connect directly blucon at a standalone cellurar smartwatch any thoughts?

**Comment by dimis28** [comment]
the model of the smartwatch is here https://www.lightinthebox.com/hhyn8-smart-watch-wireless-charging-android-5-1-system-wifi-gps-2g-3g-call-500w-hd-camera-can-download-and-install-applications-independently_p6021947.html ... please help me is for my 8 yeas old son!

**Comment by gregorybel** [comment]
Are you sure you have deleted pairing from your LG phone? you need to make sure Blucon is not connected to another devices. Go BT settings and remove Blucon device.

best is you delete pairing from all 3 devices.

then you need to pair from within xdrip, not from BT settings.

**Comment by gregorybel** [comment]
Look Here https://github.com/gregorybel/xDrip-plus/wiki/How-to-use-Blukon-with-xdrip

**Comment by dimis28** [comment]
My dear Grecory i have all the other device  competely inactive..i have remove the battery from blucon for 30 seconds and try to pair directly from xdrip....the worlds bonded and paired are the same one? I am asking you this because when  i insert the 6 digits from xdirp via bluetooth scan a message at the center of xdrip shows and it says pairing....and when i am scanning the only device that founds my smartwatch is the blucon !!!!

**Comment by dimis28** [comment]
Gregory any other thoughts?

**Comment by gregorybel** [comment]
yes: now we need logs. would you be able to send logcat? if yes, we need all logs containing Dex and GATT during scan and pairing.

I think this kind of watch has BT issue.

thanks

**Comment by dimis28** [comment]
![26732713_1685612368152202_98849296_o](https://user-images.githubusercontent.com/21019084/34649687-d98a7df4-f3ab-11e7-833c-5d79d5c886db.jpg)

**Comment by dimis28** [comment]
I think that i have understand the problem. Can you change this screen so i can scroll down and see the forget device? If you do that i could press forget device at xdrip. And this is because i reset the smartwatch factory settings. I have done a test if i go first from bt settings of the smartwatch it is paired (i can press the forget device as also). But if i go first at xdrip and do bluetooth scan i enderen the blucon's pin and then it tries to paired automatically and says at xdrip screen meny wrong pin even i insert it correctly. So i suggest if i you change the menu at this screen and i am able to press forget i will manage to bonded it first from xdrip. It looks like the smartwatch tries to bond at the same time itself at xdrip and at the bt settings. Could you fix this screen for me? Also i have the same problem when i see the screen at the 3 first reading i can not see all the screen.
