### ISSUE TITLE
xDrip did not spoke the trend after activating the setting in last nigthly (05.01)

### ISSUE THREAD

**Issue by MasterPlexus** [NightscoutFoundation/xDrip#257]
The trend will be not used after put the setting on "bg_to_speech_trend". Activated the extra Logging for BgToSpeech:v, which shows no more information, and only output for example "Calculated text: 102"

I'm on german language, but seen that the trend at the moment is hardcoded given without translation, so I did not expect that this is the problem.

Stopping at the moment, as this is not my class, but if you want I can investigate further at evening (if no other has time for it wich are more familiar with the class)

**Comment by jamorham** [comment]
Can you describe what you heard and what you expected to hear? If you enable the speech it should then speak an example so testing should be easy.

**Comment by MasterPlexus** [comment]
I expect to hear the glucose value, and in addition the trend. This is new implemented as far as I see, and I activated it in the speech setting area. The value is spoken, but not the trend arrow...

**Comment by jamorham** [comment]
Can you recheck this in the latest nightly? When you switch on the speak readings setting it should speak an example after a few seconds as well.

**Comment by MasterPlexus** [comment]
I tested it. The result is:
- set "speak trend arrow name" to marked: "einhudertsechzig"
- set also "speak glucose value twice" to marked: "einhundertsechzig"
- set "Speak everything twice" to marked: "einhudertsechzig einhundertsechzig"
- same behavior if a new value was read

So for me it looks like the to first two markable settings after the on/off switch are not respected but the "everything twice" is respected. So the question is, is that only on my phone, or did other have the same issue? Did you hear the arrow name?

**Comment by MasterPlexus** [comment]
OK, I found the point which is wrong. In bgSpeach the constructtext is not right maintained, because the trend will be added only if not mgdl is used (so only in mol it will be add). I'll change that, and will also try to implement translation, and will made than a Pull request if ok for you.

**Comment by jamorham** [comment]
Ok this is very useful, can you point me to the line of code concerned? Yes translation would be good too.

Thanks.

**Comment by MasterPlexus** [comment]
Its set in the elseclause which handles only if mgdl is not true:
https://github.com/NightscoutFoundation/xDrip/blob/74b02dedb1b3d3ec7db02f21d8e9d97618c42cb3/app/src/main/java/com/eveningoutpost/dexdrip/utils/BgToSpeech.java#L114

and also this line for double speak:
https://github.com/NightscoutFoundation/xDrip/blob/74b02dedb1b3d3ec7db02f21d8e9d97618c42cb3/app/src/main/java/com/eveningoutpost/dexdrip/utils/BgToSpeech.java#L121

this should put to the end.

Unfortunately I have a small lack in my knowledge about using the getString(R.String.xxx) within a static function. Did you implement a standard way within xDrip+ to make it possible to use the app resource, or did I have to made a special context Class for it?

**Comment by jamorham** [comment]
```
  xdrip.getAppContext().getString(R.string....)

```

**Comment by jamorham** [comment]
^ Nice catch on the if/else I was blind to that when I checked earlier!

**Comment by MasterPlexus** [comment]
Somtimes it is in that way... Blind for the mistaces we made. Could not count the time of bugs I created wich are quite simple, but not viewable forme. And if I found them later, I could cry ;)

Anyhow, startet to implement the translate. Will give tomorrow the pull request after some tests.

**Comment by jamorham** [comment]
Ok, I want to include the fix in today's nightly so I will commit the fix for trend and repeat twice and I would be very grateful if you can contribute the strings and translation.

**Comment by MasterPlexus** [comment]
Oh, I was faster then I think ;) May you can use this pull:
https://github.com/NightscoutFoundation/xDrip/pull/276
