### ISSUE TITLE
Questions on using xDrip with Dexcom G6

### ISSUE THREAD

**Issue by ClaudeVernier** [NightscoutFoundation/xDrip#2581]
Hello 
I hope this is the right place sorry if not.

I use xDrip+ since months with FSL2, OOP and AAPS.
I just started using Dexcom G6 in France.
At the hospital, they had me install the Dexcom app and also the app MyDiabby where they can follow my data.  This app gets data from the Dexcom, using another app: Clarity.

I heard that since june, your app can get data directly from the Dexcom but I'm not sure of the version I have, is there two different xDrip, can I simply upgrade... 
Also, I wonder if you had tests or feedback of cases where we can continue using MyDiabby and Clarity ? 
Attached is my version of xDrip.

Thanks for all the great work.
![inbound6138255226852580914](https://user-images.githubusercontent.com/3709997/209564416-6d610f90-b655-4a8e-b2aa-f79e871e4434.jpg)

**Comment by Navid200** [comment]
Please do NOT open an issue unless you are told be a developer.  You must have seen this request when you opened this issue.  

You can open a discussion if you have a question:  https://github.com/NightscoutFoundation/xDrip/discussions
