### ISSUE TITLE
Tidepool Authentication API Deprecation

### ISSUE THREAD

**Issue by toddkazakov** [NightscoutFoundation/xDrip#2597]
### Discussed in https://github.com/NightscoutFoundation/xDrip/discussions/2596

<div type='discussions-op-text'>

<sup>Originally posted by **toddkazakov** January  3, 2023</sup>
Hello, I am the lead backend developer at Tidepool. In December 2022 we replaced our legacy authentication system with  Keycloak. As a result, the existing API endpoints are deprecated, but we noticed that they are heavily used xDrip. As we are trying to completely retire the old system, all applications should migrate to the new OpenID Connect compatible implementation.

We don't have timeframe for the removal of the old APIs, but the way xDrip currently utilizes the APIs puts a strain on the new system (existing APIs act as proxy), because it starts a new auth session every time it requires a fresh token, instead of refreshing the session token directly.

I'll be more than happy to assist with setting up an integration/production environment client for the application. Any OIDC compatible library can be used (e.g. https://github.com/openid/AppAuth-Android). Let me know what's the best way to proceed.

</div>

**Comment by jamorham** [comment]
Can you provide more information? For example how the new authentication flow works so that we can determine the changes which would be required in xDrip?

**Comment by toddkazakov** [comment]
Hey @jamorham. The new system supports the standard OpenID Connect flows, e.g.:
- Open a browser to authenticate the user at https://auth.tidepool.org or https://auth.integration.tidepool.org
- The authorization servcer will redirect the user to xDrip using a custom scheme 
- xDrip will receive an authorization code from the redirect
- The authorization code can then be exchanged for an access and refresh token pair
- Access tokens are short-lived (valid for 1 to 5 minutes) and can be renewed using the refresh token obtained in the previous step. 
- To disconnect a user from Tidepool, the refresh token can be revoked, which will terminate the user session.
- Users have the ability to terminate sessions server-side, which will invalidate the refresh token. To obtain a fresh token pair, this process must be repeated from the beginning.

You can check https://github.com/openid/AppAuth-Android#implementing-the-authorization-code-flow for an example how to implement this. I can set up an OpenID client on the integration server when you are ready to work on this.

**Comment by jamorham** [comment]
Is it possible to do this without a web browser? I can imagine that it could introduce the possibility for errors relating to the user's choice of browser component or security issues from the same.  

I get 404 errors on both the above listed auth URLs.

Please go ahead and set up test credentials and send privately to jamorham at gmail

thanks

**Comment by gazhay** [comment]
Something like this?
https://github.com/openid/AppAuth-Android

**Comment by toddkazakov** [comment]
@jamorham there's no way to this without a web browser. This is the de-facto standard for authenticating against a third-party provider (e.g. sign in with Google or Facebook) and there aren't any inherent compatibility or security issues related to the choice of browser. I can give you few examples why it's important for authentication to happen in a web browser - in the near future we'll allow users to enable Multi-Factor authentication, so after they enter their username/password credentials, they'll also be prompted to enter a verification code (could be sent by SMS or obtained from Google authenticator app). Additionally, we might enable sign in/sign up with social providers, so we can't possibly ask all of our partners/clients to implement this functionality. If those flows are fully handled as an interactive browser experience, we can implement them once, and let client only deal with the bear minimum (i.e. implementing the OpenID Connect flow which delegates the authentication and authorization to Tidepool).

To create a client, I'll need to configure the redirect URL. Do you have any preference? Does `xdrip://callback/tidepool` work for you?

@gazhay yes, that's a reference implementation and I suggest you use it for the xDrip integration.

**Comment by jamorham** [comment]
@toddkazakov Hi, Sure I understand the reason for the approach. I was asking about whether browser is required because normally the user wouldn't leave xDrip to login to anything. Even with google sign-in this is done within the app itself.  

My main concern is that of compatibility that users may have installed or receive bundled any range of incompatible or insecure browsers (for example those that pipe all the data via their own http proxy) - Indeed the AppAuth-Android package has workarounds and lists for allowed/buggy browser implementations from what I can see looking at it. 

This is a potential can of worms I would prefer to avoid but it sounds like it isn't possible to... xDrip does things like wrap the TLS stack so that we can support TLS 1.2 even down to Android 5. I'm not sure a bundled browser on an old phone has the same chance of working reliably.

The url scheme you suggest is fine, however I am also not sure what the implications are for when users have multiple copies of xDrip installed (eg using variants) and how that will handle the callback.

**Comment by emmatovar27** [comment]
Hi @toddkazakov do you think is possible to add a client id for AAPS too? I'm currently working in the integration of AAPS and Tidepool. There are AAPS users that don't use xDrip+ and can benefited to upload directly from AAPS. :)

**Comment by toddkazakov** [comment]
@emmatovar27 I added a new client with client id `aaps` with redirect uri `aaps://callback/tidepool`. All endpoints are the same as above.

For both AAPS and xDrip, you should include `offline_access` in the list of scopes when making the initial authorization request in order to obtain a refresh token. The refresh token can then be used to get a new access token when the old one expires using an API call to the token endpoint.

**Comment by jamorham** [comment]
@toddkazakov what is the protocol/procedure for utilizing the authorization code?

**Comment by toddkazakov** [comment]
Here's a rough (and simplified) outline how the authentication flow works:
1. Open an in-app browser at the authorization endpoint e.g. `https://auth.integration.tidepool.org/realms/integration/protocol/openid-connect/auth?client_id=xdrip&response_type=code&redirect_uri=xdrip://callback/tidepool&scope=openid%20data_read%20data_write%20offline_access`
2. Tidepool will prompt the user for their username/password
3. On successful authentication, Tidepool will redirect the user to the `redirect_uri` specified above and will pass the `authorization_code` as a query parameter to the `redirect_uri`
4. xDrip will intercept the redirect to the custom scheme and will obtain the `authorization_code` from the query parameters
5. xDrip will exchange the `authorization_code` for access and refresh token at the token endpoint by making a `POST` request with to https://auth.integration.tidepool.org/realms/integration/protocol/openid-connect/token
6. The validity period of the access token is relatively short (e.g. from 1 minute to 10 minutes, and is determined by the auth server). To obtain a fresh access token, xDrip can make a subsequent `POST` request to the token endpoint by passing the refresh token that was obtained in 5.

For native applications, it's important to use this flow called PKCE. You can find more info [here](https://auth.integration.tidepool.org/realms/integration/protocol/openid-connect/token).

All of the above is generally handled by the authentication library you choose. You'd only need to pass the configuration options, e.g.:
```java
AuthorizationServiceConfiguration serviceConfig =
    new AuthorizationServiceConfiguration(
        Uri.parse("https://auth.integration.tidepool.org/realms/integration/protocol/openid-connect/auth"), // authorization endpoint
        Uri.parse("https://auth.integration.tidepool.org/realms/integration/protocol/openid-connect/token")); // token endpoint

AuthorizationRequest.Builder authRequestBuilder =
    new AuthorizationRequest.Builder(
        serviceConfig, // the authorization service configuration
        "xdrip", // the client ID, typically pre-registered and static
        ResponseTypeValues.CODE, // the response_type value: we want a code
        "xdrip://callback/tidepool"); // the redirect URI to which the auth response is sent

String codeVerifierChallengeMethod = "S256"
String messageDigestAlgorithm = "SHA-256"

SecureRandom secureRandom = new SecureRandom();
byte[] bytes = new byte[64];
secureRandom.nextBytes(bytes);

val encoding = Base64.URL_SAFE | Base64.NO_PADDING | Base64.NO_WRAP
val codeVerifier = Base64.encodeToString(bytes, encoding)

MessageDigest digest = MessageDigest.getInstance(messageDigestAlgorithm)
byte[] hash = digest.digest(codeVerifier.toByteArray())
String codeChallenge = Base64.encodeToString(hash, encoding)

AuthorizationRequest authRequest = authRequestBuilder
    .setScope("openid email data_read data_write offline_access")
    .setCodeVerifier(codeVerifier, codeChallenge, codeVerifierChallengeMethod)
    .build();

**Comment by jamorham** [comment]
@toddkazakov With the old style login we would receive a `userid` field. Where is this obtained after using the new login flow? I assume we should be following the same procedure to start a session etc?

**Comment by jamorham** [comment]
@toddkazakov Do you have any more information about how we get the userid with the new flow or am I misunderstanding which steps need replacing with the new authentication mechanism?

**Comment by toddkazakov** [comment]
@jamorham you can get the user id by calling the userinfo endpoint (e.g. https://auth.integration.tidepool.org/realms/integration/protocol/openid-connect/userinfo) with the access token you obtained passed in the authorization header (`Authorization: Bearer access_token_goes_here`).

**Comment by jamorham** [comment]
@toddkazakov Okay I think I have this working now. How frequently might we need to refresh the authorization code because I don't think that can happen when the user is not present? thanks

**Comment by jamorham** [comment]
@toddkazakov any advice? for what to put for the production url? See my question above

**Comment by toddkazakov** [comment]
@jamorham the production url is https://auth.tidepool.org/realms/tidepool, however it's not enabled yet

**Comment by jamorham** [comment]
@toddkazakov I thought the old authentication was deprecated? I was expecting that we should transition to the new authentication. When can we do this? thanks.

**Comment by toddkazakov** [comment]
The production environment is not enabled for the xDrip client. I'd like to take a look at the implementation before I flip the switch.

**Comment by jamorham** [comment]
@toddkazakov Okay I will publish something soon for you to take a look at. With testing so far it seems like the authorization_code is invalidated after 24 hours which requires the browser component to fire up again which doesn't work while the screen is off.

**Comment by toddkazakov** [comment]
@jamorham you're supposed to exchange the `authorization_code` for an access and refresh tokens immediately after the callback. The access token is then valid for a short duration, the refresh token for a few days. You should refresh the access token in the background before the refresh token expires. This will also return a new refresh token that's valid for few more days. Hope that makes sense.

**Comment by jamorham** [comment]
@toddkazakov thanks, that is what I'm doing but I will check the persistence... From what you are saying about the authentication model, if a user doesn't submit any data for a few days (eg they are on holiday without internet) when they return will they be required to complete the browser based authentication again?

Is it correct that the `sub` parameter remains constant for the particular user? thanks

**Comment by toddkazakov** [comment]
> if a user doesn't submit any data for a few days (eg they are on holiday without internet) when they return will they be required to complete the browser based authentication again

That's correct. The authorization code can be used once. We can set the refresh token life time to be 2 weeks, so this doesn't happen very often. Does this work?

> Is it correct that the sub parameter remains constant for the particular user?

Yes, `sub` is the user id and is constant.

**Comment by jamorham** [comment]
@toddkazakov I have added support in commit https://github.com/NightscoutFoundation/xDrip/commit/e33663e55d34fa7d6622f205096730104359c656 which is available in the Jan 26th Nightly for testing.

To test, the user would enable `Engineering Mode` as described [here,](https://github.com/NightscoutFoundation/xDrip/wiki/Engineering-Mode) go to the `Cloud Upload` -> `Tidepool` section and select to `Use Integration (test) servers` and at the bottom enable the `Debug Option` and then enter the details to the `Login User Name` and `Login Password` sections. `Login Password` is not used with the new authentication, but on accessing this preference item it will trigger the initial browser login.

In testing so far, everything pretty much looks to be working and xDrip will cache everything it can until it detects that anything has become invalidated at which point it will start the process again requiring browser access.

There is still an issue that I think the browser is caching the login which means that it isn't possible to change selected user because it isn't possible to logout a user. So if you change the username for a logged in user, it just logs in the old user again. I haven't yet found if there is a way to resolve this.

**Comment by toddkazakov** [comment]
@jamorham thanks, I'll take a look today. 

The browser stores a session cookie which expires after some time (usually few days of inactivity). To force re-authenticate the user you can pass `prompt=login` to the initial authorization request with [addAdditionalParameters](https://openid.github.io/AppAuth-Android/docs/latest/net/openid/appauth/AuthorizationRequest.Builder.html#setAdditionalParameters-java.util.Map-).

**Comment by jamorham** [comment]
@toddkazakov ok great and thanks for the tip regarding login I will work to integrate that when user name is changed.

**Comment by toddkazakov** [comment]
@jamorham I took a look at the commit you pointed me to. Is it possible for you to integrate the code verifier challenge to the auth flow as in the example above? This is required for public clients (e.g. native apps) to prevent authorization code hijacking by other apps installed on the device.

**Comment by jamorham** [comment]
@toddkazakov  Please see https://github.com/NightscoutFoundation/xDrip/commit/8e3592e234607b6edfef6c935e2d631f93c09296 for update that includes the code verification and correctly handling the situation where a user changes the login user name in preferences.

**Comment by jamorham** [comment]
@toddkazakov are you able to enable production access now? Thanks

**Comment by toddkazakov** [comment]
@jamorham implementation looks good. I'll go ahead and create a client for you. I'll need a day.

**Comment by jamorham** [comment]
@toddkazakov please let me know when we can test the production side. Thanks

**Comment by toddkazakov** [comment]
@jamorham can you please try now? I have created the exact same client in our production environment.

**Comment by jamorham** [comment]
I got logged out this morning even though the session has been constantly active. The error said `invalid_grant` - `Session doesn't have required client` - I haven't been able to get logged back in yet but possibly that is because my password has changed since I previously wrote it down. I'm not sure as I'm just getting invalid password messages. Is there a fault with the backend?

**Comment by jamorham** [comment]
@toddkazakov production environment

**Comment by toddkazakov** [comment]
@jamorham I believe this is caused by a bug in Keycloak (the IAM software we use). The bug is fixed in the latest version, but we'll need some time to plan the upgrade. Thank you for the understanding.

**Comment by jamorham** [comment]
@toddkazakov okay please let me know when that is upgraded in the future because currently using the new authentication system is defaulted to off within xDrip settings and to complete migration I would change that default setting but need to have confidence that authentication will be reliable for users before doing so. many thanks.

**Comment by toddkazakov** [comment]
@jamorham apologies, I've been busy with other tasks. We'll do the upgrade in the next few weeks. I'll let you know when it's done.

**Comment by toddkazakov** [comment]
@jamorham the fix has been deployed

**Comment by jamorham** [comment]
@toddkazakov are we ready to switch the new mechanism to be the default? Do you think everything is now working correctly? thanks

**Comment by toddkazakov** [comment]
@jamorham has this been released? If not, I encourage you to do it as soon as possible.

**Comment by Navid200** [comment]
> @jamorham has this been released? If not, I encourage you to do it as soon as possible.

@toddkazakov 
It was released on September 23.

**Comment by toddkazakov** [comment]
Great, thank you! Should we close this issue or do you want to keep it open in case you need support?

**Comment by Navid200** [comment]
Yes, I close it for now.  Thanks

**Comment by Navid200** [comment]
@toddkazakov Hi,
Is there any interest to add the ability of following someone to TidePool?
