### ISSUE TITLE
Xdrip Bluetooth contour next link 2.4

### ISSUE THREAD

**Issue by EllaGotemans** [NightscoutFoundation/xDrip#260]
Is it possible to connect the contour next link 2.4 with bleutooth to xdrip. In the settings of glucose meters the option is off and I cannot turn it on.

**Comment by jamorham** [comment]
I don't know how similar this is to the contour next one but I'm hopeful it also conforms to the standard.

Make sure you have at least one glucose reading on the meter.
Put the meter in to pairing mode 
Scan for it in the glucose meter menu
Connect to it when it shows
If its working you should see it download data from the meter
Once data is downloaded successfully then xDrip will allow you to use that meter

**Comment by EllaGotemans** [comment]
I only have the option on the glucosemeter to connect to the pump

**Comment by EllaGotemans** [comment]
After reading a lot of internetpages I have found that the communication is nog bluetooth but IEEE802. So the only way to connect the meter to my phone is with aan OTG cable.

**Comment by jamorham** [comment]
Yes, which pump is this? there is an uploader app which you can then use to get CGM data in to xDrip from there.

**Comment by EllaGotemans** [comment]
Medtronic 640G, my little daughter has it. I follow her CGM values by connecting the contour next link 2.4 with an OTG cable to my phone and I use xdrip. I’m looking for a connection to my phone without an OTG cable.

**Comment by hartlijn** [comment]
Not yet possible @EllaGotemans. You still need some hardware and OTG.

**Comment by LoopasPododolski** [comment]
Hi,

does anyone know if I can get Data from Beurer evo (with bluetoothdongle) to xdrip?
https://www.beurer.com/web/de/produkte/medical/blutzucker/blutzuckermessgeraete/gl-50-evo-mg-dl.php
I could pair it, but received a time out error from xdrip.
