### ISSUE TITLE
Consistency of blood glucose unit syntax

### ISSUE THREAD

**Issue by Navid200** [NightscoutFoundation/xDrip#2644]
xDrip allows you to choose which one of the two blood glucose units you want to use.

However, there seems to be another disagreement other than the unit.
Some prefer mg/dL while others prefer mg/dl.   I am talking about the symbol representing the unit of volume, litre being uppercase or lowercase.  
We talked about this here:  https://github.com/NightscoutFoundation/xDrip/pull/2166

We already have a discrepancy in xDrip.  So, even the developers are not being consistent.
As an example, you can see that uppercase is used her:
![1](https://user-images.githubusercontent.com/51497406/214187054-322c3e98-383e-4948-823d-ff233a7262f6.png)  
While lowercase is used here:
![Screenshot_20230123-194034](https://user-images.githubusercontent.com/51497406/214187357-baa88309-b3f7-4b03-9d1e-660370606637.png)
<br/>
<br/>
    

Instead of forcing one or the other, or having both as we do now, I hope that we can agree to allow the user to choose one or the other to be used consistently throughout xDrip.

We choose which unit we want to use on the page shown below.
![Screenshot_20230123-193327](https://user-images.githubusercontent.com/51497406/214189882-962a9e64-eb34-489e-b7d4-0f70522d15fd.png)

Can we add a toggle switch, in a less prominent form/position, to the same page controlling whether L is used or l?  
This requires inserting a new variable in every location in xDrip the unit of blood glucose is present.
Developers should use the variable instead of typing the unit.  We should make it a habit to remind developers of this in all PR reviews asking them to follow this practice.
Can we do this?

**Comment by tolot27** [comment]
I do not know why this issue was raised. It is against our own policy to first discuss this.
In this particular case we have a PR for some time. I'll continue there.

**Comment by Navid200** [comment]
Our policy is that developers approve issues to be opened.
What PR?

**Comment by Navid200** [comment]
Should I post in your issues that you have opened and ask why they have been opened?

**Comment by Navid200** [comment]
Postponed
