### ISSUE TITLE
double view of IE's and KH's in addition with to long numbers if come from Nightscout/AAPS

### ISSUE THREAD

**Issue by MasterPlexus** [NightscoutFoundation/xDrip#265]
I've startet looping, and see now that if I maintain therapeutic data (Injections and carbonhydrates) that those will be shown in xDrip doubled, and sometimea the view switch to very long zeronumber after the komata (see screenshot, ignore the glucose values, I'm ill at the moment :-P )

![image](https://user-images.githubusercontent.com/942153/34709927-9bab84f0-f519-11e7-8fff-26974ac74b01.png)

My Config: connection in xDrip to nightscout via API, also in AAPS, and in addition in AAPS xDrip as the source for Glucose-values.

**Comment by jamorham** [comment]
I will see if I can get this cleaned up somewhat.

**Comment by jamorham** [comment]
This should be solved in the Jan 10th nightly which is available now. Please let me know if that fixes it?

**Comment by MasterPlexus** [comment]
The long numbers are fixed now, thanks. But the double entry is still active. May this is a problem within the Synchronisation? 
I have AAPS set to use xdrip for the glucose values, and additionally nightscout API. In xdrip I have set nightscout API also. May AAPS send the therapeutic in addition direct to xdrip? May I have to stop one sync to nightscout (I think xdrip) ? May I try it this evening.

Anyway, thanks for the fast reaction ;)

**Comment by jamorham** [comment]
I don't know enough about AAPS to know for sure, perhaps @AdrianLxM is more familiar with the issue?

**Comment by MasterPlexus** [comment]
So made some tests. It looks like that xdrip gets the treatments directly from AAPS, and if the download from Nightscout is activated, then it will be shown as a double entry. Local fix for me: deactivate that setting, so xdrip will in future only upload the data to nightscout, and not vice versa. So issue will be closed.
