### ISSUE TITLE
Custom Battery warning level - DIY transmitters

### ISSUE THREAD

**Issue by Elvin6669** [NightscoutFoundation/xDrip#268]
Hello,
As there are increasing numbers of DIY G5 transmitter, as like mine, the transmitter now receives 3.7v from a rechargeable LiPo battery and would be nice to be able to change the voltage warning level from the standard 290 to a customable higher level like around 300-320.

Would a feauture like this be possible to be added?
The issue I am having is that the battery warning time is very short, max 8h or if I am unlucky to have it discharge between battery checks.

Thank you.

**Comment by jamorham** [comment]
Could you drop me an email about this to discuss it further, my username at gmail thanks

**Comment by Elvin6669** [comment]
Sent you an email.

Looked through the code and what I found so far that at C:\Users\elvin\Desktop\xDrip code\xDrip-master\wear\src\main\java\com\eveningoutpost\dexdrip\G5Model\Ob1G5StateMachine.java

Line 58 is set as LOW_BATTERY_WARNING_LEVEL = 300 
Is this the Setting I need to change to get a different warning level?

**Comment by jamorham** [comment]
I will get this implemented shortly

**Comment by Elvin6669** [comment]
Thanks a lot! 
Appreciate it!

**Comment by jamorham** [comment]
This should be present in the 22nd Jan Nightly. Look in `Settings` -> `G5 Debug Settings` -> `Adjust battery warning level` and change it to the level you want to receive alerts at.

**Comment by jamorham** [comment]
Marking as resolved
