### ISSUE TITLE
Blukon collector restart race condition

### ISSUE THREAD

**Issue by gregorybel** [NightscoutFoundation/xDrip#269]
Hi,

in some circonstance, it could be possible that xdrip restarts collector altough xdrip is communication with blukon. It could happen when option "Agressiv service restarts" is enabled but also if user force restart manually. It can be quiet annoying as it may lead to long time until xdrip and blukon reconnects, as xdrip still needs to wait 5min each time.

As more and more user complains about difficulties to reconnect, I think we should fix this issue.

In the init function, I add a guard `m_communicationStarted` to avoid resetting variables, which doesn't help totally as BT link is closed.

I could think about these possibilities to solve issue:
- Blukon Class provide a method `isCommunicating()` and DexCollection Class should check for it before restarting Collection
- We change timer for collection restart to something in between 2 communication slots (7min, 13min, ....) but at at least not 10min. Could be also great to give a dropdown list with different good times

There are certainly better solutions...

What do you think?

Gregory

**Comment by jamorham** [comment]
I think storing a timestamp of the last time blukon class received any data from the remote device and then we can use that (or a boolean method like `isCommunicating()` based on that timestamp to decide whether to restart the service instead of `BgReading.last_within_millis()` would make it more reliable. 

As far as I know, if any data is being received from the blukon device then there is no need to restart the service?

**Comment by gregorybel** [comment]
yes when something received to need to restart. We can do with such a timestamp but this would mean we need to set this timestamp on each received command, maybe too much overhead?

How to interface both classes? Using PersitantStore?

**Comment by gregorybel** [comment]
@jamorham how do we continue here?
I can provide a timestamp but how?
A getter?
Using persitentStore?
Better idea?

I looled at code when restart is done and it seems we cant access blukon class.

Any change to change timout for restart? Or even better can we let user decide? For blukon 6min would be fine, as we should get latest after 5min a new value.

I have concerns about overhead to set timestamp on each value, is it valid or doesnt matter?

Thanks.

**Comment by jamorham** [comment]
I would say if you are concerned about performance just store the last timestamp in a `static long` field and then make your comparisons against that. The class is unlikely to be unloaded that often while it is in use so the data would likely be 99% correct when tested.

I've created an interface and directed it towards a static method in `Blukon` like so:

```
   public static boolean isCollecting() {
        return false; // stub
        // use internal logic to decide if we are collecting something, if we return true here
        // then we will never get reset due to missed reading service restarts
    }
```

**Comment by jamorham** [comment]
@gregorybel Build your logic in to this new method in `Blukon` and I will get the rest of it wired up shortly. https://github.com/NightscoutFoundation/xDrip/commit/677e57b7755bb0d4c65c6f982f6129207e0fab22

**Comment by gregorybel** [comment]
create PR: https://github.com/jamorham/xDrip-plus/pull/46

**Comment by gregorybel** [comment]
done
