### ISSUE TITLE
Issue with TBR displaying on the graph

### ISSUE THREAD

**Issue by Artemdrip** [NightscoutFoundation/xDrip#2708]
When using Omnipod Dash in master branch or Accu check Combo with the new combo driver in the APPS dev branch 3.1.0.3, TBR is displayed incorrectly in Xdrip (last nightly version).
AAPS sends TBR with local broadcast to Xdrip and those are displayed with multiple vertical lines.
However if Accu check combo is used with ruffy, everything is displayed correctly.
Unfortunately I don't know if it's due to AAPS or Xdrip.
![a6a375b7-0bb8-46aa-9f91-0bba2d7f1858](https://user-images.githubusercontent.com/69725840/221941308-b59e6efd-39fd-499c-acf4-182cea1ba482.jpg)
![fb128aaf-0a6d-4346-aeac-2e4438f89ef5](https://user-images.githubusercontent.com/69725840/221941314-d3d45f86-d337-4c19-95c1-e2cd1ecdd4a9.jpg)
![706c9431-d6b4-412a-9b6f-a89b685638e5](https://user-images.githubusercontent.com/69725840/221941319-f4f32c37-ca1b-4912-ae96-86d444a21482.jpg)
![e058a56d-8cbf-472a-999a-90baa4b0e29b](https://user-images.githubusercontent.com/69725840/221941321-b17636fe-1841-481b-976e-5d697a6091b3.jpg)

**Comment by Navid200** [comment]
Would you please not open an issue as a first step?
You must have seen multiple requests asking you not to open an issue and asking you to open a discussion instead.

This is where you can open a discussion:  https://github.com/NightscoutFoundation/xDrip/discussions
