### ISSUE TITLE
Hour Buttons on main graph screen

### ISSUE THREAD

**Issue by Kustomwireless** [NightscoutFoundation/xDrip#272]
I have seen screen shots of Xdrip+ that have 4 Hour buttons on the main graph screen
 24hour 12 hour 6 hour 3 hour can you tell me how to make them show up I have 3 different android devices and can not find a way to turn the hour buttons on.
Also will there ever be a way to enter and track Basal on the graph.
Thank's for a Great APP

**Comment by jamorham** [comment]
Long press the red xdrip icon at the top of the home screen

**Comment by Kustomwireless** [comment]
Thank You that was the only thing that I did not press.
You are the best my wife loves you.
