### ISSUE TITLE
So, when you use SSH to connect, you don't get a menu?

### ISSUE THREAD

**Issue by AlJeske** [NightscoutFoundation/xDrip#2730]
So, when you use SSH to connect, you don't get a menu?

_Originally posted by @Navid200 in https://github.com/NightscoutFoundation/xDrip/discussions/2723#discussioncomment-5236055_

This is exactly what happened to me, no menu (connecting to serial ports disabled).

**Comment by AlJeske** [comment]
This is exactly what happened to me, no menu (connecting to serial ports disabled) I have already been using Xdrip+ and want to be able to show my Endocrinologist the data.  Setup is: Dexcom G6=>Xdrip+=>Aaps. If there is a better way for the Endo to see my progress, let me know and I will forego the Nightscout-google cloud endeavor.

**Comment by Navid200** [comment]
Please respect the rules.
You were asked not to open an issue when you attempted to open this.
You were asked to open a discussion.
Please do that, and I will help you.

This is the link, again:
https://github.com/NightscoutFoundation/xDrip/discussions
