### ISSUE TITLE
Trend arrow on wear (SW3) does not budge

### ISSUE THREAD

**Issue by LongboatAline** [NightscoutFoundation/xDrip#274]
No matter how steep the delta, the trend arrow on both the xDrip watchface and the xDrip large watchface on my Sony SW3 remains level. 

- Version: nightlies between Jan 01 2018 and Jan 18 2018
- Hardware Data Source: 640G/Evernsense
- Upload: mongoDB
- Smooth sensor noise on
- Wear Integration: on, Show Treatments activated
- Smartwatch sensors on (stepcounter works like a charm!)

Other SW running/communicating via xDrip broadcast: 600series uploader, AndroidAPS

Images: xDrip watchface, AAPSv2 watchface of the same timespan as reference.
![xdrip02](https://user-images.githubusercontent.com/35570803/35116768-da336ce0-fc8c-11e7-908e-8fc88d438291.png)
![aaps04](https://user-images.githubusercontent.com/35570803/35116797-ee66eda4-fc8c-11e7-9906-ac84629225cc.png)

My heartfelt thanks to everyone involved in creating this incredible piece of software - the entire ecosystem is a true life-changer! Still learning... Tatjana

**Comment by jamorham** [comment]
Is this a new problem, did it work previously?

**Comment by LongboatAline** [comment]
I only got the CGM since November, so I can't say that I've got much to compare it to. From xDrip I only know the horizontal arrow.
If there's any version you'd like me to try, I'll happily do so. 
(same user as my ripe handle, th122 - trying to move the medical-themed stuff to a separate entity)

Thanks, Tatjana

**Comment by DavitBS** [comment]
I bought a Sony Smartwatch 3 recently and configured it to work with my xdrip+ (version f20d8da-2018.05.30 with Hardware data source: 640G/Eversense) and 600seriesuploader on my phone.
Trend arrow on watchface is always horizontal no matter delta value is.
It would be great if the arrow could change according to delta values to provide us with fast visual info of our BG trend.

**Comment by Navid200** [comment]
@LongboatAline Would you please close this issue if it has been resolved?
Otherwise, would you please update considering it has been 3 years. 
Thanks

**Comment by Navid200** [comment]
Please ask the user community before opening an issue.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks
