### ISSUE TITLE
Disconection alarm

### ISSUE THREAD

**Issue by merberaza** [NightscoutFoundation/xDrip#275]
When the mobile is on silent mode the disconection alarm is only shown as a message on the screen but it does not sound.
Low and high glucose alerts sound when the mobile is on silent mode. They have override silent mode.But disconection alarm has not that option. Or i don't know how to do it. Sorry in that case.
Thanks in advance!

**Comment by jamorham** [comment]
Can you tell me which android version you are using?

**Comment by merberaza** [comment]
Version 7.1.1

Enviado desde Yahoo Mail con Android 
 
  El lun., ene. 22, 2018 a 9:58, JamOrHam<notifications@github.com> escribió:   
Can you tell me which android version you are using?

**Comment by Navid200** [comment]
@merberaza Would you please close this if it has been resolved?
Otherwise, would you please update?
Thanks

**Comment by Navid200** [comment]
@merberaza What do you mean by disconnection alarm?  Do you mean "Missed reading alert"?

**Comment by merberaza** [comment]
Yes, i mean the missing reading alert.When you are using your personal mobile, if you have the sound on, many times the phone sounds with each notification. During the night i would like to put the silent mode on, but i can't because the missing readings alert qoult not sound.

Enviado desde Yahoo Mail con Android 
 
  El mar., feb. 23, 2021 a 20:23, Navid200<notifications@github.com> escribió:   


@merberaza What do you mean by disconnection alarm? Do you mean "Missed reading alert"?

**Comment by Navid200** [comment]
Would you please add your comments to this issue then, which is a duplicate.  
https://www.facebook.com/groups/xDripG5/permalink/4603084736431652
I close this one.  We can always re-open it if you disagree.
