### ISSUE TITLE
Cant connect new transmitter 

### ISSUE THREAD

**Issue by Schizm1** [NightscoutFoundation/xDrip#2755]
I just installed a new G6 transmitter but out of the ordinary its not connecting. Samsung S22+. All I did was update the BT id but I can't get a connection. Why is this so different?

**Comment by Navid200** [comment]
You must have seen this request already:  Please don't open an issue unless asked to do so by a developer".
Where you asked to open this issue by a developer?

If not, please open a discussions here:  https://github.com/NightscoutFoundation/xDrip/discussions

**Comment by Schizm1** [comment]
Sorry, I don't know. I'm a firefighter that loves xdrip but not a techy. I
again apologize but simply looking for a solution to a issue.

Mike
