### ISSUE TITLE
xDrip+ event logs and screenshots thereof

### ISSUE THREAD

**Issue by jbowler** [NightscoutFoundation/xDrip#2793]
This discussion originates in this, FaceBook, discussion:

https://www.facebook.com/groups/xDripG5/posts/9041152629291485/?comment_id=9041252579281490&reply_comment_id=9056028927803855

My original point is that \<three drops\>/View Events Log gets overloaded with spurious warnings.  In the case of the FB thread this seemed to be NightScout warnings which were clearly not directly related to the issue the OP (in that thread) posted.

I take Navid's point that the developers have the "upload logs" option, which doesn't truncate on screen size, and that the developers have History to deal with.

So my point, and my reason to create a discussion here, is that it is counter productive to include /ancient history/ or, indeed, /really important to me/ in event logs that FB users will be asked to post.  If the log in question contained NOTHING it would be more useful; so start from there.

Only put something in a bug report that will be reported by people encountering bugs that will certainly be relevant, and work up to the screen size.

**Comment by Navid200** [comment]
This shows the screenshot that was posted on facebook in the thread:
![341763485_607935074325452_8918289884371249696_n](https://user-images.githubusercontent.com/51497406/233744381-16e4af53-1007-4483-9068-de60984f592a.jpg)

**Comment by jbowler** [comment]
Yes.  So the problem is that the OP originally reported a three minute failure from 12:56 (IRC; I'm quoting from memory and the screen shots don't seem to contain the calendar date even).  BTW; I'm not implying any miscreance in the OP comment.  The data as presented seems 100% correct.

The sensor was, so far as I can tell, inserted and the transmitter too, then nothing happened, so far as anyone knows.

The whole issue raise by the original FB thread is off topic here; my intention was to point out that the excess data in the screen shot obfuscates any possible attempt to work out what is going on.

**Comment by Navid200** [comment]
This is my opinion:

The System status page is crucial.
The guide is very important.
The logs present information.

In case of a G6 not establishing connectivity, as can be seen in the status page below from the same thread, there are so many questions that must be answered before anyone may need to see the logs.
![342052326_1160258197975273_2260970130283484191_n](https://user-images.githubusercontent.com/51497406/233748532-fef2e392-6988-47a9-a4f5-cf0ec99c41b8.jpg)

For example:
Is the transmitter id entered correctly (possible typo)?
Is there another app already connected to the same transmitter?
Is the transmitter activated?  If it's still in the box, it is not.
Is the transmitter transmitting?  You can use a scanner to verify.
....

But, the user was not very interested.  It seemed she had already decided that something was wrong with the particular phone she was using.

**Comment by jamorham** [comment]
I'm not sure what the problem being reported here is exactly, but the log shows messages about receiving remote BG when it isn't set as a follower. Isn't that a big clue that something is going on with that?

**Comment by Navid200** [comment]
@jbowler I just realized this is an issue you have opened.
I don't know why you did that.
I am certain you saw a note asking you not to open an issue unless you were told by a developer.

**Comment by jbowler** [comment]
Well, I opened it from here:

https://github.com/NightscoutFoundation/xDrip/discussions/1900

It's meant to be a  **discussion**; read the first line:

>This discussion originates in this, FaceBook, discussion:

So can you move it to the "Discussions" (I've found out how to open one, but it's more efficient to move this "Issue" since it was meant to  be a "Discussion" in the first place...)

**Comment by Navid200** [comment]
@jbowler Please do NOT open an issue.
Please open a discussion here: https://github.com/NightscoutFoundation/xDrip/discussions

If needed, we will convert it to an issue.

You must have seen this same request when you opened the issue.  It was a request from you as an xDrip user by those who maintain it.
You can work with us or against us.  Why would you choose the latter?  How will that serve you?
