### ISSUE TITLE
LG G6 collector

### ISSUE THREAD

**Issue by Adirael** [NightscoutFoundation/xDrip#280]
I've tried almost all combinations of G5 Debug Settings for an LG G6, has anyone been successful in capturing most data with any combo?

Right now I have checked:

* Try the new OB1 G5 Collector
* Scan for G5 Constantly
* Force G5 to UI Thread
* Authenticate G5 before each r(equest?)

It works for a little while, but then the signal is lost and it wont come back unless I reboot the phone. Sometimes rebooting doesn't fix it either. Using a Smartwatch 3 as a capture device works flawlessly though.

**Comment by jamorham** [comment]
Try the latest nightly to see if things are improved with the OB1 collector? 

Make sure your phone has any manufacturer specific power saving "features" disabled.

**Comment by Navid200** [comment]
@Adirael Would you please close this unless you still have problems?
