### ISSUE TITLE
Carelink login not working with xdrip

### ISSUE THREAD

**Issue by Navid200** [NightscoutFoundation/xDrip#2823]
### Discussed in https://github.com/NightscoutFoundation/xDrip/discussions/2821

<div type='discussions-op-text'>

<sup>Originally posted by **iwascu** May  8, 2023</sup>
the carelink server only works with medtronic applications. xdrip can no longer connect to the server. do you have the same problem? (server is carelink.minimed.eu)</div>

**Comment by cagito** [comment]
Same probleam.   
![image](https://github.com/NightscoutFoundation/xDrip/assets/23023191/2ec1b80c-df30-4858-ab0f-b44c45134d25)

**Comment by Navid200** [comment]
@cagito 
Would you please use the patient account instead of the care partner account?
That should fix it for now.
@benceszasz can open a PR to address this in a different way hopefully soon.

**Comment by DanielFinestrat** [comment]
@Navid200 Hey there, I'm having the same 400 download error when using my care partner account (Spain). I've changed my settings to use my patient account but apparently I'm getting a nullptr error when using that account. Any idea what I may be doing wrong?

![Screenshot_2023-05-25-16-17-18-33_2dd2c1bcb8f659cd696bcba2072f751b](https://github.com/NightscoutFoundation/xDrip/assets/8960119/213081e2-6863-4286-9590-fdea533df7ab)

**Comment by sedy89** [comment]
carelink now requries the information about the patient.

Previously the content of the payload was the username and the role,

`
05-25 18:18:02.144  9788 21467 I flutter : | OAuth | D | 2023-05-25 18:18:02.144481 | Request URL: POST: https://clcloud.minimed.eu//connect/carepartner/v6/display/message?{}
05-25 18:18:02.144  9788 21467 I flutter : | OAuth | D | 2023-05-25 18:18:02.144704 | Request Headers: {Accept: application/json, Content-Type: application/json}
05-25 18:18:02.144  9788 21467 I flutter : | OAuth | D | 2023-05-25 18:18:02.144770 | Request Payload: {"username":this_is_my_carelink_acc,"role":"carepartner"}
05-25 18:18:02.144  9788 21467 I flutter : | OAuth | D | 2023-05-25 18:18:02.144832 | Public: false
`

 but after the update the payload got extended by the patient.

`
05-25 18:18:02.144  9788 21467 I flutter : | OAuth | D | 2023-05-25 18:18:02.144481 | Request URL: POST: https://clcloud.minimed.eu//connect/carepartner/v6/display/message?{}
05-25 18:18:02.144  9788 21467 I flutter : | OAuth | D | 2023-05-25 18:18:02.144704 | Request Headers: {Accept: application/json, Content-Type: application/json}
05-25 18:18:02.144  9788 21467 I flutter : | OAuth | D | 2023-05-25 18:18:02.144770 | Request Payload: {"username":this_is_my_carelink_user,"role":"carepartner","patientId":patient_user_name}
05-25 18:18:02.144  9788 21467 I flutter : | OAuth | D | 2023-05-25 18:18:02.144832 | Public: false
`
![grafik](https://github.com/NightscoutFoundation/xDrip/assets/65983953/9b154d70-ac42-41c2-8ff5-e1617845c828)

I tested this change in the carelink python api and I got the restuls back.
Xdrip requires an option to select/set the patient in the settings and the payload of the request needs to get updated.

I got the log by using "adb logcat | findstr flutter " and opening the carelink app until it updated the values.

**Comment by benceszasz** [comment]
@sedy89 I am already working on it. The BLE endpoint API change still only works with 7xxG pumps, but this change also affects standalone CGM users. For them there is a new API when using care partner account, which must be also implemented:
`GET /patient/m2m/connect/data/gc/patients/$patientUsername`
For patient accounts the old API is still good.
The multi patient follow API changes only affects CareLink servers on which the multi follow option is enabled:
`GET /patient/configuration/system/personal.cp.m2m.enabled`
Multi follow was enabled on the US server last week and on the EU server a few days ago.
I already have a working private version, which I am testing for every scenario and after that I will create a PR for the official xDrip.
By the way I am working on a little bit more user friendly version, where the patient only needs to be provided if multiple patients are followed by the care partner, because there is new an API for patients if multi follow is enabled:
`GET patient/m2m/links/patients`

**Comment by Navid200** [comment]
Please try the latest release:  https://github.com/NightscoutFoundation/xDrip/releases/tag/2023.05.26

**Comment by sedy89** [comment]
wow... that was fast :) Thank you very much, it is working fine for me!

**Comment by Navid200** [comment]
The latest Nightly seems to address this issue.  
We can always reopen if needed.

**Comment by vaneevaolya** [comment]
Hello! The same problem in Spain for some days now. Latest nightly build is not connecting also=( Login error.

**Comment by robmaggidev** [comment]
Same here in Italy, friday worked :/, upgrading to latest build doesn't fix. I'm using the patient account (in case this may be related the issue).

**Comment by awbunge** [comment]
I have the same problem here in Rome (Italy), from september 28th, when Medtronic did an "Important scheduled maintenance work". Tha last "Nightly build" of xDrip+ was that of 24th Sep 2023, it doesn't work after the scheduled maintenance work. Have some else the same problem? Thanks.

**Comment by dircsem** [comment]
Not sure if is anybody using this connection but I'm having problem to connect to the carelink server but recently I can't login into it:

![Image](https://github.com/user-attachments/assets/ba4d524a-b357-46a9-92a5-64825ab9abc2)

**Comment by dircsem** [comment]
Thank you @Navid200 I just need to get the latest nightly build and the fix was there. I'd look for an issue at carelink and I just found this one, haven't seen the nightly build logs.
