### ISSUE TITLE
Dexcom One losing connection

### ISSUE THREAD

**Issue by hughconway** [NightscoutFoundation/xDrip#2833]
I am seeing the connection to Dexcom One transmitter (transmitter ID starting Cxxxxx) drop until a full Bluetooth restart and manual pairing is completed. This comes up a a pairing request in the notifications area and needs to be opened and the checkbox to allow call history and contacts ticked before pressing pair. Haven't managed to pin down what causes the drop in th first place but seems to be happening roughly every 12 hours or so.

Phone is Google Pixel 6 Pro on latest version of Android 13 and xDrip version is the nightly build from May 14th.

**Comment by jamorham** [comment]
Please try the special pairing workaround setting and report back if that resolves the issue.

**Comment by Navid200** [comment]
Please don't open an issue.  Please open a discussions instead:  https://github.com/NightscoutFoundation/xDrip/discussions
If needed, we will convert it to an issue.
