### ISSUE TITLE
Enable bluetooth and try again

### ISSUE THREAD

**Issue by dianabalashova** [NightscoutFoundation/xDrip#284]
I have a problem with recognition Dexcom MT by the Xdrip+ . It says error: Enable bluetooth and try again. Bluetooth is turned on, it worked properly one month and yesterday stopped. The phone I use is Huawei CUN-21L (YP II) and I cleared all the cash and data related to the Bluetooth application. 

Could it be from the Dexcom transmitter, I can not awake it in any way and Xdrip can not find it. Also tried with Samsung Galaxy S8+.

Thank you in advance for any comments.

**Comment by JonathanM32** [comment]
Having a similar problem on my pixel 2 xl

**Comment by Navid200** [comment]
@dianabalashova Would you please close this issue if you don't have the problem any more?

If you have any problems finding the correct settings, please post in the facebook group:
https://www.facebook.com/groups/xDripG5
