### ISSUE TITLE
Hi everyone, i have an issue that how i can solve it( massage ) rest-api upload to nightscout has falied

### ISSUE THREAD

**Issue by YOUSIFALHAJ** [NightscoutFoundation/xDrip#2854]
### Discussed in https://github.com/NightscoutFoundation/xDrip/discussions/1900

<div type='discussions-op-text'>

<sup>Originally posted by **jamorham** January  4, 2022</sup>
## 👋 Welcome!
  Please see the directions below from @Navid200 on how to use the discussions feature and associated guidance and rules.</div>

**Comment by PhilTU** [comment]
Please write this in discussions not here in issues, This is for definite bugs that have been identified.
