### ISSUE TITLE
xDrip does not have full bulgarian language support

### ISSUE THREAD

**Issue by DiBochev** [NightscoutFoundation/xDrip#2875]
xDrip does not have full Bulgarian language support.
Most of the menus/items are in English.

**Comment by Navid200** [comment]
Please don't open an issue in this repository as you must have seen already when you opened this.

Instead, please open a discussions, again, as you must have seen already when you opened this:
https://github.com/NightscoutFoundation/xDrip/discussions

Thanks for your understanding.
