### ISSUE TITLE
G6 transmitter with a space won't connect or send alert

### ISSUE THREAD

**Issue by robertrub** [NightscoutFoundation/xDrip#2885]
Minor bug. If by error one enters a space character after the G6 transmitter serial number (cut and paste can do that), xDrip will not connect and will not give any errors (except that there are no new BGs)

See discussion below with log capture.

https://github.com/NightscoutFoundation/xDrip/discussions/2884

**Comment by jamorham** [comment]
The issue should be resolved in the July 1st nightly which is available now.

**Comment by Navid200** [comment]
Thanks
