### ISSUE TITLE
Webfollower w Libre3, Signal Missed

### ISSUE THREAD

**Issue by hpcolus** [NightscoutFoundation/xDrip#2889]
### Discussed in https://github.com/NightscoutFoundation/xDrip/discussions/2888

<div type='discussions-op-text'>

<sup>Originally posted by **Havanna22** June 15, 2023</sup>
I have used Xdrip+ with Webfollower and Libre3 for months now but now it suddenly says Signal Missed.
This coincides with an update of LibreLinkUp, maybe there is a connection?
Libre3 app works correctly, LibreLinkUp App works correctly showing the glucose level, jut Xdrip+ gives Signal Missed
I have an Android version 13.
I have tried both with the Latest release XDrip+ and also the latest pre-release and restarted phone.
What else can I try to get it to work?</div>

**Comment by hpcolus** [comment]
![Screenshot_20230615-222813](https://github.com/NightscoutFoundation/xDrip/assets/104551107/76ef2a4c-355e-4514-9d8c-adf1fd93b26c)
As stated in the discussion, there is now a latency period of 20min from librelinkup, the server that feeds xDrip as webfollower.  Even with this 20min lagging, xDrip should look into it

**Comment by Navid200** [comment]
Please don't open an issue unless when asked by a developer.

**Comment by a-jey** [comment]
The api-links have changed).

those should be correct:
api-us.libreview.io
api-eu.libreview.io
api-fr.libreview.io
api-au.libreview.io
api-jp.libreview.io
api-de.libreview.io
api-ca.libreview.io

Maybe there are more.

**Comment by hpcolus** [comment]
> The api-links have changed.
> 
> those should be correct: api-us.libreview.io api-eu.libreview.io api-fr.libreview.io api-au.libreview.io api-jp.libreview.io api-de.libreview.io api-ca.libreview.io
> 
> Maybe there are more.

It works, but it should be noted that the solution is temporary and does not apply for a 'webfollower' of libreview. This solution implies to install another apk in the phone (linkupconnect)  and change the hardware source. In addition, according to the developer https://github.com/cmtjk/LinkUpConnect/blob/master/README.md, the xDrip feature of 'webfollower' is better when it comes to implement historical data.  Therefore the issue should remain open until the final fix is implemented directly in xDrip, so there would be no need to use another apk app.

**Comment by a-jey** [comment]
> > The api-links have changed.
> > those should be correct: api-us.libreview.io api-eu.libreview.io api-fr.libreview.io api-au.libreview.io api-jp.libreview.io api-de.libreview.io api-ca.libreview.io
> > Maybe there are more.
> 
> It works, but it should be noted that the solution is temporary and does not apply for a 'webfollower' of libreview. This solution implies to install another apk in the phone (linkupconnect) and change the hardware source. In addition, according to the developer https://github.com/cmtjk/LinkUpConnect/blob/master/README.md, the xDrip feature of 'webfollower' is better when it comes to implement historical data. Therefore the issue should remain open until the final fix is implemented directly in xDrip, so there would be no need to use another apk app.

It wasn't meant as a workaround but as an information for the developers ;-)

**Comment by Navid200** [comment]
This seems to have been resolved.
You can see the solution here:  https://github.com/NightscoutFoundation/xDrip/discussions/2893#discussioncomment-6206348

And I have summarized the solution here as well as the second update:  https://navid200.github.io/xDrip/docs/Libre3_Follow.html
