### ISSUE TITLE
G5: Don't automatically un-pair on phones that can't automatically re-pair

### ISSUE THREAD

**Issue by juliatuttle** [NightscoutFoundation/xDrip#290]
Some phones (like mine) require user intervention to pair with a Bluetooth device. Right now, the old and new G5 collectors can automatically un-pair from the G5 to try to resolve a connection problem. On phones that can't re-pair automatically, this just makes things worse -- the original problem might have resolved by itself, but now xDrip won't get any data until the user manually intervenes. In those cases, xDrip should not automatically un-pair at all.

**Comment by jamorham** [comment]
I'm working on this now and hopefully will have something out tomorrow you can try out.

**Comment by jamorham** [comment]
Did we resolve this issue in the nightly? Please let me know if I can close this issue. Thanks.

**Comment by jamorham** [comment]
any news on this? thanks

**Comment by juliatuttle** [comment]
Yup, it's working as expected -- far fewer instances where I have to manually repair because OB1 unpaired automatically., with the occasional instance (like just now today) where I have to manually unpair and repair. Thanks!
