### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by kimbersdiabetic** [NightscoutFoundation/xDrip#291]
Dear Sir,

I am at the moment using your excellent Xdrip+ app with the Freestyle Libre on 
 an Android Samsung 5,
I am trying to find out what Android watch will work, Also is there a watch that will work as a seperate device to my phone.

Many thanks for your help.

**Comment by AdrianLxM** [comment]
There is a large chapter about watches in the documentation: https://github.com/NightscoutFoundation/xDrip/blob/master/Documentation/WatchGuide.md

**Comment by kimbersdiabetic** [comment]
Many thanks Adrian.

**Comment by kimbersdiabetic** [comment]
Forgot to ask Adrian – In theory any Android 1 or 2.0 should be okay?

 

Many thanks.

 

From: Paul Kimberley [mailto:paullorayne@btinternet.com] 
Sent: 02 February 2018 12:28
To: 'NightscoutFoundation/xDrip' <reply@reply.github.com>
Subject: RE: [NightscoutFoundation/xDrip] Help Please (#291)

 

Many thanks Adrian.

**Comment by Navid200** [comment]
@kimbersdiabetic Would you please close this issue?
