### ISSUE TITLE
Samsung, Dexcom, and recent Android patch

### ISSUE THREAD

**Issue by Navid200** [NightscoutFoundation/xDrip#2917]
### Discussed in https://github.com/NightscoutFoundation/xDrip/discussions/2915

<div type='discussions-op-text'>

There are reports of some Samsung phones having difficulty after a recent (June 2023) Samsung patch.
This affects Bluetooth operation.  So, if you use xDrip only as a follower (BYODA, Companion app mode, CareLink, Nightscout follower, xDrip sync follower, ...), this will not be an issue. 

<sup>Originally posted by **Navid200** June 28, 2023</sup>
Please keep your comments as short as possible.</div>

**Comment by Navid200** [comment]
1- Make sure all settings are correct: https://navid200.github.io/xDrip/docs/G6-Recommended-Settings.html

2- Please make sure you are using the latest xDrip Nightly.  https://github.com/NightscoutFoundation/xDrip/releases/tag/2023.06.29
  
3- Please enable OB1 debugging: https://navid200.github.io/xDrip/docs/Dexcom/OB1Debug.html  
3b- Restart the phone.  
  
4- If it is not paired, do what you usually do to pair.  Wait for it to work and fail.  If it does not fail and the problem is resolved, perfect.  Please tell us.  If the problem persists, please continue.  
  
5- Look at the logs. You should see a lot more logs than usual.  
Only if you have waited for a while so that xDrip has operated with detail logs enabled, tap on "Upload logs" at the bottom.  
Add some relative narrative, like "gaps of x minutes between readings or whatever the problem is", and submit.  
  
6- Post in this thread and state you just uploaded including an identifying component in your upload so that the developer can communicate with you knowing who uploaded the logs.  
  
7- Please don't post here just because you have a problem.  Please allow this thread to be dedicated to the specific topic of the latest Samsung update impact.   If you have any other problems, please post here: https://github.com/NightscoutFoundation/xDrip/discussions

**Comment by oconnorellen** [comment]
Logs uploaded, 20.59 nughtscout treatment was last entry on log

**Comment by Navid200** [comment]
Please try today's release and see if it improves the recent connectivity issues you have been experiencing.
https://github.com/NightscoutFoundation/xDrip/releases/tag/2023.07.02

**Comment by oconnorellen** [comment]
So far so good, I will keep you updated, thank you!

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by oconnorellen** [comment]
Hi, still dropping in and out but there is a slight improvement I think

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Navid200** [comment]
@oconnorellen Would you please not reply to emails in order to post here.  Please log in to GitHub and you will see how cluttered the thread becomes because of your replies.

**Comment by xamrex** [comment]
@Navid200 I have just send logs

I did few days ago Samsung A53 system update (its A536BXXU6CWE9) from that time I dont have regular readings.
During the day I got maximum like 20 readings in total.
Today (03JUL23) i have radings @ 06:39,06:44, ... , 07:13; then 11:39, 11:44, .. , 12:19, and 16:54, 16:59,....,17:29
I got last OOP2 algorithm from 25May23, and last Xdrip (1st Jul 2023)
I m using freestyle libre 2
I have enabled OB1 debugging from 19:19 03JUL23, and then restarted phone, and i m sending those logs @ 19:40

**Comment by Navid200** [comment]
| Model | Android | TX | Hardware Data Source | Patch | Working |  
| ------- | --------- | --- | ------------------------ | ------ | ---------- |

**Comment by ss1043** [comment]
Hi @Navid200, do we have a rough estimation, of when this might be fixed? Thanks in advance for your effort and team.

**Comment by Navid200** [comment]
@ss1043 My understanding is that this is not an xDrip issue as there are many apps that have this problem.
There are also a lot of rumors.  But, we don't have statistics.  I have seen people claiming no issues with different models.
That's why I would like to fill the table.

**Comment by Arnoldas8** [comment]
After the update, it does not allow connecting to the watch and the connected signal disappears after connecting xdrip, the signal appears and disappears after a while, this is how xdrip works after the Samsung update

**Comment by Arnoldas8** [comment]
![received_177127451883367](https://github.com/NightscoutFoundation/xDrip/assets/139204152/9c4eae4a-e52c-4517-b81c-98c3ae287a36)
![received_232084706440972](https://github.com/NightscoutFoundation/xDrip/assets/139204152/fe729358-cbc0-4f48-9e3f-0c9a636f44ba)
![received_834590017679051](https://github.com/NightscoutFoundation/xDrip/assets/139204152/73b130d3-465f-4759-b933-059d83f3af2d)
![received_829944961510399](https://github.com/NightscoutFoundation/xDrip/assets/139204152/9827e7c4-2e8f-4866-a154-39ac3dd6eddc)
![received_228950530014860](https://github.com/NightscoutFoundation/xDrip/assets/139204152/47a5a3c1-5ea0-4f92-9b31-8df3fcd5aaa3)
![received_1282186286017965](https://github.com/NightscoutFoundation/xDrip/assets/139204152/74f7d480-d9dc-4ef3-bd0e-c36340e870d7)
( I upload photos of how everything works after the update and the signal disappears, it turns on constantly and after a while it disappears again )

**Comment by mr-mjb** [comment]
It may be of use to inform you that CamAPS have sent out this communication to it’s users that Samsung will issue an update on 24th July to fix to the recent signal loss issues on A series devices.  I suspect this issue is common to what is being seen for xdrip users…

![IMG_2119](https://github.com/NightscoutFoundation/xDrip/assets/55636308/82520175-8239-4700-a0d9-db7d9954a41d)

**Comment by parapenT1sta** [comment]
Right now I'm not using xDrip for mine G5 sensors but I realized that after the latest Samsung patch, my S20+ was having more issues connecting to my pump with AndroidAPS, something that I didn't have before. Then I realized that Bluetooth was set to battery optimization after the update, after I changed the setting, the connection was improved. You can try and check if improves the connection.

![Imagem WhatsApp 2023-07-17 às 10 19 09](https://github.com/NightscoutFoundation/xDrip/assets/608650/fc545467-477e-4d64-9584-0b433a6f3ba3)

**Comment by xamrex** [comment]
Today Samsung push update for A53, and after update its working ;-)

**Comment by Navid200** [comment]
@xamrex 
Thanks

**Comment by ss1043** [comment]
I also want to provide information it's working fine again. Thanks

**Comment by Navid200** [comment]
@xamrex @ss1043 
Can either of you share a screenshot of the patch details so that I can show people the date it has been released?

**Comment by xamrex** [comment]
![Screenshot_20230726_203455_Software update](https://github.com/NightscoutFoundation/xDrip/assets/12885918/5682791c-36d6-4343-a8c6-364a741e1bfb)
On my phone its  **A536BXXS7CWF6** update (little strange because this site shows **A536BXXS7CWG2** )

**Comment by ss1043** [comment]
@Navid200 

Here are the notes in English 😄 

![image](https://github.com/NightscoutFoundation/xDrip/assets/28440976/424cabf5-d863-458b-b1f7-f1a5689a1693)


Source: https://doc.samsungmobile.com/SM-A536B/EUX/doc.html

**Comment by aalaamer** [comment]
> ### Discussed in #2915
> There are reports of some Samsung phones having difficulty after a recent (June 2023) Samsung patch. This affects Bluetooth operation. So, if you use xDrip only as a follower (BYODA, Companion app mode, CareLink, Nightscout follower, xDrip sync follower, ...), this will not be an issue.
> 
> Originally posted by **Navid200** June 28, 2023 Please keep your comments as short as possible.

Hi .. I am new in this .. I am having trouble with Bluetooth connection on my samsung 8 .. please help me

**Comment by Navid200** [comment]
@aalaamer Please open a new discussion.  It's much easier that way.  
There is no guarantee there is anything common just because you have a problem with Bluetooth.
