### ISSUE TITLE
extension of TransmiterPL/LimiTTer  protocol

### ISSUE THREAD

**Issue by FPV-UAV** [NightscoutFoundation/xDrip#292]
additional info about device (Transmiter/Limiter) error states
4-fields message (BG*1000, battery mV, battery%, sensor minutes/10)

when BG value = (string) '000999' = info about error
battery mV = error number (0001, 0002, etc)
battery% and sensor minutes = additional info about errors

action -> display info without triggering alarm (display for 1-minute if possible or until OK button pressed by user)

error numbers:
0001 - to low voltage for NFC reading (BLE work even with 1.8V, but NFC need more than 2.3V) -> Message: "please check battery?"
0002 - all device working OK, but no sensor in NFC field of work - transmited every 5 minutes only when device recognize connected to phone state. -> Message: "Please check position of device. Is it fixed on sensor?"
0003 - 9999 - other errors -> Message 'Error xxxx-yy-zzzz' (xxxxx = battery mV, yy-battery%, zzz-sensor minutes)

+add info about received error message to log

**Comment by FPV-UAV** [comment]
DexCollectionService.java

processNewTransmitterData(TransmitterData transmitterData, long timestamp)

after:
if (use_transmiter_pl_bluetooth && (transmitterData.raw_data == 100000)) {
            Log.wtf(TAG, "Ignoring probably erroneous Transmiter_PL data: " + transmitterData.raw_data);
            return;
        }
add
if (transmitterData.raw_data == 999) {
....
}

**Comment by Navid200** [comment]
@FPV-UAV Would you please close this issue if it has been resolved?
Otherwise, would you please update?
Thanks

**Comment by Navid200** [comment]
If you ever like to re-open this, I suggest that you clearly specify what we have now and what you would like to have instead.
The more clear and shorter and simpler you make it, the more likely it is that someone may decide to implement it.
