### ISSUE TITLE
Trying to run slot 1 and slot 2 simultaneously on different phones. 

### ISSUE THREAD

**Issue by tim2000s** [NightscoutFoundation/xDrip#2922]
I'm trying to run xDrip on a second phone using slot 1, with BYODA on primary phone - a Samsung S23 Ultra (presumably using slot 2).

I've historically run both xDrip and BYODA on the Slot 1 testing phone with no issues. I'm using the latest nightly (2nd June), but with slot 1 selected, the phone doesn't seem to be able to pair with the Transmitter (G6). 

Phone is a Redmi Note 10 Pro 5G. 

Any ideas?

_Originally posted by @tim2000s in https://github.com/NightscoutFoundation/xDrip/discussions/2834#discussioncomment-6343219_

**Comment by tim2000s** [comment]
To add to this, I used slot 1 and slot 2 simultaneously for a long time using xdrip-js on am Edison device with OpenAPS, so I'm comfortable with the safety of doing this.

**Comment by Navid200** [comment]
Please don't open an issue.
You opened a discussion as you should have.
Please continue the conversation there.  If there is a need to open an issue, we will.
