### ISSUE TITLE
Installation issues with Xdrip

### ISSUE THREAD

**Issue by AlisaAqua** [NightscoutFoundation/xDrip#2925]
Hy!
I have Samsung s10+ and I have tried to install dozen of times xdrip+ but it just won't install itself. I've tried latest official version which was in May, I also tried varanty version 4, and I've also tried latest prerelease version which was released few days ago. Every time I get same result.
First my phone tells me that this is app is made for older phone ver but I still click install, the installation is running and then at the end it says that app couldn't be installed. 
Could you please help or tell me what issue is?
Thank you

**Comment by Navid200** [comment]
Please don't open an issue.
Please open a discussion instead.  
https://github.com/NightscoutFoundation/xDrip/discussions

If there is a need to open an issue, we will do that.
