### ISSUE TITLE
Add watchdog to clear xDrip+ cache automatically at programmable intervals

### ISSUE THREAD

**Issue by gszakacs** [NightscoutFoundation/xDrip#294]
Every once in a while my system fails receiving data from the G5 sensor. The failure mode continues until the xDrip+ app cache is cleared. Changes in the advanced bluetooth and collector service settings and/or restarting the phone do not seem to resolve the issue, but clearing the xDrip+ app cache resolves the issue, restores correct operation and does not require that I restart the phone. How difficult would it be to add an automatic xDrip cache cleaning routine to the "aggressive service restarts" option ? For now I try to setup a tasker app service to automatically clear the cache, but it would be nice if this function would be integrated within xDrip+. Thanks

**Comment by Navid200** [comment]
@gszakacs Would you please close this issue if it has been resolved?
You can also ask for support in the xDrip facebook group.
https://www.facebook.com/groups/xDripG5
Thanks

**Comment by Navid200** [comment]
These are the general recommended settings for G5/G6:
https://www.facebook.com/groups/xDripG5/permalink/4603084736431652
If you don't have a facebook account, you can post in the Gitter room and ask.
But, the symptoms you describe are the symptoms of having incorrect xDrip and/or Android settings.
