### ISSUE TITLE
MissedReadingService class not kick startet without new BG value

### ISSUE THREAD

**Issue by gregorybel** [NightscoutFoundation/xDrip#295]
Problem is, as long as there is not at least on BG value received, this class will be not started.
Expected behaviour: class is started right at the beginning

**Comment by jamorham** [comment]
This should be fixed in Mar 19th nightly by this commit: https://github.com/NightscoutFoundation/xDrip/commit/7d6718dddfcc8ca61c6892936b95b67aa1b72f73

**Comment by gregorybel** [comment]
thank you!

**Comment by gregorybel** [comment]
fixed
