### ISSUE TITLE
NFC x Libre 2 - not working

### ISSUE THREAD

**Issue by Rabuffulin** [NightscoutFoundation/xDrip#2959]
Hi...I'm trying since yesterday start a new Libre2 sensor in Xdrip installed on my Samsung ZFold 4 but it's not working. I started sensor like always I did and when I tried read sensor first time with NFC function, Xdrip send me messages like "NFC error IO" or "NFC reader time expired" or "NFC failed". Last month I had this problem and I lost 2 sensors because this, but when I put third sensor, it worked. Anybody already had this problem? I'm two days without use sensor because now all sensor that I put I have the same issue....I try with 3 sensors and the problem is the same....The sensor appears to me on Bluetooth map but when I choose it Xdrip can't connect and I don't know what to do...I tried to do this process in other model cellphone but not worked too....the sensors works fine on Abbot app (LibreLink), so I think that the problem isn't with the sensors..anybody could help me, please?

**Comment by Navid200** [comment]
I am closing this since you have ignored our requests and suggestions not to open issues.

Again, please open discussions instead:
https://github.com/NightscoutFoundation/xDrip/discussions
