### ISSUE TITLE
Auto-Config/scanning QR-Code problem 

### ISSUE THREAD

**Issue by LakeSideCitizen** [NightscoutFoundation/xDrip#2964]
Good morning all,
meanwhile I'm quite despairring.
Since a few days I'm trying to switch from G6 to G7 with xDrip. 

I followed the instructions **[here](https://navid200.github.io/xDrip/docs/Dexcom/G7.html)**.
After going to **Settings - Auto Configure**  I'm not seeing the message as shown in the instructions.
The message isn't there. 
Instead a camera screen appears directly (see screenshot below).
As it seems it's a scanning screen for the QR-Code but if I try to scan the Settings-QR-Code, or a QR-Code of the G7 sensor nothing happens.
In the Screenhot you can see what happens. The orientation of my scren changes to landscape and there is a bright rectangle, 
what seems to be the scanning section. If i hold a QR-Code from a sensor or the code for xDrip settings in front of it nothing happens.

How can I get the G7 running, respectively connecting to my xDrip?
The Instruction page tells if I can't see a message like **[this](https://navid200.github.io/xDrip/docs/Dexcom/images/keks_QR_confirm.png)** I should stop and inform them.
How can i inform "them" (the developer?) about the issue of the not appearing message as mentioned at the instruction page?

xDrip-Version 23ccbd1-2023.07.16
Samsung Galaxy S20 FE
Androind 13

Can anybody help me?
I don't want to have to use the Dexcom-App.
XDrip is a faithful companion for quite a long time now and I don't wanna miss it.

Thank you very much and have a nice day

regards
Philipp

![Screenshot_20230724_053539_xDrip+](https://github.com/NightscoutFoundation/xDrip/assets/39773498/724cd28e-fd72-45bc-81d4-3bb5e188ec8f)

_Originally posted by @LakeSideCitizen in https://github.com/NightscoutFoundation/xDrip/discussions/2960_

**Comment by Navid200** [comment]
Please don't open an issue in this repository.
If there is a need to open an issue, we will as you to do it.

**Comment by Navid200** [comment]
As of the August 2, 2024 release (https://github.com/NightscoutFoundation/xDrip/releases/tag/2024.08.02), there is an additional option that allows you to scan from a QR code image file saved on your device.
