### ISSUE TITLE
"Nightscout Follower" imported insulin types

### ISSUE THREAD

**Issue by source2k** [NightscoutFoundation/xDrip#2965]
Using "Nightscout Follower" as data source provided by Juggluco with "Download Treatments" makes no difference between short and long acting insulin. The IoB behaves the same for short and long acting insulin.

Feature request: Selection of the insulin profile for the long/short acting insulin which is used during import.

**Comment by Navid200** [comment]
Please don't open an issue as explained  on the pages you must have gone through in order to open this issue.
We will open an issue if needed.
Please open a discussions instead.  https://github.com/NightscoutFoundation/xDrip/discussions
We want to help.  But, you have to cooperate with us.
