### ISSUE TITLE
ActivityRecognized errors: Received ActivityRecognition we were not expecting!

### ISSUE THREAD

**Issue by PieterGit** [NightscoutFoundation/xDrip#297]
During poweron of my phone I get the following errors:

![actvityrecognizer no expecting](https://user-images.githubusercontent.com/6500826/36061079-4603b216-0e55-11e8-8eac-c66a6e258da0.png)

I think these errors cause Motion Tracking to be disabled. I got a notification that the Motion Tracking was disabled because of errors.

Version: https://github.com/NightscoutFoundation/xDrip/releases/tag/2018.02.02
Phone: Samsung S7

This error is caused by:
https://github.com/NightscoutFoundation/xDrip/blob/a78dccb971c1f28b263fe694cfeb7f9e955d9203/app/src/main/java/com/eveningoutpost/dexdrip/Services/ActivityRecognizedService.java#L523

@jamorham : Can you explain this error? I think there is a parenthesis fault, because the error is based on the `else ` statement of `((Pref.getBooleanDefaultFalse("motion_tracking_enabled")))`  which shouldn't be an error I suppose. I checked and `Enable Motion Tracking` setting was off. The logging is not very helpful for debugging what went wrong. I re-enabled motion tracking again and will see if I can find the cause.

**Comment by Navid200** [comment]
@PieterGit Would you please close this issue if it has already been addressed?
Otherwise, would you please update?
Thanks

**Comment by Navid200** [comment]
If you like to re-open this, I suggest including what CGM (Hardware Data Source) you are using.
