### ISSUE TITLE
Aidex values not broadcasting via API to watchdrip.

### ISSUE THREAD

**Issue by jiresongit** [NightscoutFoundation/xDrip#3036]
### Discussed in https://github.com/NightscoutFoundation/xDrip/discussions/3035

<div type='discussions-op-text'>

<sup>Originally posted by **jiresongit** August 22, 2023</sup>
I am trying to use watchdrip with xdrip and GlucoRX Aidex sensor.

It seems that the watchdrip app is not able to receive push notifications from xdrip of BG changes, only when watchdrip itself makes forced requests to xdrip.

In woking with @bigdigital (the author of watchdrip) , it seems that the xdrip Aidex code on the BgReading.bgReadingInsertFromInt has a last parameter of false, meaning that the notification to watchdrip etc does not occur.

I am hoping that I have explained this ok and included as much information as needed.</div>

**Comment by Navid200** [comment]
@bigdigital 
Would you be able to open a PR and test?

**Comment by jiresongit** [comment]
I am happy to test when ready, I may just need to be sent an apk :)

**Comment by Navid200** [comment]
@andyrozman 
Do you have any thoughts?
What are the ramifications of changing that from false to true?

**Comment by andyrozman** [comment]
Theoretically it should work, what my code does is to receive broadcast from Aidex application and converting them into valid BG records. We can try to changing it to true... Shouldn't make any problem, at least not in my code... Question would be, when paraemeter is true, do we need to have something set, that was not set before... But we won't know until we try.

**Comment by Navid200** [comment]
Considering I don't wear a watch and don't use Aidex, I will be the worst person to make any changes to fix this since I will not be able to test.  But, more importantly, I don't have a direct feel for the problem.  
I wanted to bring the right people together.  

I leave it in everyone's hands who is here.
If I can help, please let me know.

**Comment by jiresongit** [comment]
if someone is able to try and send me an apk i'm more than happy to try it out as i have aidex and the watch

**Comment by jiresongit** [comment]
So, @bigdigital sent me an apk with the change to test. Not only has it fixed the issue impacting watch drip but I'm now also getting readings read out in the car and more that stopped when I switched from libre to aidex.

From my perspective would be great for the change to be made in the official codebase.

**Comment by Navid200** [comment]
@jiresongit Would you please try the latest Nightly (https://github.com/NightscoutFoundation/xDrip/releases/tag/2023.09.08) and tell us if it works?

I am closing this issue.
We can reopen if it has not been resolved.

Thanks @bigdigital for the PR

**Comment by jiresongit** [comment]
@Navid200 works great thank you
