### ISSUE TITLE
Kotlin Version

### ISSUE THREAD

**Issue by Martifan** [NightscoutFoundation/xDrip#3045]
hello, maybe someone has a code for Kotlin, or a piece of code, how to connect to the sensor and how to read data from the sensor?
thank you all very much

**Comment by Navid200** [comment]
@jamorham 
Please merge this: https://github.com/NightscoutFoundation/xDrip/pull/2966

**Comment by Navid200** [comment]
@Martifan 
Please don't open an issue to ask a question.
Please open a discussion instead.
