### ISSUE TITLE
Caresens Dual BT Meter not working with xDrip

### ISSUE THREAD

**Issue by WanaGo** [NightscoutFoundation/xDrip#305]
Hello,
New Zealand diabetics are being issued Caresens Dual BT meters for Glucose and Ketone testing. These are also available in the UK and possibly other countries.
When trying to make this work for xDrip, you can pair the meter and xDrip starts chirping, but then it does the disconnect sound before any data comes through.
Attached is a bit of a random log when using nRF app on my phone, sniffing out the BT meter services etc.
Is this any help and can this be made to be compatible with xDrip please.
There are a large number of people here using xDrip who now have these meters and finding this is not working, and it would be awesome to make it work like the Contour Next One does.

Thanks
[Log 2018-02-10 221348.txt](https://github.com/NightscoutFoundation/xDrip/files/1721786/Log.2018-02-10.221348.txt)

**Comment by jamorham** [comment]
Ok, I will look in to this

**Comment by old-square-eyes** [comment]
Just adding my notes from Gitter. Hopefully they are of assistance.

Same experience with new Caresens Dual BT. However, after installing the native Smartlog app (play store), I was able to ingest readings to nRF Toolbox (3rd party) app.

Does this mean there is hope that it complies and is unencrypted?
Initial tests are promising for the consistency of this metre (consecutive readings - unsure yet of actual accuracy). I've been comparing it to my self funded Contour Next. It's in the UK, AU and completely funded in NZ so would be worthwhile supporting.

nRF Toolbox: https://drive.google.com/file/d/1ODzC7olF6TAD-0mGPHOdXpkrkHMvNTl2Fg/view?usp=drivesdk

xDrip+: https://drive.google.com/file/d/1oknso7Bmvn7UsroePslHr92mfkPM8gcJ/view?usp=drivesdk

The audio played seems to indicate a connection was made, and then a disconnect. Maybe there is no error... simply that the values were not picked up.

https://drive.google.com/file/d/1qhktuCRy5CMyMGT95ULgNz8nG0UiwUSs/view?usp=drivesdk
This is the nRF Connect view of the glucose service. xDrip seems to be happily connecting when I turn the metre on. If the noises are to be believed.

**Comment by old-square-eyes** [comment]
@jamorham - Another thing to note is this metre is funded for a "Dual" purpose. It is also our Ketone metre. It might be neat (or it could also be the reason BG fails!) if Ketone readings could also be brought in. I know xDrip doesn't track Ketones but you could save it as a note on the plot perhaps for now.

**Comment by WanaGo** [comment]
Hi @jamorham - Any chance this will appear on your radar in the next few months? Thanks

**Comment by Tornado-Tim** [comment]
Bumping support for this meter, let me know if there is any debug things I can do.....

**Comment by jamorham** [comment]
Ok support for this meter is added in the June 9th Nightly. See https://github.com/NightscoutFoundation/xDrip/wiki/CareSens-Dual-Glucose-Meter for some notes. Please let me know how it goes.

**Comment by jamorham** [comment]
I've had multiple reports of success with this now on the latest nightlies. Is this now resolved?

**Comment by WanaGo** [comment]
Yes thanks very nuch
