### ISSUE TITLE
Strange message colors when sensor age exceeds 10 days

### ISSUE THREAD

**Issue by ANDREAPIPPI** [NightscoutFoundation/xDrip#3052]
### Discussed in https://github.com/NightscoutFoundation/xDrip/discussions/2985

<div type='discussions-op-text'>

<sup>Originally posted by **ANDREAPIPPI** August  4, 2023</sup>
AAs shownn in the image, the message "Ends in 13.6 days" has white text on a black background, but when the age goes past 10 days, the message changes to "Expires Sun, 3:58pm", in terrible white text on a cream background, which turns out to be almost illegible.
Is this the rule or have I chosen wrong colors in the settings?
I searched but couldn't find my mistake.
Thank you.
Andrew :-)

![strange-colors](https://github.com/NightscoutFoundation/xDrip/assets/32884006/cf6f9da5-8ad8-4a20-8a52-710b3a9539d3)
</div>

**Comment by Navid200** [comment]
What is the hardware data source?

**Comment by ANDREAPIPPI** [comment]
It's a FSL 2 14 days Europe, used Direct under OOP2 Algorythm, but the same problem occurred with a FSL 1 14 days Europe with MiaoMiao 1, too....

**Comment by ah7675** [comment]
The key function: https://github.com/NightscoutFoundation/xDrip/blob/c53c8440be7987441437bd82e5d134ba7c3ad98f/app/src/main/java/com/eveningoutpost/dexdrip/g5model/SensorDays.java#L192C45-L192C45

**Comment by ANDREAPIPPI** [comment]
Hi.
I just found that this was a problem caused by my phone's MIUI 14 OS, just like the strange color settings problem in discussion #3176, i.e. if the screen display setting is "Dark", problems exist, if "Clear" all is OK.

![All OK](https://github.com/NightscoutFoundation/xDrip/assets/32884006/0ec30e3b-ccc8-4f3f-b9b7-97a5dc8b18a8)

I need to change my phone with a "real" Android one, alas!
Sorry for troubling and for the time wasted, I apologize.    :-(
