### ISSUE TITLE
Unparseable dateformat usinf Xdrip+ in follower mode with nightscout.

### ISSUE THREAD

**Issue by hartlijn** [NightscoutFoundation/xDrip#309]
![img_20180217_140511](https://user-images.githubusercontent.com/28272471/36341385-aef5663c-13ed-11e8-8492-fb0350fe7347.jpg)
Using xdrip not on uploader phone but in follow mode, I can't sync from Nightscout due to parse errors on date format. 

Is there something I can change in the uploaded phone to become 'dateformat-compliant'?

**Comment by MattiasJohansson06** [comment]
I havet the same problem.

**Comment by Navid200** [comment]
@hartlijn Is this still a problem?
Or, is it resolved with recent xDrip releases?
Would you please update?
Thanks

**Comment by Navid200** [comment]
Please consult with the user community before opening an issue.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks
