### ISSUE TITLE
Random app refreshes are not yet solved on android 12 caused by numbers wall on lockscreen

### ISSUE THREAD

**Issue by matthiasvdpoel** [NightscoutFoundation/xDrip#3104]
> I believe this issue has been resolved.

Music to my ears!

We can always reopen if needed.
Thanks

_Originally posted by @Navid200 in https://github.com/NightscoutFoundation/xDrip/issues/1891#issuecomment-1492328713_
  

> > I believe this issue has been resolved.
> 
> Music to my ears!
> 
> We can always reopen if needed. Thanks

I recently upgraded my One plus Nord from android 11 to android 12 and I'm now also experiencing this bug as stated above. I have the number wall enabled. I will disable the number wall and see if that fixes it.

**Comment by Navid200** [comment]
Please don't open an issue.
Please respect the instructions asking you to open a discussion instead.

https://github.com/NightscoutFoundation/xDrip/discussions
