### ISSUE TITLE
Alarm sound not played, only vibration

### ISSUE THREAD

**Issue by drnoname82** [NightscoutFoundation/xDrip#312]
Moto G5, latest nightly of xDrip+, Lineage OS 14.1, Sony SW3:

Alarms only work properly for a short time after starting xDrip+, then no sound is played anymore, notification and vibration work as expected. When clicking "Test Alert" in settings, the xDrip default sound is not played at all, system sounds are only played when "Override phone silent mode" is not selected. The phone is not set to silent. The logs contain no error messages. AndroidAPS alarms work flawlessly.

**Comment by drnoname82** [comment]
Update:
- Reminders work
- Calibration alerts work
- Predictive alerts work
- Level alerts don´t work, no sound is played (as described above)

**Comment by jamorham** [comment]
Ok I have tested this with `LineageOS 14.1-20180220-NIGHTLY-falcon` and xDrip+ versions `20a4313-2017-11-13` and `2da481f-2018-02-23` with Alert volume profile of `Medium` and `High` and default xDrip sound and default ringtone sound. With the high glucose alarm set. It all worked correctly.

**Comment by drnoname82** [comment]
The changes in the 23rd Feb nightly ( https://github.com/NightscoutFoundation/xDrip/commit/e03c1db5abf8e7441fdb8173e1efd10f3c6bbeff ) appear to have solved the problem. I will do some more testing with different settings, but so far all alerts have been played.

**Comment by jamorham** [comment]
Ok, I am thinking you need to test for longer because I haven't been able to reproduce the problem here on any xDrip version, so it may be related to object lifecycle. I have had alarms going off all day on the test device here but it may not have much memory pressure due to being a fresh install of LineageOS

**Comment by drnoname82** [comment]
We have been testing this for a week now and so far it has worked perfectly. I think you solved our problem, thank you! (Reverting to versions before the commit let the error reappear)

**Comment by jamorham** [comment]
Okay nice one. I will mark this as resolved.

**Comment by drnoname82** [comment]
Unfortunately the error is back :( Your fix worked flawlessly until today, now we have the exact same problem again. Nothing about the phone‘s configuration has changed, no updates etc. XDrip version is from Feb 23rd. After a restart alerts started working again.
