### ISSUE TITLE
"Cannot save block will null data" with Freestyle Libre

### ISSUE THREAD

**Issue by Itja** [NightscoutFoundation/xDrip#315]
Hi, I'm a nightscout user and just discovered xDrip+. Trying it out with a Moto Z Play on an Abbott Freestyle Libre sensor (NFC). I tried it with the *latest APK* from JoH's site as well as using a fresh build of the master branch using Android Studio under Windows 8.1, both times with the same results. The only things changed after app installation are *Hardware Data Source* set to **Libre Bluetooth**, enabled *Use NFC feature* and also enabled *Scan when not in xDrip+*. Glimp was uninstalled prior to the first installation of xDrip+.

## Problem
Promptly after holding the phone onto the sensor, a `Scanned OK!` toast appears and the view switches to the graph. However, no points or lines or anything is drawn in the graph. It keeps being empty. The events log inside the application has one entry:

> **LibreBlock**
> Cannot save block will null data
> 23 Feb 2018 8:48:31 PM

The Logcat output of Android Studio seems to have some clues about this failed scan. However, as I've never used xDrip before, I hope you can find what's going wrong much faster than I could. 

## Logcat output

I pasted the full log output [here as a Gist](https://gist.github.com/Itja/f94cbc0405c387d6176da98f27b414f1) as it is quite long. A shortened version is here:

```
02-23 20:48:31.011 25008-25021/com.eveningoutpost.dexdrip D/NFCReaderX: Reader mode tag discovered
02-23 20:48:31.040 25008-25021/com.eveningoutpost.dexdrip D/jamorham JoH: nfc-debounce rate limited: 1 seconds
02-23 20:48:31.041 25008-25021/com.eveningoutpost.dexdrip D/jamorham exec: New task queue for: doTheScan
02-23 20:48:31.042 25008-25021/com.eveningoutpost.dexdrip D/jamorham exec:  New thread: doTheScan
02-23 20:48:31.047 25008-25008/com.eveningoutpost.dexdrip I/jamorham JoH: Displaying toast using fallback
02-23 20:48:31.294 25008-26936/com.eveningoutpost.dexdrip I/jamorham JoH: Benchmark: Tag read 243.0 ms
02-23 20:48:31.294 25008-26936/com.eveningoutpost.dexdrip D/NFCReaderX: GOT TAG DATA!
02-23 20:48:31.299 25008-25008/com.eveningoutpost.dexdrip I/jamorham JoH: Displaying toast using fallback
02-23 20:48:31.300 25008-25008/com.eveningoutpost.dexdrip D/NFCReaderX: onPostExecute called
02-23 20:48:31.300 25008-26936/com.eveningoutpost.dexdrip D/jamorham exec: Queue empty: doTheScan
02-23 20:48:31.348 25008-26946/com.eveningoutpost.dexdrip I/jamorham librereceiver: Data that was recieved from librealarm is <null>
02-23 20:48:31.348 25008-26946/com.eveningoutpost.dexdrip E/LibreBlock: Cannot save block will null data
02-23 20:48:31.355 25008-26884/com.eveningoutpost.dexdrip V/FA: Activity paused, time: 1824696218
02-23 20:48:31.356 25008-26946/com.eveningoutpost.dexdrip D/jamorham librereceiver: Sensor age advanced to: 5680
02-23 20:48:31.357 25008-25008/com.eveningoutpost.dexdrip D/jamorham: Home: Processing incoming bundle
02-23 20:48:31.357 25008-26946/com.eveningoutpost.dexdrip D/jamorham librereceiver: Oldest cmp: 1970-01-01 00:59:59 Newest cmp: 1970-01-01 00:59:59
02-23 20:48:31.357 25008-26946/com.eveningoutpost.dexdrip D/jamorham librereceiver: Lag Timeshift: 17
02-23 20:48:31.357 25008-26946/com.eveningoutpost.dexdrip D/jamorham librereceiver: DEBUG: sensor time: 5665
02-23 20:48:31.357 25008-26884/com.eveningoutpost.dexdrip V/FA: Activity resumed, time: 1824696221
02-23 20:48:31.359 25008-26946/com.eveningoutpost.dexdrip D/BgReading: getForPreciseTimestamp: No luck finding a BG timestamp match: 2018-02-23 20:33:31 precision:270000.0 Sensor: null
02-23 20:48:31.360 25008-26946/com.eveningoutpost.dexdrip D/jamorham librereceiver: Creating bgreading at: 2018-02-23 20:33:31
02-23 20:48:31.370 25008-25008/com.eveningoutpost.dexdrip D/jamorham: Home: Refresh Status Line: 
02-23 20:48:31.372 25008-25008/com.eveningoutpost.dexdrip D/jamorham: Home: updateCurrentBgInfo from: generic on resume
02-23 20:48:31.379 25008-25008/com.eveningoutpost.dexdrip D/jamorham graph: Noise Cached noise timestamp: 1970-01-01 00:59:59
02-23 20:48:31.379 25008-25008/com.eveningoutpost.dexdrip E/jamorham graph: Exception doing iob values in bggraphbuilder: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
02-23 20:48:31.379 25008-26946/com.eveningoutpost.dexdrip I/BG GSON:: {"a":0.0,"age_adjusted_raw_value":0.0,"b":0.0,"c":0.0,"calculated_value":0.0,"calculated_value_slope":0.0,"calibration_flag":false,"dg_mgdl":0.0,"dg_slope":0.0,"filtered_calculated_value":0.0,"filtered_data":0.0,"hide_slope":false,"ignoreForStats":false,"ra":0.0,"raw_calculated":0.0,"raw_data":0.0,"rb":0.0,"rc":0.0,"time_since_sensor_started":0.0,"timestamp":0}
02-23 20:48:31.380 25008-26946/com.eveningoutpost.dexdrip D/jamorham librereceiver: Oldest : 1970-01-01 00:59:59 Newest : 1970-01-01 00:59:59
02-23 20:48:31.380 25008-26946/com.eveningoutpost.dexdrip D/jamorham librereceiver: DEBUG: sensor time: 5666
02-23 20:48:31.382 25008-26946/com.eveningoutpost.dexdrip D/BgReading: getForPreciseTimestamp: No luck finding a BG timestamp match: 2018-02-23 20:34:31 precision:270000.0 Sensor: null
02-23 20:48:31.382 25008-26946/com.eveningoutpost.dexdrip D/jamorham librereceiver: Creating bgreading at: 2018-02-23 20:34:31
02-23 20:48:31.391 25008-25008/com.eveningoutpost.dexdrip I/jamorham graph: Raw points size is zero
02-23 20:48:31.392 25008-26946/com.eveningoutpost.dexdrip I/BG GSON:: {"a":0.0,"age_adjusted_raw_value":0.0,"b":0.0,"c":0.0,"calculated_value":0.0,"calculated_value_slope":0.0,"calibration_flag":false,"dg_mgdl":0.0,"dg_slope":0.0,"filtered_calculated_value":0.0,"filtered_data":0.0,"hide_slope":false,"ignoreForStats":false,"ra":0.0,"raw_calculated":0.0,"raw_data":0.0,"rb":0.0,"rc":0.0,"time_since_sensor_started":0.0,"timestamp":0}
02-23 20:48:31.393 25008-26946/com.eveningoutpost.dexdrip D/jamorham librereceiver: Oldest : 1970-01-01 00:59:59 Newest : 1970-01-01 00:59:59
02-23 20:48:31.393 25008-26946/com.eveningoutpost.dexdrip D/jamorham librereceiver: DEBUG: sensor time: 5667
02-23 20:48:31.395 25008-26946/com.eveningoutpost.dexdrip D/BgReading: getForPreciseTimestamp: No luck finding a BG timestamp match: 2018-02-23 20:35:31 precision:270000.0 Sensor: null
02-23 20:48:31.395 25008-26946/com.eveningoutpost.dexdrip D/jamorham librereceiver: Creating bgreading at: 2018-02-23 20:35:31
02-23 20:48:31.395 25008-25008/com.eveningoutpost.dexdrip I/jamorham JoH: Benchmark: Default lines create - bggraph builder 17.0 ms
02-23 20:48:31.401 25008-25008/com.eveningoutpost.dexdrip I/jamorham JoH: Benchmark: Clone preview data 3.0 ms
```

**Many more similar lines here**

```
02-23 20:48:32.657 25008-26946/com.eveningoutpost.dexdrip I/BG GSON:: {"a":0.0,"age_adjusted_raw_value":0.0,"b":0.0,"c":0.0,"calculated_value":0.0,"calculated_value_slope":0.0,"calibration_flag":false,"dg_mgdl":0.0,"dg_slope":0.0,"filtered_calculated_value":0.0,"filtered_data":0.0,"hide_slope":false,"ignoreForStats":false,"ra":0.0,"raw_calculated":0.0,"raw_data":0.0,"rb":0.0,"rc":0.0,"time_since_sensor_started":0.0,"timestamp":0}
02-23 20:48:32.658 25008-26946/com.eveningoutpost.dexdrip D/jamorham librereceiver: Oldest : 1970-01-01 00:59:59 Newest : 1970-01-01 00:59:59
02-23 20:48:32.659 25008-26946/com.eveningoutpost.dexdrip D/jamorham librereceiver: Spline: 2018-02-23 20:38:31 value: 2170
02-23 20:48:32.660 25008-26946/com.eveningoutpost.dexdrip D/BgReading: getForPreciseTimestamp: No luck finding a BG timestamp match: 2018-02-23 20:38:31 precision:270000.0 Sensor: null
02-23 20:48:32.661 25008-26946/com.eveningoutpost.dexdrip D/jamorham librereceiver: Creating bgreading at: 2018-02-23 20:38:31
02-23 20:48:32.666 25008-26946/com.eveningoutpost.dexdrip I/BG GSON:: {"a":0.0,"age_adjusted_raw_value":0.0,"b":0.0,"c":0.0,"calculated_value":0.0,"calculated_value_slope":0.0,"calibration_flag":false,"dg_mgdl":0.0,"dg_slope":0.0,"filtered_calculated_value":0.0,"filtered_data":0.0,"hide_slope":false,"ignoreForStats":false,"ra":0.0,"raw_calculated":0.0,"raw_data":0.0,"rb":0.0,"rc":0.0,"time_since_sensor_started":0.0,"timestamp":0}
02-23 20:48:32.667 25008-26946/com.eveningoutpost.dexdrip D/jamorham librereceiver: Oldest : 1970-01-01 00:59:59 Newest : 1970-01-01 00:59:59
02-23 20:48:32.668 25008-25008/com.eveningoutpost.dexdrip D/jamorham: Home: updateCurrentBgInfo from: new data
02-23 20:48:32.673 25008-25008/com.eveningoutpost.dexdrip D/jamorham graph: Noise Cached noise timestamp: 1970-01-01 00:59:59
02-23 20:48:32.674 25008-25008/com.eveningoutpost.dexdrip E/jamorham graph: Exception doing iob values in bggraphbuilder: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
02-23 20:48:32.686 25008-25008/com.eveningoutpost.dexdrip I/jamorham graph: Raw points size is zero
02-23 20:48:32.690 25008-25008/com.eveningoutpost.dexdrip I/jamorham JoH: Benchmark: Default lines create - bggraph builder 18.0 ms
02-23 20:48:32.696 25008-25008/com.eveningoutpost.dexdrip I/jamorham JoH: Benchmark: Clone preview data 3.0 ms
02-23 20:48:32.706 25008-25008/com.eveningoutpost.dexdrip I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
02-23 20:48:32.709 25008-25008/com.eveningoutpost.dexdrip I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
02-23 20:48:32.711 25008-25008/com.eveningoutpost.dexdrip I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
02-23 20:48:32.712 25008-25008/com.eveningoutpost.dexdrip I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
02-23 20:48:32.714 25008-25008/com.eveningoutpost.dexdrip I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
```

Thank you for putting all the effort into this project!

**Comment by jamorham** [comment]
@Itja to ensure that this isn't a problem introduced recently by the new `LibreBlock` system can you please try installing an older version to see if the same problem exists there:

https://github.com/NightscoutFoundation/xDrip/releases/download/2017.11.13/xDrip-plus-20171113-20a4313.apk

xDrip allows any version to be installed over the top of any other so you don't need to uninstall.

**Comment by Itja** [comment]
Hey JoH, thanks for your answer!
First, I'm running Android 7.1.1 and when trying to install the APK directly, I get "**App not installed.**
The package conflicts with an existing package by the same name."

After uninstalling the current build and installing your APK, I still get no values in the graph on scanning. And still the "Scanned OK!" toast shows. However, there is no exception logged in the *Error and Event List* in the app, other than one that occured on startup (or even installation?) of the app: 

> **DailyIntentService** exception on CalibrationSendQueue [...] SQLiteException: no such column: mongo_success, while compiling: `DELETE FROM CalibrationSendQueue WHERE mongo_success = ?`

As I think this is unrelated to the issue, I have [uploaded the Logcat here](https://gist.github.com/Itja/56ececf86861b77356d86f58d315b030).

Again, thanks for looking into the issue!

**Comment by Itja** [comment]
@jamorham You have any clues as to why the read values are not saved? I will try and look if I can fix it this weekend.

**Comment by tzachi-dar** [comment]
I night be missing here something. But can you scan again, and then see if you can add calibrations to your system?
If not using the libreOOP algorithm, then xDrip will ask you to calibrate the readings.

**Comment by Itja** [comment]
Hi @tzachi-dar, thanks for your answer. I didn't know exactly what you meant by calibrations (as I never used xDrip+ before). What I did do now is tapping on the "pipette" (or pen?) icon up right in the graph. In the overlay, I hit the finger button down left and entered a value, after which I hit the green ✓ in the top right. I then touched the finger button again. I also opened the "Blood Test Action" box for two of the values and hit "Calibrate", but this did not seem to do anything. After doing all of this, I again did a "Scanned OK" unsuccessful scan. My screen now looks like this:

![device-2018-02-26-223050](https://user-images.githubusercontent.com/11618623/36696576-de441e16-1b44-11e8-8999-522572a751a1.png)

I also figured out the reason of the exception.

`LibreBlock.createAndSave` is called twice. The first time from `NFCReaderX.NfcVReaderTask.onPostExecute` directly with `this.data`, which contains valid data from the NFC read and thus, the call succeeds.

Afterwards, `NFCReaderX.NfcVReaderTask.parseData` is called to create a `ReadingData` object using the second `ReadingData` constructor. This causes the `raw_data` property of the `ReadingData` object to be `null`, which is important later.

The `onPostExecute` now passes on the `ReadingData` object as `mResult` on to a new thread, which runs `LibreAlarmReceiver.processReadingDataTransferObject` with `mResult` as a parameter. Inside, the `raw_data` property of `mResult` is passed on to the second call to `LibreBlock.createAndSave`, which subsequently must fail, due to the `raw_data` being null, as it tests for it explicitly to be not null.

I hope you know how to eliminate the exception. Does it even has to do something with no graph being displayed? 

Also, how can I choose another algorithm than libreOOP? Where is this algorithm used?

**Comment by tzachi-dar** [comment]
Hi, 
Currently, your device is looking for a BT device to scan.
As far as I can tell right now, you should go to settings->hw data source-> and choose LibreAlarm.
I believe that if you will choose that you will get a dialog saying that collection is running. 
After the scan you will have on the menu the option to add a double calibration.

By default xDrip has it's own algorithm, that is based on raw values and calibrations, so you have a choise of two algorithms...

I'll look deeply on the LibreBlock.createAndSave issue that you have raised, but I believe that the problem is not directly related to that.

Please change the settings and let me know how it is going.

**Comment by Itja** [comment]
Oh. It was so easy. Thanks. I had "Libre Bluetooth" selected.

Why does the "NFC Scan features" menu even show up, when "Libre Bluetooth" is selected (it does not for any other BT source) and why does it scan the sensor, while ignoring the results? What could have pointed me to select the correct "LibreAlarm"?

However, thank you very very much for the support and the development of xDrip+. I hope I can contribute some time in the future, too.

**Comment by tzachi-dar** [comment]
The reason that you can scan when "libre bluetooth" is on is because if you would have paired with the device you can still use the phone to scan the sensor.
But I'll open an issue on this wording problem.
