### ISSUE TITLE
xDrip+ can backfill a "flat line" of Libre values to Nightscout on restarting

### ISSUE THREAD

**Issue by endafarrell** [NightscoutFoundation/xDrip#316]
Though xDrip+ sees the last 8 hours of glucose readings on a restart in the morning, it seems to send the last value for the previous 8 hours to Nightscout's REST API.

![screenshot_2018-02-25-15-40-00](https://user-images.githubusercontent.com/890447/36642640-d7d0a96c-1a42-11e8-888d-1de1320aa2c2.png)

This first picture is a screenshot of xDrip+ (a recent nightly build) showing the values read from Libre. My setup is the Freestyle Libre, a Sony SW3 reads the Llibre for the Jamorham Libre Alarm as the collector and xDrip+ sends to Nightscout. I am unable to sleep with the SW3 - I seem to kill the Libre after only 7 days due to physically knocking it about too much while I sleep. Thus, I take and turn the SW3 off as I go to bed, I stop the Libre Alarm app on the phone and in the morning I turn everything back on and get them started again.

After I get them started, the graph on Nightscout is a flat line: 
![img_0077](https://user-images.githubusercontent.com/890447/36643050-ede7c6f0-1a46-11e8-95b8-95758eebed85.PNG)

Ever since the 13th of Jan 2018, the data on Nightscout is a flat line of glucose values, starting 8 hours before the first Libre Alarm reading, and all at the value of whatever that first Libre Alarm reading was. I checked that it wasn't a rendering problem with Nightscout by looking at the individual `sgv` values in my mLab `entries` collection - they are all the same value: and hence this issue.

However, I started with Libre Alarm and xDrip+ in Dec 2017 and for the first weeks this problem was not happening - but mid Jan was the time that I had to abandon trying to sleep the night wearing the SW3. I have not redeployed nor upgraded Nightscout during this time (I'm still successfully running my initial deployment). I _did_ upgrade xDrip+ from what was then the latest "release" version (early Nov I _think_, to a recent nightly build (a78dccd-2018.02.09), but that hasn't made a difference in this case.

This screen grab from Nightscout perhaps shows what happens a little more clearly: 
![nightscout gets flat lines](https://user-images.githubusercontent.com/890447/36643109-7e0fa00e-1a47-11e8-975f-3ef19d7dc77e.png)

Given that no-one else seems to have reported this issue, it may be that I am unusual in (a) reading a Libre via Libre Alarm and (b) not being to keep the system running all the time. It may of course be a case that I have an unusual combination of settings - but I need advice on what to try.

**Comment by endafarrell** [comment]
I was looking to see if any of my settings were contributing to this, and I suspect that having two "Cloud Upload > Nightscout Sync (REST-API)" URLs might be unusual. So, this morning before restarting the SW3 and Libre Alarm, I edited the setting to just have one, but it did not seem to affect how the numbers were reported.

**Comment by endafarrell** [comment]
![screenshot_2018-03-01-08-43-14](https://user-images.githubusercontent.com/890447/36836394-7fa4b2b6-1d39-11e8-9979-8f4e7bf3eead.png)

Here, Nightscout has a "flat line" of Libre values, but xDrip+ itself has the "correct" values:

![screenshot_2018-03-01-08-43-37](https://user-images.githubusercontent.com/890447/36836458-a447f6aa-1d39-11e8-8fcf-29cfbe3bd42c.png)

**Comment by tzachi-dar** [comment]
Are you using Oop algorithm?

**Comment by endafarrell** [comment]
@tzachi-dar If "Oop algorithm" means "Settings > Less common settings > Other misc options > Out of process blukon algorithm." then no, I'm not using it as I don't have a blukon device.

**Comment by tzachi-dar** [comment]
Can you please update to the latest nightly, and see if the problem still exists?
I have just checked it on my phone, and it seems to work OK.
If it does not, can you please do the following:
go to settings->less common settings->extra tags for logging and then add there: "BgReading:v"
Do an upload, and send me the logs of it (use export database) and then share it with tzachi.dar@gmail.com

**Comment by endafarrell** [comment]
Hi @tzachi-dar - thanks for looking at this.

I've updated to https://github.com/NightscoutFoundation/xDrip/releases/tag/2018.02.28 (9e9ad76-2018.02.28 Code 1802281519) and stopped the Libre Alarm app on the phone before I ate. Then, an hour or so later, I started the Libre Alarm app again and the problem is still evident.

xDrip+ shows the correct LibreAlarm values: 
![screenshot_2018-03-01-20-10-56](https://user-images.githubusercontent.com/890447/36864823-092cc952-1d8e-11e8-98b6-6f2b435ac1f7.png)

... but what is sent to Nightscout is the "flat line":
![screenshot_2018-03-01-20-13-08](https://user-images.githubusercontent.com/890447/36864852-22213e3e-1d8e-11e8-9c10-ee02b98cc9cf.png)


I'll now set the extra tags for logging, and I'll upload tomorrow morning and share the results then.

**Comment by endafarrell** [comment]
(Earlier today, I emailed @tzachi-dar the logs from this morning)

**Comment by jamorham** [comment]
Try turning off `Send Display Glucose` from the Nightscout Sync options in Cloud Upload settings and see if that makes any difference.

**Comment by endafarrell** [comment]
@jamorham I tried this by turning off Libre Alarm for an hour after breakfast - and it seems to have worked - instead of a "flat line", the Libre scanner, xDrip and Nightscout all show the same "s" curve I had this morning. 

Many thanks!

Is there anything I can do/try/help with this - or should I just Close it?

**Comment by tzachi-dar** [comment]
According to what I understand from getDisplayGlucose() it seems that it depends on readings arriving at order.
This is also the comment on: injectDisplayGlucose

However in the function CalculateFromDataTransferObject This is not the case. We need to sort values, before sending them up.

**Comment by endafarrell** [comment]
@tzachi-dar Do you think that sorting before sending would also "fix" #332?

**Comment by tzachi-dar** [comment]
I believe that yes.

**Comment by jamorham** [comment]
Can you try re-enabling the send display glucose option and install the March 6th Nightly and let me know if that solves the issue. Thanks.

**Comment by blocklist** [comment]
For mit it works @jamorham no longer a flat line. The 8h was rebuild/send now correctly to nightscout.

**Comment by endafarrell** [comment]
@jamorham and @blocklist - I am delighted to confirm that, with the Code: [1803061753 APK](https://github.com/NightscoutFoundation/xDrip/releases/tag/2018.03.06) (from yesterday), and with ``Settings | Cloud Upload | Nightscout Sync (REST-API) | Send Display Glucose = "ON"``, I see the same data on Nightscout as I do in the xDrip+ UI. 
Success!

![issue-316-is-fixed](https://user-images.githubusercontent.com/890447/37085156-97704850-21f4-11e8-9625-6e5168fe5749.PNG)

Many thanks @jamorham and @tzachi-dar for all of this.
