### ISSUE TITLE
Android 14, Google Health not working

### ISSUE THREAD

**Issue by daproc76** [NightscoutFoundation/xDrip#3160]
### Discussed in https://github.com/NightscoutFoundation/xDrip/discussions/3130

<div type='discussions-op-text'>

<sup>Originally posted by **daproc76** October 14, 2023</sup>
I use xdrip+ on an Android 14 device. When I trie to connect xdrip+ with Google Health, I get the message app update required - connect the developer.

Thanks for this great App. I love it.
Best regards
daproc76</div>

**Comment by jamorham** [comment]
Please try the latest xDrip+ nightly which should resolve the issue.

**Comment by Navid200** [comment]
Sorry, I forgot to close this.
@daproc76 Please let me know if this is still a problem.
