### ISSUE TITLE
Absence of sugar readings in the History section if one-minute values are received from the sensor.

### ISSUE THREAD

**Issue by Inkalika** [NightscoutFoundation/xDrip#3187]
I came across the fact that in the History section there is a limit on the number of sugar values. For example, if I receive 1 minute readings from Juggluco (Libre2), then for part of the night from 00:00 to 03:00-06:00 am (depending on how many readings there were during the day) there will be no readings. That is, the readings per day will be less than 1*60*24.
If I select 5-minute sugar values for display, then the sugar readings for the day will be complete.
Is it possible to increase the number of sugar storage points in the History section?

**Comment by Navid200** [comment]
Thanks for you contribution.
Please be kind and follow the request that you must have seen when you opened this issue and open a discussion instead.

In case you didn't see it, let me show it to you again:
![Screenshot 2023-11-16 085816](https://github.com/NightscoutFoundation/xDrip/assets/51497406/bfeaa63f-3ee8-4b02-b782-e05c47ab27b4)

And here is where you can open a discussion: https://github.com/NightscoutFoundation/xDrip/discussions

Please help us.
