### ISSUE TITLE
Errors in the operation of the active calibration plugin with the sensor Sibionics

### ISSUE THREAD

**Issue by Inkalika** [NightscoutFoundation/xDrip#3188]
I'm using a Sibionics sensor. In the sources I select 640g/Eversense. 
It works with the modified app Sugar Joy+ that can be downloaded from here https://t.me/kubarev_modz
In xDrip set the data source to 640g/Eversense.
Since this sensor can only be calibrated when the active calibration plate is turned on (the letter P in a circle is displayed next to the sugar value), after turning it on, the following errors were detected:
1) Raw readings are sent to Nightscout, not calibrated ones (after using the plugin)
2) If you delete calibrations on the phone Master or do calibrations. then instead of the sugar level, followers will display “???” until the initial calibration is completed. If 2 followers are enabled via the xdrip follower source, then this error can occur at any time and can be corrected by deleting one of the followers.

Is it possible to fix these functions when the active calibration plugin is enabled?

**Comment by Navid200** [comment]
Please do not open an issue.
