### ISSUE TITLE
Libre3 Webfollower: beonlabs community script for Web Follower is not available

### ISSUE THREAD

**Issue by Raimund58** [NightscoutFoundation/xDrip#3213]
### Discussed in https://github.com/NightscoutFoundation/xDrip/discussions/3125

<div type='discussions-op-text'>

<sup>Originally posted by **pkmzl** October 10, 2023</sup>
Hi,
the source of the custom script https://community-script.beonlabs.net returns a file with text "service ceased". So that xDrip doesn't get data from Libre 3 anymore.
How could the problem be solved?
</div>

The Libre3 Webfollower stopped getting data at some point. A fresh installation of xDrip didn't help.
If the necessary script is missing, it would also explain the missing sugar data. 
Please fix the script service if possible, the webfollower is awesome :)

**Comment by Raimund58** [comment]
Ref https://github.com/NightscoutFoundation/xDrip/discussions/3041 as well

**Comment by Navid200** [comment]
Can you ask in the following discussion for advice?
https://github.com/NightscoutFoundation/xDrip/discussions/3230

And please don't create an issue without being asked.  Thanks

**Comment by Raimund58** [comment]
wtf, why is it now working again? I just opened the xdrip app again. 
And the script is still empty. Man, I hate this obscure stuff.

**Comment by Raimund58** [comment]
I didn't need to create a new follower account or accept the TOS or stuff. It just worked again...
