### ISSUE TITLE
Vehicle mode does not stop after bluetooth is disconnected, causing 'speak readings' to continue.

### ISSUE THREAD

**Issue by Gferrar123** [NightscoutFoundation/xDrip#3219]
### Discussed in https://github.com/NightscoutFoundation/xDrip/discussions/3217

<div type='discussions-op-text'>

<sup>Originally posted by **Gferrar123** November 30, 2023</sup>
Vehicle mode does not stop after bluetooth is disconnected, causing 'speak readings' to continue.
Running Version 2023.11.14 
Samsung Galaxy 23 with Android 14
Dexcom G6
I have recreated it with two different bluetooth pairings and the issue has been confirmed by @Navid200 
Any fix would be great, but I would love to see a vehicle mode trigger based on Android Auto running, rather than a specific bluetooth connection.</div>

**Comment by FriedelPas** [comment]
The same here with the latest Samsung System update that installed One UI 6.0 and Android 14 on a Samsung Galaxy S21 FE 5G
Running version 2023.07.16

**Comment by Navid200** [comment]
Please note that you can disable the ongoing speak readings, after leaving the car, by disabling "Vehicle mode" under xDrip+ Motion tracking.

This is not a solution to the problem.  But, it is a way to disable the behavior until this is addressed.

**Comment by FriedelPas** [comment]
Yes, I know and have done that, what indicated me more clear that this was the reason. But I was thinking that adding extra input could help adressing the problem.
BTW, after the update of samsung, the phone said that xDrip was developped for an older version of the system and possible could cause problems. I not noticed problems at that time, but when first time driving with car the problems started. Until now it is the only issue that I had with the update.

Would be nice when problem solved, but also now xDrip stay the game changer in treathing my diabetes very well! Thanks to xDrip I can have values more then 90% in range and so getting an Hemoglobine A1C of 5.1%, so I'm very happy with this app.

**Comment by Kaapeli64** [comment]
I've been using Vehicle mode happily for years, today I got Android 14 update on my OnePlus Nord 2 5G and it no longer exits the Vehicle mode. In the morning I still had "Vehicle mode: Enabled" followed with "Vehicle mode: Disabled" prints in the log, but now after the update I only see "Vehicle mode: Enabled" prints one after one, every time I enter the car. xDrip no longer detects the exits.

**Comment by Navid200** [comment]
Please try the xDrip release of May 12, 2024 or any after that and if the problem persists, please report it here.

**Comment by Kaapeli64** [comment]
Thanks for the fix! Have been running it for couple of days now and it works just like it used to work before.

**Comment by vanelsberg** [comment]
> Please try the **xDrip release of May 12, 2024** or any after that and if the problem persists...

Thanx much! This version fixed the problem for me!

**Comment by Navid200** [comment]
There is a report on facebook that this is still happening for Android 13.

**Comment by wouterlemcke** [comment]
I still have this issue. Running Android 15 (Pixel 8) and Xdrip 2124091707

**Comment by Kaapeli64** [comment]
I think the big flag here is Android 15, has something changed there again? It certainly works fine for me on Android 14.
