### ISSUE TITLE
Remove duplicate Norwegian language in Crowdin and xDrip+

### ISSUE THREAD

**Issue by olorinmaia** [NightscoutFoundation/xDrip#3243]
I'm language coordinator for "Norwegian" and "Norwegian Bokmal" in AAPS and xDrip+ in Crowdin.

We had a similar issue in AAPS with duplicate Norwegian language entries in Crowdin. The correct language to translate is "Norwegian bokmål", as this is the default system language in Android for Norwegian phones. There is only one written language in Norway that is broadly used. I think Norwegian was added to crowdin by mistake, like with AAPS.

**Thus "Norwegian" https://crowdin.com/project/xdrip/no (45% translated,) can be removed/deleted in Crowdin and corresponding language choice in xDrip+ can also be removed.**

The choice for Norwegian bokmål in xDrip+ can be renamed from "Bokmal" to "Norsk bokmål" in language settings which should point to https://crowdin.com/project/xdrip/nb (100% translated in crowdin now :) )

Referring to conversation with Mathis Walter @ crowdin :)

![image](https://github.com/NightscoutFoundation/xDrip/assets/114103483/bcfceb2c-c1f6-41f6-8296-799dd17aad2c)

**Comment by Navid200** [comment]
Someone has added the language that you want to delete.
Why are they wrong and someone else is right?
What would be the problem if you allow this language to stay?  It will not stop anyone from using the language you want to keep, does it?

**Comment by Navid200** [comment]
Is this what you want to be deleted?
![Screenshot 2023-12-17 174314](https://github.com/NightscoutFoundation/xDrip/assets/51497406/378d5fad-05f2-4263-b293-0f25830c0a33)

<br/>  

If yes, you can see there have been updates to it on October 8, only 2 months ago.
I don't think we (xDrip) should get in the middle of ethnic disagreements.  I prefer that we find a solution that does not involve deleting someone else's hard work.

**Comment by Navid200** [comment]
Would you accept the following as a solution?

We change Bokmal to Norsk (Bokmal)?  And we change Norsk to Norsk (Nynorsk)?

And this is conditional on the other parties agreement.  So, we need to reach out to the others and get their agreement as well before we go ahead.  But, would you accept this?

**Comment by olorinmaia** [comment]
In Norway we got 3 different language options in android, nynorsk, norwegian bokmål (svalbard and jan mayen) and Norwegian bokmål. But only Norwegian Bokmål is regularly used. The two latter are basically the same language. Nynorsk is actually different from bokmål, but it not added to crowdin and is very little used in Norway :)
Not sure why both "no" and "nb" are added to Crowdin as they basically have been translating the same strings with the same words. 

Norwegian bokmål is default language in android on Norwegian phones.

There is no problem with keeping the language, except that some users maybe choose the lesser translated norwegian option. If you don't force any language in xDrip+ settings Norwegian Bokmål is loaded.

**Comment by olorinmaia** [comment]
> Would you accept the following as a solution?
> 
> We change Bokmal to Norsk (Bokmal)? And we change Norsk to Norsk (Nynorsk)?
> 
> And this is conditional on the other parties agreement. So, we need to reach out to the others and get their agreement as well before we go ahead. But, would you accept this?

I think this is also a good solution. Then most people will choose the correct Norwegian option to get proper Norwegian bokmål translations :)

**Comment by Navid200** [comment]
I hope I can make myself clear.
We should not make any decisions that rely on a judgement about what language is spoken in a country.
That really has nothing to do with the purpose of xDrip.

xDrip is to help everyone control their diabetes.  Languages have been added to allow more people benefit from xDrip.
We should be able to pursue that without getting into ethnic disagreements.  

Someone has added the language you want to delete.  I don't want us to do that unless the same person who added it comes here and says that yes, I made a mistake and I want this language to be deleted.  Without that, if we delete the language, even if the Norway's head of government asks us to do so, we would be out of line.  We don't get into politics here.  Someone has added this language.  I would like to hear their side before we go ahead and delete it.

**Comment by olorinmaia** [comment]
I understand your concerns. And I think your solution to keep them both and renaming to properly show what language you are selecting is fine. That solution doesn't require further discussion either from any part.

**Comment by Navid200** [comment]
It does.  As we need to change how the other language is presented, we still need their agreement as well to be fair.
I appreciate your agreement.  Thanks

**Comment by olorinmaia** [comment]
I can only see one other Norwegian user that has contributed to "Norwegian" in crowdin. To be honest I think you are making this abit more complicated than necessary. I've sent him a message to have a look at this issue.

Could you though rename the option "Bokmal" to "Norsk bokmål" so it's easier for Norwegian users to manually select the option in xDrip+ that has proper translations for their native language?

**Comment by Navid200** [comment]
This is just my opinion.  I am not the owner of this repository.  He may not care about any of my concerns.  I offer my opinion.  He makes the last call when there is a disagreement.

**Comment by ahaarrestad** [comment]
We should focus our efforts on one norwegian translation, not two. If I by mistake have not picked this up earlier, that's on me :-) I have done some translations without reflecting on this.

The suggestion to use the default setup is good. This will make it easier for users.

**Comment by olorinmaia** [comment]
Both crowdin languages have about the same translation for given strings. They are basically duplicates in terms of what is translated. Many of them are generated by jamorham also. Like we noticed with AAPS https://crowdin.com/project/xdrip/no isn't used on Norwegian android phones, thus translation are automatically fetched from https://crowdin.com/project/xdrip/nb which is the language we should focus on. "no" (Nynorsk) is a secondary native written language that we all learn in school, but isn't really used for anything anymore.

To be honest, there is no point keeping https://crowdin.com/project/xdrip/no and renaming to Nynorsk, because practically none in Norway uses this anyway. I think like in AAPS, "no" was added by mistake. We brought "nb" into AAPS crowdin to get automatically correct language in Norwegian phones and wear apps.

That's all there is to it really, we got one language in Norway that everyone knows, but for some reason android/crowdin got them abit mixed up. For norwegian users of xDrip+ the best solution without a doubt, is to remove crowdin/"no" in crowdin/xDrip, and rename crowdin/"nb" to "Norsk bokmål" in xDrip+.

@jamorham can you look at these comments, and @tolot27 comment from crowdin, and let me know what you think is the best approach?

**Comment by jamorham** [comment]
Hi there, the history of this I believe is that we had the `no` language code and were approached by Norwegians who said that there was also a `nb` language code. Understanding that Norway is a big place and there might easily be regional dialects I added this and people readily contributed to those translations. 

I think what is being discussed here is that the `no` localization is maybe redundant as `nb` is used very much as the main language or indeed that `no` is not a written language in itself?  I'm wary about removing something which might be a regional dialect without any personal knowledge about whether there are any cultural sensitivities around it. For example in the UK there are laws which protect the continued use of the welsh language and I wouldn't want to change anything that might affect a minority in general.

I am happy to change the force language choice option for `Norsk` to `nb` if that makes more sense, however that would have the effect of resetting anyone who currently has it forced to `no` back to the default next time they enter that preference screen so we might need a settings migration to make sure that doesn't happen. For non-forced languages the user's phone language setting should dictate which locale xDrip will use, for example `nb`

If there is more to this that I'm not understanding, please let me know. Thanks

**Comment by olorinmaia** [comment]
@jamorham I'll try to further explain.

There is no reason to have two languages in crowdin for Norwegian. The only one needed is "Norwegian bokmål" `nb` as this is the default and only written language used for norwegian android phones. If you want I can get several other norwegians to confirm this, but I find it strange that you don't believe me as I've done a similar change in AAPS to get proper translations in Norwegian. 

https://github.com/nightscout/AndroidAPS/issues/2790

See above issue with having the wrong norwegian language option `no` in AAPS and crowdin, this was fixed by adding `nb` (Norwegian bokmål) and transferring all translated strings from `no` to `nb` then deleting `no` from AAPS and crowdin so we could focus on proper translations for the one and only correct language for norwegians, Norwegian bokmål `nb`

We have also now translated Norwegian bokmål `nb` to 100% for xDrip+ and we won't bother translating `no` as this is basically a duplicate.

**Comment by jamorham** [comment]
Its not that I don't believe you, its just based on what I was told when the `nb` language was introduced to xDrip, it was that there were two languages for Norway was how it was expressed to me which is why I added the additional locale.  

I'm now being told that there is really only one and that it is `nb` vs `no` but because of the legacy of how the original `no` language is present in the array list for the forced language option I'm saying that change needs to be handled carefully to avoid negatively affecting users and that also I need to be sure that removing `no` completely is the right thing to do because I have no personal cultural understanding about whether there are any differences in those translated strings which might be important to anyone.

**Comment by ahaarrestad** [comment]
I might have added to the confusion when translating strings time years
ago. The above comment about how this should be done looks much more
correct than any comment i might have added. Please accept my appologies
for this.


It will be a good user experienced for the Norwegian user choosing
Norwegian language the way described in this thread. The aaps translations
works very well.

Alf Einar has dobe a great jo here and it will be better both for users and
maintainers to follow his advice.

Asbjørn

lør. 23. des. 2023, 13:40 skrev JamOrHam ***@***.***>:

**Comment by FredriHo** [comment]
As a fellow Norwegian I can also confirm what @ahaarrestad and @olorinmaia is saying. We do have three written languages in Norway, and they are accordingly to the ISO 639-1 nb, nn, and se. NO does not exsist. If the NO language option indeed was translated to nynorsk(nn) og sapmi(se), I would totally agree with @jamorham and @Navid200, however this translation is just an unfinished and bad nb (norsk bokmål). This is not a question og ethnicity or politics, it's a matter of cleaning up and avoid Norwegian users being confused and getting a worse experience of xDrip than they could have had choosing the language code that actually have been put an effort in translating.

**Comment by Veysel-Akbina** [comment]
I agree with my fellow Norwegian commentators, there is really no need for confusion with multiple Norwegian languages in Xdrip. Norsk Bokmål is the de facto standard in many aspects of Norwegian society, including education, media, and official communications.  I give full credit to Alf Einar for his effort to make things as simple as possible for Norwegian users of Xdrip.

Best regards
Veysel

**Comment by Navid200** [comment]
My concern was exactly the same as jamorham's.  
In Canada, where I live, there are also sensitivities to language and language rights.

I'm afraid some of you here may be overlooking the fact that when someone is in a position of making decisions that affect a very large group, there is a very heavy weight on their shoulder if they are not in it for personal financial gain.

Sometimes, majority may not be right.  There may be individuals who are affected by this who are not present here.  That's not going to change no matter how many more people come here and agree with you.

If you look at jamorham's first post here, he has clearly explained what he is comfortable doing.  But, I don't see any of you explaining if that is acceptable or not and why.  
Can you please put yourselves in his shoes instead of trying to convince him that you are right?
Sometimes, there isn't a right and a wrong but rather the best way forward.

I suggested something similar at the beginning and there was agreement.  What changed?  Why are we back at "deleting" again?

**Comment by jamorham** [comment]
Thanks for the additional information. My understanding of the situation and steps we should consider:

1) Norwegian user's phones will automatically use the `nb` strings so by default they will get the best strings already.
2) Any effort made on `no` strings on crowdin is wasted and so that language should be removed there.
3) The only time that the `no` strings will be used in xDrip is if the user has used the xDrip force language option and selected `Norsk`

To resolve 3, we should change this language value to `nb` and then create a legacy settings update feature to move anyone from `no` forced language to `nb` forced language. After this is done we can also remove the `no` translated strings from the xDrip source tree as these would never be accessed.

If anyone has any comments about whether I've missed anything or misunderstood please let me know?

**Comment by FredriHo** [comment]
@Navid200 because it's the by far best solution to this. As I quite explicitly pointed out, the NO-translation is just a NB(norsk bokmål) left-hand work. It's not a matter of others hard work or ethnicity/politics issues.

**Comment by olorinmaia** [comment]
> Thanks for the additional information. My understanding of the situation and steps we should consider:
> 
> 1. Norwegian user's phones will automatically use the `nb` strings so by default they will get the best strings already.
> 2. Any effort made on `no` strings on crowdin is wasted and so that language should be removed there.
> 3. The only time that the `no` strings will be used in xDrip is if the user has used the xDrip force language option and selected `Norsk`
> 
> To resolve 3, we should change this language value to `nb` and then create a legacy settings update feature to move anyone from `no` forced language to `nb` forced language. After this is done we can also remove the `no` translated strings from the xDrip source tree as these would never be accessed.
> 
> If anyone has any comments about whether I've missed anything or misunderstood please let me know?

This sound like a good way to solve this and i will assist with testing so we know it works like we expect. Please also change display name in xdrip of `nb` to "Norsk bokmål" or just "Norsk" when `no` is removed.

Im eager to check out the newly 100% translation of `nb`, is it planned a nightly release soon with new strings from crowdin? 😀

**Comment by t1dude** [comment]
Seems like there's already enough confirmation, but I'm adding one anyway. Norsk Bokmål is the correct language for Norwegian users, and no one will complain about this being fixed.

**Comment by Navid200** [comment]
I am closing this because I believe it was addressed already with this: https://github.com/NightscoutFoundation/xDrip/pull/3349

If not, please let me know and we can reopen.
