### ISSUE TITLE
Sanity check raw filtered / unfiltered values

### ISSUE THREAD

**Issue by scottleibrand** [NightscoutFoundation/xDrip#327]
Per https://gitter.im/nightscout/intend-to-bolus?at=5a999410458cbde557e9f3ed and https://github.com/openaps/oref0/pull/942 there is a safety issue with xDrip allowing a sensor with very low filtered and unfiltered values to be calibrated, which results in xDrip reporting the same SGV/glucose value indefinitely until the next calibration.  We should add thresholds for various device types for the known sane value ranges, as is done with G5 already.

**Comment by jamorham** [comment]
I've implemented this and currently am testing it locally to ensure normal operation.

**Comment by jamorham** [comment]
published in the March 5th nightly

**Comment by Navid200** [comment]
@scottleibrand Would you please close this issue if it has been addressed?
If not, would you please update?
Thanks
