### ISSUE TITLE
Bluetooth may be disabled by airplane mode

### ISSUE THREAD

**Issue by gitanO0** [NightscoutFoundation/xDrip#3273]
I've opened this issue as instructed by @Navid200  via [this ](https://github.com/NightscoutFoundation/xDrip/discussions/3270)discussion.

The following is only a summary, please refer to the above discussion for more details.

Google has relaxed how it implements airplane mode and it seems that xdrip+ is at odds with how it implements airplane mode restriction vs how Google/Android handles airplane mode.

[Google allows airplane mode to be enabled on Android devices (at Android 14+) while keeping Bluetooth and WIFI turned on.](https://www.sammobile.com/news/android-14-smarter-flight-mode-samsung-galaxy-phones/)
Xdrip+ has had a limitation where it stops collecting if airplane mode is turned on.  I believe the issue arises from the following scenario:  Airplane mode is enabled and wifi and BT remain turned on.  If you step away from your phone and lose connection and the BT watchdog becomes active, it will try to reconnect BT which then fails due to airplane mode being turned on.  There is an xdrip event log entry that states, "Not setting Bluetooth to state: true due to airplane mode being enabled".

Would like it if xdrip could ignore airplane mode during its BT Watchdog processes and simply continue to function, if that is in fact the issue.

**Comment by Navid200** [comment]
@gitanO0 Please try the latest xDrip release and see if it makes a difference and please report.
Thanks

**Comment by Navid200** [comment]
https://github.com/NightscoutFoundation/xDrip/releases/tag/2024.01.05

**Comment by gitanO0** [comment]
On it.

**Comment by gitanO0** [comment]
Preliminary test is positive. I enabled airplane mode and then turned off BT. Waited until the next collection cycle and BT was auto turned on and the data came through. Yes! I suspect that this is a good fix. I'll need to wait a little longer to do the other edge case scenario where airplane mode is enabled. Bluetooth is on but then I go out of sensor range and Bluetooth starts doing the watch dog thing and tries to toggle Bluetooth. But then before the fix it wouldn't have been able to work because of the airplane mode situation. But now it seems that it will just turn on automatically and things should work.

**Comment by Navid200** [comment]
Closing as it seems it has been addressed by this release: https://github.com/NightscoutFoundation/xDrip/releases/tag/2024.01.05

We can reopen if not.
