### ISSUE TITLE
Extend date string parsing to handle "2018-03-03T11:22:48+01:00"

### ISSUE THREAD

**Issue by endafarrell** [NightscoutFoundation/xDrip#331]
While investigating #316 I noticed that the AndroidAPS.log had many entries of the form

```11:25:50.585 [IntentService[DataService]] ERROR [NSDeviceStatus.java:243]: Unhandled exception
java.text.ParseException: Unparseable date: "2018-03-03T11:22:48+01:00" (at offset 19)
        at java.text.DateFormat.parse(DateFormat.java:571) ~[na:0.0]
        at info.nightscout.utils.DateUtil.fromISODateString(DateUtil.java:51) ~[na:0.0]
        at info.nightscout.androidaps.plugins.NSClientInternal.data.NSDeviceStatus.updatePumpData(NSDeviceStatus.java:213) ~[na:0.0]
```

While I am (strangely, but I am not an Andriod developer) not able to find a ``NSDeviceStatus.java`` file in https://github.com/NightscoutFoundation/xDrip I see two ``DateUtil.java``, one in ``:app`` and the other in ``:wear``. If I was to create a Pull Request for thie, would those be the two files to change?

**Comment by tzachi-dar** [comment]
This is very likely an issue on android aps and not in xDrip.

Try:
https://github.com/MilosKozak/AndroidAPS/blob/b9b99917d9284dd46aebb0d5b82f64d544bb62d0/app/src/main/java/info/nightscout/androidaps/plugins/NSClientInternal/data/NSDeviceStatus.java#L207

**Comment by endafarrell** [comment]
@tzachi-dar Let me know if a PR on extending xDrip's DateUtils to cover that would be of any benefit. I don't know if xDrip is ever presented to these kinds of date strings.

**Comment by endafarrell** [comment]
@tzachi-dar - is #309 related to this - or is #309 an exception from within the AndroidAPS code that is bubbling-up to xDrip?

**Comment by BigWebstas** [comment]
any update on the resolution? im having trouble getting stuff from Diabetes:m >> Nightscout >> Xdrip+

![image](https://user-images.githubusercontent.com/2896329/61742194-ccb5d100-ad4f-11e9-9629-64e94e6793d2.png)

**Comment by Navid200** [comment]
@endafarrell Would you please close this if it is resolved?
I see the second post stating that this is very likely not due to xDrip.
You never responded to that comment.
Do you disagree?
If not, let's close the issue please.
Thanks

**Comment by endafarrell** [comment]
Hi Navid200

I cannot be sure where the problem was or what changed for the problem to have been resolved, but this isn't a problem any more.
