### ISSUE TITLE
Have "Send Display Glucose" only smoothen the last 3-to-5 readings when more than 30 min of new data is uploaded.

### ISSUE THREAD

**Issue by endafarrell** [NightscoutFoundation/xDrip#332]
```Settings | Cloud Upload | Nightscout Sync (REAST-API) | Send Display Glucose ``` is a very useful setting (for me) as it greatly helps my CGM to be stable. My sensor is a FreeStlye Libre, and it can at time be noisy, hence this setting helps.

However, if there is a long time between xDrip obtaining glucose values[1], this setting can "smoothen" out the values to be a "flat line", as seen in #316. Therefore, when uploading to Nightscout, only "smoothen" the last 3-to-5 readings when there is more than 30 min of new glucose readings being uploaded. It is better that the earlier ones be noisy than flat as the Nightscout reports and newer tools like Autotune will be more accurate.

/e

[1] eg: if I take the SW3 off the Libre at night, and turn (my xDrip HW source) LibreAlarm off until morning. If I sleep on the SW3+Libre, I seem to physically deform the cannula and the Libre dies after about 7 days, returning only a "LO" reading.

**Comment by tzachi-dar** [comment]
Does this happen by default, or did you set anything for it to happen?

**Comment by jamorham** [comment]
@endafarrell Can you try the March 6th nightly and let me know whether this resolves the issue?

**Comment by endafarrell** [comment]
Hi @tzachi-dar - sorry I didn't see your comment until @jamorham mentioned me.

Your fix for #316 has removed the need for this issue - with the [2018.03.06 APK](https://github.com/NightscoutFoundation/xDrip/releases/tag/2018.03.06) the data sent to Nightscout is smooth without being a flat line. Success :-)

![issue-316-is-fixed](https://user-images.githubusercontent.com/890447/37085417-46ed1326-21f5-11e8-87bf-cc2e53817b7f.PNG)

Many thanks to you both for this.
