### ISSUE TITLE
Can't see glucose value on the Screen... 

### ISSUE THREAD

**Issue by parapenT1sta** [NightscoutFoundation/xDrip#336]
... when using Libre NFC option and after I scan the sensor with my smartphone. Is it because it's displaying Bluetooth option alert message? 

![screenshot_20180307-003616_xdrip](https://user-images.githubusercontent.com/608650/37067141-5f50ffb8-21a0-11e8-844c-37befa69c7e0.jpg)

**Comment by jamorham** [comment]
Are you using a bluetooth bridge device at all?

If not, try the LibreAlarm data source and see if that works better.

**Comment by parapenT1sta** [comment]
No Bluetooth at all. I am waiting for T-mini.

LibreAlarm source fixed it! Thanks! 

I am closing it.
