### ISSUE TITLE
Pebble app is causing 60min+ missed readings (possibly)

### ISSUE THREAD

**Issue by bryanw20** [NightscoutFoundation/xDrip#339]
Moto G5 plus, stock 7.0 phone.
Xdrip+ latest nightly builds, or latest stable version (Nov I think it is)

I may need to do more testing; but I think the pebble app is causing me to lose signal for 60min+. A restart collector occasionally works; swapping collector type [ob1/old] sometimes helps too. But usually needs a phone reboot to restore the connection.
This drop out can happen in different locations (home, work, car, etc) So I don't believe it to be interference from something specific. It can be at anytime of day/night. But usually only happens once in a day - 2 days (not several times a day/24hr period).

I first tried turning off the pebble watch, still had app installed. still had missed readings.
Removed the Pebble app; as recommended by @jamorham  and tested for about 36-48 hours & no large missed readings happened (several 10-15; but never more than about 15min)
After re-installing the pebble app I got a missed reading w/in a few hours, and again the next night.

I have been using this Moto for about a year. I used to get ~88% capture rate pre ob1; and ~98% post.

I have sent logs from xdrip in; I'm not sure if/how I can attach them here.

**Comment by jamorham** [comment]
I don't think its the pebble app exactly. I expect it will be bluetooth resource starvation within Android.

Basically you can imagine that whenever android is hunting to connect to a bluetooth device it is using up a slot. Anything you have paired or any apps which are searching for peripheral devices will be using this up. Too many slots used up and bluetooth has problems.

Does your pebble app have watches in there you are not using? Do you have anything else paired in android bluetooth settings that you're not using? Try removing those if so.

**Comment by bryanw20** [comment]
Thanks.
I did just now delete all but a few watch faces. I use xdrip clay 98% of the time. When I take a dex break for a few days I use another face.
Let's see if that helps.

as for BT devices, I have a few paired with my phone. I use headphones 1-4times a week, so I want to keep them paired. as well as the onetouch meter. I could possibly remove the OBDii device until I need to use it on a car.
![bt](https://user-images.githubusercontent.com/26827860/37105352-8a259fec-21f4-11e8-961d-8dd0c4d6af75.png)

here's my log from today just as you were replying, I caught it at 15min missed; rebooted & back up at the 20min mark.
![log1](https://user-images.githubusercontent.com/26827860/37105387-a3b14e7a-21f4-11e8-969d-fa1f003cc58e.png)

**Comment by bryanw20** [comment]
And here's some log data for the other day. Post re-install pebble app. probably a 60-75min missed time.

![log2](https://user-images.githubusercontent.com/26827860/37105433-ca6a9ae4-21f4-11e8-880c-e5ddd0d3e0af.png)
![log3](https://user-images.githubusercontent.com/26827860/37105434-ca820c9c-21f4-11e8-928d-4e8ecb09bbd1.png)
![log4](https://user-images.githubusercontent.com/26827860/37105436-cae5b184-21f4-11e8-9203-536b45a822c7.png)

**Comment by bryanw20** [comment]
Thanks again for taking time to help.

While I'm on the subject of pebble; I don't think it's adding any step/motion tracking to xdrip. Pebble shares with google fit.

I have a little guy on my screen, but he's always at 1503, every day. no motion blur colors on the graph.

???
![tracking1](https://user-images.githubusercontent.com/26827860/37105909-0065fca0-21f6-11e8-8391-587479146029.png)
![tracking2](https://user-images.githubusercontent.com/26827860/37105910-007cd664-21f6-11e8-9e3d-85a10dd182b4.png)
![tracking3](https://user-images.githubusercontent.com/26827860/37105911-00929ddc-21f6-11e8-8ec7-0536baa38da8.png)
![tracking4](https://user-images.githubusercontent.com/26827860/37105912-00b06fce-21f6-11e8-8089-121651d098ea.png)

**Comment by Antonio2001** [comment]
@bryanw20 Good morning from Spain. I'm sorry to write in your post as my question is not related to it, I haven't found a way to write you a prívate message.
Is it possible to use Pebble as a collector when you are away from the phone? I have read it is but the option doesn't appear in xdrip (it does if you choose Android Wear) If yes, does it work with Pebble round too?
Thank you so much for your help.
Kind regards

**Comment by bryanw20** [comment]
@Antonio2001 I'm still new at things. But my understanding is pebble can only display xdrip data from the phone.
I believe certain Android watches that have a full Android on them are the only ones capable of being a collector. Like a Sony sw3 I think.

**Comment by Antonio2001** [comment]
Thank you bryanw20

**Comment by bryanw20** [comment]
Apparently it's just me; and I guess reducing the # of watch faces may have helped, or possibly something in a newest build; either way it's been several days now w/o a major loss of signal.
