### ISSUE TITLE
Feature Request: New alarm type for make benefit of a peaceful night's sleep.

### ISSUE THREAD

**Issue by old-square-eyes** [NightscoutFoundation/xDrip#342]
Any person with a Dexcom (that has to pay for it) will, like me, be extremely sleep deprived - more so than most diabetics. This is because we have noisy starts and noisy endings as we try to squeeze the most out of our sensors.

In spite of a few awfully confusing settings which appear to allow for such occurrences, alarms still fire on a hair trigger when small amounts of noise creeps in.

I'd like to propose a new High and Low alarm type, which can be used to catch slower rates of change in basal affected BG, but have more configurable tolerance for noise. This is the only thing I'm concerned about overnight, and when set at a tighter threshold than my actual High and Low alarms, I could safely be alerted with a softer beep when I drift off course, even with noise.

**Proposal**
Additional universal, configurable High/Low Alarm - Outside x threshold, for n minutes. With the option to take the average  BG from n readings. Or if not average, then some algorithm like oref0 BG calculation used for DIYPS.

**Uses**
- Easier to understand and configure than other disparate, confusing options
- Could also be used as a better sustained High alarm than the current one, which only looks at the system "High" setting. For example, I'd like to configure a lower high value, to be woken from, if it is maintained past a certain threshold. 8hrs overnight, a little bit high, has very poor long term health outcomes.

![screenshot_20180310-015057](https://user-images.githubusercontent.com/25760491/37239256-2699cb6e-249d-11e8-862a-eae0463b9bd0.png)

**Comment by tzachi-dar** [comment]
There are two things that can get you very near to what you want:

1) for high, there is a persistent high alert.
2) For both, alerts can start snoozed which means that if you put your default snooze for the alert on x minutes, it will only fire once you are low for x minutes.

Hope this helps.

**Comment by ANDREAPIPPI** [comment]
Hi.
I'm increasing the Italian translation of the English text, but it would be a very easier task if 
I could do it on a text file with PC, instead of on a Smartphone.
Is this possible?
If yes, where can I find the text file?
Thank you.
Bye
Andrea    :-)


> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/NightscoutFoundation/xDrip/issues/342#issuecomment-372605064

Andrea Pelloni

**Comment by old-square-eyes** [comment]
@tzachi-dar I touched on these. Persistent high is not configurable and is tied to the system hyper setting.

It would be great if you could access something similar through the High/Low alerts screen. Then you could have multiple. I personally want to be alerted if I'm semi-high, for any extended length of time.

As for #2 I'm not seeing that behaviour. My low alert is 3.5 with a default snooze of 30 minutes on start snoozed... in the picture above, it fired and woke me up.

Lastly, I'm still at a loss as to what the "Snooze Alert Before It Fires" button and sub options is supposed to achieve.

Thanks for the help though!

**Comment by old-square-eyes** [comment]
More info. I really need to figure out how to resolve this as I'm loosing my mind with the sleep loss :(

![untitled](https://user-images.githubusercontent.com/25760491/37572095-e91a0acc-2b6a-11e8-90e1-4e65dca69dfd.png)

**Comment by tzachi-dar** [comment]
snooze alert before it starts is meant to solve the following issue:
your BG is 100, you eat something, you have an alert on 120.
You see that BG goes up, and you know it will cross the 120 bar, you already gave insulin, so there is not much you can do about it.
So, you hope this will be resolved in 45 minutes. You snooze the alert even before it starts for 45 minutes. after that if bg is still not below 120 the alert will fire.

What is the sensor that you are using? if dexcom, are you using xDrip or xBridge? (I'm trying to understand if you have filtered data or only raw).

**Comment by jamorham** [comment]
I get similar random dips like this but don't have this alarm problem occurring.

Settings here are as follows:

Alert Volume Profile = Ascending Volume
Smart Snoozing = Yes
Smart Alerting = Yes
Start Snoozed = Yes
Notification Channels = No

**Comment by old-square-eyes** [comment]
Isn't what you just explained achieved through the hamburger menu "Snooze alerts" and simply disabling high alerts for x amount of time? Why dive deep into an alerts config just to avoid what you describe. Seems an odd little feature for one off use deep in the settings. Using the other method at least you get feedback in the form of a countdown of snoozed time remaining.

Im on a G5. 

Thanks for the help. I really appreciate it.

**Comment by old-square-eyes** [comment]
I have the same settings as you except alarm medium volume profile. Ascending has been buggy for my historically.

**Comment by tzachi-dar** [comment]
The difference from snooze all high alers, is that if I have an alert on 120, and I only snooze this it, then I can still have an alert on 150, and if that will fire, I can add more insulin.

Does the g5 have both raw and filtered data?

**Comment by old-square-eyes** [comment]
@tzachi-dar interesting you point this out (about dual high alarms for different purposes). I woke up in the middle of the night - to yet another alarm. And I wondered why it was my second (actual) low alarm, and why my warning sonar ping hadn't woken me since I sat in the semi low zone for quite a few minutes.

Now I'd either slept through the softer alarm or perhaps having two alarms quite close together causes some inability for the lower one to adhere to the snoozing first.

I guess I need to test that theory somehow. But I wasn't about to investigate size 6 font at 4 in the morning.

**Comment by old-square-eyes** [comment]
I'll add that this is still a feature request... I feel there would be much to gained for a new universal alarm type stated in OP... especially the extended semi-high configuration. You're a sleep for a long time (at least I want to be), and I wouldn't mind a quiet reminder if I've been sitting up above 6 or 7 for quite some time.

**Comment by old-square-eyes** [comment]
I have just now gotten a semi low alert described above, that I believe adhered to my pre snooze rules. So I guess I need to figure out why my actual low alert fires on a single low noisy value.

**Comment by old-square-eyes** [comment]
Would the raise every x minutes setting affect this? It is set to 1 minute (the default for creating a new alarm).

**Comment by old-square-eyes** [comment]
OK I did two things and my low alert just behaved correctly.

I widened the threshold of my pre and main low alarms (4.0 and 3.6 respectively).

Secondly I switched back to phone as collector, from my SW3 on OB1G5.

**Comment by themotoden** [comment]
I don't have 24,12,6,3 hour buttons on the screen... How can I switch them on?

**Comment by old-square-eyes** [comment]
@themotoden long press the xDrip logo on the home screen

**Comment by themotoden** [comment]
Oh..) Thank you! What other Easter eggs do we have?)))

**Comment by themotoden** [comment]
These buttons need to be added in history screen!

**Comment by old-square-eyes** [comment]
Also another thing that doesn't make sense with the current start snoozed use case... is that I might want a 30 minute snooze if I have a legitimate daytime low. Say, if I have treated with glucose.

But at night, I might not want the alarm starting snoozed for 30 minutes, if the only reason to start snoozed is to avoid a few blips of noise. To me, both thresholds should be stored and accessed  independently and my proposal covers that.

**Comment by old-square-eyes** [comment]
@jamorham what are the changes of building a test API? I'd love to be able to spoof (automate) test BG data to simulate scenarios. Could it be added as an engineering data source? It would make testing and reproducing bugs more efficient.

**Comment by ANDREAPIPPI** [comment]
**@themotoden** 24,12,6,3 hour buttons on the screen. 
In my phone (5.5" Full HD) the hour buttons look big and invasive... could them be just white without the big grey box behind them?
Or, even better, with text modified in "3 H  6 H  12 H  24 H",  in a smaller grey box?
The screen is already filled with informations, graphs and symbols, so perhaps this can reduce a bit the crowding...
Thank you.  Pippo    :-)

**Comment by themotoden** [comment]
As for me, I got answer) Another question is not mine)

**Comment by ANDREAPIPPI** [comment]
Sorry, you are right. 
I'll open a new thread for this. 
I apologize for my mistake. 
Pippo   :-(

**Comment by Navid200** [comment]
@old-square-eyes Did you ever try filtering options to reduce the impact of noise?  I'm not saying they work.  I'm just wondering if you tried them.
This is really a noise issue, that you are trying to resolve using a special alarm.

**Comment by Navid200** [comment]
@old-square-eyes 
I understand your request for an alarm that does not trigger because of a single spike.  But, creating such an alarm is going to be challenging.  But, more importantly, just because someone creates something, it doesn't mean that it will be merged.
To avoid that, we need to focus on absolute necessities first.

I have labeled this issue as postponed so that we don't forget to come back to it when other issues have been addressed.  So, for now, I am going to close it.

Thanks for the suggestion.
We can also continue to talk about it here even with the issue closed.

**Comment by old-square-eyes** [comment]
@Navid200 No, I've never had any success with smoothing in xDrip, for this issue or otherwise. Work around noisy readings just kind of overlays a second plot and glucose number from filtered seems to jump around with noise (as does trend arrow).

As for your comment about it being a noise issue... I'm not so sure. The goal is to get sleep. I think whether on Native or xDrip with some smoothing settings, sensors will always blip noise out of range at the start or near the end of the sensor's life.

The feature "start snoozed" has never worked for me as evidenced by the screen shots. I still routinely get woken by one or two points of noise.

At night, when I never have much IOB the chance of me dropping quickly is nonexistent and I'd be much more happy with a forgiving alarm that is tolerant to noise, and even compression lows to a certain point. To this day I am dogged by night time alarms and it seems like the "start snoozed" feature is broken.

**Comment by Navid200** [comment]
I hear you.  If you like to reopen this, I will not object.  

If we were to create this alarm, or add the capability to the existing alarms, this is my understanding.
We need the alarm to ignore spikes.  A spike is a sudden drop, or sudden raise, that is cancelled by the following reading.  So, in fact, it is a reading that is not very accurate, and would not happen if the sensor was brand new.
Nothing wrong with that as many of us restart sensors.
To implement this, the only way I can think of is to have a record of readings and monitor the record.  If the sudden drop continues to decrease (have to wait an additional 5 minutes to confirm), we issue the alarm because it is a real drop.  On the other hand, if the sudden drop is just a spike, we will not issue the alarm.
This means a delay (at least 5 minutes) in case of a real drop.  I can already see objections by developers saying that this will be used by someone who is not aware of the effective delay resulting in their alarms to be delayed.

Can you think of a way to implement this alarm without effectively delaying a real decrease alarm by 5 minutes?

**Comment by old-square-eyes** [comment]
@Navid200 Just one quick point... the Dex system seems to include smoothing on the TX, but also an additional layer in their app. When I tried it out recently it was quite noticeable. This of course adds a 5-10 min delay that you describe. I have seen anecdotal reports around on the web too. If on-label Dexcom users are OK with this smoothing and associated delay I think we could have it as an option in xDrip, no problems. There is already something in xDrip "Glucose number from filtered - Delayed but more stable when noisy". I'm not sure how well this works and it's not clear what other settings configure the smoothing used (There are two "Smooth sensor noise settings just above it in Display Settings" but again it's not actually clear if this is just a display thing or how it works at all really).

That said... maybe we forget the new noise tolerant alarm and look at why the existing "start snoozed" feature doesn't seem to work in some scenarios.

**Comment by Navid200** [comment]
@old-square-eyes When you tried out the Dexcom app recently, did you keep using it until the sensor became noisy as you do with xDrip.   Only then, can you make a fair comparison.

**Comment by Navid200** [comment]
@old-square-eyes xDrip has a new setting:

Settings &#8722;> xDrip+ Display Settings &#8722;> Graph Settings &#8722;> Graph Smoothing 

This setting is disabled by default.  Would you like to give it a try to see if it reduces transients and resulting unneeded alerts?

**Comment by old-square-eyes** [comment]
@Navid200 been up all night with silly alarms. I'm ready to try this. Does smoothing affect broadcast to AAPS data?

**Comment by Navid200** [comment]
@old-square-eyes I'm so sorry about that message.  Since I mentioned that, I have been corrected.  The new setting I have mentioned above only affects what is shown on screen (graph).  It has no impact on alerts.
I am sorry about my erroneous suggestion above.
