### ISSUE TITLE
Confirmation pop up before deleting an alert

### ISSUE THREAD

**Issue by Hexonium** [NightscoutFoundation/xDrip#3448]
### Discussed in https://github.com/NightscoutFoundation/xDrip/discussions/3445

<div type='discussions-op-text'>

<sup>Originally posted by **Hexonium** May  5, 2024</sup>
When modifying an alert (in the level alerts menu), it is very easy to select "remove alert" by mistake and lose the corresponding alert. This happened to me many times while I only wanted to snooze an alert (the two buttons are next to each other). Could we have a confirmation box before removing an alert?</div>

**Comment by Navid200** [comment]
Please try the xDrip release of May 12, 2024 or any one after that.  There is now a confirmation pop up.  The alert will not be deleted unless you approve it.

Thanks for reporting this.
