### ISSUE TITLE
Issue or not

### ISSUE THREAD

**Issue by Klaus3d3** [NightscoutFoundation/xDrip#346]
I resently had a bad libre sensor wich gave me constantly the very high value of 481.xxx mgdl hours after seting wich i didn't realised in the first. But i was very confused, that after the initial calibration (was at 130mgdl) all previous values were gone in the timeline. But that i saw that they were actually pushed below the zero line due to the big calibration delta.

Should'nt it be so that if you stop the old sensor and start a new one the old value should stay

**Comment by Klaus3d3** [comment]
(Sorry:-D)
...where they are? In my case the old data from the old sensor were also recalibrated with the calibration of the new sensor. 
Plugin was dactricsae.

I also have an issue with this plugin or xdrip+ itself, that i get sometimes different readings on the phone and on the watch. Phone seems to show the plugin value and the watch seems to show the xdrip calibrated value..

**Comment by Klaus3d3** [comment]
481.xxx means it was always the same raw value for 2 hours after setting. But i dont remember the xxx.

**Comment by jamorham** [comment]
Do you know which version you are running where you got this effect?

**Comment by Klaus3d3** [comment]
Latest nightly

**Comment by Klaus3d3** [comment]
Ok, lets concentrate on the issue not having the same value on phone and watch.
When i look on my timeline i have 2 curves. One is blue - must be the Plugin curve - and one is faded, wich should be the original or raw curve.
I would guess, that the raw curve has the values wich come to the watch.
If i tap " send data to watch" the values get mostly equal. Sometimes the value is equal then but not the direction.

**Comment by Navid200** [comment]
@Klaus3d3 Would you please close this issue if it has been resolved?
Otherwise, would you please clearly specify what the requested feature is?  I suggest making the description as short as possible.
Thanks

**Comment by Klaus3d3** [comment]
Closed
