### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by ANDREAPIPPI** [NightscoutFoundation/xDrip#348]
Hi.
I'm increasing the Italian translation of the English text, but it would be a very easier task if
I could do it on a text file with PC, instead of on a Smartphone.
Is this possible?
If yes, where can I find the text file?
Thank you.
Bye
Andrea    :-)

**Comment by cybernissart** [comment]
I asked also to Jon if we could work on the strings.xml file directly, instead of using the app. More convenient for massive change, and 'find' capabilities.

Andrea, you should search for 'strings-it' sentence in the repository to get it.

**Comment by ANDREAPIPPI** [comment]
Thanks a lot, I'll search for it as you suggested.
Appeciated.
Andrea   :-)

**Comment by filipedanunes** [comment]
I can help with portuguese

**Comment by themotoden** [comment]
I think developers of xDrip should let people translate by themselves on their devices (Croud-source translation, Save translation on my phone).

Anyway, I can help with Russian

**Comment by tolot27** [comment]
@filipedanunes and @ANDREAPIPPI Please join [crowdin](https://crowdin.com/project/xdrip) and suggest your translations their. Soon, I'll add dynamic screenshots to get a better context.
