### ISSUE TITLE
Add integration with Diabetes: M

### ISSUE THREAD

**Issue by uperceptron** [NightscoutFoundation/xDrip#349]
I have tried a wide variety of applications for diabetes management. Until I found this one that, to my taste, is the most complete. 

Currently it has integration with Nightscout, but this integration does not work very well and in occasions when there is no connection, it would be good to have a direct connection.

Luckily, they provide a library for Android. 

https://www.diabetes-m.com/blog/news/you-can-now-scan-and-send-data-from-freestyle-libre-or-nightscout-to-diabetesm/

https://github.com/sirmamedical/diabetes-m-addon-example

**Comment by AdrianLxM** [comment]
Possible duplicate: https://github.com/NightscoutFoundation/xDrip/issues/128

**Comment by tolot27** [comment]
Closed in favour of #128.
