### ISSUE TITLE
time base from time buttons gets lost

### ISSUE THREAD

**Issue by RaabenFuchs** [NightscoutFoundation/xDrip#350]
**hi @all!**

I'm new to android developement and really love this app, although it was a bit compicated in the beginning.
i recently found the "contributing.md" and therefore closed my first commit on jamorhams page:
[https://github.com/jamorham/xDrip-plus/pull/49]()

Can anybody tell me, if this project is synchronous to @jamorham 's?

The issue is, that the timebase of the main graph is often overwriten, maybe by
`hours = DEFAULT_CHART_HOURS;` line 190

I could resolve this, as mentioned in the pull above, but I dont think its a good way to do it with a one line change to the timebase, because the x-axis of the graph always changes on every circumstance, when the graph is updated. maybe by:
`setViewport() in java/home`

a fixed timebase on the horizontal axis should be standard, and i don't know how to do this with minor changes in "home". Im sry i had to change so much, but it was really easier for me, to rewrite the chart functions to one function that DRAWS the chart, and an UPDATE function. i didnt even really understand the need for the update function, as its easier to redraw it every time, but i left this "as it is" in my pull and everything worked really fine afterwards.

What i wanted to say is, that its easier to restructure the code, then to fix the bugs. For me it just happened that way, as i tried to understand how it works

I also would like to have a fixed ratio between horizontal and vertical axis, but maybe I'll open another issue to discuss this

Please tell me what you think and also have a look on my comment on this calibration issue (-: 
https://github.com/NightscoutFoundation/xDrip/issues/241

**Comment by jamorham** [comment]
Have you used the March 13th version? You can long press the time buttons to lock a particular time period for the graph.

**Comment by RaabenFuchs** [comment]
no sry, but i'll give it a try thanks. 
i like to try anyway cause i'm excited about the android statusbar update

would it be ok, to try to delete some of the, better all `setViewport()` calls, or try to find out if they're necessary?

i really would like to switch back to your versions, therefore i have to ask about is it somehow practicable to switch to _horizontal and vertical_ zoom. i really really need this

have a nice day

**Comment by RaabenFuchs** [comment]
ok don't know how you did this, but it seems to work. everything about the graph looks fine now
