### ISSUE TITLE
Libre 2 plus / 2+  C6 sensor not recognised. Patchinfo 0xC60931

### ISSUE THREAD

**Issue by PhilTU** [NightscoutFoundation/xDrip#3500]
> I have created oop2 version for the c6 libre2. Please note that we are using the first 3 numbers so I might need more information for this. Right now it is 0xc60930
> 
> oop2: https://drive.google.com/file/d/1z4IzWla5nor2JJbXVglWhhWXUG_nMmok/view?usp=sharing
> 
> The xdrip version is: https://drive.google.com/file/d/14NOgsjTTt0jN2TJ5yWICUZtiJc9254w4/view?usp=sharing

I was unsuccesful with a UK Libre 2plus sensor and these files. patchinfo reports as C6 09 31 @tzachi-dar   Libre 2plus is rolling out as the default L2 sensor in the UK.

_Originally posted by @PhilTU in https://github.com/NightscoutFoundation/xDrip/discussions/3439#discussioncomment-9561211_

**Comment by PhilTU** [comment]
Updated test version initially looks good and connected successfully 
![Screenshot_20240531-070700](https://github.com/NightscoutFoundation/xDrip/assets/76240903/1a872c3b-6e87-4ce4-9135-e25d9751b3d0)
![Screenshot_20240531-070501](https://github.com/NightscoutFoundation/xDrip/assets/76240903/45a0b959-3842-44db-84b3-f37dcd5849b2)

**Comment by PhilTU** [comment]
Revised test version worked corrctly for >24h with only one signal loss.

**Comment by Navid200** [comment]
Please use the xDrip release of June 11, 2024 or any one after that and if the problem persists, please tell us.
Thanks
