### ISSUE TITLE
XDrip Prefs. display wrong BT Collector name

### ISSUE THREAD

**Issue by zackallan** [NightscoutFoundation/xDrip#356]
I am using the following combination of bluetooth collector, mobile, and watch: Blucon, Nexus 6P, Ticwatch E. The xDrip preferences dialog displays "LimiTTer" as BT Collector. "Blucon" would be expected.

xDrip+ build 3f52aa5-2018.03.15

**Comment by gregorybel** [comment]
after getting first BG, Blucon is shown

**Comment by zackallan** [comment]
Thanks for your answer. So this behaviour is a result of the broken connection between the watch and Blucon as described in #304.

**Comment by zackallan** [comment]
After connecting a Miaomiao reader to the smartwatch, Xdrip Prefs. on the watch still display „LimiTTer“ as BT Collector.  Although the watch received several readings. The BT Collector name should be changed to Miaomiao or Libre Blueooth.
Similar issue: By restarting the watch collector on the phone in the status page or on the watch in the 3-dot menu a toast appears saying „LimiTTer Collector Started on Watch“. The collector name in the toast should be adjusted as well.

**Comment by Navid200** [comment]
@zackallan Would you please close this issue if the problem has been resolved?
Otherwise, would you please use the support channels to see if anyone else experiences the same issue or have possible solutions?
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks

**Comment by zackallan** [comment]
As I don't use the described setup any more I can't test if the issue has been solved.
