### ISSUE TITLE
Feature Request: Carbs on Board

### ISSUE THREAD

**Issue by ralf-ms** [NightscoutFoundation/xDrip#359]
Hi,

I find myself often switching to nightscout to look at the CoB value, which I find extremely useful and which gives me some orientation if I have to increase my IoB.
Would it be possible (and not too difficult) to add this value to xdrip?

Thanks a lot for all your work and effort!
I really rely on this app.

**Comment by mk89pwnz** [comment]
Would love to have it too :)

**Comment by Navid200** [comment]
@ralf-ms Would you please close this issue if it has already been addressed?
Otherwise, would you please update?
Thanks

**Comment by tolot27** [comment]
Where can it be enabled?
