### ISSUE TITLE
readings totally off

### ISSUE THREAD

**Issue by jo1st** [NightscoutFoundation/xDrip#360]
Replaced a sensor today ( libre ). Currently using with blucon and xdrip latest stable. Stop sensor, replace, start sensor as always. initial 2 calibrations and sebveral during the day due to the big difference in readings. All day ranges have been completely off, about 30 or 40 difference with blood testing and the libre scanner. What's going on?? I did have noticed way more problem since the latest update.

**Comment by tzachi-dar** [comment]
Are the libre scanner results good (compared to finger prickings)?
Usually this things improve after the first day.

**Comment by jo1st** [comment]
thanks for your reply. the libre scanner results seem ok enough when comparing with finger pricking. now after resetting the xdrip app completely (android data delete, strangely enough no cache data) seems a little better. I'm not sure at this point. Actually, does anyone know how to completely reset the libre scanner???

**Comment by RaabenFuchs** [comment]
there can always be differences between reader/app  at fast changing values.

you could add screenshots to your post, espacially of the calibration curve if its available. so it would be easier to locate a problem

dont think restarting the reader device will change anything though you said it works nearly correct

**Comment by jamorham** [comment]
I believe this is already being discussed in https://github.com/NightscoutFoundation/xDrip/issues/385
