### ISSUE TITLE
"Encountered backfill data we don't recognise"

### ISSUE THREAD

**Issue by jengleruk** [NightscoutFoundation/xDrip#3613]
### Discussed in https://github.com/NightscoutFoundation/xDrip/discussions/3612

<div type='discussions-op-text'>

<sup>Originally posted by **jengleruk** August  5, 2024</sup>
Hi - seeing this, and it seems the sensor (G7) has failed.

Is that message a "regular" one for a sensor failure, or have we done something wrong?

One thing that came to mind was that we left the phone in UK time even though we are now in Italy (one hour ahead).

Could that have caused an issue?

Thank you all.

![WhatsApp Image 2024-08-05 at 12 08 45_3dcd5fc2](https://github.com/user-attachments/assets/e3a36392-5ce9-4d29-a410-1f5a00e38450)
![WhatsApp Image 2024-08-05 at 12 19 20_c94498fc](https://github.com/user-attachments/assets/2b69615e-e1ab-4be2-bca1-c18584b0b954)

</div>

**Comment by jengleruk** [comment]
As I added to this in the discussion section:

We started a new sensor. The old one was 2 days old at failure.  The new one is currently warming up but it says only 8 days of life remaining rather than 10.

Aside from wondering what the cause of this is, is there anything I can do to stop it expiring in 8 days time?

Thank you

**Comment by jengleruk** [comment]
Update to above is that around 10 mins into the warm-up, time remaining has now corrected itself to 10.5 days.

**Comment by Navid200** [comment]
Did someone ask you to change this into an issue?

**Comment by Navid200** [comment]
It takes a lot of time to coordinate everything.  

When you encounter a problem, it is of course an issue for you.
But, if everyone who encounters a problem, opens an issue here, we will not be able to do anything and we also have to spend a lot of time going through them all trying to figure out which one is a real issue and which one is a user error.  

You can help us be following the procedures we have asked you to follow like the following.
**Please do not open an issue unless when you are asked by a developer**

**Comment by jengleruk** [comment]
Many apologies - I was panicking a little.  I will not raise any issues unless asked.
