### ISSUE TITLE
Behavior variance from expected in status.json in API endpoint.

### ISSUE THREAD

**Issue by raymond-richmond** [NightscoutFoundation/xDrip#363]
The endpoint seems to be returning values for bgHigh and bgLow in whatever units xDrip is set to for a preference.  The behavior in nightscout is to always present these as mg units. 

xDrip/app/src/main/java/com/eveningoutpost/dexdrip/webservices/WebServiceStatus.java

**Comment by jamorham** [comment]
yes I can correct this for you

**Comment by raymond-richmond** [comment]
I wanted to get in the habit of documenting things here for you rather than just mentioning in the chat.  hard to keep track, I imagine, of all the people vying for your input. :)
