### ISSUE TITLE
xDrip does not recognise new G7 sensor, despite correct code, and it working on Tandem T-slim pump

### ISSUE THREAD

**Issue by shrewsdog** [NightscoutFoundation/xDrip#3688]
### Discussed in https://github.com/NightscoutFoundation/xDrip/discussions/3687

<div type='discussions-op-text'>

<sup>Originally posted by **shrewsdog** September 28, 2024</sup>
Issue is xDrip not recognising a new sensor (which is working on Tandem T-Slim pump).  System Status has correct TX ID for new sensor, but transmitter days and battery voltages are clearly for the old transmitter as days are 10, and voltage a 280 and b 176. Data source is shown as G6/G7/1/1+ Transmitter, and xDrip version is dfcbe80-20240917.  Phone is Motorola Moto g(6) Play.

Catalogue of errors by me.  Had G7 on day nine.  Had been erratic, so inserted new one early.  Then realised I needed to stop the first one.  Used stop sensor which stopped both (at this point I believed I had not paired sensor 2).  Then removed the 2 sensor TXs from bluetooth list on my phone and rebooted.  Inserted sensor 3, paired it with pump which is receiving data correctly.  New TX ID on phone is correct, but the status page is showing the old day nine sensor and battery data, and the main page records sensor error and 'Ends 7.48' tomorrow.  I opted to put an incorrect TX ID in Xdrip, allowed it to try to connect, and when it failed reinputted the correct TX, but no change.

Both the expiring sensor and its replacement have been sat in microwave for hours.  Applicator code for new sensor is correct. 

It is as though the tx data for the first sensor is 'locked' on the phone.  </div>

**Comment by Navid200** [comment]
I think I asked you to bring this to GitHub.
If yes, thanks for doing it.
But, I didn't ask you to convert it to an issue.
Please let it be a discussion. If it turns out that needs to be converted to an issue, it will be.

**Comment by shrewsdog** [comment]
Apologies - I was not sure what I needed to do.

 

Screenshot attached.  After the 'notional' expiry of the original sensor
this morning, I changed the tx id, and it returned the expected mismatch
message.  I then restarted my phone, re-entered the correct code, and the
main screen reports "G7 State isn't currently known.  Next connection will
update this", but the attached shows otherwise.

**Comment by laverdanny** [comment]
Hi, I just had the same problem with a One+ sensor.
Changed sensor at oldone's grace period starting, changed sensor code in parameters but App always shows oldone end time.
Solved using fake sensor code, deleted both bluetooth connections and re-entered newone code

**Comment by laverdanny** [comment]
Can the App delete oldone bluetooth connection when sensor code changes ?

**Comment by laverdanny** [comment]
I see.
Actually, I tried to get back to the guide but haven't been able to find it, please give me the link once again, I'll store it somewhere

**Comment by Navid200** [comment]
@laverdanny Of course.  This is the guide: https://navid200.github.io/xDrip/docs/Dexcom/G7.html
