### ISSUE TITLE
Verio Flex Meter readings on Nightscout

### ISSUE THREAD

**Issue by jettechfsr** [NightscoutFoundation/xDrip#370]
I have the One Touch Verio Flex Meter syncing via wifi to Xdrip on my phone ok but reading not showing on Nightscout website I put in the REST-API Base URL but don't see the meter points on the website I see them on the Xdrip on my phone ok are these reading included. 

My Dexcom G5 is on order and wanted to get everything setup before it arrives

**Comment by jettechfsr** [comment]
Ok I ran a report and the readings are showing on the report
[Meter Readings.pdf](https://github.com/NightscoutFoundation/xDrip/files/1850632/Meter.Readings.pdf)
 so the data is getting to the database just not displaying on live feed

**Comment by jamorham** [comment]
I'm not sure if this is an issue or not? Perhaps ask Nightscout team why this would be?

**Comment by jettechfsr** [comment]
Not sure but now all is working got Dexcom setup insurance wouldn't cover my verio using Countour Next One nice compact meter and works great with xdrip and more accurate
