### ISSUE TITLE
Calibration messes up the graph

### ISSUE THREAD

**Issue by zshh** [NightscoutFoundation/xDrip#371]
Hi,

Not sure if I should post an issue for nightly builds, so delete this if its not relevant.
I've been running build from Mar 18 and it has been working fine.

Yesterday I update to build from Mar 23 and I noticed 2 things
1) Follower devices work fine
2) Main device (blukon/Libre) showed weird behaviour when starting new sensor.
    Normally it would take 3x5 minutes for initial sensor reading (prior to first calibration), but as soon as     
    I connect this one, it said it got 2 readings within seconds, which is weird?
3) The biggest issue was today (tested and confirmed at 3 occasions during the day. Every time we
     did the blood sugar test and entered the correct value for calibration, entire graph in the display 
     was updated / refreshed and it was way off. For example during the night we had couple of dips at around 4 mmol. These were clearly shown by both xdrip and Libre reader itself. However in the morning when we did the calibration, xdrip changed the entire visible curve (for entire evening that passed). On this new modified curve, it showed we where nowhere near 4 mmol at any point, but instead at about 6 at lowest.
As I said same behaviour was replicated on another two later ocassions.

So Mar 18 build OK, Mar 23 not that much. Could ofcourse be problem introduced in builds between 18th and 23rd as well.

I rolled back to Mar 18 build and now it behaves as expected.

**Comment by Klaus3d3** [comment]
i had this too, someday

**Comment by Navid200** [comment]
@zshh Would you please close this issue?
