### ISSUE TITLE
How do i change sensor correctly?

### ISSUE THREAD

**Issue by lowskillzgd** [NightscoutFoundation/xDrip#373]
When i change my Libre sensor, my xdrip is not reading the sensor. How do i do it properly?

**Comment by ChristinaWi** [comment]
We start a new sensor with the libre device and afterwards with the libre app on the phone. I am not sure that the start with the app is necessary, but with this procedure we have all options: libre device, app and xDrip.

**Comment by RaabenFuchs** [comment]
yes, thats right. plus: stop the old sensor in xdrip-menu of course before you scan the new one to go safe that nothings messed up

**Comment by Navid200** [comment]
@lowskillzgd Would you please close this issue?

For help with settings and how to guides, please post on facebook:
https://www.facebook.com/groups/xDripG5
