### ISSUE TITLE
Clibration, another one (maybe an issue)

### ISSUE THREAD

**Issue by RaabenF** [NightscoutFoundation/xDrip#377]
This is just for your information, this sensor seemed to be dying anyway. No prob for me:

At day 11 libre sensor (with blureader) was noisy and falling, due to an infection,

now i fingerpricked two times, decided to disable both in the calibration table.
Later i reactivated both pricks by clicking on it in the graph, in following order:

-6.57
-12.10
-6.57
-6.57

You see the result in the pics. I taped it three times cause it doesnt seem to wrk. Funnyly it changed its raw value as you can see. (It also changed its time first!)

If you want you can also give me a hint where to search for this bug

![screenshot_20180330-153347](https://user-images.githubusercontent.com/36605089/38140021-4fb427b6-3432-11e8-8746-98c9c322a68f.png)
![screenshot_20180330-152632](https://user-images.githubusercontent.com/36605089/38140022-5043c74a-3432-11e8-847f-e4cbe158e662.png)

**Comment by Navid200** [comment]
@RaabenF Thanks for sharing.
Would you please close this issue?
You can also share experience on the xDrip facebook group.
https://www.facebook.com/groups/xDripG5
Thanks
