### ISSUE TITLE
Hour buttons look big and invasive

### ISSUE THREAD

**Issue by ANDREAPIPPI** [NightscoutFoundation/xDrip#383]
Hi. In my 5.5" Full HD phone the hour buttons look big and invasive... could them be just white without the big grey box behind them?
Or, even better, with text modified in "24 H    12 H   6 H   3 H ", eventually in a smaller darker grey box?
The screen is already filled with informations, graphs and symbols, so perhaps this can reduce a bit the crowding...

**As it is now:**
![before](https://user-images.githubusercontent.com/32884006/38447590-92dd0090-39fe-11e8-9998-799cd576264c.jpg)

**As I propose:**
![after](https://user-images.githubusercontent.com/32884006/38447594-970169b8-39fe-11e8-8c8d-a37c860fafb6.jpg)

Thank you. Pippo :-)

**Comment by themotoden** [comment]
Maybe vertical? Under treatments and looks the same?

**Comment by ANDREAPIPPI** [comment]
It looks OK to me, hope for other people too...
Bye. Pippo  :-)

**Comment by AdrianLxM** [comment]
@ANDREAPIPPI is this a mockup or did you do this in code?

**Comment by ANDREAPIPPI** [comment]
Hi. Yes, it's a PhotoShop mockup, I'm unable to work in code.
Bye.
Pippo    :-)

**Comment by AdrianLxM** [comment]
@ANDREAPIPPI can you compile your own xDrip from sourcecode?

The text on the button depens on one line in strings.xml (./app/src/main/res/values/strings.xml)
`<string name="hour_format">%s Hour</string>`

You could change it to:
`<string name="hour_format">%s H</string>`

... and see how it looks.

cheers,
Adrian

**Comment by ANDREAPIPPI** [comment]
@AdrianLxM  Sorry Adrian, as I told I'm unable to do anything with code. Sorry again      :-(

**Comment by jamorham** [comment]
Please try the Aug 19th Nightly. I believe this problem should be resolved.

**Comment by ANDREAPIPPI** [comment]
Hi jamorham. My previous installed version was the xDrip-plus-20180530-f20d8da, months ago, and with the Aug 19th Nightly the only difference I see is the new graphical trend arrow, all other things are as before, both the battery bridge white contour on black, and the big hour buttons below (BTW, why the 3Hours button has a differnt background of the other three?).
Bye and thank you for all you are doing.
Pippo    :-)

![pippo-2](https://user-images.githubusercontent.com/32884006/44310694-d8c83e80-a3da-11e8-9138-602f85735261.jpg)

**Comment by ANDREAPIPPI** [comment]
Sorry, I have not remembered thet the 3 Hours buttton has a different background because I locked it as default.
Pippo    :-(
