### ISSUE TITLE
Apparent calibration or data processing issue reported (with Libre/Blucon)

### ISSUE THREAD

**Issue by jo1st** [NightscoutFoundation/xDrip#385]
I've been using xdrip for awhile and honestly after you continuously update it 
 by doing calibrations work with that it does a pretty good job eventually the readings received are very very close to what I get with the finger testing. the problem that I notice is that sometimes the app seems to be getting into a some kind of a dormant state specially when we are on the lower level today for example I felt very sick and kind of week like I was down in the 50s and I know because I've been a diabetic for very long time and then xdrip was just telling me that I was 77 so I decided to check with my libre sensor and it was reporting 53 then I used the same sensor but this time I did a blood test and it actually give me 33 and I tried to add the 53 to the calibrations of the app and it accepted it and adjusted itself a little bit but we're talking about 20 difference which on the lower side it's very dangerous but then when I tried to enter 33 as calibration and xdrip told me that it was impossible for me to enter because he was out of range. I'm sorry if I'm being bragging but that is a problem on the lower side, some times xdrip sticks to a level and does not moves from there. I would reallyy appreciate the author to step in. Thanks

**Comment by ANDREAPIPPI** [comment]
Hi. Your  calibrated values are distributed along all the scale (i.e. LOWs, NORMALs and HIGHs)?
I have seen something this kind, but mainly when calibrations were mostly on the NORMAL-HIGH range. 
So I tried this way: after one week I reset all calibrations (Stop Sensor> Don't Stop, Just Reset all Calibrations), and it looks working better. 
Anyway I don't know how XDrip+ algorithm works, so may be my way is pure nonsense...
Pippo   :-)

**Comment by jo1st** [comment]
I'm so sorry but I really don't understand your question I apologize. I
just would like the author to actually look into this because eventually
every time we go into the low values it's like the app is refusing to take
calibrations in consideration

**Comment by jo1st** [comment]
I would have preferred your comments to be related to the tech part of my
question and not to fall in some kind of paternal sermon.

Being diabetic for over 20 years I know exactly what I'm supposed to do
when I have a low special in the 33 range. I didn't think that I was
supposed to write in this board that I had some sugar to take care of my
low levels.  my question was why the app does not move from where it is and
stays in the 70s when actually there is such a big difference with what the
actual values are. expecially considering the whole time readings are right
on.

I'm not here to argue so please refrain from debating my reply and let's
stick to useful troubleshooting info.. Thanks

**Comment by AdrianLxM** [comment]
@jo1st please read the post again. There are 4 "technical" reasons for the app to not calibrate on those values. And then there is a suggestion how to calibrate (troubleshooting).

If you have eaten sugar you should not calibrate as you need stable values to calibrate.

**Comment by jo1st** [comment]
My question was not about calibrating. I apologize if my post was
misleading. My question is to try to find out if there is any kind of bug
that prevents the app from displaying real values when we reach low levels.
This question was not about calibration. So please let it go man.

**Comment by AdrianLxM** [comment]
If you want me to help could you then please rephrase what you would consider a bug.

**Comment by AdrianLxM** [comment]
It most likely is a problem with calibration that the slope does not match. It would help if you could post a screenshot of the calibration graph.
The Libre sensor has the added difficulty that it autocalibrates itself rendering the slope determined by xDrip outdated.

**Comment by jo1st** [comment]
I don't really use the Libre reader to calibrate. I actually use the one
touch Ultra Vue mostly.

Attached is the calibration

I'm really sorry I'm not being clear enough what I'm trying to say is that
xdrip it's usually very precise just a few units away from the actual blood
test but what I noticed is that when sometimes we go towards low levels
there is some kind of stalling, the levels keep dropping in real time but
eventually xdrip still reports a straight line on levels like 70 71 74 73
but then eventually the levels have dropped a lot in reality in the 50s.

**Comment by themotoden** [comment]
Can you post your calibration graph please?

**Comment by jo1st** [comment]
well I did. you can't see it? I attached again to this reply

**Comment by jo1st** [comment]
attached now again 
![screenshot_20180409-223031](https://user-images.githubusercontent.com/36887391/38541377-dd0b8230-3cd9-11e8-8844-f6b9e4ff3c79.png)
, unfortunately email replying with file doesn't work.

**Comment by themotoden** [comment]
Hm... Good graph... Well, I don't know what is a problem, sorry

**Comment by jo1st** [comment]
To be honest with you guys I'm a little bit disappointed that the author of the app didn't even take the time to comment on what's happening here. Today actually t happen again. the levels where for about 2-3 hours reported in the 100s by the app but then eventually I start feeling kind of weak and I knew that something was not right so I went on and actually the app for ask me to do one of the schedule every 12 hours calibrations so I did that and actually my levels were 60 that means there were 40 units difference between what the app was saying and the actual real levels. Please be aware that actually the app is doing usually well. Always within 2 3 4 5 units maximum 10 units away from the blood test. there's the problem indeed. From my observation, if the app it's reporting a steady level at any level but for several hours it's like the app is not reacting anymore to any inputs from the sensor so like today for several hours my levels were in the hundreds and the app stay there but eventually the level start dropping at one point after two two three hours and the app does not realize that. 
![screenshot_20180416-213547](https://user-images.githubusercontent.com/36887391/38812915-8d96a010-41c8-11e8-9fce-35b8e97b4dfc.png)

**Comment by jamorham** [comment]
In the standard configuration the glucose value is going to be related in a linear way to the raw sensor value received. If xDrip is showing a flat graph but blood glucose is dropping significantly it implies that the raw sensor value is not matching that.

With Libre temperature is also a factor which is significant but not yet included in the calibration algorithm. Could there be anything unusual with the temperature of the sensor occurring? I assume it is a european sensor and is being worn on the back of the arm.

**Comment by gregorybel** [comment]
your comments are really disappointing me. xdrip is free software made by developers in their free time for free.

I see 3 possibilities if you are unhappy:
1) use CGM manufacturer original app
2) learn to code and fix issues by yourself
3) do great and fair errors reports that we are happy to help you

from what I see you are calibrating wrong.
if you think xdrip sleeps then make sure Xdrip is free from battery optimization.
but if you still get values  don't think that it's the issue.

otherwise you could talk to your doc about how to correctly use CGM. The measured values are til 20 minutes lates so if you drop fast for sure CGM values are not same as finger pricks. you need to anticipate then. You could activate BG predictions.

**Comment by jo1st** [comment]
what exactly is your problem man? who is complaining about anything?
....damn, I apologize for offending your ego.

I do believe I did report correctly and fairly, the only disappointment was
when the thread was open for probably a week or so, many other people
already replied but Jon didn't yet. I know he's very busy helping us and
actually sometimes he contacted me directly, just tried to get his
attention on this case.

I'm a reporting a possible bug and that's why I was asking for the author
to step in and comment/correct me, advise, like he actually did a post or 2
above.

bg predictions are enabled
Xdrip is free from battery optimization.

can you please explain how I'm calibrating wrong? I'm doing a calibration
every 12 hours with the set alarm

**Comment by AdrianLxM** [comment]
The author of that algorithm no longer is working on xDrip. You might have luck with the xDrip G5 group on Facebook when tagging her.
Here you have to take chances with me that has been in the project longest and co-authored part of the basic algorithm you are talking about, Grégory who did author the blucon/libre integration and Jon who does a really really great job maintaining and developing the app.

**Comment by jo1st** [comment]
I totally understand. I thought Jon was the author of the app. my
apologies.

**Comment by themotoden** [comment]
maybe some problem with transmitter? Did you try another one?

**Comment by jo1st** [comment]
I guess I'm the only one experiencing this issue, so I apologize for
bringing that up, I thought and I still do think there is some happening.
It happens only in the morning after hours and hours of stable levels
during sleep (long acting insulin taken)

Thanks Jon for your explanation. Any suggestions to try with setting and
........???

**Comment by RaabenFuchs** [comment]
Hi jo,
first, i didnt wanted to reply to your question, cause so many developers already replied.

but now i see, as most times, the answer could be so simple!

in your last answer you state out, "It happens only in the morning" but in your screenshot it appears to be 22:00 evening ;)

I'm relative new to type 1 one, and so far nearlly a "native" to the libre, as i got it after remission, so please let me tell you, as someone mentioned before, this is really a cgm problem in general:
-you're experiencing a slow and light bg drain/drop
-but youre fat shugar doesnt respond to that due youre body counter acts in some way

maybe you really should consult your doctor to avoid that
AND REALLY DONT CALIBRATE THAT! if you do so, you even change true values

**Comment by RaabenFuchs** [comment]
Hi again,
this is another topic, but it fits here well, because first i thought i have the same problem:

I want to show you my actual calib curve, too. I dont know if its new, due to internal calib changes of the libre, but,

could it be, that this has not appeared before? 
The raws are that high, that i got LOW after waking up and scanning. Despite i felt really great!
I will try to code some non linear algorithm. But this is not possible with existing environment, right?

I dont want to do this, i know all of you could do better!

![screenshot_20180429-094944](https://user-images.githubusercontent.com/36605089/39404510-c7fd29e2-4b94-11e8-8c82-822f1cd04893.png)

**Comment by Navid200** [comment]
@jo1st Would you please close this issue considering it has not received any new posts for more than 2 years?
Even when closed, it can still be accessed.  
Thanks
