### ISSUE TITLE
[FEATURE REQUEST] Reset G5 clock timer

### ISSUE THREAD

**Issue by Kryptonit3** [NightscoutFoundation/xDrip#386]
Refer to following PR for iOS Loop

https://github.com/LoopKit/xDripG5/pull/84

**Comment by jamorham** [comment]
Try the 9th April nightly:
* Enable engineering mode (see wiki)
* Set up as normal
* Enable OB1 collector in G5 debug settings
* Use the voice command `hard reset transmitter` 
* Command will be processed the next time data would be read 
* Observe the `System Status` tab for what is happening
