### ISSUE TITLE
Data from calibration plugin not uploaded to nightscout.

### ISSUE THREAD

**Issue by Klaus3d3** [NightscoutFoundation/xDrip#391]
Hi there,

i'm still working on the interface for my amazfit smartwatch and while this testings i found out, that i get the corrected curve and the notification from the selected calibration plugin, but in the uploaded nightscout data and in the Glucose Data table i find the values from xdrip, wich are different.
latest nightly

**Comment by gregorybel** [comment]
fixed in https://github.com/NightscoutFoundation/xDrip/commit/1d7a28be51c56eddc1c9aa1effdf77a731185f72

**Comment by tolot27** [comment]
@Klaus3d3 Please can you confirm that it is working now and close the issue?
