### ISSUE TITLE
Blucon fails to reconnect

### ISSUE THREAD

**Issue by zackallan** [NightscoutFoundation/xDrip#392]
With Apr 7th 2018 nightly or newer Blucon fails to reconnect after phone was out of range. Restarting Blucon or restarting collector on phone does not help. Only way to reconnect is tapping "Forget device" and running a bluetooth scan.

Phone: Nexus 6P
OS phone: Android 8.1.0

**Comment by Son1k02** [comment]
I've run into something extremely similar, but have found that using the April 9th nightly, & disabling Bluetooth bonding (clicking on it in the 2nd page system status) that the disconnects go away. I was having good luck with the latest nightly tonight until an hour ago when it decided to start with the disconnect. Have read on fb alot of people finding the same issue, hopefully someone can identify the issue soon!

**Comment by zshh** [comment]
Same here, rolled back to one of the March builds....

ps. Is anyone really reading/acting on the things posted here? Looks like noone is tagging and assigning issues

**Comment by ralf-ms** [comment]
I had to do the same:
rolled back to the March 30th version (...5b7b3c7): no bluetooth problems with this release.

**Comment by ralf-ms** [comment]
updated to the latest nightly (April 17th) and deactivated "allow blucon unbonding".
Will keep you informed if this has solved the issue.

**Comment by jamorham** [comment]
Please also make sure to untick the following item if you are having any problems with reconnections:

`Settings` -> `Less Common Settings` -> `Bluetooth Settings` -> `Close GATT on BLE Disconnection` -> `Unchecked`

**Comment by gregorybel** [comment]
17th April is running a lot better. 
unchecked automatic unbonding, close GATT
enabled Agressive service Restart

otherwise see https://github.com/gregorybel/xDrip-plus/wiki/How-to-use-Blukon-with-xdrip

**Comment by ralf-ms** [comment]
so far no more problem with deactivated settings above ("allow blucon unbonding", "close GATT on BLE Disconnection").
I'm happy again :-)

**Comment by zackallan** [comment]
Thanks for your advice. With the latest nightly and the recommended settings the connection between Blucon and Phone is stable. It is working much better than before.
But unfortunately another problem now occurs: Sometimes the phone receives no readings although the status page reports that Blucon is connected. Restarting Blucon manually helps. The log message lists: DexCollectionService – Got null pointer trying to set CCCD descriptor

**Comment by zackallan** [comment]
The reconnection issue seems to be solved. But I will start a new bug report regarding the above mentioned problem.
