### ISSUE TITLE
Race condition for "Disable Forced Wear on Missed Readings"

### ISSUE THREAD

**Issue by old-square-eyes** [NightscoutFoundation/xDrip#396]
If you are force collecting via Wear, and switch off your phone:

When you turn it on again, if the time delta is > than your `Disable Forced Wear on Missed Readings`, `Minutes since last Reading` value, the phone will disable forced Wear before Wear can sync and backfill BG data collected while the phone was off.

I experience this frequently as I turn off my phone most days at some point.

**Comment by Antonio2001** [comment]
Good evening. I'm sorry to post here, I don't know any other way to contact you...
I've read one of your post saying that about the xbridge2 build: "Even on the new circuit, you can disable the sleep cycle if you prefer through a serial toggle" How do you do that?
Thank you for your help and my appologies again for the off topic.
Regards

**Comment by old-square-eyes** [comment]
Hi @Antonio Press B with a USB serial connection open to the Wixel.

Last page from the doc https://github.com/jstevensog/wixel-sdk/blob/master/apps/xBridge2/xBridge2.pdf

**Comment by Antonio2001** [comment]
Thank you so much, old-square-eyes, maybe this way I'll avoid missing packets.
Kind regards

**Comment by Navid200** [comment]
@old-square-eyes Is this still happening with the recent releases of xDrip?

**Comment by old-square-eyes** [comment]
@Navid200 No doesn't seem to happen any more. However, often the phone struggles to pick up the missed readings stored in the Wear DB for several cycles (or at all) without rebooting the phone and watch. During this time it can pass the threshold for "Disable Forced" and then the phone tries to take over. After that the readings on the watch seem orphaned. The phone then grabs the history from the TX (if you're using Native mode).

Sometimes it syncs after a reading or two though and it's fine.

**Comment by Navid200** [comment]
> @Navid200 No doesn't seem to happen any more. 

So, do you want to edit the title to reflect what the current problem is?
Or, do you want to close the issue if you believe this issue does not happen anymore?

**Comment by old-square-eyes** [comment]
Will close and create a new issue when I get some video of it happening.
