### ISSUE TITLE
Feature Request:  Implement RACP for G5 data source

### ISSUE THREAD

**Issue by Rezer** [NightscoutFoundation/xDrip#399]
I just recently switched to xDrip from the Dexcom G5 app, and the feature I find myself missing the most is the downloading of stored records from the sensor after being out of range for a period of time.  My understanding is that the app as it is today is designed to be entirely passive and pick up transmissions from the sensor every 5 minutes, so I imagine there may be significant changes required to get this working.  Would it be feasible to implement the two way communications necessary to request the stored records that were missed when a sensor comes back in range, or is this just not going to happen?

**Comment by jamorham** [comment]
Try this:

https://github.com/NightscoutFoundation/xDrip/wiki/Guide-for-using-OB1-G5-Internal-Algorithm-Feature

**Comment by jamorham** [comment]
back-filling is implemented in the nightlies.
