### ISSUE TITLE
Broadcasting to AAPS problem

### ISSUE THREAD

**Issue by infoneo** [NightscoutFoundation/xDrip#401]
I have found serious problem with brodcasting bg data from xdrip+ to AAPS – I’m not sure if it’s a AAPS or xdrip+ problem.

Since 4 days I’m looping with xDrip+ with G5 internal algo (hard reset has been done 4 days ago). BTW my transmitter batteries was ending. Today morning G5 transmitter went to state „stopped”. It was impossible to restart transmitter – „g5 start failed – session start failed clock is not sychronized”. Ife checked transmitter also with G5 Dexcom app it said “Transmitter error – you have to pair new transmitter” (it is translation). I’m almost sure, that the problems with transmitter was caused by low batteries (voltage A and B was about 280).

Due to above mentioned problems, I changed back to old, xdrip collection method and calibration algo.

Transmitted started to work, but with many signal loss – there was many BG reading gaps.

But the main problem I saw was, that in spite of BG gaps in xDrip, AAPS keeps receiving/replicating last good BG reading every 5 minutes. Please see the screenshots – “flat periods” are gaps filled by AAPS.

„BG data table” in xdrip since 13:17 is empty, xdrip logs constantly say ”filtered data is exactly double raw – this is completely wrong – dead transmitter? – blocking glucose calculation”. AAPS still “receiving” 165… since 13:17. Data send form xDrip do NS is also ok – just AAPS replicates last reading..

AAPS build: 267aca44-2018.04.20, xdrip nightly build: a5307da-2018.04.18

![scrrenshot1](https://preview.ibb.co/fksiBn/Screenshot_20180420_134900.png)
![scrrenshot2](https://preview.ibb.co/dBiZHS/Screenshot_20180420_134908.png)

**Comment by tolot27** [comment]
@infoneo Does this problem still occur?
