### ISSUE TITLE
Using OB1 and G5 internal algorithm, wear watchface always shows flat direction arrow

### ISSUE THREAD

**Issue by jwoglom** [NightscoutFoundation/xDrip#402]
![image](https://user-images.githubusercontent.com/192620/39091804-d2293ae2-45cb-11e8-844f-0f8ccd83030e.png)
![image](https://user-images.githubusercontent.com/192620/39091809-ecfc541c-45cb-11e8-92bb-b1fc08b19028.png)

**Comment by jwoglom** [comment]
The direction arrow also does not appear as though it is being sent to Nightscout, and exhibits the same behavior as the watchface. The wear complication also appears to have broken entirely (appears as though it's not getting new data at all, and shows an "old 2h" message, for instance).

This functionality is clearly a huge step forward, by the way, and I'm not trying to be nitpicky: I just immediately noticed this when toggling the option on with my current setup.

**Comment by jamorham** [comment]
Is this resolved in the current nightly?

**Comment by jwoglom** [comment]
Yes -- complication is working as well. Thanks!
