### ISSUE TITLE
Calibration rejected: Unknown code: 12

### ISSUE THREAD

**Issue by jwoglom** [NightscoutFoundation/xDrip#405]
Possibly related to #404. Using g5 native mode, all calibrations are rejected with this error even after a "G5 calibration requested."

**Comment by jamorham** [comment]
Could this be related to sensor noise? How old is the sensor?

**Comment by jwoglom** [comment]
I don't think it's related to sensor noise; the sensor was 8 days old, and had just been restarted the day before at the 7-day mark. Using an official receiver device, calibrations are accepted fine.

**Comment by triplem** [comment]
I had this issue even on the first calibration of the sensor.

**Comment by triplem** [comment]
Had this today again. No noise shown, "needs calibration" in system Status. Same unknown Code on calibration.

**Comment by jamorham** [comment]
I believe this should be resolved now.

**Comment by Navid200** [comment]
@jwoglom Would you please close this issue if it has been resolved?
Thanks
