### ISSUE TITLE
Medtrum CGM

### ISSUE THREAD

**Issue by kimbersdiabetic** [NightscoutFoundation/xDrip#408]
Dear Sir/Madam,

I have been using the Xdrip through Blucon/Ambrosia which has been great. I am of today picking up a new CGM through a Company called Medtrum UK

http://www.medtrum.com/S6.html

Can you confirm please if I can use this new device through Xdrip?

Many thanks for your help.

**Comment by jamorham** [comment]
It doesn't currently work with xDrip. To make it work we would basically need to have physical access to a device to reliably implement support for it. Is the unit you are receiving promotional? Do you think the manufacturer would be interested in xDrip being able to support it?

**Comment by kimbersdiabetic** [comment]
Hi I have bought 4 Sensors and a Transmitter for £225 the sensor lasts for 7 days and the transmitter is rechargeable bud, The reports and layout is very simuliar to Bluecon it provides a service but not as in depth as the xdrip provides, My contact there is a lady called Yadi and she is the Marketing and Sales Manager her email address is gaoyd@medtrum.com
It would be great if you could contact them as the product that you have is a great piece of kit, Please let me know how you get on and i will also try and contact her. I know that the Company are trying to get a CE mark for there next project which is a CGM that will last for 14 days. Hope this helps Bud. Paul

**Comment by kimbersdiabetic** [comment]
Hi have you spoken to the guy's from Medtrum?

**Comment by dimis28** [comment]
Kimber can you post a review of your experience at FB group named Trials for diabetes please?

**Comment by jamorham** [comment]
@kimbersdiabetic I sent them an email but haven't heard anything. Is it the S6 or A6 unit?

**Comment by kimbersdiabetic** [comment]
[Medtrum A6.pdf](https://github.com/NightscoutFoundation/xDrip/files/1964532/Medtrum.A6.pdf)

Its the A6 

[

**Comment by kimbersdiabetic** [comment]
Hi Jamorham have you had any luck yet please with the guys at Medtrum.

On another topic what is the difference between Xdrip+ on my Android phone through Ambrosia and Xdrip+ Nightscout? Many thanks.

**Comment by jamorham** [comment]
@kimbersdiabetic I haven't had any response to my April 30th email. Perhaps as a customer you could convince them to engage with me. I'm sure it is in their interest to do so but they might see things differently of course...

**Comment by kimbersdiabetic** [comment]
Leave it with me Bud, Whats the difference between Xdrip+ on my Android phone through Ambrosia and Xdrip+ Nightscout? Many thanks.

**Comment by jamorham** [comment]
@kimbersdiabetic I don't really understand your last question. Ambrosia make the blucon device which can be used as a collector with Libre. xDrip+ is published by the Nightscout foundation but also "Nightscout" would often be used to refer to the Nightscout web service which xDrip+ can upload and download data from.

**Comment by kimbersdiabetic** [comment]
Hi Jamorham,

I have been in contact with the Guy's from Medtrum they are interested in engaging with Xdrip, Have you any figures of how many people are using Xdrip world wide?

**Comment by kimbersdiabetic** [comment]
Hi Jamorham,

I have been in contact with the Guy's from Medtrum they are interested in engaging with Xdrip, Have you any figures of how many people are using Xdrip world wide?

**Comment by jamorham** [comment]
At least 8000 people use xDrip+ every day and that number is steadily rising.

**Comment by kimbersdiabetic** [comment]
Many thanks is there any other way of contacting you Bud?, I have details of who to contact at Medtrum in Shanghai and Watford they may be interested in engaging with Xdrip but I dont want to give info out on the public domain. Hope this helps.

**Comment by jamorham** [comment]
Yes just email me jamorham at gmail

**Comment by kimbersdiabetic** [comment]
I have just emailed you Bud

**Comment by jamorham** [comment]
closing due to replacement ticket
