### ISSUE TITLE
Request related to G5 native calibration.

### ISSUE THREAD

**Issue by PedanticAvenger** [NightscoutFoundation/xDrip#410]
when native G5 calibration is selected, I believe it would be useful to have a warning show on the main screen that the sensor is about to expire.  Say starting 6 hours before that occurs.  Currently when 7 days passes xDrip simply errors until you restart or the auto-restart may kick in at an inappropriate time.

**Comment by Navid200** [comment]
@PedanticAvenger Would you please close this issue?
You can place a note on the main screen showing when the sensor will expire.
If you need to know how, please respond.
If that is not sufficient, please explain.
Thanks

**Comment by PedanticAvenger** [comment]
Issue was addressed, forgot i had this issue opened.
Closure fine.
