### ISSUE TITLE
Need Help compiling the app

### ISSUE THREAD

**Issue by Moshikol** [NightscoutFoundation/xDrip#411]
I have just cloned the repo on the master branch  and i cant compile the app on my phone,
I got an error : **Failed to find byte code for com/squareup/wire/ProtoEnum**.
My phone is Samsung Galaxy S8 with android 8.0.1
I tried to clean project and rebuild with no success.
I tried also refresh all the maven modules and still no success.

thanks in advance.

**Comment by tzachi-dar** [comment]
What version of android studio are you using?

According to https://stackoverflow.com/questions/49525708/ioexception-failed-to-find-byte-code-when-upgrade-to-android-studio-3-1 you have to use another version of android studio.

Maybe try building it from  command line using 
graddlew assembledebug

**Comment by Moshikol** [comment]
@tzachi-dar Great it worked thank you very much
