### ISSUE TITLE
Huawei Watch 2 as G5 collector

### ISSUE THREAD

**Issue by QuadAlpha** [NightscoutFoundation/xDrip#417]
Hello,

Recently discovered XDrip+ and the phone sync to Android Wear works great!  I can't however get my Huawei Watch 2 to work as a standalone collector.  I saw that there is a patch for the original Huawei Watch, but not this one (which is a very popular model); my build number is OWD.180215.018

Is there any way to get this to work so that the watch can be used independantly as a collector or when the phone is off / out of range?  I've tried most settings with no luck.

**Comment by jamorham** [comment]
related https://github.com/NightscoutFoundation/xDrip/issues/374
