### ISSUE TITLE
Feature Request: Add countdown timer in seconds in status

### ISSUE THREAD

**Issue by old-square-eyes** [NightscoutFoundation/xDrip#421]
When testing, one gazes often at the 5 minute life cycle of a BG capture. Waiting for that 4 minute to tick over to 5 can take an eternity. Especially if up in the middle of the night waiting for multiple readings, struggling with issues or waiting for ideal calibration conditions.

A minute can seem like an eternity when staring at a status screen at 4am.

Propose: Status page & home page (in engineering mode or display settings), counts down in seconds for collector wake up, in the last 30 seconds. Option also to add an audible beep in the process for testing various things so the phone doesn't have to be watched as closely when observing function.

**Comment by gitanO0** [comment]
@old-square-eyes Would this be similar to this open request?  https://github.com/NightscoutFoundation/xDrip/issues/79

**Comment by Didsonthego** [comment]
why does it keep losing connections and after a hour or having to reboot re install it starts to work again?
yes 5 mins is also a long time. can anyone also help me setup to this software too?

**Comment by old-square-eyes** [comment]
@gitanO0 yes the same :) I'll close this.
