### ISSUE TITLE
Sony Smartwatch 3 not working as a collector

### ISSUE THREAD

**Issue by dideldum** [NightscoutFoundation/xDrip#422]
Sony Smartwatch 3 was used as a transmitter previously (rooted, old firmware, NFC patch).

Now the Sony firmware was updated using the Sony software to M1D64T (unrooted) again.

The Sony was paired with an Elephone P8000 running xDrip+ (2018-03-15 and later 2018-05-02). Android Wear / Wear OS is the current one from the Google Play Store.

Even though Wear-Collector-Service and Force-Collector is enabled on the watch and the phone, the watch does not collect values from a Blucon. The Blucon is working well connected to the phone.

In the xDrip+ status page on the phone it is shown, that the phone service is stopped because auf the watch. The watch is shown as connected to the Blucon, counts from 5 down to 0, but doesn't get values.
On the watch in the Bluetooth settings, despite the status "connected" in xDrip+, the Blucon is shown as "disconnected".

The xDrip+ watchface is filled with data, as long as the phone is connected to the Blucon, the SSW3 just doesn't take over the collection.

![image](https://user-images.githubusercontent.com/1267238/39671929-a3b4e358-5121-11e8-9693-9c04364bb863.png)
![image](https://user-images.githubusercontent.com/1267238/39671931-a9ee5fd8-5121-11e8-90b9-63ed07e054a4.png)
![image](https://user-images.githubusercontent.com/1267238/39671934-aee0b11c-5121-11e8-9a4b-2f2bbf4e4e03.png)
![image](https://user-images.githubusercontent.com/1267238/39671936-b57bbe72-5121-11e8-8e7b-ad6d86890ece.png)

**Comment by jamorham** [comment]
Did the SW3 previously work as a blucon collector for you?

**Comment by dideldum** [comment]
It was not used as a collector before. When I bought it, I configured it immediately as a transmitter. When changing to the Blucon, the SSW3 was laying around some months. Now I wanted to use it as a collector (because I leave my collector smartphone laying around all the time).
So I updated the firmware to the regular current Sony firmware using the Sony Software, installed the current Wear OS on my smartphone and connected the watch with it. So it should be in a regular factory state.
But it was the first time now, that I tried to use it as a collector.

**Comment by andreashelgesson** [comment]
Believe we need Android wear 2 in watches for collectorfunction, sw3 is still i. 1.5 and regarding to what I've read, it will not upgrade to 2.0. Hope I'm wrong....

**Comment by jamorham** [comment]
@andreashelgesson wear 2.0 is not required to act as a collector. The SW3 is one of the best smart watches to act as a collector.

**Comment by dideldum** [comment]
Strange, I tried xDrip+ version 2018-03-12, and this time the SSW3 connected to the Blucon and worked as a collector.
So staying at the moment with 2018-03-12 I can close the issue. Will try newer versions later.
