### ISSUE TITLE
Blucon Values over 400 error

### ISSUE THREAD

**Issue by alwayssimifuzi** [NightscoutFoundation/xDrip#423]
Hey everyone,
I have a problem with xdrip + Blucon, if my values are over 400 (yeah not so good) the xdrip app shows completely bad values.
Example: BG is 475, xdrip shows something between 50 and 100 mg/dl.
The error occures everytime and not just sometimes.
Do you know how to fix this?
I will share some Screenshots if the problem shows again. 
Thank you very much for helping me out!

**Comment by alwayssimifuzi** [comment]
![image](https://user-images.githubusercontent.com/34485830/39672676-0b8986de-512f-11e8-8ace-c79be7079ab4.png)

Here a screenshot from my nightscout page, the Values are bad for 20 minutes, then they're back.

**Comment by alwayssimifuzi** [comment]
![image](https://user-images.githubusercontent.com/34485830/39672680-3c8896bc-512f-11e8-86cb-9c3905705521.png)

Here you can see a problem from friday to saturday, sugar dropped fromm very hight to normal and where on this level till saturday morning. Then i recognized the issue and stopped xdrip.

**Comment by alwayssimifuzi** [comment]
If you need more information just let me know :)

**Comment by tzachi-dar** [comment]
You are probably using an old version.
Please try with the latest nightly, it should be solved there.

**Comment by alwayssimifuzi** [comment]
Okay I installed the latest nightly. Thank you!

**Comment by gregorybel** [comment]
but is the 13th bit option activated as default?

**Comment by alwayssimifuzi** [comment]
13th bit option?
