### ISSUE TITLE
Snooze dialog not appearing in xDrip after selecting notification in drawer

### ISSUE THREAD

**Issue by Webifi** [NightscoutFoundation/xDrip#424]
Description of Issue:
If xDrip was the previously active app, after selecting an xDrip high/low notification in Android's notification drawer, xDrip opens but only to the Home Screen, not the snooze dialog.   I have to hit "Back" while xDrip is open, then re-select the notification.  Now xDrip opens the snooze dialog.

Expected result:
xDrip should open Snooze dialog when selecting a notification, no matter its previous state.

xDrip version:
ea6c855-2018.05.04  (Nightly)
(Using Dexcom G5)

Device:
Android 8.1.0 (Nexus 5X)

**Comment by Navid200** [comment]
@Webifi After you open the Android notification, can you not just swipe right to snooze it?

**Comment by Webifi** [comment]
Looks like this has been resolved.  Just had a high alert, and selecting the android notification opens xdrip, and opens xdrip's snooze high alert dialog.
