### ISSUE TITLE
Wear 2.0 watch-face doesn't auto-update

### ISSUE THREAD

**Issue by jamorham** [NightscoutFoundation/xDrip#426]
Due to issues with version handling on Wear 2.0 the xDrip watchface doesn't automatically keep in sync with the version installed on the phone. 

Plan to detect this within the watchface.

**Comment by avr248** [comment]
Good Luck

**Comment by jamorham** [comment]
26th July nightly has some support for this on my demigod enabled watch roms,

**Comment by Navid200** [comment]
@jamorham I hope you don't mind me closing this as it seems you are happy with the status.
But, please let me know if I should reopen.
