### ISSUE TITLE
Polar M600 Oreo update

### ISSUE THREAD

**Issue by jamorham** [NightscoutFoundation/xDrip#427]
Installing the stock oreo update from polar will break my rom patches.

Patches need to be updated for oreo.

**Comment by jamorham** [comment]
https://github.com/NightscoutFoundation/xDrip/wiki/Patching-Android-Wear-devices-for-use-with-the-G5

Page updated with the new M600 Oreo care package.

Tests here show it working with G5 and other collectors like miaomiao - Make sure to use the latest xDrip nightly watchface.

**Comment by borijess** [comment]
I tried the patch and got an error in TWRP. All the patches errored.

**Comment by borijess** [comment]
Ok tried the watch again and it is working as a collector now.

**Comment by jamorham** [comment]
Marking as resolved

**Comment by abherrma** [comment]
@borijess how does the M600 work w/ xdrip? would like to have a fitness watch that can get g5/g6 data directly from the transmitter (w/o phone).

**Comment by Kalovsky** [comment]
@abherrma Took me a little bit of tweaking with the settings in xdrip, but eventually got it so that I use my watch as collector almost exclusively.

**Comment by martinachtman** [comment]
@jamorham i just received a polar M600 0A1E(Build OWDB.180305.015) and installed xdrip+(20190518-14a03a7). The watch isn't working as a receiver, without the patch( OWDB.180305.008), would you be so kind, to port the patch to OWDB.180305.015?

**Comment by mvuoristo** [comment]
@jamorham I have Polar M600 with build  OWDB.180305.015 and got errors when tried to install patch into it. Is it possible to port a  bt patch for a latest build? Thanks.
