### ISSUE TITLE
(Request) Multi-wave Bolus options

### ISSUE THREAD

**Issue by parapenT1sta** [NightscoutFoundation/xDrip#429]
Are you thinking to add an option for Multi-Wave Bolus? For those using Libre and Insulin Pump with no Loop environment?

**Comment by Navid200** [comment]
@parapenT1sta Are you planning to add this capability?
Or, have you already?
Would you please update the status of this issue?
Thanks a lot

**Comment by parapenT1sta** [comment]
@Navid200 I am not a developer :( I am closing this ticket.

**Comment by Navid200** [comment]
I saw "contributor" and made the assumption.  Sorry about that.
In that case, you don't have to close.  Do you know if this capability exists now or still not?

**Comment by parapenT1sta** [comment]
@Navid200 I only collaborate with translations.

Now we have for Basal Insulin but still no option for Multi Wave but should be useless since Nightscout doesn't support it.

**Comment by Navid200** [comment]
Many thanks for your contributions.  Please fell free to reopen.

**Comment by parapenT1sta** [comment]
I don't think it's needed. I even had forgot that I had this request. :)
