### ISSUE TITLE
What is the current stable release date / version?

### ISSUE THREAD

**Issue by roppenheimer** [NightscoutFoundation/xDrip#434]
There doesn’t seem to be any note of current release date / version or release note to document what changes are made in the new version.

**Comment by Webifi** [comment]
Seems like you need to just find the best nightly that fits your needs.

However I've yet to find a nightly that doesn't seems to intermittently hang the G5 ob1 collector, requiring me to start my phone and/or restart the collector, then nurse the collector back to life by watching the "G5 Status" screen, keeping the phone from sleeping, waiting for the "Phone Service State" to say"Got data ..." and "Bluetoth Link" to say "Closed OK".  After that, it seems to work again until it intermittently hangs again, missing data from my G5.  

Really quite annoying.

**Comment by Navid200** [comment]
You can click on commits to see what has been done for each release.  That's all we have.
No, it's not a release note.
![Untitled](https://user-images.githubusercontent.com/51497406/117747060-7e4f1c00-b1db-11eb-8be5-6b7394973574.png)

It has been requested before.  It will not be added.  I am sorry.

**Comment by Navid200** [comment]
https://navid200.github.io/xDrip/docs/ReleaseNotes.html
