### ISSUE TITLE
Buggy Samsung using workaround 

### ISSUE THREAD

**Issue by roppenheimer** [NightscoutFoundation/xDrip#435]
What does the message “Buggy Samsung using workaround” in the G5 system status mean? Is this configurable? Does it relate in any way to missed readings?

**Comment by jamorham** [comment]
It means a work-around is being applied to get around Samsung power saving features which are not compliant with the android specification. It is not configurable, it automatically enables when required.

**Comment by Alita1174** [comment]
Xdrip ha dejado de funcionar y me aparece este mensaje "Buggy Samsung: Using work around".
Puede ser el motivo del fallo de la aplicación?
