### ISSUE TITLE
Calibration graph is completely out of limits 

### ISSUE THREAD

**Issue by ulrik2000** [NightscoutFoundation/xDrip#438]
I can't find a way to get my calibration graph to become normal again. Tried stopping and starting sensor again. G5. Tried restating mobile. Tried adding BG values. Tried different settings. Nothing works.

Now I have also uninstalled xDrip+ and installed xDrip+ again, to start from scratch. But the problem is still the same. Is the sensor faulty? But then I have just experienced 2 faulty sensors in a row. And it has never happened before. It does not seem to be the the most likely explanation.

Does Xdrip+ store some (in this case faulty) data, that it continue to use, even after re-installation of the application, to create the most likely (in this case a very faulty) calibration graph?  
And it seems in this case, xdrip creates a calibration graph, that is so faulty, that it is not possible to correct it by entering additional BG calibration values?

I have used xdrip+ for 6 month and it always work perfectly. What has happened?

I think the issue started when I did not stop sensor before it was out of body. 

Screenshots (According to graph my BG can go as low as MINUS -95 mmol/l. It's way out.

And so is the BG readings from xdrip. Display ??0 or 2,0 mmol/l (which is equal LOW). On the last screenshot I had just calibrated. The graph then moves up towards the calibration, as supposed to, but as calibration is still way out, the next value (the last read dot) comes in as 2.0 mmol/l or LOW.

Can I reset the whole system somehow?

![screenshot_20180513-201731](https://user-images.githubusercontent.com/33326622/39983032-8c559fb4-5756-11e8-80f4-dcc015b2665a.png)

![screenshot_20180514-091456](https://user-images.githubusercontent.com/33326622/39983340-a1bd1688-5757-11e8-9607-727ad2b23104.png)

**Comment by ulrik2000** [comment]
Solved. :)
Problem was that the battery in the transmitter was low (Voltage A: 189 and Voltage B: 176) and that it somehow made the transmitter transmit false values to xDrip+. The false values was so much out of range, that xDrip+ could not calibrate (which is good). 
Thank you for comments and help :)

**Comment by jamorham** [comment]
Which version are you using? This should be caught by the newer Sensor Sanity checks which would refuse to touch a raw value that high.

**Comment by Navid200** [comment]
@ulrik2000 Since your problem was resolved, would you please close this issue?
Thanks
