### ISSUE TITLE
Bluecon: reading historical data older than 20 minutes ago

### ISSUE THREAD

**Issue by trallen** [NightscoutFoundation/xDrip#439]
Hi there

I tend to go for runs without my phone, and when I return, the only historical data I get is the previous four readings. I'd like to be able to track what happened to my glucose levels during the run.

Reviewing the code, I see that Bluekon.java seems to limit m_minutesBack to 15 whenever the value is over 17 (lines 356-362 in the current git master):

```
// ensure to have min 3 mins distance to last reading to avoid doible draws (even if they are distict)
if (m_minutesBack > 17) {
    m_minutesBack = 15;
} else if (m_minutesBack > 12) {
    m_minutesBack = 10;
} else if (m_minutesBack > 7) {
    m_minutesBack = 5;
}
```

Is there a specific reason that it reduces any age to the most recent 15 minutes? Could I simply rebuild it with those lines commented out, or with a loop which sets any m_minutesBack to the closest multiple of 5, along the lines of this:

```
if ((m_minutesBack % 5) > 2) { 
    m_minutesBack -= m_minutesBack / 5;
}
```
?

Thank you for some very useful software!

**Comment by gregorybel** [comment]
no, reading last 8h is a lot more complicated and Battery intensive.

you can have a look at how it's done using NFC.

why do you need that?

**Comment by trallen** [comment]
Thanks for the quick reply. I'll play around a bit and see if I can get it working satisfactorily (maybe hidden behind a preference).

**Comment by tzachi-dar** [comment]
There is one simple advice to get the 8 hours data:
Follow this page: https://github.com/tzachi-dar/LibreOOPAlgorithm

It will also give you results very close to the libre reader with no need for calibration.

**Comment by trallen** [comment]
Thanks very much! The LibreOOPAlgorithm extension works fabulously. Interesting to see the difference in values (in my previous testing of the Libre Reader, the values seem to be slightly less accurate than a well-calibrated value in xDrip, but that's a matter for the FreeStyle team!). I'll mark this issue as closed.
