### ISSUE TITLE
Broadcast of CGM-values from AAPS to xDrip not working

### ISSUE THREAD

**Issue by philipgo** [NightscoutFoundation/xDrip#446]
[AAPS 20 RC3, xDrip Feb 11, modified Dexcom App]
Many AAPS users use the modified [Dexcom App](https://github.com/dexcomapp/dexcomapp). This app is  modified so it broadcasts CGM values to AAPS. AAPS in turn can broadcast CGM values to xDrip - for example to make use of the great alarm features or combine the NS upload with Bluetooth meter values.

This feature completely stopped working with the Feb 13 nightly, it still works with the Feb 11 nightly. However, with the Feb 11 nightly, xDrip displays the proper direction arrow but always uploads direction=flat to Nightscout.

Upload created by AAPS:
```
{ 
    "_id" : ObjectId("5affdd0be1ecc30013a19be6"), 
    "device" : "AndroidAPS-DexcomG5", 
    "date" : 1526717691000.0, 
    "dateString" : "2018-05-19T08:14:51Z", 
    "sgv" : NumberInt(148), 
    "direction" : "SingleUp", 
    "type" : "sgv", 
    "NSCLIENT_ID" : 1526717707080.0, 
    "created_at" : "2018-05-19T08:15:07.964Z"
}
```

Same value when uploaded by xDrip after receiving the broadcast from AAPS:
```
{ 
    "_id" : ObjectId("5affdd0cd13d101efcc8b76a"), 
    "device" : "xDrip-NSEmulator", 
    "date" : 1526717691000.0, 
    "dateString" : "2018-05-19T10:14:51.000+0200", 
    "sgv" : NumberInt(148), 
    "delta" : 9.967, 
    "direction" : "Flat", 
    "type" : "sgv", 
    "filtered" : NumberInt(148000), 
    "unfiltered" : NumberInt(148000), 
    "rssi" : NumberInt(100), 
    "noise" : NumberInt(1), 
    "sysTime" : "2018-05-19T10:14:51.000+0200"
}
```

**Comment by jamorham** [comment]
Thanks for the detailed bug report. Please can you test the May 20th Nightly and let me know if it resolves both these reported issues.

**Comment by philipgo** [comment]
After one day of testing I can say that:
- Broadcast of the value from AAPS to xDrip now always works
- xDrip mostly (but not always) shows the same direction arrow as AAPS. Does xDrip calculate the direction from the delta? Would it be possible to use the same direction as AAPS?
- xDrip never uploads the correct direction to Nightscout, the uploaded direction is always "Flat"

Thank you!

**Comment by philipgo** [comment]
@jamorham If the direction arrow error proves hard to fix, an alternative would be to allow for an option to drop upload of CGM values while still uploading Bluetooth meter values.

**Comment by jamorham** [comment]
I believe a fix for this will be in the next nightly

**Comment by jamorham** [comment]
https://github.com/NightscoutFoundation/xDrip/commit/dd677e7db2c0c9e607d9eeda5548a67b4256de2d

Please let me know if this resolves it

**Comment by philipgo** [comment]
Nice, that appears to have fixed it. Thank you so much! I will do some more testing and report again in a few days.

**Comment by jamorham** [comment]
If everything is okay now please report success and close the ticket. Thanks!

**Comment by philipgo** [comment]
Both broadcast and direction arrows now work as expected. Thank you for the fix!
