### ISSUE TITLE
Latest (after 17.12) nightly Builds (automatic) have a broken watchface

### ISSUE THREAD

**Issue by diabetesdt1** [NightscoutFoundation/xDrip#45]
The nightly Builds after 17.12 have a broken Watchface.
On the SmartWatch, the xDrip-Watchface is only Black and show nothing :-(

**Comment by jamorham** [comment]
@kskandispersonal are you able to check this? thanks

@diabetesdt1 Can you use System Status menu in xDrip app to confirm exactly the version you are currently running?

**Comment by kskandispersonal** [comment]
@jamorham I do not see this is yesterday's code built on my machine.  I just pulled the latest code and will rebuild, test and report back.

**Comment by blocklist** [comment]
Version 1612171610 works
with the latest Version 161220800 from today morning it works, but only when the watch is not rebootet.

When  have choose a other Watchface and then the xDrip Watchface again, it works.

![20161222_153031](https://cloud.githubusercontent.com/assets/491321/21428819/37ccb44e-c85c-11e6-8caa-f253f712e891.jpg)
![20161222_153035](https://cloud.githubusercontent.com/assets/491321/21428818/37af8b44-c85c-11e6-93e1-5f0f0423ec97.jpg)
![20161222_153120](https://cloud.githubusercontent.com/assets/491321/21428817/37a13d50-c85c-11e6-92d6-f16cfc0fd355.jpg)
![20161222_153133](https://cloud.githubusercontent.com/assets/491321/21428816/37a06a56-c85c-11e6-8c41-09d6a0a9533e.jpg)
![20161222_153144](https://cloud.githubusercontent.com/assets/491321/21428814/379cb80c-c85c-11e6-8279-6402a38ce22b.jpg)
![20161222_153156](https://cloud.githubusercontent.com/assets/491321/21428815/379e54aa-c85c-11e6-99cc-0edc204c9d9e.jpg)
![20161222_153239](https://cloud.githubusercontent.com/assets/491321/21428813/3799f568-c85c-11e6-8654-1f6664ac8477.jpg)

**Comment by jamorham** [comment]
okay I think we know what is causing this and a new version is being prepared

**Comment by blocklist** [comment]
perfect guys! Thank you!

**Comment by jamorham** [comment]
Please try this version and let me know if it resolves the problem:

https://github.com/NightscoutFoundation/xDrip/releases/download/2016.12.22b/xDrip-plus-20161222-51bd62f.apk

**Comment by blocklist** [comment]
Yes, it works. 
The Watchface/xdrip-prefs not crashed after installing and reboot (phone and watch; watch only).

Thank you very much!

**Comment by jamorham** [comment]
@diabetesdt1 does this also resolve your problem?

**Comment by blocklist** [comment]
@jamorham it is the same account. Only for forks of diabetes-software from me :-) sorry, i used the false-login (blocklist.de). issue is solved. Thanks!
