### ISSUE TITLE
Weird graph after disabling data collection

### ISSUE THREAD

**Issue by TebbeUbben** [NightscoutFoundation/xDrip#450]
I just disabled data collection to pair a Bluetooth meter and this is what my graph looks like now:
![screenshot_20180521-094434](https://user-images.githubusercontent.com/8694925/40296058-ed099510-5cdb-11e8-8b36-3ac1699b5200.png)

**Comment by jamorham** [comment]
I believe you said this was due to testing a full-sugar drink with a connected glucose meter?
