### ISSUE TITLE
Error with Libre trend

### ISSUE THREAD

**Issue by dv1** [NightscoutFoundation/xDrip#452]
xDrip Bluetooth collection worked so far. But now all of a sudden the libre trend does not work anymore. The logs show: "libreBlock exists but no matching bg record exists" and "BG data was not calculated, working on raw data". xDrip was recently calibrated. "Show libre trend" shows "display error".What can I do to fix this? Also, the main screen shows three triangles with exclamation marks. What do these mean?

EDIT: Scanning with NFC removed the three triangles, but "show libre trend" is still not working. Using the SweetReader.

This is version a30ed57-2018.05.10 .

**Comment by tzachi-dar** [comment]
What hw are you using for the scan?
In any case, this might happen if there is a too often scan. Is the issue resolved after a few minutes?

**Comment by tzachi-dar** [comment]
I'm sorry, but I'm not familiar with the sweet reader. Do you know if it passess the full scans?

**Comment by tzachi-dar** [comment]
Libretrend works with everything that brings the entire nfc block always: so it works with 
tomato, librealarm, bluekon (oop mode) and direct scans by phone.

We need to understand how sweet reader works to see how to enable it there as well.

**Comment by dv1** [comment]
Ah, okay. This explains it. Prior to getting the LibreReader, I scanned via NFC with the phone.

However, I turn off "Show libre trend", and yet I see the "Show libre trend" menu item?

**Comment by Navid200** [comment]
@dv1 Would you please close this issue if you have the answer you were looking for?
If not, you can use the support channels.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks
