### ISSUE TITLE
BLE connectivity state indication

### ISSUE THREAD

**Issue by keencave** [NightscoutFoundation/xDrip#454]
Would it be possible to add a BLE connectivity state indication to the xDrip+ main screen?

I suggest a small colored dot or a colored name "BLE" on the upper screen:

Red: Disconnected
Yellow: Connecting
Green: Connected

This would make things easier to detect errors in BLE communication.

**Comment by Navid200** [comment]
The time of last reading is shown n the main screen at the to left.

If it shows 1 Minute ago or anything less than 5 minutes ago, it means that there has been connectivity up to the last reading.

If it shows a value of 5 minutes ago or anything grater than 5 minutes, it means that there is a problem.

I hope that this is good enough to serve the purpose.
Is it OK if we close this issue?

**Comment by Navid200** [comment]
We can reopen this if needed.
