### ISSUE TITLE
QR menu not showing properly

### ISSUE THREAD

**Issue by parapenT1sta** [NightscoutFoundation/xDrip#456]
Using Finowatch Q1 PRO 240x240, this is what I get. 
I am able to choose QR option pressing on the screen, sometimes its select the XDrip Plus Security, and other times the "Show General..."

![20180528_125902](https://user-images.githubusercontent.com/608650/40613707-9112dcfc-6277-11e8-8cc4-d41d8d302ea2.jpg)

**Comment by jamorham** [comment]
This should be resolved in the 31st May nightly. Please let me know if it works.

Thanks

**Comment by parapenT1sta** [comment]
Oh yes!!! issue fixed!!
