### ISSUE TITLE
Plugin glucose value not pushed to android wear (complication & watchface)

### ISSUE THREAD

**Issue by nsghub** [NightscoutFoundation/xDrip#468]
I'm using a calibration plugin and the plugin value is shown on the phone as expected.
On Android Wear 2.x the complication always shows the xdrip+ default value but not the plugin value. The dedicated xdrip watchface is able to show the plugin values, but it's not reliable. After a while it switches back to default (display always on) and it takes another while until it changes back to plugin.

**Comment by gregorybel** [comment]
fixed in https://github.com/NightscoutFoundation/xDrip/commit/1d7a28be51c56eddc1c9aa1effdf77a731185f72

**Comment by Navid200** [comment]
@nsghub Would you please close this issue if it has been addressed?
Thanks
