### ISSUE TITLE
meter as a sensor

### ISSUE THREAD

**Issue by getut** [NightscoutFoundation/xDrip#469]
xdrip and nightscout are so incredibly useful even without data every 5 minutes from a true CGM. Would it be possible to add a setting to allow meter data to be used as sensor readings rather than just calibrations?

**Comment by jamorham** [comment]
What happens if you select `Disable Collection` as the data source and use with just a meter?

**Comment by getut** [comment]
Unless I'm doing something wrong, it isn't exporting from xdrip as a blood glucose reading and it isn't uploading to nightscout as a reading either.

**Comment by getut** [comment]
After running it last night and today, it does show on the nightscout reports as a red dot just like it does in xdrip, but still won't use it in raw data exports or in any calculations or displays such as the current bg number showing on the nightscout page. It also won't auto populate on the bolus wizard even if the last bg reading with the meter was less than 5 minutes ago.

**Comment by getut** [comment]
Jamorham... hopefully you see the question... any more ideas on how to get meter data showing up as actual BG readings?

**Comment by jnharmon** [comment]
I think I basically have the same question in issue 453.  My meter readings from a Onetouch Verio Flex are going into xDrip, but are not being pushed to my Nightscout MongoDB database.  The strange this is that the battery status from the Verio Flex is going to MongoDB, but the actual meter readings are not.

**Comment by getut** [comment]
I'm using a contour next one bluetooth meter. My readings go into both xdrip and nightscout, but don't show up on either graph because I believe both xdrip and nightscout are tagging them calibrations not glucose readings. I came to this hypothesis based on the fact that using data export from xdrip to csv does not show any BG readings at all. The CSV is in the format Day, Time, UDT_CGMS,BG_Level,CH_GR,Bolus, Remark. BG_level is always an empty field even when I can run a report in nightscout and see red dots for each meter reading.
![selection_044](https://user-images.githubusercontent.com/1457587/41482933-2cbc617e-70a5-11e8-8a51-23503f9c98f7.png)

**Comment by getut** [comment]
Sorry to keep harping on this one, but jamorham, who I believe is a dev asked me a question about disabling collection and if it gets meter readings to function as real bg tests as if from a meter. This leads me to believe that HE thinks this should be working. Does anyone have any idea as to what could be configured incorrectly that it isn't working that way? If this is a feature request that simply isn't implemented, I'll shut up and wait patiently. But if this is in fact something that should already be working, then any more ideas?

**Comment by Navid200** [comment]
If you disable automatic calibrations, the readings from the Bluetooth meter should still show in the graph but not be used for calibration.

**Comment by Navid200** [comment]
I am closing this issue for now.
Would you please update as to if you are still experiencing this with newer releases of xDrip?
Thanks
