### ISSUE TITLE
xdrip sometimes becomes unresponsive after pin code input for blukon

### ISSUE THREAD

**Issue by gregorybel** [NightscoutFoundation/xDrip#470]
Nightly from 5.5.18.
steps:
* Blukon already paired
* BT scan
* select blukon
* input pin
-> no more reaction from xdrip

Don't always happen!

**Comment by jamorham** [comment]
I think this may resolve it:

https://github.com/NightscoutFoundation/xDrip/commit/d0d70b59b273ffa9e9d368306649b8201061d4b9

**Comment by gregorybel** [comment]
yes it's solved, well done, thanks Jon
