### ISSUE TITLE
xdrip displaying "LOW" bg, AndroidAPS takes that as a missed reading and restarts normal basal profile.

### ISSUE THREAD

**Issue by iversenshotrods** [NightscoutFoundation/xDrip#471]
When experiencing a low bg, xdrip displays the correct "LOW (38)" message on graph but AndroidAPS sees "LOW (38)" as a missed reading and restarts the normal basal instead of keeping the temp basal at 0%. AndroidAPS community advised to open xdrip issue.

**Comment by Navid200** [comment]
@iversenshotrods There is a wealth of knowledge on the xDrip facebook about AAPS.
If you still have questions, you can post there.
https://www.facebook.com/groups/xDripG5

Would you please close this issue?

**Comment by iversenshotrods** [comment]
This issue was corrected with an app update back in late 2018.
