### ISSUE TITLE
history being deleted

### ISSUE THREAD

**Issue by castdoom** [NightscoutFoundation/xDrip#474]
hi i noticed that after using xdrip "latest version" the history stored on the libre sensor seems be be getting deleted. when i scan using the libre app none of the last 8 hours is there.

unfortunately i need to keep the libre app up to date so if this is a feature can it be turned off somehow?

libre+blucon

**Comment by tzachi-dar** [comment]
Not sure what you mean. Are you saying that reading that you had are getting deleted, or that the gap is not closed?

**Comment by castdoom** [comment]
hiya,

i have to still scan my libre sensor for my clinic to view the graphs via libreview.

the libre sensor stores the last 8 hours of 15 min checks itself, but after using xdrip + blucon, when i go to update the libreview app the sensor hasnt got the last 8 hours. its treated like the sensor has no history stored at all.

it could just be a bug with the libre sensor? i thought it was a feature of xdrip heh...

**Comment by nsghub** [comment]
I cannot confirm that for nightly 2018.06.10.

**Comment by tzachi-dar** [comment]
This seems very strange.
xDrip does not have a way to delete anything from the sensor.

**Comment by castdoom** [comment]
ah, hmm do you think its just a issue with the libre? i stopped using xdrip and blucon just to see if the history started up again "same sensor" and its working fine

**Comment by tzachi-dar** [comment]
This is very strange, can you try putting the bluecon on and see if it happens again?

**Comment by castdoom** [comment]
sure thing il report back in abit of testing :)

**Comment by castdoom** [comment]
doesnt seem to be happening anymore strange! may have just been a bug with the sensor itself.

quick question, is there a way to get exactly the same values showing on xdrip as scanning with the libre app?
