### ISSUE TITLE
Miaomiao Bluetooth reconnect

### ISSUE THREAD

**Issue by jroth-haj** [NightscoutFoundation/xDrip#478]
Durch Interferenzen mit WLAN im 2.4 GHz Bereich scheint xDrip die Verbindung zum miaomiao zu verlieren. Dies passiert, je nach Umgebung, unterschiedlich oft.
Dann muss ich im xDrip den Bluetooth Scan durchführen, den (eigentlich bekannten) miaomiao auswählen und es läuft wieder.

Lässt sich dieser Prozess nicht automatisieren? xDrip kennt doch die MAC des bereits verwendeten Miaomiao.

Ist es möglich bei fehlenden Daten nach 10 bis 15 min den Scan und die Verbindungswiederherstellung zu automatisieren?

translated by google:
Due to interferences with WLAN in the 2.4 GHz range, xDrip seems to lose the connection to the miaomiao. This happens differently, depending on the environment. Then I have to perform in xDrip the Bluetooth scan, select the (actually known) miaomiao and it works again. Can not this process be automated? xDrip knows the MAC of the already used Miaomiao. Is it possible to automate the scan and reconnect after 10 to 15 minutes if there is no data?

**Comment by jroth-haj** [comment]
Mybe corresponding with #440
Using Samsung S5.

Can it be a workaround to implement automatic scan and reconnect?

**Comment by leoleezoom** [comment]
And you can follow the steps below to turn off the "Trust Auto-Connect" to have a try!

Setting——> Less common settings ——>Bluetooth Settings——>Trust Auto-Connect(Turn it off!)

**Comment by jroth-haj** [comment]
Great. since yesterday morning (36h) no problems!
I'll report again in the next days.
It seems to solve the problem.

**Comment by digiphot** [comment]
I have the same problem. Using Samsung S8+
Question: What version of xdrip+ I should use?
I did not find (in the German version) the "Trust Auto-Connect"

**Comment by digiphot** [comment]
I have got an answer from a different source:
The trick is to purge the bluetooth cache

**Comment by jroth-haj** [comment]
Since I installed the new version, optimized the BT setting and also have GPS enabled it's working!
