### ISSUE TITLE
A bug on the new OB1 Collector for dexcom G5

### ISSUE THREAD

**Issue by jokellerweb** [NightscoutFoundation/xDrip#481]
![2018-06-17 21 29 05](https://user-images.githubusercontent.com/31852218/41511440-fdb58210-7276-11e8-952f-470d26230231.jpg)

The watch shows the wrong trend arrow. xDrip-App on Phone ist correct. Watch-Collector with dexcom G5

**Comment by Navid200** [comment]
@jokellerweb Would you please close this issue if the problem has been resolved?
Otherwise, would you please update?
Thanks
