### ISSUE TITLE
sensor issues

### ISSUE THREAD

**Issue by castdoom** [NightscoutFoundation/xDrip#485]
hiya,

been using the blucon + xdrip for a couple days, the issue is that as of last night the libre sensor seems to have broken, it displays "lo" even with a normal nfc scan when im sitting around 10 according to a bg test the sensor has just under 4 days left of use but il have to change it, is it possible that the blucon causes issues with the libre sensor? has anyone else had this issue?

**Comment by gregorybel** [comment]
I assume your Sensor moved a bit and doesn't measure anything anymore. you should replace it. make sure your property clean the skin and if it Happens again you should consider fixing the Sensor with kind of transparent adhesive.

this happens sometimes due to arm holder.

**Comment by castdoom** [comment]
yeah that could be it!  i replaced it and the new ones fine, when i use the blucon i have a strap holder for it, i guess that moved the sensor...any suggestions on the adhesive for the sensor/blucon that wont move it? 

thanks for your help

**Comment by gregorybel** [comment]
this for example: Fixomull Stretch 2 m x 10 cm Verband, 1 St. https://www.amazon.de/dp/B00EIHGUSC/ref=cm_sw_r_cp_apa_9IjlBbY2TM8ED

either around Sensor or over Sensor+blucon

**Comment by castdoom** [comment]
thanks, i got tegaderm i think its called, so im trying that just over the libre.

happen to have any suggestions on something good to hold the blucon in place without moving the libre? if the strap isnt a good goto.
