### ISSUE TITLE
MiaoMiao Battery status at home screen?

### ISSUE THREAD

**Issue by parapenT1sta** [NightscoutFoundation/xDrip#487]
I can't get MiaoMiao battery status at the main screen as I do with Blucon. Is it possible to add this info? Instead of going to System Status - BT Device page.

Thanks

**Comment by ralf-ms** [comment]
I'd like to have that too.

**Comment by bboi61** [comment]
And a warning Battery Low at 30%, so it has communicated to me the Chinese manufacturer.
I would be happy, thank you.

**Comment by dabear** [comment]
@tzachi-dar This should be trivial to implement, looking at blukon.java the only thing you would have to set is Pref.setInt("bridge_battery", X); something you can look into? I don't know if having the battery value stored both in PersistentStore (like tomato does now) and in Pref is the correct thing to do here (this should maybe be unified?)

**Comment by tzachi-dar** [comment]
Opened https://github.com/NightscoutFoundation/xDrip/pull/501

**Comment by parapenT1sta** [comment]
@tzachi-dar Thanks! :)

**Comment by gregorybel** [comment]
maybe another candidate for the common class?

**Comment by dabear** [comment]
This can now be closed

**Comment by simonish** [comment]
Is this MM battery status now included in the latest nightly build? - I am still running 20180530

**Comment by Navid200** [comment]
@parapenT1sta Was this implemented?  Can we close this issue?
Thanks

**Comment by parapenT1sta** [comment]
@Navid200 Yes. It was. :) Closing the ticket.
