### ISSUE TITLE
Wear complication show wrong BG plugin

### ISSUE THREAD

**Issue by gregorybel** [NightscoutFoundation/xDrip#492]
Dont know if it an old issue I never saw or a new one but using datriasec as plugin for libre, wear complication shows value from xdrip plugin and not from datriasec plugin, which somtimes are not the same values!

Can you fix it or give my a hint where issue could be?

**Comment by nsghub** [comment]
And also #468

**Comment by gregorybel** [comment]
yes indeed!

**Comment by gregorybel** [comment]
fixed in https://github.com/NightscoutFoundation/xDrip/commit/1d7a28be51c56eddc1c9aa1effdf77a731185f72
