### ISSUE TITLE
Block NS upload on noisy values

### ISSUE THREAD

**Issue by AdrianLxM** [NightscoutFoundation/xDrip#495]
Reminder from the gitter conversation:

It would be good if there was an option to also block the upload to Nightscout on noisy values like with the local broadcast. (Safety measure for loop systems).

**Comment by tim2000s** [comment]
If you’re using G5, xDrip+ is already providing noise information and OpenAPS is handling this, with various behavioural changes for light and heavy noise, as the same is available via the Dexcom connections. Surely that’s a better way of handling it?

**Comment by Navid200** [comment]
@AdrianLxM Do you still think this would be a good feature?
There are loops that don't go through Nightscout, like t:slim.  So, even if implemented, it will not benefit all loop systems.

What do you think?
I would like to either label this or close it.
Thanks

**Comment by Navid200** [comment]
We can always reopen.
Closing dur to inactivity
