### ISSUE TITLE
miaomiao settings

### ISSUE THREAD

**Issue by Mr-Enigma** [NightscoutFoundation/xDrip#498]
hiya!

just wondering if the recommended settings for the miaomiao is the same as blucon? 

i just got my miao today and already seen a checksum error in the status page?

thanks!

**Comment by tzachi-dar** [comment]
Is this a one thing or does the checksum error happens more.
There is a big chance that it is caused because miaomiao is not attached well to the sensor. Try connecting them better.

**Comment by castdoom** [comment]
hiya,

i have noticed the checksum error twice, in the 4ish days i have been using the miao. i suspect its just a bug somewhere but its not causing issues :)

**Comment by tzachi-dar** [comment]
Checksum error from time to time does not mean a bug.
It means some thought of data corruption, but the checksum mechanism protects from than and a retry happens.
It is very common in NFC or other ways of communications.

**Comment by castdoom** [comment]
ah so i should just ignore it? i have tried removing the miaomiao and reapplying but got the error a couple more times

**Comment by Navid200** [comment]
@Mr-Enigma Would you please close this issue?
You can ask for help on the xDrip facebook group:
https://www.facebook.com/groups/xDripG5

**Comment by Mr-Enigma** [comment]
> @Mr-Enigma Would you please close this issue?
> You can ask for help on the xDrip facebook group:
> https://www.facebook.com/groups/xDripG5

I like many others don't use Facebook, it seems to me the best place to ask questions would be where the software is not a random social media platform. But yes I will close this since it has been resolved.

**Comment by Navid200** [comment]
There are many xDrip users, and a few developers, who share ideas and knowledge in the xDrip facebook group. 
A question posted in that group gets responses in less than 24 hours.  If a discussion there results in a conclusion that there is indeed an xDrip bug, an issue is opened here then.

If you don't like to use that resource, I cannot force you.  It was just a suggestion.
