### ISSUE TITLE
Force English Text doesn't work

### ISSUE THREAD

**Issue by iValkou** [NightscoutFoundation/xDrip#500]
"Force English Text" option doesn't work on Android 8+

**Comment by jamorham** [comment]
This issue has been confirmed.

**Comment by jamorham** [comment]
This should be resolved in the Aug 17th Nightly. Please confirm. Thanks

**Comment by hjortling** [comment]
Confirmed working on Android 8.0 running xDrip+ Nightly build 8th Sep 2018

**Comment by jamorham** [comment]
Marking as resolved.
