### ISSUE TITLE
Add support for Medtrum A6 CGM

### ISSUE THREAD

**Issue by jamorham** [NightscoutFoundation/xDrip#504]
This work is in progress now.

This ticket replaces: https://github.com/NightscoutFoundation/xDrip/issues/408

@kimbersdiabetic @dimis28 @tim2000s @sulkaharo if you know of any interested parties who would be able to test the support when it is ready, it would be great if they could make themselves known here.

**Comment by jamorham** [comment]
I am making good progress with this. I will let you know when I have anything to test.

**Comment by Menor3** [comment]
Nice one, can't wait to test it out. The medtrum application is pretty bad and it drains the battery like CRAZY.

**Comment by jamorham** [comment]
Ok, I think I have a lot of stuff working now. I'm getting data from the sensor. We have the option to use the A6 native algorithm or the xDrip algorithm. 

I'm going to make it an option which to show as the primary number and then plot the alternate algorithm as a trace behind it so we can work out which may be the most useful. There may need some tuning to work properly with xDrip calibration algorithm which as a lot of dex style assumptions in it.

**Comment by jamorham** [comment]
Okay the July 19th nightly contains support for the Medtrum A6. Its about 2000+ lines of code so far!

To get it to work you should select Medtrum A6 in the hardware data source settings section. Then use `Bluetooth Scan` to identify the A6 transmitter. It isn't always discoverable so you often have to keep clicking scan until it shows up. If its not attached to your body then pop it in the charging doc and after a few seconds it should be visible.  When you see it click on it to select it.

Now select `Start Sensor` in xDrip (assuming it is connected to a sensor) and you should start to get it gathering data. Use the `System Status` menu item and the `Medtrum` tab to see what the collector is doing.

Once you have calibrated it then you can also go back to the `Settings` page and below the `Data Source` you can choose to use either the native algorithm of the A6 or the xDrip algorithm on the raw data. I am very interested to know whether xDrip algorithm works successfully with it. 

It will also generate a dual plot showing the Native algorithm and xDrip algorithm. The one which is not selected as primary will show as tiny purple dots.

**Comment by Menor3** [comment]
Where exactly I can download this new version?

**Comment by jamorham** [comment]
@Menor3 switch to the Nightly update channel, see instructions here: https://github.com/NightscoutFoundation/xDrip/wiki/How-to-get-the-Nightlies-on-Automatic-Update

**Comment by Menor3** [comment]
Do you think that having xdrip and easysense app open at the same time may cause the transmitter to lost the signal, so I have to restart it?

**Comment by jamorham** [comment]
I think there is a very strong chance that the official app can interfere. You can try force stopping it from the android system settings for apps and see if that can temporarily stop it running while you test xDrip.

**Comment by Menor3** [comment]
Yeah, I can confirm that the official app is causing sensor to lost signal. After force stoping the app, everything works for now.

**Comment by Menor3** [comment]
Do you think it is possible to make so the sensor doesn't restart every time you unplug the transmitter from the sensor?

**Comment by jamorham** [comment]
@Menor3 it might be possible. How often do you have to remove the transmitter?

**Comment by Menor3** [comment]
Not often, but for example I had some problems with the signal, because of the official app and I had to unplug it like 3 times to get the signal back again and every time the 2 hrs warm-up started. If everything works I think that you need to unplug it just to recharge the transmitter.

**Comment by jamorham** [comment]
Do you need to recharge the transmitter during the normal life of a sensor? I believe the xDrip implementation is robust and you shouldn't need to reset anything. If the transmitter can crash then perhaps it is not so simple but I haven't observed that in testing so far.

**Comment by Menor3** [comment]
I charged the transmitter to a 100% before starting a new sensor, but because of the signal problem the transmitter has 28% after roughly 2 days of use. Usually I think that you don't have to recharge it during a single sensor life.

**Comment by jamorham** [comment]
@Menor3  Can you let me know how the battery performs when using xDrip vs the official app, both the phone battery and transmitter. Thanks

**Comment by Menor3** [comment]
The phone battery performs very good with the xdrip comparing to the official app which could even take me over 20% of phone battery until evening. Xdrip takes about 1%, I haven't noticed any difference between the phone battery consumption when I used libre sensor and now medtrum. The transmitter seems to hold the battery pretty good while using xdrip app, I would say that it is much better than on the official app. After the whole day of use the transmitter battery dropped just 1%

**Comment by jamorham** [comment]
@Menor3 thanks for the testing and great to know its working well! The July 21st nightly should improve back filling, add extra failsafes to ensure it never stops collecting and also I believe the xDrip algorithm can now be used for calibration if you want to.

I am not sure how this will perform during the first 2 days of the sensor life as we don't know the raw sensor metrics yet,  but after that I think it definitely should be fine. You can instantly swap which is the primary source (native vs xDrip) using the checkbox just below the Medtrum A6 data source in the xDrip settings page.

I would be very grateful if you can upgrade to this new version (use check for update 3 dot menu item) and confirm it continues to operate correctly.

**Comment by jamorham** [comment]
July 23rd release contains some updates that make things work more cleanly during sensor warm-up period. Upgrading is strongly advised. 

With this version if you are using xDrip algorithm you can remove the transmitter and then reattach it and continue to get readings during the warm-up period although the numbers could be off due to the transmitter changing its internal low-level calibration.

**Comment by Menor3** [comment]
I updated the app to the newest version and I unplugged the transmitter to charge it, but I didn't get any readings after I reattached it. It just went to the warming up mode and it was showing that the signal has missed.

**Comment by Menor3** [comment]
I have done it at the beginning of testing the app

**Comment by kimbersdiabetic** [comment]
Not very good. Waited for 2 Hours for the initial set up, Then just waited for a further 3 Hours to get Initial Readings still needs 2 readings but checked  system status and it was reporting not Connected. This is the issue that i used to have with the Medtrum Easy sense app it would keep Disconnecting, Using Samsung Galaxy 5.

**Comment by Menor3** [comment]
After getting rid of the official app I haven't had any problems with connection, the problem is probably on your side.

**Comment by jamorham** [comment]
@Menor3 which model of phone do you use and which android version?

**Comment by Menor3** [comment]
Pixel 2 xl, android 8.1

**Comment by jamorham** [comment]
I've changed the collector in the latest nightlies to hopefully make it more robust on some phones. @Menor3 can you confirm that the latest nightly is still working well for you?

**Comment by Menor3** [comment]
Same thing, new transmitter doesn't wanna connect with the app.

**Comment by kimbersdiabetic** [comment]
Hi Menor3 How have you found the accuracy?

**Comment by Menor3** [comment]
Pretty good, but I usually use the xdrip calibration for the first 4-5 days then I would switched it up for the native medtrum calibration. That worked the best for me.

**Comment by DunePlodder** [comment]
I recently tried the updated Medtrum. @jamorham gave me a code to use in xDrip which was successful. I think the code varies according to the serial number of the transmitter.
For me the results from the upgraded Medtrum were a big improvement over the older version. However it didn't last long enough (12 days) to compete with my usual Dexcom from a self funding point of view.

**Comment by Menor3** [comment]
Anyone know how to make the app work with the new transmitter? @DunePlodder said that he typed in the app, can you tell me something more about it?

**Comment by DunePlodder** [comment]
@menor3 I think you'll have to ask @jamorham for the code.

**Comment by jamorham** [comment]
@Menor3 @DunePlodder Just use the latest nightly which has support

**Comment by Menor3** [comment]
@jamorham I still cannot connect the sensor. It doesn't appear in the Bluetooth scan

**Comment by jamorham** [comment]
@Menor3 is it connected to another device? I don't think it shows on scan if it is already connected. If you really get stuck you can pop it in to the charger and after a few seconds it should show on the scan.

**Comment by Menor3** [comment]
@jamorham Everytime i connect sensor to the app information is displaying 'set medtrum serial number' , where I can do that?

**Comment by DunePlodder** [comment]
@Menor3 Have you looked at this:
https://github.com/NightscoutFoundation/xDrip/wiki/Using-the-Medtrum-A6

**Comment by Menor3** [comment]
@DunePlodder yes I have, I can't see any information about that

**Comment by DunePlodder** [comment]
@Menor3 As I remember you don't actually enter the serial number. When you do the Bluetooth Scan in xDrip it displays the serial number at that stage. I can only suggest starting again & following the wiki step by step. Might be worth rebooting your phone first?

**Comment by Menor3** [comment]
@DunePlodder I started from scratch few time but there's always connectivity issues. The sensor connect for a few seconds then it disconnects and that's not ending loop.

**Comment by DunePlodder** [comment]
Does it connect to the Medtrum App? Thinking it could be a transmitter problem? Otherwise I'm a bit short of ideas I'm afraid.

**Comment by Menor3** [comment]
Yes it connects to the medtrum app no problem

**Comment by ARLabsClosedLoop** [comment]
I've just had a message from Spencer Martin at Medtrum that xDrip now supports the new Medtrum sensor & transmitter. Ive been using A6 closed loop (AAPS/DanaRS) since July and would like to know how this new upgrade is implemented - via an additional software layer (Medtrum app->xDrip->AAPS) or whether the new Tax is now supported directly in xDrip?

**Comment by louispeel78** [comment]
Good morning all, 

I received the new slim version of the medtrum A6 with the new sensors on saturday. 
I have tried to connect with Xdrip but it reads the transmitter serial number incorrectly and does not work. I am currently using medtrums own interface which i am not overly happy with. Can anyone offer any help as to how to correctly connect the transmitter to xdrip ?
Many Thanks

**Comment by Menor3** [comment]
@louispeel78 Did you have to pay for the new transmitter?

**Comment by louispeel78** [comment]
yes, but this was my first order from medtrum. i was waiting for the new system before i changed over.

**Comment by Menor3** [comment]
@louispeel78 are they still charging 140 pounds for 4 sensors?

**Comment by louispeel78** [comment]
I got the starter pack which was 225 for the new transmitter and 4 sensors, so i assume the 4 pack of sensors will also have the same price of 140 for a pack of 4

**Comment by ARLabsClosedLoop** [comment]
I have had some discussions with Spencer at Medtrum UK. He's sent the new TouchCare Slim (TCS) transmitter had sensors to Jon Amorham (last week) Medtrum have released him new code to build into xDrip - but so far (and I've been asking Jon on here for a month or two about it) there is no reply or news of a TCS compatible xDrip.
I'll use up my old A6 sensors and have to switch over to Dexcom in July, I expect. BUT I will be able to use prof Roman Hvorka's new Android loop software with my Dana RS then - every cloud has a silver lining.

**Comment by louispeel78** [comment]
i'm looking into looping but i only have access to a metronic 640g so my options are limited

**Comment by louispeel78** [comment]
@jamorham please keep us updated with the development of the Touchcare Slim. I am in the unfortunate position that the alert specially on the follow app do not always work and i have this on a 19 month baby so the notifications are important to me. Also is there any reading i can do which will allow me to use the android APS on the Medtrum 640G I can change GCM if needed. 
Many Thanks for all your work on this.

**Comment by markw3194** [comment]
@louispeel78 how are you getting on with the TCS? 
I’ve got a starter kit arriving tomorrow, but I’ve only found bad reviews about their previous CGM’s! 

Also, for anybody else reading it they’ve got a special offer on at the moment, £170 for a starter kit (transmitter+charger and 4 sensors)

**Comment by louispeel78** [comment]
@markw3194 I must have missed the special offer as i paid the full 225 for the kit. 
to be honest i was ok with it the first day, the second day readings were off by around 30mg/dl  by the time it came to calibrate. I have started calibrating twice a day and it seams to be within reason. i'm not happy with the interface and the alarms, I have the CGM on my 19 month son who sleeps in the next room and the follow app does not always give out the alarms. I do love the reading every two mins rather than waiting the full 5 mins. I am looking forward to getting back to xdrip + where at least i know the alarms are working. In all honesty i dont think in my eyes anything will match up to the dexcom G6 which we used for the first 3 months but i just cant afford it anymore.

**Comment by lawwolf78** [comment]
Good morning everyone. 

Did we have any update on this ? 
I am back to the medtrum until the freestyle 2 sensors arrive. 
must admit i'm not all that happy with medtrums new system. 
I am hoping that using xdrip might soften the blow a little, so really looking forward to this,

**Comment by gemmid81** [comment]
Hi I was wondering if anyone could help me. I have just set up my son's Medtrum cgm with xdrip and it is showing as lost on his handset. Does the use of xdrip mean that the information bypasses the handset? Thank you for any information 😊

**Comment by Navid200** [comment]
It seems support was added a long time ago.

If you have found this thread and have questions about how to use xDrip, please use the support channels:
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
