### ISSUE TITLE
Error after starting a new G6 sensor

### ISSUE THREAD

**Issue by ArkonPhoenix** [NightscoutFoundation/xDrip#507]
A few minutes after starting a new G6 sensor in the July 6 version of xDrip, you get an error that says unable to start G5 sensor. But when you swipe the error away and go to the xDrip app, it's still in warmup mode.

**Comment by jamorham** [comment]
I think this is fixed in the July 15th Nightly

**Comment by jamorham** [comment]
Marking as resolved
