### ISSUE TITLE
Noise Blocking error

### ISSUE THREAD

**Issue by winni67** [NightscoutFoundation/xDrip#508]
Hello,
when using the OB1 Collector with the G5 Native Algorithem (Data Source: G5 Native), then noisy values are not broadcasted to AndroidAPS. But with the setting „Fallback to xDrip“ then noisy values are broadcasted. This happens even, when the setting „Noise Blocking“ was set to „Block High noise and worse“. When using the xDrip internal G5 algorithm only (Data Source: DexcomG5), this noise blocking settings works very well.
I think this is an security issue.
I found this error in the Nightly Build 20180521-3534dc9 and it also happens in my current version 20180706-94e03a6.
After „Fallback to xDrip“ the shown noise in xDrip is for example 122 and the BG Original 131/BG Estimate 126. Then one minute after reading the new glucose value in xDrip, it is also shown in AndoridAPS. This happens one minute after the message form xDrip about „not broadcasting“ this value is shown.

**Comment by Navid200** [comment]
@winni67 Is this still a problem?  If not, would you please close this issue?
Thanks

**Comment by winni67** [comment]
I switched from G5 to G6, so I can‘t test this problem.
