### ISSUE TITLE
Miaomiao connected but no data received

### ISSUE THREAD

**Issue by Hornedar** [NightscoutFoundation/xDrip#509]
Hi there,

I recceived my Miaomiao reader  the last weeks and it connects easily to xDrip+ (xDrip-plus-20180709-73cfa6d) but there is not data transfered. At system status the Tomato Battery, Tomato Hardware, Tomato Firmware and Libre SN are empty and there are not glucose values available.

Now I tried the chinese tomato app and it establish a working connection. When I now run xDrip+ in parallel there are now also some readings available in xDrip+... I suppose, the requests of both programs have to be synced to get data to xDrip+.

In the system status now the following values are shown.

Field  | Value
------------ | -------------
Tomato Battery | 100
Tomato Hardware | 0001
Tomato Firmware | 0036
Libre SN | [11 digit serial number]

I tried different setting for the settings in xDrip+ but without any luck.

Did they change anything on the communication of the Miaomiao?

Here is the log with DexCollectionService:d as option set. The collector is restarted at 21:13 (Service stopped).

![log](https://user-images.githubusercontent.com/9384633/42727924-748d9dee-87af-11e8-85ef-a60c3bade40e.png)

I can also provide the sniffed BLE communication from the tomato app of the celluar phone if it's usefull.

**Comment by klettervirus** [comment]
I am having the same (similar) issue. My samsung s7 edge (oreo) can find the miaomiao via xdrip (bluetooth scan), connects and gives one to about five readings, then quits giving any readings. 
"Status" says it´s connected, no complaints in "BT Device", but no readings. When I do bluetooth scan at that time it does not see the miaomiao, but when I tap "forget device" it immediately sees and connects to miaomiao, transmitting about one reading.

I was watching #440 where the issue seems to be connecting to the miaomiao at all. I have played with the BT settings to no avail, but I fear I have messed them all up. Can I reset them to default? Or what else could be the cause of this funny behaviour?

**Comment by Tapiocapioca** [comment]
I have the same problem. Me also S7 Edge with Oreo.

**Comment by klettervirus** [comment]
OK, I have found the solution to my Problem: I managed to install the "libreOOPAlgorithm" to make the values shown match the readings of the libre-handheld more closely. While that worked quite well it obviously messed up the connection with my miaomiao. After deactivating the libreOOPAlgorithm it went back to work! So whoever has similar problems, check for that too!

**Comment by Tapiocapioca** [comment]
I think you found the problem, me also have libreOOPAlgorithm, I will try to follow your solution!

**Comment by Hornedar** [comment]
I did not install or use the libreOOPAlgorithm and I think my problem is different:
xDrip+ finds the miaomiao and connects to it. 
The DexCollectionService gives entries in the error list (different to log in the screenshot above): "Failed to discover services!", "Got null pointer trying to set CCCD descriptor", "Error: mCharacteristic was null in sentBtMessage", "Error writing characteristic" (e.g. ...F0, ...D105), and lots of "Stale data so requesting backfill".
If I now start the tomato app in parallel on the same phone (BQ Aquarius with Android 7.1.1), xDrip+ receives data. I assume, it's the result of the tomato app requesting the data and xDrip+ receiving it in parallel to the tomato app.

**Comment by tzachi-dar** [comment]
I think that the issue can come from 2 things:
1) the tomato is not connected well to the sensor.
2) A problem with oop algorithm.

#2 can be checked easily by going to settings->less common seting->other misc options, disable oop algorithm.
I'll be very happy if someone who has the issue will connect the phone to the computer and run
adb logcat > file.

Then upload the file, this will help me debug the issue.

**Comment by Hornedar** [comment]
I will upload the file today evening. Thanks for your help!

**Comment by Hornedar** [comment]
Here is the logfile as requested. The SSIDs of the wifi networks were removed from the logfile.

At first only xDrip+ is running. The cache and data was cleared before the restart of the celluar phone. The settings were done with the connection wizard. After 5 minutes and the first reconnect, no data was received. Then I started the tomato app (timestamp roughly 21:14) in parallel and both apps were receiving data after some minutes. After that also the battery status, hardware and software version and Libre SN is filled in the xDrip+ system status.

[logfile_xdrip_tomato-app.log](https://github.com/NightscoutFoundation/xDrip/files/2207137/logfile_xdrip_tomato-app.log)

xDrip+ only running:
![screenshot_20180718-211118](https://user-images.githubusercontent.com/9384633/42904189-86df1e32-8ad4-11e8-96b7-f7e367642598.png)
![screenshot_20180718-211122](https://user-images.githubusercontent.com/9384633/42904197-88e3ad88-8ad4-11e8-987e-fe9d250e60ac.png)

xDrip+ and tomato app running in parallel:
![screenshot_20180718-211410](https://user-images.githubusercontent.com/9384633/42904198-8a2e88fc-8ad4-11e8-93c2-af874e165254.png)
![screenshot_20180718-211414](https://user-images.githubusercontent.com/9384633/42904199-8b9d11b8-8ad4-11e8-86c8-a4b14dc507ed.png)

OOP algorithm is disabled:
![screenshot_20180718-213604](https://user-images.githubusercontent.com/9384633/42904241-ad142368-8ad4-11e8-93ae-18439d6e1902.png)

**Comment by Hornedar** [comment]
Hi there,

sorry for the late response, I was on vacation.

There is no data received with and without OOP activated. The log above was done without OOP enabled.

Attached to this post you find the btsnoop_hci.log. The following tasks were done at the approximated timestamps.


0.000 | btsnoop.log started
-- | --
0.000 | xDrip+: started
22.642 | xDrip+: configured
67.014 | xDrip+: connection established
426.735 | xDrip+: wake up
535.244 | xDrip+: restart collector with polling mode
568.979 | Tomato:  app started
587.712 | Tomato:  logged in
683.189 | Tomato:  update installation done
715.500 | Tomato: first readings aquired
715.500 | xDrip+: first readings aquired

Perhaps someone can judge or debug the differences in the communication of the xDrip+ and the tomato app.

[btsnoop_hci.log](https://github.com/NightscoutFoundation/xDrip/files/2315439/btsnoop_hci.log)

**Comment by SpeedoPasanen** [comment]
My P20 pro stopped connecting to miaomiao after an android update / reboot. Nothing seemed to work - reset miamiao, reboot phone several times, forget and re-search BT device,... Then I installed Tomato and bound to miaomiao using that. Instantly works, somehow xdrip piggybacks the connection made by tomato?

Error i saw in the log was "Task Deadlock on: sendData" (if that's an error...)

**Comment by comflow** [comment]
Same problem arised here. The auto-disable functionality of my Samsung Galaxy S8 disabled, i.e. put to sleep, the libreOOPalgorithm app, causing xDrip to no longer receive readings. 
Solved it by either: 
- disabling OOP in xDrip
- restarting the libreOOPalgorithm app

**Comment by Stuggesjoerd** [comment]
> Hi there,
> 
> sorry for the late response, I was on vacation.
> 
> There is no data received with and without OOP activated. The log above was done without OOP enabled.
> 
> Attached to this post you find the btsnoop_hci.log with the xDrip+ version [55dcd85](https://github.com/NightscoutFoundation/xDrip/commit/55dcd855a709d12ec6c2a68906183da276061525)-2018.08.21 (currrent nightly build) used. The following tasks were done at the approximated timestamps.
> 
> 0.000	btsnoop.log started
> 0.000	xDrip+: started
> 22.642	xDrip+: configured
> 67.014	xDrip+: connection established
> 426.735	xDrip+: wake up
> 535.244	xDrip+: restart collector with polling mode
> 568.979	Tomato:  app started
> 587.712	Tomato:  logged in
> 683.189	Tomato:  update installation done
> 715.500	Tomato: first readings aquired
> 715.500	xDrip+: first readings aquired
> Perhaps someone can judge or debug the differences in the communication of the xDrip+ and the tomato app.
> 
> [btsnoop_hci.log](https://github.com/NightscoutFoundation/xDrip/files/2315439/btsnoop_hci.log)

Any updates on this so far?

**Comment by bolattleubayev** [comment]
Hey there! I just had the same issue, wanted to share what helped me, maybe it will help someone else too

We have set up a new Libre sensor, set up a bunch of calibrations (did not remove previous) at this point. Then after one more calibration my phone (Huawei P20 Lite) in Bluetooth Scan could find the miaomiao, however on the main screen there was a little gray bubble at the bottom "Sensor clock signal missing" or something like this and no updates. Also, the difference between the actual measured value and the one shown on screen was big (9.0 mmol/l and 4.5 mmol/l respectively)

Following advices in this thread I checked OOP status, it was off. Then we restarted the miaomiao manually (using little button in the hole) and reset all previous calibrations (I suspect this was the step that fixed it).

After that all was fine

**Comment by Navid200** [comment]
@Hornedar Would you please close this issue if your problem has been resolved?
You can use the support channels to find out what other users do in a similar situation.  
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
If you have done and this problem persists, please update.
Thanks

**Comment by Hornedar** [comment]
This issue has not been solved. After changing to the Libre 2 sensor I'm not using the MioaMioa reader any more. Therefor this issue will be closed.
