### ISSUE TITLE
UI Legend or Explanation

### ISSUE THREAD

**Issue by BigWebstas** [NightscoutFoundation/xDrip#515]
I tried searching everywhere for this but i cannot find a decent document, guide or Wiki article that covers all the Lines, Colors, and Icons that are on the Watch UI and the Phone UI

![image](https://user-images.githubusercontent.com/2896329/43025015-662a9cfc-8c2d-11e8-8067-5751cf5a3ebc.png)
Like the above image, what is this icon?

![image](https://user-images.githubusercontent.com/2896329/43025140-d83ee992-8c2d-11e8-8f86-6c30e0b0d405.png)
Or like what is this purple background area or this blue line? 

Im sorry if its out there in the ether and i over looked it

**Comment by Navid200** [comment]
@BigWebstas Would you please close this issue if your answers have already been answered?
You can also post in the xDrip facebook support group.
https://www.facebook.com/groups/xDripG5
Thanks

**Comment by Navid200** [comment]
Most of what you are looking for, if not all, can be found at the following.
Settings -> xDrip+ Display Settings -> xDrip+ Color Settings

Would you please have a look.  Please let me know if any particular item is missing.
We can always reopen this if needed.
