### ISSUE TITLE
tizen collectors?

### ISSUE THREAD

**Issue by Mr-Enigma** [NightscoutFoundation/xDrip#516]
is it possible at all for tizen watches to act as standalone collectors?

**Comment by castdoom** [comment]
yeah i know there is only one for android wear, i was just wondering if there are limitations to tizen to prevent a small collector app that works on tizen

**Comment by Lizzy74** [comment]
Will xdrip work on a tic watch?

**Comment by ralf-ms** [comment]
yes, it works on a tic watch (I tried the tic watch s with the miaomiao transmitter).

**Comment by dustin-lennon** [comment]
Right now, I am just using the wearable widget on my Samsung Frontier S3. Would be nice to have a tizen collector

**Comment by Tesummerill** [comment]
Wearable Widgets works very well getting the info on my s3

**Comment by castdoom** [comment]
yeah i have WW too, it does work to just display what my phone is collecting but a standalone collector app sim to the android wear one would be alot better. i know there are limitations to tizen that android wear doesnt have which may prevent a tizen app being functional like the wear one is...

**Comment by ronrosenbaum** [comment]
I don't have a Tizen watch but might want one.  With wear widgets are you able to display your BG readings on the Samsung Gear watch faces all the time?  I mainly want to be able to easily glance at my BG readings all the time.

**Comment by dustin-lennon** [comment]
The WW does have widget you can add, but nothing that will take the place of the watch face all the time.

**Comment by arty-name** [comment]
@ronrosenbaum, [I have described my approach for that in the other ticket](https://github.com/NightscoutFoundation/xDrip/issues/460#issuecomment-429366367)

**Comment by Navid200** [comment]
@Mr-Enigma Would you please close this issue if your question has been answered already?
If not, would you please use the support channels for asking questioons?
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks
