### ISSUE TITLE
Android Wear complications display null using native algorithm

### ISSUE THREAD

**Issue by browncoatdave** [NightscoutFoundation/xDrip#517]
The watch face displays bg values correctly, and when using xdrip algorithm with g5 values displayed properly on complication.  Now using G6 and native, complication displays null.

**Comment by browncoatdave** [comment]
Using 7/21 nightly on wear 2.0, pixel 2 xl 9.0 beta.

**Comment by jamorham** [comment]
A fix for this is in the works

**Comment by cwpeterson** [comment]
Going to throw a "me too" out there. I had no issues with this until I switched to G6 and the nightly build this week.

**Comment by jamorham** [comment]
Please try the July 26th nightly, it should address this and also enable syncing of back-filled data.

If you are using a Wear 2.0 device then remember you need to uninstall and reinstall the wear app because it doesn't automatically update.

**Comment by browncoatdave** [comment]
7/26 is working.  Thank you!

**Comment by cwpeterson** [comment]
Confirmed, the complication is now working on my Moto 360 2nd Gen. Thanks for your efforts!

**Comment by cwpeterson** [comment]
One question, where is the syncing of back-filled data option at?

**Comment by jamorham** [comment]
Marking as resolved.

**Comment by jamorham** [comment]
@cwpeterson its not an option, if you're using the native algorithm then the data will be back-filled and (now) synced properly.
