### ISSUE TITLE
xDrip without Play Services

### ISSUE THREAD

**Issue by malloy139** [NightscoutFoundation/xDrip#519]
Hello,

i use a Android phone without Google Play Services installed as a follower.
Sending the measurements from the Master to the influydb works, but I get no readings on the follower. Shouldn't it download them from the influxdb, or does this only work via the Play Services?

**Comment by tzachi-dar** [comment]
I think that what you should do is this:
Create a nightscout site and upload data there.

Than on follower phone install nightscout client and set xdrip to receive data from it.
This should allow getting bg data to work.

**Comment by malloy139** [comment]
I'm closing this issue because xDrip now works with microG implementation.

**Comment by tolot27** [comment]
@malloy139 That's good to know and something to add to the feature list. Did you test it intensively?

**Comment by malloy139** [comment]
> @malloy139 That's good to know and something to add to the feature list. Did you test it intensively?

I use it as follower since half a year now and it works well.
Can't say anything about master.
