### ISSUE TITLE
values completely off

### ISSUE THREAD

**Issue by jo1st** [NightscoutFoundation/xDrip#521]
I recently switched from blucon to miao miao. I'm using it with a Libra sensor and the nightly version from July 7th of Xdrip. After having to reset the app because of missed readings now all the sudden all the readings of way off compared to the finger pricking sometimes even 40 units difference which it never happened in the past. xdrip is always being very very precise most of the time I don't know what's happening and I was wondering if somebody can suggest a solution to this. I. I'm attaching a screenshot of calibration and version. A difference of about 10 units it's usually not a big deal but 40 it is so please help[
![screenshot_20180725-002840_xdrip](https://user-images.githubusercontent.com/36887391/43149921-a719840c-8fa3-11e8-8d72-3a3bcc10af25.jpg)
![screenshot_20180725-002823_xdrip](https://user-images.githubusercontent.com/36887391/43149922-a74f20ee-8fa3-11e8-8197-0dd13ad9daac.jpg)

](url)

**Comment by Kywalh** [comment]
Stupid question from me... Do you calibrate when BG is almost stable ?

**Comment by jo1st** [comment]
I calibrate under different scenario, every 12 hours with the alarm but after all this discrepancy lately I'm trying to calibrate a little more often here and there. the last calibration was last night around bed time. bg reported by xdrip 158, actual with finger prick 118. Please anyone tell me something that I don't know to make this work better. Too much of a discrepancy

**Comment by jamorham** [comment]
Broadly your calibration chart shows that there is a significant variance both +- between your finger stick tests and and the raw value. This could indicate a noisy sensor. You can try enabling Datricsae calibration plugin from advanced calibration and see if that produces better results. It uses a different weighting mechanism.

Personally I tend to calibrate only if the value is off and then I use the finger-stick value entry via the treatment editor and automated calibration.

**Comment by jo1st** [comment]
Thank you Jon, I did enabled Datricsae calibration plugin, I will let you know what happens.

Regarding: _**I use the finger-stick value entry via the treatment editor and automated calibration.**_

What do you mean about that, can you tell me how to do that???

**Comment by jo1st** [comment]
Jon, finger bg still not matching xdrip. Also after calibration, 30 levels difference between xdrip and my blood test when I enter the value in xdrip the value in xdrip doesn't change more than one or two units only. I remember in the past when I calibrate xdrip it will adjust itself properly

**Comment by Navid200** [comment]
@jo1st Would you please close this issue if it has been resolved?
If not, you can use the support channels.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks
