### ISSUE TITLE
Export data???

### ISSUE THREAD

**Issue by Xana-53** [NightscoutFoundation/xDrip#524]
Buongiorno,
sono un nuovo utilizzatore di Xdrip, ma come faccio ad esportare i dati presenti in xdrip?
Grazie

**Comment by jamorham** [comment]
Usa il menu di esportazione dal menu 3 punti in alto a destra della schermata iniziale. Tradotto con google traduttore.

**Comment by jamorham** [comment]
Marked as resolved
