### ISSUE TITLE
Export (Sidiary-Format) - Type mismatch

### ISSUE THREAD

**Issue by jroth-haj** [NightscoutFoundation/xDrip#528]
Because of Line Feed in Remark, the exported csv isn't usable as Sidiary import file.
It gives a type mismatch.

Example:

11.07.2018;17:41;;;;;LowReservoir 722 
12.07.2018;00:19;;;;;ChangeTime 722 
12.07.2018;10:02;;;;;Rewind 722 
12.07.2018;10:04;;;;;Prime 722 
12.07.2018;10:05;;;;;Prime 722 
12.07.2018;15:17;;;;;NewTimeSet 722 
12.07.2018;15:17;;;;;ChangeTime 722 
12.07.2018;23:32;;;;;Battery 722 
12.07.2018;23:33;;;;;Battery 722 
12.07.2018;23:33;;;;;ClearAlarm 722 
12.07.2018;23:33;;;40;3.6;Normal bolus with wizard.
Calculated IOB: 6.554
Programmed bolus 3.6
Delivered bolus 3.6
Percent delivered:  100%
Food estimate 3.6
Correction estimate 0
Bolus estimate 3.6
Target low 120
Target high 120
Hypothetical glucose delta -216
13.07.2018;00:51;;;50;4.5;Normal bolus with wizard.
Calculated IOB: 7.008
Programmed bolus 4.5
Delivered bolus 4.5
Percent delivered:  100%
Food estimate 4.5
Correction estimate 0
Bolus estimate 4.5
Target low 120
Target high 120
Hypothetical glucose delta -270
14.07.2018;01:00;;;20;;

**Comment by MasterPlexus** [comment]
Will check that soon.

**Comment by jroth-haj** [comment]
Any News?
How can I support you?

**Comment by MasterPlexus** [comment]
I have to implement the escaped linefeed (very special chars ||) for the export. Unfortunately my developing system is need to setup new, so I'll need one or two days.

**Comment by MasterPlexus** [comment]
Made a Pull request, which works for me.Sorry as it needs more Time as expected.
https://github.com/NightscoutFoundation/xDrip/pull/561

**Comment by jroth-haj** [comment]
Thanks for the bugfixing.
I tested it with the last nightly today.
