### ISSUE TITLE
Clarity?

### ISSUE THREAD

**Issue by bpollina** [NightscoutFoundation/xDrip#529]
My endocrinologist requires dexcom clarity when I visit and when I call for help. I see there is an option to log into clarity but can't get it to work? what's the 10 digit serial # it keeps asking for?

**Comment by doc77** [comment]
You need to get that from Dexcom.

**Comment by bpollina** [comment]
I was getting clarity and share confused. any word on clarity integration?

**Comment by doc77** [comment]
From what I understand it is a very difficult project because of how Dexcom has Clarity locked down. It could take awhile to find the key.
