### ISSUE TITLE
Upload G5 battery stats to NS device status

### ISSUE THREAD

**Issue by zjedr** [NightscoutFoundation/xDrip#530]
Currently G5 battery stats are culled daily.
Could we get them uploaded to NS before they are culled so they can be reported/analysed.

**Comment by jwoglom** [comment]
I've been hoping for this too, so I can do some graphing/analytics on how long transmitters last. Check out PR https://github.com/NightscoutFoundation/xDrip/pull/584

**Comment by Navid200** [comment]
This would be very useful
