### ISSUE TITLE
Doses of insulins

### ISSUE THREAD

**Issue by calimerofr59** [NightscoutFoundation/xDrip#531]
Hello, I would like to know how to enter the doses of fast insulins and doses of insulins slow in Xdrip+ because with Xdrip when I click in the top right on the syringe there is no distinction between the two, we can enter that a kind of insulin. Thanks for your answer

**Comment by doc77** [comment]
There is no distinction. What you can do is make a note to say what kind of insulin was taken, but there is no way to directly attach the note to the injection.

Many have asked about distinguishing basal and bolus, but it has never been added.

**Comment by calimerofr59** [comment]
OK thanks a lot. Indeed it's a pity not to be able to distinguish them given their different duration of action on blood glucose. Have a good day

**Comment by k2s** [comment]
seams that this will be fixed by #718

**Comment by Navid200** [comment]
@calimerofr59 Is this still missing?
Would you please update?
Thanks

**Comment by Navid200** [comment]
The capability to use multiple insulin types exists.
Please see
Settings -> xDrip+ Predictive Simulation -> Multiple Insulin Types

I am closing this issue.  Please let me know if you think it should remain open.
