### ISSUE TITLE
Additional condition (BG > x for rising, BG < y for falling) for BG rising/falling alarms (Feature request)

### ISSUE THREAD

**Issue by dideldum** [NightscoutFoundation/xDrip#532]
I like the BG rising/falling alarms, but they don't make sense always.

A BG falling alarm, when I come done from 250 due to a correction, is not interesting at all. But when I'm below, let's say 140-150, and BG falling applies, I'm VERY interested to prevent an upcoming hypo early.

Vice versa, if BG rising applies after a hypo, when I have taken fast carbs to rise again, this BG rising alarm is completely useless. But when I'm above 150-180, then the BG rising should indeed alarm me!

So I would like to have additional conditions for BG rising (only when > x) and BG falling (only when < y).

Would that be possible?

**Comment by Navid200** [comment]
Duplicate:
https://github.com/NightscoutFoundation/xDrip/issues/311
