### ISSUE TITLE
Setup text - need to make it less

### ISSUE THREAD

**Issue by exceter** [NightscoutFoundation/xDrip#536]
on Q1 Pro i am able to install only January 2018 version, later versions (alfa, beta) a not able to install due to long text, it is just not reaching last lines.
I think this issue is for all small display devices

**Comment by jamorham** [comment]
What kinds of text are you referring to?

**Comment by exceter** [comment]
When you want to update the below text appears:
"Do you want to install an update to this existing application? Your existing data will not be lost. It does not require any special access."

not able to click "Install", due to small screen size. By now only solution is to remove existing and install fresh.

**Comment by Navid200** [comment]
@exceter Is this still the case now?
Thanks

**Comment by Navid200** [comment]
Please update status before reopening.
