### ISSUE TITLE
Another finding related to calibration 

### ISSUE THREAD

**Issue by jweismann** [NightscoutFoundation/xDrip#538]
With the preemptive restart for G5, I noticed a couple of times that I can calibrate with the right-hand side menu (finger, carbs, insulin and time) but not with the left-hand side menu where there is a point called Add Calibration (but it was in its Cannot Calibrate state). I have seen the two ways of sharing calibrations values operate inconsistently and I wonder if it would be better to have only one way of doing things. It's not clear to me if they are indeed supposed to operate differently (and if so, what the recommended way to calibrate is). 

A third issue that I noticed with calibrations is if one undo a calibration then it disappears and one cannot redo it due to time diff but really isn't it already passed onto the G5 so there is no way that one can undo it or ? If this is indeed the case, then maybe one shouldn't be allowed to undo measurements that have led to G5 calibrations. 

Hope this is useful to you. Thanks again for a great app.

**Comment by jweismann** [comment]
Hi. I just caught a situation similar to the first situations tonight and have shared the logs with you. The master received a calibration that the sensor rejected. When trying to force the calibration on the master phone I could not enter it via the left-hand side main menu but I could on the right hand side menu (finger, carbs, insulin and time) and when doing it via the right hand side it was also accepted by the sensor. I don't understand why the semantics differs, i.e. why it will take it from one menu but not from another.

I have tagged the logs send with #538.

Thanks

**Comment by Navid200** [comment]
@jwedding Would you please close this issue if you have found answers?
If not, you can use the support channels.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks

**Comment by jweismann** [comment]
closed
