### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by jweismann** [NightscoutFoundation/xDrip#539]
Would it be possible to allow treatment uploads only to nightscout but no sensor data. We have several phones that are configured as xDrip-Follower that we use to input treatments that we want to have uploaded but we don't need additional copies of the CGM entries from these devices, i.e. it would be cool if one could skip CGM uploads to NS similar to what one can already do for treatments and bridge battery and then only have the treatments uploaded from these devices. Maybe there is a way to accomplish this today that I'm just not aware off.

Thanks.

**Comment by doc77** [comment]
Treatments are automatically shared from the follower to the master. Every bit of data on any follower is uploaded to the master.

Why don't you just do your NS upload from the master?

**Comment by jweismann** [comment]
Maybe I have simply misunderstood current implementation. I have configured each of the
xDrip-Follower phones with a cloud upload setting that have Nightscout Sync (Rest-api)
configured with the Base URL being the same as the one used by ns-client to feed
local xDrip-Follower, but are you saying that I don't need to do this? That the
xDrip-Follower will feed the NS site via the local ns-client and the local xdrip itself
does not have to have any URL knowledge about the NS site. If this is indeed the case 
then I will close this issue.

**Comment by doc77** [comment]
Yes. You only need the xDrip+ master feeding to NS. Entries made on the follower phones are synced with the master immediately, regardless of their proximity.

**Comment by jweismann** [comment]
Excellent!!! Thank you so much for the clarification.

**Comment by jamorham** [comment]
I believe you can have the Nightscout upload on any follower or the master (recommended). If you put it on more than one handset then you're really testing xDrip's de-duplication facilities to the maximum as you have the greatest chance for a feedback loop as xDrip can both upload and download from Nightscout and also syncs everything between masters and followers as well.

**Comment by jweismann** [comment]
Great input, @doc77 and @jamorham. To summarize and pose an follow up question: Let S be the transmitter, M the master xdrip phone that has S as its Hardware data source. Let F1 and F2 be followers to M, i.e. they get "entries" from M. Let T be sources of treatments (here both M, F1 and F2 may enter treatments - think of it as patient and two care-givers). Finally let NS be a nightscout site where all data is collected. In simple drawings the great suggestion is to go from:

             F1+T --> NS
S --> M+T -------> NS
             F2+T --> NS

into a setup like the one shown below where only one device, namely the master M, uploads to NS:

        M  <-- F1+T
S --> M  -------> NS
         M  <-- F2+T

That is, one Master that gets "entries" from S and additional "treatments" from F1, F2 and all "entries" and all "treatments" will get uploaded to NS via M. Neither F1 nor F2 will have any local nightscout syncs (rest-api) settings activated. The question relates to how F1 and F2 should communicate with M.

Question: Today I have F1 and F2 set as followers via AndroidAPS NSclient - is this the recommended way to setup followers nowadays or should I rather have F1 and F2 set as followers via the xdrip Follower handset settings? I would be most grateful if you could shed some light on the pros and cons here.

**Comment by shafiro** [comment]
I hope it is OK to ask here ?

I am following my son's phone (which is the master), but my phone is feeding to NS. Treatments entered on my phone are uploaded to NS. Treatments entered on my son's phone, are synced to mine, but are not being uploaded. Why?
