### ISSUE TITLE
Wiki - process description for translation

### ISSUE THREAD

**Issue by Kywalh** [NightscoutFoundation/xDrip#541]
Hello
I started to do translation in French and I already submitted a couple of them.
I gave my email address but I don't know what is the next step ?

Thanks

**Comment by themotoden** [comment]
I can translate to Russian, but how can I use my translated version? Please, add option for this

**Comment by tolot27** [comment]
@Kywalh I did not find you at [crowdin](https://crowdin.com/project/xdrip) and do not understand what you mean by "I already submitted a couple of them."

@themotoden I accept your join request at crowdin. You are now able to suggest translations.

**Comment by Navid200** [comment]
Is this still an issue?
Or, can we close it?

**Comment by tolot27** [comment]
We still don't have a documentation describing the translation process.

**Comment by Navid200** [comment]
@tolot27 With respect to documentation, can we not have a link to crowdin in Wiki?
And then, you can add any detail documentation under discussions as a post pinned to the top, no?

Can we close this issue?

**Comment by tolot27** [comment]
Better, someone creates a PR against [CONTRIBUTING.md](https://github.com/NightscoutFoundation/xDrip/blob/master/CONTRIBUTING.md). Mayb you can do this?

We close this issue as soon as it is fixed/implemented. Linking it to a PR will close it automatically, if the PR gets merged.

**Comment by tolot27** [comment]
> Do I understand you correctly that you are suggesting that I submit a pull request to change https://github.com/NightscoutFoundation/xDrip/blob/master/CONTRIBUTING.md to include how translators can submit their translations?

Yes, you or someone else. This is a simple task which does not need developer skills. The PR should briefly describe the translation process (Crowdin account, translation, approval, automatic merging to https://github.com/jamorham/xDrip-plus/tree/l10n_master7 and final merging to xDrip by jamorham) and link to the Crowdin project and Crowdin manual.
