### ISSUE TITLE
insert today

### ISSUE THREAD

**Issue by castdoom** [NightscoutFoundation/xDrip#544]
hi, i put on a new sensor and activated it around 6pm, i waited till i was going to sleep after 1am to put my miomio on and connect it up to xdrip.

the issue is it popped up was it inserted today, well its been less than 24 hours and i know the libre has kinda a warm up time so i pressed yes, selected 6pm then i got a error that its in the future?...

**Comment by jamorham** [comment]
The date/day changes at midnight.

**Comment by jamorham** [comment]
Just answer the question of when sensor inserted with the details of when it was inserted. For Libre it will make little difference but if you tell it yesterday then it knows its not within the warmup period and thats all it needs to know and wont ask for a time. With dex we try to be more specific with exactly when the sensor was inserted as this can affect some calculations.
