### ISSUE TITLE
Changes of insulin duration affeccted only after reboot?

### ISSUE THREAD

**Issue by andreascarsetto** [NightscoutFoundation/xDrip#545]
I took care that that a change of the insulin duration (Settings  > xDrip+ Predictive Simulation settings > Low level prediction values > Insulin duration) is received only after the phone is restarted. Surely there are bigger problems to solve. It would be enough to report it on the label that the modification will work after the restart

**Comment by Navid200** [comment]
I think any setting you change, not just insulin-related, requires that you restart the phone.  You are better off doing that always.
I agree that what I just typed should be in documentation.
But, I don't think we are going to add a note to every setting that you need to restart after an update.
I am going to add the label to document as a reminder.
