### ISSUE TITLE
Pebble trend watchface problems with xDrip+ 

### ISSUE THREAD

**Issue by zjedr** [NightscoutFoundation/xDrip#55]
Since changing to xDrip+ about a month ago, I have found the packaged 'Color Trend Watchface' goes into a mode where the following problems occur :-

- the watch doesn’t process/vibrate for any alerts coming from xDrip+ (via Notification Center).
- pressing any righthand side button causes the watchface to load again, pressing button again causes the watchface to crash.
- ‘timeago’ is missing from the watchface, not sure if this is a cause or consequence. 

I can see it is in this mode when the ‘timeago’ is missing, all other controls are still updating as usual (bg,trendline, delta,etc.)
Watchface goes into this mode about once or twice a day, usually overnight, I can’t identify what’s causing it to go into this mode. Atm, I’m not using the watchface overnight as I rely on the pebble vibrations for my BG alerts. Alerts work when I swap to a non xDrip watchface, even after it goes into this mode. 
Once in this mode, it can be difficult to get it running normally again, I often have to reboot phone and reinstall watchface from xDrip+ settings. 
Hardware/software:-
-	Samsung S5 with android 5.0
-	Pebble time steel running v4.3
-	xDrip+ latest beta with G4 via xBridge wixel
-	I use ‘Notification Center’ to provide an extended vibration pattern for xDrip alerts.
Any help resolving this would be appreciated.

**Comment by jamorham** [comment]
Hi, thanks for a detailed problem report.

I am assuming you are running the Nov 24th version of xDrip+ Can you please go in to update settings and switch to the `Nightly` channel and apply the latest update. To get `Nightly` you first switch to `Alpha` in `Settings` -> `xDrip+ Update Settings` -> `Update Channel` then exit settings and go back in and it will then allow you to select `Nightly`.

Once you have this version installed, toggle the Pebble support so it offers to reinstall the watchface. Allow it to reinstall the watchface and please let me know if you get the issue reoccur with that. For good measure if you could shutdown and restart your pebble after installing the watchface so we can be sure any possible memory corruptions are cleared out.

Thanks.

**Comment by jamorham** [comment]
Please let me know if this resolves the issue. Thanks

**Comment by zjedr** [comment]
Too easy, I have run the new release for a couple of nights now without any problems. I love it when an issue is solved before report it, fantastic. There are many of us T1s out here who really appreciate all the hard work and many hours you put into these products, keep up the great work.
