### ISSUE TITLE
Bridge battery disconnects

### ISSUE THREAD

**Issue by zshh** [NightscoutFoundation/xDrip#550]
Hi,

What is the deal with bridge battery? We are using blucon and battery normally lasts for 1 week. This has started happening in last few months on nightly versions where bridge battery warnings are randomly pop-ing up and every time it does xdrip stop reading glucose values and app has to be restarted. VERY annoying. Now it complaints on batteries changed in blucon after like 6 hours or so.
Battery is fine and I have validated by measuring the voltage.

Is it possible just to disable battery "monitoring" all together? Not just the visual/text warning but just make xdrip ignore the battery thing all together and stop messing with my readings?

Thanks

**Comment by gregorybel** [comment]
I wouldn't disable it but rather fix issue or accept it.

I saw it one time too, it seems Blucon stores the battery low Info and even after a battery change and it takes a while until battery status is correct again.

Other assumption, we have a bug in relation with persistent storage. I see also that sensor age after sensor exchange keeps wrong a few hours.

@jamorham, any thoughts?

**Comment by zshh** [comment]
@gregorybel 
I get what you are saying, obviously fixing it would be optimal. 
However from my (caregiver) perspective it creates stress. We got Blucon and xdrip to lessen the burden of waking up 4-5 times during the night to check BS, have alarms and be able to calibrate values for our daughter, but nowdays we get "missed connection" alerts several times per day and always it's battery bridge issue, so it becomes frustrating.

What I ment by disabling it, is to have an option in the app itself which I can toggle.

**Comment by gregorybel** [comment]
settings / Alarm / extra Alarms / collector battery alert?

but if after a few hours after changing battery you get battery low then you might change battery type, you should one from Sony.

**Comment by Navid200** [comment]
@zshh Is this still an issue?
