### ISSUE TITLE
G5 Start Failed message

### ISSUE THREAD

**Issue by cwpeterson** [NightscoutFoundation/xDrip#551]
I am using the new G6 sensors. I'm on my 3rd sensor, the first had issues and failed within a couple days, had to get a replacement from Dexcom. The second worked for about 13 days before I started seeing a lot of noise. I changed it this morning and less than 30 minutes after changing it, a message popped up stating: 

G5 Start Failed Session Start Failed: Unknown code: 6. 

I saw this on the last 2 sensors also.

After the 2 hour warm up, I did get a reading and things seem to be going fine. Is this just an erroneous error message?

I've attached a screenshot of the error message.

I can't tap on the message, only swipe it away.

![screenshot_20180816-092048](https://user-images.githubusercontent.com/12939749/44214996-00977800-a137-11e8-9768-fb7aefacdc36.png)

**Comment by jamorham** [comment]
Which xDrip version is this with?

**Comment by cwpeterson** [comment]
Sorry, I meant to post that. Running the 8-7 nightly. The first time I used a G6 was with a previous build. Right now everything has been solid and stable. Just that message popped up about 20 or so minutes into the sensor.

**Comment by Navid200** [comment]
@cwpeterson If you are not having this problem any longer, would you please close this issue?
Thanks
