### ISSUE TITLE
Speak Readings>"Or per number of minutes" text is too large

### ISSUE THREAD

**Issue by dave1812** [NightscoutFoundation/xDrip#553]
doesn't match other text on that page and therefore I can't see the current setting (number of minutes).  That line and the line of text above it is out of proportion to all other text.

If you fix THIS issue, but don't fix the issue I posted about 5-6 days ago, I won't be able to use the fixed version as I won't get data on my Gear 2.

**Comment by jamorham** [comment]
Can you provide a screenshot to illustrate the problem? Thanks.

**Comment by dave1812** [comment]
Here u go...

**Comment by dave1812** [comment]
I sent the screenshot via email but I don't see it here on get hub. I hope you have it somewhere. Please let me know if you don't. Thank you

**Comment by jamorham** [comment]
You need to drop it in on the github website

**Comment by dave1812** [comment]
![screenshot_20180819-062740_xdrip](https://user-images.githubusercontent.com/37376075/44314492-b7615580-a3ce-11e8-952c-0f3191b4655e.jpg)

**Comment by dave1812** [comment]
See how large the font is for those first few items?  Way larger than the following items, and therefore I can't see the current number of minutes that I've selected.

**Comment by dave1812** [comment]
16 days and not a peep from anyone on the dev team??   Hello??

**Comment by dave1812** [comment]
ah, thanks for the explanation.  if the text size is fixed in a daily release, will anyone be updating this thread?

**Comment by MasterPlexus** [comment]
Normally yes.

**Comment by yosepito** [comment]
@jamorham & colleagues
An additional feature of this section: I use xdrip while biking. To me, is quite important to know how much it raises/decreases, and not only the label of the trend (slight up/down...). The possibility that one can select between xdrip speaking aloud the number of the delta or the text label would be a nice improvement. I don't know how to do this in the code. Anyone else see this feature as interesting for having a "normal" life?
Sorry, but I don't know how to use the "pull request" feature of this site
thanks!

**Comment by increddibelly** [comment]
this looks like something I could to to get into the xDrip code. I can confirm the symptoms on my phone, that's something. *forked*

**Comment by MasterPlexus** [comment]
At the moment I'm not complete clear on that. If you add android:textSize="5sp" in pref_advanced_settings.xml to all SeekBarPreference's, the size will be fine on my phone. But I'm pretty sure that this is not the usual way to set the font size in relation to the rest of all preference entrys. I would expect that Resources should be set for that, but I did not see any other font-Settings up to now... @jamorham, is there a general setting for Fontsize of the Prefs, where maybe the SeekBar should be included?

**Comment by jamorham** [comment]
Adding a `textSize` element to the `SeekBarPreference` definition in the xml makes no difference to size on my phone (sony android 6)

I think it has to be done with a custom layout for `SeekBarPreference` which I think has a `layout` xml parameter. When I tried this recently I got a crash I couldn't determine the source of and haven't pursued it further.

**Comment by MasterPlexus** [comment]
Mysteriuos... Which value you given in the `SeekBarPreference` ? I was not sure that `android:textSize="5sp"` is right, but with that value it was rendered right on my Androidemulator...

Did you have your try with `Layout xml` as a patch? Then I would try to investigate that further, as I think it is better to use it in that standard approach.
