### ISSUE TITLE
No sync with Pendiq in background

### ISSUE THREAD

**Issue by IgnisAsphodel** [NightscoutFoundation/xDrip#554]
Hi!

We have one of the last nightly builds and Pendinq pen. Pen set to BT always on.
xDrip and pen syncs only when we open xDrip main window.
Is there any way to change sync procedure? 
Right now xDrip retrive data from pen in 10-15 seconds after opening, can you add another one sync in 10 minutes? Also it may be 30-minutes period of silence after last sync with new data.

**Comment by tolot27** [comment]
Does it work with the latest version?

**Comment by Navid200** [comment]
@IgnisAsphodel Would you please close this issue?
Or, please respond.
Thanks
