### ISSUE TITLE
XDRIP on Samsung Smartwatch

### ISSUE THREAD

**Issue by FranzMo** [NightscoutFoundation/xDrip#556]
is it possible to scan my Freestyle Libre sensor with a Samsung smartwatch as standalone solution?
I wont just hold my watch to the sensor. without any bluetooth collector.

**Comment by ralf-ms** [comment]
No, not possible.
Samsung watches run tizen os and there are only android applications available.

**Comment by FranzMo** [comment]
Ok thanks
When speak from Android, do you mean Wear OS as standalone solution?

Von: ralf-ms <notifications@github.com>
Gesendet: Samstag, 25. August 2018 08:50
An: NightscoutFoundation/xDrip <xDrip@noreply.github.com>
Cc: FranzMo <franz.m50@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [NightscoutFoundation/xDrip] XDRIP on Samsung Smartwatch (#556)


No, not possible.
Samsung watches run tizen os and there are only android applications available.

**Comment by ralf-ms** [comment]
Yes! So far there are no applications for tizen os, and  - here I've to correct myself - there are also no applications for wear os (android watches) you can nfc-scan your libre sensor with.
xdrip runs on wear os, but relies on a bridge device like blukon or miaomiao which read the sensor via nfc and send the data using bluetooth to the android (wear os) watch (or the phone).

**Comment by Navid200** [comment]
@FranzMo Would you please close this issue if your question was answered?
You can use the support channels for questions instead of opening an issue.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks
