### ISSUE TITLE
Micro Bolus Represented by SBM Marker

### ISSUE THREAD

**Issue by old-square-eyes** [NightscoutFoundation/xDrip#562]
Recently SMB markers were introduced to nightlies, for small boluses to reduce clutter on the xDrip timeline for looping users.

This is currently the default, even for non looping users, impacting boluses <=0.3u.

Request that this visual be able to be disabled so that users micro bolusing can still track their dose.

Edit: Threshold from 0.5 to <=0.3

![screenshot_20180826-101858_xdrip](https://user-images.githubusercontent.com/25760491/44623476-a27f4780-a923-11e8-8ceb-b396add45ac8.jpg)

**Comment by jamorham** [comment]
The issue report is for boluses < 0.5 but it should only affect boluses <= 0.3U - Can you confirm?

**Comment by old-square-eyes** [comment]
Request is to be able to disable the graphic for any bolus be it 0.1, 0.3 or 0.5.

But yeah just tested now and you are quite right. Only 0.3 and below is currently affected I'll edit the original post.

**Comment by old-square-eyes** [comment]
Interesting the toast says 0.5 in the screen shot :)

**Comment by old-square-eyes** [comment]
Also think I found a bug. Entering 0.299U results in 99U being registered.

**Comment by jamorham** [comment]
Yep, I think these are two different issues. I will get them addressed.

**Comment by jamorham** [comment]
Please try the 27th Aug nightly, see the new setting in `xDrip+ display settings`

**Comment by old-square-eyes** [comment]
@jamorham what is the setting called? I don't see it on 27th Aug.

**Comment by old-square-eyes** [comment]
Seems good. Tested with 0.2, got icon, changed setting, icon turned to value :) I'll close this issue and open a new one for the rounding bug above.

**Comment by old-square-eyes** [comment]
Referenced above https://github.com/NightscoutFoundation/xDrip/issues/565
