### ISSUE TITLE
[HELP!] Xdrip early G5 transmitter death?

### ISSUE THREAD

**Issue by Webifi** [NightscoutFoundation/xDrip#566]
Basically new G5 transmitter (28 days), only ever used with Xdrip OB1,  showing voltage A @250

![screenshot_20180828-120911](https://user-images.githubusercontent.com/5082671/44738933-f4f36c00-aabb-11e8-9ea1-f5b28cb57d30.png)

Previous G5 transmitter lasted almost 6 months, first used with Dexcom App, then Xdrip.

Is there something with how Xdrip uses/initializes a G5 transmitter that could be killing it early?

**Comment by Webifi** [comment]
Battery status just updated.  Now showing:
Voltage A: 240
Voltage B: 231
Resistance: 651

Thoroughly confused.

**Comment by Webifi** [comment]
Now I'm. getting "Got data 15:49", and it does authentication and get data every 5 minutes, but xdrip still says signal missed.

Even more thoroughly confused.   Did xdrip just kill my G5 transmitter in under 30 days of use?

**Comment by doc77** [comment]
Did you receive both the old and new transmitter simultaneously? If the second transmitter was allowed to "sit" for six + months then your second transmitter behavior is not unusual. The transmitter battery immediately starts losing charge the moment it is manufactured.

**Comment by Webifi** [comment]
I'm pretty sure the magnet in the transmitter's box is there to prevent the transmitter from drawing much/any current until you remove it from the packaging, though it sounds like the G5 is worse in this regard than the G4 was.  The transmitter died well before the ship by date on the box.

I've restarted a new transmitter in the same way now, so we'll see.

**Comment by Webifi** [comment]
Next transmitter is now only 52 days old, and reporting low battery, with Voltage A at 290 and Voltage B at 275.  While I know they are only guaranteed to last 3 months, they normally last much longer.

Really does seem like something xdrip is doing something that chews up G5 transmitter batteries faster than normal.   The first transmitter I used with with XDrip lasted 3 months on the native Dexcom G5 app, then another ~3 months on XDrip.  The next one lasted only about a month.  And now the 3rd looks like it may only last about 3 months.  (The 2nd transmitter was received with the 1st.  The 3rd was received just before 1st use in August.)

Is there something the native G5 app does to the transmitter that allows it to last longer, even when the transmitter is used with Xdrip?  Are G5 batteries really just this unpredictable?

**Comment by doc77** [comment]
When you run in native mode you are enabling two way communication with the transmitter. That uses up a battery faster.

If you use any other xDrip+ mode it is only one way communication (transmitter>>xDrip+). In that case xDrip+ has no effect on the transmitter battery.

**Comment by Webifi** [comment]
I don't use native algorithm in XDrip, only OB1.

**Comment by Webifi** [comment]
Next transmitter finally dies, but at only ~60 days of use.

Is no one else seeing these issues with G5 transmitters on x-drip?

**Comment by Webifi** [comment]
One thing I notice is that "Bluetooth Link" almost always says "Disconnecting" instead of "Disconnected".  Is it possible that xdrip is keeping the Bluetooth link open longer than it's supposed to?

**Comment by edmundac** [comment]
Hello, I'm having the same problem after switching from a Galaxy G5, which broke, to a less reliable BLU Dash X2. Using xDrip+ and the Dexcom G5, I've lost 3 transmitters in the span of 3 months. I think the poor quality of the phone is to blame, but I don't know which phones work best with xDrip+. I'm thinking of using the Dexcom G4 and havingf the G4 transmitter send the signal to xDrip+. 
![49202804_517287285432269_2069196749360070656_n](https://user-images.githubusercontent.com/40383153/50804692-32170880-12bd-11e9-8852-c0c9e994014c.png)

**Comment by Webifi** [comment]
On my latest transmitter, I enabled 'G5 Native', and the transmitter seems to be lasting much longer.  On the first transmitter I used with XDrip, I has first used the transmitter with Dexcom's official app, so it would have used the 'Native' mode as well, until the official app rejected the transmitter after it decided it was too old (3 months.).   That transmitter lasted another 4 months on Xdrip using the non-native mode.

My guess is that you need to use the 'native' mode on the transmitter at least once, else the thing drains the battery.

**Comment by Navid200** [comment]
@Webifi 
Would you please close this issue?  
There are so many similar experiences, where a transmitter battery drains faster than expected.  Dexcom has a warranty that covers early battery failure.

**Comment by Webifi** [comment]
Dexcom warranty will not cover it if you've used the G5 with x-drip -- and this issue is with x-drip.

I'll close the issue when it's been verified that x-drip no longer kills G5s early.

**Comment by Navid200** [comment]
There are thousands of people using xDrip with G5 with no such issue.  There are many transmitters shipped with batteries that are not healthy.  This happens with many manufacturing production lines.  The warranty concept is the result of that.  The manufacturer can spend a lot of money to improve the yield by 0.1%.  Alternatively, they can offer to replace a malfunctioning product for much less.  Looking at the big picture, it makes business sense for them to take the second route.

It would be great if someone who had replaced the battery with a rechargeable would perform an experiment where he/she would use xDrip after a full recharge until the transmitter needed charge and then did the same thing using the Dexcom app.  If the battery lasts longer on the Dexcom app, it would prove your suggestion.

You can keep this open for now.  I am just going through the old issues asking individuals to be reasonable and close an issue that is years old unless there is a reason to leave it open.

**Comment by Webifi** [comment]
In this case, x-drip seems to be able to put the G5 (and G6 for that matter) in to a mode that consumes more power. 

If someone has a rechargeable G5, it would be nice for them to try to reproduce the results, though I'm not sure they'll be able to.   It basically boils down to not using "native" mode on the G5 immediately after first use, right out of the box.  The G5 seems to need to have native mode enabled on X-drip at least once to keep it from draining battery quickly.  I was able to reproduce it on a few different transmitters.   Related, but not required for the issue: If the transmitter is already "past date" (new, never attached to sensor, but transmitter is old) this means you'll need to hard reset the transmitter immediately, else you'll not be able to put it in native mode, and it will drain its battery quickly.   (I can only assume the transmitters have an actual expiration timestamp, in addition count-down from first use expiration - both resettable by hard reset -- but again, unrelated to the original issue, other than the issue is automatically triggered on older but new transmitters.)

I'm not sure if hard resetting a G5 transmitter, then trying to use it in non-native mode will re-create the issue.  Certainly was repeatable on first use. 

(The G6 battery drain issue is much different, so I wont go into details here, but has to do with trying to re-use a sensor.  Was able to kill a new G6 in a few short hours.  Not willing to do much testing with G6s, since you can't change the batteries in the newer ones.)

**Comment by Navid200** [comment]
The recommended settings I provide in the xDrip facebook group asks people to use G5 in non-native mode.  This has never caused the battery to drain as you suggest.
I personally used one of my G5 transmitter only in non-native mode right out of the box.  It lasted more than 5 months.

You are welcome to share your experience with us in the facebook group:
https://www.facebook.com/groups/xDripG5

An issue can stay open only if it clearly provides the means to reproduce the problem.

**Comment by Webifi** [comment]
I don't/won't  do Facebook.

I was able to reproduce the issue reliably multiple times with different transmitters.  I'd recommend you re-test again -- and adjust your recommendations for non-native mode use.

**Comment by tolot27** [comment]
> In this case, x-drip seems to be able to put the G5 (and G6 for that matter) in to a mode that consumes more power.

xDrip cannot put the transmitter into any mode. It can only starts and stops a sensor. That is the only "write" access to the transmitter. In between, it just reads the data every five minutes. I really don't see any causality that xDrip is responsible for a higher power consumption of the transmitter.

@jamorham Any further comments to this issue?

**Comment by Webifi** [comment]
> xDrip cannot put the transmitter into any mode. 

Not directly, and perhaps I should have said "state", but it's certainly possible that a transmitter could get stuck in a state/mode/what-ever-you-want-to-call-it that would consume more power as the result of an unexpected condition.   It's also possible that this condition could be more likely to be encountered by certain combinations -- like if native mode had ever been used on the transmitter before (haven't looked at the details of how that's queried) plus anomalies specific to a given Android device/Bluetooth stack/etc.

**Comment by Navid200** [comment]
We are asking xDrip users to participate in conversations and sharing experiences using forums.  
Other than facebook, the available options are:
https://gitter.im/jamorham/xDrip-plus
https://github.com/Navid200/xDrip/discussions

We encourage discussions.

But, we are discouraging users from using this issues platform for that purpose.

Out hope is that the developers can look at the open issues and see where they need to focus on next.

There are individuals who use their G5 transmitters only in non-native mode.  That mode, by the way, only affects xDrip.  It does not in any shape affect the transmitter.  The transmitter has no idea if the receiver (xDrip in this case) uses the raw values or the blood glucose values that the transmitter transmits.

I encourage you to open a thread and we can continue this conversation.  But, please do not reopen this issue. 
Thanks
