### ISSUE TITLE
Improve wear collection service when phone is out of range

### ISSUE THREAD

**Issue by zackallan** [NightscoutFoundation/xDrip#567]
With the latest nightlies the wear collection service is started as soon as the smartwatch has no connection to the phone (only "Enable Wear Collection Service" is activated). It would be better if the wear collection service is already started when the phone cannot connect to the transmitter even if the watch is still connected to the phone.
I often noticed that the watch has a better bluetooth range than the transmitter. So the watch did not start collection service because it still had connection to the phone but the transmitter already lost connection to the phone. Due to this issue there are sometimes no readings received.

Collector device: Miaomiao
Watch: Ticwatch E
OS watch: Wear OS: 1.5 Android 8.0.0
Phone: Nexus 6P
OS phone: Android 8.1.0

**Comment by Bo7amada** [comment]
I also have Ticwatch E but I could never collect reading from watch independently no matter what I tried.

My phone is Galaxy S8 though, any tips on how to do it?

**Comment by Bo7amada** [comment]
Yes I'm on MaioMaio, I'll see the docs now, but did u patch ur watch or something?

**Comment by zackallan** [comment]
No, there is no patch needed for Miaomaio.

**Comment by Hyuril** [comment]
> 
> 
> With the latest nightlies the wear collection service is started as soon as the smartwatch has no connection to the phone (only "Enable Wear Collection Service" is activated). It would be better if the wear collection service is already started when the phone cannot connect to the transmitter even if the watch is still connected to the phone.
> I often noticed that the watch has a better bluetooth range than the transmitter. So the watch did not start collection service because it still had connection to the phone but the transmitter already lost connection to the phone. Due to this issue there are sometimes no readings received.
> 
> Collector device: Miaomiao
> Watch: Ticwatch E
> OS watch: Wear OS: 1.5 Android 8.0.0
> Phone: Nexus 6P
> OS phone: Android 8.1.0

Hello and thank you for opening that issue. I have the same so I have to "Force Wear Collection Service" and "Only use Wear" to avoid this problem.

Collector device: Miaomiao
Watch: Ticwatch Pro
OS watch: Wear OS: 2.1
Phone: Sony Xperia XA
OS phone: Android 7.0

**Comment by Navid200** [comment]
@zackallan Would you please close this issue if you have got answers to your questions.
If not, you can use the support channels.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks

**Comment by zackallan** [comment]
As I don't use the described setup any more I can't test if the situation has improved in the meantime.
