### ISSUE TITLE
Freestyle Libre expiring date alert

### ISSUE THREAD

**Issue by ANDREAPIPPI** [NightscoutFoundation/xDrip#570]
Hi. 
As many Freestyle users I insert a new Libre sensor (without initializing it!) 24 to 48 hours **before** the expiring date of the one in use, because this allows to settle the tissues soreness due to the violent insertion of the needle. 
Most of times this gives much more accurate readings from Freestyle almost immediately after initialization, instead of having about 24 hours of incorrect values.
Hence my request: I think it could be useful to have an alert message, configured like the "High" or "low" values alerts, starting at a selectable time (6-12-24-36-48 hours) before the working Libre expiring date.
This way we will be informed that it's time to insert the new sensor.
Thank you for all your precious work, very appreciated!
Pippo    :-)

**Comment by sodesignberlin** [comment]
Great idea.
This feature would be very handy. Thought not aaaas important (we can handle this without an alert ;-) Anyway if it is easy to implement it would be another very nice feature for this more and more improving app.

**Comment by ANDREAPIPPI** [comment]
I agree with sodesignberlin about the relevance of this feature, but xDrp+ has already the needed info, so I supposed it could not be a difficult or long task, and I hope to be right...   .-)

**Comment by Navid200** [comment]
xDrip has reminders.
https://navid200.github.io/xDrip/docs/Reminders

Please have a look and see if you can accomplish what you need using reminders.

**Comment by Navid200** [comment]
There is an existing feature that shows when (time and date) the sensor will expire on the main screen: https://navid200.github.io/xDrip/docs/Sensor-Expiry.html

We will add an optional notification (not an alert) that will come up a day before the expiry.  So, it will make no noise or vibration.  But, it will pop open a notification on the phone that you can dismiss the same way you dismiss an alert.

**Comment by Navid200** [comment]
There is now a sensor expiry notification in xDrip as of February 11, 2023.
https://github.com/NightscoutFoundation/xDrip/releases/tag/2023.02.11

Please test it and let us know if you run into any problems.
We can always reopen if needed.
