### ISSUE TITLE
Xdrip Plus won't install

### ISSUE THREAD

**Issue by dpsumption** [NightscoutFoundation/xDrip#574]
My daughter is T1 and we have been using the DExcom G4 share with Xdrip2.06-76d589d-experimental-xDrip2-beta-206-2016.09.24
I use Nightwatch on my smartphone and works great.  

We just upgraded the Dexcom to the G6.  I tried to download the current version of Xdrip+ and the nightly update and i try to install on my daughters phone (which is running Xdrip).  When I launch the apk file, it goes into the Xdrip app and I see where it says it will not overwrite my settings and I click install.  After a few second I get an error that says App not installed.  I get this whenever I try to launch the apk files that I downloaded.  I did go in and set to install unknown sources.
Her phone is a Samsung S8 running Android 8 (ver 9 is not yet avail thru verizon).
Can anyone help?

UPDATE:  I just downloaded to another Samsung S8 and it installed just fine.  I think I will need to uninstall the old version (after I write done the settings for azure website etc) before it will install.  I will try that tomorrow and will update.

**Comment by jamorham** [comment]
Does your old version of xDrip have the ability to export settings? Check the various menus for the option to save the settings out. Then you should be able to import those to xDrip+

**Comment by jamorham** [comment]
marking as resolved
