### ISSUE TITLE
feature request: insulin calculator?

### ISSUE THREAD

**Issue by castdoom** [NightscoutFoundation/xDrip#577]
is it possible to make a calc integrated into xdrip so you can put your ratios in and when eating something can just enter the carbs then xdrip checks the time, checks ratio and your current bg level giving you a suggested dose for the carbs and a correction if needed?

**Comment by doc77** [comment]
Settings>xDrip Predictive Simulator Settings.

Settings>xDrip+ Display Settings>Show Bolus Wizard Preview

**Comment by castdoom** [comment]
is the BWP an insulin calculator? i had it enabled already and dont see an option to calculate dosage

**Comment by doc77** [comment]
You don't have to calculate anything.  It should run in the upper center fairly continuously.

If you're going to eat, enter the carbs you are going to eat and It will calculate the proper bolus. It takes into account your I:C ( you can set that by time of day), your current Bg, and your Bg momentum. It does not factor in exercise.

For corrections it just automatically suggests a correction bolus based on your correction factor.

It's quite handy. If you want something a bit more robust try Predict BGL on the play store. It imports your Dexcom readings via Share and has a good prediction model.

**Comment by castdoom** [comment]
oooh somehow i missed that feature, thanks very much @doc77 much appreciated!
