### ISSUE TITLE
Starting a G6 Sensor

### ISSUE THREAD

**Issue by DunePlodder** [NightscoutFoundation/xDrip#578]
I've been a little confused each time I've started a g6 sensor so created some notes for myself:
[Start a G6 sensor.txt](https://github.com/NightscoutFoundation/xDrip/files/2354219/Start.a.G6.sensor.txt)

It may be useful to others. Feel free to use, correct, edit or add to it.

**Comment by jamorham** [comment]
This looks correct to me

**Comment by Navid200** [comment]
@DunePlodder Thanks for the contribution.
Would you please close the issue as it is not an issue.  It can still be accessed after closed.
