### ISSUE TITLE
Xdrip wear app need updating...

### ISSUE THREAD

**Issue by chip83** [NightscoutFoundation/xDrip#580]
Often when I turn on or restart my Ticwatch E (Android 8.0) I get the message "Xdrip wear app need updating...".
I use the last nigtlhy of xdrip.
I checked on the playstore and there are no updates. What can I do?

**Comment by jamorham** [comment]
Wear 2.0 doesn't handle updates properly as xDrip versions can be upgraded and downgraded without problems. When you get that message I think you should uninstall the xDrip wear app and re-install it on your watch. That should ensure you get the latest version.

**Comment by jamorham** [comment]
marking as resolved
