### ISSUE TITLE
Patching LG G Watch W100 care pack, now stuck on boot

### ISSUE THREAD

**Issue by nsghub** [NightscoutFoundation/xDrip#582]
I installed the care pack for my G Watch (build M1D65S). Patching ~~worked without any problems but~~ throws an error and now it just shows the LG boot screen forever.

I applied the patch manually in the adb shell and get an error when patching with xdelta3. The checksum is incorrect and patching stops. By adding the no-checksum-option I'm able to apply the patch but the result is the same. The watch hangs at the boot image.

The logs that are available in recovery mode don't show any errors.

I can still boot into fastboot and restore the original system image.

**Comment by Navid200** [comment]
@nsghub Would you please close this issue if you have got answers already?
You can also use the xDrip facebook support group.
https://www.facebook.com/groups/xDripG5
Thanks

**Comment by nsghub** [comment]
I'm not seeing any answers here.
Willl not use facebook.

**Comment by Navid200** [comment]
Of course that's your choice.  
It's been 3 years since you posted here.  And, I am the only one who has responded.  You can wait another 3 years.  Who knows ...

**Comment by tolot27** [comment]
@nsghub The only other support resource at the moment is [Gitter](https://gitter.im/jamorham/xDrip-plus).

Care packs are specific to each Watch and not part of xDrip. Hence, we cannot help you, here. Please connect the author of the care pack (@jamorham?) directly or ask for support in either of the two support channels.
