### ISSUE TITLE
Stale BG number on Always On Display

### ISSUE THREAD

**Issue by bassettb** [NightscoutFoundation/xDrip#585]
The BG number that shows on the Always On Display will often be stale.  In attached images, the current BG is 158.  Always On Display shows 144, which is from 15 minutes prior.  I've seen it show a much older reading in the past few days.
![20180912_202121](https://user-images.githubusercontent.com/20321279/45460243-46117b80-b6ca-11e8-91c3-df7e964b3bdf.jpg)
![20180912_202039](https://user-images.githubusercontent.com/20321279/45460244-46117b80-b6ca-11e8-97d0-ef4a705b103f.jpg)

xDrip+ Version 1809080944
LG G6
Android 8.0.0

**Comment by jamorham** [comment]
I think this might be the always on display caching the data. If you unlock the phone does the notification area instantly have the correct number icon?

**Comment by Flori3000** [comment]
It is the same for me on a LG V30 (Oreo 8.0.0). Even if I unlock the screen and open Xdrip, the AOD stays on the same outdated value.  Please, can you check this?

**Comment by liddijx** [comment]
Did you find a solution to this? Same thing happening with my LG V40

**Comment by davidmtml** [comment]
Same issue on my LG G6

**Comment by Navid200** [comment]
@bassettb I am closing this issue as you never responded to the question posted by a developer.
We can always re-open if needed.

**Comment by Der-Schubi** [comment]
Hi! I got the same issue, the notification icon (that shows the small numbers) will always update, even on AOD, but the graph often stops to update at all. In the split second, when I unlock the phone 'til the graph gets hidden, it will show the correct value. @jamorham The in-app log doesn't show anything but "Cannot get root view" some time later, maybe when I unlock the phone.
I'm using the latest nightly.
![IMG_20211111_131447701](https://user-images.githubusercontent.com/2668238/141297920-11f78474-3f4a-4339-ab8c-227564b59b52.jpg)
s.
