### ISSUE TITLE
Session start failed: clock not synchronized or other error

### ISSUE THREAD

**Issue by zestyo** [NightscoutFoundation/xDrip#588]
I started to get this error out of the blue last week. Tried restarting the sensor and even doing a hard reset of the transmitter with no luck. Eventually tried a brand new sensor and still the same error.
Any ideas how to proceed here? Has anyone else seen this issue before?

![screenshot_20180917-214108](https://user-images.githubusercontent.com/648797/45649571-9a9a6980-bac3-11e8-8129-6494ffe474e3.png)

Thanks

**Comment by jamorham** [comment]
Which xDrip version are you running?

**Comment by jamorham** [comment]
I think that the issue should be fixed in the Alpha or nightly. Otherwise I would say try a hard reset.

**Comment by zestyo** [comment]
Tried a hard reset in both Alpha and Nightly with the same effect. It goes one or two readings then fails again.

**Comment by zestyo** [comment]
Ended up getting a replacement transmitter as nothing else seemed to work.
