### ISSUE TITLE
Broadcast of incorrect bgvalues when scanning manually

### ISSUE THREAD

**Issue by YPOC** [NightscoutFoundation/xDrip#589]
When scanning the FSL manually with xDrip only the 4 latest values get broadcasted correctly (like to AAPS), values that are older than that will default to the latest value. 

The first two screenshots show xDrip and AAPS before scanning, the others are after scanning.

![screenshot_2018-09-19-20-16-32](https://user-images.githubusercontent.com/24976043/45778176-3230c100-bc58-11e8-9f68-1b1a99c40496.jpg)
![screenshot_2018-09-19-20-16-45](https://user-images.githubusercontent.com/24976043/45778177-3230c100-bc58-11e8-8d81-d2178337254d.jpg)
![screenshot_2018-09-19-20-16-59](https://user-images.githubusercontent.com/24976043/45778179-32c95780-bc58-11e8-9b9a-3c795bd129ba.jpg)
![screenshot_2018-09-19-20-17-07](https://user-images.githubusercontent.com/24976043/45778181-32c95780-bc58-11e8-87ca-f8b0a83b86a3.jpg)
![screenshot_2018-09-19-20-17-20](https://user-images.githubusercontent.com/24976043/45778182-32c95780-bc58-11e8-9615-897e050f0fb5.jpg)
![screenshot_2018-09-19-20-17-32](https://user-images.githubusercontent.com/24976043/45778175-3230c100-bc58-11e8-97b4-336102ec2ffa.jpg)

**Comment by Navid200** [comment]
@YPOC Is this still an issue?
You can ask in the support channels to see if there are solutions or work-arounds.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks

**Comment by YPOC** [comment]
@Navid200 As I'm no longer using Freestyle Libre I can't tell if it has been fixed. At least with the G6 collector I have found no issues in that regard.
