### ISSUE TITLE
JSON exception when receving historical values from 600SeriesAndroidUploder

### ISSUE THREAD

**Issue by ekazum** [NightscoutFoundation/xDrip#591]
Using Medtronic 640G pump and 600SeriesAndroidUploder as collecting app. Xdrip runs on same android device as collector.
Normal behaviour in previous releases was that when pump is back in range, all historical values are read and broadcasted to Xdrip on reading device.
In latest release, only current value appears in Xdrip, history values do not appear.
Log shows - Got JSON exception org.json.JSONException: No value for direction

600SeriesAndroidUploader did not change and only change was upgrade of Xdrip on collecting device. I assume something changed in interface Xdrip is expecting to get.

**Comment by ekazum** [comment]
After additional tests -
Problem does not occur on build from 2/7/18
Problem starts to happen on build from 4/7 onwards

**Comment by jamorham** [comment]
Please try the Sept 29th nightly and see if this resolves the problem. Thanks

**Comment by Cindbar** [comment]
I am using the Sept 29th nightly. xDrip is collecting old values, from time of connecting the Contour-Next-Link back. But xDrip is stopping at first old value found in the xDrip collection. Older values, back to 90 days ago are not fetched, if some values are already saved in between.

How to force xDrip to fill the gaps?

**Comment by jamorham** [comment]
Marking as resolved.
