### ISSUE TITLE
Settings Wiki

### ISSUE THREAD

**Issue by linomassarani** [NightscoutFoundation/xDrip#593]
Where could I find the updated verson of wiki with description of each menu like in the following link from 2015?

https://github.com/StephenBlackWasAlreadyTaken/xDrip/wiki/Settings

**Comment by Navid200** [comment]
It doesn't exist.  
You can find the existing Wiki.
https://github.com/NightscoutFoundation/xDrip/wiki
There are many subjects that currently don't have documentation.
We would like to improve documentation.

We cam reopen this issue if needed.  
But, as I said there are many subjects that currently have no documentation.  it would be pointless to have an open issue for every one of them.
