### ISSUE TITLE
different BG readings 

### ISSUE THREAD

**Issue by Binyamin-R** [NightscoutFoundation/xDrip#599]
Hi, I am using xdrip+ with miao miao. the readings that I get from the app are different. Is there a way to make xdrip+ use the same algorithm as the official libre scanner?
Are the readings from xdrip+ considered more accurate the ones from the libre scanner?
thanks in advanced

**Comment by tzachi-dar** [comment]
xdrip allows different algorithms to calculate bg readings.
To get results similar to the scanner, please see https://github.com/tzachi-dar/LibreOOPAlgorithm

Which are better hard to say:
For some people libre official scanner always get bad readings, and so xdrip is definitely better.
For other people, libre gives very good result, and it is hard for xdrip to do better.
Some people are just not ready to calibrate (mainly teenagers) so libre will be definitely better.

Some times sensors start to go wrong on the 10'th day, and xdrip can help.
So, you need to see in which backet you fail in your case (and as I said it changes from sensor to sensor).

**Comment by Binyamin-R** [comment]
thank you for the quick response, I am currently trying to download it. will it allow me to see both algorithms at the same time?

**Comment by tzachi-dar** [comment]
No, only one at a time.

**Comment by Navid200** [comment]
@Binyamin-R Would you please close this issue as it seems your question was answered?
Thanks
