### ISSUE TITLE
XDrip no longer able to read dexom G4

### ISSUE THREAD

**Issue by Larica03** [NightscoutFoundation/xDrip#600]
Yesterday around 4pm central time xdrip stopped being able to receive data from our dexcom G4 share receiver. The event log says "the phone is trying to read from paired device without encryption. Android bug? Have the dexcom forget whatever device it was previously paired to: oncharacteristicwrite code: 129bond 12." Then it keeps agressively restarting collector service due to lack of reception. 

Up until yesterday we have had no problems. We tried a different phone and a different receiver. We uninstalled and reinstalled xdrip more than once. We had all devices forget each other. We are on the alpha channel, so we tried two older builds and still no luck. At this point we don't know what else to try, or what has suddenly changed that is creating the problem. Any ideas? Thank you for your help!

**Comment by Larica03** [comment]
Also getting this: "got the status 133 bug, bad news! Count:1 - might require devices to forget each other: instance uptime: 0"

**Comment by jamorham** [comment]
glad you got it working - marking as resolved.
