### ISSUE TITLE
Copying of Callibration settings

### ISSUE THREAD

**Issue by svirito4ka** [NightscoutFoundation/xDrip#601]
Could you please clarify how to copy just _callibration settings_ from one device to another? For example  from time to time my little daughter uses the smartwatch (Finow Q1 Pro, Android 6.0) and the mobile phone (Sony Xperia Z5 Compact, Android 7.1.1) as collector for one and the same transmitter Dexcom G5. The smartwatch is more comfortable at the school while the mobile phone at home.

**Comment by tzachi-dar** [comment]
The fastest way to do that is to copy the calibration data manually. 

That is "enter engineering mode" on the watch. 
After that, calibrate on the phone.
wait 10 minutes for calibration data to be stabilize on phone.

on the watch, go to calibration graph, and (if you are in engineering mode) you can set the slope and intercept to follow the data on the watch.

One more question: how old is your son? does he look at values on the watch, or are you only looking at it?

**Comment by svirito4ka** [comment]
Thaks for your prompt answer, I'll try it! I monitor BG values remotly (by mobile Internet on the smartwatch). When my daughter (7 years) is at school she doesn't look at them, as a rule.

**Comment by tzachi-dar** [comment]
I'm facing a similar issue with libre.
The direction that I'm going in is to have xdrip to only receive data and upload it to the other xdrip.
I did not do this for the g5 since I had no one to test it. Do you want to try and test such a solution (I'm not sure that I'll have time to implement it, but maybe in the future).
This will probably require installing new versions, collecting logs and so on...

**Comment by svirito4ka** [comment]
I don't quite catch your idea. I do have G5 and it works with one xDrip+ as master (receive and upload BG data) and another one as follower (watch BG data). It works through Nightscout server or mongoDB.

**Comment by tzachi-dar** [comment]
No, I mean that the watch will use it's BT to get data from the g5.
The watch will then upload data to a mongodb.
The master xdrip on phone will get the g5 data from xdrip and apply calibration on it (and send it to NS and followers).

**Comment by svirito4ka** [comment]
My watch works on Android 6.0 and xDrip+ installed on it. The watch gets BG data from G5 by bluetooth connection (this watch has bluetooth, GPS and 4G module) and uploads them to Nightscout (mongoDB).
