### ISSUE TITLE
not connecting 

### ISSUE THREAD

**Issue by Binyamin-R** [NightscoutFoundation/xDrip#602]
I started using the miao miao with the freestyle libre and xdrip+ and it was working fine. I tried changing the algorithm to the oopalgorithm, but it didn't work and I lost the connection between the miao miao and xdrip+. I tried deleting the app and downloading it a few times, but it doesn't seem to connect and is stock on the collecting initial data screen. Does anyone know how I can make them connect again? do I have to wait until I put in a new sensor?

**Comment by tzachi-dar** [comment]
No need to wait for a new sensor.
Very likely you should go to settings->less common settings->other misc options
and disable "out of process libre algorithm"

**Comment by tzachi-dar** [comment]
Does it show connected on status screen?

בתאריך יום א׳, 30 בספט׳ 2018, 17:24, מאת Binyamin-R ‏<
notifications@github.com>:

**Comment by Binyamin-R** [comment]
no, it's stuck on the "collecting initial readings" screen, and just doesn't get any data

**Comment by tzachi-dar** [comment]
You can press the back button to get rid of this screen.
Then go to status and see what is displayed.
Go to bt status and see what is displayed.
Try bt scanning again.

בתאריך יום א׳, 30 בספט׳ 2018, 17:34, מאת Binyamin-R ‏<
notifications@github.com>:

**Comment by Binyamin-R** [comment]
it says "connecting". so I'm guessing it's stuck on that. how do I bt scan again?

**Comment by Binyamin-R** [comment]
if it's by going to bluetooth scan and pressing on the miao miao again, then I have tried that a few times, and it doesn't seem to help

**Comment by tzachi-dar** [comment]
Yes, that is what you should have done.
What does the bt status page show?

בתאריך יום א׳, 30 בספט׳ 2018, 17:41, מאת Binyamin-R ‏<
notifications@github.com>:

**Comment by Binyamin-R** [comment]
It's working! I think the problem was that I had other libre related apps on my phone that I forgot about (like libre alarm). I deleted the apps and restarted the phone and now it's connected again. It's a bit weird because I also had these apps the first time I connected, and it didn't seem to cause a problem so i'm not sure. thank you for your help!

**Comment by Navid200** [comment]
@Binyamin-R Would you please close this issue as it seems your problem was resolved?
Thanks
