### ISSUE TITLE
Keep getting persistent high alerts, despite the alert being switched off

### ISSUE THREAD

**Issue by alexmoir1** [NightscoutFoundation/xDrip#604]
Have also tried disabling all alerts, but  it still fires even when sugars are below the high alert.
Any ideas?

Thanks
Ali

**Comment by jamorham** [comment]
It is linked to the high mark on the chart but I wouldn't expect you to get it when persistent high alerting is switched off.

**Comment by Navid200** [comment]
@alexmoir1 Would you please close this issue if it has already been addressed?
Thanks
