### ISSUE TITLE
Transmitter reset doesn't work on G6

### ISSUE THREAD

**Issue by norbertgaal** [NightscoutFoundation/xDrip#605]
`hard reset transmitter` has no effect on a G6 transmitter.

Latest nightly, tried with native mode on and off as well. Engineering mode is enabled.

**Comment by jamorham** [comment]
What firmware version is your G6 transmitter?

**Comment by norbertgaal** [comment]
Firmware Version: 1.6.5.25

**Comment by jamorham** [comment]
I had someone test this today with the same reported firmware and they confirmed that it does work.

I don't know what the difference would be. Are you using OB1 collector? You also should get a pop up message when you request it.

**Comment by norbertgaal** [comment]
Strange, I will go back and do some troubleshooting. 
Yes, I am using OB1 and I am not getting any popup message hence was my confusion. Nothing in the logs either. Initially I thought this command is ignored because some checks fails but looks like the issue is on my side.

Thank you for following this up.  It would be nice hearing other results as well but I am going back to test further.

PS: I am using an SW3 as a collector, but I tried this with and without it as well as I wasn't sure if this is something what would be forwarded to the watch.

**Comment by norbertgaal** [comment]
Looks like the issue is at me, going to test it with different setup (phone/transmitter)

**Comment by tudorfarcas2002** [comment]
it works with firmware 1.6.5.25. It was reconnected after 7 minutes instead 10-15min at G5
