### ISSUE TITLE
Xiaomi Huami Amazfit Bip Lite

### ISSUE THREAD

**Issue by Fohlenpower** [NightscoutFoundation/xDrip#618]
Is it possible zo integrate my new Xiaomi Huami Amazfit Bip Lite?

My setup: Libre / miaomiao / xdrip+ (adc3870-2018.09.15)

If I go to: Settings - Smart Watch Properties I found the point AmazFit Sync Service but not more to 
 integrate my Xiaomi Huami Amazfit Bip Lite.

**Comment by jbocciocastrillo** [comment]
Hi, yes sounds interesting to have that option, but nobody knows what this exactly can do... Btw, I am using Xdrip+ since I abandoned last week my iPhone 7 + Spike setup to explore all the amazing options that Android offers with Xdrip. Which smartwatch do you recommend me? I was thinking about a second hand Pebble classic, but I do not know if Xdrip+ allows to directly connect via Bluetooth to the Pebble. Thanks for the tips!

By the way @Fohlenpower I think the Ticwatch E is not a bad option neither if you want a smartwatch, and it only costs 120$!

**Comment by jbocciocastrillo** [comment]
Thanks @Klaus3d3 do you know how to install it on Amazfit devices? do you also know if the connection is direct between the Amazfit and the Miaomiao transmitter? I understood that only WearOS 2.0 smartwathces can be configured as Data Collectors

**Comment by Klaus3d3** [comment]
Yes i know, 'cause i made it.

See this:

https://github.com/NightscoutFoundation/xDrip/issues/353

The watchface needs to be installed to the watch and on phones side you must activate the service.

The Amazfit Service in this master repository is not up to date. Therefor use the latest release of my fork until i made a new pull request.

**Comment by alwayssimifuzi** [comment]
I‘d love to see the Bip integrated, would be a very nice Pebble replacement.

**Comment by xannasavin** [comment]
+1 on the BIP integration, also since BIP has an incredible battery life. 
Main difference as far as I can see: BIP is on MiFit, Stratos and Pace are on the Amazfit App.

**Comment by Klaus3d3** [comment]
> 
> 
> +1 on the BIP integration, also since BIP has an incredible battery life.
> Main difference as far as I can see: BIP is on MiFit, Stratos and Pace are on the Amazfit App.

the main difference is, Pace,Stratos and Verge running android, bip runs it's own OS and is less powerfull.

**Comment by xannasavin** [comment]
Agreed - it would be enough if one could get actual glucose and trend arrows on a BIP watchface. Nothing more needed in my opinion :)

**Comment by pge** [comment]
+1 for the bip. It's the most "innocent" looking of the huami family watches, that would also be worn by a woman :)

**Comment by Vectruz** [comment]
i has amazfit bip and use custom watchfaces with custom apps, whats hold the development of compatibility with this device? someone know how to did it work? i love to see my glucose levels on amazfit bip, this smartwatch at least not need to recharge each day.

**Comment by Karisematic** [comment]
Looking forward to a BIP watch face, together with the long battery life it will be a great tool to monitoring my BG

**Comment by MikeFor** [comment]
+1 for the bip. We monitoring our son BG. I have Sony smartwatch 3, my wife have Amazfit Bip. On Sony i see visual graphic of BG, on Amazfit Bip thru program "Tool & Amazfit" my wife receive every 5 minutes notification. And I am too looking forward to a BIP watch face.

**Comment by MikeFor** [comment]
Could a graph be displayed based on the information in the notification? 
![IMG-2f14fc72b4d73df3cf4fc418003e414d-V](https://user-images.githubusercontent.com/54059068/62927783-edf26600-bdbf-11e9-9836-07783ee48ecc.jpg)

**Comment by Vectruz** [comment]
Hi, i use this same app... but i not know how to make this BG and delta
values display when update the notification on my smartphone. it appears
with how settings? i see one ignore permanent notifications, i disabled it
now to check if is it... may it work! but if you can respond my question
about how to setup this info, i will be glad, thanks!

Em ter, 13 de ago de 2019 às 05:46, MikeFor <notifications@github.com>
escreveu:

**Comment by N3ska** [comment]
Hi MikeFor,

How could I get that notification on my Amafit bip from Xdrip? 

https://user-images.githubusercontent.com/54059068/62927783-edf26600-bdbf-11e9-9836-07783ee48ecc.jpg

I can receive when it goes over the limits but it never shows me a digit and the arrow.

I am also using a Samsun S6.

Could you please help me?

**Comment by MikeFor** [comment]
Hello! tomorrow will be manual with pictures :)

**Comment by N3ska** [comment]
Many thanks 😊

On 4 Sep 2019 16:26, MikeFor <notifications@github.com> wrote:

Hello! tomorrow will be manual with pictures :)

**Comment by MikeFor** [comment]
Hello! 
I hope I can help someone with these settings.
https://github.com/MikeFor/Repository/issues/1

**Comment by N3ska** [comment]
Thanks so much!!!! It really works!!! Happy with this..... soooooo happy... Thanks for your time and help! I do appreciate it

**Comment by MikeFor** [comment]
> Thanks for your time and help! I do appreciate it

Always ready to help :)

**Comment by sp17b** [comment]
Hey can I also get the link?

**Comment by MikeFor** [comment]
> Hey can I also get the link?

Yes ;) https://github.com/MikeFor/Repository/issues/1

**Comment by Navid200** [comment]
@Fohlenpower Would you please update?

**Comment by Fohlenpower** [comment]
Erledigt
