### ISSUE TITLE
Error: bgreadinginsertfromjson passed a null or zero length json

### ISSUE THREAD

**Issue by cfaagaard** [NightscoutFoundation/xDrip#621]
xdrip version: 2018.09.08
nsclient version 1.58
Loop version: 1.9.3
I would like to use xdrip as nightscout viewer and followed these instructions: https://jamorham.gitbooks.io/xdrip-plus/content/xdrip-plus-nightscout-viewer.html
I am using Loop, so it the json from Loop that gets into nightscout.

I am getting data into the nsclient but I am only getting some of the treatemens-data into xdrip and I get none of the entry-data.
I am getting this treatement:
{
    "_id": {
        "$oid": "c8bc850a6d6c433fb2651730"
    },
    "timestamp": 1539186893000,
    "eventType": "Correction Bolus",
    "enteredBy": "loop://iPhone",
    "uuid": "c8bc850a-6d6c-433f-b265-17307690b980",
    "insulin": 3.5,
    "created_at": "2018-10-10T15:54:53Z",
    "sysTime": "2018-10-10T17:54:53.000+0200"
}

But I am not getting the entries which all have the following json:
{
    "_id": {
        "$oid": "5bbe35f202aa6d8d3546c18c"
    },
    "sgv": 274,
    "date": 1539192000000,
    "device": "loop://iPhone",
    "dateString": "2018-10-10T17:20:00Z",
    "type": "sgv"
}
In xdrip event log I get the following every 5 minutes:
bgreadinginsertfromjson passed a null or zero length json

**Comment by jamorham** [comment]
Please update to the latest nightly and re-test to see if the problem persists:

https://github.com/NightscoutFoundation/xDrip/wiki/How-to-get-the-Nightlies-on-Automatic-Update

**Comment by cfaagaard** [comment]
Should I upload logs?

**Comment by jamorham** [comment]
yes please upload logs and comment in them so I know who they are from. thanks

**Comment by cfaagaard** [comment]
Log is uploaded with a reference to this issue.

**Comment by jamorham** [comment]
Please try the Oct 11th nightly (out now) as it should log more information about this problem.

**Comment by cfaagaard** [comment]
But this entry-json is not going into xdrip:
{
    "_id": {
        "$oid": "5bbfa32602aa6d8d357bf256"
    },
    "date": 1539285180000,
    "sgv": 104,
    "dateString": "2018-10-11T19:13:00Z",
    "device": "loop://Frederik - iPhone",
    "type": "sgv"
}

**Comment by cfaagaard** [comment]
Any updates om this issue?

**Comment by fromorbonia** [comment]
@cfaagaard or @jamorham - did you get a break through with this problem? I'm getting that same error message.
The most noticeable symptom is that xDrip+ isn't picking up data from the NSClient (AndroidAPS installed is 2.0) and is stating "signal missed". If I specifically go into xDrip+ it sometimes restarts itself, other times I un-pause NSClient manually and that then works.
The error log message above occurs about 20 times at approximately the last time that there was a successful connection.
I have just done a new install of LineageOS 15.1 (Oreo 8.1 from AOKP) on a Samsung Galaxy S4 Mini. Previous to that I was on KitKat and was having similar problems (hence the upgrade!).
Thanks

**Comment by cfaagaard** [comment]
@fromorbonia Nope. It works on a Nexus p6 with android 8.1 (which I then use as my alarmclock), but I can't not get it to work on a Pixel 2 with android 9 (my personal phone).

**Comment by fromorbonia** [comment]
@cfaagaard - I got a bit further with this, but I don't think it will help you. I'm still getting those error messages - but NSClient is now running. 
I'm on Azure for Nightscout, and I needed to turn on HTTP 2.0 and Websockets at the server host level - and now AndroidAPS / NSClient works consistently.

**Comment by cfaagaard** [comment]
@fromorbonia I'm also on azure. Turned on http 2.0 and websockets. Downloaded nsclient and the newest drip+. And it works now! If it was the azure settings or a fix in the new clients i don't know. But it works.
@jamorham do want me to close the issue or do you want to do it?

**Comment by Navid200** [comment]
Thanks, closing
