### ISSUE TITLE
Large database sizes slow down interface?

### ISSUE THREAD

**Issue by hardaker** [NightscoutFoundation/xDrip#626]
I have/had an xdrip database on my pixel 2 that's been around since Mar, 2017.  The xdrip interface (eg, when entering treatments) has been getting slower and slower over time to respond to screen presses, etc.    Additionally, I'd get warning messages that 'xdrip was taking too long to respond: close or wait?'.

As a guess that it was the sqlite database getting too big, I exported it, pulled it over to my desktop, ran `delete from BgReadings where timestamp < 1533106800000;` (which killed everything before august 1, 2018, and pushed it back and imported it.  Sure enough, it's now zippy fast again.

Not sure what can be done about this other than to offer a "keep for how long" interface, suggesting at least 3 months of data is wise for the a1c calculations.

**Comment by MasterPlexus** [comment]
Just check the settings. There is are two options which are on Interest for you on this (settings, additive settings, Glucose retention and save database daily. There you can set is as you want (for example 90 days)

**Comment by Navid200** [comment]
@hardaker Would you please close this issue if you are satisfied with the response you got?
Thanks

**Comment by hardaker** [comment]
Thanks for the help.  I've switched to using that and it works well.
