### ISSUE TITLE
OB1 G5/G6 vs. OLD

### ISSUE THREAD

**Issue by svirito4ka** [NightscoutFoundation/xDrip#627]
I use Dexcom G5 and my smartwatch Finow Q1 Pro works as OB1 G5/G6 Collector (non-native mode) uncorrectly (unfortunately, with a period of just 10 minutes and only for about a day) but it works well when OB1 G5/G6 Collector unticked. If I use OLD Collector will the readings be as accurate as in OB1 G5 Collector (native mode unticked) and will the sensor and the transmitter periodically restart automatically?

**Comment by lmiekus** [comment]
The readings from OB1 or the standard collector are always the same. The OB1 was created to solve problems with BT communication between phone and transmitter. As in your case the native mode (Dexcom algorithm for BG values) is not used the restarts of the sensors are not required. The restart play the role in case of G6 sensor and the native mode. For G5 such operation is not needed, you simply continue using your G5 sensor until the "noise level" is to high - readings are erratic.

**Comment by lmiekus** [comment]
What is your capture rate for G5 and Finow Q1 Pro? What is the battery life?

**Comment by svirito4ka** [comment]
The capture rate reaches about 70 %, the battery life is 8-10 hours. My daughter uses the watch at schcool with only 3G , Wi-Fi disabled, brightness at the lowest level and make just a couple of messages (or calls) per day.
