### ISSUE TITLE
Use Bluetooth Meter always OFF

### ISSUE THREAD

**Issue by komp** [NightscoutFoundation/xDrip#634]
I use a Contour Next One glucose meter.
In Settings Glucose Meters,  Use Bluetooth Meter shows OFF
and I have been unable to change this.  Why?
I have successfully Scan'ed for Bluetooth Meter, and it sees my Contour Next.

thanks for your help.

I had this problem with the standard release (Sept 18, if I recall), so I picked up the most recent
Oct. 15 release, and have exactly the same issue.

**Comment by komp** [comment]
I should have included a few more details about my environment.
I am using a nexus 5X (google) phone, running Android 8.1.0 
I am currently using xdrip+ to display results from a Dexcom G5 transmitter.

**Comment by jamorham** [comment]
Does your glucose meter currently have values? It must already have values when scanned by xDrip or it wont allow you to use it.

**Comment by komp** [comment]
Thanks for the quick response:

> Does your glucose meter currently have values? It must already have values when scanned by xDrip or it wont allow you to use it.
> 


I just re-tried.

So, I took a reading with the Contour Next, and the value is displayed on the screen.
So, I went to Xdrip Settings -> Glucose Meters.
I still cannot et “Use Bluetooth Meter” to switch to On.
I did scan for Bluetooth Meter, and it immediately responded with Contour Next One and an Id.

Still, I cannot change “Use Bluetooth Meter” 
(or “Automatic Calibration”, which is what I really want).

Ed Komp

**Comment by komp** [comment]
> After you scan for the meter are you clicking on it? It should then report on the screen about connecting to the meter and retrieving the records. Only after that succeeds does it let you enable it as a meter.

After scanning, I select the meter “Contour783…”. and it asks if I want it paired.
I say “yes”, of course.
But, I don’t see anything about it retrieving records, and when I go back one level,
“Use Bluetooth Meter” still only shows “OFF”.
If I press or press-and-hold this option, nothing happens.
Also, I cannot select any of the other options on the “Glucose Meters” page.

If I go back to Scan, I still see a device id (?) listed for the meter (though it no longer identifies it as a Contour GM).
There is also a second id that I believe is for the Dexcom G5 device.

I have also tried selecting the Contour device and holding, to get an option to unpair the device — which works.
Then, I retried the pairing operation …

thanks for your help,

**Comment by komp** [comment]
Just after the trials listed above, I went to check out the Error and Event List.
After I clicked, Low, to see everything, I may have found the problem (?)
I just uploaded the list, since it is difficult to read the entire thing on the phone.
But, I did see the exception need BLUETOOTH_PRIVILEGED permissions.
A quick search online:
from: https://developer.android.com/reference/android/Manifest.permission#BLUETOOTH_PRIVILEGED

BLUETOOTH_PRIVILEGED
added in API level 19
public static final String BLUETOOTH_PRIVILEGED
Allows applications to pair bluetooth devices without user interaction, and to allow or disallow phonebook access or message access. This is not available to third party applications.

Constant Value: "android.permission.BLUETOOTH_PRIVILEGED"

So, how does xDrip get the ability to do this, even though it is a third party app?
When I check my xDrip app Permissions
Location, SMS, Storage

**Comment by komp** [comment]
I can close this myself, finally.
I checked to see what other privileges I could provide to xDrip.
The only ones I had not were photo and contacts.
I just tried allowing "contacts",  and now when I scan for the Contour GM 
it does download all the current info from the device (as jamorham said it should in an earlier message).
And, I can turn on "Use Bluetooth Monitor".
