### ISSUE TITLE
Number Icon in Notification Area Font Size 

### ISSUE THREAD

**Issue by opasha** [NightscoutFoundation/xDrip#635]
The double digit font is readable for the Number Icon notification, but the triple digit font size becomes much smaller and harder to read. Can you update this so they are equal or tell me how to modify this manually. I'm comfortable with adb, modification of system/data folders, etc on my rooted Mi Max 3 running Miui 10 Beta Weekly 8.8.9 xiaomi.eu rom. Thank you.

**Comment by jamorham** [comment]
It isn't possible to increase the number icon font size due to space limitations in that area.

**Comment by opasha** [comment]
I understand the vertical limitation, but why horizontal? The three digit size can't match the 2 digit size with a slight horizontal increase? Can you at least point me to the xml file for this? Thank you.

**Comment by jamorham** [comment]
Do you ever see an icon on the top line of the phone display which is wider than the standard? I don't think it is possible to change that width or height. The view is controlled by the android framework.

**Comment by opasha** [comment]
Fair point. It is an icon limitation. The png no matter the internal image size/look will get resized by android status bar framework xml. Wish there was a way to configure it to mimic the battery percentage size. Thanks for the feedback.

**Comment by Navid200** [comment]
@opasha Would you please close this issue?
Otherwise, would you please update?
Thanks
