### ISSUE TITLE
Snooze for calibration during night 

### ISSUE THREAD

**Issue by CaroGo** [NightscoutFoundation/xDrip#64]
Is it possible to add an option to snooze or disable the calibration reminders just during night? So you would not have to enable and disable it every day again...

**Comment by jamorham** [comment]
Do you have your phone plugged in charging at night? There is the option in `Calibration Alerts` which says `Even when charging` if you un-check this option then it wont prompt for calibration while plugged in charging. 

If you don't see that option, please switch to the nightly update channel.

**Comment by CaroGo** [comment]
Ok, thanks! Found the option! Great!

**Comment by doc77** [comment]
How about if the phone is not charging at night? I still disable calibration alerts every night because that is not when I charge the phone.
Thanks
