### ISSUE TITLE
Maximum Sync Queue Size Exceeded

### ISSUE THREAD

**Issue by alexmoir1** [NightscoutFoundation/xDrip#642]
Hi Guys
I keep getting this queue size exceeded message. I can get rid of it by clearing all xdrip data (Settings - Apps - Xdrip - Storage - Clear Data) but I then have to set everything up again & error comes back a few weeks later. When the queue size is exceeded, followers don't get any data.
Screenshot of error log attached.
Any idea how I can stop this happening?

Thanks for your help.
Regards
Ali

![screenshot_20181016-165426_xdrip](https://user-images.githubusercontent.com/24193604/47555247-3c9f4400-d903-11e8-82fb-4c7f69a38ca8.jpg)

**Comment by AdrianLxM** [comment]
I also have this issue.

I didn't have time to trace where it is coming from.
I do have AndroidWear enabled.
I do have could upload DISABLED.
I do have syncing with other xDrip instances DISABLED.

**Comment by gregorybel** [comment]
I see issue too, after receiving a calibration from Meter.

**Comment by jamorham** [comment]
Check that you are not disabling background data access for xDrip

**Comment by thomasmenges** [comment]
I see the same issue. Background data is enabled for Xdrip

**Comment by Navid200** [comment]
@alexmoir1 Can we close this?
If you are still experiencing this, would you like to try Nightscout sync as an alternative?
Thanks

**Comment by alexmoir1** [comment]
I had it again on a follower recently. I had to Clear Data & set up again.
What's Nightscout Sync?

**Comment by Navid200** [comment]
Nightscout is a (free) online repository many of us upload out blood glucose readings to directly from xDrip.
If you look under hardware data source on your follower where you currently have selected xDrip+ Sync Follower, you will see another option called Nightscout Follower.
If you have Nightscout set up, and have set up the master to upload to it, you can select that on the follower.  The follower will show the readings and the master will never show the max sync queue error any more.

Will you consider it?
If you don't have a facebook account, I can ask and provide a link to a public document online that would walk you through the required setup.

**Comment by Navid200** [comment]
These are instructions for setting up Nightscout.
http://nightscout.github.io/nightscout/new_user/?fbclid=IwAR3oa0QOlDnwCYr7VCm8Sv8SNZLDHdVRqUNZp9HbRl7WxSgHKQq_-68JsOE

They may look intimidating.  Believe me, it is worth it.  Do it when you can give it 20 minutes of time.  Don't expect to complete it in 2 minutes.

**Comment by alexmoir1** [comment]
We're already set up as a Nightscout follower on Xdrip.

**Comment by Navid200** [comment]
@alexmoir1  If your followers are using the Nightscout follower option, you can disable the xDrip sync on the master, which will stop getting the max sync queue size exceeded error.

On the master, go to the following page:
Settings -> xDrip+ Sync Settings, and deselect "Be master for followers".

**Comment by Navid200** [comment]
@alexmoir1 Can we close this issue?
Do you have any questions about what I suggested?

**Comment by alexmoir1** [comment]
Hi, the master is Diabox. I'm just running xdrip as follower. Clearing data fixes the issue, but it's not very elegant. Feel free to close the issue.

**Comment by Navid200** [comment]
So, you get this pop-up on the follower?

Can I ask what hardware data source you have selected for the follower on Settings -> Hardware Data Source?

**Comment by alexmoir1** [comment]
Nightscout Follower

**Comment by Navid200** [comment]
What do you see on the follower on the following page?

Settings -> xDrip+ Sync Settings

**Comment by jamorham** [comment]
Is this still a problem with the latest nightly? I thought this had been resolved already

**Comment by Navid200** [comment]
@alexmoir1 Would you please test this with the following release and report?  Thanks.
https://github.com/NightscoutFoundation/xDrip/releases/tag/2021.05.16

**Comment by Navid200** [comment]
If anyone is still experiencing this, please let us know.  In the meantime, I close this.

**Comment by saraBoKakal** [comment]
me

**Comment by Navid200** [comment]
@saraBoKakal Please provide the following screenshots:

- Classic status page
- xDrip logs showing the message 
- Uploader status page 
- Settings > xDrip Sync settings

**Comment by Inkalika** [comment]
I have sugar from juggluco going into aaps, and from that it goes into xdrip along with therapy. Almost every day the queue for transferring therapy to xdrip hangs and aaps starts to slow down. And this happens until I reboot the phone several times. I cleaned aaps cache, xdrip cache, cleaned base in aaps, disconnected therapy transfer from aaps xdrip - all this does not help. The only thing left is to completely clear both apps and re-configure. Maybe someone knows an algorithm to eliminate the queue of 200000 values from aaps xdrip?
Libra2 sensor, 1-minute readings, aaps version 3.3

Translated with DeepL.com (free version)

![Image](https://github.com/user-attachments/assets/5651656e-9844-4c0e-a477-484cfefb0b36)
![Image](https://github.com/user-attachments/assets/276b9865-2df6-480e-a40e-40dd6ccbd336)
![Image](https://github.com/user-attachments/assets/a9d58c54-244f-4026-a01b-6a39873634d3)
![Image](https://github.com/user-attachments/assets/26657370-dcf9-4937-b2cc-d717e7265e7a)
![Image](https://github.com/user-attachments/assets/70c1b46c-96f5-4db9-a6bf-05a121e218e4)
![Image](https://github.com/user-attachments/assets/a0ab0253-fe5d-4140-8d4e-c258b4063b7a)
![Image](https://github.com/user-attachments/assets/dfe28033-3de7-46d2-9d32-28945115e937)
