### ISSUE TITLE
Future BG reading is continously broadcast if option 'send display glucose' is enabled

### ISSUE THREAD

**Issue by jotomo** [NightscoutFoundation/xDrip#643]
While simulating the upcoming DST change, I changed the clock forward, which resulted in a reading of 119mg/dl being taken in the future. After going back to the current time, xDrip continuously broadcasted this future record. This only happens if _Inter-app communication->Send display glucose_ is enabled.

When processing a new BgReading, with the above option set, at https://github.com/NightscoutFoundation/xDrip/blob/master/app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/BroadcastGlucose.java#L53 the value of the youngest BgReading record is retrieved from the DB and send instead.

This issue is probably elsewhere in the code as well, as the UI correctly charted the readings, but also displayed that future reading continuously:

![screenshot_20181026-124231_xdrip](https://user-images.githubusercontent.com/1732305/47563027-c3164e80-d920-11e8-8e9a-0c1a3584c2e7.png)

**Comment by jotomo** [comment]
P.S. The fix was to delete future records via _System status_.

**Comment by AdrianLxM** [comment]
If I'm not mistaken, the display glucose now gets injected into the BG object (for NS upload). So it could be used instead of the recent one?!

**Comment by Navid200** [comment]
@jotomo Is this still a problem?
If not, can we close the issue?
Is there a solution if it happens?
