### ISSUE TITLE
Font size of Error and Event List

### ISSUE THREAD

**Issue by AdrianLxM** [NightscoutFoundation/xDrip#645]
... is very large. Nightly of 15th of October.

**Comment by jamorham** [comment]
Which handset are you using? What are the screen dimensions?

**Comment by AdrianLxM** [comment]
I'm using an Atom with 432x230 pixels on a 2.45 inch screen.

It was unreadable before (too large).

**Comment by Navid200** [comment]
@AdrianLxM Has this been addressed, or is it still the same?
Thanks
