### ISSUE TITLE
Note 9 connects sony smartwatch 3 for xdrip collector

### ISSUE THREAD

**Issue by junni3011** [NightscoutFoundation/xDrip#647]
Suddenly ssw3 cannot collects the bg for days.
I tried to unpair the ssw3 and re pairing with the phone and now xdrip plus does not installed on the ssw3. After some attempts of pairing it was installed on ssw3 but now it cannot collects the bg.
Would anyone please help?? If i try to collect the bg directly from phone it keep disconnects and cannot connects back.

**Comment by mistermintsgh** [comment]
Have you received the October security patch/update for your Note 9 @junni3011 ?

**Comment by wefink** [comment]
look  my comment in "Samsung October patch causing signal loss issues'
BTW October update still not arrived on my note 9
wf

**Comment by Navid200** [comment]
@junni3011 Would you please close this issue if it has been resolved?
Otherwise, you can use the support channels.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks

**Comment by Navid200** [comment]
Please ask the user community to see what options may exist.
