### ISSUE TITLE
Improve support for Finowatch / Finow Q1 PRO

### ISSUE THREAD

**Issue by jamorham** [NightscoutFoundation/xDrip#648]
What is the current situation with xDrip+ support on this device? What are the issues? Please let me know! thanks

**Comment by tzachi-dar** [comment]
As a collector of miaomiao this works well.
The q1 pro itself is a very low end watch. Battery might last from 7 hours to 18 hours with no good reason.
keyboard is almost useless. screen is low quality. (I guess that this is what you can get for 75 usd).
That said,  I'm not aware of issues as a collector.

**Comment by svirito4ka** [comment]
I used the watch Finow Q1 Pro with G5 as a collector in old mode, trying almost all versions of xDrip+ starting from August this year. The readings were received with intervals of 5 minutes and were transmitted to the Nightscout by the watch through 3G. But there was no stability, packet capture percentage was about 50-70 %. The collector used to terminate work when the charge was below 30 %. I think it depends on the in-build algorithm of energy saving. Also I tried to use this watch as a collector in OB1 mode (including Native Algorithm). The readings were received with intervals of 10 minutes and were transmitted to the Nightscout by the watch through 3G. This interval was inacceptable for me, so I left this mode.

**Comment by gordan1987** [comment]
My daughter use Finow Q1 Pro with G5(FW. 1.0.4.10).I set up them as a collector in OB1 mode with out native mode.In G5 Debug Settings mark only Use the OB1 Collector and Allow OB1 initiate bonding. And disable all in less common settings relates to bluetooth. Install root on watch and disabled all unused apps. Packet capture percentage about 85-95%.The readings  received with intervals of 5 minutes and  transmitted to the Nightscout by the watch through 3G. 
But some time watch lose connection totally helps only restart or start receive data with intervals of 10 minutes. In System Status - G5 Status - Phone Service Status show that it stuck on Connection request.
And if I start mess with less common settings or G5 Debug Settings I get no change in connections. So I set up alarm on missing reading and just rerstart watch.

**Comment by svirito4ka** [comment]
gordan1987, did you manage to unlock the bootloader on the finow q1 pro watch? This question was also asked @jamorham in gitter on 18th Nov. I think he has some ideas for improving collector service of this watch. And hope he is planning to realize “wearDemigod” mode for this watch.

**Comment by gordan1987** [comment]
I upload all for [rooting to Mega](https://mega.nz/#F!fQkiyC7L!3NhHK9DpAO6bqVApPXnncA)

**Comment by lmiekus** [comment]
I have enabled verbose longing for OB1 collector on this watch for Dexcom G6 sensor. The logs with the problematic situation as described by gordan1987 have been uploaded through xdrip with the information "#648" and my email address (lmiekus@gmail.com) The problem appeared at 23:10, since that time watch was unable to connect to the sensors. Only after restarting watch the connection have been restored . If you have any other questions please let me know. I am also attaching the exact configuration of the phone with all the important settings.
[Settings.docx](https://github.com/NightscoutFoundation/xDrip/files/2722310/Settings.docx)

**Comment by gordan1987** [comment]
It would be nice if xDrip had a possibility to restart the clock, if no data received. For me this only way to restore receiving data.

**Comment by lmiekus** [comment]
Did you thought about trying less common settings > Bluetooth settings > Timer value for BT Watchdog  set to 6 minutes and Bluetooth Watchdog checkbox ticked? I am occasionally getting lost connections as described by you, we usually do smartwatch restart to solve it. But I am planing to try this option too.  That option to set timer value is not possible in last stable version of xdrip+. I found this one in nightly from 28.12.2018.

**Comment by gordan1987** [comment]
I try set Timer value to 6 minutes in nightly. Still no luck, only restart helps.

**Comment by svirito4ka** [comment]
Did someone try to run the old collector (without OB1) on this watch? On russian diabet forum people says that it works well with G5 transmitter. Also they say it works reliably with Miao-Miao (transmitter for Libre sensor).

**Comment by gobeti** [comment]
I have the same issues with my daugther´s FINOW (+ Dexcom G6) working as a master. I realised that during the night (charging) it works perfectly (every 5 minutes reads and sends to nightscout) but then, once it is not charging, it becomes very unstable.

Thus, I am checking @imiekus´s guidelines this weekend to see whether it has something to do with battery optimization matters.

> Did you thought about trying less common settings > Bluetooth settings > Timer value for BT Watchdog set to 6 minutes and Bluetooth Watchdog checkbox ticked? I am occasionally getting lost connections as described by you, we usually do smartwatch restart to solve it. But I am planing to try this option too. That option to set timer value is not possible in last stable version of xdrip+. I found this one in nightly from 28.12.2018.

**Comment by gobeti** [comment]
The settings put together by @lmiekus were great. Much better connection. Still I had an issue today  where it lost connection and I had to restart the bluetooth system to get it working again.... I set up the automatic bluetooth restarting option but still it seems that once it enters into "blocked" status not event that feature would work. In any case, much better once battery optimization is not ticket for several services as described by @lmiekus

**Comment by gobeti** [comment]
Eventually, I seemed to have fund a good solution. Turned on all the BT special settings in Xdrip and I get readings every 5 minutes in the FINOW Q1 PRO. I tested it by putting the watch away for 25 minutes and, as soon as it was next to my daughter ´s dexcom G6 started reading nicely every 5 minutes and uploading in nightscout. So far so good. That plus the battery settings from @lmiekus seems to make a very good combination. Above 90% readings... sweet

**Comment by gobeti** [comment]
Still having issues with the BT connection, I am afraid. It is just unstable. It seemed to work but it still has issues when trying to link during the Wake Up of the transmitter. It just does not unless you force the BT off and on.... :-(

**Comment by lmiekus** [comment]
As the best solution for now is to restart the smartwatch. I thought that a quick workaround for existing problem would be to automate the restart with Tasker that is triggered by xdrip notification (alarm) "BR Reading Missed". The alarm would be triggered by xdrip if no BG reading is received for 6 minutes.  I have tested it on rooted phone and it works. Now the next step is to test it on finow without root privileges. This way you automatically preform restart with your own intervention.

**Comment by gobeti** [comment]
> As the best solution for now is to restart the smartwatch. I thought that a quick workaround for existing problem would be to automate the restart with Tasker that is triggered by xdrip notification (alarm) "BR Reading Missed". The alarm would be triggered by xdrip if no BG reading is received for 6 minutes. I have tested it on rooted phone and it works. Now the next step is to test it on finow without root privileges. This way you automatically preform restart without your own intervention.

Thanks, Tasker is a paid app, right? Is it possible to use "automate"? The issue is that the FINOW screen is rather small so difficult to set up the blocks but I guess I could try?

**Comment by lmiekus** [comment]
> > As the best solution for now is to restart the smartwatch. I thought that a quick workaround for existing problem would be to automate the restart with Tasker that is triggered by xdrip notification (alarm) "BR Reading Missed". The alarm would be triggered by xdrip if no BG reading is received for 6 minutes. I have tested it on rooted phone and it works. Now the next step is to test it on finow without root privileges. This way you automatically perform restart without your own intervention.
> 
> Thanks, Tasker is a paid app, right? Is it possible to use "automate"? The issue is that the FINOW screen is rather small so difficult to set up the blocks but I guess I could try?
> 
> @lmiekus I tried something interesting yesterday. Since my daughter is only 6 and she doesn't really know when the watch is sending data to nightscout, I installed teamviewer in both, the collector (FINOW) and my Mac so see if I could remotely turn off and on the BT OR restart the watch... Unfortunately, the FINOW (or teamviewer) did only allow to "see" the current screen displayed in the watch, not to "modify" as if I were touching it... Pity, do you know @lmiekus if this can be changed so that I can remotely access and manipulate the watch? Cheers

Unfortunately teamviewer remote  support works only on a limited number of smartphones. Finow is not among those devices. I did use in the past apowermirror to configure remotely Finow from my computer. This comes with some limitations: 1. you need to connect smartwatch first to your computer via usb with usb debugging enabled on the smartwatch  2. smartwatch and the computer from which you will try to manage that smartwatch have to be in the same network. 3. after restarting smartwatch you have go through point 1. 
The Tasker is a paid app. As to automate I did try that but it had problems with executing restart on the phone.

**Comment by gobeti** [comment]
Thanks @lmiekus would it be possible to have a quick guideline on how to set up the above task in tasker? I have downloaded the trial version for 7 days but it does not look 100% intuitive, sorry. Or maybe you can share that set up via email? Cheers

**Comment by lmiekus** [comment]
> I try set Timer value to 6 minutes in nightly. Still no luck, only restart helps.
@gordan1987 quick question as to what is the rom version after rooting the smartwatch with the files provided by you? Additional were you able to update to the latest rom version 1.5 after rooting was performed? I want to automate the restart of the smartwatch when there are BG Missed Readings alarms from xdrip. For this to work root permissions are required. Before doing rooting I want to check the above.

**Comment by lmiekus** [comment]
> Thanks @lmiekus would it be possible to have a quick guideline on how to set up the above task in tasker? I have downloaded the trial version for 7 days but it does not look 100% intuitive, sorry. Or maybe you can share that set up via email? Cheers
@gobeti You can extract the attached zip file with the folders to your root directory on phone storage. After that go to Tasker click on the three dots icon (upper right corner) -> Data -> Restore -> User Local Backup , confirm file selection "Tasker\configs\user\backup.xml" . I've tested it on Finow and it didn't work, not enough permissions. Rooting is required.

**Comment by gobeti** [comment]
@lmiekus Thanks for that! In the meanwhile, I realized that it is actually good enough to turn off and on the Bluetooth for Xdrip to reconnect again with the G6 (no need to restart the watch).

I am teaching my daughter to do it when the alarm raises so... perhaps this is good enough for the situation.

Ideally, it would be great if Xdrip would turn the BT off and on automatically but it is not the case even though I saw it as one of the BT options in the app. Pity! but, hey, it is still a wonderful app that no Company would dare to develop. We are free to experiment at our own risk so thanks to devs for this!

**Comment by gobeti** [comment]
@lmiekus Great improvement. Check whether you can replicate. 

1) I reset the FINOW to factory settings. I reinstalled Xdrip from scratch (no QR help). I introduced the heroku address manually (big challenge here).

2)  Optimised FINOW Q1 Pro battery settings and unchecked basic Xdrip settings which were not needed. 

Result so far: Improved battery live (up to 20 hours!) and perfect sync with the BT every 5 minutes even though it disconnects when the watch is far away from transmitter it naturally reconnects when in range again.

I will let you know if this changes but, so far, 3 very good days with readings above 95%.

**Comment by lmiekus** [comment]
@gobeti  what version of xdrip did you use? I will try your approach as the next step.

**Comment by gobeti** [comment]
> @gobeti what version of xdrip did you use? I will try your approach as the next step.

I used the February one (no the nightly one) @ https://jamorham.github.io/#xdrip-plus

**Comment by chrisharris751** [comment]
Have you guys tried the official dexcom app at all? I'm running xdrip at the moment, but it still gets to the point where the only thing that gets it working again is a restart. I tried to automate a restart triggered from the missed reading alert with macrodroid, but I need root privileges for that.

**Comment by gobeti** [comment]
@chrisharris751 No, I have not tried it in the FINOW. And I will not because it serves little purpose for my daughter´s needs. Indeed, the watch, sometimes, does not connect to the transmitter. Only solution so far for me, to turn off and on the BT.

**Comment by gigich** [comment]
Anyone tried the 4g version with Android 6.0? Is it working as a standalone collector?

**Comment by gobeti** [comment]
It does work but see above thread for information.

**Comment by svirito4ka** [comment]
Has the watch started to work without any flaws after installing new releases of xDrip+? I launched my watch as a OB1 collector for G5 in non-native mode half an hour ago. It still works without any flaws. I use Nightly build 13th Mar 2019.

**Comment by gobeti** [comment]
@svirito4ka My watch is now running very well. It does not lose connection and, if it does, my daughter gets an alarm and she just turns off and on the Bluetooth. Pretty smooth. Thus, I did not update since 14 Feb 2019 the app. I just do not want to break anything.... :-)

**Comment by svirito4ka** [comment]
@gobeti It is good news! Could you share the settings of your watch?

**Comment by gobeti** [comment]
@svirito4ka This is what I did: reset to factory the watch (Deleted Xdrip since it was working awful), downloaded version 14 feb, didn't copy setting from my old device, set it up in the very same watch (hard to do since keyboard sucks), set up battery permissions for BTs and Xdrip... and that is it, seems to work much better.

**Comment by Wilmamee** [comment]
@gobeti new firmware works very well for us with libre/miaomiao (3 followers): 98% capture, 30 hrs batterylife in last 7 days. Only problem so far is that de finow does not autoconnect on startup, it does reconnect after out of reach.

**Comment by exceter** [comment]
Using Q1 Pro with Dex-5 since april 2018. As everyone here, i am also having BT connection lost issue which we resolve by restarting. Till now was using OB1 mode in non-native mode.
6 days ago had to reinstall OS on smartwatch and reseted transmitter and started using OB1+Native mode. Seems i have less BT connection issues, in most cases i noticed it is able to reconnect if there was no connection for 10-30 minutes, Before had to restart device 2-10 times a days, these days not more than 2-3 times only. As you know, in native mode transmitter keeps data for last 3 hours, so i get 100% readings from transmitter.
But battery is drained fast, before backup was 10-15 hours, now i see it 10 hours is max. Now disabled all unnecessary apps, will see performance.

**Comment by dicko72** [comment]
@gobeti Looking to take your approach, although can't find 14th Feb version. Can you confirm the latest situation with this watch? Thanks

**Comment by dicko72** [comment]
@jamorham is there anything I can give you that will help troubleshoot issues with this device? I'm going to grab the latest nightly and use a spare phone to change settings using QR code. Makes life easier with the small screen etc.

**Comment by dicko72** [comment]
@gobeti thanks for the update. I've reverted to using the phone with the watch as a follower. Despite the bulk my daughter really wants to ditch the phone at school. Maybe one day!

**Comment by Wilmamee** [comment]
@dicko72 we use this watch for our daughter (libre/miao/action launcher/4g no wifi/2 followers/nightscout upload/OOPalgorithm) with the xdrip 20190110 release and have no (re)connection problems. Ticked are only: turn bluetooth on, bluetooth watchdog, close gatt, use scanning and trust auto connect. Not sure what al those options do, but it works just fine. Losing 3 a 4% battery in an hour, when charged overnight it gets us throug the day easily. Only downside we encounter is the chargercable, we sometimes misplace the pins.

**Comment by dicko72** [comment]
@Wilmamee thanks for that. Seemed to work perfectly for 3 hours. Every 5 minutes getting data. Then we left the house and it stopped. I'm assuming a coincidence. The only difference is we use a G5 and I have wifi turned on. What I do notice is if I turn Bluetooth off and then on xdrip has an error saying to turn Bluetooth on. Even though I have the turn Bluetooth on option enabled. Only way to recover seems to be a reboot. When it happens again I'm going to force stop xdrip and rerun to see if it recovers. Might need to root to automate the recovery.

**Comment by 1seam1** [comment]
I have the Finow Q1 Pro, can anyone please tell me how to use Live Wallpapers? I have been researching for days but have not been able to get any working.. :(   im running out of ideas

**Comment by kenfred** [comment]
@dicko72 and @Wilmamee  Are you still using the Finow? Any connection issues?

I picked one up. (Actually they sent me a Q2 Pro instead of a Q1). I have had super flaky connections and I'm looking for help on how to troubleshoot it. I'll make a small BT tweak and it's fixed for a bit, but then goes flaky again. Last night I reenabled "close gatt" and had a good long stretch, but now disconnected again.

**Comment by Wilmamee** [comment]
@kenfred Using a Q2 pro now, checked are:
Turn Bluetooth on
Bluetooth watchdog
Use scanning
Allow blucon unbound

Only issue seems te be that i'ts signal strenght is weaker then de Q1pro. When lying on te sensor while sleaping the Q2 somtimes losses connection an it's distance to te sensor is only 3 meters at that moment. It will autoconnect.

**Comment by kenfred** [comment]
@Wilmamee Thanks for that. I'd try these in the app settings. I'm also interested to know if you had to do something within the watch that's external to the xDrip app. I have tried to go through android's permissions to make sure xDrip has full access to bluetooth and location and is not affected by the battery manager. I'm not sure if I'm missing something.

**Comment by kenfred** [comment]
@jamorham are there any settings or logs I could provide that would help move this issue?  Thanks!

**Comment by gobeti** [comment]
@kenfred I got the Q1 for my daughter and it just works fine. About 20 hours of battery with no major issues

**Comment by kenfred** [comment]
@gobeti Thank for that data point. Can you tell me what your other hardware is and what settings you're using? We're on xDrip+G6+tSlim+Finow. xDrip was working great when we had a samsung phone as the collector. We switched to the Finow being the collector and the master of a sync group, but it is not staying connected.

Are you using you own google account on the watch or did you create a google account for your daughter and manage it through Family Link?

**Comment by Navid200** [comment]
Consolidated all watch support requests: https://github.com/NightscoutFoundation/xDrip/issues/1872
