### ISSUE TITLE
10.28.2018 Nightly Wear OS Null Null Complication problem 

### ISSUE THREAD

**Issue by opasha** [NightscoutFoundation/xDrip#651]
SOLVED: See my last post. JUST ADD A CALIBRATION on your phone app. 

Current setup: Mi Max 3 (phone) + Ticwatch Pro, Ticwatch E (Wear OS watches) + MiaoMiao (cgm bluetooth transmitter) + xDrip+ (app) 

Currently on 10.28.2018 nightly. Before this update, Ticwatch Pro (Wear OS 2.1) and Mi Max 3 (Oreo 8.1) had zero issues with the complications refreshing properly. The xDrip+ app watchfaces sync and work correctly. I use Pear Modular and A/D watch faces with no problems when adding the xDrip+ complication in previous versions. However, on this nightly, there's the famous null null issue. As you know, you can't rewind the wear OS xDrip+ download. Whenever I update the xDrip+ app on my phone, it's done with the internal updater of the xDrip+ app. Then, we get the toast to update our xDrip+ Wear OS app, so we un-install and re-install the latest wear version. I think the problem is with the latest wear version? Any advice is helpful. Thank you.

I've rebooted both watch and phone. I've installed the previous 10.23.2018 (this causes mismatch with the wear app), thus the app update toast returns. Nothing works to rectify the Null Null Complication problem.

**Comment by opasha** [comment]
Just tested my Ticwatch E, which has the older wear 10.23.2018 xDrip+ app installed (it's telling me to update to 10.28.2018 version), but it's showing the correct complication data for xDrip+ on Pear Modular watch face (still have 10.28.2018 on phone). I'm connected to both watches currently. So, I know for a fact that it's the 10.28.2018 xDrip+ Wear OS app. Please update. Thank you.

**Comment by jamorham** [comment]
Nothing has changed in the wear component between 23rd - 28th Oct and other changes were extremely minimal and I doubt very much would be related.

**Comment by opasha** [comment]
Well, it caused an issue. I've read through all the old null null threads. Someone referred it to accidental reversion of code (it happens). Would you mind uploading the previous wear OS apk of xdrip so I can test? I'd appreciate it.

**Comment by jamorham** [comment]
All the code is available simply by clicking the `Code` tab on github, you can review the changes made between versions. The APK files are generated directly from the github commits with automatic continuous integration. I very much doubt anything unexpected has happened.

**Comment by opasha** [comment]
You can doubt all you want, but the error is 100% there. I'm not some newbie 😄. By testing, I'm helping you. I updated to the latest 10.31 nightly for the phone. No issues on old 10.23 wear OS xdrip apk. Then wanted to test and updated both watches to the updated 10.31 (uninstall on watches from the playstore and reinstall otherwise you get the toast that app needs updating). Guess what? Null null compilations on both watches. Care to elaborate?

**Comment by opasha** [comment]
Your update even says 10.31 within the updater but the file downloaded every time says 10.30. Not that it matters, but it also fools the internal updater thinking 10.30 is older even though it's the same file. 

[url=https://postimages.org/][img]https://i.postimg.cc/d34QY4hm/Screenshot-2018-10-31-13-50-07-537-com-eveningoutpost-dexdrip.png[/img][/url]

[url=https://postimages.org/][img]https://i.postimg.cc/66DYVtTK/IMG-20181031-134421.jpg[/img][/url]

[url=https://postimages.org/][img]https://i.postimg.cc/L5Zg6dMB/IMG-20181031-134525.jpg[/img][/url]

**Comment by opasha** [comment]
Just an update. Seems the latest version (10.30) as seen above on my two watches fixed the complication issue with a new sensor. I'll update if anything changes. Thank you.

**Comment by opasha** [comment]
I figured it out! 😄😄😄. Updated to latest November 2 nightly and null null Complication issue returned on both watches. Xdrip watch faces as before had no issues. 

The SIMPLE FIX is to ADD a single CALIBRATION (the same reasoning as starting a new sensor where you are forced to add 2 calibrations). Please mention this fix to everyone on Android Wear. 👍🏼

**Comment by gregorybel** [comment]
I added this solution here: https://github.com/gregorybel/xDrip/blob/gregorybel-update-docu/Documentation/WatchGuide.md
thanks!

**Comment by daniel2887** [comment]
Hi,

I'm running into this same null complication issue on my Fossil Gen 5, running xDrip+ version e14bae1-2020.07.13, watch face "Next Gen Digital" and using the xDrip complication. xDrip+ is using my Nightscout website as a data source. When I try to enter a calibration to work around this issue, I get the "impossible slope" error message. Any ideas?

**Comment by farcusnz** [comment]
is it possible to get this bug reopened? The solution to add a calibration works only for a single reading for me. I am using xdrip+ with oops. If I add a calibration in xdrip then the reading displays in my watch complication. However, it does not update and after a period of a few mins displays "null null" again.
Is this a result of me using oop with xdrip?
![watch](https://user-images.githubusercontent.com/29653298/117521931-94ef4a80-b004-11eb-8438-829f99225561.jpg)

**Comment by mairamaa** [comment]
Using the calibration approach only works for a single reading and that one value is left frozen on the complication, despite the actual sensor values changing in the background. Temporarily changing to a different watchface and later returning back to the initial face with xDrip complication has the complication value change to `old <MM>m`. This value is never updated. Complication display is never reverted back to the initial `null, null`. xDrip+ proprietary watchface works ok and the updated sensor values are synchronized immediately there.

xDrip app logs display errors similar to following
```
wearjamorham listener

syncBGData new BgReading calibrationUuid not found by byuuid; cannot save! calibrationUuid=null bgData.calibration_uuid=null bgData.uuid=8829840d-9b89-41ee-bd58-cc02ae7c362e timeString=2023-04-28 09:09:13
```

Using Samsung Galaxy Watch 5 Pro, Libre 2 EU with oop2, Samsung Galaxy S22 Ultra, xDrip+ Version 3254cca-2023.03.23

**Comment by Giorgio-Zarantonello** [comment]
@mairamaa any solution?

**Comment by hlriffel** [comment]
Can this issue please be reopened? I'm also facing this problem using a Libre 2 EU with OOP2 and a Ticwatch Pro 5.

Changing the "OOP2 algorithm calibration" to any value other than "No calibration" makes the complications work, but it is not really a solution for me as it shows misleading readings regardless of how many calibration values I add.

**Comment by Navid200** [comment]
@hlriffel If a developer can and wants to fix this, they can.
Having an open issue doesn't expedite anything as long as no developer is interested in fixing it.

There doesn't seem to be a developer interested in WearOS.
