### ISSUE TITLE
display issue

### ISSUE THREAD

**Issue by jo1st** [NightscoutFoundation/xDrip#658]
why everything is so small all the sudden and the glycimic levels all the way to 600?
how can I get the usual display back? 
![screenshot_20181031-095952_xdrip](https://user-images.githubusercontent.com/36887391/47759778-8a95bc80-dcf4-11e8-9f7c-c0eff83433e7.jpg)

**Comment by dave1812** [comment]
what version are u on?  see the version on the System Status screen.

**Comment by jo1st** [comment]
d1d4887-2018.09.08

funny is that it eventually fixed it self all the sudden but weird

**Comment by DunePlodder** [comment]
You had some very high readings at about 15:00. This caused xDrip to resize the vertical scale. After a few hours those readings are no longer on the screen so the vertical scale is resized to fit the newer readings.

**Comment by jamorham** [comment]
Recent versions include the voice command: `clean up excessive high readings` which can resolve this quicker than waiting for 24 hours to pass.
