### ISSUE TITLE
MiaoMiao (Libre) BG reading time

### ISSUE THREAD

**Issue by thomasmenges** [NightscoutFoundation/xDrip#660]
Is it possible to change the period time of BG reading ? In the Glimp App you can manage the BG reading time. This helps to clear the noise effect of the BG readings.
The BG value of my miaomiao is often read only every 10 to 14 minutes and this period im my opinion is too long.

**Comment by gregorybel** [comment]
this looks like a connection issue, like 3 or 4 other issues here

**Comment by Navid200** [comment]
@thomasmenges Would you please close this issue if it has been resolved already?
Otherwise, would you please use the support channels?
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks

**Comment by thomasmenges** [comment]
Cannot answer the question if issue exists anymore. I'm using Dexcom now and for me the problem is solved.
