### ISSUE TITLE
enhancement request: OOP built in?

### ISSUE THREAD

**Issue by castdoom** [NightscoutFoundation/xDrip#662]
i currently use the "oop" calibration algorithm, the issue is i just got a sony SW 3 to use wear instead of my phone as the collector and it doesnt seem to work with this calibration algorithm on, is there a way to make it built into xdrip rather than an addon?

**Comment by dabear** [comment]
No. That would taint xDrip-plus with Abbot proprietary code.

**Comment by castdoom** [comment]
oh didnt know it would cause issues
