### ISSUE TITLE
Latest Note 9 update

### ISSUE THREAD

**Issue by dougstanton** [NightscoutFoundation/xDrip#671]
The latest note 9 security update has made Xdrip useless. I've had it running for weeks and love it but after the latest update Xdrip starts missing readings and eventually just never recovers

**Comment by gregorybel** [comment]
I think this issue is same as https://github.com/NightscoutFoundation/xDrip/issues/671

can you maybe close your issue and add add comments on this one?

**Comment by dougstanton** [comment]
Issue already exist

**Comment by eneficus** [comment]
I am having the same issue xdrip useless after latest update does not work at all had to failback to dexcom official app

**Comment by dougstanton** [comment]
I gave up and have been using nightwatch with dexcom share and pulling the
data from there.
