### ISSUE TITLE
How to delete "Noisy" warm up readings

### ISSUE THREAD

**Issue by thevascgmdb** [NightscoutFoundation/xDrip#673]
hi, i am a new user of xdrip+ and am loving its functionality. Well done to the developers and everybody thats has made the app something that makes my and other peoples lives better!!

A quick question.

I use a Libre Freestyle sensor (i am in australia) to collect my raw data and then transfer that to my Xdrip+ on my samsung s9 via a mioa miao. All seems to work great.

Last night, i had to renew my Libre freestyle sensor and when i reapplied the new one, there was a significant amount of noisy data which showed readings that were nowhere near my actual readings.  

I would like to delete those readings so they doesn't throw my averages off (i love my stats).  I have attached an image of what i am seeing.  note the time between 3am and 4am

Is there a way to delete only these readings?

Thanks in advance.

![image](https://user-images.githubusercontent.com/43108702/48034724-abf31e80-e1b4-11e8-9ad4-a469caf36bf3.png)

**Comment by AdrianLxM** [comment]
Enable the data tables in the settings.
Then in the BG data table long-click a reading that you want to exclude from the statistics.

**Comment by AdrianLxM** [comment]
Closing this issue. If my response above does not solve it, please reopen.

**Comment by thevascgmdb** [comment]
awesome, thanks heaps
