### ISSUE TITLE
G6 start requests calibration

### ISSUE THREAD

**Issue by ddellspe** [NightscoutFoundation/xDrip#675]
I'm on the latest version of xDrip and I'm unable to get my sensor session to start, the errors that I'm getting are the following:
Ob1G5StateMachine
```
Session Start failed info: 1969-12-31 18:00:00 1969-12-31 18:00:00 1969-12-31 18:00:00
SessionStart Failed: Clock not synchronized or other error
Starting G6 sensor using calibration code 9159
```

Running the 11/2 build on a Pixel 3 XL.  The session is now requesting that I calibrate, but I'm no the proper settings for the native algorithm to work appropriately

**Comment by ddellspe** [comment]
Looks like this was an issue of the transmitter being expired, I guess it's another reason for the error that was being received by this specific error code (0x04) [here](https://github.com/NightscoutFoundation/xDrip/blob/7cb725783429de7a02342194f4fc68a1fc66c0c0/app/src/main/java/com/eveningoutpost/dexdrip/G5Model/SessionStartRxMessage.java#L81) and [here](https://github.com/NightscoutFoundation/xDrip/blob/7cb725783429de7a02342194f4fc68a1fc66c0c0/wear/src/main/java/com/eveningoutpost/dexdrip/G5Model/SessionStartRxMessage.java#L81)

**Comment by adanvdo** [comment]
1. @ddellspe I ran into this problem tonight. I attempted to start a new sensor and transmitter at the same time.  I have been having issues getting the sensor to start correctly. Mine is a brand new transmitter, so im not sure why it's having problems.
