### ISSUE TITLE
Xdrip doesn't connect to blucon

### ISSUE THREAD

**Issue by loopinglea** [NightscoutFoundation/xDrip#680]
I have attempt all the tips I found, but nothing work. I have the problem since a few days, it has worked before for a few weeks without problems. Can somebody help me?

**Comment by gregorybel** [comment]
did you checked this?

https://github.com/gregorybel/xDrip/blob/gregorybel-update-docu/Documentation/blukon.md

what is exactly your problem?

if it really doesn't connect, maybe you input wrong pin?

**Comment by loopinglea** [comment]
Yes I have checked it, nothing worked... the pin is correct, I had used it many times before. In general i get no data from the blucon, cause it didn't connect.

**Comment by gregorybel** [comment]
then that could be a hardware issue. 
is led flashing shortly when you push 2 times reset button?
If not maybe battery empty or contact to battery need to be bent a bit (be careful).
Or your device is dead, need claim it.
did you try with manufacturer App?

**Comment by Navid200** [comment]
@loopinglea Would you please close this issue if it has been resolved?
Otherwise, would you please use the support channels?
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks
