### ISSUE TITLE
Red On Black

### ISSUE THREAD

**Issue by Diabeticliberty** [NightscoutFoundation/xDrip#682]
Does anybody have a way of changing the red text colour that appears during warnings of 'low blood sugar' events? At times of near hypoglycemia the text is extremely difficult to read. I have tried at length changing colour settings but the red text seems preset.

**Comment by Navid200** [comment]
@Diabeticliberty Would you please explain exactly what text you mean?
Do you mean the main blood glucose value shown almost at the top of the screen?

**Comment by Diabeticliberty** [comment]
It appears I didn't explain myself adequately. I meant every piece of information that shows up on screen in red at times of low blood sugar.

**Comment by Navid200** [comment]
Do you mean this?
![Screenshot_20210401-112405](https://user-images.githubusercontent.com/51497406/113317414-5962b180-92dd-11eb-950d-75df103b27a6.png)

**Comment by Diabeticliberty** [comment]
Hello, yes that's it. During times of hypoglycemia it is extremely difficult to read. In fairness I struggle with red text against a black background at most other times too. When low on glucose it is really challenging

**Comment by Navid200** [comment]
There is no significant contrast of dark red on black, no matter how good someone's vision is.  
So, I'm not surprised.  I agree with you and would like to change the text color to white regardless of value.  
But, that would be a long-term project and may not be approved considering how everyone has got used to everything as is.
I will work on that.

But, it is possible to change the background color.  If you change the background color from black to gray, you may get better contrast.
You can change colors:
Settings -> xDrip+ Display Settings -> xDrip+ Color Settings

The background color is "Main Chart Background".

If you mess things up, you can just tap on "Reset to Default" for each color individually.

**Comment by Diabeticliberty** [comment]
Hello again, thanks for getting back to me. I tried some time ago changing everything I could possibly find to try and make the colour contrasts work better for me. Nothing really seemed to work all that well which was in essence why I posted the issue on here. In all fairness Xdrip+ has brought me nothing but good since the very first day I started using it. It would of course be extremely good to be able to find a workaround the red and black issue but ultimately it is the highly enhanced way Xdrip+ allows me to monitor and control my type 1 condition that really matters most to me.

All the very best to you and all involved in Xdrip+

**Comment by Navid200** [comment]
@Diabeticliberty Would you please post a screenshot of the following page?

Settings -> Alarms and Alerts -> Extra Alerts (xDrip+)

**Comment by Diabeticliberty** [comment]
![Screenshot_20210409-133904_xDrip+](https://user-images.githubusercontent.com/44977244/114181236-29e52200-9939-11eb-8ff0-71cb56213d7b.jpg)

**Comment by Diabeticliberty** [comment]
Hello, I hope this is what you are looking for. If you need anything else then please just ask.

**Comment by Navid200** [comment]
Yes, that's what I wanted to see.

It seems that you have not enabled the alarm.
![114181236-29e52200-9939-11eb-8ff0-71cb56213d7b](https://user-images.githubusercontent.com/51497406/114181557-a4994780-990f-11eb-9679-89ad777d7e7e.jpg)

I would just like to inform you that if you enable it, please see the attached marked image, you will get an alarm when the predicted glucose drops below your Low value in less than the time you can specify in minutes (Alarm at Forecasted Low mins).
Then, even though you may have difficulty seeing the reading, but you can choose a specific sound clip for the alarm to leave no doubt what the alarm is.

**Comment by Diabeticliberty** [comment]
Hmmmmm interesting. I have never utilised that particular function. I will however now do so. Thank you for pointing this out to me. Would you now like me to close this issue since you have resolved it as much as is possible without remapping the entire colour scheme of the app?

**Comment by Navid200** [comment]
Please leave open for now.

You can specify unique sound clips for your different alarms.  You can even use your own sound clips.  This may allow you to identify which alarm it is without having to focus on small print.

**Comment by Navid200** [comment]
Closing it now.
I labeled it (postponed) so that we won't forget.
