### ISSUE TITLE
G6 uploaded as G5

### ISSUE THREAD

**Issue by quizzmaster** [NightscoutFoundation/xDrip#684]
The uploaded device String using a Dexcom G6 is "xDrip-Dexcom G5 Native" but should be "xDrip-Dexcom-G6 Native".

**Comment by jwoglom** [comment]
I haven't tried the patch with newer versions of xDrip but #559 should fix this

**Comment by quizzmaster** [comment]
With the latest nightly the device string is "xDrip-DexcomG5 G5 Native". Now the G5 is doubled.

**Comment by Navid200** [comment]
@quizzmaster Has this been resolved?

**Comment by quizzmaster** [comment]
@Navid200 no, it's still "xDrip-DexcomG5 G5 Native" for the Dexcom G6

**Comment by Navid200** [comment]
Where is this uploaded to?
How can I see this?  I also use a G6.

**Comment by quizzmaster** [comment]
It is uploaded to nightscout. Just look at the endpoint for the BG values `/api/v1/entries/sgv.json`

**Comment by Navid200** [comment]
Sorry, I am a novice.  Can you be more specific?  When I go to Nightscout, I see my blood glucose versus time in a graph.

**Comment by quizzmaster** [comment]
Well, just append `/api/v1/entries/sgv.json` to your Nightscour URL and you get the latest blood glucose informations from the API (in json format).

**Comment by Navid200** [comment]
Thanks.

**Comment by Navid200** [comment]
@quizzmaster Would you please try the latest Nightly (May 10, 2021) and see if this is fixed or not?

**Comment by Navid200** [comment]
@quizzmaster 
Please reopen if it still has not been fixed.
