### ISSUE TITLE
Tomato battery not available on follower mode

### ISSUE THREAD

**Issue by parapenT1sta** [NightscoutFoundation/xDrip#689]
Is it possible to add Tomato battery status on follower mode? I tried all options and seems to no be available. It's working fine with Nightscout but not with xDrip+.

**Comment by bboi61** [comment]
Maybe then you could change the name, in MiaoMiao.
Thank you

**Comment by bboi61** [comment]
Maybe then you could change the name, in MiaoMiao.
Tomato was the name of the original Chinese app
Thank you

**Comment by parapenT1sta** [comment]
> Maybe then you could change the name, in MiaoMiao.
> Tomato was the name of the original Chinese app
> Thank you

I think it's a good suggestion too :)

**Comment by bordeb** [comment]
If this is going to be addressed I would like to add upon that it would also be good to resolve the issue when "Tomato battery" is renamed to "Bridge battery" in the situation when "Libre Bluetooth **+ wifi**" is selected as source. If only "Libre Bluetooth" is source then it is ok, but when one selects "Libre Bluetooth + wifi" the battery status is renamed from Tomato to Bridge

**Comment by Kywalh** [comment]
Same with blucon.... Not visible as followers...

**Comment by IgnisAsphodel** [comment]
It'll be great to add sensor age to folowers homescreen too)

**Comment by parapenT1sta** [comment]
@jamorham
@ tzachi-dar

🙏

**Comment by stefanchavdarov** [comment]
would be useful feature for me too

**Comment by Navid200** [comment]
@parapenT1sta Is this still the case or are there any updates?

**Comment by parapenT1sta** [comment]
@Navid200 Was fixed already. :)
