### ISSUE TITLE
Plugin value not shown on Wear OS 1.x 

### ISSUE THREAD

**Issue by nsghub** [NightscoutFoundation/xDrip#692]
The issue #595 was closed and that might be true for a complication on Wear OS 2.x
But the watchface on Wear OS 1.x still doesn't show the plugin value all the time (it sometimes does). An indicator would be nice to see when a plugin value is used.

**Comment by tolot27** [comment]
@nsghub Is the problem resolved, meanwhile? If not, please ask for help at the the support channels https://www.facebook.com/groups/xDripG5 or https://gitter.im/jamorham/xDrip-plus.

**Comment by jamorham** [comment]
Closed by request due to inactivity
