### ISSUE TITLE
Pure BT Standard CGM profile data source

### ISSUE THREAD

**Issue by SindreSB** [NightscoutFoundation/xDrip#694]
Hi,

I see there is a service in the code that implements a pure CGMS profile CMGS, but it is not in the data source list on the settings page. This would be for a custom Dexcom bridge. Is there any of the other options that, while under a different name, works with the pure CGM profile? 

If not, then I will look at enabling it my self,, but are there any documents on the architecture of the app so that I get idea of how to get started? Or, would it be easier to implement different services on the BLE device itself as to better work with any of the existing data sources?

**Comment by jamorham** [comment]
Which class are you referring to?

**Comment by SindreSB** [comment]
This is the one I though of, but I realize it might not be the continuous profile, and only the single measurement one.  
        xDrip/app/src/main/java/com/eveningoutpost/dexdrip/Services/BluetoothGlucoseMeter.java
      
So I quess there isn't a pure CGMS probile supported (or anything fairly similiar). I assume the issues might not be the best place to ask about this. Is there any other place to ask questions about the app?

**Comment by SindreSB** [comment]
As far as I know, no, but I'm working on one now as a more reliable and power efficient version of the wixel based bridge, so figured I'd check how easy it would be to add support for it in xDrip.
