### ISSUE TITLE
Not speaking readings

### ISSUE THREAD

**Issue by Kustomwireless** [NightscoutFoundation/xDrip#699]
On all versions after 2018.11.15 my Motorola G4 set up as a follower will not speak any readings after the 1st one when you start speak readings.  Any suggestions or help with this.

**Comment by jamorham** [comment]
I've tested with 2018.11.29 and 2018.12.01 versions using follower mode and speak readings is working on a Samsung Galaxy A3 running Android 8.0

**Comment by jamorham** [comment]
Thank you for your testing. I have looked through all the commits between 15th Nov and 25th Nov and there is only one thing I think it could be. I will revert that for the next nightly.

**Comment by jamorham** [comment]
Please try the 3rd Dec nightly

**Comment by Kustomwireless** [comment]
It is working correctly  now on 3rd DEC  version  Thank you so much.
Again Thank you for all you do and this GREAT APP
My Wife would be lost without Xdrip-plus I only can only HOPE you will make it work with 14 day US sensors PLEASE

**Comment by jamorham** [comment]
Do you get any event log messages on the follower like: `Received a bg reading that appears to be in the future:` ?

Regarding the US 14 day Libre sensors, I think there would need to be a working group that gets some really good data sets to make any progress.

**Comment by Kustomwireless** [comment]
I just went and looked  every reading has an error message in the event log.
I wish I could offer some help on the 14 day sensor I am much more a hardware guy than a coding person. So for now we are buying as many 10 day sensors as i can find.
