### ISSUE TITLE
huawei EMUI Bluetooth issues and missed readings

### ISSUE THREAD

**Issue by Mikeyatrum** [NightscoutFoundation/xDrip#705]
This isn't necessarily an issue with xDrip+ but its an issue with all users trying to utilize a Huawei phone. Looks like the Huawei EMUI software does some of its own BLE trickery and causes issue with scanning and connecting thus causing missed readings. The error you will see in the logs is this:

11-08 17:55:43.935 11438 11503 E Bth     : G.GattService:App 'Your APP' is scanning too frequently on screen off

See here: https://github.com/AltBeacon/android-beacon-library/issues/554

They didn't find an answer for it but I was thinking an easy work around would be to have an option wake the screen for a second while connecting. It's not ideal but would probably open up xDrip use to the Huawei phones.

**Comment by jamorham** [comment]
Can you let me know what type of collector you are using within xDrip and the android version of the affected phone? 

If you are using G5/G6 can you check if the `Minimize Scanning` option is enabled and if not enable it.

**Comment by Mikeyatrum** [comment]
Thanks for the quick reply. I'm 90% sure I had that minimize scanning option checked while messing around with it for the last 5 days. Today it's not checked, I probably messed with it. I've checked the box and will see if it makes a difference.

Collector: OB1
Android Version: 7.0.0
Dexcom Version: G6
xDrip Version: 2018.09.08

**Comment by Mikeyatrum** [comment]
Just validated with the "minimize scanning". Sure enough after the screen went off I started losing readings. I'm currently 30 in without a reading. Woke up the screen and had readings back within a few minutes. This is the pattern.

**Comment by opasha** [comment]
Not sure if you've tried this, but have you tried locking xdrip+ in Recents. Just like miui, emui kills apps aggressively. I know because I've owned a Mate 9. Try that and see?

**Comment by Mikeyatrum** [comment]
Yup tried that. Funny you mention that though. I have found if I don't
force it to the UI thread that it does get killed off eventually even if
locked in the recent's screen. That said, today's reading have been a bit
better since re-ticking the "minimize scanning". I'm getting a lot more
consistent 5 min reading. I still see gaps of 10 - 15 minutes but I'm not
seeing the 30 - 60 minutes I was seeing. I'll keep it at these settings for
now.

**Comment by opasha** [comment]
How about this:
"Solution
We had the same issue in our app. The solution in our app was to change the setting in Settings

Settings->Apps & notifications->Apps-><your app>->Battery

Set App launch to 'Manage manually'
Auto-launch - activated
Secondary launch - activated
Run in background - activated"

**Comment by gregorybel** [comment]
- yes these options are important.
- lock App in App Manager.
- make sure Xdrip ignores battery optimization
- might want to add persistent notification

I have a p20 pro with 100% capture rate for g5.

**Comment by Mikeyatrum** [comment]
I'm not finding those settings on the Huawei. I'm back to 10 - 30 min random gaps.

**Comment by Nalla306** [comment]
I have a mate 20 pro and don't suffer this issue with emui.

In settings>apps>apps click on 3 dots in top right and select special access then battery optimisation. Change the drop down to all apps and find xdrip, click on it and check 'don't allow'

Next in Settings > battery > app launch find xdrip and click to select to manage manually and make sure all three options are selected.

This is with the latest emui, hopefully you have those options.

**Comment by Mikeyatrum** [comment]
Yeah this older version of EMUI doesn't have the "app launch" options. It's already set to ignore battery optimizations. I'll looking into finding an upgrade path on this phone.. if not looks like I'm looking at replacing it.

**Comment by gregorybel** [comment]
look under battery settings and you need to allow xdrip launch.

then lock app, right corner, look at app running and click on lock

**Comment by mountrcg** [comment]
@gregorybel could you plz outline the G5 Debugging options you use in xdrip. Anytime I lock the Huawei P20 Pro with Android version9 I loose my readouts. The App launch options under Battery I set for xdrip and aaps to manual and also did not allow the battery optimizations for both in Apps special access.

**Comment by gregorybel** [comment]
did you Check this?

https://androidaps.readthedocs.io/en/latest/EN/Usage/huawei.html

**Comment by mountrcg** [comment]
Yes I did, as this is the summary of this thread. I fou d the issue yesterday. In Setti gs>Battery it needs to be put in Performance mode. I had it in Power Saveing mode.

**Comment by mountrcg** [comment]
Also took me a while to figure out how to get the lock on the Apps in the switcher - pull the app down.
The persistent notification in xdrip+ I did not find. But I capture 100% now, also in sleep mode. Thanks a lot.

**Comment by gregorybel** [comment]
Great! would you like to add your findings in the documentation page? Like this you will help other people

**Comment by mountrcg** [comment]
Yes. How, I looked but couldn't see how to participate.

**Comment by gregorybel** [comment]
https://androidaps.readthedocs.io/en/latest/EN/make-a-PR.html

**Comment by Navid200** [comment]
@Mikeyatrum If you need help with G6 connectivity, please use the support channels.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
We can always re-open this if it is really an xDrip bug.
