### ISSUE TITLE
Multiple Insulin Profiles

### ISSUE THREAD

**Issue by doc77** [NightscoutFoundation/xDrip#706]
I know this has been brought up before, but could you incorporate multiple insulin profiles in xDrip+?

This would allow for basal and bolus differential in both MDI and pump, extended boluses, FIASP, and any other insulin situations.

This is the one area that xDrip+ is severely lacking in an otherwise unmatchable app. It's adoption would take this excellent app to the next level.

**Comment by gruoner** [comment]
@doc77 by the end of last year something like you suggested was merged to master #1080 
check it out and rise improvement requests if it doesn't fit your needs.....

**Comment by Navid200** [comment]
@doc77 Is this still a shortcoming?

**Comment by doc77** [comment]
@Navid200  Yes it is. Basal insulin is poorly addressed, bolus insulins are incompletely listed.  What has been done so far is an excellent start but it still requires significant polishing.

**Comment by Navid200** [comment]
@doc77   I read somewhere someone claim "the basal should be adjusted until your average is flat;  it's only the bolus that should play a role in the analysis".  
Would you share your opinion/knowledge in that respect please?

**Comment by doc77** [comment]
Basal can be used to accommodate small snacks during the day, instead of bolusing for say, 5-8g carbs. It would also be valuable to observe a particular basal's activity profile for you individually. It is also important in figuring TDD. Bolus calculation pertains more to an immediate carb load, like a meal or a snack of 10g carbs or more.

I have been using insulin for 50 years, analogs for over 20, and have come to recognize that there are many strategies for using it. The only thing you need to figure out a lot of those strategies is data.

**Comment by Navid200** [comment]
Duplicate: https://github.com/NightscoutFoundation/xDrip/issues/531

**Comment by Navid200** [comment]
Please don't open duplicate issues.  
We need to organize the issues so that they can be prioritized.   Redundant issues don't help that.  
I am going to close this.  If you have anything here that you believe you cannot post in the original post, please let me know and we can re-open this.
