### ISSUE TITLE
Reactive graph stopped being...reactive

### ISSUE THREAD

**Issue by acollien** [NightscoutFoundation/xDrip#707]
Hi Team, until recently, the main graph would plot BLG and only show me the relevant section of the grpah i.e. if I am below 10 all the time, I'd never see the upper part of the graph (higher 12-24 section). This made it easier to read as it would just crop what I was seeing and make it larger on the homescreen (hope this is making sense). 
Recently, it stopped do thing this - I see the entire graph, up to 24+. So everything smaller (bit like having a high resolution on a monitor). I haven't changes any settings, just happened a couple days ago. And I can't find a setting to fix it. Thanks for your help.

**Comment by jamorham** [comment]
Do you have a reading in the last 24 hours which goes up to this height of the graph? Once that period passes (eg 24 hours) the graph will then auto-scale to whatever your current range of readings would be.

**Comment by acollien** [comment]
> Do you have a reading in the last 24 hours which goes up to this height of the graph? Once that period passes (eg 24 hours) the graph will then auto-scale to whatever your current range of readings would be.

Nah - no high values. Looks like it was just the 1st hour calibration. I started a new sensor, so it must just be getting it's eye in, in the first 24 hours, as it's righted itself now and has auto-scaled.
