### ISSUE TITLE
Extra Status Line Treatment Insulin Total

### ISSUE THREAD

**Issue by doc77** [NightscoutFoundation/xDrip#71]
It would be helpful to be able to have the Extra Status Line display the current day's Treatment Insulin Total.
Thanks

**Comment by gitanO0** [comment]
To add to this request:  I'd like to see two more options for that extra line status. Bolus insulin administered in the same time period (already commented on by doc77) and a ratio of that insulin total to carbs.
So... for an example of 9pm, it might show 120 g carbs, 20 units insulin and for the ratio, something like .167 (20/120).
The idea is that that .167 value should be pretty constant from day to day... deviations on any significant level would indicate perhaps, the person is getting sick, or maybe insulin resistance.

**Comment by jamorham** [comment]
The 1st March nightly contains extra status line option for Total Insulin, please test and let me know if it works.

**Comment by roycesimpson** [comment]
Working as intended.

**Comment by doc77** [comment]
Works fine. Thank you very much for implementing this feature.
