### ISSUE TITLE
Menu title language change

### ISSUE THREAD

**Issue by parapenT1sta** [NightscoutFoundation/xDrip#714]
Using Portuguese language, some menu titles change to English after some use. I need to restart the phone to get back to Portuguese language

For exemple: "Settings on external storage"

![48383432_2035062066612013_1750755607608033280_n](https://user-images.githubusercontent.com/608650/50146908-c25cc180-02ac-11e9-9811-ecb623ff0fa5.png)

![48368401_2242766312713192_191319326790254592_n](https://user-images.githubusercontent.com/608650/50150558-40719600-02b6-11e9-8d8f-d90351bf44d2.png)

**Comment by parapenT1sta** [comment]
And also the speaking language changes even when I force a locate language.

**Comment by Navid200** [comment]
@parapenT1sta Is this still a problem?

**Comment by parapenT1sta** [comment]
@Navid200 It doesn't happen that often. I thought I had closed this issue.
