### ISSUE TITLE
changelog needed

### ISSUE THREAD

**Issue by stefanchavdarov** [NightscoutFoundation/xDrip#715]
I'm looking for a changelog in app for nightly releases pre or post update

**Comment by parapenT1sta** [comment]
Do you check the Code Commits?

**Comment by stefanchavdarov** [comment]
...in app... or in pre-download window

**Comment by jamorham** [comment]
Change log information is here: https://github.com/NightscoutFoundation/xDrip/commits/master

xDrip is unusual for an Android app that you can simply upgrade and downgrade at will without data loss. Compatibility is maintained over at least a 2 year window. If you have any problem with the newest version, simply reinstall the previous version from your downloads folder. There is no need to uninstall the current version.

**Comment by Navid200** [comment]
@stefanchavdarov If you are happy with the explanation provided by jamorham, would you please close this issue?
If not, would you please replay?
Thanks

**Comment by tolot27** [comment]
The commit log is not really helpful and requires understanding of the code. A "real" changelog would be very useful. Sometimes, code changes fix issues but the commit log does not contain an issue number, i. e. #1635.

**Comment by stefanchavdarov** [comment]
Changelog can be as simple as .txt and may be short bw each version with each nightly listed trailing in same txt.
'new features' deserve a line of their own; Bug fixes ot minor changes just write as 'misc bug fixes' 
End user doesnt read code well.

**Comment by Navid200** [comment]
This issue requests for change logs (change logs needed).
The developer clearly explained what is available.

Some may not be happy with that answer.
I see two options.  
Step up and do the work and provide change logs, or we can close this issue.

Can anyone see a third option?  Demanding someone else to work for us is not a reasonable option considering we are all volunteers.

**Comment by Navid200** [comment]
Duplicate: https://github.com/NightscoutFoundation/xDrip/issues/434
