### ISSUE TITLE
Diasend integration

### ISSUE THREAD

**Issue by pmarguelles** [NightscoutFoundation/xDrip#716]
It is an interesting option because Diasend incorporates the ambulatory glucose profile (AGP) which is a globally recognized standard for visualizing continuous glucose monitoring (CGM) so that it is easy for patients and healthcare professionals to identify glucose patterns and trends. independent of HbA1c.

**Comment by doc77** [comment]
XDrip+ also incorporates the AGP.  It's found in statistics, and you can get it for today, yesterday, 30, 60, and 90 days.

**Comment by pmarguelles** [comment]
Great, it's true, although it could include more data and be more complete.
Thank you

**Comment by j7m** [comment]
Yahhh! It's will be greate! Can take information from Omnipod and xdrip!

**Comment by razerrazer** [comment]
It's there any way to upload your AGP data from xdrip to Diasend to share your data with your hospital?

**Comment by Navid200** [comment]
Is there anything you can think of that you can get from Diasend that you cannot get from Nightscout?

**Comment by Navid200** [comment]
Please answer questions before reopening.
