### ISSUE TITLE
Suggestion: Multi Window Support

### ISSUE THREAD

**Issue by mistermintsgh** [NightscoutFoundation/xDrip#719]
Can I suggest that xDrip implements multi window support please?

https://developer.android.com/guide/topics/ui/multi-window

Reason for this struck me when I was driving home from work the other day. Using my phone as a sat-nav I thought it would be great to be able to see my map and directions on one side of the screen as well as my glucose reading on the other. I started a multi window session, and my phone warned me that "this app may not support multi window" (although it didn't specify which app it was referring to). I thought it looked like it was working OK, but when I stopped at a traffic light and made the xDrip window the one in focus by reading suddenly changed and I realised what I had been looking at for the past 20 minutes wasn't an accurate reading after all.

If there's a way to make it so that even if xDrip isn't the focus/on top window it would still update and provide live data, that would be really useful for me, and I suspect many others, especially on long distance drives. Seeing data at a glance without having to change the screen on the phone, press a button or look at a watch face, or scan using the Libre reader would mean eyes can stay on the road while still having access to accurate data.

Thanks

**Comment by tzachi-dar** [comment]
Are you aware that xDrip can speak the BG?
This defiantly solves the problem of driving.

**Comment by mistermintsgh** [comment]
I am @tzachi-dar but it doesn't defiantly solve the problem, or even definitely solve the problem.

Having it speak the readings would interrupt any other sounds being delivered e.g. navigation directions, music being played and would just generally be irritating hearing a reading every 5 minutes (or whatever frequency was set) rather than being able to glance and see the reading whenever I chose to.

**Comment by doc77** [comment]
How about if you just tap on the xDrip+ window to make it the app in focus? This seems to work well on my Samsung Note 8.

**Comment by mistermintsgh** [comment]
@doc77 That does work, but only with specific navigation apps that already have multi window enabled.

So, for example, Google Maps works great like that, but my sat nav of choice is Waze as I find it much better at calculating alternative routes, avoiding traffic etc, but it does not seem to support multi window.

I figured it would probably be easier getting an app like xDrip updated to use multi window than something like Waze made by a huge company (which in this case is Google!)

**Comment by doc77** [comment]
@mistermintsgh  I just had a thought XDrip+ supports a method to display your Bg on the status bar. It's there and updates as long as  your status bar is showing.

**Comment by mistermintsgh** [comment]
@doc77 It does, you're right, but, the text in the notification area is incredibly small (I have tried changing the settings, but it only ever shows a very small number on my S9+)

When driving, I just think it would be far too difficult to see the small number without taking your eyes off the road for too long.

Compare that with the below, which is really easy to see (I am not actually driving here, especially with that hypo - don't panic!)

![xdrip nav](https://user-images.githubusercontent.com/42671801/51113970-c7edee80-17fb-11e9-81e6-2ee8a867271f.jpg)

**Comment by Kywalh** [comment]
From my understanding, the multi-resume windows is only available from Android Pie.
Before that release , the inactive windows are frozen.... 
So I'm in the same situation, either the GPS is active or xdrip....
Could be nice to upgrade xdrip with supporting multi resume...

https://www.google.com/amp/s/www.xda-developers.com/android-q-splitscreen-multitasking-multi-resume/amp/

**Comment by Navid200** [comment]
@mistermintsgh what is the current status?
If you have not found a working solution, I wonder if you are willing to ask using the support channels and update here.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks

**Comment by tolot27** [comment]
This is a nice-to-have feature with no treatment impact. We postpone it until we have more developers.
