### ISSUE TITLE
Suggest: Delete selected one calibration from calibration graph

### ISSUE THREAD

**Issue by stefanchavdarov** [NightscoutFoundation/xDrip#720]
Add a Delete option for selected one calibration in calibration graph.

There is such feature in calibration data table, its not friendly to find (long touch) and its not the place you'd want this to be. In graph the delete should be much friendlier to find the noisy/bad calibrations get to be seen easier.

**Comment by Navid200** [comment]
It's possible that it is not meant to be easy.
If it is made too easy, then, there will be a request to make it possible to undo a delete because people keep deleting calibrations unintentionally.

**Comment by Navid200** [comment]
I am closing this issue not because it should not be implemented.  But, because it should be put on hold for now.  And I label it accordingly.

**Comment by simonpickering** [comment]
Apologies I didn't spot this existing Issue before I started my own. 

> It's possible that it is not meant to be easy.
> If it is made too easy, then, there will be a request to make it possible to undo a delete because people keep deleting calibrations unintentionally.

Is it a bad thing that there's also (the requirement to add) the option to undo a deletion? I have deleted the wrong entry from the table on occasion because I selected the wrong one - choosing from the graph would be easier in at least some cases, but in any case being able to undo something is a fairly standard UI "method".

I must admit I've not looked at the code in question, but I assume a deletion/un-deletion would _simply_(!) be a case of marking a record to be used or not, and then calling the curve fit code to gather the requisite entries and work out the equation. I will have a look though.

**Comment by Navid200** [comment]
You can already set a calibration not to be used using the data table.  And you can undo that by unmarking the calibration.

We are moving to the era of factory-calibrated sensors that don't require to be calibrated twice a day.
As we move away from the time we needed to calibrate so much, and considering this was never implemented, I am going to close this issue.
We can always reopen if needed.

**Comment by simonpickering** [comment]
Is there a wontfix/not planned state rather than completed?

**Comment by Navid200** [comment]
Where do you see completed?

I see the existing labels and "Closed".

**Comment by simonpickering** [comment]
I see "Navid200 closed this as completed"

**Comment by Navid200** [comment]
I don't know where you see that.

Just look at the labels in GitHub.
![Screenshot 2023-08-14 175320](https://github.com/NightscoutFoundation/xDrip/assets/51497406/cf7a63a5-7c87-4e9f-ab04-4c0e4daf6e54)

And this is what you see under the title, again, in GitHub:
![Screenshot 2023-08-14 175428](https://github.com/NightscoutFoundation/xDrip/assets/51497406/d79e49a9-a357-438a-9f59-37844427d47a)

Can you post a screenshot where you see completed.

**Comment by simonpickering** [comment]
I see it inline
![Screenshot_2023-08-14-22-52-17-784_com android chrome](https://github.com/NightscoutFoundation/xDrip/assets/1830341/10730e58-8569-402c-8da6-d99016957e9b)

**Comment by Navid200** [comment]
OK, I see that now.
Thanks for helping me see what you meant.

That looks like a GitHub bug to me.
It's definitely nothing I did.  When I close an issue, it doesn't ask me why are you closing this.  I never chose completed anywhere.
I am sorry about that.
  
I think it is clear that it has not been completed.

**Comment by simonpickering** [comment]
Cool, just wanted to check there wasn't a clearer message. Agreed that people will realise it's not completed. Cheers
