### ISSUE TITLE
API "direction" options @ /api/v1/entries/current.json ?

### ISSUE THREAD

**Issue by haspden** [NightscoutFoundation/xDrip#725]
Just developing a clock for the kindle touch/paperwhite...

What are the direction options of the API? at /api/v1/entries/current.json

I can see Flat is one (as I am flat now) and there is a file /static/images/Flat.svg

I can also see
- SingleUp.svg
- SingleDown.svg
- DoubleUp.svg
- DoubleDown.svg

are the directions the same names? e.g. DoubleDown ?

Thanks

**Comment by haspden** [comment]
Options that I have seen and thus worked out exist are

→ Flat
↑ SingleUp
↓ SingleDown
↗ FortyFiveUp
↘ FortyDiveDown

_What may exist, but i've not yet seen them in the API json return
↑↑ DoubleUp
↓↓ DoubleDown_

**Comment by tolot27** [comment]
Trend arrows (using Unicode characters) and values are defined in https://github.com/NightscoutFoundation/xDrip/blob/master/app/src/main/java/com/eveningoutpost/dexdrip/ImportedLibraries/dexcom/Dex_Constants.java#L86-L96.
