### ISSUE TITLE
Feature Request : Android Lockscreen Clockface

### ISSUE THREAD

**Issue by haspden** [NightscoutFoundation/xDrip#729]
Not even sure if this is possible, however a clockface showing the digital time, blood glucose value & trend/arrow much like the bgclock.html page would be really handy...

Particulatly for samsung and other devices which now have "Always on Display"

**Comment by jamorham** [comment]
Last time I checked the Always On Display feature is for system apps only that only Samsung can authorize. If you know any different please let me know.

**Comment by gregorybel** [comment]
Huawei p20 pro has this feature too, I wanted to implement it but didn't find information how API looks like. if someone knows something I would be interested too

**Comment by jamorham** [comment]
Using root I think I can do it on Samsung but of course Samsung phones don't work nicely with root

**Comment by Navid200** [comment]
@haspden A lot has changed, with xDrip and with Android, since you opened this issue.  Is this still something you cannot accomplish with the latest xDrip release?
If not, would you please close the issue?
Thanks

**Comment by haspden** [comment]
Not practicable thus closing

**Comment by tolot27** [comment]
@haspden Did you see #1625? That's likely want you want(ed).
