### ISSUE TITLE
Dexcom G6 authentication errors

### ISSUE THREAD

**Issue by meatychunks99** [NightscoutFoundation/xDrip#732]
Hi,
I've had a good trawl through other issues but cannot find anyone reporting this same issue...

We've just bought a trial pack of the G6 for our daugher. We've previously been using libre and Miaomiao with Xdrip+ with a Nexus 5X and a SSW3.

I've followed directions to use the source wizard and entered the transmitter ID. I've disabled the watch to simplify things. However, the status shows 'connecting', and 'authorizing', but nothing more. The list of scanning errors grows larger.
Checking the log I can see:

Ob1G5StateMachine
authentication notification throwable:(CHECK_AUTH)
com.polidea.rxandoird.exceptions.BleDisconnectedException:Disconnected from EA:
...

Ob1G5StateMachine
Could not read after AuthRequestTX:
com.plidea.rxandroidble.exceptions.BleGattCannotStartException:
GATT exception from MAC address ... with type
BleGattOperation{description='CHARACERISTIC_READ'}

Ob1G5StateMachine
Received Authentication notification bytes:...
I'm using xdrip+ version d1d4889-2018.09.08
Code:1809080944

Starting to think I may have invested in an expensive turkey. Any help would be hugely appreciated...

**Comment by meatychunks99** [comment]
Thanks for the response.

Updated to the latest nightly build but still seeing connection issues. I've sent the log file onto you...

Your help is gratefully received.

**Comment by jamorham** [comment]
Marking as resolved.

**Comment by BOC14** [comment]
Hi @jamorham , firstly thanks for all your work on this.

Are you able to elaborate on what the resolution was to this issue? I'm experiencing a potentially similar issue on the G5 so was just curious to read it.

I am now pulling the latest Alpha so will try that out.

**Comment by Kitekater** [comment]
I have got the same problems with my G6 Sensor with my new Huawei P30 Pro
