### ISSUE TITLE
REQUEST: Wear OS app for use xDrip on my 5y.o. child smartwatch for using without smartphone

### ISSUE THREAD

**Issue by NStrakhov** [NightscoutFoundation/xDrip#749]
Hello!
My 5 y.o. daughter has diabetes type 1 and goes to kindergarten.
She is too young to take smartphone with. And it's too dificult.
Standalone app runs on android 4.4 or higher.
I cant find to buy any children smartwatch with android 4.4...
Can you make stand alone application for Wear OS to collect data via bluetooth an send to followers?

**Comment by svirito4ka** [comment]
xDrip+ supports wear integration through its wear app. The xDrip+ wear app is installed with the standard xDrip+ apk. [https://github.com/jamorham/xDrip-plus/blob/master/Documentation/WatchGuide.md](url)

**Comment by NStrakhov** [comment]
It is great information! Thank you!
But Huawei Watch 2 LTE does not look like a watch for a baby... I will try anyway, of course. 
Can you specify common parameters to help me find more siutable watch for my little daughter?
For example: embedded slot for SIM-card, Wear OS, bluetoth 4.0, ability to install app from unknown sources, etc...

**Comment by tzachi-dar** [comment]
I think that it is better to go with a phone and put the phone near the kid.
If that is not possible, then there are watches that have full android.
For example the "Finow Q1 Pro" works well with xdrip and miaomiao (you need to verify that for the g5).
Still it would look huge on a 5 years old boy, although you can put it in his pocket.

**Comment by doc77** [comment]
You might look at a mini Android phone, like a Unihertz Jelly Pro. It is only slightly larger than a watch, can easily be kept in a child's pocket, and has cellular connectivity for following.

**Comment by svirito4ka** [comment]
NStrakhov, as you can see there are many solutions for your case. But if you will intend to use the watch mentioned me, I mean the "Huawei Watch 2 LTE", then make sure before your buying that it has build number: OWDE.180215.017. For details see [here](https://github.com/NightscoutFoundation/xDrip/wiki/Patching-Android-Wear-devices-for-use-with-the-G5).
In addition you can read about my experience using this watch clicking [this link](https://github.com/NightscoutFoundation/xDrip/issues/744).
About using "Finow Q1 Pro" look at [here](https://github.com/NightscoutFoundation/xDrip/issues/648).
And certainly you can find more usefull information using Search Box on the Issues page and [gitter](https://gitter.im/jamorham/xDrip-plus).

**Comment by jserajlic** [comment]
Hi, I have huawei watch 2, build OWDE.180926.001.A1, is there any solution to set it as collector. 
tnx

**Comment by svirito4ka** [comment]
You can try to find the required ROM and flash it on your watcn, then patch your watch. Search [here](
https://forum.xda-developers.com/).

**Comment by jserajlic** [comment]
Tnx you so mouch. Finishes successfully.

**Comment by jserajlic** [comment]
Just I get the 
ERROR with demigod mode
ERROR with demigod-2 mode

Is that some problem

For now, working as collector

**Comment by svirito4ka** [comment]
There is no guarantee that the watch will work as required. The status of these modes should be OK.

**Comment by jserajlic** [comment]
Right now it is om, will see in future.
Tnx

**Comment by jserajlic** [comment]
...*it is ok

**Comment by greenninjas** [comment]
I had to downgrade from OWDE.180926.001.A1 to the exact version mentioned in patch instructions (OWDE.180215.017). Then patches do apply correctly.

I requested @jamorham if he could make the patches against OWDE.180926.001.A1 as well, it would be much obliged.

**Comment by Navid200** [comment]
Please use the support channels for asking advice about what can be done using xDrip.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

Open an issue only if you have discovered a bug or if you need a feature to be added that has no work-around to accomplish.  When opening an issue, please follow the guidelines presented to you.
Thanks

**Comment by Navid200** [comment]
@NStrakhov Did you find a solution?

**Comment by NStrakhov** [comment]
No. I have given up. I use a telephone.

**Comment by Navid200** [comment]
I'm sorry about that.

**Comment by old-square-eyes** [comment]
Not sure if we should re-open this, but I have just successfully achieved a downgrade and have loaded the patch on. Successful Demigod mode. Took a whole day of research / trial and error etc but I should be able to document the steps.

**Comment by Navid200** [comment]
@old-square-eyes That would be wonderful if you could document it.
Then, others can find it even if the issue is closed.

**Comment by old-square-eyes** [comment]
Just some quick and dirty steps since I haven't had time to do a full write up. Basically if you have the correct build number, just follow the instructions in the care pack on the xDrip watch guide.

If not, get TWRP loaded per the care pack instructions. Download a copy of the correct image and extract it until you see system.img.

Copy it to the watch using

adb push system.img /sdcard/

Then on the watch using TWRP install the img.

Reboot and let the watch set up, but before you pair it tap the button to go to settings and confirm the correct image is loaded. Then progress with the instructions from the care pack.

**Comment by meatychunks99** [comment]
> 

Can I just add - having followed well documented instructions to install the correct version of the stock ROM - that the step to install the fix-boot-security.zip patch (from the care-pack) via TWRP is also required before the watch will boot. I was stuck staring at the Huawei logo wondering if I'd bricked my watch for hours before I figured that out...
