### ISSUE TITLE
Missed Readings Samsung S9 Plus

### ISSUE THREAD

**Issue by m1st0** [NightscoutFoundation/xDrip#753]
I keep getting missed readings warning every 20 minutes with an occasional re-connection and backfill of data.  However, this does miss out on a few alerts.  High logs state:

`Enabled Buggy Samsung workaround due to jitter of: [various seconds or minutes shown, but not consistently]`

In addition, on the EH logs show every 20 minutes or so:

`BG Readings MIssed (@[time])`

So, sometimes it runs for a while, and sometimes it starts like hiccups and stops reading results unless I leave the app open constantly.  I have tried G5/G6 Debug Options as well as Bluetooth Settings.

G5/G6 setttings on:
- Using the OB1 collector
- Native algorithm
- Preemptive restarts
- Minimize scanning
- G6 support
- Allow OB1 unbonding
- Allow OB1 initiate bonding
- Scan for G5 constantly
- Authenticate G5 before each read
- Unbond G5 before each read (no effect seen on/off)

G5/G6 settings off:
- Force G5 to UI Thread (no effect seen on/off, so left off)

Bluetooth settings:
- Turn Bluetooth on is active
- Bluetooth watchdog is on
- Timer value for BT watchdog >> 5, 6, 19, or 20 to see if it would restart before it missed readings or right after so that it could catch the issue but I yet see the missed readings for at least 20 minutes

Any other debug or hints to fix Samsung issues?  I don't think XDrip+ is being battery optimized, but it seems that way.  With Lineage OS 15.1 (Android 8.1.0) on the S9+, I had a stable run with XDrip+.  I decided to try and see if the Samsung S9+ ROM could also be a good option, but that is when the issues of missed readings arise. Version 14fecb8-2019.01.10.

**Comment by jamorham** [comment]
See the related issue: https://github.com/NightscoutFoundation/xDrip/issues/663

**Comment by m1st0** [comment]
Closing this issue and moving to #663.
