### ISSUE TITLE
Kospet Hope 4g smartwatch does not upload data to Nightscout

### ISSUE THREAD

**Issue by dimis28** [NightscoutFoundation/xDrip#754]
Greeting to all members. We have recently bought the Kospet Hope 4g smartwatch with android 7.1 We have used until now other smartwatches with Android 6.0 with great success. We have nightscout and azure. The Kospet watch refused to upload any data to azure(we receive bluetooth data from our transmitter-blukon). I have checked all the battery options so no application gets to sleep neither the Wifi and the Data, and i have checked i hope all the applications permissions concerning the Xdrip. Any thoughts? Will be better to change to Heroku and see if the problem remains? I even try to set the watch as a follower but it does not show anything .

**Comment by jserajlic** [comment]
Hi, how mouch hours battery works with 4g connection. tnx
I need to buy watch for my 6 years old son

**Comment by dimis28** [comment]
The Dm2018 is the best choice for your kid.http://s.click.aliexpress.com/e/TgSw2nO

**Comment by dimis28** [comment]
I write about Dm2018 because it has 900 mah battery and will last more from Kospet. We have buy Kospet for a backup solution .

**Comment by dimis28** [comment]
I write about Dm2018 because it has 900 mah battery and will last more from Kospet. We have buy Kospet for a backup solution .

**Comment by jserajlic** [comment]
Thank you so much

**Comment by calibr** [comment]
@dimis28 sorry for the offtopic, do these watches(Kospet Hope or Dm2018) need a phone(paired with them) to upload data to NightScout? Or they just use mobile 3G/4G network and work complete autonomous and without any phone? Does their firmware need to be patched like for Android Wear watches?

**Comment by dimis28** [comment]
No phone needed they are standalone collectors new version of Kospet released http://s.click.aliexpress.com/e/ca7GqfGU

**Comment by dimis28** [comment]
one of the best choise is also this great smartwatch https://m.gearbest.com/smart-watch-phone/pp_009309925869.html?lkid=64107282

**Comment by Loodeytunes** [comment]
Hello sorry to bring up this old post. How do you get watchface for it? Or do you just open the app?

**Comment by Navid200** [comment]
@dimis28 I am closing this issue as it seems you solved the problem.

Please use the support channels to share expertise.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
