### ISSUE TITLE
SW3 not working as collector with miamiao/Libre

### ISSUE THREAD

**Issue by Paulusma** [NightscoutFoundation/xDrip#755]
I am trying to get a Sony Smartwatch 3 to act as collector following the Watchguide but so far had no success: i can't get the watch to connect to the miaomiao.

I can see the miaomiao as available BT device on the phone but not on the watch. 

Am i doing somehting wrong or is there a problem with BT on my watch? What are the precise steps to get the SW3 paired with the miaomiao? I was able to pair the phone and watch so i would think BT is working on the SW3.

**Comment by parapenT1sta** [comment]
Did you follow these steps? https://www.youtube.com/watch?v=Awvbueg8sIg

**Comment by jamorham** [comment]
@Paulusma which xDrip version are you using? Can you try the latest nightly. thanks

**Comment by Paulusma** [comment]
@parapenT1sta i thought i did but apparently not: after taking a very deap breath i removed xDrip from the phone and started the smartwatch from factory settings. Lo and behold, following the guide it worked like a charm (@jamorham using the 10-1 build)!
