### ISSUE TITLE
Pebble CGM Careportal offline adding Insulin&Carbs

### ISSUE THREAD

**Issue by tremor** [NightscoutFoundation/xDrip#757]
At the moment I configured the Nightscout API (https://my.ns.instance/api/v1/treatments) in my Pebble CarePortal Settings. Is it possible to direct interact with xDrip+ like the Pebble Nightscout Watchface what uses http://127.0.0.1:17580/pebble  ?

**Comment by tremor** [comment]
Nobody any idea how to insert insulin with the Careportal App?

**Comment by Navid200** [comment]
@tremor Would you please close this issue if your question has been answered?
You can also use the xDrip facebook support group.
https://www.facebook.com/groups/xDripG5
Thanks
