### ISSUE TITLE
G6: Calibrations are added into OB1 collector even when OB1 collector is not used

### ISSUE THREAD

**Issue by andyrozman** [NightscoutFoundation/xDrip#763]
So I am G6 user, at the moment I am not using OB1.

When I do calibration with my meter (I am using Contour One), calibration is added into two queues: NativeCalibrationPipe and OB1G5StateMachine. 

Problem is I am not using OB1, and when I tried to switch to OB1 I couldn;t because my queue had about 40 elements, and every 5 minutes xDrip tried to process one unit from Queue, he couldn't do that because calibration in Queue was very old, so it got error and just deleted that entry from queue and went into to wait state. On next cycle it started again. (Queue did get smaller, but wait time to clean it would be few hours)

Proposed solutions (both should be implemented):
A.) If OB1 is not enabled, then Calibration is not put in the queue
B.) When OB1 processes the queue, queue should be cleaned up before (all too old calibrations (and maybe any other events) should be removed)

**Comment by Navid200** [comment]
@andyrozman Would you please mention what the status is now?
Thanks

**Comment by Navid200** [comment]
If you like to reopen this issue, please update your current settings.
