### ISSUE TITLE
Build troubles.  (xDrip should have a reliable documented automated build procedure)

### ISSUE THREAD

**Issue by afcady** [NightscoutFoundation/xDrip#768]
I'm trying to build xDrip.  I have never before built any Android program or any java program.  Here are the troubles I'm running into.

----

EDIT: Nevermind actually.  At last, I successfully built it.  Here is the working build procedure:

```
wget -c https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O ../sdk-tools-linux-4333796.zip.partial
mv ../sdk-tools-linux-4333796.zip.partial ../sdk-tools-linux-4333796.zip
unzip -d ${ANDROID_HOME} ../sdk-tools-linux-4333796.zip
mkdir ${ANDROID_HOME}
yes | ${ANDROID_HOME}/tools/bin/sdkmanager --licenses
yes | ${ANDROID_HOME}/tools/bin/sdkmanager "platforms;android-26" "build-tools;27.0.3" "extras;google;m2repository"
bash gradlew assembleRelease
ln -sf app/build/outputs/apk/release/app-release-unsigned.apk .
```

-----

I have a `Makefile` that generated these commands.  It should make it possible simply to run `git clone`, `cd xDrip` and then download and build the `.apk` just by typing `make`.  I will try it out on a fresh directory later to make sure.  Then I'll put it in a PR.

**Comment by Navid200** [comment]
@afcady Sounds like your problem has been resolved.
Would you please close the issue then?
Thanks

**Comment by afcady** [comment]
Not exactly resolved, as #903 is not merged.

**Comment by Navid200** [comment]
But, isn't 903 self-contained?  Or, are you saying 903 and 768 are duplicates?

**Comment by afcady** [comment]
903 is a pull request, not an issue.

**Comment by Navid200** [comment]
I see thanks.

**Comment by tolot27** [comment]
@afcady As commented at #903, the PR can be merged only after removing the hardcoded version numbers. When do you have time to implement this?

**Comment by Navid200** [comment]
@tolot27 Considering there is already a PR, shouldn't this be closed?  What if someone else sees this open issue and starts spending time on this developing a solution?  Wouldn't that be a waste of time?

**Comment by tolot27** [comment]
@Navid200 Issues will be closed automatically, as soon as the linked PR gets merged. It is recommend that people should read the complete discussion at the issues and if they are willing to contribute, discuss this with the developers.

Anyway, this issue can be closed since there is a tiny HowTo at https://xdrip.github.io and there is no need for a Makefile.
