### ISSUE TITLE
Nightscout follower 

### ISSUE THREAD

**Issue by crizz6396** [NightscoutFoundation/xDrip#772]
I tried to use the source nightscout follow
Entered in my website every way I can think of, it wont pull the data.

Is there a specific format that it needs to be in?  Is there any other setting that needs to be on?

**Comment by danielharrelson** [comment]
I came here today looking for just this information.

I know there is the NightWatch app, but it's dated (last updated 2016).

I've had limited success using NSClient and xDrip+, but it's really hit and miss at consistency with following a NightScout webpage.

Is there any way to do this strictly withing the xDrip+ client, without any other applications running in the background? Need to be able to do this on a Pixel 3.

**Comment by jamorham** [comment]
Please install the latest nightly, it is a lot more tolerant with the formats for the nightscout follower URL.

@danielharrelson select data source for nightscout following and then there is a URL to enter of your nightscout site.

**Comment by danielharrelson** [comment]
@jamorham Is there any special Nightscout follower url?

Mine would be https://cgm.DOMAINNAME.systems

Just want to make sure the TLD .systems would be accepted.

**Comment by danielharrelson** [comment]
@jamorham, maybe I'm wrong... but when I tried to setup as Nightscout follower, it is very unintuitive.

https://www.youtube.com/watch?v=d0ZuhiqqLOM

Using a Dexcom G5 + Spike to upload to Nightscout, just trying to get Android to follow. It appears as if xDrip+ wants to setup to be the receiver for the transmitter upon first boot.

Maybe @crizz6396 can comment if that's the same issue they're having.

**Comment by crizz6396** [comment]
I tried the latest nightly build.  First time that I lost data.  After installing the latest nightly build I lost like 8 hours of data from today.

I tried to use the nightscout follow.  I thought it was working because I got it to download 1 reading then it stopped

**Comment by jamorham** [comment]
@danielharrelson The Nightscout following data source is now included in the Source Wizard (20th Feb nightly), select `Other` then you will see the option.

**Comment by danielharrelson** [comment]
@jamorham PERFECT! Thank you so much! I know I didn't open this ticket, but maybe @crizz6396 can comment too and it can be closed! :)

**Comment by crizz6396** [comment]
So it is working but poorly.  As soon. As I switch over to night scout follow and it downloads the data, it clears al but the last 12 hours.  I downloads 1 data point then doesn't pull again.  

I have to restart collector then it will download another data point.

**Comment by danielharrelson** [comment]
To be honest, I'm the diabetic. My girlfriend follows me...She's got a Pixel 3XL with the latest Android, however she's currently asleep, so I'll check in tomorrow if there are any issues on my end.

**Comment by danielharrelson** [comment]
Everything seems good on my end, sorry for late update. Can be closed for me.

**Comment by crizz6396** [comment]
Dan
You are using the follow sources and it updates without issue?

**Comment by danielharrelson** [comment]
My girlfriend follows my nightscout with xDrip+. She has a Pixel 3 and none of the issues you reported.

**Comment by crizz6396** [comment]
with the latest update everything is working fine.

**Comment by jamorham** [comment]
Marking as resolved
