### ISSUE TITLE
Huawei Blucon Connection Issues

### ISSUE THREAD

**Issue by haspden** [NightscoutFoundation/xDrip#773]
Having some issues with a new Huawei Mate 20 Pro using a blucon

At first, it would connect but no data would pull through after the initial reading

![whatsapp image 2019-02-07 at 5 50 11 pm](https://user-images.githubusercontent.com/4039041/52501525-7822fd00-2bd8-11e9-908a-4cdacff808a6.jpeg)
![whatsapp image 2019-02-07 at 5 01 41 pm](https://user-images.githubusercontent.com/4039041/52501602-9e489d00-2bd8-11e9-9ce4-ffc9842a7e0c.jpeg)
![whatsapp image 2019-02-07 at 5 28 48 pm](https://user-images.githubusercontent.com/4039041/52501603-9ee13380-2bd8-11e9-9376-9b709658e962.jpeg)

I finally got it to transmit some data after resetting several times etc

but it soon stopped sending data in the background

![whatsapp image 2019-02-08 at 3 26 16 pm](https://user-images.githubusercontent.com/4039041/52501706-e2d43880-2bd8-11e9-869c-9e663e14f248.jpeg)

Any thoughts ?

Thanks

**Comment by gregorybel** [comment]
Blucon is not bonded. did you enter pin?

otherwise look here:

https://github.com/jamorham/xDrip-plus/blob/master/Documentation/blukon.md

**Comment by Navid200** [comment]
@haspden Would you please close the issue if it has been resolved?
If not, would you please respond to the suggestion?
Thanks

**Comment by haspden** [comment]
unable to verify if issue still persists as no longer have this hardware
