### ISSUE TITLE
"stop sensor" function on menu should not be overridden by restart sensor or preemptive restarts. 

### ISSUE THREAD

**Issue by PedanticAvenger** [NightscoutFoundation/xDrip#774]
For a while now (on nightlies) using stop sensor to change a sensor site has resulted in an auto start moments later asking for a calibration simply a restart. I have to try stopping 2 or 3 times to be able to trigger the sensor start process properly. If I change site, then quickly do a stop/start in rapid succession it seems to work in proper manner.

**Comment by bassettb** [comment]
I am seeing this also.  I just asked about it on the forum and quickly heard from 4 others seeing the same issue.

**Comment by Navid200** [comment]
@PedanticAvenger This should not be happening any more if you update xDrip, for example to July 13, 2020.
Would you please close this issue?
Thanks

**Comment by PedanticAvenger** [comment]
Certainly.
Just expected it to be closed if attached to a bug by someone else I guess.
I had not seen the issue a few builds later.
