### ISSUE TITLE
Master's battery percentage on follower watch face

### ISSUE THREAD

**Issue by NightscoutCloud** [NightscoutFoundation/xDrip#777]
Hello,

My son has T1D and his phone is a master for followers. My phone is a follower and works with my watch. Everything works fine except one thing: my watch shows my phone's battery (follower's battery in the 'Uploader %' field) but not the master's battery (as I think should be). Please advise what I missed in the settings or add this as an issue.

Thank you

**Comment by Navid200** [comment]
@NightscoutCloud Would you please close this issue if your question has been answered?
You can also use the xDrip facebook support group for asking questions.
Thanks
