### ISSUE TITLE
Polar M600 patch failed

### ISSUE THREAD

**Issue by mfank** [NightscoutFoundation/xDrip#779]
The Nougat Patch failed und the M600 can not boot anymore. Before I made a Local Backup. How can I get this Backup Back to internal Storage.  Within the TWRP the internal storage is empty.

**Comment by Navid200** [comment]
@mfank Would you please close this issue if you don't need an answer any longer?
If you do, I suggest you post in the xDrip facebook support group.
https://www.facebook.com/groups/xDripG5
Thanks
