### ISSUE TITLE
Total Insulin/Carb ratio in extra status line

### ISSUE THREAD

**Issue by gitanO0** [NightscoutFoundation/xDrip#78]
Please extend the new "extra line status" options for total carbs and total insulin to include another (and last) option for the ratio of those two.  carbs/insulin. For example if the total carbs for last 24 hrs is currently 100 and total insulin is currently 15 then this new option would show 6.67.

**Comment by gitanO0** [comment]
I modified the above request to swap the values in the ratio to put carbs in the numerator and insulin in denominator.  Makes more sense.  Most folks relate to a "carb to insulin ratio" and not the other way around.

**Comment by jamorham** [comment]
Should be present in the March 27th Nightly, please check and let me know if it is correct. Thanks.

**Comment by gitanO0** [comment]
I've upgraded to the 3/27 build and things look good.  Thanks for the
inclusion!
-r

**Comment by jamorham** [comment]
Marking as resolved.

**Comment by tolot27** [comment]
Related to #71.
