### ISSUE TITLE
Best way to monitor a kid's glucose levels for the whole day

### ISSUE THREAD

**Issue by okrad** [NightscoutFoundation/xDrip#786]
Hi all, I'm not sure this is the right place to ask, but I couldn't find a more suitable place, and I'm curious about the ways you are using xdrip+ for monitoring your children levels.

I'm the father of an 8 yo child diagnosed with type 1 diabetes 6 months ago. A couple of weeks ago we bought a miaomiao and installed xdrip+ on both my wife's phone (master) and on mine (follower). I also activated a nightscout instance on heroku, and connected my wife's phone to it. 
I have to say xdrip+ is an impressive app, and I, as a professional developer and an user, can only be amazed for the work you have done. I'd really love to contribute to the project in the future... 

Anyway, we are planning on buying a supported smartwatch with a 3g sim reader, so that we can monitor the kid's glucose levels while he is at school. I guess in this scenario the smartwatch should be configured as master, and my wife's phone should become a follower... Right?

Problem is, these "gadgets" have very short battery duration, I'm not even sure they could stand alive for 8/9 hours a day with bluetooth and 3g connectivity on, and even then, when the kid comes home or when he goes practicing some sport the watch would have to be recharged and so the kid would have to take it off.

I'm sure many of you have the same problem... But how do you solve it? Do you disconnect the watch everyday and turn your phone into master just for the evening/night, restoring the watch as master the morning after? Do you automate this process in any way (for example with tasker or smt like that)?

Thank you to everyone who's going to report back his/her experience!

**Comment by tzachi-dar** [comment]
Yes, we face a similar situation. And it can be solved.

xdrip supports more than one collector, so the watch can be charged while he is at home.

In any case, here are my advices:
1) Don't use a watch as a collector. It is much harder to use it (screen very small, battery and so on). Kid should come to school with a phone, put it in his bag, and things will still work. This phone should be the master.

2) If using a watch after all, we sometimes use "finow q1 pro". Not the best thing, battery some days last 7 hours, and some days 18 hours. I'm not sure why.

3) For all house coverage solutions with miaomiao and rpii, please see here: https://docs.google.com/document/d/1955quKMUfaVHyQZLw3k8IEkPFv3od00bA0AoJKY96xE/edit?usp=sharing

4) For adding another phone as a collector, please see here: https://github.com/NightscoutFoundation/xDrip/issues/782#issuecomment-464617462

Please ask again, if you still have questions.

**Comment by okrad** [comment]
Thank you @tzachi-dar, I used the "API Upload (REST)" method on the master phone for cloud upload, I didn't know you could "share" the same BT device with the MongoDB method!

**Comment by whoiswes** [comment]
Just adding my experience as we have a 7 year old (dx'd 4 years ago) and have been using xDrip in some fashion for most of that time.

Note - we're on G5's still, will be flipping to G6 with our next order.

We have a Nexus G5X, running Lineage 15 and xDrip, that our son carries with him.  It's paired with an old SW3 that the teacher wears on a lanyard and charges each night at schoo.  My son has a small backpack that contains tabs, glucagon, and his meter, so the phone just stays in there or gets carried in a pocket.  We have the phone hooked to the school wifi network, and can easily go a few days between charges.  We have a T-Mobile 200MB free plan sim that provides data when we're out and about, and have never come close to using all of the data.

That phone is a master, and also uploads to a Nightscout instance.  Teacher and nurse staff all watch Nightscout.  My wife and I have xDrip set up in follower mode on our phones, so we can remotely calibrate or enter other treatment info (although we rarely do this).  Additionally, I have a second xDrip instance (cloned the APK with one of the myriad of app cloning tools) for my CGM, uploading to my own Nightscout instance (I was diagnosed 6 months after my son).  For me, both instances work flawlessly.

We never even powered on the G5 receiver we got when we upgraded from the G4, and this setup has been amazingly reliable.  The staff absolutely love having easy access to his numbers from anywhere, and it makes coordinating care remotely a breeze.  I cannot say enough good things about xDrip and Nightscout!

**Comment by zshh** [comment]
We gave up on the watch as collector part. Obviously it depends on child's physique, but all watches i've seen that could act as collector are huge and bulky for our daughter.

So we're using phone with xdrip and bluecon and it works relatively ok.
Decent phone with good BT is a must tho. Initially we bought her Huawei P20 lite and we had huge problems with constant signal dropping and disconnecting. Outdoors it was nightmare to stay connected even if the phone was in her jacket pocket. Thought it was blucon that was the culprit, but since we changed to Xperia XZ1 it works much better.

I personally had Fitbit ionic with xdrip watchface as follower, but it wasnt that good. Now I have ticwatch pro and that works really well. Not using it as collector obviously, but there is possibility to do it.

**Comment by Navid200** [comment]
@okrad If your question was answered, would you please close the issue?
Thanks

**Comment by okrad** [comment]
Sure, thanks to all for reporting back their experience! 
We too gave up with the idea of using the watch as a collector. Since then we used for a period an old HTC (one m8s) phone. Although it worked, it was really slow and the battery life was barely enough to cover the day.
We are currently using a Samsung A20e and it works great. The battery lasts for 3/4 days and the bluethooth is quite stable.
Me and my wife are using a pair of MiBand 5 connected to our phones and they work great too.
