### ISSUE TITLE
Automatic calibration process of G6 when G6 mg/dl and xDrip mmol not working?

### ISSUE THREAD

**Issue by diagnoe4** [NightscoutFoundation/xDrip#789]
My G6 is a US one that works with mg/dl, I however use mmol and have xDrip show results in mmol. 

I use an Accu-Chek Aviva Connect in mmol that syncs with xDrip.  xDrip seems a bit confused about how to handle calibrations in this scenario for the G6. I understand that the glucose levels are calculated by the G6, not xDrip (as I understand it was with the libre). 

Until just now it looked like calibrations were not sent to the G6 as long as I had mmol in the settings (the red squares don't become round).
If I switch that to mg/dl. The squares do turn round and calibrations do seem to be sent.
The test I took now while in mmol however seems to have caused the sensor to be calibrated as it corrected down from 9.5 to 7.2. However, this calibration does not show up in the calibration table and graph and also the square did not turn round. The calibration table and graph only contain the calibrations sent while xDrip was in mg/dl mode. The log seems to indicate that calibrations are happening despite that not being visible on the graph, the calibration table, and the calibration graph:
NativeCalibrationPipe: Queuing Clibration for transmitter: 5.5 mmol/l [timestamp]
Ob1G5StateMachine: Queuing Clibration for transmitter: 5.5 mmol/l [timestamp]
BluetoothGlucoseMeter: New blood test data: 5.5 @ [timestamp] Bluetooth Glucose Meter: Roche [MAC Address]
BluetoothGlucoseMeter: Prompting for calibration for: 5.5 mmol/l from: [timestamp]
No other messages after that related to the calibration.
The square glucose measurement on the graph does not turn round

On libre it would have the following messages as well:
BloodTest: Opportunistic calibration for Blood Test at [timestamp] of 6.6 mmol/l matching sensor slope at [timestamp about 9min later] from souce Bluetooth Glucsoe Meter: Roche [MAC address]
jamorham: Home: Processing Finger stick Claibration with values: glucose: 6.6 timeoffset: [6-digit number] full auto: true
AddCalibration: Creating auto calibration from: 6.6 requested: [timestamp] from source: processFingerStringCalibration
NativeCalibrationPipe: Queuing Calibration for transmitter: 6.6 mmol/l [timestamp]

These kind of messages only appear if I switch to mg/dl and then manually click on the blood test and select calibrate in that prompt.

Secondary comments:
Compared to how the calibrations worked with the Libre (smooth), with the G6 it looks strange. It also doesn't adjust previous readings like it did with the Libre and I have multiple "jumps" in the graph.

Is the calibration behavior a bug or do I have to change something in the settings? Let me know if you need more information.

**Comment by Navid200** [comment]
@diagnoe4 I'm sorry about the long delay in responding to this.  By now, you may have moved to a Firefly.  Is this still a current question?

**Comment by diagnoe4** [comment]
@Navid200 while most comments seem to still hold, auto-calibrations still work, so not really an issue.

The calibration table never contains values for me, but that does not bother me.

**Comment by Navid200** [comment]
unless the first two characters of the serial number are 80 or 81, the transmitter does not send raw values.  That may be why the calibration graph is empty.  

You will get answers, in a few hours not in a few years, if you ask in the support channels:
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus

**Comment by diagnoe4** [comment]
I have been using the gitter chat for immediate questions. The issues I reported were meant to be backlog items. If it were something more bothersome, I would have made myself heard.

**Comment by Navid200** [comment]
The horizontal axis of the calibration graph represents raw values.  The vertical axis represent what xDrip considers to be the corresponding blood glucose for each raw value defined by the line shown on the graph.
No G6 transmitter after 81XXXX sends raw values.  xDrip cannot show anything on the calibration graph because xDrip has no access to the raw values.  That's why such transmitters cannot use the non-native mode.

**Comment by tolot27** [comment]
@Navid200 your latest comment should be added to the docs.

**Comment by tolot27** [comment]
I've added it to the [[Frequently-Asked-Questions-(FAQs)]]. Maybe, a short explanation could be shown on the calibration graph explaining this.
