### ISSUE TITLE
Duplication of bluetooth meter values messing with graph and calibration

### ISSUE THREAD

**Issue by diagnoe4** [NightscoutFoundation/xDrip#790]
I have observed a bug with the Accu-Check Aviva Connect sync: sometimes historic glucose levels are suddenly populated on the graph at a wrong time. E.g. I would measure 5.3 at 8 in the morning. That same 5.3 would sometimes suddenly appear at 14:30 again after taking a measurement at say 16:00 but with no measurement happening at 14:30 and other measurements having happened between 8:00 and 14:30. Often these measurements would appear multiple times. This doesn't happen very often but does from time to time and did sometimes mess with the Libre calibration. The times these reading reappear seems quite random and not connected to when the device sends the information to xDrip (it never appears close to a reading that was just taken and correctly synchronized, always a few hours in the past. Often I don't even notice until I scroll back.

A similar issue has been opened for the Contour next:
https://github.com/NightscoutFoundation/xDrip/issues/138
I would assume it's the same issue caused by the bluetooth sync.

**Comment by nsghub** [comment]
I can confirm this bug. Still happens with the Contour Next.
Was the first time for me this morning. The BT meter was not connected when the repeated measurement value was populated.

**Comment by muthijammy** [comment]
I have more data on issue of duplicate calibration triggering at random time. These seem to be triggerring conditions:

Meter connected to xdrip on mobile
Keep automatic calibration enabled in config
Do BG test and Dont calibrate using it (4:22 pm)
Open xdrip after 30 minutes
Earlier BG value randomly applied as calibration now(4:50 pm)

I had noticed this issue in past but didnt realise last step in trigger. It has been discussed in past in FB and I see below open issues raised without triggers mentioned and open. 

Workaround seems to be disabling automatic calibration or click on BG in graph and calibrate. Can there be quick fix as time-is-money and delayed BG used for calibration is quite dangerous. Should I raise new issue or this issue will get priority based on new comments

**Comment by Navid200** [comment]
@diagnoe4 Do you still experience this with the latest xDrip release?
May 21, 2021

**Comment by Navid200** [comment]
@diagnoe4 If this is not related to the following, please explain.
https://github.com/NightscoutFoundation/xDrip/issues/296

If it is related, please use that existing issue to communicate your concerns.

**Comment by diagnoe4** [comment]
> 
> 
> @diagnoe4 Do you still experience this with the latest xDrip release?
> May 21, 2021

Hi all, sorry for the late reply. I have not observed this issue in many months. I would therefore assume it's fixed at least for my case.
