### ISSUE TITLE
Feature Request: Sensor end-of-life warning 

### ISSUE THREAD

**Issue by becheran** [NightscoutFoundation/xDrip#793]
I am using a Dexcom G6 with xdrip on my phone and watch. 
One little feature that I would love to have is a sensor end-of-life reminder before the G6 sensor actually stops running. 
I know that I can see the sensors start time and the days since I started the sensor. It would just be comfortable to get a short reminder 24h before the sensor actually stops. 
Do you think this is an interesting feature for XDrip? 
If so, I could try adding it via a pull request myself.

**Comment by RaabenFuchs** [comment]
I alway thought the same, even if im using libre. support it!
sometimes, you just dont care about all the information

**Comment by Navid200** [comment]
@becheran I think this will be very useful.  Did you ever implement this?

**Comment by tolot27** [comment]
This issue is duplicated by #1467.

**Comment by becheran** [comment]
@Navid200 No I didn't :(
@tolot27 True. Since I don't have the hardware to even test this anymore and won't find the time anyway, I will close this issue.
