### ISSUE TITLE
backfill data not uploaded to Dexcom Follow

### ISSUE THREAD

**Issue by doc77** [NightscoutFoundation/xDrip#795]
Would it be possible to have the Dexcom Follow upload have a look back feature. This would be valuable for when the watch is used as a collector and it only shows on the uploader phone when it is back in proximity of the watch.  The phone will backfill but Follow will not look back.

**Comment by doc77** [comment]
@kskandispersonal  Thank you!

**Comment by Navid200** [comment]
@doc77 I am sorry to bother you again.  I am going through the old issues.  Was this ever resolved?

**Comment by tolot27** [comment]
@Navid200 The PR is still not merged. Will have a look soon.

**Comment by Navid200** [comment]
@doc77 Please update the current status of xDrip with respect to this.

**Comment by Navid200** [comment]
xDrip offers follow capability based on Nightscut as well as xDrip sync.
The ability to follow using Dex share also exists.

Is an official Dexcom follower capable to do what is being requested here?

My concern is that if we provide too much redundancy in xDrip, we will only be spreading ourselves too thin considering we don't have many active developers.

We can always reopen this if someone is interested to add it.
