### ISSUE TITLE
GNSentry

### ISSUE THREAD

**Issue by Wilmamee** [NightscoutFoundation/xDrip#796]
Is it possible to make xdrip support for the GNSentry (GlucoNightWatch)?

**Comment by jbm76** [comment]
Hellooo....

Any news about the compatibility of GNSentry (GlucoNightWatch) with xdrip?

Has anyone been able to connect it?

Thnks againnnnnn!!!

**Comment by castdoom** [comment]
i asked GNS about this around 3 weeks ago amd they said they have the xdrip devs working on it.

not heard anymore since. i would personally love xdrip to support GNS as i find the official app far too basic

**Comment by lelebrian** [comment]
Same here. Following to know when it will be possible,

**Comment by Navid200** [comment]
Duplicate:
https://github.com/NightscoutFoundation/xDrip/issues/686
