### ISSUE TITLE
xDrip+ Sync Follower Issue

### ISSUE THREAD

**Issue by doc77** [NightscoutFoundation/xDrip#80]
My tablet is set up as an xDrip+ Sync Follower. When I enter a treatment proposal on my phone, which is set up as the master, but do not confirm it as accepted treatment, the treatment proposal shows as accepted treatment on the tablet (xDrip+ Sync Follower). 

For instance if I propose an insulin treatment of 7u, then abandon it, then 9u and abandon it,  then propose an insulin treatment of 10u and accept that, the data on the phone correctly shows an insulin treatment of 10u but the data on the tablet incorrectly shows insulin treatment of 10u+9u+7u. Note the graphs and the extra status line.

Thanks.

![screenshot_20170304-123252](https://cloud.githubusercontent.com/assets/15315426/23590017/28c99130-019e-11e7-8b8c-9fb4ec61fc9f.png)
![screenshot_2017-03-04-12-32-45](https://cloud.githubusercontent.com/assets/15315426/23590021/313deece-019e-11e7-9eba-9b1f3c3f9915.png)

**Comment by jamorham** [comment]
How are you abandoning the treatment entry? I haven't been able to reproduce this.

**Comment by doc77** [comment]
I'm first accepting the treatment so I can view the predicted result. Then I use the undo arrow to back out of it before trying to enter a new value.

**Comment by doc77** [comment]
I played with some tablet settings and the problem resolved. After enabling location things got back to normal. I have no idea why this would effect normal xDrip+ function, but I will keep location enabled going forward on both the phone and the tablet.
Thanks.
