### ISSUE TITLE
Automatic calibration with BT meter and manual calibration dialog

### ISSUE THREAD

**Issue by nsghub** [NightscoutFoundation/xDrip#804]
I'm using a Contour Next One BT meter and have enabled automatic calibration. In most cases this automatic calibration works fine and waits for another 15 minutes until it adds the value to the calibration. But sometimes the message "Use this measurement for calibration?" appears immediately after the measurement. If I select "No" the automatic calibration still works fine.

**Comment by boc-the-git** [comment]
@nsghub what exactly is the issue here?
What would you be expecting to happen, compared to what is happening?

**Comment by nsghub** [comment]
@boc-the-git This was an issue when I was using the Libre. When you start a new Libre sensor, xDrip asks for two calibration values. I would assume that those values can be retrieved via BT from the Contour device. But when the xDrip dialog is shown and you use the BT meter, then this dialog is overridden with the "received new BT value" one. This value is not used for initial calibration. I hope I recall that correctly, because I'm using a Dexcom sensor now...

**Comment by etogonza** [comment]
> @boc-the-git This was an issue when I was using the Libre. When you start a new Libre sensor, xDrip asks for two calibration values. I would assume that those values can be retrieved via BT from the Contour device. But when the xDrip dialog is shown and you use the BT meter, then this dialog is overridden with the "received new BT value" one. This value is not used for initial calibration. I hope I recall that correctly, because I'm using a Dexcom sensor now...

Need support on this. Is the same for me when initial calibration prompts.

**Comment by tolot27** [comment]
@nsghub Would you please close this issue if your problem has been resolved?
Otherwise, please contact the user community on the following support channels for further assistance:
- https://www.facebook.com/groups/xDripG5
- https://gitter.im/jamorham/xDrip-plus

Thanks!
