### ISSUE TITLE
Initial calibration with BT meter shows manual dialog

### ISSUE THREAD

**Issue by nsghub** [NightscoutFoundation/xDrip#805]
When using my BT meter for the initial calibration the manual calibration dialog is shown when the measurement is received. The initial calibration dialog is closed and has to be selected again.

**Comment by nsghub** [comment]
Might be related to #804.

**Comment by tolot27** [comment]
Test

**Comment by tolot27** [comment]
@nsghub Would you please close this issue if your problem has been resolved?
Otherwise, please contact the user community on the following support channels for further assistance:
- https://www.facebook.com/groups/xDripG5
- https://gitter.im/jamorham/xDrip-plus

Thanks!

**Comment by jamorham** [comment]
closed as reported as duplicate
