### ISSUE TITLE
Constant loss of signal - G5 with Nokia

### ISSUE THREAD

**Issue by tudorfarcas2002** [NightscoutFoundation/xDrip#806]
I have a friend to whom I installed xdrip+ on Nokia 2, Android 7.1.1 with G5.
I can't find the correct configuration of that checks in "G5 / G6 debug settings" or in "Less common settings / Bluetooth Settings".
I tried "use the OB1 Collector" but also "Native Algorithm" or "Allow OB1 initiate bonding" / unbonding.
There are many breaks in the reception but sometimes for 20-30 minutes it's ok
Please help

**Comment by tudorfarcas2002** [comment]
I noticed that there are no loss of values ​​when the phone is being used and during the night or when the phone is not in use, there are no values

**Comment by jamorham** [comment]
Which xDrip+ version are you using? Please update to the latest nightly and disable the `Minimize Scanning` option and use the `OB1 collector`

**Comment by tudorfarcas2002** [comment]
14fecb8-2019.01.10 this is the updated version of the application after i checked with "Check for updated version".
Both are already like you said: **Use the OB1 collector** is checked and **Minimize Scanning** is unchecked

**Comment by jamorham** [comment]
https://github.com/NightscoutFoundation/xDrip/wiki/How-to-get-the-Nightlies-on-Automatic-Update

**Comment by tudorfarcas2002** [comment]
Thank you for this guide.
Question: if i have some checks in actual version and i make update with the latest nightly, these check stay there or i must uninstall first and after that to download the app again?

**Comment by MasterPlexus** [comment]
@tudorfarcas2002, normally all settings should be stay as they was set by you. But it will be a good idea from time to time to made a backup of your settings.

**Comment by tudorfarcas2002** [comment]
@MasterPlexus my concern is not to keep a check mark in the wrong place

**Comment by tudorfarcas2002** [comment]
@Jamorham - thank you!!!. It is almost resolved the problem, is not perfect but is manageable. I noticed that no value was lost during a long call.

**Comment by tudorfarcas2002** [comment]
some screenshots

**Comment by tudorfarcas2002** [comment]
i want to share with you some screenshots but i cannot find a way to do that...:(

**Comment by philippebourget** [comment]
Hi, this sounds like the Nokia might be cutting the connection temporarily to save battery. I does not happen at night since I am guessing the phone is connected to a power source.  Has the nightly build fixed your issues? If not, have you tried adding xDrip to the phones battery saving exclusions?

**Comment by tudorfarcas2002** [comment]
@Philippe that was my guess too but i checked again battery settings. Nightly not entirely resolved the issue, but now is quite ok. It has only some 10min-20min interruptions , not hours like before
