### ISSUE TITLE
Nightscout follower - 5 min. delay

### ISSUE THREAD

**Issue by ireneusz-ptak** [NightscoutFoundation/xDrip#808]
Hi,
not urgent but annoying issue - while following Nightscout page you get the data between 5 and 10 minutes old. Users already found a workaround for that - set manual time on your phone 1 minute back and you get BG values 0-5 minutes old. This 1 missing record is important especially for children when the BG changes quick.

There has to be an option to fix that in xDrip+ ;)

Cheers,
Irek

**Comment by smog2002** [comment]
Hi,

i´ve installed the version 2019.04.01 and have the same issue.
The data has a delay of 5min on my HTC 10 too.
The "clock" workaround is not working for me :)

Any possibility that you can check this out? :)

**Comment by jmacikanycz** [comment]
Funny, the two year old nightwatch app does not have this issue.

**Comment by ArkonPhoenix** [comment]
I was going to submit this issue now that I am using Loop, and want faster updates. Yeah, its about 5-10 delay. Then when it does get caught up, its never caught up to now, it's always 5 minutes behind. And yes, I have a kid too, so having current numbers would be nice.

**Comment by glebivanov** [comment]
I'm experiencing the same issue. I did all sorts of experiments today thinking the problem is on the Nightscout side. But it looks like xDrip+ is pulling data with a delay, or not frequently enough.

I'm preparing to start using Loop for my kid so the lag is an issue for me.

**Comment by ltatnall** [comment]
I have the same problem so have gone back to using nightwatch instead (I use it with a 3 yr old so current data is important.) Any idea why? Is it the same for all NIGHTSCOUT followers

**Comment by glebivanov** [comment]
In the Nightwatch settings I've decreased the Dexcom Share polling interval to 15 seconds:
`BRIDGE_INTERVAL = 15000` 

This almost completely eliminated the lag. 

Alternatively, we could investigate the Nightscout Follow logic. I believe it's in [NightscoutFollow.java](https://github.com/NightscoutFoundation/xDrip/blob/master/app/src/main/java/com/eveningoutpost/dexdrip/cgm/nsfollow/NightscoutFollow.java)

**Comment by Paragulis** [comment]
I have the same problem, is there any solution for it?
thanks

**Comment by glebivanov** [comment]
Still no solution, other than decreasing`BRIDGE_INTERVAL`

It doesn't fix the problem completely though.

**Comment by ArkonPhoenix** [comment]
So we use Loop and in the latest Master Branch they came up with a
workaround/option that can send the CGM data from the Dexcom/Loop phone
directly to NS. Its been working great for us. We currently let both ways
send in data and it appears to not duplicate the data. Plus you can also
see the delay on one of the pills hover over text.

[image: image.png]

The issue/delay is with the Dexcom servers.

**Comment by ireneusz-ptak** [comment]
@glebivanov My guess is that changing grace value in https://github.com/NightscoutFoundation/xDrip/blob/992a5414adae337579d667718ca411f9fd6a6af1/app/src/main/java/com/eveningoutpost/dexdrip/cgm/nsfollow/NightscoutFollowService.java to something bigger than 10 seconds (like: Constants.SECOND_IN_MS * 30) should fix the problem.

We changed our rig to Dexcom so I'm not so motivated to test it anymore, but maybe someone else would like to volunteer?

**Comment by Luke-Ness42** [comment]
Can anyone help me by explaining how to change the bridge interal?

**Comment by Navid200** [comment]
@ireneusz-ptak Was this ever resolved?
Did you ever confirm that the, through Android settings, clocks of the master and the follower are automatically adjusted using an online time base?

**Comment by ireneusz-ptak** [comment]
@Navid200 No idea, I'm not using NS follow option anymore.

**Comment by ireneusz-ptak** [comment]
To clarify - no idea, but I helped someone on "CGM in the Cloud" group with the same problem yesterday ;)

**Comment by Navid200** [comment]
> To clarify - no idea, but I helped someone on "CGM in the Cloud" group with the same problem yesterday ;)

If there is a work-around to resolve this with xDrip as is, would you please include the steps?

**Comment by ireneusz-ptak** [comment]
It's in the first post - manually set time on your phone 1 minute back.

**Comment by Navid200** [comment]
I saw this issue once.  Eventually, we found out that the follower had its time base synchronization in Android settings disabled.
Android settings -> System -> Date & Time

Enabling that resolved the issue.
