### ISSUE TITLE
Watchface always stuck (SSW3)

### ISSUE THREAD

**Issue by Radetim** [NightscoutFoundation/xDrip#810]
I'm using xDrip+ (currently nightly 2019.02.21) together with a Sony SmartWatch 3 with xDrip watchface (the standard one). Usually my phone is collecting the readings and sending them to my watch. When activating the watch display, the watchface is almost always stuck, restarting, or going black. I get the WearOS message "xDrip Prefs. does not react, do you want to close the app?" regularly (I translated the message from German, I hope you know what I mean). When "Force wear collection" is enabled, the watchface works perfectly fine.

**Comment by kskandispersonal** [comment]
This can happen if the watch app is out-of-sync with the phone xDrip+ version.  Make sure that your watch has the same version of phone xDrip+.  You can do this either w/ adb, or with Android Wear on your phone and selecting sync all apps.  

Also, you might want to try restarting your watch when this happens to ensure all preferences are synced to your phone.  

If still having problems, try initializing the watch xDrip+ DB by selecting "Reset Wear DB" from the upper, right 3-dot menu on phone xDrip+.  This will initialize your wear DB in case there is some corrupt data.

**Comment by Radetim** [comment]
Thank you! Syncing all apps via WearOS seems to have done the trick. But I think I'll stay with wear collection anyway. So being out-of-sync did something good. ;)

**Comment by kskandispersonal** [comment]
I'll close this issue then?
