### ISSUE TITLE
can't set alarms anymore

### ISSUE THREAD

**Issue by Klaus3d3** [NightscoutFoundation/xDrip#811]
Hi, since i'm back to the master fork i have an empty alarm list with both nightlies from 23.02 and 04.03. and can't set new once.
I've tried almost everything i can think of to find a solution.
All i get when trying to set an alert is: 
"Warning! No active Low Alert exists,without this there will be no alert on low glucose! 
Please add or enable a low alert." and a still empty list.

**Comment by tzachi-dar** [comment]
Just to make sure, are you pressing save after creating the alert?

Assuming that yes, very likely there is a problem with your sqllite db.
Can you try to save your settings, restore them and try again?

If that does not help, can you try to backup your db, delete it and see if that solves the problem?
You can also try to backup it, than restore it and see if that will solve the problem.

**Comment by Klaus3d3** [comment]
I already tried all of this. Even when i setup an alarm with my old version installed...save settings.. deinstall old version...install theese new nightlies and try to restore the old settings, everything is fine (old settings are there) except the alarm list is empty again.

**Comment by MasterPlexus** [comment]
@Klaus3d3 , sorry, please incrise the extended logging tag to the following:
alarmlist:v;editalertactivity:v;alerttype:v

Alarm-Entrys are a little bit more complex that I thinked ;)

**Comment by Klaus3d3** [comment]
![screenshot_2019-03-05-15-49-31-673_com eveningoutpost dexdrip](https://user-images.githubusercontent.com/31705095/53830117-098c5180-3f82-11e9-8ad8-4c2c1dcaa373.png)
hope this helps a bit

**Comment by MasterPlexus** [comment]
Sorry, I've made a second mistake. Please use 
alarmlist:v, editalertactivity:v ,alerttype:v

The seperator is , and not ; 

Not my best day I guess ;)

**Comment by Klaus3d3** [comment]
I noticed this myself but sadly nothing popos up in the log when i try to save an alert.

I've also did a full reset including flash of a new rom of my phone, but still no success.

**Comment by Klaus3d3** [comment]
maybe this helps:

03-05 22:15:18.365 10588-10588/? E/SQLiteDatabase: Error inserting mp3_file= override_silent_mode=true end_time_minutes=1440 predictive=false active=true vibrate=true threshold=70.0 uuid=dd493d31-dc12-48f7-b996-1e616142024a default_snooze=35 volume=0 light=false minutes_between=1 above=false all_day=true name=Niedrig force_speaker=true _id=null text=null time_until_threshold_crossed=0.0 start_time_minutes=0
    android.database.sqlite.SQLiteException: table AlertType has no column named force_speaker (code 1 SQLITE_ERROR): , while compiling: INSERT INTO AlertType(mp3_file,override_silent_mode,end_time_minutes,predictive,active,vibrate,threshold,uuid,default_snooze,volume,light,minutes_between,above,all_day,name,force_speaker,_id,text,time_until_threshold_crossed,start_time_minutes) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:903)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:514)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1562)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1433)
        at com.activeandroid.Model.save(Model.java:153)
        at com.eveningoutpost.dexdrip.Models.AlertType.add_alert(AlertType.java:319)
        at com.eveningoutpost.dexdrip.EditAlertActivity$1.onClick(EditAlertActivity.java:552)
        at android.view.View.performClick(View.java:6614)
        at android.view.View.performClickInternal(View.java:6591)
        at android.view.View.access$3100(View.java:786)
        at android.view.View$PerformClick.run(View.java:25948)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
03-05 22:15:18.380 1426-5377/? D/ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{5934a3c com.eveningoutpost.dexdrip} is now in focus and seems to be in full-screen mode
03-05 22:15:18.380 1426-5377/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.eveningoutpost.dexdrip/com.eveningoutpost.dexdrip.AlertList/1603091400
03-05 22:15:18.832 1426-1522/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{3458009 u0 com.eveningoutpost.dexdrip/.AlertList t82} time:5978267
03-05 22:15:21.947 764-3660/? W/SurfaceFlinger: Attempting to set client state on removed layer: com.eveningoutpost.dexdrip/com.eveningoutpost.dexdrip.AlertList#0
03-05 22:15:21.948 764-3660/? W/SurfaceFlinger: Attempting to destroy on removed layer: com.eveningoutpost.dexdrip/com.eveningoutpost.dexdrip.AlertList#0
03-05 22:15:33.902 10588-10629/? E/DexCollectionService: Recieved a buffer after 297 seconds, starting again. already acumulated 363 bytes.
03-05 22:15:33.911 10588-10629/? E/DexCollectionService: Starting to acumulate data expectedSize = 363
03-05 22:15:33.916 10588-10629/? D/Inevitable: Creating task: dex-set-failover due: 2019-03-05 22:15:34

**Comment by MasterPlexus** [comment]
Thanks. Looks like a column is missing in the table when no entry is there
android.database.sqlite.SQLiteException: table AlertType has no column named force_speaker (code 1 SQLITE_ERROR):

Will check that tomorrow (or maybe @tzachi-dar ;) )

**Comment by jamorham** [comment]
I think `AlertType.fixUpTable()` must be missing from `IdempotentMigrations` so the schema isn't properly set up before attempts are made to write the data.  I can add this for the next nightly.

**Comment by Klaus3d3** [comment]
This sounds promissing. But...am i the only one?

**Comment by jamorham** [comment]
This should be resolved in the March 7th nightly. @Klaus3d3 you are probably not the only one so thanks for noticing the issue!!

**Comment by Klaus3d3** [comment]
Hi, yes its working again. Thanks all.
