### ISSUE TITLE
Dexcom Follow Upload

### ISSUE THREAD

**Issue by doc77** [NightscoutFoundation/xDrip#814]
Would it be possible to include carbs and insulin treatments in the Dexcom Follow upload? Although they can't be tracked in Follow, I think this information could be utilized in sugarmate.io

**Comment by kskandispersonal** [comment]
Dexcom Share does not seem to have an API to post data events for carbs, insulin, etc.

[Dexcom Share API](https://github.com/nightscout/share2nightscout-bridge/issues/15)

**Comment by Navid200** [comment]
@doc77 Would you please close this if you are happy with the response?
Otherwise, would you please update?
Thanks
