### ISSUE TITLE
please some suggestions or solution for wrong readings

### ISSUE THREAD

**Issue by jo1st** [NightscoutFoundation/xDrip#818]
I really need some help and possible suggestions, solutions. 
Currently using xdrip with miaomiao on international libre 14 days on a note 9 android version 9. Latest stable release as pushed by automatic updates. Everything was fine until 2 sensors ago. Now levels are totally wrongly reported, differences of over 100 between blood, libre scanner and xdrip. Did not change no settings.
Should I reset (data and cache) xdrip??? Re install?? Calibration is done as usually twice at beginning and every 12 hours possibly during flat state but now I have to calibrate way more often specially because I have to check my real levels since this discrepancy started. Please help. Could it be MiaoMiao???

**Comment by tzachi-dar** [comment]
Can you post calibration graph and calibration database?

בתאריך יום ו׳, 8 במרץ 2019, 04:19, מאת Gian ‏<notifications@github.com>:

**Comment by jo1st** [comment]
database is under export database on the right menu?

**Comment by jo1st** [comment]
ATTACHED
![screenshot_20190308-195011_xdrip](https://user-images.githubusercontent.com/36887391/54027345-91719600-41e4-11e9-9ac2-e77bba8816a2.jpg)

**Comment by jo1st** [comment]
[export20190308-200958.zip](https://github.com/NightscoutFoundation/xDrip/files/2945674/export20190308-200958.zip)

**Comment by tzachi-dar** [comment]
Indeed your graph does not look well.
You should have an almost straight line between the points, and you have points that are very far from the straight line.
Do you only calibrate only when bg is stable? Also, don't calibrate right after you eat.

If you do, I think that only replacing the sensor will help.

I have put a blue circle around the problematic points.
![image](https://user-images.githubusercontent.com/7942372/54033353-beaa4e00-41bc-11e9-82df-766050775b64.png)

**Comment by jo1st** [comment]
I thank you very much for your reply. I was thinking about the sensor being
defective but this is been on the last three sensor that is happening so
I'm wondering could be an upgrade gone bad? also when I scan the sensor
with the Libre scanner it's not very different from the blood test so what
can I do man?

**Comment by tzachi-dar** [comment]
I don't think that it is related to some hw or sw problem other in the sensor it self.
You need to make sure that you are calibrating only when:
1) BG is stable.
2) not after a meal.
I believe this should solve the problem.

If you still want to move to a mode without calibrations, and have results very close to the one that are received on the reader, this can also be done.
You need to install something that is called OOP algorithm from: https://drive.google.com/file/d/18zkgZq3ztNlgQZovKcE7ddO70PuawfBB/view?usp=drivesdk 
and then enable it on xdrip:
On xdrip go to setting->less common settings->other misc options-> and set out of process blukon algorithm. (If this option is disabled, this means that your version of xDrip is too old).

**Comment by jo1st** [comment]
is my version ok? it's currently unchecked but not greyed out.
only use it if moving to the different algorithm?

**Comment by jo1st** [comment]
I did install it and it seems working very well. I wanted to ask you. If I
want to go back to the way it was how do I do that?

**Comment by tzachi-dar** [comment]
To go back simply disable:
out of process libre algorithm

**Comment by jo1st** [comment]
I uploaded the screenshot of my settings. Do you mean the checkmark,
uncheck it and it will go back to the regular way? The one below that talks
about calibration it's greyed out, not possible to do that yet? Does that
mean I can use your algorithm and still do calibration on top of it? How's
that work?

**Comment by tzachi-dar** [comment]
to turn off the oop algorithm uncheck the "out of process blukon algorithm".
Calibration of the oop is probably not possible, and I was never was able to make it work reliably.

**Comment by wefink** [comment]
it seems I have a similar problem...since 2 weeks I can not trust the xdrip anymore..xdrip is jumping up and down more than 100...too bad maybe.... since the last update  to android 9?

**Comment by jo1st** [comment]
I honestly think so. just crazy recently

**Comment by tzachi-dar** [comment]
Can you post a picture of libre trend when there are the problems.

**Comment by wefink** [comment]
it is not libre..it is dex5 transmitter
![Screenshot_20190313-162519_xDrip+](https://user-images.githubusercontent.com/13422335/54313075-ddd72000-45ae-11e9-86e8-2bcbfc2a50ff.jpg)

**Comment by wefink** [comment]
here the next    ...some minutes later
![Screenshot_20190313-164436_xDrip+](https://user-images.githubusercontent.com/13422335/54313417-af0d7980-45af-11e9-9978-41f2f900c3f3.jpg)

**Comment by jo1st** [comment]
I disabled the blucon calibration, restarted the phone but calibration that
I enterrd are not registered

**Comment by wefink** [comment]
same problem here...several calibrations today not accepted.....or notized...strange things.....extreme noise..changes from reading to reading 50 or more difference up and down..

**Comment by jo1st** [comment]
I hope someone I can take a look at the situation. Used to work a great for
2 years and now it's all over the place it keeps telling me low that means
I'm the 40 but eventually I just checked with my sensor scan and it was 93
and on the actually blood test it was 114 so the scanner it's working not
bad because eventually it's always a little bit behind the blood test but
it was not even that behind but xdrip is reporting low. I have to go to
back to the out of process libre algorithm unfortunately.

**Comment by jamorham** [comment]
@wefink can you try with native mode? It looks like extreme sensor noise. If that is the case I would expect native mode to report sensor failed.

Any dex users reporting this problem please also look in the status and let me know the transmitter firmware version.

**Comment by jo1st** [comment]
what about me man.?

**Comment by wefink** [comment]
firmware    1.0.4.10

**Comment by wefink** [comment]
maybe that ended working?   hwoto test it?

**Comment by wefink** [comment]
worse is, that the calibration iss not more accepted

**Comment by wefink** [comment]
very bad is, that the calibration is not accepted by the phone

**Comment by jo1st** [comment]
Guys just as a reminder I did open the thread myself so I don't mind you
helping him as well but at least someone please look into my issue, maybe
Jon?

**Comment by wefink** [comment]
hi jo1st...I think it might be helpful if you are in the same situation (as it looks for me) if you aswer his question   "Any dex users reporting this problem please also look in the status and let me know the transmitter firmware version.

**Comment by jo1st** [comment]
I'm not a Dex user dude

**Comment by wefink** [comment]
activating "native algorithm" I got no data...witout I see data, but they are not true

**Comment by jo1st** [comment]
Guys are you going to help me a little bit please? Xdrip is not working
anymore with the sensors, data is all over the place

**Comment by AdrianLxM** [comment]
Possible duplicate: https://github.com/NightscoutFoundation/xDrip/issues/521#issuecomment-407586173

**Comment by jo1st** [comment]
Yeah maybe be a duplicate but the problem still exists and it's happening
again

**Comment by wefink** [comment]
getting errormessage "rawdata security failurer"

**Comment by jo1st** [comment]
I'm going to close this tread because eventually I opened it to be helped and it became the tread of another member. at the end nobody really cared about my issue.
