### ISSUE TITLE
Is the wiki disabled?

### ISSUE THREAD

**Issue by razzintown** [NightscoutFoundation/xDrip#82]
Clicking on the Wiki tab seems to reload the code page. Is the wiki page disabled? Is there another wiki? If so, should the wiki tab redirect to that?

**Comment by jamorham** [comment]
There isn't a wiki. The only documentation is in the Documentation folder:

https://github.com/NightscoutFoundation/xDrip/tree/master/Documentation

**Comment by razzintown** [comment]
Since there is a Wiki tab regardless, can it redirect to the documentation folder?

**Comment by AdrianLxM** [comment]
I created a wiki site that simply links the documentation folder.
