### ISSUE TITLE
Critical french translations. See inside.

### ISSUE THREAD

**Issue by philippebourget** [NightscoutFoundation/xDrip#825]
I need someone to merge the pull-request #823.  Essentially, I fixed the french translation of xDrip. 

**Should be merged ASAP since the current translations bring confusion (see example below)**

| Intended ENG | Translation FR | Actual ENG Meaning of FR Translation |
|---------------|----------------|-----------------------|
|"No, keep Parakeet as is."|"Ne pas garder Parakeet comme il est"| Do **not** keep Parakeet as it is. |
|"Possible bad calibration slope, please have a glass of water, wash hands, then recalibrate in a few!"|"Possible mauvaise pente d'étalonnage, allez boire un verre, lavez-vous les mains, puis recalibrez dans quelques temps!"|[...] **have a drink** [...] (phrased as if you're offering me a beer)|
|"Scan [Dexcom] Share Barcode"|"Numériser Partager Barcode"|"Scan [verb to share] [Barcode is not a french word]"|

**and MUCH, MUCH, more.**

**Comment by tolot27** [comment]
Fixed with the next build.
