### ISSUE TITLE
Eversense sensor data reading

### ISSUE THREAD

**Issue by mauriziocasini** [NightscoutFoundation/xDrip#826]
Hi, congratulations on the program and I would like to participate in the development.
I implemented a class that reads the data provided by the patched Eversense app of BernhardRo (Esel).
My questions are:
1 - Could be this really useful? I use it and it works fine.
2 - Where i can put the start of the service when the Eversense sensor is selected in settings? At the moment the service starts with the application and i know that this is not the right way to do it but i don't find where to put the code.

Regards,
Maurizio

**Comment by Navid200** [comment]
@mauriziocasini Sorry about the delay.
Are you still interested too contribute?

**Comment by mauriziocasini** [comment]
Hi
Yes, i still interested.
At the moment, I'm using my patched app and it works well

**Comment by Navid200** [comment]
@mauriziocasini You can open a pull request if you have made an improvement to xDrip.
https://github.com/NightscoutFoundation/xDrip/pulls
Not every pull request will be merged.

If you have a question for the developers or need guidance, please post in the Gitter room and ask for help:
https://gitter.im/jamorham/xDrip-plus

We would like to dedicate the issues platform to user issues and feature requests.
I hope you don't mind my closing this.  We can reopen it if needed.  Please let me know if you think it should remain open.
