### ISSUE TITLE
ASUS Zenwatch2 patching failure

### ISSUE THREAD

**Issue by tudorfarcas2002** [NightscoutFoundation/xDrip#829]
@jamorham 
Hello Jon
First of all, I want to THANK YOU for ALL your extraordinary work!!!
I have an Asus Zenwatch2 watch that I want to use as a collector. I followed all the steps you described in the patching procedure (I was very careful about everything you described).All the steps were ok, each verification point was ok.
However, when I want to connect the watch with Wear OS,what seems curious, there are two ASUS watches on the phone, both with the same name. I selected first one - unsuccessfully, then reset, forget, restart both and connect on the second one.
In both cases it starts to take the data from watch up to 90%, and it does not move anymore.
I wanted to check if bluetooth is active on the clock (which is obviously ok since the phone sees the clock) but there is no BT menu, just WIFI and other settings (accessibility, font, brightness, media volume, disconnect&reset, power off.
I reset the clock again - nothing, so I've rebuilt the patching process. Here I noticed:
*ERROR: could not patch BT!*
*Demigod mode enabled!*
First attempt was ok.

I know you said it was risky, I just wonder, am I still having a chance to recover my watch or make it work as a collector?

**Comment by svirito4ka** [comment]
You can try to find the stock ROM and flash it on your watcn, then patch again. Search [here](
https://forum.xda-developers.com/).

**Comment by tudorfarcas2002** [comment]
@svirito4ka it works. Thank you !!!
@jamorham - also patching procedure finished and running !!! :)

**Comment by svirito4ka** [comment]
Excellent. Could you close the issue.
