### ISSUE TITLE
xdrip api-secret correct url syntax

### ISSUE THREAD

**Issue by mir3k** [NightscoutFoundation/xDrip#830]
Hello
I try to use xdrip open web service with secret.

It perfectly work without the secret.
For example:
http://127.0.0.1:17580/status.json
But whenever the secret is set the result is like this:
Authentication failed - check api-secret
secret is required 
no secret supplied

Can you simply pass the api secret key in url header ?
As I understand the api key should be pass as sha1 like the manual says for Abc: 
915858AFA2278F25527F192038108346164B47F2
For example:
http:// 915858AFA2278F25527F192038108346164B47F2@127.0.0.1:17580/status.json
But above don’t work.
Does anyone have any suggestions how the syntax should look like ?

**Comment by MasterPlexus** [comment]
Normally I would expect not to build the hash from the secret. Normally the secret itself should be placed in the link ... Anyway, take care that you did not add a space in the link (I see one in your example after the Doubleline)

**Comment by mir3k** [comment]
1. It doesn't matter if you place the sercet itself (Abc) or hash in the url it doesn't work.
2. Normally there is no space, just a typo in the example. (my mistake)
3. can someone provide a proper url how it should look like ?

**Comment by MasterPlexus** [comment]
Ok, now it looks like more clear for me. Where did you try to use the URL? The point is, that the tool (for example the smartwatches whatchface) needs the ability how to send the header back to the Webinterface of xdrip.

**Comment by mir3k** [comment]
it is used on desktop pc (for example chrome browser).
I did it to watch extracted information from json in local network on my pc and it perfectly work without the api secret.
Now i want to secure it by adding the api secret, and I can’t managed to make a proper header in the browser because the syntax don’t work like it should be and I can’t find the answer in the google either.

**Comment by tzachi-dar** [comment]
Two things: not sure that it will help, but doing my best:

1) The has should be the lower case, not the upper case.
2) I'm not sure how you are sending the requests, but I have played a little bit with the nightscout, and there I had to send something like:

curl.exe -X DELETE -H "api-secret: 911eea185f5c758ac275687da8b7eab50ad720e5"  -g https://snirdr-dev.herokuapp.com/api/v1/devicestatus/5c8aed34cc32420004e029ae

So, the api secret should be part of the header.
I'm not sure how you are sending the requests, but something has to put the api-secret in the header.
And again, I have tried this with nightscout, might be different with xdrip.

**Comment by MasterPlexus** [comment]
As far as I can see in xdrip it is handled in the same way (see docu u der the link https://github.com/NightscoutFoundation/xDrip/blob/master/Documentation/technical/Local_Web_Services.md)
What you can try is to use an ajax-request with a JavaScript framework like jQuery, to set the header. But this then has to be set within a HTML page/app...

**Comment by mir3k** [comment]
I was referring to that page too,
My understanding was that it can be made by simple (http syntax) where you can put your secret like login and password and it will be working.
Example: http://user:password@host...
http://apikey@host...
But is doesn’t work.

**Comment by MasterPlexus** [comment]
Unfortunately it will not work, because an Api-secret is not an authorisation protocol which could be handled directly in the browser .. so you need a layer in between, which set the header in the right way (I did not know up to now a other way).

Anyway, did you have a nightscout instance? If not, you could try https://ns.10be.de which provides an easy setup for that, and you will have an secure access to your data from every internet PC/mobile...

**Comment by mir3k** [comment]
i will check it thankyou

**Comment by dinizmauricio** [comment]
@mir3k, Did you manage to complete the work? I want to send the amount of carbohydrates to Xdrip via webservice and I can't because it needs to be authenticated.

**Comment by mir3k** [comment]
i did it without the autentication token, just left it open and it works until now.

**Comment by dinizmauricio** [comment]
I managed to make a query, follow the example in Python. Do you know how I can make a post?


`import requests

myHash='d018020ba8f49a010afdbabf7e8be89551085750'
header1 = {'api-secret': myHash}

resposta = requests.get('http://192.168.2.1:17580/status.json', headers=header1)
print (resposta.text)`
