### ISSUE TITLE
Amazfit Verge with NFC sensor

### ISSUE THREAD

**Issue by macinblack** [NightscoutFoundation/xDrip#831]
Hello everyone, I researched for the first time about Xdrip and I'm interested in using it with a smartwatch. I see that Amazfit devices are supported by Xdrip, but the new Amazfit Verge isn't included yet on list. This device have a affordable price and have a NFC Sensor, looks almost perfect to do this job. It will be supported in a near future? Thanks!

**Comment by dimis28** [comment]
http://s.click.aliexpress.com/e/biTg9H9W

**Comment by Klaus3d3** [comment]
Sorry i don't have a Verge, so i can't test it.

NFC is also not relevant. The servicec for the amazfit watches only sends the data to a watchface and sends alarms. Nothing more. XDrip itself needs to run on the phone.

**Comment by 1immortal** [comment]
The US global model doesn't support NFC, only the Chinese one.

**Comment by Navid200** [comment]
@macinblack Would you please update your request considering that it has been almost 2 years?
Thanks

**Comment by 1immortal** [comment]
this can be closed, as Verge is near EOL, and the global version does not support NFC nor the CN one for this purpose.
