### ISSUE TITLE
Wear OS Graph Complication Feature Request/Discussion

### ISSUE THREAD

**Issue by ahaverty** [NightscoutFoundation/xDrip#836]
I've been using the xDrip watch faces for a while, but feel like I'm missing out on some of the other wear os complications.

The main reason I've been using the xDrip watchface is for the graph to see the full trend.
Has anyone looked into making a larger graph complication to compliment the existing one?
I'm not sure of the are limitations or complexity involved with complication dev, but I could give it a shot.

I'm thinking something like this:
![image](https://user-images.githubusercontent.com/2920947/54922152-7d75a600-4eff-11e9-9ef3-0d158224ce5e.png)

**Comment by ahaverty** [comment]
Or maybe it could be an alternative to the last reading time, where you could still make out the last reading time from the graph 
![image](https://user-images.githubusercontent.com/2920947/54922693-9894e580-4f00-11e9-8bb7-e5501757e528.png)

**Comment by hellis5544** [comment]
Hi, I don't know if this has gone anywhere or not but I wholeheartedly support the idea! At the moment I am using a complication on a different watch face (not the xdrip supplied one) and if we could have a chart complication it would make everything work that much better in my opinion.

**Comment by ahaverty** [comment]
I've moved to a Garmin myself, so unfortunately I won't be making a pull request for it. Hopefully some developer sees this and also agrees!

**Comment by Navid200** [comment]
@ahaverty Can we close this considering you are not interested in it any longer?
It can still be seen even when closed.
Thanks
