### ISSUE TITLE
Chaotic readings from MiaoMiao

### ISSUE THREAD

**Issue by nathanherrmann** [NightscoutFoundation/xDrip#837]
I've been using xdrip+ with Freestyle Libre and MiaoMiao for about 2 months now.  This has happened once before, but it was right at the end of a sensor's life, so I attributed it to that.  As you can see from the screenshot, this sensor is less than 2 days old.  I should probably try to re-calibrate, but unfortunately I left my meter at home, and I'm at work.  Any thoughts on why the readings would be all over the place like this?

![Screenshot_20190325-092334](https://user-images.githubusercontent.com/13732059/54924062-e5b58f00-4ee1-11e9-8ad6-9da3d4c7226d.png)

**Comment by 17gubbar** [comment]
I have the same trouble whit dexcom g6 atm.. Maybe something changed in som nightly build?

**Comment by nathanherrmann** [comment]
It looks like the version I'm running is from January 10, 2019.

**Comment by nathanherrmann** [comment]
Well, after 2 days of this, doing lots of calibration, easing calibration data, recalibrating, I finally replaced the sensor. The new sensor has only been on for 2 hours, but so far there is no sign of this. I'm guessing it is a problem with the sensor. When I was on the medtronic system, they were usually good about replacing bad sensors, so you might want to talk to Dexcom about it, but they might refuse to help since you are using a 3rd party system.
