### ISSUE TITLE
errormessage "transmitter sent raw sensor value of "0". This is not good.

### ISSUE THREAD

**Issue by wefink** [NightscoutFoundation/xDrip#838]
what can I change or adjust?    sensor is new...Transmitter G5 firmware 1.0.4.10

**Comment by wefink** [comment]
software is last version 25.3.

**Comment by wefink** [comment]
found it..

**Comment by IselcoP** [comment]
I'm having the same problem, how did you solve it?

**Comment by vick9000** [comment]
Мне кажется, что такое сообщение говорит о том, что передатчик не может получить данные от датчика. Но проблема в самом передатчике. Т.к. после замены сенсора ошибка осталась. Кто что подскажет?
