### ISSUE TITLE
Ob1G5 state machine errors

### ISSUE THREAD

**Issue by timmy354321** [NightscoutFoundation/xDrip#839]
Followed by aggressively restarting collector due to lack of reception. 
I have been searching for a similar thread on this issue but every fourth or fifth reading from the G6 is missed and then it reconnects after another 10 or 15 minutes. I've experienced this in the latest stable build and the nightly build. I've also turned off the "use OB1 collector" option after reading other posts and it shows "bonded" but no readings. I'm using a BlackBerry keyone on android 7. I'm just trying to get reliable connectivity perhaps I'm missing something. Thank you for any input.

**Comment by Navid200** [comment]
@timmy354321 If you are not experiencing this any longer, would you please close the issue?
Thanks
