### ISSUE TITLE
Tidepool integration - upload errors

### ISSUE THREAD

**Issue by pazaan** [NightscoutFoundation/xDrip#842]
The Tidepool integration can fail with the error "400 Bad Request", leading to "stuck" uploads.

This occurs when there are invalid values in xDrip that the Tidepool servers will not accept, resulting in the 400 response (such as negative CGM values).

We need to add a data validation step before uploading to Tidepool

**Comment by pazaan** [comment]
@jamorham - you can assign this one to me :)

**Comment by imakeinterfaces** [comment]
@pazaan The way I experienced was that the first phone i enabled tidepool on had no problems whatsoever. However that phone died and i had to switch to an interim phone which experiences this problem. I also bought a third phone to replace the interim one and now that one experiences the error as well.

The problem both of them exhibit is an error saying 400, `Found Existing Remote Dataset` There's a big thread on this here https://forum.fudiabetes.org/t/xdrip-integration-with-tidepool/5653/5 I suspect this is an issue with multiple devices.

**Comment by tzachi-dar** [comment]
I have seen a case where upload fails, probably because there is a negative value on calculated_value.
Data is: 

"51926"	"51926"	"0.0"	"0.012"	"0.0"	"0.0"	"-26.6857484754007"	"0.0"	"78"	"0"	"81b473fe-70c8-48ad-869c-46b1eb93280d"		"0.0"	"0.0"	"-26.6857484754007"	"0.012"	"1"	"0"	"0"	"0.0"	"0.0"	"0.012"	"0.0"	"0.0"	"10"	"626ce774-4bd1-4488-b73e-83cd61835654"		"1256437385.0"	"1560865244888"	"2489687d-cb1c-43b3-8bec-963662f4e0de"

See the -26 there. I'll create a fix and see if it will help.
Fix has to be in ESensorGlucose

**Comment by tzachi-dar** [comment]
@pazaan I'm looking for the checks that tidepool is doing to verify the entries.
For example, i have noticed that some BG values are too small/big.
Bolus values also have some limitations. 

Can you tell me what this limitations are, so I can add them to xdrip?

**Comment by pazaan** [comment]
Thanks @tzachi-dar. I obviously haven't got around to this yet (soooo many open source projects to work on!).
You can find [Tidepool's data model documentation at the developer portal](https://developer.tidepool.org/data-model). There are a couple of models of interest for [this integration](https://github.com/NightscoutFoundation/xDrip/tree/master/app/src/main/java/com/eveningoutpost/dexdrip/tidepool): [`cbg`](http://developer.tidepool.org/data-model/device-data/types/cbg.html) (for ESensorGlucose), [`smbg`](http://developer.tidepool.org/data-model/device-data/types/smbg.html) (for EBloodGlucose), [`basal` (with `automated` subtype)](http://developer.tidepool.org/data-model/device-data/types/basal/automated.html) (for EBasal), [`bolus` (with `normal` subtype)](http://developer.tidepool.org/data-model/device-data/types/bolus/normal.html) (for EBolus) and [`wizard`](http://developer.tidepool.org/data-model/device-data/types/wizard.html) (for EWizard).

**Comment by tzachi-dar** [comment]
Thanks, this is what I was looking for. Hope to have my pr ready soon.

**Comment by tzachi-dar** [comment]
Created a fix in: https://github.com/NightscoutFoundation/xDrip/pull/983

**Comment by Navid200** [comment]
@pazaan Can we close this issue if it has been resolved?
Thanks

**Comment by pazaan** [comment]
Yep, looks good to me 👍🏻
