### ISSUE TITLE
Galaxy S8 Dexcom G5 - Android 9 - Causing Bluetooth Connection Issue 

### ISSUE THREAD

**Issue by motnu** [NightscoutFoundation/xDrip#843]
Just got the 9.0 update and it broke my Xdrip+ Connection to my G5. 

I did update to the latest code. 
I did try the "Use Scanning" - with reboot 
I did try "Force UI Thread" - with reboot 

Without any science behind it ... I don't get readings while the screen is locked/off.  I get some.... with the Xdrip app active in the foreground i do get some readings. 

I did check the battery settings but didn't see any options to change. 

**Error "Aggressively restarting collector service due to lack of reception: backoff: 300"**

Any setting advice?

**Comment by csc0tt** [comment]
I'm seeing the same issue after updating my S8 to Android 9

**Comment by motnu** [comment]
After brute force (flipping options and rebooting )  

Currently I'm collecting with the following 
- Turned off OB1 Collector 
- DeveloperOptions Bluetooth 1.3 
- Unchecked "force G5 to UI Thread" 
- Checked "Authenticate G5 before each read"  

It does drop my headphones but ...  I'll take my BS readings over headsets and speakers any day.. and of course at night, when i really need it.

**Comment by csc0tt** [comment]
I have been messing with settings today and then rebooting my phone and I think I have it working with the screen locked. I have all the same settings besides you except:

* OB1 connector is enabled
* Trust Auto-connect is disabled (under less common settings > Bluetooth)

**Comment by csc0tt** [comment]
I tried updating to the newest nightly build (April 1) last night, and it looks like I was getting data overnight with the screen locked

**Comment by Mistert1982** [comment]
I have  Lineage 16 installed. Latest apk and still no Connection
