### ISSUE TITLE
G6 not receiving data when phone locked

### ISSUE THREAD

**Issue by microcosm** [NightscoutFoundation/xDrip#844]
Using Dexcom G6 and Galaxy S9+ with Android 9.0 and xDrip+, the app receives no data after the phone has had the screen locked for a while. It *does* successfully receive data the rest of the time. Pictures and full details here:
[https://www.facebook.com/groups/cgminthecloud/permalink/2103252869795958/](https://www.facebook.com/groups/cgminthecloud/permalink/2103252869795958/)

**Comment by csc0tt** [comment]
Hey, I had this issue too with my S8 after it got yh. Android 9 update.

I updated xDrip to the nightly build from April 1 and it seems to be working with the screen lock on again.

**Comment by microcosm** [comment]
Yeah. It totally works. Thank you! \o/

**Comment by ladawareness** [comment]
Hello, I am new at this, having the same issue with Samsung S10, dexcom g5, I don't know what does it mean to update xdrip to the nightly build from April 1st

**Comment by microcosm** [comment]
You can get it here https://github.com/NightscoutFoundation/xDrip/releases
