### ISSUE TITLE
Add more than one insulin type

### ISSUE THREAD

**Issue by thevascgmdb** [NightscoutFoundation/xDrip#847]
Hi team, any chance you could add more than one insulin type to xdip? Also allow us to determine peak strength time anf amount of time it works. 
Also, can you allow us to add basal insulin and also dictate how long it works for.

**Comment by k2s** [comment]
there seams to be pull request for this see #718

**Comment by Navid200** [comment]
@thevascgmdb Would you please close this issue if it has been resolved?
Otherwise, would you please update?
Thanks

**Comment by thevascgmdb** [comment]
It is closed.. I don't know how to close it myself
