### ISSUE TITLE
Insulin sensitivity factor at different times of day

### ISSUE THREAD

**Issue by thevascgmdb** [NightscoutFoundation/xDrip#848]
Any canch you guys could create an option to allow for different Insulin sensitivity factors at different times of day?
Mornings need more Insulin and it doesn't work so well given the dawn effect

**Comment by csc0tt** [comment]
I think you can do this already. Under predictive simulation settings, select the insulin sensitivity factor, press and hold on the values and then choose "split this block in two". Then you can change the start time and the sensitivity value. Hope this helps!

**Comment by thevascgmdb** [comment]
perfect, thats it... thanks
