### ISSUE TITLE
Allow (G5) optional raw (unfiltered) plot on graph

### ISSUE THREAD

**Issue by TecMunky** [NightscoutFoundation/xDrip#85]
It would be useful for me, and possibly others, to be able to see a plot of the raw unfiltered (or filtered) data plotted on the Home Screen.  The benefit would be the ability to see trends in BG values even when normal plotted data changes due to calibration algorithms, rewriting history, or other reasons.  Ideally it should be easy to turn this extra plot off and on - possibly via an icon on the Home Screen.  The plot could also be adjusted with an offset to keep it on screen in a useful manner, and/or a scale factor, but otherwise should not be affected by changes in calibration, plugins, or other affects.

**Comment by Navid200** [comment]
@TecMunky Would you please close this issue if it has already been implemented?
Thanks

**Comment by TecMunky** [comment]
> @TecMunky Would you please close this issue if it has already been implemented?
> Thanks

To my knowledge this has not yet been implemented.
If it has, let me know.  If it will never be implemented, please close it.

**Comment by Navid200** [comment]
Sorry, I didn't mean it that way.  I was just wondering if it may have been addressed and you may have forgotten to close this.  
I find this very interesting.
I see posts, in the xDrip facebook group about G5, regularly with a light gray curve included.
Please see the attached image.
What is that light gray curve?

![1](https://user-images.githubusercontent.com/51497406/107818308-69323080-6d45-11eb-8403-b2e35995525c.jpg)

**Comment by TecMunky** [comment]
The light grey curve is the averaged fit of historical values.  When you
calibrate, those don't change, even though data points may change from the
most recent 3 hours.

The point of my request is that, after a sensor is started, and before the
first calibration, the lack of data could be an issue, and being able to
see raw data before a calibration is performed will allow a DP to take
action which is otherwise not possible, because no information is available.

As for the "G5" part, for any Dexcom sensor, or in fact ANY sensor, the raw
data before a calibration could still be useful.

**Comment by Navid200** [comment]
Let's say you wanted to implement this.  How would you show the raw values on screen considering that the units and values will be different.  There is a slope and intercept involved.  
So, you will need two different vertical axes to show both raw and calibrated values at the same time.
How would you do that?

**Comment by Navid200** [comment]
Should the request be reworded to:
 For a transmitter that sends raw data (like Dexcom G5), show pre-calibration results, with a unique color, after sensor start and before calibration, using predefined calibration constants.

The user must enter those constants after enabling the feature.  
The result will be a single curve with a different color for the periods between sensor start and calibration request.

**Comment by TecMunky** [comment]
That wording sounds good.  The default slope and intercept should be good
enough.  Frequently, my first calibration of a new sensor comes close to
the default values.

**Comment by Navid200** [comment]
As G5 is becoming an old technology now that G7 is out and as we still have not implemented this, I am going to close this.
I am sorry.

We can always reopen if this is a necessity.
