### ISSUE TITLE
Missed reading alert can't snooze or no sound 

### ISSUE THREAD

**Issue by chookchook1** [NightscoutFoundation/xDrip#850]
Our missed reading alerts don't appear with a snooze option, nor do they appear under the Snooze Alert setting when active. To combat this I unticked ' enable missed reading alert' during a sensor warm up. Now, even though it is re ticked, there's no audible alert for missed readings at all. There is a silent alert though. Other alerts work and snooze as expected. 
We are using this phone as a follower via nightscout. I can provide screen shot of setting if needed.

**Comment by Navid200** [comment]
@chookchook1 Would you please close this issue if you don't have this question any longer?
Otherwise, I suggest you post in the xDrip facebook support group.
https://www.facebook.com/groups/xDripG5
Thanks
