### ISSUE TITLE
On demand reading BG - feature request

### ISSUE THREAD

**Issue by bobhavlin** [NightscoutFoundation/xDrip#851]
Would it be possible to add an "on demand" reading button to get a value in between the regular 5 minute intervals?

Thanks!

**Comment by johanrosse** [comment]
I would like this too.
Coming from iphone and spike where this function exist, and i miss it a lot.

**Comment by codefish42** [comment]
I always miss this feature when my phone was out of range for a while (e.g. swimming) and after returning I have to wait several minutes to get a reading.

**Comment by roadman666** [comment]
also here the same. had a vacation with t1 child. Had to pull him out of water 1 minute before planned read as the feature is not available. would it possible to implement?

**Comment by syntaxerr66** [comment]
Unfortunately this isn't possible. The five minute interval is due to the Dexcom transmitter sleeping for five minutes before waking up and sending the BG. While the transmitter is sleeping, all connectivity is turned off and won't be available until the interval is over.

**Comment by Navid200** [comment]
@bobhavlin Would you please close this issue if it has been resolved?
Thanks

**Comment by bobhavlin** [comment]
> @bobhavlin Would you please close this issue if it has been resolved?
> Thanks

Yes!  I now understand the 5 min broadcast interval is due to the BLE programming on the Dexcom transmitter and cannot be changed.  Thanks!
