### ISSUE TITLE
Follower from two masters

### ISSUE THREAD

**Issue by npedrogao** [NightscoutFoundation/xDrip#861]
How can I be follower from multiple masters?

**Comment by LongboatAline** [comment]
by using the multiple data paths into xDrip. 
(sensor readout, receiving through xDrip broadcast from another program, backfilling from a nightscout instance written to by another data source)

It's getting hard to distinguish between the traces, though!
This kind of use seems to be a sideeffect so far, and not exactly recommended:

![Screenshot_20190510-102954_widget](https://user-images.githubusercontent.com/35570803/57574824-50923980-7440-11e9-887b-748016c78fe6.jpg)

The upper trace is a G6 sensor running on another phone, the lower trace is a G5 read out by this xDrip instance directly.
I'm not sure which path the G6 sensor data is taking exactly. The data source is set to G5 via BT., and the phone serving the G5 is using another nightscout instance than the phone serving the G6.
Possible candidates are: 
   * AndroidAPS on the G5-phone (read-only access to the same nightscout as the G6 phone)
   * G6 phone is configured as master, but G5 phone is not set up to use the follower as data source.

**Comment by Navid200** [comment]
@npedrogao Would you please close the issue if the problem has been addressed?
Thanks
