### ISSUE TITLE
Huawei P8 Lite XDrip+ follower - no BG readings

### ISSUE THREAD

**Issue by ikniwn** [NightscoutFoundation/xDrip#866]
Has anyone come across this?  I have checked threads and can't find an answer but I'm new to this so sorry if I have missed something obvious.

I am using a Huawei P8 lite as a follower - XDrip V. 2919.01.10 installed.  I am using Heroku.  I have the REST-API settings correct - checked with my other follower phone that works.  I can see treatments on the Huawei, but no BG data and the home screen tells me that 'no data received from master yet'.  

I have tried changing the base URL from https to http but it didn't work.

Hopefully someone has an answer!  Thanks!

**Comment by Hyuril** [comment]
Hello, it's the same story here with the last XDrip+ app. No BG readings and the Miaomiao seems connected on my Huawei P8 Lite....

**Comment by Navid200** [comment]
@ikniwn Would you please close the issue if it has been resolved?
Thanks

**Comment by ikniwn** [comment]
Fixed - i think data slow to download as started to work after leaving it alone in frustration!
