### ISSUE TITLE
Supported Bluetooth Blood Glucose Meters?

### ISSUE THREAD

**Issue by tremor** [NightscoutFoundation/xDrip#867]
Is there a complete list of all supported bluetooth blood glucose meters? I know that the Conture Next One and the OneTouch Select Plus Flex is compatible, but both use CR2032 Batteries and I hvae to replace it too often. I search for something with a LiON accu and a MicroUSB or USB-C Charging port. This is these days better to find than a pack of coincells. The Libre Freestyle 2 Reader does take bloodsugar tests and recharges over USB, but don't  exports the data via bluetooth, right?

**Comment by tremor** [comment]
Does the breuer gl 50 evo reader is supported by xdrip?

**Comment by andyrozman** [comment]
@tremor Battery for Contour One lasts for about a year... Mine is currently on 14 months...

**Comment by tremor** [comment]
@andyrozman With automatic bluetooth connection to xDrip?

**Comment by doc77** [comment]
Yes @tremor.  The Contour Next One connects to xDrip+ via Bluetooth. You have to set options for what to do with the automatically transferred readings.

**Comment by Navid200** [comment]
@tremor Would you please close this issue if your question has been answered?
There are currently 2 support channels you can use for asking questions.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
We will hopefully be able to add some documentation as well later.
Thanks

**Comment by JasonJShuler** [comment]
Where is the list? Requiring people to ask every time seems extraordinarily inefficient...

**Comment by Navid200** [comment]
@JasonJShuler 
You are more than welcome to join the group of volunteers who are maintaining xDrip.
Do you have time, and interest, to create a list and answer corresponding questions, and be criticized for being inefficient?

**Comment by JasonJShuler** [comment]
> @JasonJShuler 
> You are more than welcome to join the group of volunteers who are maintaining xDrip.
> Do you have time, and interest, to create a list and answer corresponding questions, and be criticized for being inefficient?

I'm willing to setup a wiki page about it, but how would I find out so I could make such a list? Happy to peruse code...

**Comment by JasonJShuler** [comment]
> xDrip implements the Generic Attribute Profile (GATT) for blood glucose meters (BGM), at least partially. Hence, every BGM should be supported if they implement the BGM GATT as well - so far the theory. In practice, not every BGM implementing this GATT works as expected. For instance, the [FORA 6 Connect](https://foracare.com/multi-functional-monitoring-system/6-connect-multi-functional-monitoring-system) does not work, but I'm working on supporting it.

Thanks! Is this the only protocol / profile currently implemented? That is, there aren't any other device-specific implementations?

I'll try to do some research, and if you like I can make a wiki page about it - if I have right to do so. If not, how would I contribute? (I don't think Github offers PRs for the wiki - but I haven't dived super deep)

Thanks again!

**Comment by Navid200** [comment]
@JasonJShuler I can answer some of your questions, if not all, if you ask them using the right channels, mentioned already at the top.

The issues platform is for bringing to the attention of the developers what needs their attention.
I am more than happy to talk to you about what we are doing for documentation and how you can help.

**Comment by Navid200** [comment]
@JasonJShuler If there is a reason you don't like the two mentioned platforms for having a conversation, I can offer you a third choice:
https://github.com/Navid200/xDrip/discussions
