### ISSUE TITLE
G6 auto-calibrate on a coded/native session

### ISSUE THREAD

**Issue by LongboatAline** [NightscoutFoundation/xDrip#873]
After a bumpy preemptive restart of a coded G6, I had to stop the G6 and restart it with its code to get it back running. (including the 2 hour delay). 
When an hour later, I took a BG-reading to calibrate a G5 still up and running on a second phone, the primary phone handling the G6 took the occasion to sabotage the code-session by sending the calibration it had picked up from the paired meter to the G6. (this is a first. so far the still active “automatic calibration" setting had never kicked in despite daily readings taken for the sake of the G5)

### Here's what happened
* sensor started 9 days ago on the Dexcom receiver using the code.
* used source wizard to get the session into xdrip after the session was running.
* preemptive restart caused xDrip and Dexcom receiver to demand calibrations.
* powered down Dexcom receiver
* stopped sensor in xDrip, waited until that event got propagated to the sensor.
* started sensor with xDrip, entered code
* an hour later: took a bg reading using a BT-coupled meter. noticed later that this caused a calibration.

### Idea
could coded sessions be excluded from the "automatic calibration" license?

**Comment by LongboatAline** [comment]
## Addendum 
even though the Dexcom Receiver does show the calibration, the sensor has been running smoothly for three days now without ever requiring me to do another calibration. 

So it seems like this is the way it's supposed to work? I had (mis-?) understood the official documentation that as soon as a G6 sensor was calibrated, it would keep asking for calibrations in order to remain in native mode. 

This doesn't seem to be the case, and looks good to me.

**Comment by LongboatAline** [comment]
Possibly related: #959

**Comment by Navid200** [comment]
@LongboatAline Do you still see a need for this?

**Comment by Navid200** [comment]
Can you explain when someone would benefit from this feature if added?
Can you see this as something that many would benefit from?

**Comment by Navid200** [comment]
If you need to reopen this issue, would you please update?
