### ISSUE TITLE
Bg Data Table

### ISSUE THREAD

**Issue by doc77** [NightscoutFoundation/xDrip#874]
When a bad reading is flagged in the Bg Data Table, would it be possible to turn the dots on the main screen graph a different color?  This would make bad readings be differentiated from valid ones.

**Comment by tolot27** [comment]
BTW: How do you flag a BG reading as bad? Manually, by changing the entry in the SQlite DB?

**Comment by doc77** [comment]
You mark it as bad in the Bg Data  Table (readings). This is still a feature request, and one that I don't imagine would be too difficult to institute.

**Comment by ARkaine2** [comment]
If leaving post here can speed up realizing this FR, then I leave it here.

**Comment by Navid200** [comment]
@ARkaine2 This feature was added more than a year ago.  
Do you have a question about it or does it not work for you or what?

**Comment by ARkaine2** [comment]
**@Navid200**

Sometimes I get "jumping" BG Data (Reading) and it makes main view vertically narrow.
I'd like to fix it.
The most logic way I see is to move certain BG Data (Reading).
But is(n't) it possible?

![photo_2022-12-29_23-00-52 с](https://user-images.githubusercontent.com/31447095/210011017-60f908b4-585a-4764-bdfd-fd5f25985cae.jpg)

**Comment by Navid200** [comment]
@ARkaine2 That was never the request.  It was to change the color.
But, your idea is interesting.
If I were you, I would open a discussions (not an issue), and we can talk about it.
I will already go ahead and ask to see what the others think about it.  Thanks

**Comment by Navid200** [comment]
@ARkaine2 There is already an open issue for this.  You can add your suggestions there:  https://github.com/NightscoutFoundation/xDrip/issues/2173

**Comment by ARkaine2** [comment]
[Navid200](https://github.com/Navid200)
:) So, should I use time buttons to force the x axis range?
Of course I'll try, but ATM it's difficult (not possible) to see/get jump BG Data (Reading), but I'm all interested.
Or NVM, then I see it later.

**Comment by Navid200** [comment]
@ARkaine2 Unless I am misunderstanding you, this is not related to the x axis.  It is related to the y axis.  And there is nothing you can do about it as is.

**Comment by ARkaine2** [comment]
[Navid200](https://github.com/Navid200), oh I got that. That's sad. :)

**Comment by ARkaine2** [comment]
[Navid200](https://github.com/Navid200)
I got that. That's sad.
If it can be realized, know, that I need that.
Thanks.
