### ISSUE TITLE
WebServer and CORS

### ISSUE THREAD

**Issue by hrii** [NightscoutFoundation/xDrip#876]
I was trying to build a custom module for Cobi.bike (https://cobi.bike/devkit) to display XDrip data
using the webServer interface of XDrip. However Cobi's browser prohibits fetching of the data from
Xdrip's server because of CORS. Would it be possible to add "Access-Control-Allow-Origin: *" to the header of the response from the server so that JS running on a browser would also be able to fetch the data?

**Comment by gitanO0** [comment]
I'm now having an issue showing data on my fitbit... Getting CORS issue as well.

**Comment by jamorham** [comment]
Yes I will add this

**Comment by jamorham** [comment]
Added in the May 18th Nightly available now

**Comment by hrii** [comment]
Seems to be working. Thanks!

**Comment by gitanO0** [comment]
On my end too.

**Comment by jamorham** [comment]
marking as resolved
