### ISSUE TITLE
Show BG graph on MIUI LockScreen

### ISSUE THREAD

**Issue by karelinoleg** [NightscoutFoundation/xDrip#879]
There is a problem on Xiaomi 6 with MIUI 10.3: it has not supported widgets on lockscreen. I have to unlock device every time I want to see BG graph. Using of xDrip widget on phone lockscreen would be a better solution for doing this. But it is not supported on MIUI.

Another solution might be to use "Number Wall on lockscreen".. but... terrible MIUI does not support it too. It work on another devices but on device with MIUI calling WallpaperManager#setBitmap(wallpaper, null, false, WallpaperManager.FLAG_LOCK); does not have any effect without any exceptions. (with WallpaperManager.FLAG_SYSTEM it works fine. But that's not what I need).

So now I'm thinking to make BG graph displayed in collapsed notification. (Because it is impossible to expand notifications on lock screen).

**Comment by karelinoleg** [comment]
What do you think about this solution: [Pull-requets#880](https://github.com/NightscoutFoundation/xDrip/pull/880)? 
I have tried to change collapsed notification layout to enlarge image on it.

This is actual layout | New layout
------------------------- | ---------------
![Screenshot_1557956467](https://user-images.githubusercontent.com/8264069/57975912-ce27ed80-79dc-11e9-9413-7dc1ad862a9c.png) | ![Screenshot_1557956378](https://user-images.githubusercontent.com/8264069/57975914-d122de00-79dc-11e9-91cf-4ce666447885.png)

**Comment by Navid200** [comment]
@karelinoleg What is the status of this?

**Comment by karelinoleg** [comment]
It may be closed I think.
Because https://github.com/NightscoutFoundation/xDrip/pull/1101 was been merged. And that was an sufficient solution to my problem
