### ISSUE TITLE
When using DexShare or Nightscout follow, WearOS integration breaks

### ISSUE THREAD

**Issue by Arakon** [NightscoutFoundation/xDrip#882]
The native xdrip+ watch face "Circle" displays a glucose of 999 and doesn't update, and the complication shows NULL/NULL only.
This is using the nightly from the 19th of may.
Data shows correctly on the Widget and main app.

**Comment by Navid200** [comment]
@Arakon Has this been resolved?

**Comment by Navid200** [comment]
If you like to reopen this issue, would you please consult with other users to see what options or work-arounds may already be available and update this issue accordingly?
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks
