### ISSUE TITLE
Quickstart new Libre sensor with NFC reading and blucon

### ISSUE THREAD

**Issue by nsghub** [NightscoutFoundation/xDrip#884]
I usually start a new libre sensor with the Libre app 2 hours before the current one stops working. This way the new sensor can be used right away in xDrip using the NFC scan feature, because enough values are available. My normal data source is blucon.

I installed the latest nightly (190519) today and had to start a new sensor. Now my method is not working anymore, only the blucon readings are accepted. Is this behavior new and intended or was it a bug?

**Comment by gregorybel** [comment]
@jamorham could it be this due to sanity check?
@nsghub  we justr add sanity check for Blucon, might be that this is fixed in next release.
Thanks for report and you could downgrad in the meanwhile

**Comment by jamorham** [comment]
@nsghub If you look at the Event Log from the top right menu on main xDrip home screen does it have anything in it about rejecting values due to sensor serial number changes?

Did you issue the Stop/Start menu items for the sensor within xDrip when actually wishing to start using the new sensor?

**Comment by nsghub** [comment]
Yes, I stopped and startet the sensors via the menu items.

I will upload the screenshots from the log later.

**Comment by nsghub** [comment]
![Screenshot_2019-05-20-14-24-39](https://user-images.githubusercontent.com/39347827/58021762-23165180-7b0c-11e9-87a4-c0af199243c5.jpg)
![Screenshot_2019-05-20-14-24-12](https://user-images.githubusercontent.com/39347827/58021766-27db0580-7b0c-11e9-901e-5aaea4301926.jpg)
![Screenshot_2019-05-20-14-23-37](https://user-images.githubusercontent.com/39347827/58021775-2c9fb980-7b0c-11e9-85da-9118a08abb36.jpg)

**Comment by tolot27** [comment]
@nsghub Is this still relevant or did you switch to L2?

**Comment by nsghub** [comment]
It's not relevant for me anymore. I've switched to G6 ;)

07.01.2022 00:24:18 Mathias Walter ***@***.***>:
