### ISSUE TITLE
Feature request: Option to remove watch battery from Wear OS status bar.

### ISSUE THREAD

**Issue by jamespaulley** [NightscoutFoundation/xDrip#885]
Could we have the option to remove watch battery (or uploader battery) from the Wear OS status bar? For me, it's an unneeded percentage figure to scan through when I'm glancing down for my loop status.

**Comment by Navid200** [comment]
@jamespaulley Is this still the case?
Would you please consult with other users to see what options may be available?
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks

**Comment by jamespaulley** [comment]
Sorry I'm not sure if this has been fixed, I'm not using the xDrip watch face atm, started using AAPS face instead.

**Comment by Navid200** [comment]
If you don't mind, I close this now.  If you or anyone else needs this feature, we can reopen.  But, with no one actively needing it, it's best to close it to give priority to the many other open issues we still have.
