### ISSUE TITLE
Calibration Check-Ins: "No useable driver found"

### ISSUE THREAD

**Issue by TebbeUbben** [NightscoutFoundation/xDrip#89]
The Calibration Check-Ins are not working. When I click on the button, it says that the calibrations are checked-in but in the log there is appearing the message "No useable driver found".

**Comment by jamorham** [comment]
This should be resolved in the March 27th nightly by commit https://github.com/NightscoutFoundation/xDrip/commit/e0703334b06dd33248e70de1c471f82ea5147525

Thanks for reporting the issue. Please let me know if it works.

**Comment by TebbeUbben** [comment]
It's working again. Thanks!
