### ISSUE TITLE
Switch Sensor

### ISSUE THREAD

**Issue by triplem** [NightscoutFoundation/xDrip#893]
I would like to see a new Functionality "switch sensor". I do presoak my g5 sensors and after around 24 hours I usually stop the old one and start the new sensor. For this to work, I do need to type in the new Sensor Id and wait 15min to get 3 initial readings. It would be great, if I do not need to type the sensor Id and it would be better if I could start the new sensor directly without the wait period of 15mins.

**Comment by Navid200** [comment]
@triplem 
Would you please close this issue if this is not a request any longer for you?
Otherwise, would you please provide more detail?
For example, what you mean by "sensor ID" with respect to G5.
Thanks

**Comment by triplem** [comment]
Not using g5 anymore.
