### ISSUE TITLE
Disable automatic calibration during I itial calibration

### ISSUE THREAD

**Issue by triplem** [NightscoutFoundation/xDrip#894]
On starting a new sensor, and automatic calibration from contour next the initial calibration is not shown anymore but instead the normal calibration dialog appears. It would be great if the two next readings would be put into the initial calibration directly.

**Comment by triplem** [comment]
Duplicates #805.

**Comment by Navid200** [comment]
Please share your comments in the duplicate issue: https://github.com/NightscoutFoundation/xDrip/issues/805 .  I close this one then.
