### ISSUE TITLE
Not getting Temp Basals as a Nightscout Follower

### ISSUE THREAD

**Issue by ArkonPhoenix** [NightscoutFoundation/xDrip#895]
I have the "Show Basal TBR" setting checked in "Graph Settings". And we get all the other data as expected, all except for the Basal Patterns.

**Comment by tzachi-dar** [comment]
I'll send a PR soon that will solve this.

**Comment by kskandispersonal** [comment]
@tzachi-dar Will PR #868 resolve this issue also?  Graph looks great showing the basals!  Thank you!

**Comment by tolot27** [comment]
#1303 is the continuing PR.

**Comment by rustymonkey** [comment]
Hi I'm seeing this as well. 

fwiw, I'm using Xdrip+ 2020.11.27 on a Pixel 2 XL (running Android 11). Xdrip+ is configured with: Hardware data source: Nightscout follower; 'Download treatments' enabled. A separate NS client is not installed.

Xdrip+ displays BG data correctly as do carb entries/boluses, however basal rate adjustments don't show.

**Comment by Navid200** [comment]
What is the status of this?
Have you tested the latest Nightly and enabled download treatments?

**Comment by Navid200** [comment]
Please try with the latest Nightly and if the problem persists, please let me know.
