### ISSUE TITLE
Samsung s10e May patch caused constant reboots while using xdrip+

### ISSUE THREAD

**Issue by AlexanderDemko** [NightscoutFoundation/xDrip#896]
Please help ro resolve this problem. I can not use the xdrip+ on my phone. After May 24 - the phone reboots every from 1 to 10 minutes. If I stop the sensor or delete the xdrip - everything begin to work fine.
I use Dexcom G5 sensor. The Samsung s10e OS is of version: G970FXXU1ASE5/G970FOXM1ASE5/G970FXXU1ASE5

**Comment by davide1985** [comment]
I have the same problem too. I tried to reset the phone (s10 +) and install the last version of Xdrip but the problem was not solved. Tips?

**Comment by AlexanderDemko** [comment]
I've tried the latest one. Not helped.
Eventually it started to work with disabled option "Use the OB1 Collector".
I think, it is not normal. It would be nice to use the OB1 Collector.

**Comment by jmalakauskas** [comment]
I have the same issue. And on top of that, Xdrip misses readings when I disable the OB1 collector.

**Comment by AlexanderDemko** [comment]
I agree, xdrip works worse without OB1 collector.

**Comment by davide1985** [comment]
How can we solve it?

**Comment by opasha** [comment]
Have you guys tried my settings here?

https://github.com/NightscoutFoundation/xDrip/issues/891

**Comment by avr248** [comment]
I have the same issue, please help.

**Comment by davide1985** [comment]
> Have you guys tried my settings here?
> 
> #891


I tried to set xdrip with your settings. Let's see if it works. Should you install the latest patch?

**Comment by opasha** [comment]
@davide1985, I'm running the latest beta.

**Comment by davide1985** [comment]
Hi, this morning I received a new update on the samsung s10 +. Can we activate the "OB1 Collection" again

**Comment by AlexanderDemko** [comment]
> Hi, this morning I received a new update on the samsung s10 +. Can we activate the "OB1 Collection" again

Have you checked this?

**Comment by davide1985** [comment]
> > Ciao, stamattina ho ricevuto un nuovo aggiornamento sul samsung s10 +. Possiamo attivare nuovamente la "Collezione OB1"
> 
> Hai controllato questo?

After updating the smartphone, I activated the "OB1" again. Let's see if it works..

**Comment by davide1985** [comment]
Does not work. The phone has just restarted. Turn off "Ob1" again.

**Comment by olegsegal** [comment]
I'm getting the same problem with my S10e, which runs as a follower, so there is no way to disable the "OB1 collector" mode.

Really waiting for the fix!!

**Comment by jamorham** [comment]
Samsung appear to have introduced quite a significant bug this time... 
Try this: go in to xDrip settings and disable the `Samsung workarounds`

**Comment by davide1985** [comment]
Hi everyone, today I received a new update from samsung. I installed it, then tried to re-run the "OB1" and "Samsung workarounds" section and it seems to work correctly again ..

**Comment by olegsegal** [comment]
@jamorham, I can confirm that disabling "Samsung workarounds" solved the problem for me! Cheers!

Didn't receive fresh update from Samsung yet. I have SM-G9700 (Chinese version)

**Comment by Lee-S** [comment]
@olegsegal can I confirm you disabled Samsung Workarounds AND enabled OB1? I get into a reboot loop and have to factory reset, so want to check before I try.  I'm also still waiting for the Samsung update.  Thanks

**Comment by Kasi1000** [comment]
Good Morning, 
What is „Samsung Workarounds“ and where can I find it in the settings?

**Comment by AlexanderDemko** [comment]
> Good Morning,
> What is „Samsung Workarounds“ and where can I find it in the settings?

Settings - Less common settings - Other misc options - Samsung Workarounds

**Comment by AlexanderDemko** [comment]
> Samsung appear to have introduced quite a significant bug this time...
> Try this: go in to xDrip settings and disable the `Samsung workarounds`

Thanks for suggestion. It works for me.
