### ISSUE TITLE
Automatic calibration does not work in watch forced mode

### ISSUE THREAD

**Issue by haralha** [NightscoutFoundation/xDrip#897]
Automatic calibration does not seem to work when you run the collector in watch forced mode.

I use a Contour Next Cone bg-meeter that is connected to xdrip. It sends readings to xdrip and a red square shows up on phone and watch. I have enabled automatic calibration and it works when the collector runs on the phone. But when I enable forced mode automatic calibration does not seem to work anymore.

 Since I don't know how the automatic calibration algorithm work it is hard test and reproduce a situation. But I have used force collector for a week now and an automatic calibration has never happen (no circles). When I switched the collector to the phone it works perfectly.

How does the automatic calibration algorithm work? 

Is it a known problem/feature that it will not work when you run forced collector?

**Comment by etogonza** [comment]
Someone with exactly the same problem. I´ve the same bg-meter and I´m using the last nightly build (from 31st December). Please this need resolution. Thanks.

**Comment by Navid200** [comment]
@haralha Is this still a problem?

**Comment by haralha** [comment]
@Navid200 I don't know. I have moved on to Dexcom G6 and uses the native mode with no calibration at the moment.

**Comment by Navid200** [comment]
So, I close this issue.
If anyone experiences this problem, please provide details and we can reopen it.
