### ISSUE TITLE
Feature (Alarm customization) request

### ISSUE THREAD

**Issue by Navid200** [NightscoutFoundation/xDrip#905]
Hi,

This is the first time I am posting here.  I hope I have not overlooked any rules and regulations.

When I am at work, I prefer to have a discrete alarm so that the entire office does not find out that my glucose may go low in 30 minutes if I don't eat something!

On the other hand, when I am sleep, I prefer a more pronounced alarm to ensure that it wakes me up.

Constantly adjusting the volume up and down everyday is not practical.

It would be really useful if the xDrip alarms would allow me to specify two different sound files, one for one time period and the other for the rest of the day.
Say if it would let me specify one sound for 7:00 AM to 6:00 PM and a completely different sound file for the rest of the day for the same alarm.

Then, I would pick a light and short alarm sound for the period I am at the office and I would pick a different more noticeable alarm sound file for the rest of the day.

Even if you don't think this is helpful and do not add it, I would like to thank everyone who has created xDrip or has contributed to it.
What a wonderful program.

Thanks a lot

**Comment by jamorham** [comment]
I think you can already do this for level alert alarms by specifying two different alarms and choosing exclusive time periods for each and then choosing the specific sound file for each. 

Alarms like predicted low probably don't have this same flexibility.

**Comment by Navid200** [comment]
Would it be possible to add the flexibility to pick two different alarm sounds, based on the time of day, for the forecast low and persistent high alarms?

Another flexibility that has been requested for a very long time is to be able to pick 2 more thresholds for BG falling and BG rising alarms.  For those two alarms, would it be possible to increase the number of existing thresholds from 2 to 4?

**Comment by Navid200** [comment]
There are different open issues about alarms.  They are not identical requests.  But, we can categorize all of them as requests for alarm customization.

The alarms are not identical in how they are set in xDrip.  It is as if someone created a few alarms.  Later, someone else added a few more alarms but did not bother using the same template used by the first developer.
Later, another person added yet a few more alarms.
So now, we have inconsistencies and it seems that it may not be easy to add the requested features.

One request is to allow the missed reading alarm to override DND.  But, this capability already exists for the other alarms.
This request is to allow two different sound files to be used, based on the time of day, for the predicted low alarm.  But, this capability already exists for other alarms.
Another request is to add a trigger threshold to the fast rising and fast falling alarms.  But, the other alarms have trigger settings already.

Would it help if we remove all the alarms from the code and create a single module that took care of all the alarms using a unified template?

**Comment by tolot27** [comment]
Maybe the original request can be solved with Tasker. xDrip has implemented the Tasker API and with Tasker you can have different profiles based on different parameters, i. e. location.

**Comment by Navid200** [comment]
Thanks.  I will have to read up about the tasker.

But, do you think there is no reward if we make all the alarms use the same template?  Wouldn't that make it easier to maintain them?

**Comment by Navid200** [comment]
I am closing this issue.
Using the ascending volume profile addresses this issue as well.
