### ISSUE TITLE
Falling/Raising BG Falling Threshold Adjustment

### ISSUE THREAD

**Issue by Seithx** [NightscoutFoundation/xDrip#907]
Hello,

Current available threshold for Xdrip to start alerting, is either a raise or fall of 2 or 3 mgdl per reading.

Personally, I don't get any of the alerts, because the way my blood sugar raises after a meal, if I missed a shot or did not inject enough insulin for example, is lower than the threshold and I have no way of changing it.

So what happens is that my blood sugar raises steadily (for example), and I don't get any alerts until it reaches to what I defined as a high blood sugar level. 

I'm a low carber, so I don't have huge jumps, but steady raises in blood sugar, or steady decreases in blood sugar OVERTIME.

So if we could set it ourselves, or at least get a lower threshold, it will make Xdrip much much more usable for us low carbers. either 0.5 or 0.7 mgdl threshold, will improve a lot of users experience I reckon.

**Comment by Seithx** [comment]
Any comments regarding this?

**Comment by Navid200** [comment]
You can specify as many alerts for as many different levels as you wish.
You are correct that you cannot change the fast falling or fast rising alarm values other than choosing one of the two available values for each.

I am looking at the scenario you have described and and I don't understand why you cannot use additional levels to address your concern.

Let's say your high alarm is set at 7.0.  I am just picking a number here.  It can be any other value.  But, I am going to try to make a point.
You say that you get no alarm until your glucose reaches 7.0.  Why?
You can add another alarm set at 6.0 and another at 6.5.   Now, you will get 2 alarms before your blood glucose reaches 7.0.  You can add as many high alarms as you want at any value you like.

Can you please explain why you cannot do that?

**Comment by Seithx** [comment]
In theory, I can.

I also recognize its a good workaround, instead of adding extra work, though, without of course undermining what youve done so far, it sounds like it should be easy to adjust to accommodate for low carb users, needing this, since this feature is already existent. 

But, its not the same and that feature is completely unusable for me.

Also, think about the amount of false alerts I would go, since sometimes my sugar is just comfy and stable at 80 mg, so, on a day like that, I`d have to shut my alerts off for the whole day.

Or at all, since you know, blood sugar is dynamic to an extent, even for a strict low carber.

So lets say I set 80 as my HIGH alert. You say, alert when 70, alert when 65.... I`d have constant alerts. Sometimes its like, 75, 72, 80, 79.... within an hour or two....

Enabling the feature would make a whole big diff.

**Comment by Navid200** [comment]
> ... since this feature is already existent.

Would you please state where you have seen this feature?

**Comment by Seithx** [comment]
I was referring to Other Alerts, when you can choose between 2mg to 3mg rising threshold.... If we were to add a more subtle increases, the prediction model would alert me....

**Comment by Navid200** [comment]
I had misunderstood.  Thanks for clarifying.

**Comment by Navid200** [comment]
Let's say you could ask for one additional setting.  What would it be?
Now, what if you could ask for 2 more settings?  What would those be?

Would they be the same for rising and falling?

**Comment by Seithx** [comment]
If your goal is to prioritize i`d go with rising.

I detailed what would suffice here: https://github.com/NightscoutFoundation/xDrip/issues/1120#issuecomment-787106483

I think thats enough.

**Comment by Navid200** [comment]
take it you are happy with 0.1.  Great.  
No need for diagrams.

**Comment by Seithx** [comment]
Any change would be great!

Why do we need diagrams, can you elaborate?

**Comment by Navid200** [comment]
Not sure what there is to elaborate.  I typed "no need for diagrams".  
All I needed was what threshold is suggested.  You are one of several individuals who have asked for this.  I am not asking you for anything else.  And thanks for answering the question.

I hope that is clear.

**Comment by Seithx** [comment]
Sorry, mis interpreted your meaning of diagrams....

**Comment by Navid200** [comment]
@tzachi-dar 
@jamorham 
@StephenBlackWasAlreadyTaken 
@jstevensog 


The following screenshot is from values/arrays.xml.
![Screenshot 2021-03-31 132231](https://user-images.githubusercontent.com/51497406/113185363-5952ab00-9224-11eb-8cb2-b56bb64dbb62.png)

The two thresholds are items 2 and 3.
It's as if some time in the past, there was a first item and someone removed it.

Does anyone know if that ever happened and why?

**Comment by AdrianLxM** [comment]
@Navid200 usually git blame - or the git history of that file - gives you a good hint.

**Comment by Navid200** [comment]
@AdrianLxM Thank you so much.  I can clearly see when what happened now using the history.

**Comment by tzachi-dar** [comment]
I don't think there ever was a first value. I think that what we are
actually getting is the string values that are written there. Either "2"or
"3" right now.
I'm almost sure that if you will add values there, they will be used.
Obviously, you need to check for the case of an existing alert and see that
nothing was changed there.

**Comment by Navid200** [comment]
@Seithx The lower threshold, of 1, has been added.  You can test it by updating to the latest Nightly build.
https://github.com/NightscoutFoundation/xDrip/releases/tag/2021.04.06

Please report here if you discover any unexpected behavior.
Thanks
