### ISSUE TITLE
Use xDrip+ as follower for Dexcom G6

### ISSUE THREAD

**Issue by MarkusSacramento** [NightscoutFoundation/xDrip#914]
My daughter has Dexcom G6. As a follower would like to retrieve data from Dexcom Share to xDrip so that I can view her bloodsugar on a smartwatch.
I live in Europe and when I try to log in to Dex Share Follower I retrieve error that account is missing code 500.
I guess that is because we in Europe connects to another database.
Can I change what database to connect to?

**Comment by jamorham** [comment]
There is a setting option to choose whether you are using the USA or outside USA servers. It may confusingly be in the share upload section - Try that, you should be able to search preferences on Android 8 and above.

**Comment by ahaarrestad** [comment]
@MarkusSacramento I am using the dexcom share follow in EU as suggested above. works fine. but it is a bit hard to find the USA / EU button. did you find it?

**Comment by tzachi-dar** [comment]
settings->cloud upload->dexcom share server upload->Dexcom usa based account.

**Comment by Josef-A** [comment]
I also think this is confusing. But I understand that it should be the same setting for both upload and download. Could it be implemented as one place in the setting for accounts where you can fill in all settings needed for Dexcom share and then just use that account in the settings for download/upload

**Comment by tolot27** [comment]
The original issue is solved because both US and non-US servers are implemented, already. @Josef-A please open a separate issue for your feature request.

**Comment by Navid200** [comment]
@MarkusSacramento Developers have made suggestions to help you.  I hope your problem is resolved.  If not, and you would like to reopen, please respond to the suggestions first.
Thanks
