### ISSUE TITLE
Huawei watch 2 odd.180926.001

### ISSUE THREAD

**Issue by lassondes43** [NightscoutFoundation/xDrip#915]

**Comment by lassondes43** [comment]
With this firmware can we put collector or can we change the firmware! How can I proceed to make it work!

**Comment by Navid200** [comment]
@lassondes43 Have you fond an answer to your question?
If yes, would you please close this issue/
If not, you can use the support channels to see if anyone may have any suggestions.
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks

**Comment by Navid200** [comment]
If you like to reopen, please update the current status and what work-arounds exist.
Thanks
