### ISSUE TITLE
After the last update on 5/18/19 Starting new session fails "G6 Sensor failed"

### ISSUE THREAD

**Issue by TimothyGold** [NightscoutFoundation/xDrip#919]
The past 2 sensors I have tried to use the latest stable release on 5/18/19 but am unable to get the sensor to start successfully.  I always get "Encountered backfill data we don't recognize" and then the sensor shows G6 failed and then sensor session not started.  I have to revert to an older version to get the sensor to work and then it starts fine.

**Comment by TimothyGold** [comment]
Just another point - If I upgrade to the latest releases from the April release that I am on now after my sensor is successfully started it works great until I need to start a new sensor.  Starting a sensor does not work on the latest upgrades for me at all.

**Comment by apeterson22** [comment]
I'm getting the Sensor failed to start as well when restarting a sensor. Will forget device help resolve this?

**Comment by Navid200** [comment]
@TimothyGold Are you still experiencing unexpected sensor stops?
If not, would you please close the issue?
If yes, could you please post in the xDrip facebook group?
https://www.facebook.com/groups/xDripG5
Thanks
