### ISSUE TITLE
Avoid the two hour calibration after a stop/restart on the same sensor

### ISSUE THREAD

**Issue by revyTH** [NightscoutFoundation/xDrip#92]
Hi! I've just got yesterday a Dexcom G5 and I am currently testing the xDrip+ application, which is really awesome. I've started a new sensor with an iPhone running the Dexcom official app, then I've stopped the sesnor on the Dexcom app and started a new session (wearing same sensor) using the xDrip+ app on a Samsung Galaxy tablet. The xDrip application required about 20 minutes to connect to the G5 transmitter and to start to get data. Next I've stopped and restarted the sensor, for debugging purposes, from the xDrip+ app, but this time it started again the warmup process of 2 hours. Is it possible to skip the two-hours warmup phase after a stop/restart in case the sensor has not been replaced?

**Comment by jamorham** [comment]
When starting the sensor in xDrip+ it asks when the sensor was inserted. You should enter this as accurately as you can for when the actual sensor was inserted to the body. I think if that time is more than 2 hours ago then it will allow a calibration after two readings have been received.

**Comment by fastworks** [comment]
What jamorham described is consistent with what I experienced. This is my first sensor on xdrop+.

**Comment by jamorham** [comment]
I believe this is resolved.
