### ISSUE TITLE
Uploading incorrect delta to Nightscout

### ISSUE THREAD

**Issue by cascer1** [NightscoutFoundation/xDrip#920]
Originally created as https://github.com/nightscout/cgm-remote-monitor/issues/4693

**Describe the bug**
The delta reported by the nightscout API (for example `/api/v1/entries/current.json`) is different from the actual BG delta. According to @sulkaharo this is caused by xDrip uploading incorrect deltas to Nightscout.

**To Reproduce**
1. Observe delta reported by xDrip (in the xDrip app)
2. Calculate actual delta (using last two readings, should be the same as xDrip)
3. Observe delta reported by Nightscout (not API, should also be the same as xDrip)
4. Observe delta reported by API (this is often different)

**Expected behavior**
The BG delta uploaded to Nightscout should be the actual delta.

**Screenshots**
[Recording displaying discrepancy](https://i.eliens.co/1560937263212.mp4)

**Your setup information**
- Nightscout version 0.11.2-rc2-20190323
- xDrip nightly 20190530-a25cacb
- Dexcom G6

**Additional information**
This issue never occurred for me when I was using a Dexcom G5.

**Comment by dmelliott20** [comment]
did you get to the bottom of this. I'm experiencing the same issue

**Comment by cascer1** [comment]
I bought a new phone that doesn't work well with xDrip so i switched to another app.

**Comment by Navid200** [comment]
@cascer1 
>Observe delta reported by Nightscout (not API, should also be the same as xDrip)

Where is this delta, which is correct, coming from if not from xDrip?

**Comment by Navid200** [comment]
I can recreate this problem.  So, I will see if I can understand more about it and hopefully fix it.

But, the problem seems to be, at least for me, directly related to the problem reported here: https://github.com/NightscoutFoundation/xDrip/issues/691

If there is a reason this is a different matter, please explain and help me understand and I will reopen this.
Thanks for reporting.
