### ISSUE TITLE
Nightscout upload error

### ISSUE THREAD

**Issue by JimZam** [NightscoutFoundation/xDrip#922]
Good morning. Since several hours ago I'm unable to upload data to Nightscout, probably I've messed up with Back-fill and now I get this error message everytime xdrip+ tries to upload new readings:

Rejecting identical TranmitterData contraint: last ... due to 2 minutes rule this: ...

Edit: ok, the message doesn't have anything to do with Nightscout, it finally works (don't know what I have done but finally works...). Probably it is related to the 2 minutes waiting before xbridge goes to sleep, I think.
Thank you so much

**Comment by Navid200** [comment]
@JimZam Would you please close the issue as it seems the problem has been resolved?
Thanks
