### ISSUE TITLE
Phone won't receive values if watch is collector (sideloaded)

### ISSUE THREAD

**Issue by nsghub** [NightscoutFoundation/xDrip#925]
I'm using the LG Watch W100, which still runs Wear OS 1.x.
I had to reset the watch recently and now the apps do not sync to the watch automatically. This seems to be related to one of the latest Wear OS updates from Google.
So I sideloaded the xdrip wear app. The watch shows the BG values that the phone collects. But if I set the watch as collector, the phone will not receive the values from the watch (watch shows correct values).

The communication seems to be unidirectional and is only working from phone to watch. I can select the collector on the phone and the watch displays this selection. But when I select "force watch as collector" on the watch, the phone does not show this state on the status page.

Of course phone and watch are running the latest nightlies. I assume this was never really tested because there was no need to install the wear app this way.

**Comment by nsghub** [comment]
Finally the apps from the phone were synced to the watch. I also reinstalled xdrip.
Now I can change the collector from the watch and the phone acknowledges this. But the phone still shows missed readings, if the watch is the collector.

**Comment by PolarDog23** [comment]
FWIW, I have a similar situation with a Wear OS 1.x, only I can no longer get the watch to receive the app (so my watch is effectively dead as far as xDrip is concerned).  Is the situation improved at all with Wear 2.0? Does xDrip work with the newer version of the OS?

**Comment by psvtg** [comment]
Try xdrip version from 13.04.2019

**Comment by Gonzmdv** [comment]
I'm having the same problem with my Sony Smartwatch 3. Working the watch as collector, xDrip in the phone doesn't receive any glucose reading despite the watch is connected to the phone and I can open settings in the watch from the xDrip menu in the phone.

**Comment by Gonzmdv** [comment]
Today I installed latest nightly, pressed Restart Wear Database and got it fixed after running again the watch as collector.
Anyway, I haven't tried to do that with previous version.

**Comment by nsghub** [comment]
Yes, I can confirm that. Started to work again with the nightly from around Sep. 9th.

**Comment by MiglioKrajewski** [comment]
I have this same issue happening but in Version e557cba-2022.05.19

**Comment by enginemr2** [comment]
I have had the same problem. It was fixed by using an older version of xDrip, version 2021.03.08. This is a very simple xDrip change. After this change you must reset the SWR50 to the factory default values and unpair the phone from the watch. Then just use the Wear OS to again pair with the watch and closely monitor for all confirmations. 
I have also discovered that in the xDrip Debug settings you should enable 'Scan for G5 constantly'. I acknowledge that I am using the Dexcom G6.
