### ISSUE TITLE
Support for LibreAlarm using Sony Smartwatch 3

### ISSUE THREAD

**Issue by pimeys** [NightscoutFoundation/xDrip#93]
Hi,

I'm curious can I use a rooted Sony Smartwatch 3 as an NFC reader with xDrip+ as you can with LibreAlarm? I'm planning to buy one only if it's possible to attach one to a Freestyle Libre NFC chip so it could read the glucose values constantly and send them to the Android phone using Bluetooth. I'm currently using this software with Libre using the phone NFC functionality, but a nightly alarm for hypos would be more than a nice feature.

**Comment by jamorham** [comment]
Yes, you use LibreAlarm and enable the xDrip+ integration within that app and select LibreAlarm as the data source within xDrip+

**Comment by pimeys** [comment]
Yeah it works super nice!

**Comment by filipedanunes** [comment]
can you point me a good linux tutorial on how to install the nfc in my sony smartwatch 3. thx

**Comment by tzachi-dar** [comment]
https://github.com/pimpimmi/LibreAlarm/wiki
