### ISSUE TITLE
Alerts re-raise until acknowledged instead of following re-raise setting

### ISSUE THREAD

**Issue by Tank-Missile** [NightscoutFoundation/xDrip#930]
I have my high and low alerts set to re-raise every minute, but they go off until they are acknowledged. This wasn't a problem before the latest android update.

```
xDrip+ version: 14a03a7-2019.05.18

Android Version: 9
```

**Comment by Navid200** [comment]
@Tank-Missile Is this still a problem?
If yes, could you please post in the xDrip facebook group?
https://www.facebook.com/groups/xDripG5
If not, would you please close the issue?
Thanks
