### ISSUE TITLE
Feature request: Alert on stale loop/pump data in NightScout

### ISSUE THREAD

**Issue by mkitchingh** [NightscoutFoundation/xDrip#935]
Thank you for awesome app! It is a great tool for us. We use it as a client for NightScout. Daughter with T1D uses Omnipod Eros/Dexcom G6/Loop. I'm requesting a feature to alert when Loop hasn't successfully talked to the pump in X minutes. In our situation, the USB cable (yes of all things, the actual cable) charging her RileyLink died. The RileyLink eventually ran out of power in the middle of the night. NightScout raises an alert condition when this happens. If xDrip could pick up this alert from NightScout, that would be very helpful. Thank you!

**Comment by Navid200** [comment]
@mkitchingh Does this capability not exist now?

**Comment by mkitchingh** [comment]
> @mkitchingh Does this capability not exist now?

Not that I can find.

**Comment by Navid200** [comment]
@mkitchingh When this happens, do you not stop receiving readings from Nightscout?

**Comment by mkitchingh** [comment]
> @mkitchingh When this happens, do you not stop receiving readings from Nightscout?

If I quit getting readings at all or no blood sugar data, it will alarm after 20 minutes. No alerts on Loop not looping though. I have setup another method for alerting when Loop isn't looping.

**Comment by Navid200** [comment]
If xDrip is a part of the loop, it will receive readings and provide them to the pump somehow.  If this path is broken before xDrip, xDrip already has a missed readings alert that can serve to inform user that there is a break.

However, if xDrip is not a part of the loop or if break happens after xDrip, there is no way we can create an alert.

This sounds like a wishful thinking.  I don't see how we can implement this.  I am going to set this as postponed.
