### ISSUE TITLE
Unable to upgrade

### ISSUE THREAD

**Issue by yoxud** [NightscoutFoundation/xDrip#940]
Whenever I want to upgrade xdrip, I need to rebuild and reinstall it. Trying to upgrade through the app always results in an "application not installed" error even though xdrip has been granted permission to install. I have a feeling this has something to do with the signing of the apk when I build it. What is the recommended way of building it so I can update it through the app?

**Comment by MasterPlexus** [comment]
The problem.is, that your sign on the build computer is a different one then the sign of the official one. So Android think the app is a different one. You have to:
- export all settings and data in your installated app
- deinstall the app
- download the original app here from the GitHub and install it
- import the exported settings and data

After that you should be able to aktualize the app via the app internal process

**Comment by Navid200** [comment]
@yoxud Would you please close this issue if you are happy with the advice you have been given?
If not, would you please respond to it?
Thanks
