### ISSUE TITLE
Feature Suggestion: Alarm When Xdrip+ Is disconnected from Reader (Blucon, MiaoMiao etc)

### ISSUE THREAD

**Issue by Seithx** [NightscoutFoundation/xDrip#943]
Hello,

So I wanted to suggest a feature. Not really a feature, but for those of us who need to know our blood sugar levels constantly to avoid lows or highs, It's pretty important.

It doesn't happen much, but if I get my phone into flight more, and then back, Xdrip+ will not connect back to my MiaoMiao.

My suggestion is creating an alarm that if the reader cannot connect for more than 10 mins let's say, Xdrip+ will alert you that you have no signal.

Otherwise, you could be left for hours with no signal and wouldn't know about it, if you were busy or anything else, which defeats the purpose of this whole app.

**Comment by nsghub** [comment]
Just enable the "missed readings" alarm.
