### ISSUE TITLE
Huawei Watch 2 Collector + T:slim x2 connection Issues

### ISSUE THREAD

**Issue by djfye** [NightscoutFoundation/xDrip#950]
So I have the Huawei watch 2 patched with the care pack zip. Without the watch as a collector the phone and x2 get readings every 5 minutes fine. With the watch as a collector it seems the watch and x2 are fighting with each other to connect. Only one or the other will get readings at a time but not both.

**Comment by Navid200** [comment]
@djfye Would you please close this issue if it has been resolved already?
Otherwise, could you please post in the xDrip facebook support group.  There are many experienced individuals using x2 providing support.
What do you mean by "sensor ID" with respect to G5?
Thanks
