### ISSUE TITLE
Phone died, powered back on and xdrip initially worked fine but now isn't providing me with readings. 

### ISSUE THREAD

**Issue by revverbau** [NightscoutFoundation/xDrip#951]
I use xdrip with a G5 sensor on my galaxy S10, and I put in this new sensor yesterday, all was well. Last night my phone died as I forgot to charge it, so when I powered it back on it gave me a notification about all the missed readings and asked me to calibrate, but then after working with noisy readings for just under an hour, it stopped providing me with readings altogether, along with a message that "calibration rejected, sensor stopped" 
The system status page shows that the sensor status is "stopped"
Is there any way I can start the sensor again? Or will I have to put in a new sensor? 
Thanks in advance.

**Comment by revverbau** [comment]
I think its worth stating that on the status page, it says "stopped" in the sensor status bit, but it also says that it was connected every five minutes, and that the Bluetooth link is still okay with the transmitter, yet on the home screen it says "signal missed <when it stopped> minutes ago"

**Comment by Navid200** [comment]
@revverbau Would you please close this issue if the problem has been resolved?
Otherwise, could you please post in the xDrip facebook support group?
https://www.facebook.com/groups/xDripG5
Thanks
