### ISSUE TITLE
POCTech CGMS and xdrip+

### ISSUE THREAD

**Issue by irma15121966** [NightscoutFoundation/xDrip#952]
Hello evrebody.
My name is Dmitry Tretyakov.
I have type 1 diabetes since 1980 year and live in Ukraine.
Now I am testing a new Chinese system of continuous glucose monitoring (CGMS) POCTech.

I have the documentation on the data exchange protocol with the transmitter poktech.

I am very sorry that xdrip+ does not support data input from the POCTech transmitter.
Сould you help me and modify the program xdrip+ to work with the POCTech transmitter?

Yours sincere admirer Dmitry Tretyakov.

**Comment by vikotek** [comment]
Hello!
We can try to tighten it.
transcontrol37@gmail.com
Sergey

**Comment by irma15121966** [comment]
Hello Sergey.
I am very grateful to you for the answer.
Zhejiang POCTech Co., Ltd.  promised to give me the documentation on the
communication prootocol with her transmitter on 16.07.2019.
I hope they keep their promise.
As soon as the protocol documentation is in my hands, I will contact you.
I will be very grateful for your help.
Sincerely, Dmitry Tretyakov.

чт, 11 июл. 2019 г. в 14:45, vikotek <notifications@github.com>:

**Comment by emaragkos** [comment]
Hey there Dmitry, Sergey
I am also interested in connecting POCTech with xdrip+.
Do you have any news about it?

**Comment by Navid200** [comment]
What is the status of this?

**Comment by Navid200** [comment]
Duplicate: https://github.com/NightscoutFoundation/xDrip/issues/697
