### ISSUE TITLE
Alarm on G6 restart. 

### ISSUE THREAD

**Issue by JohnArm** [NightscoutFoundation/xDrip#953]
When a G6 Sensor restarts the readings can jump usually up by 2 mmol/l. This is a particular problem when running a closed loop as the system then delivers insulin to correct to the now wrong Bgs.
Is it possible to to add an option to alarm on a restart so that I can then recalibrate?

**Comment by th122** [comment]
The jump can be avoided, see #946

**Comment by Navid200** [comment]
@JohnArm Can you explain what you mean by that?
If you are restarting, you already know that you are restarting.  So, what would be the point of the alarm to notify you that you are restarting, which you already know?

**Comment by Navid200** [comment]
Perhaps you meant preemptive restart.
We cannot do that any longer with the G6 products that re in the market.  There are some old G6 devices that people are still using.  But, that will benefit only a small portion of the community.
We can always re-open this if needed.  I am closing it now as I am not sure what you need.
