### ISSUE TITLE
Entered blood test values triggers autocalibration in spite of settings

### ISSUE THREAD

**Issue by JustasM11** [NightscoutFoundation/xDrip#959]
Hello,

When I enter blood tests it is shown as circle not rectangle. I see that autocalibration is triggered in spite of settings. I use finger icon (left one) on window where threatments are entered. App asked one time, do I want to perform autocalibration using popup and I answered no.

I have nightscout heroku app connected and one nightscout follower. The same happens when followers enters blood test values.
When I try to repeat entering BG value it is not added: log says that calibration is already queued.

Please see screenshots attached.
The same settings on the follower.
I can collect and provide additional info if needed. 
![photo_2019-07-19_23-27-12 (2)](https://user-images.githubusercontent.com/12593214/61563910-d0aad000-aa7d-11e9-8aa5-22925670e573.jpg)
![photo_2019-07-19_23-27-12](https://user-images.githubusercontent.com/12593214/61563911-d1436680-aa7d-11e9-87f7-a5d171ed98c1.jpg)
![photo_2019-07-19_23-27-13](https://user-images.githubusercontent.com/12593214/61563913-d1436680-aa7d-11e9-8600-7177ae6ab329.jpg)

**Comment by Navid200** [comment]
@JustasM11 A lot has been updated since you first opened this issue.
Are you still experiencing this with more recent releases of xDrip?

**Comment by JustasM11** [comment]
Found solution: with disabled Automatic calibration and use treatment bg values: Auto it works as expected: no automatic calibration
