### ISSUE TITLE
Time based prediction values

### ISSUE THREAD

**Issue by TebbeUbben** [NightscoutFoundation/xDrip#96]
Can you a the ability to change the prediction values by time. For instance in the morning I need more bolus and correction Insulin.

**Comment by AdrianLxM** [comment]
You can long-press the setting for I:C and Sensitivity and split it... then you can have different time frames.

**Comment by jamorham** [comment]
There should also be a pop-up window when you first enter the profile editor to explain this. Did that not appear?

**Comment by TebbeUbben** [comment]
No, it did not appear.
