### ISSUE TITLE
Make poll interval choosable

### ISSUE THREAD

**Issue by sneps85** [NightscoutFoundation/xDrip#966]
As i use NightScout in combination with XDrip+ and a Medtronic 640G, i would like to have an option in XDrip to set the poll interval, as it impacts battery drain very much on my phone and i do not need to get values immediately, every 10-15 minutes should be fine.

**Comment by Navid200** [comment]
Many people charge their phones once a day.  i wonder how often you charge your phone.
If this feature would reduce the power consumption of the phone so much that it could now survive being charged only every other day, it would be a justifiable feature.
It's highly unlikely that the xDrip power requirements are that extreme.

The fact is that reducing the frequency of readings would considerably reduce the power consumption of the transmitter.  But, the impact on the receiving phone will not be significant.

Are you willing to perform an experiment?
Would you please record exactly how long it takes for your phone battery to drain from full to 10% while being used normally?
Then, uninstall xDrip and perform the same measurement.
What are the two figures?

**Comment by Navid200** [comment]
If you like to reopen this, please respond to the questions.
