### ISSUE TITLE
Which SmartWatch as a robust standalone

### ISSUE THREAD

**Issue by gibbandrew** [NightscoutFoundation/xDrip#968]
I need a simple to use (daughter 9) smartwatch, preferably waterproof (swimming) that can function as a standalone.

Our set up is _

Libre
MiaoMiao
Samsung S7
xDrip on phone

Have tried unsuccessfully to get Ticwatch E2 to work reliably.

Anyone got a similar set-up working?
Ideally I don't want to have to go delving into previous xDrip releases and advanced Bluetooth settings. I'm not clever enough and if anything disconnects I need to be able to talk my Daughter through reconnecting.

Any help appreciated.

**Comment by opasha** [comment]
You need to turn on location and sensor permissions for your e2. If not, I recommend ticwatch c2 for her. I use the Ticwatch Pro LTE, Ticwatch Pro, and LG Watch W7 flawlessly with setup. The Ticwatch Pro and LG Watch W7 I used specifically for my miaomiao/libre setup without issues. You need to go to your xdrip settings on the watch specifically and check: Enable Collector (activates the watch to take over when away from your Bluetooth of your phone), Force Collector (makes the watch the primary collector entirely independent of your phone).

**Comment by krpavlic** [comment]
What do you mean by turn on sensor permissions? I have S2 and I just didn't managed to make it work as collector. Can you give me point by pont instruction what do to (if S2 can work as standalone collector in the first place)?

Thank you!

**Comment by Navid200** [comment]
@gibbandrew Would you please use the support channels, instead of opening an issue, for asking questions?
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Would you please close this issue?
Thanks
