### ISSUE TITLE
Snooze alarm if treatment was already entered

### ISSUE THREAD

**Issue by TebbeUbben** [NightscoutFoundation/xDrip#97]
Can you please add the feature that an alarm will be snoozed if an treatment is active that will bring you back above/below threshold?

**Comment by gitanO0** [comment]
Neat idea.  Seems a tad risky but would be great to have the option.

**Comment by Navid200** [comment]
Doesn't that defeat the purpose of an alarm?
May be I am misunderstanding the request.  Are you saying if your blood glucose is dropping and you take some carbs and you enter that, you should not get an alarm if your glucose continues to drop below a set alarm value?
If yes, I definitely wouldn't want that and would never enable it.  Can you explain why you would want to enable that?

**Comment by Navid200** [comment]
You can open this if you like.  But, I suggest you add some detail to help the reader better understand what you are asking for.
