### ISSUE TITLE
xDrip - Variable for Notification Graph 

### ISSUE THREAD

**Issue by wagnefrede** [NightscoutFoundation/xDrip#988]
Hey guys 

I have a question. I would like to know which variable xdrip uses for the graph in the notification. I would like to export the graph. does anyone know anything about it? we got 2 graphs a small one at the normal notfication and the big what in extendet view. I think there could be a way to get it out of.

Thanks for your time :)
![Screenshot_20190825-234421_One_UI_Home 1](https://user-images.githubusercontent.com/45721291/63656341-c40f4b00-c792-11e9-8135-2274419621f0.jpg)
![Screenshot_20190825-234409_One_UI_Home 1](https://user-images.githubusercontent.com/45721291/63656345-d093a380-c792-11e9-98c7-47bd02d51707.jpg)

**Comment by parapenT1sta** [comment]
Has be done but never merged.

https://github.com/NightscoutFoundation/xDrip/pull/880

@jamorham

**Comment by karelinoleg** [comment]
I can rebase pull-request if there is a chance to merge it. @jamorham ?

**Comment by wagnefrede** [comment]
I want to know because I want to make a Tizen WatchFace and want to export it with autonotification and tasker. I even have export the bg-value and the delta value

**Comment by fivepointfiveish** [comment]
Interested too. I'm keen to help in any way I can on Tizen watchface. But I'm a noob in Tizen and xdrip. Just started using both

**Comment by wagnefrede** [comment]
That's not a problem :D have made 4 Watchfaces if you want to have a look :) i am Diabetic Type 1 and I have made some Watchfaces to display my Blood-Glucose Values from my Continous-Glucose-Monitoring(CGM) Sensor. Https://getwatchmaker.com/users/Bkd6tbYxr

Used some LUA scripts :)

**Comment by wagnefrede** [comment]
No one have any idea? I only need a variable or so. :(
