### ISSUE TITLE
Provide Documentation on Setup with Google App Engine

### ISSUE THREAD

**Issue by techbelle** [NightscoutFoundation/xDrip#989]

**Comment by Navid200** [comment]
@tolot27, I'm not sure how to label this.

**Comment by Navid200** [comment]
We will be adding documentation.
There are many subjects that need documentation.

**Comment by tolot27** [comment]
@techbelle What should be setup on Google App Engine? xDrip is an Android application which gets build with Gradle. If you don't want to create an environment by yourself, you can try the Makefile provided in #903 or look at [.travis.yaml](https://github.com/NightscoutFoundation/xDrip/blob/master/.travis.yml).

**Comment by techbelle** [comment]
I don't have a question about how to set it up. This is a suggestion of, _there should have documentation on how to set this up_, in case users don't want to use Heroku. I set up Nightscout on Google App Engine a couple of years ago, there were many other users asking then how to do it.

**Comment by tolot27** [comment]
But you cannot run xDrip at Google App Engine. Hence, there cannot be a documentation about it. Or I do not understand your question. Setting up [Nightscout CGM Monitor](https://github.com/nightscout/cgm-remote-monitor) at your own server or somewhere else is a totally different topic. In that case you have to ask the Nightscout community for support.

**Comment by techbelle** [comment]
ahh I see what you are saying. It did take quite a bit of effort to set up both (xDrip and Nightscout) end to end, but it's fine to keep this closed.
