### ISSUE TITLE
G5/G6 Status

### ISSUE THREAD

**Issue by AJIH** [NightscoutFoundation/xDrip#990]
Is there a list of Failed sensor?
Sensor Failed 1...                                                    Possible solutions or causes
"             "       2...                                                           "
"             "       10.                                                           "

**Comment by Navid200** [comment]
@AJIH Would you please ask your questions using the support channels?
https://www.facebook.com/groups/xDripG5
https://gitter.im/jamorham/xDrip-plus
Thanks

**Comment by Navid200** [comment]
There is also Wiki
https://github.com/NightscoutFoundation/xDrip/wiki
We are hoping to improve the documentation.

**Comment by Navid200** [comment]
Issues should be only used to report a bug or a feature request if there is no work-around.
