### ISSUE TITLE
Screensaver shows bottom bar in Android 9.0

### ISSUE THREAD

**Issue by haspden** [NightscoutFoundation/xDrip#994]
I love the screensaver be functions as well as the lock screen function however the screensaver bugs me as it keeps the very bright bottom bar which also slows down charging... See the photos and OS details too...

It's only small but holds me back from using it 24/7/365...

Thanks in anticipation

<img src="https://user-images.githubusercontent.com/4039041/64084234-17e4db80-cd21-11e9-986d-96609d499386.jpg" width="300" /><img src="https://user-images.githubusercontent.com/4039041/64084235-17e4db80-cd21-11e9-8673-de918d07bd2b.jpg" width="300" />

**Comment by haspden** [comment]
Just a quick FYI other screensaver don't show this, only the xDrip+ option 👍

**Comment by haspden** [comment]
Issue still persists on 344702e-2021.02.11

**Comment by tolot27** [comment]
@haspden What do you mean with "very bright bottom bar"?

**Comment by haspden** [comment]
Picture attached in original post - the bottom menu bar is in the picture with 3 icons on (usual android bottom bar)

**Comment by tolot27** [comment]
Okay, now I understand what you mean: navigation bar with softkeys.

**Comment by Navid200** [comment]
Cannot recreate this issue.
Please take a picture of your phone with the screen locked, instead of creating a snapshot.

**Comment by haspden** [comment]
![IMG-20210306-WA0014](https://user-images.githubusercontent.com/4039041/110219124-49f67100-7eb5-11eb-9760-df9b51729003.jpg)

Not sure why a screenshot won't work for you, but see photo...

**Comment by Navid200** [comment]
Great.
I just don't know how you take a snapshot when the phone is locked.
Anyway, that definitely shows the problem.

I don't see that.
Would you please include your phone info and Android version?

Would you get the same thing if you use any other app as your screen saver?
I mean, how do we decide if this is an xDrip issue versus a phone issue?

**Comment by haspden** [comment]
Samsung S9+ (SMG965F)
Detailed software and UI versions screenshotted

So when I use another App I have for screensaver the BBC ambiance app the bar shows for approx 2 seconds before hiding itself and just leaving the slideshow on display.

Has existed on several versions of xDrip since originally reported however build number screenshotted too

![Screenshot_20210306-205644_Settings](https://user-images.githubusercontent.com/4039041/110220596-91352f80-7ebe-11eb-9254-54fd5bc8e3c3.jpg)


![IMG-20210306-WA0021](https://user-images.githubusercontent.com/4039041/110220545-34397980-7ebe-11eb-8d2a-483e10ee6225.jpg)

![IMG-20210306-WA0022](https://user-images.githubusercontent.com/4039041/110220548-37cd0080-7ebe-11eb-9535-6e21846f12f4.jpg)

![Screenshot_20210306-205030_Settings](https://user-images.githubusercontent.com/4039041/110220445-baa18b80-7ebd-11eb-8527-69aeb0a5de70.jpg)
![Screenshot_20210306-205020_Software update](https://user-images.githubusercontent.com/4039041/110220447-bbd2b880-7ebd-11eb-9f65-a1f04e26510a.jpg)

**Comment by Navid200** [comment]
Is there a navigation bar customization option on your phone that you may have edited to make it so bright?
https://www.samsung.com/ca/support/mobile-devices/galaxy-phone-customize-the-navigation-bar/#

**Comment by Navid200** [comment]
@haspden 
We need to ensure that this is an xDrip issue and not a phone setting.
Would you please respond to my question?

**Comment by haspden** [comment]
Hi @Navid200 , sorry I've moved to a new phone now and unable to reproduce it on this phone. With the S9+ however I can confirm that I had done a factory reset to try and resolve the issue. One thing however that I've just thought about is the Day/Night Light/Dark mode setting. As this was brought in as an optional software update part way through owning the S9+ and I had it set to day mode rather than night, its possible that in night mode this would have been dark (or darker at least).

You could try reproduce this by turning off night auto mode on the android device and turning it to day mode only

Hope this helps

Henry

**Comment by tolot27** [comment]
@haspden Is/was the navigation bar also visible if you click on preview in the screensaver settings?

**Comment by Navid200** [comment]
Thanks for feedback.

I don't think the Android control panel characteristics are a part of xDrip.  I suspect this should be addressed by adjusting the behavior of the phone rather than the behavior of xDrip.

This issue can be found in searches even when it is closed.
If others experience this issue, we can always reopen.
