### ISSUE TITLE
Feature Request: Version Information in Settings

### ISSUE THREAD

**Issue by definitivequestion** [NightscoutFoundation/xDrip#998]
Ideally I'd like a section labeled "About" appearing at the bottom of the settings page listing XDrip version information and anything else that may be useful in describing issues.

**Comment by westermarck** [comment]
@definitivequestion if you go to the left side menu and select `System Status` the first tab (named `Classic Status Page`) will display the version number

**Comment by definitivequestion** [comment]
Could you maybe change "Version" to "xDrip Version" in that status page? It is kind of confusing since there are several components that could have versions.

**Comment by tolot27** [comment]
Hmm, the topmost line is the version. What exactly is confusing?

**Comment by Navid200** [comment]
@definitivequestion When you go to the system status page, you are in xDrip.  There is no other component there.  You may have other apps running at the same time on your phone.  But, not inside xDrip.

We can always reopen this issue if needed.  But, I am going to close it now and hope that xDrip serves you well.

**Comment by jimbaxter** [comment]
I do agree, it is not clear what the version relates to. The other information in that tab is about data collection, so I thought it was reading the version from the Freestyle Libre.

**Comment by Navid200** [comment]
> I do agree, it is not clear what the version relates to.

Can you post a screenshot?  
  
This is how you can find out what version of xDrip you are running:
https://navid200.github.io/xDrip/docs/xDrip-Version.html
